### ISSUE TITLE
Combine lines when removing unnecessary imports

### ISSUE THREAD

**Issue by Beliavsky** [astral-sh/ruff#10001]
I ran ruff on a code with the line

```
from pandas_util import (read_csv_date_index_multicolumn, print_first_last,
    unique_column_names_list, print_unique_column_names,
    print_stats_numeric)
```
and it said

`main.py:8:5: F401 [*] `pandas_util.unique_column_names_list` imported but unused`

Running ruff --fix main.py changed the line to

```
from pandas_util import (read_csv_date_index_multicolumn, print_first_last,
    print_unique_column_names,
    print_stats_numeric)
```
It would be slightly preferable to shorten this, giving

```
from pandas_util import (read_csv_date_index_multicolumn, print_first_last,
    print_unique_column_names, print_stats_numeric)
```

The rule could be to combine lines when doing so still gives lines less than 80 characters long.

Thanks for ruff.

**Comment by charliermarsh** [comment]
Have you tried running the formatter (`ruff format`), or the isort rules (`ruff check --fix --select I`)? Both of these should take care of reformatting the imports, but the `F401` rule is intentionally independent from that process.

**Comment by MichaReiser** [comment]
Hy @Beliavsky. I'll close this as resolved. Feel free to reopen or comment if you're still facing the issue.
