### ISSUE TITLE
Bug report: I001 not working properly

### ISSUE THREAD

**Issue by mvadari** [astral-sh/ruff#10013]
Command: `poetry run ruff format`

Code:
```
from typing import Optional
from pprint import pformat
```

isort via flake8 highlights this as an issue, because it is sorted incorrectly. But ruff doesn't seem to have any issue.

Subsection of ruff settings:
```
[tool.ruff.lint]
ignore = [
    "D205",
    "D212",
    "D415",
]
select = [
    "ANN",
    "D",
    "E",
    "F",
    "I",
    "W",
]
```

**Comment by MichaReiser** [comment]
Hy @mvadari 

Can you try running `ruff check --fix`? `isort` is a lint rule and runs as part of `ruff check` and not `ruff format`. We're aware that this is confusing but haven't yet had a chance to work on integrating the formatter into `ruff check` https://github.com/astral-sh/ruff/issues/8232

**Comment by MichaReiser** [comment]
I'm closing this since we haven't heard back. Feel free to re-open/comment if you're still encountering this issue.
