### ISSUE TITLE
(🐞) blank-line-with-whitespace (W293) fix is highly unsafe

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#10038]
```py
def test_something():
    assert foo() == """\
assert [1, 2, 3] == [1, 4, 3]
  
  At index 1 diff: 2 != 4
  Use -v to get more diff"""
```
Here, the white space on line 2 of the expected value is intentional, yet `ruff check --fix` deletes it without question.

Or is this actually a bug, and it shouldn't be applying to strings at all?

# Workaround
Disable this rule and use `ruff format` instead, as it doesn't modify the content of strings.

**Comment by dhruvmanila** [comment]
It might be an actual bug because we do mark it as unsafe inside a multiline string:

https://github.com/astral-sh/ruff/blob/3209b8545fa749c3c9dd9d37d6931d0f2ccdc26c/crates/ruff_linter/src/rules/pycodestyle/rules/trailing_whitespace.rs#L105-L113
