### ISSUE TITLE
[Infinite loop] by the rule codes E302

### ISSUE THREAD

**Issue by Fokko** [astral-sh/ruff#10034]
```
...quoting the contents of `pyiceberg/avro/decoder_fast.pyi`, the rule codes E302, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!
```

This can be easily be reproduced by:

```
git clone git@github.com:apache/iceberg-python.git
cd iceberg-python
pre-commit autoupdate
make lint
```

Ruff version v0.2.2

**Comment by MichaReiser** [comment]
Hy @Fokko . Thanks for reporting this issue. Any change that you've already updated your repository? I'm asking because I'm unable to reproduce the issue after cloning your repository and running 

```
 ruff check --select E302 --preview --fix
```

**Comment by charliermarsh** [comment]
Closing, but happy to re-open if we have a repro.
