### ISSUE TITLE
Remove rule S410

### ISSUE THREAD

**Issue by ofek** [astral-sh/ruff#10030]
See this discussion https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762

It _may_ be valid to recommend the `defusedxml` third-party package over the standard library `xml` module but the `lxml` third-party package is the de facto way to work with XML in Python and any security issues which were previously a concern have been [fixed](https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762/5) and the `defusedxml` project even [now documents](https://github.com/tiran/defusedxml/commit/a252917a0740a624ca4078b4348b52da1e14f56a) that it is safe.

**Comment by charliermarsh** [comment]
Would we need to augment the ruleset with new checks to ensure that `lxml` is being used with the appropriate defaults?

**Comment by ofek** [comment]
Based on https://github.com/tiran/defusedxml#defusedxmllxml I was thinking you could check for `etree.XMLParser(...)` without an explicit `resolve_entities=False` but actually based on the documentation https://lxml.de/apidoc/lxml.etree.html#lxml.etree.XMLParser it seems the default has been changed to be safe so I think this rule should simply be removed.

**Comment by charliermarsh** [comment]
Cool, I think we can remove it in v0.3.0.

**Comment by charliermarsh** [comment]
Doing this now.
