### ISSUE TITLE
Consider updating known rules that conflict with formatter

### ISSUE THREAD

**Issue by ofek** [astral-sh/ruff#10032]
This document https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules

I just upgraded Hatch static analysis to use the latest 0.2.2 from 0.1.9 and I think rules E301-E306 either conflict or are at least superfluous so I'm de-selecting those.

**Comment by MichaReiser** [comment]
Thanks for the feedback. These are preview rules and you're feedback on the formatter incompatibility is extremely helpful. 

We should make the rules compatible with the formatter inside of pyi files.  I'll merge this with https://github.com/astral-sh/ruff/issues/10039
