### ISSUE TITLE
`module-import-not-at-top-of-file` ignore after `os.environ`

### ISSUE THREAD

**Issue by Pastells** [astral-sh/ruff#10059]
Sometimes you need to set an environment variable before importing a package, for example:

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4" 
os.environ["WORLD_SIZE"] = "1"
import torch
```

See: https://discuss.pytorch.org/t/runtimeerror-device-0-device-num-gpus-internal-assert-failed/178118/6

My suggestion is to ignore E402 `module-import-not-at-top-of-file` if it comes after a `os.environ` statement, similar to https://github.com/astral-sh/ruff/pull/9047

**Comment by charliermarsh** [comment]
I think I agree with this. We already ignore `sys.path` manipulations, and for me this is similar.

**Comment by charliermarsh** [comment]
Added in https://github.com/astral-sh/ruff/pull/10066, though it'll be `--preview`-only until we release v0.3.0, per our versioning policy.
