### ISSUE TITLE
Suspicious lxml import (S410) misleading

### ISSUE THREAD

**Issue by stacy-rendall** [astral-sh/ruff#10068]
https://docs.astral.sh/ruff/rules/suspicious-lxml-import/#suspicious-lxml-import-s410

The above page recommends "Replace vulnerable imports with the equivalent `defusedxml` package", however the defusedxml readme states "lxml is safe against most attack scenarios. lxml uses libxml2 for parsing XML. The library has builtin mitigations against billion laughs and quadratic blowup attacks. The parser allows a limit amount of entity expansions, then fails. lxml also disables network access by default. libxml2 [lxml FAQ](https://lxml.de/FAQ.html#how-do-i-use-lxml-safely-as-a-web-service-endpoint) lists additional recommendations for safe parsing, for example counter measures against compression bombs." https://github.com/tiran/defusedxml?tab=readme-ov-file#defusedxmllxml

I.e. this error is misleading and show be removed.

**Comment by charliermarsh** [comment]
There's a bunch of discussion around this in https://github.com/astral-sh/ruff/issues/10030 👀
