### ISSUE TITLE
B006 (unsafe fix) : does not fix correctly with @overload

### ISSUE THREAD

**Issue by yoann9344** [astral-sh/ruff#10083]
```diff
     @overload
     @classmethod
     def query(
         cls,
-        my_list: list[Whatever | int] = [],
+        my_list: list[Whatever | int] | None = None,
     ) -> Whatever:
-        ...
+        if my_list is None:
+            my_list = []

     @overload
     @classmethod
     def query(
         cls,
-        my_list: list[Whatever | int] = [],
+        my_list: list[Whatever | int] | None = None,
     ) -> Whatever:
-        ...
+        if my_list is None:
+            my_list = []

     @classmethod
-    def query(cls, session, my_list=[]):
+    def query(cls, session, my_list=None):
+        if my_list is None:
+            my_list = []
```

It should not touch overloaded functions except to change the right argument :
```diff
-        my_list: list[Whatever | int] = [],
+        my_list: list[Whatever | int] | None = None,
```
But must not add logic in it : 
```diff
-        ...
+        if my_list is None:
+            my_list = []
```

So the result should look like this for overloaded methods : 
```diff
     @overload
     @classmethod
     def query(
         cls,
-        my_list: list[Whatever | int] = [],
+        my_list: list[Whatever | int] | None = None,
     ) -> Whatever:
    ...
```

NB : this overloaded method has no sens, I removed the unnecessary.

**Comment by MichaReiser** [comment]
Thanks for reporting the bug. I summarise the issue again because it took a bit to figure out what the problem was. 

The `B006` replaces the `[]` default value with `None` and inserts the 

```python
if <argument> is None:
	<argument> = []
```

as the first statement in the body which in itself is the semantically correct refactor. 

However, inserting the statement is undesired if the function has a stub body. I don't think we necessarily have to test if the function has the `@overload` signature because changing the body is also undesired in typing stub files. 

[Playground](https://play.ruff.rs/b39d8557-bce4-4506-a6b2-ebf2ed3b7c07)

**Comment by yoann9344** [comment]
> The `B006` replaces the `[]` default value with `None` and inserts the
> 
> ```python
> if <argument> is None:
> 	<argument> = []
> ```
> 
> as the first statement in the body which in itself is the semantically correct refactor.

Yes that's correct

> However, inserting the statement is undesired if the function has a stub body. I don't think we necessarily have to test if the function has the `@overload` signature because changing the body is also undesired in typing stub files.

Well see ! I think it is the best way to handle it !

> [Playground](https://play.ruff.rs/b39d8557-bce4-4506-a6b2-ebf2ed3b7c07)

<details>
<summary>
Except at the end there's not a stub body.
</summary>

```python
class Test:
    @overload
    @classmethod
    def query(
        cls,
        my_list: list[Whatever | int] = [],
    ) -> Whatever:
        ...
    
    @overload
    @classmethod
    def query(
        cls,
        my_list: list[Whatever | int] = [],
    ) -> Whatever:
        ...
    
    @classmethod
    def query(cls, session, my_list=[]):
        raise NotImplementedError("")
```

</details>

**Comment by Philipp-Thiel** [comment]
I added code that identifies all functions, where the body consists only out of a docstring, the ... literal and/or the pass keyword as a stub and doesn't modify the body then. But now that I think more about it, I also find the case where the function body only raises a NotImplementedError compelling. Should that maybe also be identified as a stub?

**Comment by charliermarsh** [comment]
@Philipp-Thiel - Sure, that seems like a reasonable extension. You can use the `SemanticModel` to identify the exception type.
