### ISSUE TITLE
Can RSE102 conflict with the celery.app.task.Task.retry() method?

### ISSUE THREAD

**Issue by cclauss** [astral-sh/ruff#10139]
[`celery.app.task.Task.retry()`](https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.retry) is a strange construction that is a method call instead of the normally expected instance of an exception. This seems to confuse [`ruff rule RSE102`](https://docs.astral.sh/ruff/rules/unnecessary-paren-on-raise-exception) unnecessary-paren-on-raise-exception if `Task.retry()` is called with no parameters.
```python
@app.task(bind=True)
def tweet(self, auth, message):
    twitter = Twitter(oauth=auth)
    try:
        twitter.post_status_update(message)
    except twitter.FailWhale:
        raise self.retry()  # noqa: RSE102
```
If we leave off the `noqa` then `ruff --fix` may remove the parens which would break Celery's `Task.retry()` logic.
```diff
-        raise self.retry()
+        raise self.retry
```
@Nusnus

**Comment by AlexWaygood** [comment]
Maybe method calls (anything that starts with `self.`?) should just be exempted from this check? I feel like it's pretty rare that `method` is going to be an exception class if you're doing `raise self.method()`

**Comment by zanieb** [comment]
Maybe we should make this fix unsafe unless it's like visibly one of the standard exception classes?

**Comment by cclauss** [comment]
I sense that `RSE102` should ignore all instances of `raise self.method()`.
