### ISSUE TITLE
Ignore autoformat in docstrings

### ISSUE THREAD

**Issue by aawilson** [astral-sh/ruff#10161]
I'd like an option to prevent ruff from changing any formatting inside of particular docstrings. This is because sometimes I desire trailing whitespace for readability that ruff wants to remove--for example, in this `ply`-based code (which implements a `yacc` parser, hence the context-free grammar syntax):

```
def p_measured_time(p):
    """measured_time :'(' time ')'
                                |'(' time ',' distance ')'
    """
    # function impl follows
```

Ruff autoformats to this (note the lack of alignment between the `:` of the first line and the `|` of the second:
```
def p_measured_time(p):
    """measured_time :'(' time ')'
    |'(' time ',' distance ')'
    """
    # function impl follows
```

If this functionality does exist somehow, then I apologize for missing it, I spent some time with https://docs.astral.sh/ruff/rules/ looking for something likely but didn't find anything.

**Comment by MichaReiser** [comment]
Hey. You can disable the formatting of individual docstring by using a formatter suppression comment. In this case, you can add a `# fmt: skip` comment after the docstring, see https://play.ruff.rs/d2cd2a6f-127b-4bf8-9609-16424079f96e

**Comment by aawilson** [comment]
And today I learned fmt: skip exists, thanks for this, I'll close the issue.
