### ISSUE TITLE
Remove the `ruff` to `ruff check` alias

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#10171]
We deprecated the `ruff` to `ruff check`, `ruff --explain` to `ruff rule`, `ruff --generate-shell-completion` to `ruff generate-shell-completion` and the `ruff --clean` to `ruff clean` aliases in 0.3. Ruff 0.5 changed the commands to error.  We should remove the aliases in an upcoming minor release.

https://github.com/astral-sh/ruff/pull/10169
https://github.com/astral-sh/ruff/pull/12011 

Note that the ruff-lsp used the `ruff` to `ruff check` alias https://github.com/astral-sh/ruff-lsp/pull/392

**Comment by MichaReiser** [comment]
https://github.com/astral-sh/ruff/pull/12011 made using any of the above commands a hard error, but we keep printing an error. We should remove the commands entirely in a future release (0.6? or 0.7?)

**Comment by charliermarsh** [comment]
So the current state is that these have a custom error, and the task here is to remove the custom errors?

**Comment by MichaReiser** [comment]
> So the current state is that these have a custom error, and the task here is to remove the custom errors?

Exactly
