### ISSUE TITLE
Invalid RUF028 for match case header

### ISSUE THREAD

**Issue by qartik** [astral-sh/ruff#10174]
[The doc](https://docs.astral.sh/ruff/formatter/#format-suppression) suggests:

> `# fmt: skip` comments suppress formatting for a preceding statement, **case header**, decorator, function definition, or class definition

but for the following use case, I get a RUF028 warning. I believe this should be acceptable.

```py
string = "hello"
match string:
    case ("C"
        | "CX"
        | "R"
        | "RX"
        | "S"
        | "SP"
        | "WAP"
        | "XX"
        | "Y"
        | "YY"
        | "YZ"
        | "Z"
        | "ZZ"
    ):  # fmt: skip
        pass
    case _:
        pass
```

```
❯ ruff --version
ruff 0.3.0
```

relevant ruff.toml setting:
```
[format]
preview = true
```

**Comment by MichaReiser** [comment]
@snowsignal would you mind taking a look at this?
