### ISSUE TITLE
[website] monospace text should include `monospace` as final fallback

### ISSUE THREAD

**Issue by WhyNotHugo** [astral-sh/ruff#10185]
This issue is about astral.sh, not ruff itself. I didn't find the repository for the website, so I hope reporting here is okay (is the website still under somebody's personal account?).

The rule for `code, kbd, pre, samp` includes:

    font-family: Roboto Mono;

This will use the default serif font as fallback on situations where this font is unavailable. Example:

![screenshot showing a code block rendered with sans serif font](https://github.com/astral-sh/ruff/assets/730811/43a07e0b-eddb-4ee7-ad8e-6fff81bc7d24)

The rule should include `monospace` as a final fallback. E.g.:

    font-family: Roboto Mono, monospace;

**Comment by charliermarsh** [comment]
Thanks! Totally fine to report here in absence of better options. (The repo is in our GitHub Org, but it's private since we often draft announcements there etc.)

**Comment by MichaReiser** [comment]
Thanks. I added `Courier New` and `monospace` as fallback fonts.

**Comment by WhyNotHugo** [comment]
Thanks!
