### ISSUE TITLE
Format selection

### ISSUE THREAD

**Issue by eljeffeg** [astral-sh/ruff#10189]
Is there a way to preserve the `indent-style`, `line-ending`, and `quote-style` while ignoring the other black formatting?

**Comment by eljeffeg** [comment]
And is there a way to ignore the formatting of isort?
This is perfectly fine, I don't want it converted to the below format (in fact, this is what we don't like about black).
```py
from ipaddress import (AddressValueError, IPv4Address, IPv4Network,
                       IPv6Address, IPv6Network, NetmaskValueError)
```
```py
from ipaddress import (
    AddressValueError,
    IPv4Address,
    IPv4Network,
    IPv6Address,
    IPv6Network,
    NetmaskValueError,
)
```

**Comment by charliermarsh** [comment]
> Is there a way to preserve the indent-style, line-ending, and quote-style while ignoring the other black formatting?

Sorry, can you say a bit more about what you mean by this? You _want_ indents and quotes to be corrected? Or you want indents and quotes to be left as-is, but other formatting to change?

> And is there a way to ignore the formatting of isort?

No, we don't expose a formatting option to ignore imports. The intent is to be compatible with Black on this front.

**Comment by eljeffeg** [comment]
Correct, I want indents and quotes to be corrected without the more aggressive black formatting.

**Comment by MichaReiser** [comment]
No, this sort of configuration isn't supported by `isort` or the formatter. 

You can give [`flake8-quotes`](https://docs.astral.sh/ruff/rules/#flake8-quotes-q) a try if all you want is to enforce a specific quote style and probably a mixture of [`pycodestyle`](https://docs.astral.sh/ruff/rules/#pycodestyle-e-w) rules to enforce indentation. I don't think there's any rule to enforce a consistent line ending
