### ISSUE TITLE
Support range in required-version setting

### ISSUE THREAD

**Issue by kujenga** [astral-sh/ruff#10192]
Currently, it appears that the `required-version` [1] setting allows just a single specific version to be specified. When a version of ruff is present that differs from this version, the ruff tool errors, preventing checks from running.

The ask here is to allow range syntax, e.g. `>=`, `~`, etc., or perhaps treat the `required-version` as a minimum similar to `target-version`, so that ruff does not fail to run in the scenario that e.g. a developer upgrades ruff in their environment but is working within a repo that wants to ensure that everyone is on some minimum version of ruff.

```
$ ruff --version
ruff 0.3.0

$ cat ruff.toml
required-version = "0.2.2"

$ ruff check ./src/example/file.py
ruff failed
  Cause: Required version `0.2.2` does not match the running version `0.3.0`
```

[1] https://docs.astral.sh/ruff/settings/#required-version

**Comment by charliermarsh** [comment]
I think it'd be reasonable to support `>=` here.

**Comment by charliermarsh** [comment]
(We just need to make it backwards-compatible such that `"0.2.2"` means `"==0.2.2"`.)

**Comment by MichaReiser** [comment]
> I think it'd be reasonable to support `>=` here.

I think we would need to support a full semver syntax similar to [package.json engines](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) or it might be surprising that e.g. `<= isn't supported which, IMO, is entirely reasonable too

**Comment by charliermarsh** [comment]
Correct, that’s what I meant — we should use Python’s PEP 440 and PEP 508 specifiers since they’re already native, standardized, used in the same TOML file, and we have parsers for them. I don’t think there needs to be any more decision-making than that, personally!

**Comment by MichaReiser** [comment]
Seems reasonable, although PEP440 is probably more flexible than what we need (local versions). PEP508 seems unrelated because we don't need a name portion.

**Comment by charliermarsh** [comment]
👍 The gist of it is: it should just function identically to `requires-python` which is a standardized field that we already parse and support (see: `crates/ruff_workspace/src/pyproject.rs`).
