### ISSUE TITLE
[proposal] Split ASYNC101 into 3 separate rules

### ISSUE THREAD

**Issue by artificial-aidan** [astral-sh/ruff#10230]
Following the request [here](https://github.com/Zac-HD/flake8-async-archive/issues/11) in the original `flake8-async` repo (which is now archived) I think breaking the 3 rules into individual rules would be beneficial.

Is this a contribution that Ruff would be open to upstreaming?

**Comment by charliermarsh** [comment]
I believe that `flake8-async` is now managed here: https://github.com/python-trio/flake8-async. All the codes were renamed to `ASYNC` so we'll likely follow suit. Do you mind filing a request on that repo? I'd prefer not to deviate without strong motivation.

**Comment by artificial-aidan** [comment]
It looks like in that repo they are already broken up into separate rules for different calls I think.
