### ISSUE TITLE
Import of annotations from __future__ incorrectly enables use of | inplace of Optional

### ISSUE THREAD

**Issue by daveisfera** [astral-sh/ruff#10232]
Here's the incorrect output:
```
test.py:6:21: UP007 Use `X | Y` for type annotations
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

Here's the minimal code to demonstrate the issue:
```
from __future__ import annotations

from typing import Optional


def test(n: int) -> Optional[int]:
    if n <= 0:
        return None

    return n
```

Here's the minimal command I can use to reproduce this:
```
ruff check --target-version py39 --select U test.py
```

**Comment by charliermarsh** [comment]
Sorry, do you mind clarifying what the problem is in the above example?

**Comment by daveisfera** [comment]
The use of `|` in typing isn't supported until Python 3.10 (see [PEP 604](https://peps.python.org/pep-0604/)) but adding `from __future__ import annotations` incorrectly enables that even thought `target-version` is set to 3.9

**Comment by charliermarsh** [comment]
It's generally fine to use `|` prior to Python 3.10 with `from __future__ import annotations`, as long as it's not used in a location that would be evaluated at runtime (e.g., `x = Optional[int]` as opposed to `x: Optional[int]`). But you can set `keep-runtime-typing = true` to disable this: https://docs.astral.sh/ruff/settings/#lint_pyupgrade_keep-runtime-typing.

**Comment by charliermarsh** [comment]
Hopefully that setting solves the problem for you, but LMK if not!

**Comment by daveisfera** [comment]
[PEP 563](https://peps.python.org/pep-0563/) defines that as delaying the evaluation of typing and I don't believe it's been extended to have a meaning beyond that
But aside from the technical details, that means that a file that has that `import` removed or code that's moved copied to a file without it would then be invalid code that would need to be moved back to the pre-3.10 style and that feels wrong/broken to me, but you're the one maintaining the code, so I'll trust your call
