### ISSUE TITLE
How to install ruff on debian if it is not packaged, and pip3 complains about "virtual environments"?

### ISSUE THREAD

**Issue by ardabro** [astral-sh/ruff#10237]
Ruff is not packaged in Debian stable repo and I'm unable to install it without creating a virtual environment, which I don't want to do, because - I suppose - in such env, I'll lose access to all other system-wide packages I use.
So: how can I use it in Debian?

    > pip3 install --user ruff
    error: externally-managed-environment
    
    × This environment is externally managed
    ╰─> To install Python packages system-wide, try apt install
        python3-xyz, where xyz is the package you are trying to
        install.

It is the same with and without `--user` switch

**Comment by charliermarsh** [comment]
Have you considered using `pipx` (https://github.com/pypa/pipx)? That would be my recommendation.

**Comment by ardabro** [comment]
> Have you considered using `pipx` (https://github.com/pypa/pipx)? That would be my recommendation.

I see... Not sure if it is going to work when I want to run it inside sublime-text plugin pylsp

**Comment by charliermarsh** [comment]
Can you share more on why this wouldn't work? In either case, Ruff will end up in your `PATH`, right?

**Comment by charliermarsh** [comment]
Ah, you need to run with `--break-system-packages` if you want to install into the system Python without a virtual environment on Debian.
