### ISSUE TITLE
VS Code duplicate code format on save

### ISSUE THREAD

**Issue by james-berkheimer** [astral-sh/ruff#10240]
When I save a file certain lines of code are duplicated.  It's usually only one line that gets duplicated and it is usually only if new code has been pasted into the file.  If I disable the Ruff extension this issue goes away.  This seems to be happening only when I paste in code into a file.

VS Code version: 1.87.0
Ruff extension version: v202414.0
Pyproject.toml settings:
```
[tool.ruff]
ignore = ["F401", "F403"]
line-length = 100
```

![vscode_ruff_issue](https://github.com/astral-sh/ruff/assets/5049386/c1e42a45-fc96-4bc0-9e8f-30dd08483497)

**Comment by charliermarsh** [comment]
Do you have the isort extension installed? It could be https://github.com/astral-sh/ruff-vscode/issues/128 which is actually an unfixed bug in VS Code itself: https://github.com/microsoft/vscode/issues/174295. The recommended fix is to either disable the isort extension _or_ disable Ruff's import organization.

**Comment by james-berkheimer** [comment]
Some more weirdness when saving.

![Code_MXXJHNJSSy](https://github.com/astral-sh/ruff/assets/5049386/3ea5287b-5580-4884-a8de-8e779cbd187e)

**Comment by james-berkheimer** [comment]
> Do you have the isort extension installed? It could be [astral-sh/ruff-vscode#128](https://github.com/astral-sh/ruff-vscode/issues/128) which is actually an unfixed bug in VS Code itself: [microsoft/vscode#174295](https://github.com/microsoft/vscode/issues/174295). The recommended fix is to either disable the isort extension _or_ disable Ruff's import organization.

I do have that extension installed it seems.  Let me disable it and see if that fixes things.

**Comment by james-berkheimer** [comment]
Yup, that seems to have fixed the issue.  Thanks Charlie!

**Comment by charliermarsh** [comment]
Sorry about that, unfortunately we have no control over it!

**Comment by james-berkheimer** [comment]
> Sorry about that, unfortunately we have no control over it!

No worries.  Having both isort and Ruff was redundant anyways.  I have no issue turning off isort in this case. :)
