### ISSUE TITLE
Improve clarity of `PT006`'s error message

### ISSUE THREAD

**Issue by trag1c** [astral-sh/ruff#10242]
I was a bit startled by this when writing tests:
```py
@pytest.mark.parametrize(
    ("types",),
#   ^^^^^^^^^^  Wrong name(s) type in `@pytest.mark.parametrize`, expected `csv`
    []
)
def test_load_config_pass(...):
    ...
```
For the first few seconds I thought it was suggesting the name `"csv"` as a param name and that this was some sort of a buggy message :smile: I decided to take a look at [PT006's page](https://docs.astral.sh/ruff/rules/pytest-parametrize-names-wrong-type/) but saw no mention of `csv` there. I then found a related [settings section](https://docs.astral.sh/ruff/settings/#lint_flake8-pytest-style_parametrize-names-type) that explained that this refers to listing parameters as a comma-separated string, but I was still a little confused.

What made me realize what this is all about was the applied autofix 😅
```diff
 @pytest.mark.parametrize(
-    ("types",),
+    "types",
     []
 )
```

I think this rule could use a more obvious error message, e.g. ``Use a string for one-parameter `@pytest.mark.parametrize`​`` :+1:

**Comment by MichaReiser** [comment]
Agree, the message could be improved. It's not clear to me what I have to do from just reading the message.

**Comment by zanieb** [comment]
I've assigned myself to this but please feel free to open a pull request if I have not fixed it yet and you're interested.
