### ISSUE TITLE
Using "ruff format" with stdin

### ISSUE THREAD

**Issue by Ga68** [astral-sh/ruff#10241]
I've started using the Zed editor and want to have ruff format my code (as I'm switching from black). I can set up Zed to format-on-save using black as follows

```
  "language_overrides": {
    "Python": {
      "preferred_line_length": 88,
      "formatter": {
        "external": {
          "command": "black",
          "arguments": ["-"]
        }
      }
    }
  }
```

but when I try to the do the same with ruff, no such luck. Trying either of two below fails to work.

```
          "command": "ruff format",
          "arguments": ["-"]
```
```
          "command": "ruff",
          "arguments": ["format", "-"]
```

**Comment by charliermarsh** [comment]
I would expect the latter to work -- any idea what error you're running into? Any trace you could share?

**Comment by dhruvmanila** [comment]
Can you share your entire config? Could it be that there's a `"format_on_save": "off"` somewhere in the global setting? Zed also allows folder specific settings so I would check those as well. Can you also share a code snippet which you're facing this problem?

**Comment by charliermarsh** [comment]
Closing now in the absence of more info, but can always re-open.
