### ISSUE TITLE
Add contact github username for ecosystem checks

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#10260]
My repo is one of the repos listed in the ecosystem checks. I would like to get automatically pinged on any PR that introduces changes resulting in new violations when linting my repo.

Context: I just upgraded ruff and got a bunch of violations due to #10238.

1) I believe there is behavior hat may be considered a bug (see #10258) which I would have pointed out had I been pinged
2) I think this change made the rule less useful (see #10259), 

I would have liked to provide this feedback on the PR, before it got merged and shipped in a release.

**Comment by zanieb** [comment]
This seems challenging to do well, but the sentiment is fair. The ecosystem checks are really for the person making changes though, they're not generally intended to be helpful to the repositories we target in them. Ideally preview mode would be providing the avenue for this kind of feedback.

**Comment by ThiefMaster** [comment]
> The ecosystem checks are really for the person making changes thoug

Sure, but why not let people whose repos are part of the ecosystem checks get 1) a heads-up about changes affecting their repos and 2) give early feedback to the contributor of such a PR.

Preview mode doesn't really help because 1) I either need to have a CI that uses bleeding-edge ruff (from master) that runs frequently enough or 2) I need to wait for a release and then discover breakage and then hope it gets fixed in the next release (and I'd skip the "bad" release)

> This seems challenging to do well

Couldn't it just add the name in the this line of the ecoystem check result comment if there's a change in violation count and contact info is available:

```
indico/indico (+39 -0 violations, +0 -0 fixes) [cc @ThiefMaster]
````

**Comment by MichaReiser** [comment]
@ThiefMaster I'm sorry for the disruption that this change has caused. In hindsight, this should have been a preview style change that would have allowed us to gather more feedback. 

> Couldn't it just add the name in the this line of the ecoystem check result comment if there's a change in violation count and contact info is available

That could work based on opt-in by maintainers. Would you be interested PRing said change to the ecosystem checks?

**Comment by zanieb** [comment]
I'm still kind of hesitant to support this. We'll discuss it further internally but I would not recommend starting work on it.

**Comment by ThiefMaster** [comment]
In any case, I wouldn't mind making a PR. But only if it'll get merged of course, not a fan of wasting my time. :)

**Comment by zanieb** [comment]
I'm sorry I just don't feel comfortable committing to providing this. We do our best to assess changes and reduce breakage for downstream projects andI want to encourage feedback and interaction but I'd prefer another way to do it.

We could look into something outside of the `ruff` repository that e.g. nightly reports changes from `ruff`'s `main` branch with preview enabled. I think something in that format makes more sense than incorporating this into pull requests which can be relatively noisy.

**Comment by charliermarsh** [comment]
I'm going to close this for now -- I think the decision above is not to support it, but open to other ideas on how we can improve ecosystem notifications.
