### ISSUE TITLE
Format breaks f-string with literal strings inside (versions 0.3.0 and 0.3.1)

### ISSUE THREAD

**Issue by mvaled** [astral-sh/ruff#10273]
The f-string in the code is broken by the formater (version 0.3.1):

```python
import re
def build(extensions):
    regex = re.compile(f"({'|'.join(extensions)})$", re.IGNORECASE)
```

```
$ cat src/bug.py
import re
def build(extensions):
    regex = re.compile(f"({'|'.join(extensions)})$", re.IGNORECASE)


$ rye run ruff --version
ruff 0.3.1

$ rye run ruff format src/bug.py                                                                                                                                         1 file reformatted

$ cat src/bug.py                                                                                                                                                                   
import re


def build(extensions):
    regex = re.compile(f"({"|".join(extensions)})$", re.IGNORECASE)
```

Note: if using `--isolated` doesn't break the f-string:

```
import re


def build(extensions):
    regex = re.compile(f"({'|'.join(extensions)})$", re.IGNORECASE)
```

My `pyproject.toml` has little configuration for the formater:

```
[tool.ruff]
required-version = "0.3.1"
line-length = 100
target-version = "py312"

[tool.ruff.lint]
preview = true
ignore = [
  "E501", # line too long
  "B011", # 'assert False' is fine.
  "E741", # do not use variables named ‘l’, ‘O’, or ‘I’
  "C901", # fn is too complex
  "ISC001",
]
select = [
  "C",
  "E",
  "F",
  "W",
  "B",
  "INT",
  "ISC",    # Implicit string concat
  "G",      # f-string, %, and format in loggers is not logger-friendly.
  "RUF008",
  "W191",   # Indentation contains tabs
  "W605",   # Invalid escape sequence
  "W291",   # Trailing whitespace
  "W292",   # No newline at end of file
  "W293",   # Blank line contains whitespace
  "SIM118", # avoid 'key in dict.keys()'
  "SIM911", # use 'for k, v in dict.items()'.
  "SIM210", # use 'bool(a)' instead of 'True if a else False'
  "SIM211", # use 'not a' instead of 'False if a else True'
  "SIM401", # use 'd.get(k, default)' instead of 'd[k] if k in d else default'
  "SIM201", # use 'a != b' instead of 'not a == b'
  "SIM202", # use 'a == b' instead of 'not a != b'
  "SIM110", # https://docs.astral.sh/ruff/rules/reimplemented-builtin/
  "SIM101", # use 'isinstance(x, (T1, T2))' instead of two checks.
]

[tool.ruff.format]
preview = true
exclude = ["**/migrations/*.py"]
```

**Comment by dhruvmanila** [comment]
Hi, thanks for providing all the necessary details regarding the issue you're facing. This is related to https://github.com/astral-sh/ruff/issues/10184.

What you're seeing is a preview style change specific to Python 3.12 (set by `target-version` in your config) which allows the formatter to re-use the same quote inside a f-string. The reason `--isolated` doesn't format it is because it ignores the config file which enables preview style.

The f-string formatting style is currently in preview and open to feedback: https://github.com/astral-sh/ruff/discussions/9785. We would appreciate if you can provide any feedback on the chosen style where the formatter can use the same quote if target version is 3.12 otherwise it would preserve the existing quote.

**Comment by MichaReiser** [comment]
@mvaled is there some tool that's telling you that the f-string is "broken" now? 

Note: This is the second time this has come up. We might want to consider flipping the quotes.

**Comment by charliermarsh** [comment]
(Just tested myself -- PyCharm doesn't flag this as invalid, perhaps other editors do though.)

**Comment by mvaled** [comment]
@charliermarsh 

You're right.  I was mistakenly using Python 3.12 which would allow this weird looking quotes inside `f"..."`.

Using `target-version = "py311"` corrects this.
