### ISSUE TITLE
Add support for string type hint in typing.Annotated

### ISSUE THREAD

**Issue by minmax** [astral-sh/ruff#10279]
String type hints used in Annotated should be imported in TYPE_CHECKING section, but ruff remove imports for now.
I think ruff should treat the first argument of Annotated similar to the current behavior for ClassVar.

```python
from types import FunctionType  # `types.FunctionType` imported but unused F401
from typing import Annotated

Func = Annotated["FunctionType", int]
```

ruff 0.3.0

**Comment by charliermarsh** [comment]
This looks like a bug, probably just an oversight...
