### ISSUE TITLE
`--fix --unsafe-fixes` that converts lambda to function (rule E731) removes underscores from numbers.

### ISSUE THREAD

**Issue by dwreeves** [astral-sh/ruff#10277]
Minimal reproduction:

```shell
echo 'at_least_one_million = lambda _: _ >= 1_000_000' > foo.py
ruff foo.py --unsafe-fixes --fix
cat foo.py
```

File:

```python
at_least_one_million = lambda _: _ >= 1_000_000
```

After fix:

```python
def at_least_one_million(_):
    return _ >= 1000000
```

Expected behavior was that it would preserve my underscores (unless another linting rule disables underscores in the number), i.e. something like this:

```python
def at_least_one_million(_):
    return _ >= 1_000_000
```

**Comment by zanieb** [comment]
@charliermarsh do we have support for retaining these in general or would we need to add that core functionality?

**Comment by charliermarsh** [comment]
@zanieb - We don't retain them in the parser / AST, only the resolved number.
