### ISSUE TITLE
`ruff format` moves `# noqa` comment to wrong location

### ISSUE THREAD

**Issue by jakob-keller** [astral-sh/ruff#10281]
I would like to switch my codebase to `ruff format`, but there is one annoying issue that breaks my use case: Some `# noqa` comments are moved resulting in issues when calling `ruff check`.

Hers's a minimal code snippet to demonstrate what happens:

```python
# test.py (original)

import typing


def foo(
    __bar: str,
    /,
    **specifiers: typing.Any,  # noqa: ANN401
) -> int:
    return len(specifiers)
```

```
$ ruff --version
ruff 0.3.1

$ ruff check --isolated --select ANN401 test.py

$ ruff format --isolated test.py
1 file reformatted
```

```python
# test.py (reformatted)

import typing


def foo(
    __bar: str,
    /,  # noqa: ANN401
    **specifiers: typing.Any,
) -> int:
    return len(specifiers)
```

```
$ ruff check --isolated --select ANN401 test.py
test.py:7:19: ANN401 Dynamically typed expressions (typing.Any) are disallowed in `**specifiers`
Found 1 error.
```

I assume this issue is an edge case that has to do with the keyword-only `/` syntax being used. Are there any workarounds available?

**Comment by charliermarsh** [comment]
Oh hmm, this looks like a bug, thanks. Will look into it. The only workaround I could think of is using `# fmt: skip` on the header for now:

```python
import typing


def foo(
    __bar: str,
    /,
    **specifiers: typing.Any,  # noqa: ANN401
) -> int:  # fmt: skip
    return len(specifiers)
```

**Comment by charliermarsh** [comment]
This is why we need a programming language that doesn't allow comments :joy:

**Comment by MichaReiser** [comment]
> This is why we need a programming language that doesn't allow comments 😂

Or an `AST` that represents `/` ;) 

FYI: This is not specific to noqa. We incorrectly associate any end-of-line comment `**kwargs` comment following `/` 

https://play.ruff.rs/cb2a370c-ae53-48a5-a35f-810b9c537ae2

**Comment by jakob-keller** [comment]
Thanks @MichaReiser and everyone else at https://github.com/astral-sh! You rock 🚀
