### ISSUE TITLE
Re-code `flake8-trio` and `flake8-async` rules to match upstream

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#10303]
These two plugins were merged into one (`flake8-async`), and the rules were re-coded: https://github.com/python-trio/flake8-async/issues/124.

**Comment by jakkdl** [comment]
Sorry for the messy discussion in that issue, the stuff roughly relevant for ruff starts at https://github.com/python-trio/flake8-async/issues/124#issuecomment-1938562382

**Comment by augustelalande** [comment]
Gonna do this
