### ISSUE TITLE
Test fails when upgrading from 0.3.0 to 0.3.2

### ISSUE THREAD

**Issue by eli-schwartz** [astral-sh/ruff#10319]
I tried to bump the version of ruff and rebuild it for Gentoo. Running the tests failed:

```
running 22 tests
test helpers::tests::any_over_stmt_type_alias ... ok
test helpers::tests::any_over_type_param_type_var_tuple ... ok
test helpers::tests::any_over_type_param_param_spec ... ok
test helpers::tests::resolve_import ... ok
test identifier::tests::extract_global_names ... ok
test helpers::tests::any_over_type_param_type_var ... ok
test name::tests::empty_vec ... ok
test name::tests::extend_from_slice_heap ... ok
test name::tests::extend_from_slice_stack ... ok
test name::tests::extend_from_slice_stack_spill ... ok
test name::tests::extend_heap ... ok
test name::tests::extend_stack ... ok
test name::tests::extend_stack_spilled ... ok
test name::tests::from_slice_heap ... ok
test name::tests::from_slice_stack ... ok
test name::tests::from_slice_stack_capacity ... ok
test name::tests::pop_heap ... ok
test name::tests::pop_stack ... ok
test name::tests::push_stack ... ok
test name::tests::push_stack_spill ... ok
test nodes::tests::size ... FAILED
test str::tests::prefix_uniqueness ... ok

failures:

---- nodes::tests::size stdout ----
thread 'nodes::tests::size' panicked at crates/ruff_python_ast/src/nodes.rs:4151:9:
assertion `left == right` failed
  left: 56
 right: 48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    nodes::tests::size

test result: FAILED. 21 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p ruff_python_ast --lib`
```

**Comment by charliermarsh** [comment]
Do you know what version of Rust you're compiling with?

**Comment by eli-schwartz** [comment]
```
$ rustc --version
rustc 1.74.1 (a28077b28 2023-12-04) (gentoo)
```

**Comment by charliermarsh** [comment]
I think those tests effectively require `1.76` (our `rust-toolchain.tml`), since Rust's enum layout improved. We may want to gate them on Rust version or something similar.

**Comment by dhruvmanila** [comment]
We do have a case where it tests against 2 values although not gated by anything. I think we can just use that pattern for any other types.

**Comment by zanieb** [comment]
@dhruvmanila can you link to that?

**Comment by charliermarsh** [comment]
It's a bit of a shame because it doesn't really test the same thing. We _could_ regress size there and not notice it.

**Comment by charliermarsh** [comment]
Should be fixed in the next release (or on `main`, since you're building from source).

**Comment by eli-schwartz** [comment]
Thanks, I can backport the commit.

> It's a bit of a shame because it doesn't really test the same thing. We _could_ regress size there and not notice it.

The obvious and straightforward answer here is to use a cfg for checking the compiler version and deciding whether to compile that test assertion. However my understanding is that there is no builtin cfg for it so you'll have to write and compile a rust program that then runs rustc --version, parses the output, and prints cfg flags to stdout for cargo...
