### ISSUE TITLE
E712 "true-false-comparison" incorrectly raises on array like

### ISSUE THREAD

**Issue by tigerhawkvok** [astral-sh/ruff#10344]
Consider

```python
import pandas as pd
s = pd.Series([True, True, False, False, None, None])
filter = s != False # [True, True, False, False, True, True]
notAFilter = s is not False # True
```

or similar operations on array-likes. Here, E712 is very much _not_ equivalent, and in fact, wrong.

This may not be tractable as it requires type analysis.

**Comment by charliermarsh** [comment]
Thanks! I think this is the same as this open issue: https://github.com/astral-sh/ruff/issues/4560.

**Comment by charliermarsh** [comment]
(Closing to merge / consolidate into #4560.)
