### ISSUE TITLE
Removing unnecessary list() for generators

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#10361]
Can you add the following rules?

`a.extend([i for i in range(10)])` to  `a.extend(i for i in range(10))`
`a.extend(list(range(10))` to `a.extend(range(10)`

`' '.join([i for i in range(10)])` to  `' '.join(i for i in range(10))`
`' '.join(list(range(10))` to `' '.join(range(10)`

`[1, *list(range(10))]` to `[1, *range(10)]`

`itertools.starmap(func, zip(range(5), range(5)))` to `map(func, range(5), range(5))`

**Comment by charliermarsh** [comment]
Seems reasonable although the `extend` could be wrong if we don't know that `a` is a list; similarly, changing `.join` could be wrong if we don't know that the caller is a string. Just caveats.

**Comment by MichaReiser** [comment]
This seems similar to https://docs.astral.sh/ruff/rules/unnecessary-comprehension-any-all/ What's unclear to me is if this should be a new rule or if the existing rule should be changed to detect any unnecessary list generators.

**Comment by charliermarsh** [comment]
I'd say one rule, for built-in methods that consume generators.

**Comment by charliermarsh** [comment]
This can be merged into https://github.com/astral-sh/ruff/issues/3259.
