### ISSUE TITLE
Fix for F811 (Redefinition of unused) removes import needed at runtime

### ISSUE THREAD

**Issue by Hnasar** [astral-sh/ruff#10384]
If you have a module and a symbol of the same name, https://docs.astral.sh/ruff/rules/redefined-while-unused/ may result in broken code.
Using version: 0.3.2

## Repro
```py
import datetime
from datetime import datetime
datetime(1, 2, 3)
```
```console
$ ruff foo.py  --fix
```

## Expected

The first import (shadowed) should be removed.

## Observed

```diff
--- foo.py
+++ foo.py
@@ -2,6 +2,4 @@
 
 import datetime
 
-from datetime import datetime
-
 print(datetime(1, 2, 3))
```

```console
$ python3 foo.py 
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    datetime(1, 2, 3)
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
```

**Comment by zanieb** [comment]
Thanks for the clear report! This one looks tricky.

**Comment by charliermarsh** [comment]
I'll take a look!

**Comment by MichaReiser** [comment]
@charliermarsh is this fixed by your or could you explain what's still missing.

**Comment by charliermarsh** [comment]
Yeah it’s fixed.
