### ISSUE TITLE
Rewrite `list(x for x in y)` to `list(y)`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#10403]
Given `list(x for x in y)`, we first hit C400, which fixes to `[x for x in y]`, which hits C416, which fixes to `list(y)`. We should consider short-circuiting this.

**Comment by boolean-light** [comment]
I would like to contribute on this. Should I implement it on inside C400 or add an another rule which matches only expression of type `list(x for x in y)`?

**Comment by charliermarsh** [comment]
I think we should augment C400 to support it.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/10419. Thanks @boolean-light!
