### ISSUE TITLE
Publishing Internal Crates to crates.io

### ISSUE THREAD

**Issue by mfish332** [astral-sh/ruff#10417]
Hi thanks for this awesome project. I am working on a project that does dependency analysis on a very large codebase and would love to use Rust. When looking for the best Rust python parser I was led to [RustPython/Parser](https://github.com/RustPython/Parser). I see that Ruff originally used RustPython/Parser but it seems like the current parser has deviated quite a bit. I am wondering if you can publicly publish some of the internal crates such as the parser and ast packages.

**Comment by zanieb** [comment]
This is loosely a duplicate of https://github.com/astral-sh/ruff/issues/43

We're hesitant to publish to crates.io at this time because the internal crates are not versioned and we are moving too fast to commit to a stable Rust API.

**Comment by mfish332** [comment]
A possible solution would be to publish at a `0.0.x` version and not commit to any API. Then people consuming the package could specify an exact version. It is significantly better than forking and having to sync upstream. Ruff really has the best rust python parser around and it would be great to be able to use it in other projects.

**Comment by MichaReiser** [comment]
I'm open to releasing some crates (like AST and parser) without any stability guarantees to crates.io (e.g. using 0.0.x) but we probably would need help to set up the release process. But I'm deferring the decision to @zanieb who's taken the lead here.

**Comment by mfish332** [comment]
Hi All, thank you for quick the responses. I was mistakenly under the impression that it was impossible to install crates from within a cargo workspace via git (due to path based links). This is not true though, See [SO question](https://stackoverflow.com/questions/73233872/how-do-i-depend-on-a-crate-within-a-cargo-workspace-over-git) or this [cargo issue](https://github.com/rust-lang/cargo/issues/10151)

 For my purposes this will work great as I am not publishing to crates.io, and I can pin the ruff deps to a release tag. TLDR for those coming across this issue at a later point you can run:
```bash
cargo add ruff_python_parser ruff_python_ast --git https://github.com/astral-sh/ruff --tag v0.3.2
```

**Comment by flying-sheep** [comment]
After replacing the parser, maybe this could be revisited? It would be great to have a robust Python parser on crates.io

**Comment by chrisjsewell** [comment]
I would note rustpython now uses the ruff parser: https://github.com/RustPython/RustPython/pull/5494
It currently has to source from GitHub, which seems really not great at all 😅
