### ISSUE TITLE
[Feature Request][Pytest Rule] Enforce a strict argument being passed into pytest.mark.xfail

### ISSUE THREAD

**Issue by rshanker779** [astral-sh/ruff#10411]
Hi, 
[pytest.mark.xfail](https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-xfail-ref) has an optional strict argument that defaults to False. When strict is False, if an xfailed test unexpectedly passes, the test suite as a whole will not fail, but when strict is True, an unexpectedly passing test will be marked as a failure.

It would be nice to have a ruff rule that require the strict argument to be passed (with either value), so when writing tests with xfail it is explicit if passing cases are allowed or not.

Thanks
Rohan

**Comment by bluetech** [comment]
I think a better way is to set `xfail_strict = true` in the pytest config.

**Comment by Kilo59** [comment]
https://docs.pytest.org/en/stable/reference/reference.html#confval-xfail_strict

**Comment by jack-mcivor** [comment]
> I think a better way is to set `xfail_strict = true` in the pytest config.

FWIW I discovered that there is a tool that can check this kind of configuration - see https://learn.scientific-python.org/development/guides/repo-review/. Each check has a specific code associated with it - xfail_strict is PP305, mentioned here https://learn.scientific-python.org/development/guides/pytest/#configuring-pytest
