### ISSUE TITLE
--fix should not delete lines which are marked with pylint disable or pyright ignore

### ISSUE THREAD

**Issue by virajkanwade** [astral-sh/ruff#10439]
ruff 0.3.3

`poetry run ruff check --fix appmap`

It deleted this line. 

`import _appmap.unittest  # pyright: ignore pylint: disable=unused-import`

Ideally expected behavior: It should add `# noqa: F401`
Or atleast not delete this line.

**Comment by zanieb** [comment]
Hi! Could you please provide a reproducible example e.g. a single file with a `ruff check --isolated --fix --select <RULE>` command that demonstrates the behavior?

**Comment by charliermarsh** [comment]
Thanks -- thanks has been requested before and can be tracked here: https://github.com/astral-sh/ruff/issues/1203. Right now, though, we only respect `# noqa` directives. You can run `ruff check --select RUF100 --fix` to automatically add `# noqa` directives for existing violations, if you want, or even `ruff check --select RUF100 --select F401 --fix` to add `# noqa` for existing unused imports.
