### ISSUE TITLE
Some lines in PEP 723 blocks trigger ERA001

### ISSUE THREAD

**Issue by zeevro** [astral-sh/ruff#10455]
Ruff (version 0.3.3) treats some lines from PEP 723 blocks as commented-out code.

Example:
```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "requests<3",
#   "rich",
# ]
# ///
```

```
$ ruff check --select=ERA001 pep723.py
pep723.py:3:1: ERA001 Found commented-out code
pep723.py:6:1: ERA001 Found commented-out code
Found 2 errors.
```

**Comment by MichaReiser** [comment]
Thanks for reporting. I agree that `ERA001` should skip over these comments. This also brings up that ruff should probably support configurations in the script section, but we can track this separately

**Comment by zeevro** [comment]
Wow, that was seriously speedy!
