### ISSUE TITLE
Long SPDX-FileCopyrightText lines cause rule E501 violations

### ISSUE THREAD

**Issue by damonlynch** [astral-sh/ruff#10465]
First, let me say thank you for a great project. Keep up the great work!

A lengthy single-line `SPDX-FileCopyrightText` statement in the source code header can unfortunately easily violate rule E501.

For example, this innocuous line is 89 characters:
`# SPDX-FileCopyrightText: Copyright 2012-2015 Jim Easterbrook <jim@jim-easterbrook.me.uk>`

It is unclear to me how to direct ruff to ignore this error on a per-line basis, because being a machine-read string, obviously the line cannot end with `# noqa: E501`.

My guess is that ruff should by default ignore rule E501 violations when dealing with SPDX headers (and potentially any other machine-read source code headers that adhere to a rigid specification).

Please note the specifications explicitly recommend not using multi-line statements, so that's not a viable workaround. 

In example above, to keep it at 88 characters or below, it appears the only current workaround is to use `©️` in place of the text `Copyright`, but that will not be sufficient in all circumstances.

**Relevant Links**
[SPDX specification](https://spdx.github.io/spdx-spec/v2.3/file-tags/)
[REUSE specification](https://reuse.software/spec/)

**Comment by charliermarsh** [comment]
Yeah I think we should consider disabling E501 enforcement for SPDX headers.
