### ISSUE TITLE
`FBT003` with Pydantic

### ISSUE THREAD

**Issue by redb0** [astral-sh/ruff#10485]
Hello!

I use Ruff version `0.1.15` with `flake8-boolean-trap`. I am getting this error in the following example:

```python
from pydantic import Field
from pydantic_settings import BaseSettings


class Settings(BaseSettings):

    foo: bool = Field(True, exclude=True)
```

Command `ruff test.py --fix` return

```
test.py:7:23: FBT003 Boolean positional value in function call
```

Pydantic allows you to explicitly specify the `default` parameter (`foo: bool = Field(default=True, ...)`). However, this stands out from the general code, where other values ​​are specified without it.

I’m not sure that it’s worth “strictly” filtering such cases. On the one hand, I can disable this check for certain files. I think it's not right to do this. Maybe it’s worth allowing the user to independently specify filtering rules, in addition to those initially specified as here https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/rules/flake8_boolean_trap/helpers.rs#L7?

I'd be glad to hear your opinion.

**Comment by zanieb** [comment]
Basically the same concept as https://github.com/astral-sh/ruff/issues/10356#issuecomment-1991780371

I think we should add a configurable list of allowed types / calls.

**Comment by redb0** [comment]
@zanieb Yes, I also encountered several similar problems #4172, #4382, #6711 and other. I think a list of available names/calls would be the most flexible solution

**Comment by augustelalande** [comment]
I will implement this
