### ISSUE TITLE
Failed to read pyproject.toml after adding additional pyproject.toml file

### ISSUE THREAD

**Issue by mataton** [astral-sh/ruff#10483]
I am wanting to ignore docstring rules in my project's unit-test directories. I have a `pyproject.toml` file located at the root of the project, which looks like this:

````
[build-system]
# https://numpy.org/doc/stable/dev/depending_on_numpy.html#adding-a-dependency-on-numpy
requires = ["Cython>=0.29.32", "oldest-supported-numpy", "setuptools", "wheel"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::skbio.util.SkbioWarning",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    ".dockerignore",
    ".editorconfig",
    "aarch64.Dockerfile",
    "checklist.py",
    # created by conda-incubator/setup-miniconda@v3 action
    "ci/setup-miniconda-patched-conda_host_env.yml",
]

# Basic configurations for Ruff.
# See https://docs.astral.sh/ruff/configuration/
[tool.ruff]
target-version = "py38"
exclude = [
    "doc/**",  # documentation
    "web/**",  # website
]

[tool.ruff.lint]
select = ["E", "W", "D"]  # pycodestyle (E, W), pydocstyle (D)
ignore = [
    "D203",  # puts a space before class docstrings
    "D213",  # puts summary on second line
    "D400",  # redundant with D415 in place
    "D301",  # forces raw string literals
]
````

Then I add a `pyproject.toml` file to one of my unit test directories, which looks like this:
````
[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
ignore = [
    "D100",
    "D101",
    "D102",
    "D104"
]
````

I then try to run `ruff check path/to/test_directory` and ruff doesn't ignore the rules outlined in the `toml` file located in this directory. Furthermore, when I try to run `ruff check .` from the root directory, after having run all previous steps, I now get the following errors:

````
ruff failed
  Cause: Failed to read /home/maton/qlab/skbio/github/scikit-bio/skbio/pyproject.toml
  Cause: No such file or directory (os error 2)
````

I'm running Ruff 0.3.2

**Comment by charliermarsh** [comment]
Does `/home/maton/qlab/skbio/github/scikit-bio/skbio/pyproject.toml` exist?

**Comment by mataton** [comment]
It does, which was the confusing part. I upgraded to ruff 0.3.3 today and can't replicate the issue. Anyway, I'm now using ruff's `lint.per-file-ignores` instead of putting separate `toml` files in all the test folders, and that is working for me.

**Comment by charliermarsh** [comment]
Okay thanks! That's strange, there's not much to that error, I believe it comes directly from the standard library when we try to read the file.
