### ISSUE TITLE
Strange autofix for PYI025 if `"Set"` is included in `__all__`

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#10508]
The following snippet correctly causes Ruff to emit PYI025:

```py
from collections.abc import Set as Set

__all__ = ["Set"]
```

But if you apply the autofix, it "fixes" it to this, which is... not correct:

```py
from collections.abc import Set as AbstractSet

AbstractSet = ["Set"]
```

**Comment by MichaReiser** [comment]
What's the correct fix in your view or should the rule not emit a fix if it's a module scoped variable named `__all__`?

**Comment by AlexWaygood** [comment]
Including the name `"Set"` in `__all__` marks the symbol as being publicly exported from the module, but it doesn't create a binding in and of itself -- the `Set` binding is created via the import. So we definitely shouldn't be removing the `__all__` variable from the module here.

If we stipulate that it's correct for us to emit the violation here at all, the correct fix would be to modify the module to

```py
from collections.abc import Set as AbstractSet

__all__ = ["AbstractSet"]
```

rather than what we currently do, which is:

```py
from collections.abc import Set as AbstractSet

AbstractSet = ["Set"]
```

This is an edge case that's unlikely to come up. However, I'm somewhat concerned that it points to a broader issue with the autofix machinery that could also impact other rules.

## Should we be emitting PYI025 on this snippet at all?

This is debatable. However, I think it's fine to emit PYI025 even if the `"Set"` symbol appears in `__all__`, since that's very much an edge case that's extremely unlikely to actually come up. I'm not really concerned about this.

**Comment by AlexWaygood** [comment]
Note that the code will actually trigger F811 after being "autofixed" for PYI025:

```py
from collections.abc import Set as AbstractSet

AbstractSet = ["Set"]  # F811: Redefinition of unused `AbstractSet` from line 1
```

**Comment by AlexWaygood** [comment]
The issue is here where, after renaming the binding itself (`from collections.abc import Set`), we then proceed to try to rename all _references_ to the binding that we've just renamed:

https://github.com/astral-sh/ruff/blob/4f06d59ff6f58f2d13c2f8fcfe375b81058f87c3/crates/ruff_linter/src/renamer.rs#L202-L206

The renamer correctly recognises that `__all__ = ["Set"]` counts as a resolved reference to the `Set` symbol that we've just renamed. But it then incorrectly renames the target of the assignment rather than the string in the assignment's value.

**Comment by AlexWaygood** [comment]
Adding this debug print:

```diff
diff --git a/crates/ruff_linter/src/renamer.rs b/crates/ruff_linter/src/renamer.rs
index 8571d7f53..e8f4d1295 100644
--- a/crates/ruff_linter/src/renamer.rs
+++ b/crates/ruff_linter/src/renamer.rs
@@ -202,6 +202,7 @@ impl Renamer {
                 // Rename the references to the binding.
                 edits.extend(binding.references().map(|reference_id| {
                     let reference = semantic.reference(reference_id);
+                    dbg!(reference);
                     Edit::range_replacement(target.to_string(), reference.range())
                 }));
```

reveals that the range of the `ResolvedReference` is `33..40`, which is the range of `__all__` in the expression `__all__ = ["Set"]`, rather than the range of `"Set"`. The incorrect range is then what causes the renamer to change `__all__ = ["Set"]` to `AbstractSet = ["Set"]` rather than to `__all__ = ["AbstractSet"]`.

This TODO comment looks relevant @charliermarsh ;)

https://github.com/astral-sh/ruff/blob/4f06d59ff6f58f2d13c2f8fcfe375b81058f87c3/crates/ruff_linter/src/checkers/ast/mod.rs#L2114-L2120
