### ISSUE TITLE
GitHub release for ruff 0.3.4 missing

### ISSUE THREAD

**Issue by tobbez** [astral-sh/ruff#10534]
The GitHub release for ruff 0.3.4 appears to be missing.

Looks like the release workflow ran correctly, maybe someone forgot to publish the draft release it created?

**Comment by charliermarsh** [comment]
Thanks, that's my bad.

**Comment by charliermarsh** [comment]
Done: https://github.com/astral-sh/ruff/releases/tag/v0.3.4
