### ISSUE TITLE
`Q000` autofix failing in forward reference type annotations

### ISSUE THREAD

**Issue by augustelalande** [astral-sh/ruff#10574]
The `Q000` autofix is generating syntax errors in code with forward reference type annotations which include string literals.
```python
def foo(x: "Literal['a', 'b', 'c']") -> None:
    ...
```
autofixed to 
```python
def foo(x: "Literal["a", "b", "c"]") -> None:
    ...
```

this was found by https://github.com/qarmin/Automated-Fuzzer/actions/runs/8412442975

**Comment by AlexWaygood** [comment]
Thanks! I think the underlying issue is the same as #10546, so I'll close this in favour of that one 👍
