### ISSUE TITLE
`ruff server` lacks unused code formatting

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#10589]
In the existing LSP (notice the grayed-out text):

![Screenshot 2024-03-25 at 5 05 43 PM](https://github.com/astral-sh/ruff/assets/1309177/64ac8cb7-b6f6-4742-863a-c5325ba27d19)

With `ruff server` (white text):

![Screenshot 2024-03-25 at 5 06 02 PM](https://github.com/astral-sh/ruff/assets/1309177/3a19be52-6a43-41ec-8ce2-1e1305292a07)

**Comment by dhruvmanila** [comment]
Reference implementation in `ruff-lsp`: https://github.com/astral-sh/ruff-lsp/blob/187d7790be0783b9ac41ce025a724cf389bf575c/ruff_lsp/server.py#L739-L745
