### ISSUE TITLE
`ruff server` treats all diagnostics as errors

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#10588]
In the existing LSP (yellow):

![Screenshot 2024-03-25 at 5 05 43 PM](https://github.com/astral-sh/ruff/assets/1309177/64ac8cb7-b6f6-4742-863a-c5325ba27d19)

With `ruff server` (red):

![Screenshot 2024-03-25 at 5 06 02 PM](https://github.com/astral-sh/ruff/assets/1309177/3a19be52-6a43-41ec-8ce2-1e1305292a07)

In the existing LSP, we have a dedicated list of codes that we treat as errors, and the rest are treated as warnings. (If anything, everything should be a warning, rather than an error.)

**Comment by dhruvmanila** [comment]
Reference implementation in `ruff-lsp`: https://github.com/astral-sh/ruff-lsp/blob/187d7790be0783b9ac41ce025a724cf389bf575c/ruff_lsp/server.py#L748-L756
