### ISSUE TITLE
mixed-case-variable-in-class-scope (N815) reports mixedCase on class variables of subclassed TypedDict

### ISSUE THREAD

**Issue by teaishealthy** [astral-sh/ruff#10671]
## Description
`ruff 0.1.15`

N815 will report on mixedCase class variables on subclasses of a TypedDict, while it won't on the actual TypedDict (as expected)

## Minimal reproducible example 

```py
from typing import TypedDict

class A(TypedDict):
    mixedCase: int  # no error!

class B(A):
    alsoMixedCase: int  # Variable `alsoMixedCase` in class scope should not be mixedCase

 ```

**Comment by charliermarsh** [comment]
We can only support this for subclasses defined in the same file right now.
