### ISSUE TITLE
Errors in multiline docstrings point to the first line of the string

### ISSUE THREAD

**Issue by ts933** [astral-sh/ruff#10736]
_ruff version==0.2.1_

pyproject.toml
```

[tool.ruff]
preview = true

select = [
  "C90", # McCabe
  "D",   # pydocstyle
  "E",   # pycodestyle
  "F",   # pyflakes
  "NPY", # numpy specific
  "PL",  # pylint
  "PTH", # flake8-use-pathlib
  "SIM", # flake8-simplify
  "TD",  # flake8-todos
  "UP",  # pyupgrade
  "W",   # pycodestyle
]
line-length = 120

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
max-complexity = 5


```

**Comment by MichaReiser** [comment]
@ts933 would you mind providing a minimal code example that demonstrates the problem? It would help us to understand what you're asking for or consider a bug. Thank you

**Comment by ts933** [comment]
Code with 4 errors all pointing to the same line --> 10

`def extract_category(dataframe,  # type: ignore   # pragma: no cover
                     keyword,
                     filter_on_column='category',
                     label='io') -> pd.DataFrame:
    """Extracts rows from a given dataframe based on a filter condition and assigns a label of 0 or 1 to each row.

    Args:

        dataframe (pyspark.sql.DataFrame): The input dataframe.
        keyword (str): The keyword to match in the filter column.
        filter_on_column (str, optional): The column to filter on.
        label (str): If we want to label the data as IO or NIO.
    Returns:

        pd.DataFrame: The extracted rows with an additional 'label' column assigned with a value of 1.
    """`

file.py:10:5: D410 [*] Missing blank line after section ("Args")
file.py:10:5: D412 [*] No blank lines allowed between a section header and its content ("Args")
file.py:10:5: D411 [*] Missing blank line before section ("Returns")
file.py:10:5: D412 [*] No blank lines allowed between a section header and its content ("Returns")

**Comment by MichaReiser** [comment]
I would need to look into what the reason for this is. @charliermarsh any  chance it is so that the noqa comments work for multiline docstrings (because they match on the start of the line?)

**Comment by charliermarsh** [comment]
No, that shouldn’t be necessary for the noqa enforcement. I can take a look at this. My guess is we highlight the whole docstring, and so the start character is indeed the first line? Not sure though, I’ll look later.

**Comment by charliermarsh** [comment]
Yeah, these rules just use the range of the docstring. We could consider refining them.
