### ISSUE TITLE
TCH rules triggered even if class is declared in `runtime-evaluated-base-classes`

### ISSUE THREAD

**Issue by mtvx** [astral-sh/ruff#10749]
Despite declaring `datetime.date` as needed for runtime evaluation in `runtime-evaluated-base-classes`, Ruff nags about it and wants to move it to `if TYPE_CHECKING` block.

`pyproject.toml`:

```toml
[tool.ruff.lint]
select = [
    "TCH",  # flake8-type-checking
]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "datetime.date",
    "date",
]
```

With `example.py`:

```py
from __future__ import annotations

from datetime import date

from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Birthday(DeclarativeBase):
    id: Mapped[int] = mapped_column(primary_key=True)
    day: Mapped[date]
```

```console
> ruff check example.py
example.py:3:22: TCH003 Move standard library import `datetime.date` into a type-checking block
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

Isn't the idea that classes declared in `runtime-evaluated-base-classes` would be ignored from this check?

Ruff `0.3.5`.

**Comment by MichaReiser** [comment]
@charliermarsh do you know if that's intentional or considered a bug?

**Comment by charliermarsh** [comment]
I think this is intentional, since the `runtime-evaluated-base-classes` should be base classes rather than those used in the annotations. So, e.g., in this case, you'd want:

```toml
[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "sqlalchemy.orm.DeclarativeBase"
]
```

Can you give that a try?

**Comment by mtvx** [comment]
Jeez. Yes, that works. Thanks.

Obviously the reader (me) misunderstood. The docs state:

> *Exempt classes* that list any of the enumerated classes as a base class *from needing to be moved into type-checking blocks*.

I don't know, but maybe that's a bit difficult to understand, at least for me, a non-native English speaker. Gives at the impression that it's about excluding the classes that would be otherwise moved to the type-checking block.

The rest of the docs there is totally understandable, and it even gives correct examples. I guess my mind just had already made its mind based on the first sentence.

**Comment by pySilver** [comment]
@mtvx same thing - I've had an impression that this setting is about imported classes, not our own.
