### ISSUE TITLE
Operator Assignment Rule

### ISSUE THREAD

**Issue by IamRezaMousavi** [astral-sh/ruff#10763]
Ruff (or other python linters) don't has any rule like [operator-assignment](https://eslint.org/docs/latest/rules/operator-assignment) rule in eslint:

```diff
- x = x + 1
+ x += 1
```

**Comment by charliermarsh** [comment]
I _think_ this would be covered by https://github.com/astral-sh/ruff/pull/9932

**Comment by IamRezaMousavi** [comment]
> I _think_ this would be covered by https://github.com/astral-sh/ruff/pull/9932

Yes, Thank you
