### ISSUE TITLE
Weird behaviour of Rule C400 and C416

### ISSUE THREAD

**Issue by VascoSch92** [astral-sh/ruff#10778]
**Ruff version: 0.3.5**

_I'm sorry for the long post_

Hey, 
I would like to document the following behaviours about rules C400 and C416

## C400 error message

I have the following script `scratch.py`
```python
from typing import Dict, List, Tuple

def generate_samples(test_cases: Dict) -> List[Tuple]:
    return list(
        (input, expected)
        for input, expected in zip(test_cases["input_value"], test_cases["expected_value"])
    )
```
I run the following command

```text
>> ruff check scratch.py --select C400              
>> scratch.py:5:12: C400 Unnecessary generator (rewrite using `list()`)
```

You can see that the error message is misleading. After looking into the [C400 rule documentation](https://docs.astral.sh/ruff/rules/unnecessary-generator-list/) I propose to change the error message with one of the following:

1. _C400 Unnecessary generator (rewrite using `[a for a in iterable]`)_ or 
2. _C400 Unnecessary generator (rewrite using `list(iterable)`)_ or
3. _C400 Unnecessary generator (rewrite using `[a for a in iterable]` or `list(iterable)`)_.

I can open a PR to fix that if you are interested. Let me know which error message you like the most.

## Conflict between C400 and C416
Consider `scratch.py` equal to 
```python
from typing import Dict, List, Tuple

def generate_samples_v_1(test_cases: Dict) -> List[Tuple]:
    return list(
        (input, expected)
        for input, expected in zip(test_cases["input_value"], test_cases["expected_value"])
    )

def generate_samples_v_2(test_cases: Dict) -> List[Tuple]:
    return [
        (input, expected)
        for input, expected in zip(test_cases["input_value"], test_cases["expected_value"])
    ]
```
I run the following command
```text
>> ruff check scratch.py --select C400 --select C416
>> scratch.py:4:12: C400 Unnecessary generator (rewrite using `list()`)  # this is for generate_samples_v_1 
>> scratch.py:10:12: C416 Unnecessary `list` comprehension (rewrite using `list()`)  # this if for generate_samples_v_2 
```
Clearly, `C400` and `C416` are in conflict (as we can understand from the documentation and from this example). Moreover, we have the following problem: `C400` doesn't accept the output of `generate_samples_v_1`, but C416 does.

My questions:
1. is it correct that C400 doesn't accept the output of `generate_samples_v_1`, but C416 does ?
2. is it correct that C416 accepts the output of `generate_samples_v_2`?
3. from the documentation of `C400` and `C416`, we are inclined to understand that `C416` should contain `C400`. Therefore, they should not have conflicts, correct?

Without changing the rules `C400` and `C416`, we could:
1. rewrite the error message of `C416` as: _C416 Unnecessary generator (rewrite using `list(iterable)`)_
2. using the error message number 3 proposed in the section `C400 error message`
This should clarify the situation for future users.
(Perhaps also adding a line in the documentation shortly explaining the situation could be cool)

Let me know if you are interested in the above changes

**Comment by autinerd** [comment]
Hi!

I don't quite understand what you mean with conflict.

1. I understand from you that you would like that the error message is rewritten as *C400 Unnecessary generator (rewrite using `list(zip(test_cases["input_value"], test_cases["expected_value"]))`* or similar in your example. (Ruff has a fix available, so you could also say that it is not really needed)

2. The both rules are not in conflict. C400 is for generator expressions, while C416 is for list/dict/set comprehensions. Your function `generate_samples_v_1` contains a generator expression, your function `generate_samples_v_2` contains a list comprehension. These look similar, but are not exactly the same.

**Comment by VascoSch92** [comment]
> The both rules are not in conflict. C400 is for generator expressions, while C416 is for list/dict/set comprehensions. Your function generate_samples_v_1 contains a generator expression, your function generate_samples_v_2 contains a list comprehension. These look similar, but are not exactly the same.

Thanks for your answer. Now I understand better the situation, and I think that probably there are no problem at all. I was just confused.
