### ISSUE TITLE
`PERF402` triggers, incorrectly, on async for loops

### ISSUE THREAD

**Issue by sliedes** [astral-sh/ruff#10787]
Searched keywords: PERF402. #10322 is similar, but more complicated (and closed by the submitter).

This code triggers PERF402 on ruff 0.3.5:

```python
from typing import AsyncIterator


async def some_async_iterable() -> AsyncIterator[int]:
    for i in range(10):
        yield i


async def foo() -> None:
    values: list[int] = []
    async for i in some_async_iterable():
        values.append(i)
```

Result from running `ruff check --isolated --select PERF402`:

```
bug.py:12:9: PERF402 Use `list` or `list.copy` to create a copy of a list
Found 1 error.
```

But `list` and `list.copy` cannot be used on an async iterator. #10322 suggested using an async list comprehension, but I think that's a different animal; in the very least the error message is wrong, and a check that would suggest using a list comprehension instead of a loop would be rather different in spirit.

**Comment by CoolCat467** [comment]
I agree the error message is misleading, but yes using an async list comprehension should be the fix here:
```python
from typing import AsyncGenerator


async def some_async_iterable() -> AsyncGenerator[int, None]:
    for i in range(10):
        yield i


async def foo() -> None:
    values: list[int] = [i async for i in some_async_iterable()]
```
