### ISSUE TITLE
Rework linter API to remove a `Clone` implementation on `LinterSettings`

### ISSUE THREAD

**Issue by snowsignal** [astral-sh/ruff#10782]
In https://github.com/astral-sh/ruff/pull/10652, we had to implement `Clone` for `LinterSettings` and all sub-settings so that the `source.organizeImports` resolver could clone the settings from a reference and then modify `rules` to `[I001, I002]`. Since this cloning operation is wasteful (we only need to update one field), we should find a way to temporarily override values in `LinterSettings` without needing to clone the entire struct.

**Comment by MichaReiser** [comment]
I think we can ignore this for now. I expect that setting handling will be significantly different in Red knot.
