### ISSUE TITLE
nan-comparison code mismatch with Pylint

### ISSUE THREAD

**Issue by BlindChickens** [astral-sh/ruff#10791]
In the (W)arning category of Pylint `nan-comparison` has code `W0177`. [Here](https://pylint.readthedocs.io/en/latest/user_guide/checkers/features.html#:~:text=nan%2Dcomparison%20(W0177)%3A)

In Ruff it is coded to `W0117`.

Is it a mistake?

Thanks in advance

**Comment by charliermarsh** [comment]
Ahh thank you! We'll correct it. Looks like an oversight.

**Comment by WindowGenerator** [comment]
@charliermarsh Hi!
Can I fix it?

**Comment by charliermarsh** [comment]
Feel free, thanks! You'll need to update the code in `codes.rs`, and then also add a redirect from the old to new code in `rule_redirects.rs`.

**Comment by charliermarsh** [comment]
I'm gonna go ahead and fix this real quick.

**Comment by BlindChickens** [comment]
@charliermarsh 
Sorry to necropost like this. But I forgot to ask that this issue be updated to reflect this fix.
[here](https://github.com/astral-sh/ruff/issues/970#:~:text=nan%2Dcomparison%20/%20W0177%20(PLW0117))
