### ISSUE TITLE
new feat: Jump to source 

### ISSUE THREAD

**Issue by linpan** [astral-sh/ruff#10810]
```
❯ ruff format .  --line-length 120 
error: Failed to parse graph/node.py:26:5: Expected 'Indent', but got 'llm'
2 files reformatted, 11 files left unchanged
```

click  "graph/node.py:26:5" go to source,  use can fix it instead  find file and location line no.

**Comment by charliermarsh** [comment]
I think this would be a feature of your terminal rather than anything that Ruff could do. Like, in my terminal, I can right-click on `graph/node.py` and it will open the file in my default editor.

Do you know of similar tools that expose this, where you're seeing different behavior than for Ruff?

**Comment by CommanderStorm** [comment]
Currently, there is really not enough context to look if there is something that can be improved.
Lets get this into a reproducible direction:

- What directory are you in?
- What terminal emulators are you using? What happens in other terminal emulators?
- What is the minimal, reproducible output?

**Comment by charliermarsh** [comment]
Closing for now as it doesn't feel actionable.
