### ISSUE TITLE
doc (too-many-arguments PLR0913): 

### ISSUE THREAD

**Issue by buhtz** [astral-sh/ruff#10899]
This is about the [`too-many-arguments` (PLR0913)](https://docs.astral.sh/ruff/rules/too-many-arguments/) rule and its documentation.
I would suggest to improve the documentation about that rule because there is a difference in its treatment between ruff and pylint.

Maybe something like this?

> Differing from PyLint, ruff indeed considers every argument. In contrast, PyLint disregards certain names by default, as dictated by the --ignored-argument-names option.

Background:
As discussed with [pylint-devs at #9547](https://github.com/pylint-dev/pylint/issues/9547) the behavior of ruff and pylint are different. It seems to me that ruff is accurate and count every argument without any exception. But PyLint does have something like `--ignored-argument-names` with arguable default values (e.g. `ignored_*`).

Here is an example triggering the error in ruff but not pylint.

```
def weight_by_icd_group(data: pandas.DataFrame,
                        index_column: str,
                        icd_column: str,
                        weight_name: str = 'weight',
                        ignored_icds: tuple = ('UUU'),
                        exclude_appendix_artifact: bool = True
                        ) -> pandas.DataFrame:

```

Generally minimal differences between ruff and other linters in rule treatment should mentioned in the rules documentation.

**Comment by MichaReiser** [comment]
Thanks for reporting this. We plan to decouple our rules from the upstream rules in the long term. That's why I think it doesn't make sense for us to list all differences to similar rules in other linters. But that's just my opinion and hasn't been discussed by the team. I'm interested to hear what @AlexWaygood thinks on this.

**Comment by buhtz** [comment]
Thanks.
It also seems that PyLint do not count any arguments for private methods and functions, but ruff does.

**Comment by charliermarsh** [comment]
I think the documentation here is alright as-is.

**Comment by buhtz** [comment]
> I think the documentation here is alright as-is.

And I think different. :rofl:
