### ISSUE TITLE
Formatter breaks inline `if/else` statement different than Black when used on function argument

### ISSUE THREAD

**Issue by kikefdezl** [astral-sh/ruff#10918]
Hey! 

I have the following snippet of code:

```python
def my_function(argument: str | None):
    print(argument)

super_duper_very_long_variable_name = "foo"

my_function(argument=super_duper_very_long_variable_name if super_duper_very_long_variable_name else None)
```

Line 6 surpasses the maximum length of `88` so the line has to be broken.

`black` produces:
```python
my_function(
    argument=(
        super_duper_very_long_variable_name
        if super_duper_very_long_variable_name
        else None
    )
)
```

`ruff` produces:
```python
my_function(
    argument=super_duper_very_long_variable_name
    if super_duper_very_long_variable_name
    else None
)
```

I am just running `ruff format this-file.py` using the default settings and version `0.3.7`.

I believe the `black` output to be more readable. I am willing to try to open a PR myself if you confirm that this is a change you'd be interested in.

**Comment by kikefdezl** [comment]
I'd like to add a second example to illustrate why the current output is not very readable. In a scenario where we have a function call with many arguments:

```python
from dataclasses import dataclass


@dataclass
class MyClass:
    attr_1: str
    attr_2: str | None
    attr_3: str


super_duper_very_long_variable_name = "foo"

c = MyClass(
    attr_1="my_value_1",
    attr_2=super_duper_very_long_variable_name
    if super_duper_very_long_variable_name
    else None,
    attr_3="my_value_3",
)
```

whereas `black` produces:
```python
c = MyClass(
    attr_1="my_value_1",
    attr_2=(
        super_duper_very_long_variable_name
        if super_duper_very_long_variable_name
        else None
    ),
    attr_3="my_value_3",
)
```

**Comment by MichaReiser** [comment]
Hy @kikefdezl 

I agree that Black's formatting looks better in this specific case. This is a known and intentional deviation. We want to explore alternative formatting that makes long-subexpressions more readable without needing to use parentheses (which is something that Black otherwise tries very hard to avoid). See [known deviation](https://docs.astral.sh/ruff/formatter/black/#parenthesizing-long-nested-expressions) for more details.

**Comment by kikefdezl** [comment]
Understood, thank you :+1:

**Comment by dvdkon** [comment]
As feedback, I'd like to say that aligning the rest of the `if/else` expression with keyword arguments looks confusing to me. I'd at least indent them in this specific case, was that considered as an option?

**Comment by sshishov** [comment]
@MichaReiser can we have maybe a settings to support the parenthesis for readability?
Currently there is no option to enforce "long" inline IF statements to be readable. It would be nice if it can be configurable for the formatter.
