### ISSUE TITLE
LICENSE file in this repo is 13k lines long

### ISSUE THREAD

**Issue by mistercrunch** [astral-sh/ruff#10929]
Trying to understand the licensing here, the LICENSE file is 13k lines long(!) Lots of copyright notice. Guessing if I just use it for CI and do not redistribute then I don't need to carry the copyright(s) (?)

Any way to simplify/summarize this?

**Comment by mistercrunch** [comment]
BTW excited about the approach and project overall. We'd love to use it for Apache Superset but we're under the scrutiny of the ASF. It looks like folks in the Apache Airflow community may have done the vetting already (?)

**Comment by charliermarsh** [comment]
Yeah that's right -- the project is MIT licensed, and you don't need to carry the copyright if you're just using in CI (IIUC).
