### ISSUE TITLE
Failed to `detect-same-package` for `first-party`

### ISSUE THREAD

**Issue by serjflint** [astral-sh/ruff#10927]
Hi!

ruff 0.3.4

I am trying to sort imports like `ruff check library/module.py --fix-only`

```python
from plugins import a

from library import b
```

My config is

```toml
[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
detect-same-package = true

section-order = [
    "future",
    "standard-library",
    "third-party",
    "appnexus",
    "first-party",
    "local-folder",
]
[tool.ruff.lint.isort.sections]
appnexus = [
    "library",
    "plugins",
]
```

In the end I receive

```python
from library import b
from plugins import a
```

Instead of the file staying the same.

**Comment by charliermarsh** [comment]
Can you explain you expect something other than the result you showed above? You marked them as being part of the same section.

**Comment by serjflint** [comment]
> Can you explain you expect something other than the result you showed above? You marked them as being part of the same section.

I expect ruff do not change anything in the first snippet as `module.py` is a part of the `library`.

**Comment by serjflint** [comment]
If `module.py` was outside of `library` (and `plugins`) it would be right to receive the second snippet.

**Comment by charliermarsh** [comment]
But you have:
```toml
appnexus = [
    "library",
    "plugins",
]
```

And so imports of `library` and `plugins` are being assigned to that section, correctly.

**Comment by serjflint** [comment]
> But you have:
> 
> ```toml
> appnexus = [
>     "library",
>     "plugins",
> ]
> ```
> 
> And so imports of `library` and `plugins` are being assigned to that section, correctly.

But when I write code in library `package` and import relative module using absolute import I expect it to be counted as `local-folder` or `first-party`.

**Comment by charliermarsh** [comment]
If you have:

```
appnexus = [
    "library",
    "plugins",
]
```

Then any imports of modules named `library` or `plugins` will be classified as `appnexus`.

**Comment by serjflint** [comment]
> If you have:
> 
> ```
> appnexus = [
>     "library",
>     "plugins",
> ]
> ```
> 
> Then any imports of modules named `library` or `plugins` will be classified as `appnexus`.

I see. But I think my case is valid for custom sections. Is it possible to modify this behavior?

**Comment by charliermarsh** [comment]
I think in that case you'd want to omit `library` from `appnexus`, since you want library imports to be considered first-party?

**Comment by charliermarsh** [comment]
Going to close but I can keep answering questions if they come up.

**Comment by serjflint** [comment]
> I think in that case you'd want to omit `library` from `appnexus`, since you want library imports to be considered first-party?

It is `appnexus` for the whole project, but an absolute first-party import when inside `library`.
