### ISSUE TITLE
extend-immutable-calls doesn't work on Python scripts (as opposed to modules)

### ISSUE THREAD

**Issue by fofoni** [astral-sh/ruff#10960]
Keywords: extend-immutable-calls, B008, script, module, `__main__`
Ruff version: 0.3.7

### Working MWE

In a directory containing just the file `test.py`:
```python
from other_module import A

def f(a=A()):
    pass
```
checking with:
```bash
ruff check --isolated --select=B008 \
    --config 'lint.flake8-bugbear.extend-immutable-calls=["other_module.A"]' \
    test.py
```
yields no errors.

### Buggy MWE

If I declare `A` in the script instead of importing it:
```python
class A: pass

def f(a=A()):
    pass
```
now ruff will find a B008 error in the `def` line, no matter what I configure in `extend-immutable-calls`. I tried `A`, `test.A`, `__main__.A`, and even `builtins.A` and `__builtins__.A`. Nothing makes it recognize `A()` as an immutable call.

**Comment by charliermarsh** [comment]
Hmm yeah... We need some way to identify `A`, and if you pass a script, we probably can't find a module root against which to resolve the path.

**Comment by charliermarsh** [comment]
`__main__.A` is kind of interesting.

**Comment by fofoni** [comment]
(Updated the OP to note that I also tried with `test.A`.)

> `__main__.A` is kind of interesting.

I tried `__main__.A` because I didn't know what would work and was exploring possibilities, but I'm not sure if like it: after all, depending on how you invoke Python, *any* .py file could be the `__main__` module. In the end, fully-qualified names aren't really well-defined statically -- you need to look them up in `sys.path` and follow import hooks etc (mypy can sometimes [run into a similar problem](https://github.com/pypa/setuptools/issues/3518)).

Since ruff interprets module paths statically, I think the best thing to do in this case would be to check that `test.py` is not contained in an import package (i.e. not alongside an `__init.__.py`) and then accept `test.A` as `A`'s fully-qualified name.

**Comment by charliermarsh** [comment]
That seems reasonable to me.
