### ISSUE TITLE
`ruff server` should support an optional TOML configuration file

### ISSUE THREAD

**Issue by snowsignal** [astral-sh/ruff#10985]
In addition to common Ruff configuration fields that were introduced in https://github.com/astral-sh/ruff/pull/10984, `ruff server` should support a configuration file that can be used to configure the linter and formatter. These will take priority over file-based settings by default, though an option to have file-based settings take priority should also be available to the user.

**Comment by GaetanLepage** [comment]
Shouldn't it simply use the parameters from `~/.config/ruff/ruff.toml` ? Do you plan to introduce a LS specific config file ?

**Comment by charliermarsh** [comment]
Yeah it will read and support that just like a CLI invocation. But some users will want to point to a specific configuration file, and we want to expose that (e.g.) in the VS Code settings pane.

**Comment by charliermarsh** [comment]
Thank you so much!
