### ISSUE TITLE
Formatter: include files that were formatted in the output

### ISSUE THREAD

**Issue by AdrianB-sovo** [astral-sh/ruff#10983]
It would be useful to have the files that were formatted when running `ruff-format`.
**Usecase:** I use the pre-commit config to run Ruff locally before each commit, but also on the CI **for all files**.
- Locally, I want to automatically change the files with the formatter on a commit.
- In the CI, I want to see what files are not correctly formatted if the format checking fails.

So, to be able to do this with the same config, I use `ruff-format` **without** the `--check` option, but then I don't get the list of formatted files.
With the `--check` option:
```
ruff.....................................................................Passed
ruff-format..............................................................Failed
- hook id: ruff-format
- exit code: 1

Would reformat: src/api/v1/endpoints/customers.py
1 file would be reformatted, 317 files already formatted
```

Without the `--check` option:
```
ruff.....................................................................Passed
ruff-format..............................................................Failed
- hook id: ruff-format
- files were modified by this hook

1 file reformatted, 317 files left unchanged
```

It's not a big problem, since I can run the formatter locally on all files, but I think it would still be nice to have the list of formatted files, either by default or by opting-in with an option.

I'm using ruff v0.3.6.

**Comment by charliermarsh** [comment]
I believe this is the same as https://github.com/astral-sh/ruff/issues/8953.
