### ISSUE TITLE
`invalid-length-return-type` (`PLE0303`) - false positive when `__len__` raises an exception

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#11023]
```py
class Foo:
    def __len__(): # error: `__len__` does not return a non-negative integer
        raise Exception
```
[playground](https://play.ruff.rs/ebb68cde-b0fe-4b8f-92dd-c9843cd80da4)

# use case

i have a subclass of a type from a 3rd party module that uses `__len__` in a very misleading way, so i want to ban people from using it on my subclass:
```py
from typing import override, Never

class Bar(Foo):
    @override
    def __len__() -> Never:
        raise Exception("__len__ is banned on this class")
```

**Comment by charliermarsh** [comment]
I believe this is fixed on `main`.

**Comment by charliermarsh** [comment]
Via #11017. Sorry about that.
