### ISSUE TITLE
[Panic] Unknow nvim error while working with python based project.

### ISSUE THREAD

**Issue by HoneyBeaver506** [astral-sh/ruff#11020]
This error appeared while I was working. I have no idea why, since I was not working with rust

**Comment by charliermarsh** [comment]
Are you able to share any more information? For example: the content of the error, or the content of the file that you were working on?

**Comment by HoneyBeaver506** [comment]
Thanks for the help. I am sorry If I missed any extra details. I already fixed the error but dont know how.
