### ISSUE TITLE
Configure `ruff server` in VS Code

### ISSUE THREAD

**Issue by xshapira** [astral-sh/ruff#11028]
Can we replace Pylance with `ruff server` in VS Code?

I'm not sure if it's possible, but I tried this:
```json
{
// Python
  "python.languageServer": "ruff",
}
```

**Comment by MichaReiser** [comment]
I'm not familiar with the setting but I don't think it makes sense to replace Pylance with Ruff today. Ruff's LSP only supports linting and formatting today whereas Pylance supports semantic highlighting, go to definition, rename, etc. 

Maybe in the future ;)

**Comment by dhruvmanila** [comment]
No, that's not possible. For reference, the setting comes from the [VS Code Python extension](https://github.com/microsoft/vscode-python) for which the documentation exists [here](https://code.visualstudio.com/docs/python/settings-reference#_code-analysis-settings).

**Comment by xshapira** [comment]
Thanks guys! Hope to see ruff evolving to the point where it'll replace pylance and mypy. 

The ruff team has been crushing it lately. You're doing great!
