### ISSUE TITLE
Rule E126 implemented?

### ISSUE THREAD

**Issue by chuan137** [astral-sh/ruff#11038]
my impression is that all the flake8 rules are implemented, but I didn't get [`E126`](https://www.flake8rules.com/rules/E126.html) rule work. tried to enable the rule
```
[tool.ruff.lint]
extend-select = ["E126", "E501"]
```
but got
```
Unknown rule selector: `E126`
```

**Comment by charliermarsh** [comment]
It looks like E126 is not implemented. You can see the list here: https://docs.astral.sh/ruff/rules/#error-e. It's tracked here: https://github.com/astral-sh/ruff/issues/2402.
