### ISSUE TITLE
FURB118 bug: incorrectly replaces 1 element tuple lambdas with itemgetter

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#11075]
There is a bad fixit generated by ruff for FURB118 with operator.itemgetter().

It tries to replace this line:
```python
            return lambda x: (x[index],)
```
with this line
```python
            return operator.itemgetter(index)
```
However, these are not equivalent, in the first instance, the code will return a 1 element tuple, while in the second one, it will just return that element.

**Comment by charliermarsh** [comment]
I'll take a look, thanks @Skylion007.
