### ISSUE TITLE
Allowed captalized arg names configuration for N803

### ISSUE THREAD

**Issue by Malachov** [astral-sh/ruff#11090]
# Feature request

## Description
It is common in data science to use capital letters in names (lowercase for vector, uppercase for matrix). Example: [X in fit function in sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression.fit)

This goes against N803, e.g. 'Argument name `X` should be lowercase`'

This leads to many warnings across data science codebases.

I know, that technically it is correct and it should be warned, but to be able to suppress it in `pyproject.toml` could be beneficial in some cases.

## Pylint comparison
Maybe something like [good-names](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#good-names) could be added. Should it solve only N803? Probably it could whitelist a lot of other rules as well, but I'm not sure.

## Note
If others don't think, that this is good idea, you can close it as maybe there should be issue rather on scikit-learn.

**Comment by charliermarsh** [comment]
As a hack, I think you could add it to https://docs.astral.sh/ruff/settings/#lint_dummy-variable-rgx -- but it's not really the intended use of that variable, and it will ignore other errors on variables named `X`.

I'd be open to adding something like `good-names`, but I'd probably want it to apply to all `N` rules for simplicity. Curious for more opinions though.

\cc'ing @AlexWaygood

**Comment by charliermarsh** [comment]
Oh yeah, IMO those suffice.

**Comment by charliermarsh** [comment]
I think those settings are sufficient to close this out.
