### ISSUE TITLE
`ruff server` does not respect `exclude` configuration

### ISSUE THREAD

**Issue by snowsignal** [astral-sh/ruff#11138]
At the moment, `ruff server` does not yet respect `exclude` configuration, either in the editor configuration or in workspace configuration. This may cause unexpected behavior when editing an excluded file.

**Comment by Hoxbro** [comment]
I also see a problem with `[tool.ruff.lint.per-file-ignores]` not being respected.

**Comment by charliermarsh** [comment]
Yeah that's not wired up yet, thanks -- filing separately here: https://github.com/astral-sh/ruff/issues/11185

**Comment by charliermarsh** [comment]
I think this should now be working, since we set the filename.
