### ISSUE TITLE
Undefined name `anext`

### ISSUE THREAD

**Issue by rgilton** [astral-sh/ruff#1117]
Running ruff 0.0.166 against this file:
```py
print(anext)
```
results in this error:
```
Found 1 error(s).
test.py:2:7: F821 Undefined name `anext`
```
`anext` is a [builtin in python 3.10](https://docs.python.org/3.10/library/functions.html?highlight=anext#anext), so I _think_ it should be supported by ruff?

**Comment by JonathanPlasse** [comment]
Will fix.

**Comment by charliermarsh** [comment]
This is going out in [v0.0.167](https://github.com/charliermarsh/ruff/releases/tag/v0.0.167) (building now).
