### ISSUE TITLE
ruff server not closing with neovim instances

### ISSUE THREAD

**Issue by akthe-at** [astral-sh/ruff#11207]
Ruff: 0.4.2
OS: Windows 10
Terminal: Wezterm - Latest Nightly
Shell: Powershell Core 7.4.2
Neovim Build - Latest nightly  (and each nightly over the past 3-4 days I've noticed this)

Hello All...I feel like this is going to be kind of a barebones bug report and I am sorry about that. 

I have been using the new ruff server in lieu of ruff_lsp with neovim and noticed that there might be an issue with ruff.exe not always being terminated when you close a neovim instance. I have tried to consistently reproduce the bug and I have failed but I noticed that every once in a while I can check my processes and there will be a plethora of ruff.exe running even though I might only have 1 or 2 neovim instances or buffers open. 

![image](https://github.com/astral-sh/ruff/assets/105152139/26938a06-3ed6-4f89-bd02-2809088466a9)

I don't think I ever noticed this during my time using ruff_lsp.

Love what you all do, just wanted to try and keep you aware since ruff server is in alpha.

**Comment by dhruvmanila** [comment]
Good catch! Thanks for opening this issue. It's happening on macOS as well. And it isn't specific to Neovim, I'm seeing it in VS Code as well.

https://github.com/astral-sh/ruff/assets/67177269/aff1c493-9b22-4168-a332-4a03724ed945

**Comment by ShIRannx** [comment]
The problem persists after ruff 0.4.3.

**Comment by snowsignal** [comment]
@ShIRannx I've found the cause for that and opened a follow-up fix: https://github.com/astral-sh/ruff/pull/11291.

**Comment by danielhollas** [comment]
Hi @snowsignal I am still seeing this problem with ruff 0.4.5 and neovim 0.9.5 on Linux Fedora 39.

**Comment by dhruvmanila** [comment]
@danielhollas Hi, can you open a new issue with the logs? I tried it on macOS with Ruff 0.4.5 and Nvim 0.10.0 and it works as expected. Can you also try it with Nvim 0.10.0?

**Comment by dhruvmanila** [comment]
No worries. You can find the file path using `vim.lsp.get_log_path()` function. You can then copy paste the relevant lines (usually would be at the end of the file) related to `ruff`.
