### ISSUE TITLE
PD003 triggers on any occurrence of `.isnull()`, not necessarily on a pandas dataframe

### ISSUE THREAD

**Issue by deepyaman** [astral-sh/ruff#11235]
* List of keywords you searched for before creating this issue: "isnull", "pandas-vet" (read through some of the issues, including one that says `pandas-vet` is like training wheels; that said, I think it's reasonable to expect it not to flag issues on non-pandas code)
* A minimal code snippet that reproduces the bug: https://github.com/ibis-project/ibis-ml/blob/87889d9857237425544a3a5dc41fce9e1ca7fe5d/ibisml/steps/impute.py#L13 (sorry, I'll try to update this to something more minimal later, but I think you can trigger it by calling `.isnull()` on literally anything)
* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag: Ran though pre-commit hook.
* The current Ruff settings (any relevant sections from your `pyproject.toml`): `PD` is selected.
* The current Ruff version (`ruff --version`): v0.3.2

I did also try type hinting my function (marking `col` as type `ir.Column`), but it didn't matter. Looking at the implementation of the rule, it seems to be a naive string match.

**Comment by charliermarsh** [comment]
Thanks for the clear issue. I think we should just merge this into https://github.com/astral-sh/ruff/issues/6432 though -- it's the same issue, we aren't correctly inferring that something is or isn't a DataFrame.
