### ISSUE TITLE
PT006 breaks test by removing tuple from parametrize

### ISSUE THREAD

**Issue by Pebin** [astral-sh/ruff#11243]
PT006 breaks test, removes tuple just from argnames but not from argvalues

```
@pytest.mark.parametrize(("thresholds",), [([0.6, 0.3],), ([],)])
```

is replaced as 
```
@pytest.mark.parametrize("thresholds", [([0.6, 0.3],), ([],)])
```

so now thresholds contains tuple of list. Shouldn't the fix remove also the brackets inside so the result would be:
```
@pytest.mark.parametrize("thresholds", [[0.6, 0.3], []])
```

command:
`ruff tests/test.py --fix`

ruff 0.4.2, no special settings needed, python 3.9

**Comment by jhbuhrman** [comment]
This is a serious breakage; `ruff --fix` introduces an error.

The `--fix` option should also "fix" (i.e. de-tuple) the parameter value if it de-tuples the `argnames` parameter in case of a single parameter.

Apart from that, I find the obligatory (non-configurable) special case of tuple/list-less `argnames` in case of a single parameter quite questionable. I would prefer yet another configuration item that controls this quite opiniated preference.
