### ISSUE TITLE
Can't run ruff when installed with pip target dir option

### ISSUE THREAD

**Issue by nunoh** [astral-sh/ruff#11246]
Can't run ruff when installed with pip [target dir option](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-t) `pip install ruff -t lib`

MRE
```bash
pip install -t ruff lib
PYTHONPATH=lib python -m ruff --help
```
breaks with 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "xxxxxxxxxxxxxx/lib/ruff/__main__.py", line 32, in <module>
    ruff = os.fsdecode(find_ruff_bin())
                       ^^^^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/lib/ruff/__main__.py", line 28, in find_ruff_bin
    raise FileNotFoundError(path)
FileNotFoundError: /xxxxx/.local/bin/ruff
```

Versions:
- ruff: 0.4.2
- pip:  23.2.1
- python: 3.11.7

**Comment by nunoh** [comment]
I tried the same MRE with different libraries without an issue, but now with your explanation I understand why it doesn't work for ruff. I just defaulted to invoking the binary directly rather. Thank you for taking the time to provide the info and congrats on such a great tool! Cheers

**Comment by jaraco** [comment]
I have this issue also, and it affects Python environments created by `pip-run`. `pip-run` uses `pip install --target` for its simplicity and ability to compose with other environments. In any case, shouldn't `find_ruff_binary` fail if it cannot reliably locate the binary? Before I re-write pytest-ruff not to use `ruff.find_ruff_binary`, would you consider some alternative approaches?

- Add support for `--target` installs by searching in a `bin` directory in the package root where `ruff` is installed (works even on Windows).
- Check that the "found" binary exists and if not, fall back to a PATH search (i.e. `shutil.which('ruff')`). Such a search would not find the binary in the `target` unless the user had also added the `bin` directory to the PATH.
- Simply error when the "found" binary doesn't exist.

**Comment by jaraco** [comment]
I see now that ruff does actually raise a `FileNotFoundError` if the "found" binary isn't present. I missed that nuance when looking at `pytest-ruff`.

I would have expected/hoped that `pip-run ruff -- !ruff` (binary invocation) would have worked, because it would bypass the Python shim, but it does not:

```
 draft @ pip-run ruff -- !ruff
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/jaraco/draft/ruff': [Errno 2] No such file or directory
```

That may just be a bug in pip-run, though, where it may not be resolving the `ruff` binary in the PATH.

**Comment by kserhii** [comment]
I also catch `FileNotFoundError`, but in my case it was related to the usage of ruff in docker container. 

In Dockerfile I am installing requirements under root user and then switching to another user.
In that case `ruff` binary is placed in `/usr/local/bin` while `find_ruff_bin` gives me `/home/user/.local/bin` folder.
The quick fix is to add environment variable `PYTHONUSERBASE=/usr/local`.
