### ISSUE TITLE
Workspace edits from `ruff server` commands occasionally fail in VS Code when operating on an yet-to-be-created file

### ISSUE THREAD

**Issue by snowsignal** [astral-sh/ruff#11248]
Steps to reproduce:

1. Disable VS Code auto-save.
2. Add `ALL` to the `select` setting in the extension
3. Create a new `.py` file, but don't save it yet.
4. Add this code to the file:
```py
import foo

def bar():
    unused = 4

```
5. Using the command palette (Ctrl/Cmd+Shift+P), repeatedly run `ruff.applyAutofix`.
6. The second time you run `applyAutofix`, you should see an error about a workspace edit that couldn't be applied.

**Comment by T-256** [comment]
I can't repro this in v0.4.5

**Comment by T-256** [comment]
I can't repro this in v0.4.5. If you are still able to repro this, could you also provide the logs?

**Comment by snowsignal** [comment]
@T-256 I think this was fixed in https://github.com/astral-sh/ruff/pull/11206. 😄 

The only caveat is that this fix involve omitting document versions from workspace edits, which I would like to add back eventually.
