### ISSUE TITLE
The official doc doesn't mentions that, is it safe to set a global same RUFF_CACHE_DIR for all projects?

### ISSUE THREAD

**Issue by chipzhang** [astral-sh/ruff#11279]
Hi, I am newbie to ruff.

By default, it creates a `.ruff_cache` in the root of every project. I feel this is very ugly.
I wanna set the the global env var RUFF_CACHE_DIR to point the cache dir to a subfolder of the system's cache dir.
But in this way, all projects will use the same cache dir.

Considering the default behavior (cache dir per project rather than one global cache dir), one may suspect, is it safe to use the same cache dir? Will conflicts occur? The official doc doesn't mention it. The doc should be more specific on this issue.
Thx!

**Comment by charliermarsh** [comment]
I think it should be fine, since within `.ruff_cache/${VERSION}`, we shard by Python package (and that's key based on the absolute path to the package).

**Comment by charliermarsh** [comment]
It's not recommended, but it should be safe.
