### ISSUE TITLE
`ARG001` False positive warning about unsed `args`, `kwargs`

### ISSUE THREAD

**Issue by mh-firouzjah** [astral-sh/ruff#11281]
While *args and **kwargs are commonly used to handle variable-length arguments and keyword arguments, there are cases where we intentionally do not use these variables directly inside the function body. For example, when overriding existing methods or implementing callback functions, *args and **kwargs may be part of the function signature for compatibility or flexibility without immediate usage in the implementation. In such scenarios, the apparent unused status of *args and **kwargs is intentional and not indicative of an issue. This linting warning can be considered a false positive in specific design contexts.

**Comment by charliermarsh** [comment]
What's the specific false positive that you're seeing? Note that if you mark a method with [`@typing.override`](https://docs.python.org/3/library/typing.html#typing.override), we already ignore `ARG` violations (same with methods marked as abstract, etc.).

**Comment by charliermarsh** [comment]
Oh, we have a setting for this, I think? [`ignore-variadic-names`](https://docs.astral.sh/ruff/settings/#lint_flake8-unused-arguments_ignore-variadic-names)
