### ISSUE TITLE
Human-friendly `noqa` directives

### ISSUE THREAD

**Issue by puddly** [astral-sh/ruff#11328]
Currently, `noqa` directives need to reference the exact rule prefix and code (e.g. `SLF001`):

```python
device._switch.connect()  # noqa: SLF001
```

It would be nice to reference the rule short name (as in the [documentation](https://docs.astral.sh/ruff/rules/private-member-access/)), as I personally have trouble keeping track of numerical rules:

```python
device._switch.connect()  # noqa: private-member-access
```

This is more of a feature request than a real issue so let me know if this is by design. If not, would you accept a PR implementing this?

**Comment by charliermarsh** [comment]
Thanks! We do intend to make this change and there's some discussion on it here: https://github.com/astral-sh/ruff/issues/1773. It hasn't been prioritized yet but there's a very high likelihood that we migrate to human-readable rule names.

**Comment by puddly** [comment]
Oops, sorry for the duplicate!

**Comment by charliermarsh** [comment]
All good, only takes me a sec, I know the issue tracker very well :)
