### ISSUE TITLE
[Fix error] PIE804 auto fix does not handle := 

### ISSUE THREAD

**Issue by njharman** [astral-sh/ruff#11371]
I believe the issue is ruff 0.4.4 PIE804 auto fix does not handle := with same name as dict key

```
        func(
              **{
                  "live": False,
                  "url_foo": (url_foo := "http://custom.com"),
                  "url_bar": (url_bar := "http://bespoke.com"),
              },
          )

```

**Comment by zanieb** [comment]
What happens? No fix is offered? The fix is incorrect?

**Comment by trag1c** [comment]
Seems like Ruff fixes this as
```py
func(
      live=False,
      url_foo=url_foo := "http://custom.com",
      url_bar=url_bar := "http://bespoke.com",
)
```

**Comment by njharman** [comment]
> What happens? No fix is offered? The fix is incorrect?

Ruff fixed, found syntax error then reverted fix (without showing it (or maybe I'm blind?)) and asked me to kindly report it.

**Comment by charliermarsh** [comment]
I think they just need to be parenthesized.
