### ISSUE TITLE
Add a rule to catch int(round(...)

### ISSUE THREAD

**Issue by NeilGirdhar** [astral-sh/ruff#11412]
`int(round(x))`and  `int(round(x, 0))` and `int(round(x, None))` can all simply be written `round(x)`.  However, unnecessary casts to `int` are [prevalent](https://sourcegraph.com/search?q=context%3Aglobal+int%28round%28&patternType=keyword&sm=0&filters=%5B%5B%22lang%22%2C%22Python%22%2C%22lang%3Apython%22%5D%5D).  Please consider adding a rule to catch these?

**Comment by zanieb** [comment]
Seems reasonable to me. `unnecessary-round-cast` or something?

**Comment by Skylion007** [comment]
This sounds like a good refurb rule. @dosisod
