### ISSUE TITLE
Feature Request: Move type-only imports to `TYPE_CHECKING` block

### ISSUE THREAD

**Issue by thejcannon** [astral-sh/ruff#11447]
Howdy! 👋 

Along the lines for formatting/fixing and import sorting and import removing, it'd be really nice if there was a tool (`ruff` could do it 😉 ) that would keep track of which imports were only used for type annotations and would move them to `if TYPE_CHECKING` blocks and replace their usage with string annotations.

(Once this feature is implemented, there's probably a related feature that moves imports out of `TYPE_CHECKING` if they are used for realsies).

This would have actual tangible benefits (as opposed to just stylistic ones) as some modules are expensive to import.

Thanks y'all.

**Comment by charliermarsh** [comment]
I believe we already support this via the flake8-type-checking rules, which support autofix: https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch

**Comment by charliermarsh** [comment]
There’s also a quote annotations setting: https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_quote-annotations
