### ISSUE TITLE
[Question] Ruff server wraps line

### ISSUE THREAD

**Issue by qmmp123** [astral-sh/ruff#11504]
I'm using neovim with nvim-lspconfig. Ruff server wraps the line when it exceeds 88 chars but in pyproject.toml I've set `line-length` to 120. What can I do to avoid wrapping line?
cmd - ruff server --preview
pyproject.toml
```toml
[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "superset-frontend",
    "superset-embedded-sdk",
    "sqllab"
]

src = ["superset"]

# Same as Black.
line-length = 120
indent-width = 4
fix = false

# Assume Python 3.8
target-version = "py38"

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = []
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
```

ruff version 0.4.4

**Comment by snowsignal** [comment]
Hi @qmmp123! Thank you for opening this issue.

Could you clarify what you mean by "`ruff server` wraps the line"? Are you saying that the editor soft wraps the line once it reaches 88 characters? Or are you getting a `line too long` diagnostic once the line goes past 88 characters?

Thanks again!

**Comment by qmmp123** [comment]
Hi @snowsignal . Yeah. The editor soft wraps the line once it reaches 88 characters

**Comment by snowsignal** [comment]
@qmmp123 This sounds like a Neovim problem, not an issue with the language server. Does resizing the window to be wider change when the line soft-wraps?

If not, what does your Neovim configuration look like?

**Comment by qmmp123** [comment]
@snowsignal I don't know where is the problem, but enabling ruff in nvim-lspconfig causes this problem. That's why I've created issue in this repo

**Comment by qmmp123** [comment]
@snowsignal I don't know where is the problem, but enabling ruff in nvim-ispconfig causes this problem. That's why I've created issue in this report.
There are too many lines in my init.vim. I post only part where I'm enabling ruff
```lua
local lsp = require('lspconfig')
lsp.clangd.setup{}
lsp.rust_analyzer.setup{}
lsp.cmake.setup{}
lsp.gopls.setup{}
lsp.pyright.setup{
    settings = {
        pyright = {
          disableOrganizeImports = true,
        },
        python = {
            analysis = {
                ignore = { '*' },
            },
        },
    },
}
lsp.ruff.setup{
    cmd = {"ruff", "server", "--preview", "--verbose"}
}
lsp.tsserver.setup{}
lsp.html.setup{}
```

**Comment by dhruvmanila** [comment]
> The editor soft wraps the line once it reaches 88 characters

If this happens while you're typing, you might want to checkout the value of `textwidth` and whether you've the `t` option enabled for `formatoptions`. Run this on the command-line in Neovim:

```lua
vim.print(vim.bo.textwidth)
vim.print(vim.bo.formatoptions)
```

If `textwidth` is greater than 0 and you've `t` in `formatoptions`, the editor will auto-wrap the lines.

@qmmp123 Can you try this and let us know?

**Comment by qmmp123** [comment]
@dhruvmanila I'm sorry. My settings causes the problem. Thank you

**Comment by dhruvmanila** [comment]
No worries. Glad to hear it's sorted :)
