### ISSUE TITLE
`ruff server`: duplicate code actions

### ISSUE THREAD

**Issue by ravibrock** [astral-sh/ruff#11516]
```md
ruff
    An extremely fast Python linter and code formatter, written in Rust.

    installed version 0.4.5                              
    homepage          https://github.com/astral-sh/ruff/ 
    languages         Python                             
    categories        Linter, Formatter, LSP             
    executables       ruff                               
```

I switched from `ruff-lsp` to `ruff` today in Neovim and noticed that there were duplicate code actions (that as far as I can tell work identically):
<img width="508" alt="Screenshot 2024-05-23 at 09 50 22" src="https://github.com/astral-sh/ruff/assets/66334356/9de1c807-9205-42b8-b262-a6f1146e4f71">
(Note: It appears to only be the `organize imports` and `fix all auto-fixable problems` that are duplicated. The `disable for this line` action only appears once, as it should.)

I tried searching "duplicate code action".

I confirmed that `ruff-lsp` is *not* installed anymore:
<img width="601" alt="Screenshot 2024-05-23 at 09 51 31" src="https://github.com/astral-sh/ruff/assets/66334356/8c7d6119-f014-474f-837e-b8e82d058cf6">

Minimal `ruff` configuration:
```lua
local on_attach = function(client, _)
    if client.name == "ruff" then
        client.server_capabilities.hoverProvider = false
    end
end
require("mason-lspconfig").setup({
    ensure_installed = { "ruff" },
     ["ruff"] = function()
         require("lspconfig").ruff.setup({ on_attach = on_attach })
     end,
})

**Comment by dhruvmanila** [comment]
It seems like a bug in that the Notebook actions are not being filtered correctly?

https://github.com/astral-sh/ruff/blob/52c946a4c5c1600b45062940c76bd9fde35afd11/crates/ruff_server/src/server/api/requests/code_action.rs#L48-L72
