### ISSUE TITLE
`ruff server`: Unable to edit new, untitled files in VS Code

### ISSUE THREAD

**Issue by T-256** [astral-sh/ruff#11510]
VSCode Repro: `Ctrl+Win+Alt+N` -> select `Python File`

Output:

> ```
> 2024-05-23 13:52:40.699 [info] Name: Ruff
> 2024-05-23 13:52:40.700 [info] Module: ruff
> 2024-05-23 13:52:40.700 [info] Python extension loading
> 2024-05-23 13:52:40.700 [info] Waiting for interpreter from python extension.
> 2024-05-23 13:52:40.700 [info] Python extension loaded
> 2024-05-23 13:52:40.700 [info] Server run command: c:\Users\User\Desktop\test\.venv\Scripts\python.exe c:\Users\User\.vscode\extensions\charliermarsh.ruff-2024.22.0-win32-x64\bundled\tool\ruff_server.py server --preview
> 2024-05-23 13:52:40.700 [info] Server: Start requested.
> 2024-05-23 13:52:41.180 [info] [Trace - 1:52:41 PM] Received request 'client/registerCapability - (1)'.
> 2024-05-23 13:52:41.180 [info] [Trace - 1:52:41 PM] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
> 2024-05-23 13:52:41.180 [info]    0.139395s INFO ruff_server::server Configuration file watcher successfully registered
> 
> 2024-05-23 13:52:41.736 [info]    0.695387s WARN ruff_server::server::api Received notification $/setTrace which does not have a handler.
> 
> 2024-05-23 13:52:41.770 [info]    0.729158s ERROR ruff_server::server::api An error occurred while running notebookDocument/didOpen: expected notebook URI untitled:Untitled-1.ipynb?jupyter-notebook to be a valid file path
> 
> 2024-05-23 13:52:41.802 [info]    0.757168s WARN ruff_server::server::api Received notification $/setTrace which does not have a handler.
> 
> 2024-05-23 13:52:43.029 [info]    1.956011s WARN ruff_server::server::api Received notification $/setTrace which does not have a handler.
> 
> 2024-05-23 13:52:43.361 [info]    2.319372s WARN ruff_server::server::api Received notification $/setTrace which does not have a handler.
> 
> 2024-05-23 13:52:43.698 [info]    2.657468s WARN ruff_server::server::api Received notification $/setTrace which does not have a handler.
> ```

**Comment by snowsignal** [comment]
Thank you for opening this issue! I've made a small change to the issue title if that's okay with you 🙂

**Comment by snowsignal** [comment]
Right, at the moment the code assumes that text document URIs point to valid file paths. We'll have to rework how documents are indexed to fix this.
