### ISSUE TITLE
new rule: useless `r` string

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#11525]
we have [`F541`](https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/) which reports useless `f` strings, so it would be nice if there was a rule for `r` strings as well:
```py
foo = r"foo" # error: r prefix is not necessary

def bar():
    r"""bar""" # error: r prefix is not necessary
```

**Comment by moonlightaria** [comment]
going to start work on this

**Comment by Skylion007** [comment]
This is covered partially by: https://github.com/astral-sh/ruff/issues/8616
