### ISSUE TITLE
flake8-to-ruff tool produces config with warning

### ISSUE THREAD

**Issue by dwreeves** [astral-sh/ruff#11544]
Input:

```shell
echo -e "[flake8]\nmax-line-length = 100" > .flake8
pip install flake8-to-ruff
flake8-to-ruff .flake8    
```

Output:

```toml
[tool.ruff]
ignore = []
line-length = 100
select = [
    "E",
    "F",
    "W",
]
```

Using this config produces the following warning:

```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
```

**Comment by charliermarsh** [comment]
Thank you! Unfortunately we no longer support `flake8-to-ruff` -- we removed references to it from our own docs and removed it from Ruff itself. I'll try to add a note to `flake8-to-ruff` itself; that may require me to release, in which case, we'll try to fix it too.

**Comment by dwreeves** [comment]
Ah, that makes sense. I was wondering where it was in the code.

The warning is really minor and probably isn't worth making a code change over, since you're a busy guy and resurfacing old code is annoying. My $0.02 is, a more important change to the package, if you want to update the README would just be a note at the top of the README something like this:

```markdown
> **⚠️ Warning: `flake8-to-ruff` is no longer supported.** The last Ruff version supported by flake8-to-ruff was v0.0.233. You may experience warnings or breakage using this tool for later versions of Ruff.
```

And this captures not only the aforementioned warning but all other warnings.

v0.0.233 was released Jan 24, 2023: https://github.com/astral-sh/ruff/releases/tag/v0.0.233 which is the release of the PyPI project https://pypi.org/project/flake8-to-ruff/, hence why I am using that version. Although you may have a better idea of what version is better to say is supported.

**Comment by charliermarsh** [comment]
Appreciate it! 👍 Yeah I think I need to do a release to add that warning anyway, so was considering just fixing it while I was going through the effort.

**Comment by charliermarsh** [comment]
But I'll see how much trouble it causes me.

**Comment by charliermarsh** [comment]
Added the warning!

**Comment by dwreeves** [comment]
half a day turnaround on a goofy and mostly inconsequential request on a Sunday, that's why you're the GOAT
