### ISSUE TITLE
Formatter changes order of comments.

### ISSUE THREAD

**Issue by randolf-scholz** [astral-sh/ruff#11569]
```python
class Foo:
    # comment 1
    @abstractmethod
    def foo(self) -> None: ...
    @abstractmethod
    def bar(self) -> None: ...
    # comment 2

    # comment 3
    def baz(self) -> None:
        return None
    # comment 4
```

becomes

```python
class Foo:
    # comment 1
    @abstractmethod
    def foo(self) -> None: ...
    @abstractmethod
    def bar(self) -> None: ...

    # comment 3
    # comment 2
    def baz(self) -> None:
        return None

    # comment 4
```

[[ruff-playground]](https://play.ruff.rs/90543207-c186-4bb6-b5f6-a658d65c31c6)

1. Comments 2 and 3 get swapped.
2. An extra space is inserted after `def bar`. Since these are stubs, no space should be inserted. (for instance, comment 1/2 can be  `# region`/`#endregion`). But this is just my opinion.

**Comment by MichaReiser** [comment]
You're good at finding comment reordering bugs and thank you so much at taking the time to report them! 

Uhh, the second one is really bad. Let me have a look.

**Comment by MichaReiser** [comment]
To make it worse, this is not even related to classes nor does it require decorators. https://play.ruff.rs/2bcde006-72e6-409f-9fa9-659ef78d7944

**Comment by randolf-scholz** [comment]
I would suspect this is somehow related to special logic for formatting stub implementations https://github.com/astral-sh/ruff/issues/8357

**Comment by MichaReiser** [comment]
Yeah, that's a great observation. The issue is that, for stubs, we don't write extra empty lines between the comment and the next function, which drips over the formatting.

**Comment by MichaReiser** [comment]
@randolf-scholz thanks for debugging this together. The fix turned out to be not that bad :)
