### ISSUE TITLE
Should `[lint.flake8-implicit-str-concat] allow-multiline = false` implicitly disable `ISC003` ?

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#11582]
With `allow-multiline = true`, `ISC002` doesn't raise. Should this be reflected on `ISC003` as well? The doc mentions that
https://docs.astral.sh/ruff/settings/#lint_flake8-implicit-str-concat_allow-multiline
> Note that setting allow-multiline = false should typically be coupled with disabling explicit-string-concatenation (ISC003). Otherwise, both explicit and implicit multiline string concatenations will be seen as violations.

I feel like this burden could be lifted from the user, and allowing `--select=ISC` rather than this awkward juggling of `--select=ISC --ignore=ISC003` or `--select=ISC001,ISC002`

**Comment by charliermarsh** [comment]
Seems reasonable to me.
