### ISSUE TITLE
error from version 4.3 on Windows 7

### ISSUE THREAD

**Issue by melassa** [astral-sh/ruff#11597]
From version 4.3 ruff.exe on Windows 7 with python 3.8 generates a 0C0000005 error when launched.
It is no more compatible? I do not see anything in the ruff changelog.

**Comment by MichaReiser** [comment]
I think that's due to https://github.com/astral-sh/ruff/pull/11260 and Rust now requiring [Win 10](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#compatibility-notes)

**Comment by melassa** [comment]
Yes, I see, Rust 1.78 requires W10. A note on the changelog?

**Comment by MichaReiser** [comment]
Yeah, that seems reasonable and I should probably have waited with this change until Ruff 0.5.
