### ISSUE TITLE
Darker style --diff formatting

### ISSUE THREAD

**Issue by JoshuaSchlucke** [astral-sh/ruff#11599]
I couldn't find any infos on that so it is propably not possible, but it would be nice for older projects etc. to be able to introduce 
linting and formatting slowly like with darker for black, would be cool if ruff had it built in

**Comment by charliermarsh** [comment]
Thanks! There's more discussion around this and related ideas in https://github.com/astral-sh/ruff/issues/1149 so I'm going to merge into that.
