### ISSUE TITLE
C400 unsafe fix is more unsafe than the documentation suggests

### ISSUE THREAD

**Issue by simonpercivall** [astral-sh/ruff#11603]
Ruff 0.45

The C400 unsafe fix says that that it sometimes drops comments. It may also generate broken code:

`ruff check fix --unsafe-fixes --select C400`
```python
list(
    (1 for _ in range(1))
)
```

expected
```python
[
    1 for _ in range(1)
]  # [1]
```

actual
```python
[
    (1 for _ in range(1))
]  # [<generator object <genexpr> at ...>
```

**Comment by charliermarsh** [comment]
👍 Yeah that's a bug (rather than a question of fix safety). Thanks.
