### ISSUE TITLE
Fix isort break the indent-width

### ISSUE THREAD

**Issue by nasyxx** [astral-sh/ruff#11606]
ruff.toml
```toml
indent-width = 2

[lint]
select = ["I"]
```

Original

```python
# xx.py
from math import (
  sin,
  tan,
  cos,
  nan,
  pi,
)

del sin, cos, tan, pi, nan
```

Run

`ruff check --fix xx.py`

Except sorted and 2 spaces indent imports.

```python
from math import (
  cos,
  nan,
  pi,
  sin,
  tan,
)

del sin, cos, tan, pi, nan
```

Now, there are extra 2 spaces before cos, nan, ...

```python
from math import (
    cos,
    nan,
    pi,
    sin,
    tan,
)

del sin, cos, tan, pi, nan
```

```
ruff: 0.4.5
python: 3.12.2
```

**Comment by charliermarsh** [comment]
I guess I'll consider this a bug; it does work as expected if you have an indented statement in the file:

```python
# xx.py
from math import (
  sin,
  tan,
  cos,
  nan,
  pi,
)

del sin, cos, tan, pi, nan

if True:
  x
```

I'm unsure if we should respect `indent-width` vs. inferring the width from the file.

**Comment by nasyxx** [comment]
Yes. I encountered this problem when writing a `__init__` file.
