### ISSUE TITLE
new rule - enforce that `__init__.py` files are empty

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#11631]
putting any code in `__init__.py` files is a bad idea, because they are unnecessarily imported when you import any modules in the same folder:

```py
# ./package1/__init__.py
from package2.baz import baz
```
```py
# ./package1/bar.py
bar = 1
```
```py
# ./package2/baz.py
from package1.bar import bar
baz = 2
```
```py
# ./package2/main.py
from package2.baz import baz
```

in this example, running `python package2/main.py` crashes with a circular import error, because `package1.__init__` is imported even though none of the other files are explicitly importing from it.

it's absurd that the language would implicitly import a file that was not requested at all, so it would be nice if there was a rule to enforce that `__init__.py` files are empty.

**Comment by charliermarsh** [comment]
I believe this can be merged with https://github.com/astral-sh/ruff/issues/9848.
