### ISSUE TITLE
Implement a new rule for FastApi routes

### ISSUE THREAD

**Issue by TomerBin** [astral-sh/ruff#11637]
Hi there,

I recently came up with the idea to remove the redundant usage of the response_model keyword in FastAPI routes. FastAPI looks at the return type annotation of the decorated function by default, so using response_model while having a return type annotation with the same value is a code duplication that should be avoided.

As someone new to Rust and contributing to Ruff, I took this opportunity to learn and implemented this rule in #11579. If you find this rule aligns with Ruff’s goals, I would kindly ask for a code review.

Thank you!
Tomer Bin

**Comment by hxyannay** [comment]
As someone who uses FastAPI and did not know about this code duplication (unfortunately exists in my repository) I would love for that rule to be implemented! 👍

**Comment by yannayh** [comment]
As someone using FastAPI that had no idea that this is a code duplication (which exists in my project unfortunately 😅) I would love for this rule to be implemented 👍🏼

**Comment by TomerBin** [comment]
Hi @charliermarsh ,

Thanks for all the great work on Ruff! I noticed your comments about the benefits of bundling many rules that are not codebase specific [in here](https://github.com/astral-sh/ruff/issues/283#issuecomment-1403025627), is the current approach since there are no plugin system for Ruff at the moment. 

I get that my PR #11579 is FastAPI-specific, but I think it helps by removing redundant response_model usage and cleaning up the code. Hopefully, it fits with Ruff’s goals of improving code quality and efficiency (and non FastApi users shouldn't be affected by that 😄 )

I’d really appreciate it if you could take a look and share any feedback.

Thanks!
Tomer

**Comment by charliermarsh** [comment]
Added in #11579 -- thanks @TomerBin!
