### ISSUE TITLE
[red-knot] representation of public symbols and types, independent of full symbol tables / definitions / CFG

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11658]
When doing type inference within a module, we need full symbol tables, definitions, and CFG. (We could also possibly build these more lazily/granularly, e.g. not descend into functions unless/until we are actually type checking them.)

But we want to be able to persistent-cache types for public symbols in a module (that is, symbols accessible to other modules), and (if the module and it's dependencies haven't changed) load this info from cache and use it as a dependency for checking other modules, without needing an AST for this module, or full symbol tables, or definitions (which reference AST), or CFG (which also references AST.)

This means somehow splitting our symbol table representation to make this possible.

**Comment by MichaReiser** [comment]
I think most of what's mentioned in here is complete. Wdyt?
