### ISSUE TITLE
[red-knot] make Definition Copy

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11660]
Definition is lightweight: basically it's just a wrapper around an AST node reference (except for import definitions, which we currently abstract a bit more from the AST.) And we already clone them pretty freely. But they aren't Copy, because the import variants include names, which might be heap-allocated strings if they are long.

Definition should either be Copy, or it should be interned. Preferably it should be Copy. The simplest approach might be to just change how we represent import definitions so we point to the AST instead of storing names.

**Comment by MichaReiser** [comment]
I did this as part of the salsa refactor
