### ISSUE TITLE
[red-knot] O(1) AST node reference lookup

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11661]
Definitions need to reference AST nodes, but actual references would require dealing with lifetimes, which is awkward given our database structure. Arc would be another option, but our AST doesn't use it internally, so that doesn't work either.

Currently we use `NodeKey`, which is just a node kind and text range, and requires binary search (at best) to find the node again. This is too slow.

We could use a struct that wraps an Arc to the root node of the AST and a raw pointer to the exact node. Since the whole AST is transitively owned by the root node, and ASTs are immutable, this can allow us to safely de-reference the raw pointer.

Or another solution might turn up as part of the salsa transition (e.g. we might decide to transform the AST into our own representation, which could use Arc internally?)

**Comment by MichaReiser** [comment]
I did this as part of the salsa refactor
