### ISSUE TITLE
[red-knot] name resolution for non-local variables

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11663]
Currently we only handle local and global names, not nonlocals.

**Comment by alex** [comment]
Does this include resolution for local variables used in comprehensions?

**Comment by carljm** [comment]
> Does this include resolution for local variables used in comprehensions?

It should, yes. But this issue (and everything tagged `red-knot` on this repo) is for the under-development and very early-stages type checker, not relevant to the currently-shipping ruff linter. So if you're seeing a problem in ruff related to comprehension vars, that should be a separate issue.

**Comment by alex** [comment]
Oh I understand the state of red knot. I've just been poking at it for fun
:-)

**Comment by carljm** [comment]
Oh, awesome!! Also, hello, it's been a while, good to see you around :)

**Comment by alex** [comment]
You too!
