### ISSUE TITLE
Misleading error for non-existing directory when checking format

### ISSUE THREAD

**Issue by Holt59** [astral-sh/ruff#11677]
When running `ruff format --check XXX` on a directory that does not exist, the error currently is

> error: Failed to format tests: The system cannot find the file specified. (os error 2)

This is a bit misleading since this was just checking format, not actually formatting, should be "Failed to check format for" or something like that.

Ruff Version: 0.4.7

**Comment by charliermarsh** [comment]
Candidly I think this is ok. With `--check`, the first step is to format the file, we just don't write the formatted file to-disk. So it is true that formatting failed. If `--check` fails for other reasons (e.g., if we failed to parse the file), we show a different message based on that failure.
