### ISSUE TITLE
PLR6104 rewrites numbers w/o the base indicator

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#11672]
input
```py
test = 0x5
test = test + 0xBA

test2 = b""
test2 = test2 + b"\000"
```

Run ` ruff check --fix --unsafe-fixes --preview --select=PLR6104 --isolated`

output
```py
test = 0x5
test += 186

test2 = b""
test2 += b"\x00"
```

Ruff version 0.4.7

**Comment by charliermarsh** [comment]
Yeah, common theme with `Generator` usage, we don't preserve verbatim numbers.

**Comment by dhruvmanila** [comment]
Once #11457 is completed, this can be solved by including number related flags on `TokenFlags`, propagating it to the `NumberLiteral` node and using that in the `Generator`. This would be similar to the flags on the string nodes. This is actually one of the potential use-case me and Micha discussed for `TokenFlags`.
