### ISSUE TITLE
[red-knot] store child scopes using a Range instead of a Vec

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11681]
(idea from Micha)

Instead of `Scope::children` being a vec of scope IDs, it could just be a Range of descendants (because descendant scopes of a given scope should all be interned contiguously). This would mean that finding direct children would require filtering on the descendants' parent scope ID, but it would avoid allocating (and deallocating) all those vectors.

**Comment by MichaReiser** [comment]
I did this in the salsa refactor
