### ISSUE TITLE
Does ruff server support "hover"?

### ISSUE THREAD

**Issue by KiYugadgeter** [astral-sh/ruff#11719]
Does ruff sever support hover now?
Or, Will it support?

Now I cannot move from pyright because ruff-lsp does not support hover feature in vim-lsp.  
[vim-lsp](https://github.com/prabirshrestha/vim-lsp) does not support changing hoverProvider to false like neovim's example in README in ruff-lsp.  
Hence I want ruff server to support  hover correctly.

**Comment by dhruvmanila** [comment]
The server does support the hover feature but not in the same way as other language servers like Pyright. Ruff only detects `noqa` comments and it'll provide the rule documentation. Refer https://github.com/astral-sh/ruff/issues/10595 for a screenshot on what it looks like.

In the future, we'd like to expand it's capability to support providing information for symbols like variables, functions, etc.

Unfortunately, I don't know if it's possible to change the server capability in `vim-lsp` similar to how it's done in Neovim. I would suggest to open an issue in `vim-lsp` to check if it's possible as of today or as a feature request.

**Comment by charliermarsh** [comment]
ruff server is intended to be used alongside Pyright since it's primary purpose is enabling formatting and lint fixes in the editor -- it's not a replacement for Pyright right now.
