### ISSUE TITLE
Server: Debug command

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#11715]
Maybe ruff extension could provide a command to show current server info? This will be helpful to debugging.

_Originally posted by @yanyongyu in https://github.com/astral-sh/ruff/issues/11674#issuecomment-2144207242_

Goal: Add a LSP command to collect debugging relevant information (platform, architecture, server, number of open files, number of open workspaces, the values of the most important settings, ...)

**Comment by dhruvmanila** [comment]
Related: https://rust-analyzer.github.io/manual.html#status

**Comment by dhruvmanila** [comment]
I think a simple implementation to show Ruff's executable path and version number would be useful to begin with.

**Comment by rainzee** [comment]
> I think a simple implementation to show Ruff's executable path and version number would be useful to begin with.

In vsc's extension, the binary that use for ruff finds from different places until fallback(use bundled), but the information is missing in the output message, is it possible to add the path and version number of the binary that is currently using ruff in the output message?

**Comment by dhruvmanila** [comment]
> In vsc's extension, the binary that use for ruff finds from different places until fallback(use bundled), but the information is missing in the output message, is it possible to add the path and version number of the binary that is currently using ruff in the output message?

Which output message are you referring to? The goal for this issue is to implement that "output message" functionality. But to answer your question, yes we will be including that information in the message.
