### ISSUE TITLE
FAQs give incorrect example of a top-level settings 

### ISSUE THREAD

**Issue by keikoro** [astral-sh/ruff#11722]
The FAQ section ["How does Ruff's import sorting compare to isort"](https://docs.astral.sh/ruff/faq/#how-does-ruffs-import-sorting-compare-to-isort) contains a `pyproject.toml` example config to demonstrate the `known-first-party` setting.

Included in this example config is the top-level `src` setting (+ comment noting it is a top-level setting), which is _not_ preceded by the correct/required heading, `[tool.ruff]`. Instead, it sits right below lint-specific settings, which makes the explanatory comment sound confusing and may mislead users with regard to where `src` can/needs to be set.

[Docs/FAQ source](https://github.com/astral-sh/ruff/blob/2b28889ca9d7935488875b5c944a159a2db20a23/docs/faq.md?plain=1#L276-L295)

**Comment by keikoro** [comment]
@MichaReiser I just had another look at the FAQ and saw that in the next section, [How does Ruff determine which of my imports are first-party, third-party, etc.?](https://docs.astral.sh/ruff/faq/#how-does-ruff-determine-which-of-my-imports-are-first-party-third-party-etc), `src` is actually explained in detail.

Is it possible the example for `known-first-party` was originally intended for that section? Or was the idea to provide a complete/working if minimal example for how to configure Ruff for isort?

My suggestion would be to move the (corrected) example away from where it's currently at and into the next FAQ section (minus the then redundant explanatory comment). If readers of the isort section should be made aware the next point is sort of a continuation of the wider topic, or that it includes a fuller example, I could briefly mention that.

**Comment by keikoro** [comment]
Ping, @MichaReiser.

**Comment by charliermarsh** [comment]
Thanks @keikoro -- I think that's the right diagnosis. Updated here to match your suggestion: https://github.com/astral-sh/ruff/pull/11829.
