### ISSUE TITLE
Bug: formatting a multiline string twice gets changing results

### ISSUE THREAD

**Issue by jasikpark** [astral-sh/ruff#11724]
This was found via the `fuzz/ruff_formatter_idempotency.rs` fuzz target; It should be reproducible with standard ruff format.

Ruff was built from source around (https://github.com/astral-sh/ruff/commit/2b28889ca9d7935488875b5c944a159a2db20a23)

Original code: 

```

'''
\u{15}

'''
```

Formatted once:

```
"""
u{15}
"""

```

Formatted twice:

```
"""
u{15}"""

```

Original fuzz crash error:

```
thread '<unnamed>' panicked at fuzz_targets/ruff_formatter_idempotency.rs:31:17:

Reformatting the code a second time resulted in formatting changes.
Input: "\n'''\n\u{15}\n\n'''"
First: "\"\"\"\n\u{15}\n\"\"\"\n"

Second: "\"\"\"\n\u{15}\"\"\"\n"
diff:
--- Formatted Once
+++ Formatted Twice
@@ -1,3 +1,2 @@
 """
-
-"""
+"""
```

**Comment by MichaReiser** [comment]
Hmm, I'm having a hard time reproducing this issue. The  original code mentioned in this issue isn't valid syntax and can't be formatted (not a valid unicode escape sequence) ([playground](https://play.ruff.rs/0e161383-1617-473c-86ac-fe2453019e77)). 

I then tried to replace `\u{15}` with the corresponding ascii character, but that gets formatted correctly and in a stable way https://play.ruff.rs/3199caf0-e3ae-4d36-ac18-da00822c6af7

**Comment by jasikpark** [comment]
True original code:

```

'''


'''
```

Formatted once

<img width="583" alt="Screenshot 2024-06-04 at 9 50 31 AM" src="https://github.com/astral-sh/ruff/assets/10626596/45ffcc08-1556-4ac6-8a1d-1f929e1f67d6">

Formatted twice

<img width="579" alt="image" src="https://github.com/astral-sh/ruff/assets/10626596/17e9a42f-8f27-4e2a-87a8-8c30f607fc2e">

**Comment by MichaReiser** [comment]
Hmm, I'm still struggling. Would you mind clicking on the Share button in the playground (of the original code) and share the link here?

**Comment by jasikpark** [comment]
Original: https://play.ruff.rs/797a9277-6c6f-4c35-bc88-fa0d5da9d950

First format: https://play.ruff.rs/53a83f3e-a05e-4366-99f4-7de25b880266

Second format: https://play.ruff.rs/066f3b1c-4130-4590-9576-e025b147c689
