### ISSUE TITLE
`Ruff: Fix all auto-fixable problems` erroring out in VSCode

### ISSUE THREAD

**Issue by MadhavVij** [astral-sh/ruff#11744]
## Error When Running `Ruff: Fix all auto-fixable problems` in VSCode

When running `Ruff: Fix all auto-fixable problems` in VSCode, I get an error:
```
Failed to apply Ruff fixes to the document. Please consider opening an issue with steps to reproduce.
```

Looking at the logs in Output/Ruff, the detailed error is:
```
2024-06-04 17:48:48.138 [info] ┐ruff_formatter::printer::Printer::print{}

2024-06-04 17:48:48.138 [info] ┘

2024-06-04 17:48:48.138 [info] [Trace - 5:48:48 PM] Received response 'textDocument/formatting - (30)' in 0ms.
2024-06-04 17:49:51.866 [info] [Trace - 5:49:51 PM] Sending request 'workspace/executeCommand - (31)'.
2024-06-04 17:49:51.866 [info]  166.145599s WARN ruff_server::session::index No settings available for vscode-userdata:/Users/<user_name>/Library/Application%20Support/Code/User/settings.json - falling back to default settings

2024-06-04 17:49:51.867 [info]  166.146100s ERROR ruff_server::server::api An error occurred with result ID 31: Document snapshot not available for vscode-userdata:/Users/<user_name>/Library/Application%20Support/Code/User/settings.json
```

-----
I was able to find the original string in the code here, in case it helps resolving it:

https://github.com/astral-sh/ruff/blob/d056d09547c5fe7ff5e787ada19fc37a73d9b444/crates/ruff_server/src/server/api/requests/execute_command.rs#L61

### Keywords Searched
- VSCode
- Document
- Snapshot

### Version Information
- `ruff --version`: `ruff 0.4.7`

Please let me know if you need any more information to help resolve this issue.

**Comment by snowsignal** [comment]
@MadhavVij Thank you for opening this issue!

I think I was able to reproduce this issue by opening the user settings JSON file in VS Code and then attempting to run `Ruff: Fix all auto-fixable problems` while it was selected. Did you have the user settings JSON file open when running this command?

If you are, then that's probably the issue. `Ruff: Fix all auto-fixable problems` only works on the actively open file in your editor, so if you view the file you want to fix and then run this command, it should work as expected.

Ideally, this command should not be appearing for non-Python files. I'll work on adding a file-based filter to the extension commands so this doesn't happen in the future.

**Comment by MadhavVij** [comment]
Hi @snowsignal ,

Thank you for the prompt and detailed response!

You are correct— I had the user settings JSON file open when I ran `Ruff: Fix all auto-fixable problems` command. I just tested it on a Python file, and it works as expected. I didn't realize this at the time of reporting the issue. 

I appreciate your quick identification of the problem and the steps to resolve it. The addition of a file-based filter to the extension commands will definitely help avoid confusion.

_<<Should I close this issue or you need it to track the Pull Request?>>_

Thanks again for your help!

**Comment by snowsignal** [comment]
@MadhavVij
> <<Should I close this issue or you need it to track the Pull Request?>>

I'll leave this issue open to track the pull request. Thanks!
