### ISSUE TITLE
single command for check and format

### ISSUE THREAD

**Issue by DaniBodor** [astral-sh/ruff#11749]
Is there a single command to check both linting and formatting? 
If not, this would be a nice addition in my mind. Not that it's a big deal to do it in two steps, but our CI only passes if both are correct, so basically whenever we do either, we do both.

**Comment by MichaReiser** [comment]
Unfortunately not, but it's high on our wish list. We just need to find the time to implement it. See https://github.com/astral-sh/ruff/issues/8232 to track the progress.
