### ISSUE TITLE
[red-knot] condense literal class and function types

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11785]
Display e.g. `Literal[C1, C2]`, not `Literal[C1] | Literal[C2]`

For now I think we should not mix different kinds of literals, i.e. we should still produce `Literal[1] | Literal[C] | Literal[f]`, not `Literal[1, C, f]`.

**Comment by diceroll123** [comment]
Related: https://github.com/astral-sh/ruff/issues/7881

**Comment by MichaReiser** [comment]
@carljm is this something a contributor could take up?

**Comment by carljm** [comment]
Sure. It should just be a localized change in `types/display.rs` for UnionType
Display, handled similarly to IntLiteral types.
