### ISSUE TITLE
[red-knot] condensed display for literal unions

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11782]
We should display `Literal[1, 2]` rather than `(Literal[1] | Literal[2])`.

This should also work if there are other elements in the union, e.g. `(Literal[1, 2] | None)`

**Comment by AlexWaygood** [comment]
> This should also work if there are other elements in the union, e.g. `(Literal[1, 2] | None)`

(`None` itself is actually a valid argument to `Literal` according to PEP 586, so this example could theoretically be flattened further to `Literal[1, 2, None]`. But people very rarely do that, and we decided somewhere sometime at typeshed that we never wanted to use that. `Literal[1, 2] | None` seems clearer.)
