### ISSUE TITLE
[red-knot] switch from PreorderVisitor to regular Visitor

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11796]
We don't need the extra features provided by `PreorderVisitor` (`enter_node`, `TraversalSignal` etc), and we prefer evaluation-order visit (which the regular visitor does) over source-order visit (which `PreorderVisitor` does).

Also in this issue we could consider renaming the visitors themselves; they are both preorder visitors (to the extent that description is even meaningful for this style of AST visitor; if you can override `visit_*` you can do things both before and after visiting children, so you can implement both preorder and postorder traversal) so it doesn't make sense to distinguish them on that axis. We should probably rename `PreorderVisitor` to `SourceOrderVisitor`.

**Comment by carljm** [comment]
#11798 took care of the rename!

**Comment by MichaReiser** [comment]
We must have done this in some refactor. @carljm I let you double check.
