### ISSUE TITLE
[red-knot] use borrowing iterators instead of returning vecs for Union.elements, Intersection.{positive|negative}

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11799]
See https://github.com/astral-sh/ruff/pull/11783#issuecomment-2155133526

**Comment by AlexWaygood** [comment]
(Deferred for now until the coming Salsa refactor)

**Comment by carljm** [comment]
This was made obsolete in the Salsa refactor. At the moment we don't expose elements/positive/negative directly at all, just methods like `UnionType::contains`.
