### ISSUE TITLE
Suppress isort for single import line

### ISSUE THREAD

**Issue by bloodgain** [astral-sh/ruff#11832]
Is is possible to tell ruff to ignore a single line for isort plugin sorting?

Currently, it appears that ruff can't process `# noqa: I001` for single lines. The only way I have found to disable import sorting at all in a file is to place `# ruff: noqa: I001` before the first import, which ignores `unsorted-imports` for the entire file.

Example:
```python
# ruff: noqa: I001 <-- ignores import sorting for whole file, and must start with "ruff:", which isn't ideal
import os
import shutil
from time import time

import ray
# ... more RLlib import stuff

# local imports
from customModels import BaseCustomPPO
# ... etc.

# must be imported out of order due to GLIBCXX error with matplotlib
# noqa: I001 <-- not respected here
import pandas as pd  # noqa: I001 <-- not respected here, either
```

**Comment by charliermarsh** [comment]
You need to put `# noqa: I001` on the first line of the import _block_ (i.e., the first line of the violation).

**Comment by bloodgain** [comment]
Unfortunately, it appears that it always triggers on the first place it thinks `import` is out-of-order, even with the intentional out-of-order import in a separate block with a `# noqa` guard. Using `--fix` results in it moving the `noqa` guard comment with the import.

Full import example (I let ruff sort the other imports to narrow the problem.):
**BEFORE**
```python=
import os
import shutil
from time import time

import ray

ray.init(local_mode=True)
import wsf_python as alt_sim
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.models import ModelCatalog

from customModels import BaseCustomPPO
from models import getModel
from utilities import CSVLogging, orderData, registerRLLib

# noqa: I001
import pandas as pd  #must be imported out of order due to GLIBCXX error with matplotlib
```

**CHECK**
```bash
>$ ruff check --select=I001 ./reinforcementLearning/evaluate.py
reinforcementLearning\evaluate.py:8:1: I001 [*] Import block is un-sorted or un-formatted
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

**AFTER `--fix`**
```python=
import os
import shutil
from time import time

import ray

ray.init(local_mode=True)
# noqa: I001
import pandas as pd  #must be imported out of order due to GLIBCXX error with matplotlib
import wsf_python as alt_sim
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.models import ModelCatalog

from customModels import BaseCustomPPO
from models import getModel
from utilities import CSVLogging, orderData, registerRLLib
```

Changing the guard comment to `# ruff: noqa: I001` ignores the rule for the whole file, even though it's below the other imports.

NOTE: I am not assuming this is a bug, just an artifact of how isort/ruff.lint.isort operates. I couldn't find any examples for ignoring a single out-of-order import, so I thought this was the best place to find out if I missed the correct way to do it or it wasn't possible.

**Comment by dhruvmanila** [comment]
Assuming that you _just_ want to ignore the `pandas` import, can you try it with `isort: skip`?

```py
import os
import shutil
from time import time

import ray

ray.init(local_mode=True)
import wsf_python as alt_sim
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.models import ModelCatalog

from customModels import BaseCustomPPO
from models import getModel
from utilities import CSVLogging, orderData, registerRLLib

import pandas as pd  # isort: skip  # must be imported out of order due to GLIBCXX error with matplotlib	
```

This works for me locally.

The `noqa: I001` comment should be at the start of the import block which would be:
```py
import os
import shutil
from time import time

import ray

ray.init(local_mode=True)
import wsf_python as alt_sim  # noqa: I001
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.models import ModelCatalog

from customModels import BaseCustomPPO
from models import getModel
from utilities import CSVLogging, orderData, registerRLLib

import pandas as pd  # must be imported out of order due to GLIBCXX error with matplotlib	
```

But, this would ignore the entire block which includes all the imports after `ray.init` call. The `noqa` comment cannot be on its own line either.

Reference: https://docs.astral.sh/ruff/linter/#error-suppression

**Comment by bloodgain** [comment]
@dhruvmanila 
Ah, so! That works!

Exactly what we needed. Thank you very much! 😊🙏

**Comment by charliermarsh** [comment]
Thank you @dhruvmanila!

**Comment by randolf-scholz** [comment]
Another option is adding a single pass statement

```python
import os
import shutil
from time import time

import ray

ray.init(local_mode=True)
import wsf_python as alt_sim
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.models import ModelCatalog

pass  # might require noqa: PIE790

import pandas as pd
```

https://play.ruff.rs/a15de7ad-2f41-4ea0-9b55-3471fe64fbbd
