### ISSUE TITLE
Bug - F401 Unused imports in Jupyter Notebook breaks shell commands

### ISSUE THREAD

**Issue by jeertmans** [astral-sh/ruff#11833]
Hello!

First of all, thanks for the great tool!

Inside notebooks (e.g., Google Colab), it is very common, and [recommended](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/), to run `pip install` Python packages by linking to the appropriate Python executable, which hence needs `sys.executable`, see code snippet below.

However, Ruff will not detect that `sys` is needed in the shell command (with `!`) and will remove the `import sys` line, which will ultimately break the notebook.

Without `--fix`, the output is:

```bash
notebook.ipynb:cell 2:7:12: F401 [*] `sys` imported but unused
```

**Keywords:** "Ruff", "F401", "Jupyter", "Notebook", "unused import", "shell command".

Minimal code snippet:

```python
try:
    import package  # noqa: F401
except ImportError:
    import sys
    !{sys.executable} -m pip install package
```

A temporary fix is to add disable this check on `import sys`:

```python
try:
    import package  # noqa: F401
except ImportError:
    import sys  # noqa: F401
    !{sys.executable} -m pip install package
```

While this fix is fine, I had to learn it the hard way, as the `unused-import` fix is considered stable and will not warn you about this if you directly run with `--fix`.

**Comment by tdulcet** [comment]
Same type of issue as #8094.

**Comment by jeertmans** [comment]
Indeed @tdulcet, couldn't find it :-)

**Comment by charliermarsh** [comment]
👍 I'm going to combine with #8094. Thanks!
