### ISSUE TITLE
Improve documentation for `PLR0917` around keyword only parameters

### ISSUE THREAD

**Issue by Renkai** [astral-sh/ruff#11868]
By the document, `PLR0917` shall only happen in a function call, not in the function definition.
https://docs.astral.sh/ruff/rules/too-many-positional/

But in the tests, it will fail in the function definition.
From the tests, it's more like `too-many-no-default` rather than `too-many-positional`

https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/resources/test/fixtures/pylint/too_many_positional.py

**Comment by dhruvmanila** [comment]
Hi, thanks for opening this issue!

> By the document, `PLR0917` shall only happen in a function call, not in the function definition.
> [docs.astral.sh/ruff/rules/too-many-positional](https://docs.astral.sh/ruff/rules/too-many-positional/)

Can you clarify this bit? I might be misunderstanding what you're trying to say but from my perspective the docs does mean _function definitions_: 

> "Checks for function definitions that include too many positional arguments."

**Comment by Renkai** [comment]
Sorry I misunderstood the document earlier, that's because I didn't know to use `*` to force keyword argument is a feature of Python language. I thought it's a feature of linter shall only be check in the function call not function definition. Maybe we can add this to document of linter to avoid misunderstanding.

https://docs.python.org/3/tutorial/controlflow.html#special-parameters

**Comment by dhruvmanila** [comment]
Happy to accept a PR to improve the documentation. Maybe we can provide a reference to https://docs.python.org/3/tutorial/controlflow.html#special-parameters.
