### ISSUE TITLE
Request For Security Contact

### ISSUE THREAD

**Issue by RedYetiDev** [astral-sh/ruff#11866]
Hi! I'm a security researcher, and I may have found a vulnerability in this project. Do you have a security contact?

**Comment by zanieb** [comment]
Hi! Feel free to contact me directly: zanie[at]astral.sh

**Comment by RedYetiDev** [comment]
Thanks! Additional details have been sent.

**Comment by charliermarsh** [comment]
Thanks! (Closing the issue itself.)
