### ISSUE TITLE
Support showing Bandit issues by severity

### ISSUE THREAD

**Issue by rahult-graphcore** [astral-sh/ruff#11877]
Bandit supports reporting on only high-severity issues using the `-lll` flag e.g.
`bandit examples/*.py -n 3 -lll`

or medium and high severity issues with `-ll`
`bandit examples/*.py -n 3 -ll`

This is quite useful when running on a large codebase to filter down to only the most serious issues.
This is a request to add this config option to Bandit in the Ruff linter.

**Comment by MichaReiser** [comment]
Hi

I can see how this is useful. We're considering to introduce a warning level to distinguish between different severities. See https://github.com/astral-sh/ruff/issues/1256

I don't think we want to go as far as having more levels other than warning and error. I'll close this in favor of https://github.com/astral-sh/ruff/issues/1256
