### ISSUE TITLE
I001 Isort doesn't fix multiline imports

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#11906]
Isort does not translate multiline improt into one line
`ruff check . --fix --unsafe-fixes --preview`
``` python
from datetime import (
    date,
)
```

However, isort works for such multiline imports
``` python
from datetime import (
    date
)
```
``` python
from datetime import date
```

**Comment by MichaReiser** [comment]
Can you try removing the `,` after `date,`. Ruff, by default respects trailing commas, similar to the formatter/Black. You can disable this behavior with the [isort.split-on-trailing-comma](https://docs.astral.sh/ruff/settings/#lint_isort_split-on-trailing-comma)](https://docs.astral.sh/ruff/settings/#lint_isort_split-on-trailing-comma) option.

[Playground](https://play.ruff.rs/8addaf3c-ab0f-4538-b668-29183962986f)

**Comment by spaceby** [comment]
It works. Thank you

**Comment by spaceby** [comment]
Is it possible to remove empty lines between the beginning of the page and the import?

```python
# This comment is here only so that these empty lines are visible



from datetime import date


date(date(2024, 1, 1))
```

**Comment by MichaReiser** [comment]
E303 is the closest to what you're looking for or you can use `ruff format`.
