### ISSUE TITLE
Playground does not underline issues on first open until first code change

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#11918]
When I open or reload https://play.ruff.rs/93f469fb-9725-411c-83c0-2c0d04d0ab75, I do not see any issues being underlined. I start seeing them as soon as I add a newline, or space, or anything else. But I'd expect them to be shown right from the first page load.

Microsoft Edge for Business
Version 126.0.2592.56 (Official build) (64-bit)

Reproduces in InPrivate mode with no extensions.

**Comment by dhruvmanila** [comment]
Oh, interesting! Thanks for opening this issue.
