### ISSUE TITLE
Do Ruff have plans to support Pylint E1101？

### ISSUE THREAD

**Issue by WutingjiaX** [astral-sh/ruff#11917]
I want to switch to using ruff instead of pylint, but after reviewing the documentation, it seems that this rule is not currently supported. However, this rule is important to me. Is there a plan to support it?

**Comment by dhruvmanila** [comment]
Yeah, it's tracked in https://github.com/astral-sh/ruff/issues/970. I'll merge this issue into the umbrella issue.
