### ISSUE TITLE
FR: format (or lint with fix) getitem called with tuples litteral (e.g. `a[(b, c)]` -> `a[b, c]`) ?

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/ruff#11990]
This is an idea for a formatting or linting rule (not sure where it would fit best). Basically I'd like ruff to drop unneeded parentheses from `a[(b, c)]` (into `a[b, c]`). This pattern comes up a lot in idiomatic [`yt`](https://github.com/yt-project/yt), but there are currently no formatter (that we know of) for it, so our docs and code base have two widely spread, competing styles.
I couldn't find a similar open issue, apologies if there is.

**Comment by charliermarsh** [comment]
This seems reasonable to me as a lint rule...

**Comment by MichaReiser** [comment]
I think I would even be open to add this to the formatter because it doesn't seem to change the AST

**Comment by neutrinoceros** [comment]
Up to you guys. I'm tempted to give it a try myself but that would be my first rust contribution ever. My personal inclination is that this would go to the formatter (as a known deviation from black ?), but I'm happy to wait for consensus for I dive in.

**Comment by dylwil3** [comment]
I like the idea that @MichaReiser raised of "formatting rule = does not change the AST" but I don't think that convention is actually followed, as far as I can tell, in the lint and formatting rules that currently exist, is that right? So I ended up taking a stab at this as a lint rule based on the convention of "vibes". Let me know if you'd prefer it to be formatting.
