### ISSUE TITLE
Add `np.ComplexWarning`, etc., to NPY201

### ISSUE THREAD

**Issue by njzjz** [astral-sh/ruff#12034]
Warnings and exceptions present in `numpy.exceptions` (e.g, `~numpy.exceptions.ComplexWarning`,  `~numpy.exceptions.VisibleDeprecationWarning`) are no longer exposed in the main namespace.

- np.ComplexWarning
- np.VisibleDeprecationWarning
- np.RankWarning
- np.AxisError
- np.DTypePromotionError
- np.TooHardError

See: https://github.com/numpy/numpy/pull/25966/

**Comment by charliermarsh** [comment]
\cc @mtsokol

**Comment by mtsokol** [comment]
It will be fixed in https://github.com/astral-sh/ruff/pull/12065.

**Comment by charliermarsh** [comment]
Thanks @mtsokol!
