### ISSUE TITLE
Request: allowlist setting for `N812`/`N817`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#12031]
There are certain libraries like [PyTorch's FSDP](https://pytorch.org/docs/stable/fsdp.html) that standardized on being imported with all caps:

```python
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP

...
sharded_module = FSDP(my_module)
```

Currently, with Ruff 0.4.10 you just have to use a `# noqa: N817` for every import line of libraries like FSDP.

Also, a similar PyTorch use case is `from torch.nn import functional as F`, which raises N812.

Ideally, there is a configuration option to build up an allowlist of possible names to not raise [N812](https://docs.astral.sh/ruff/rules/lowercase-imported-as-non-lowercase/)/[N817](https://docs.astral.sh/ruff/rules/camelcase-imported-as-acronym/). I tried using the [`ignore-names`](https://docs.astral.sh/ruff/settings/#lint_pep8-naming_ignore-names) or `extend-ignore-names` settings, but neither worked.

Do you think we can either allow `ignore-names` to apply to N817, or create a new option `ignore-acronyms` that can accommodate this use case?

Thank you for your consideration!

**Comment by charliermarsh** [comment]
It does look like those rules respect the setting, but confusingly... N812 matches against the `asname` (`FSDP` above) while N817 matches against the `name` (`FullyShardedDataParallel` above). So I'll fix that. Which would you find more intuitive? Maybe we match against... both?

**Comment by jamesbraza** [comment]
So to write it out, I think:

`from torch.nn import functional as F`:
- Should match N812 as `functional` is lowercase
    - And one part of this request is to manually allowlist this in `pyproject.toml`
- Should not match N817 as `functional` is not camel case

`from torch.distributed.fsdp import FullyShardedDataParallel as FSDP`
- Should not match N812 as `FullyShardedDataParallel` is not lowercase
- Should match N817 as this is N817's normal use case
    - And the other part of this request is to manually allowlist this in `pyproject.toml`

Does that answer your question?

**Comment by charliermarsh** [comment]
Actually what I was asking is: given `from torch.distributed.fsdp import FullyShardedDataParallel as FSDP`, what value would you expect to put in `ignore-names`?

**Comment by jamesbraza** [comment]
Oh I see now. Yeah I think I would want to put `FSDP`, as that's the infringing acronym

Open to specifying `FullyShardedDataParallel`, but that's not really the point of infringement so I prefer `FSDP`

**Comment by charliermarsh** [comment]
I changed it to respect both. The rules were inconsistent as to which they looked at.

**Comment by jamesbraza** [comment]
Thank you! Appreciate the fast turnaround 👍
