### ISSUE TITLE
Remove `output-format=text`

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#12040]
https://github.com/astral-sh/ruff/pull/12010 (shipped in Ruff 0.5) made using `output-format=text` a hard error. The next deprecation step is to remove the option entirely in 0.6 or 0.7

**Comment by simsong** [comment]
so how do you turn off all of the TTY escape codes in the output?

**Comment by simsong** [comment]
Apparently you need to run with `NO_COLOR=1` environment variable set. ruff is using some magic Rust thing to figure out if it should colorize the output, and this fails when running inside an emacs compile window. You get stuff like this:

![Image](https://github.com/user-attachments/assets/8b26cd80-08fa-4ba9-accc-d8239e30ab26)

**Comment by ntBre** [comment]
Another option, if you do want the colors, is to add this to your config:

```elisp
(require 'ansi-color)
(add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)
```

That's what I have in my Emacs config!

![Image](https://github.com/user-attachments/assets/a393a7b9-4baa-43d8-be78-2d7a09e5d5ad)

I double-checked with `emacs -nw -Q` to make sure that was the important piece of configuration and that it works in the terminal.

**Comment by simsong** [comment]
Woah. Thanks.
