### ISSUE TITLE
ANN001 should not be fired if function param is a pytest fixture

### ISSUE THREAD

**Issue by buabaj** [astral-sh/ruff#12052]
```
@pytest.fixture
def tool_manager():
    return ToolManager()
    
def test_create_tool(tool_manager):
    do_something()  
```

I believe in cases like this ANN001 should not be fired because we still don't have a fixture type annotation. what then should be the best way to deal with this, please?

**Comment by dhruvmanila** [comment]
Considering this example, I think the type of `tool_manager` would just be whatever the `tool_manager` fixture is returning which is `ToolManager`. So, in general you can provide the return type of the fixture as the argument type.

**Comment by buabaj** [comment]
thanks @dhruvmanila ❤️

**Comment by dhruvmanila** [comment]
Glad to be helpful. I hope that answers your question. I'll mark this as resolved but feel free to ask any other questions that you might have.
