### ISSUE TITLE
Docs is not updated to v0.5.0

### ISSUE THREAD

**Issue by yairp03** [astral-sh/ruff#12074]
The docs weren't updated to comply with v0.5.0 changes.  
For example, there is no deprecated note on [E999](https://docs.astral.sh/ruff/rules/syntax-error/) and [RUF024](https://docs.astral.sh/ruff/rules/mutable-fromkeys-value/) is still in preview.

**Comment by MichaReiser** [comment]
Thanks for reporting. I wasn't aware that we need to start the action to publish the documentation manually. It's now running and that should hopefully fix it. I'll update the contribution guidelines. 

https://github.com/astral-sh/ruff/actions/runs/9700308469/job/26771392459

**Comment by zanieb** [comment]
I don't think that should need to be manual, presumably this is an oversight because docs are not published in uv. cc @charliermarsh

**Comment by MichaReiser** [comment]
And it just finished and the docs are up to date.

**Comment by MichaReiser** [comment]
Assigning to you @charliermarsh to look into if this should be triggered automatically

**Comment by charliermarsh** [comment]
Yup, will fix!
