### ISSUE TITLE
Infinite loop in auto-fix between `E203`/`E275`

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#12094]
Example code:
```py
pass;
```

The [`E275`](https://docs.astral.sh/ruff/rules/missing-whitespace-after-keyword/) rule tries to add a whitespace after `pass` keyword but the [`E203`](https://docs.astral.sh/ruff/rules/whitespace-before-punctuation/) tries to remove the whitespace before `;`.

**Comment by dhruvmanila** [comment]
Although, if you add in `E703` (useless-semicolon), there won't be an infinite loop because it would remove the semicolon.

**Comment by AlexWaygood** [comment]
If we're picking sides, I think E203 is correct on this one and E275 has it wrong
