### ISSUE TITLE
Invalid table header with mypy ignore missing import

### ISSUE THREAD

**Issue by thisi5patrick** [astral-sh/ruff#12098]
I have this case where I want to exclude a library from being checked in mypy.
Based on mypy's [documentation](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) what you should do is add the library as
```
[mypy-foobar.*]
ignore_missing_imports = True
```

The problem now is that after adding the library `Vision` from `pyobjc-framework-vision` into my `pyproject.toml` as such:
```
[tool.mypy-Vision.*]
ignore_missing_imports = true
```
when running `ruff check .` I get:
```
ruff failed
  Cause: Failed to parse <path>/pyproject.toml
  Cause: TOML parse error at line 79, column 18
   |
79 | [tool.mypy-Vision.*]
   |                  ^
invalid table header
expected `.`, `]`
```

Ruff version `ruff 0.5.0`
Python version `Python 3.12.3`

**Comment by MichaReiser** [comment]
Can you try to quote the table header?

```
["mypy-foobar.*"]
ignore_missing_imports = True
```

**Comment by MichaReiser** [comment]
There's also a [`pyproject.toml` example](https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml ) in the mypy documentation. 

I'm closing this issue because it seems mainly about figuring out the right syntax for the mypy configuration in a pyproject.toml (and not mypy.ini)
