### ISSUE TITLE
[Documentation] Link to closed issue in ERA001

### ISSUE THREAD

**Issue by JackDyre** [astral-sh/ruff#12108]
[This](https://docs.astral.sh/ruff/rules/commented-out-code/) page on the documentation links to [this](https://github.com/astral-sh/ruff/issues/4845) issue as a known issue with the rule, but the issue is closed. 

I assume the documentation needs to be updated?

**Comment by charliermarsh** [comment]
Unfortunately I believe some of these false positives still exist, and the issue was closed (IIRC) because we changed the applicability level of the rule.
