### ISSUE TITLE
Should cursor credit rustc?

### ISSUE THREAD

**Issue by sbdchd** [astral-sh/ruff#12107]
I was looking at ruff and rustc for inspo for lexing and the cursor files are pretty similar:

https://github.com/astral-sh/ruff/blob/d1079680bb29f6b797b5df15327195300f635f3c/crates/ruff_python_parser/src/lexer/cursor.rs

https://github.com/rust-lang/rust/blob/d1b7355d3d7b4ead564dbecb1d240fcc74fff21b/compiler/rustc_lexer/src/cursor.rs

**Comment by zanieb** [comment]
👋 I went on quite the hunt trying to see if there was context about this. As far as I can tell nobody talked about the rustc lexer and they probably would have if they based the design on it? I'm curious to hear from @MichaReiser though. 

Some references I looked at:

- https://github.com/astral-sh/ruff/pull/6099
- https://github.com/astral-sh/RustPython-Parser/pull/38
- https://github.com/astral-sh/ruff/pull/5715
- https://github.com/astral-sh/ruff/pull/4922

**Comment by MichaReiser** [comment]
Yes, we absolutely should. 

I was fairly certain that I mentioned in some comment that the implementation is derived from Rust in https://github.com/astral-sh/ruff/pull/4922 (inline comment or at least on the PR), but I didn't!
