### ISSUE TITLE
new rule - flag f-strings that contain expressions with the same quote as its outer quote

### ISSUE THREAD

**Issue by R1kaB3rN** [astral-sh/ruff#12114]
As a result of [PEP 701](https://peps.python.org/pep-0701/), in Python 3.12, you are now able to [use expression components that contain the same quote as the outer f-string](https://docs.python.org/3.12/whatsnew/3.12.html#pep-701-syntactic-formalization-of-f-strings) which allow f-strings like this:

`foo = f'{os.environ['HOME']}/foo' `

Or even nest f-strings:

`foo = f"""{f'''{f'{f"{1+1}"}'}'''}"""`

However, when using a Python version less than 3.12, the above expressions should raise a `SyntaxError`. Based on the user's Python version defined in their configuration file, I believe ruff can easily prevent any `SyntaxError` from occurring if a rule is enabled.

**Comment by dhruvmanila** [comment]
If I'm understanding this correctly, it is one of the task in https://github.com/astral-sh/ruff/issues/6591. I'll merge this into the parent issue. Thanks for the suggestion!
