### ISSUE TITLE
escape-sequence-in-docstring (D301) reports escaped docstrings within docstrings

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#12152]
Running

```sh
ruff check --isolated --select D301
```

on

```python
def foo():
    """
    This docstring contains another docstring.

        def bar():
            \"\"\"Here it is!\"\"\"
    """
```

returns an [escape-sequence-in-docstring (D301)](https://docs.astral.sh/ruff/rules/escape-sequence-in-docstring/) diagnostic, printing

```
example.py:2:5: D301 Use `r"""` if any backslashes in a docstring
  |
1 |   def foo():
2 |       """
  |  _____^
3 | |     This docstring contains another docstring.
4 | |
5 | |         def bar():
6 | |             \"\"\"Here it is!\"\"\"
7 | |     """
  | |_______^ D301
  |
  = help: Add `r` prefix
```

However, adding the `r` prefix and removing the backslashes is a syntax error:

```python
def foo():
    r"""
    This docstring contains another docstring.

        def bar():
            """Here it is!"""
    """
```

Docstrings in within docstrings can appear when a docstring contains a code snippet (which is how I discovered the issue). I would expect D301 not to be raised, as making the docstring raw doesn't work.

Ruff version 0.5.0

Search terms: D301, backslash, escape

Update: managed to reproduce with

```python
def foo():
    """
    This docstring contains another docstring.

        def bar():
            \"""Here it is!\"""
    """
```

as well.

**Comment by ukyen8** [comment]
Hi, I would like to work on this issue. Is anyone already working on it?

**Comment by dhruvmanila** [comment]
@ukyen8 I don't think so, go for it!

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/12192#pullrequestreview-2187016174. Thanks!
