### ISSUE TITLE
PLR1704 issued for `_` variable

### ISSUE THREAD

**Issue by ktbarrett** [astral-sh/ruff#12157]
I'm not sure what pylint does, but the variable `_` is idiomatically used as a "don't care" variable (in fact unused variables that *aren't* `_` trigger a different warning) and the error PLR1704 being issued for it I consider to be flying in the face of idiomatic code.

**Comment by ktbarrett** [comment]
idiomatic => conventional. You know what I mean.

**Comment by ktbarrett** [comment]
I just checked, pylint does not issue a warning in this case.

**Comment by zanieb** [comment]
Sounds like a bug to me. Thanks for the report.

**Comment by charliermarsh** [comment]
Thanks, we probably need to check this against [`dummy-variable-rgx`](https://docs.astral.sh/ruff/settings/#lint_dummy-variable-rgx). Good first issue!
