### ISSUE TITLE
SIM108 suggested for code block that could have been simplified to an `or`

### ISSUE THREAD

**Issue by brettcannon** [astral-sh/ruff#12189]
* List of keywords you searched for before creating this issue: SIM108
* A minimal code snippet that reproduces the bug.
```python
if raw_data["subtest"]:
        test_id = raw_data["subtest"]
    else:
        test_id = raw_data["test"]
```

* The command you invoked: pipx run ruff check --fix --select SIM unittestadapter/execution.py
* The current Ruff version: 0.5.0

I would have expected the code block to be simplified to `test_id = raw_data["subtest"] or raw_data["test"]`.

**Comment by charliermarsh** [comment]
Makes sense, thanks!
