### ISSUE TITLE
Potential conflict S603 and unused noqa directive in `0.5.0` version

### ISSUE THREAD

**Issue by shaneahmed** [astral-sh/ruff#12184]
Upgrade to 0.5.0 removes `# noqa: S603` during formatting as an unused noqa directive but then generates S603 error.

For example, in https://github.com/TissueImageAnalytics/tiatoolbox/pull/829/files ruff removes `# noqa: S603` as an unused noqa directive` but then fails due to S603 error.

**Comment by MichaReiser** [comment]
Hi @shaneahmed 

The last release changed (breaking) the range of some flake8-bandit rules ([changelog](https://github.com/astral-sh/ruff/releases/tag/0.5.0), [PR](https://github.com/astral-sh/ruff/pull/10667)). This will mean that existing noqa comments need to be moved. I'm sorry that this is causing you extra work. I believe Ruff can do it automatically for you when using `ruff check --extend-select=RUF100 --fix` to remove the unused noqa comments and then use `ruff check --add-noqa --select=S` to add the noqa comments for the flake8-bandit rules.

**Comment by shaneahmed** [comment]
Many thanks @MichaReiser . It helped!
