### ISSUE TITLE
ruff format ignores notebooks unless specified

### ISSUE THREAD

**Issue by Wazarr** [astral-sh/ruff#12185]
Hi,

I have noticed when using the CLI that doing `ruff format .` ignores Jupyter notebooks.
I believe this a deviation from black, which effectively formats notebooks with `black .`, with the right dependencies installed.

It's only possible to format notebooks when the filename is provided, which forces me to iterate over files to format all my notebooks.
I have looked at the documentation and other issues, and I'm on the latest version of Ruff (v0.5.0).

Would it be possible to add an option to fix this issue?
Thanks

**Comment by MichaReiser** [comment]
Can you try using `extend-include = ["*.ipynb"]` in your configuration? This way, notebooks should also be included when running `ruff check` ([doc](https://docs.astral.sh/ruff/configuration/#jupyter-notebook-discovery))

**Comment by Wazarr** [comment]
Apologies, only looked at CLI.
Thanks for the quick answer.

**Comment by MichaReiser** [comment]
No worries. The notebook documentation is fairly hidden away. We do have an issue with improving the discoverability.
