### ISSUE TITLE
RET501 should exempt properties

### ISSUE THREAD

**Issue by epenet** [astral-sh/ruff#12197]
A property is normally meant to be consumed.

```python
class Class:
    @property
    def data(self) -> None:
        return None
        # RET501 [*] Do not explicitly `return None` in function if it is the only possible return value
```

Based on https://github.com/home-assistant/core/pull/115031

Note: the main case is when overriding base properties, so this may not be needed if #12198 is resolved.

**Comment by AlexWaygood** [comment]
Yeah, I agree you'd probably want to explicitly `return None` in a property. PR welcome!
