### ISSUE TITLE
Broken link in 0.5.0 release notes

### ISSUE THREAD

**Issue by pjonsson** [astral-sh/ruff#12202]
The link to `misplaced-bare-raise` at https://github.com/astral-sh/ruff/releases/tag/0.5.0 ends with `%60/` which results in a 404. Removing the `%60` seems to go to the right page.

**Comment by dhruvmanila** [comment]
Thank you for raising this. I've updated the link.

**Comment by thewh1teagle** [comment]
@dh

> Thank you for raising this. I've updated the link.

The link in `README.md` are also broken for Windows

**Comment by dhruvmanila** [comment]
> The link in `README.md` are also broken for Windows

Can you point out which link(s) are you talking about here?

**Comment by thewh1teagle** [comment]
https://astral.sh/ruff/install.ps1
