### ISSUE TITLE
Make `VendoredFileSystem` lazy

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#12219]
The `VendoredFileSystem` reads the entire zip file when calling `new`. We should consider making the `VendoredFileSystem` lazy by using internal mutability with an inner `enum` that has two variants `Raw(Cow<'static, [u8]>)` and `Zip(ZipArchive)`. The `VendoredFileSystem::new` initializes with `Raw` and transitions to `Zip` when calling the first method.

**Comment by AlexWaygood** [comment]
Interesting. Do you think this is likely to buy us much? IIUC, we'd still have to read the whole zip as soon as a single method on the `VendoredFileSystem` instance is called, and that will be necessary as soon as we need to lookup information on a single builtin or standard-library type. I doubt there will be many Python programs that can be type-checked without resolving a single builtin or standard-library type.

**Comment by AlexWaygood** [comment]
I do like the idea though, this might open up some other possibilities

**Comment by MichaReiser** [comment]
> Interesting. Do you think this is likely to buy us much

I'm not so sure anymore. Your recommendation on https://github.com/astral-sh/ruff/pull/12214 to change `Program::vendored` to lazy load the vendored file system mitigates the concern for now. We may want to consider alternatives if returning a lazy version in `Program::vendored` isn't possible anymore (for whatever reason). 

 >  I doubt there will be many Python programs that can be type-checked without resolving a single builtin or standard-library type.

It is nice if we can avoid loading the zip e.g. when just formatting the files in a `Program`.
