### ISSUE TITLE
Supports multi `--output-format` at the same time

### ISSUE THREAD

**Issue by Zxilly** [astral-sh/ruff#12237]
For example, while running in the `GitHub Actions`, I want to use the `github` format to see details on the web ui, while also outputting the `SARIF` format to upload the result to the CodeQL.

**Comment by MichaReiser** [comment]
Thanks for opening the issue. Yeah, this is a use case that ruff doesn't support well today. I wonder if we could just write a cheap conversion between the two formats. Anyway, this has come up before, see https://github.com/astral-sh/ruff/issues/2388. I'll close this issue in favor of the other rone.
