### ISSUE TITLE
help for "--output-format" incorrectly lists "concise" as the default

### ISSUE THREAD

**Issue by DaniBodor** [astral-sh/ruff#12247]
I've noticed that as of v0.5.0 the default output format has changed from "concise" to "full". However, the help still states that the default is "concise".

Minimal reproduction:

```
ruff check -h
```

returns:

> Run Ruff on the given files or directories (default)
> 
> [yadda yadda]
> 
> --output-format <OUTPUT_FORMAT>    Output serialization format for violations. The default serialization format is "concise". In preview mode,
> 
> [yadda yadda]

**Comment by charliermarsh** [comment]
Thank you! PR welcome if anyone is up for it.

**Comment by DaniBodor** [comment]
> Thank you! PR welcome if anyone is up for it.

done
