### ISSUE TITLE
option to set `output-format` grouped by rule

### ISSUE THREAD

**Issue by DaniBodor** [astral-sh/ruff#12249]
I think it would be useful if `ruff check` could group the output by rule violated, perhaps even with the number of instances explicitly given.
This can be useful for cases where the violation is not easily fixable to decide whether to supress it case-by-case or turn it off altogether.

Currently, there is a "grouped" option, but this groups violations per file, not per rule.

**Comment by MichaReiser** [comment]
does the  --statistics option give you the output you're looking for?

**Comment by DaniBodor** [comment]
it does indeed. I missed that option. 
It's a bit confusing that it is separate from `--output-format`, as it appears to be just another output format :)

**Comment by dhruvmanila** [comment]
> It is a bit confusing that it is separate from `--output-format`, as it appears to be just another output format :)

I think the `--statistics` flag was adopted from `flake8` which is why it is separate. There's also [this comment](https://github.com/astral-sh/ruff/issues/4140#issuecomment-1527807554) for context.

**Comment by MichaReiser** [comment]
The other reason why it's different is because `ruff check --statistics --output-format=json` emits json.
