### ISSUE TITLE
`ruff server` does not consider config `include`

### ISSUE THREAD

**Issue by christianbrugger** [astral-sh/ruff#12242]
I want to use `ruff server` on a project where I want to introduce formatting and linting gradually. 

My idea was to use the `include` feature in the `ruff.toml` config:
```toml

# only lint & format opt-in files
include = [
    'src/plots.py',
    'src/reports.py',
]
```
This perfectly works when using `ruff format .` and `ruff check .`  from the CLI, meaning that only the two files listed are formatted and linted, nothing else.

However when using the `ruff server` all files are formatted and linted. This is especially problematic when using the format on save or auto-fix on save feature via an IDE. Also way to many diagnostics from the linting are shown.

I looked at the [formatting handler source code](https://github.com/astral-sh/ruff/blob/64855c5f06f0ff796eb54b8db57017f0e11017f9/crates/ruff_server/src/server/api/requests/format.rs#L86-L98) and can see that the `exclude` list is already parsed from the config. However the `include` property is not considered at all. The same is true for [fixes](https://github.com/astral-sh/ruff/blob/64855c5f06f0ff796eb54b8db57017f0e11017f9/crates/ruff_server/src/fix.rs#L36-L49) and [linting](https://github.com/astral-sh/ruff/blob/64855c5f06f0ff796eb54b8db57017f0e11017f9/crates/ruff_server/src/lint.rs#L73-L88).

I would really appreciate, if the `include` mechanism could be added to the `ruff server` as well. Meaning that the server ignores format and fix requests, and returns no diagnostics for files not in the `include` list. In the same way it works for the CLI tool.

**Comment by dhruvmanila** [comment]
Looking into this...

**Comment by dhruvmanila** [comment]
Your assessment is correct. The new server isn't considering anything from the file-resolver settings apart from `exclude` and `extend-exclude`.

**Comment by dhruvmanila** [comment]
I think the simplest solution here is to use the logic of the various `FileResolverSettings` information from `python_files_in_path` function and incorporate it into the linting and formatting entry point for the `ruff server`.

But, a long term goal would to have some kind of abstraction which can resolve the path based on the given settings.
