### ISSUE TITLE
Add `-> None` automatically to all pytest tests

### ISSUE THREAD

**Issue by chbndrhnns** [astral-sh/ruff#12274]
When running mypy on a larger codebase with many tests, it will report missing `-> None` annotations on tests in strict mode.

I suggest adding a rule that adds this return type to all tests discovered by pytest.

**Comment by AlexWaygood** [comment]
Hi, thanks for the feature request! Have you tried enabling the autofixes for [`ANN201`](https://docs.astral.sh/ruff/rules/missing-return-type-undocumented-public-function/), `ANN202`, `ANN204`, `ANN205` and `ANN206`? They might already do what you want here

**Comment by chbndrhnns** [comment]
I just did seconds ago and was about to close the issue due to this ;)
Thanks much

**Comment by AlexWaygood** [comment]
You're very welcome, glad to hear it! :D
