### ISSUE TITLE
SyntaxError is unable to return code on Linux

### ISSUE THREAD

**Issue by WutingjiaX** [astral-sh/ruff#12271]
"SyntaxError", ""code": null", "linux", "Debian"

I run the **same** code on MacOS and Linux(Debian GNU/Linux 10 (buster)), with the cmd: 
```
ruff check --output-format=json test.py
```
ruff version 0.5.1

The code in the _test.py_ is any Python code that may cause syntax errors， such as：
```
import .
```
the output on linux is:
```
[
  {
    "cell": null,
    "code": null,
    "end_location": {
      "column": 9,
      "row": 1
    },
    "filename": "/home/code/test.py",
    "fix": null,
    "location": {
      "column": 8,
      "row": 1
    },
    "message": "SyntaxError: Expected an import name",
    "noqa_row": null,
    "url": null
  },
  {
    "cell": null,
    "code": null,
    "end_location": {
      "column": 1,
      "row": 2
    },
    "filename": "/home/code/test.py",
    "fix": null,
    "location": {
      "column": 9,
      "row": 1
    },
    "message": "SyntaxError: Expected one or more symbol names after import",
    "noqa_row": null,
    "url": null
  }
]
```

but on MacOS,the output is:
```
[
  {
    "cell": null,
    "code": "E999",
    "end_location": {
      "column": 9,
      "row": 1
    },
    "filename": "/Users/bytedance/Library/Application Support/JetBrains/PyCharm2023.3/light-edit/test.py",
    "fix": null,
    "location": {
      "column": 8,
      "row": 1
    },
    "message": "SyntaxError: Expected an import name",
    "noqa_row": 1,
    "url": "https://docs.astral.sh/ruff/rules/syntax-error"
  }
]%
```

I can't understand why the output is different (especially if one code field has a value and the other doesn't)

**Comment by MichaReiser** [comment]
I suspect that you're using two different Ruff versions. Can you try running `ruff --version` on both systems and verify that they're the same?

**Comment by MichaReiser** [comment]
This has been changed as part of 0.5, see the [announcement blog post](https://astral.sh/blog/ruff-v0.5.0#changes-to-e999-and-reporting-of-syntax-errors) for more details.

**Comment by WutingjiaX** [comment]
@MichaReiser 
Thank you for your answer！If the code can be null, it needs some consideration when deserializing (such as using pydantic,it should be optional instead of string). But this is not a big problem

**Comment by kaste** [comment]
This change breaks the Sublime Text plugin which assumed "code: str".  https://github.com/kaste/SublimeLinter-contrib-ruff/issues/2

This is easy to fix and I have to anyway but in Sublime Text the "rule name" aka "code" actually matters as the "diagnostics" can be styled per linter name, per error-type ("severity"), and per rule-name.  E.g. I literally use a bomb icon for E999 errors.

**Comment by dhruvmanila** [comment]
> (Why is that an Optional[str] anyway. If I do `item["code"]`, I ask what the code is and since there is a key, you basically answer: Yeah sure I have the code, it's ... a nah ... don't know.)

You can find some context in the [blog post](https://astral.sh/blog/ruff-v0.5.0#changes-to-e999-and-reporting-of-syntax-errors) and some discussion in the [original PR](https://github.com/astral-sh/ruff/pull/11901) but the tldr is that the rule itself is deprecated i.e., `E999` doesn't exists in Ruff anymore. This means we can't use the code anywhere. Syntax errors are now always shown and one cannot select / ignore them. Regarding the type, it's `Optional[str]` because it's the value that's optional and not the key itself. The key will always be present but as there's no rule code for a syntax error, it will be `null` instead.
