### ISSUE TITLE
Add rule for using PEP696 default type params

### ISSUE THREAD

**Issue by janosh** [astral-sh/ruff#12286]
[PEP 696](https://peps.python.org/pep-0696) allows cleaning up code like

```py
from typing import Generator

def gen() -> Generator[int, None, None]:  # bad (on 3.13+)
    yield 42

def gen() -> Generator[int]:  # good
    yield 42
```

would be great if `ruff` had an auto-fix for that if the target version is at least 3.13

**Comment by dhruvmanila** [comment]
Seems like a good idea. Thanks for raising this request. Do you know if there are any other types like `Generator` that has been changed? I think `AsyncGenerator` can also be considered.

**Comment by charliermarsh** [comment]
PR welcome, we can put it under the `UP` category.

**Comment by janosh** [comment]
looks like this can be closed since https://github.com/astral-sh/ruff/pull/12371 was implemented and merged in record time as usual. thanks! 👍

**Comment by charliermarsh** [comment]
Good call, thanks @janosh.
