### ISSUE TITLE
Broken link for standalone installer for Windows

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#12298]
It seems that https://astral.sh/ruff/install.ps1 doesn't work but https://astral.sh/ruff/0.5.1/install.ps1 does. The former leads to a 404 page on the website.

As reported here: https://github.com/astral-sh/ruff/issues/12202#issuecomment-2224482278

**Comment by dhruvmanila** [comment]
cc @charliermarsh

**Comment by charliermarsh** [comment]
This is fixed (but may take some time for cache to propagate if you tried it while 404ing).
