### ISSUE TITLE
PLR1704 triggers for list comprehension variable

### ISSUE THREAD

**Issue by richardebeling** [astral-sh/ruff#12339]
This code snippet
```python3
def func(foo):
    for _ in bar(foo for foo in [1]):
        pass
```

triggers [PLR1704](https://docs.astral.sh/ruff/rules/redefined-argument-from-local/) with ruff 0.5.2
```
$ ruff --version
ruff 0.5.2

$ ruff check --select PLR1704 test.py
test.py:2:26: PLR1704 Redefining argument with the local name `foo`
  |
1 | def func(foo):
2 |     for _ in bar(foo for foo in [1]):
  |                          ^^^ PLR1704
3 |         pass
  |

Found 1 error.
```

which is wrong. [From the python3 docs](https://docs.python.org/3/reference/expressions.html#grammar-token-python-grammar-comprehension):
> However, aside from the iterable expression in the leftmost for clause, the comprehension is executed in a separate implicitly nested scope. This ensures that names assigned to in the target list don’t “leak” into the enclosing scope.

**Comment by charliermarsh** [comment]
Agreed -- that looks like a bug.
