### ISSUE TITLE
ruff did not return the original code

### ISSUE THREAD

**Issue by ArtemIsmagilov** [astral-sh/ruff#12348]
ruff version 0.5.2
OS ubuntu

I have python code
```python
self.create_empty_buttons("btn_task1", "btn_task2", "btn_task3", "btn_task4", "btn_task5", "btn_task6")
```
After command ruff formatting code and create many nested arguments
going ruff with line-length=80
```bash
ruff ruff format . --line-length=80
>>>self.create_empty_buttons(
            "btn_task1",
            "btn_task2",
            "btn_task3",
            "btn_task3",
            "btn_task3",
            "btn_task3",
        )
```
 I'm trying to remove this nesting that fits in 120 characters, but ruff does not make the code initially horizontal without nesting. Why?
 ```bash
 ruff ruff format . --line-length=120
>>>???self.create_empty_buttons(
            "btn_task1",
            "btn_task2",
            "btn_task3",
            "btn_task3",
            "btn_task3",
            "btn_task3",
        )
 ```

**Comment by ArtemIsmagilov** [comment]
It would be expected for me remove nested args for example
```python
>>>self.create_empty_buttons("btn_task1", "btn_task2", "btn_task3", "btn_task4", "btn_task5", "btn_task6")
```

**Comment by ArtemIsmagilov** [comment]
I may not know much about whether this is semantically correct and whether this is expected by many developers. I just want to know why exactly this return is ignored, given that it fits in 120 characters.

**Comment by charliermarsh** [comment]
But you ran with `--line-length=80`, and the line is over 80 characters.

**Comment by charliermarsh** [comment]
Oh, and then you re-ran with `--line-length=120` _on the formatted output_, is that right? By default Ruff will respect trailing commas and won't collapse statements. You can configure that here: https://docs.astral.sh/ruff/settings/#format_skip-magic-trailing-comma

**Comment by charliermarsh** [comment]
Or just remove the trailing comma from your example.

**Comment by ArtemIsmagilov** [comment]
Hi, @charliermarsh, thank you. Remove `,` in end and. ruff returned the lines as expected)
It seems I missed this point because you have it in the documentation. Thanks again)

**Comment by charliermarsh** [comment]
No problem! Glad to help.
