### ISSUE TITLE
Settings section of documentation has incorrect default value for output-format

### ISSUE THREAD

**Issue by sashko1988** [astral-sh/ruff#12350]
"documentation", "default settings", "output-format", 0.5.2 version

`Settings` section for toml files still shows `concise` as default (https://docs.astral.sh/ruff/settings/#output-format):

> The style in which violation messages should be formatted: "full" (shows source), "concise" (default), "grouped" (group messages by file), "json" (machine-readable), "junit" (machine-readable XML), "github" (GitHub Actions annotations), "gitlab" (GitLab CI code quality report), "pylint" (Pylint text format) or "azure" (Azure Pipeline logging commands).
> 
> Default value: "concise"

While cli outputs full as a default:
> --output-format <OUTPUT_FORMAT>    Output serialization format for violations. The default serialization format is "full"

And `ruff` actually uses `full` if a user doesn't specify it.

**Comment by charliermarsh** [comment]
Thank you -- it looks like we forgot to update `crates/ruff_workspace/src/options.rs`. Are you interested in submitting a PR?

**Comment by sashko1988** [comment]
@charliermarsh would love to!
