### ISSUE TITLE
[EHN] Suppress Errors in Code Region

### ISSUE THREAD

**Issue by randolf-scholz** [astral-sh/ruff#12377]
Currently, one can suppress errors on a per-line level, per-file level, or globally.

However, sometimes it would be more appropriate to disable errors locally within a file for some region (for instance, suppressing [`ERA001`](https://docs.astral.sh/ruff/rules/commented-out-code/) for some region).

PyLint offers `# pylint: disable=...` and `# pylint: enable=...` for this purpose https://github.com/pylint-dev/pylint/issues/2920#issuecomment-493734595.

Although, this approach is somewhat dangerous imo, since one can accidentally forget to re-enable the error code. So a start/end-region pragma with an automatic check for the existence of the close tag would be ideal.

**Comment by MichaReiser** [comment]
That makes sense. We already track this in https://github.com/astral-sh/ruff/issues/3711
