### ISSUE TITLE
Ruff LSP Setup Guide for Zed

### ISSUE THREAD

**Issue by ngriffiths13** [astral-sh/ruff#12388]
It would be great to add a Ruff LSP setup guide section for [the Zed IDE](https://zed.dev/) if possible!

**Comment by charliermarsh** [comment]
Agreed.

**Comment by MichaReiser** [comment]
Would you be interested in writing up some documentation or do you have an example configuration that we could use as starting point? I haven't used ruff with zed yet (:hand_over_mouth:)

**Comment by charliermarsh** [comment]
By the way, there's some work happening right now to make a Ruff extension for Zed: https://github.com/zed-industries/zed/pull/14198.

There are also some tricks you can use here to enable Ruff in Zed, but these are pretty basic and don't go through the LSP -- they just hook up the CLI: https://github.com/zed-industries/zed/discussions/6669
