### ISSUE TITLE
0.5.4 Windows artifact flagged on Chromium

### ISSUE THREAD

**Issue by AlexBlandin** [astral-sh/ruff#12431]
Downloading [0.5.4](https://github.com/astral-sh/ruff/releases/tag/0.5.4)'s [`ruff-x86_64-pc-windows-msvc.zip`](https://github.com/astral-sh/ruff/releases/download/0.5.4/ruff-x86_64-pc-windows-msvc.zip) gets flagged as a virus (presumably false-positive) in Chromium browsers (Vivaldi 6.8.3381.48). Unfortunately, don't have the bandwidth to do any further investigation on my end.

**Comment by charliermarsh** [comment]
Unfortunately there isn't much we can do here typically.

**Comment by AlexBlandin** [comment]
Thankfully, it seems to have passed, and now isn't flagged. Wish there was more we could do to avoid this in general, but alas.

**Comment by charliermarsh** [comment]
Totally agree.
