### ISSUE TITLE
I001 warning even after running isort

### ISSUE THREAD

**Issue by bje-** [astral-sh/ruff#12457]
One of my source files produces a warning from `ruff`:

```python
from nemo import configfile, regions
from nemo.generators import (CCGT, CCGT_CCS, CST, OCGT, Biofuel, Black_Coal,
                             CentralReceiver, Coal_CCS, DemandResponse, Hydro,
                             PumpedHydroPump, PumpedHydroTurbine, PV1Axis,
                             Wind, WindOffshore)
from nemo.polygons import (WILDCARD, cst_limit, offshore_wind_limit, pv_limit,
                           wind_limit)
from nemo.storage import PumpedHydroStorage
from nemo.types import UnreachableError
```

Running `isort` over the file does not change these statements in any way, so it seems that `ruff` and `isort` are assuming different `isort` settings. I am not running `isort` with any options nor am I using a settings file.

**Comment by charliermarsh** [comment]
Ruff's import sorting rule is designed to be compatible with isort assuming `profile = "black"`, but you're using different isort formatting there. Check out the [FAQ](https://docs.astral.sh/ruff/faq/#how-does-ruffs-import-sorting-compare-to-isort). There are a few other minor deviations that are documented in there.

**Comment by bje-** [comment]
Thanks, and sorry I missed the FAQ entry!

**Comment by charliermarsh** [comment]
No prob!
