### ISSUE TITLE
Add `"src"` to `src` default

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#12454]
We've received a few issues about this, and it's a common source of confusion. Rye actually defaults to this layout, so it's odd that we don't respect it in Ruff.

See, e.g., https://github.com/astral-sh/ruff/issues/12453.

**Comment by MichaReiser** [comment]
@charliermarsh I suspect that you can make the change 10x faster than me. Would you have the time to PR the change. If not, then that's fine and I'll give it a try.

**Comment by charliermarsh** [comment]
Yeah no worries.

**Comment by charliermarsh** [comment]
I'll do it today.
