### ISSUE TITLE
Add Jupyter Notebooks to Ruff's default inclusion

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#12456]
I think it's time we promote Jupyter Notebooks to be included by default in Ruff i.e., promote notebook files to stable.

This requires a minor version bump.

Also, the new native server doesn't run on Jupyter Notebooks unless it's explicitly included using a configuration file.

Reference:
* https://github.com/astral-sh/ruff/issues/12185
* https://github.com/astral-sh/ruff-vscode/issues/546 (native server)

**Comment by MichaReiser** [comment]
Let's make this change in preview so that we can release it with 0.6
