### ISSUE TITLE
Ruff formatter per file ignores problem

### ISSUE THREAD

**Issue by nonoash** [astral-sh/ruff#12459]
Hi,

i'd like to setup different line lengths based on file extensions, for example default 120 and .ipynb 88
I know there is already a way for the linter with:
`[tool.ruff.lint.per-file-ignores]`

but thats for linting, is there something similar for the formatter or a way to fit my case? because i can't find infos on it or make it work with something like:
```
[tool.ruff.lint]
line-length = 120

[tool.ruff.format.per-file-ignores]
"**/*.ipynb" = { line-length = 88 }
```

or
```
[tool.ruff.lint]
line-length = 120

[tool.ruff.format.specific-files]
"**/*.ipynb" = { line-length = 88 }
```

I'm using Ruff v0.5.3 with native server,
Thanks.

**Comment by charliermarsh** [comment]
Unfortunately we don't support this today, but it's tracked in https://github.com/astral-sh/ruff/issues/7696.

**Comment by charliermarsh** [comment]
Merging into that issue.
