### ISSUE TITLE
SyntaxError on py2 code

### ISSUE THREAD

**Issue by serjflint** [astral-sh/ruff#12495]
Hi! After updating from 0.3.4 to 0.5.3 ruff started to print unskippable (can't noqa them) SyntaxError.
Previously comments like `# noqa: E999 py2 incompatibility` worked fine.
An easiest reproducer would be `{}.get('a', 0L)`.

**Comment by MichaReiser** [comment]
Ruff doesn't support parsing or analyzing Python 2. I recommend you to `exclude` python 2 files.

**Comment by serjflint** [comment]
> Ruff doesn't support parsing or analyzing Python 2. I recommend you to `exclude` python 2 files.

It's certainly a reasonable approach. And I don't really want to check them. But it's too much work to separate. The extension is the same for both py2 and py3 files and there is no easy way to build a regex. Tens of thousands of files in different directories. 

The thing is, in previous versions of ruff I could just noqa them in place. Putting a noqa at the beginning of the file doesn't help (as in pylint). On the other hand, only about 10 files raised a SyntaxError when checked by ruff.

**Comment by MichaReiser** [comment]
> The thing is, in previous versions of ruff I could just noqa them in place. Putting a noqa at the beginning of the file doesn't help (as in pylint). On the other hand, only about 10 files raised a SyntaxError when checked by ruff.

You can still do the same, but instead of adding a noqa for those few files, add them to your "exclude" configuration.

**Comment by dhruvmanila** [comment]
https://astral.sh/blog/ruff-v0.5.0#changes-to-e999-and-reporting-of-syntax-errors provides some context on why this was done.

**Comment by serjflint** [comment]
> https://astral.sh/blog/ruff-v0.5.0#changes-to-e999-and-reporting-of-syntax-errors provides some context on why this was done.

Thank you. Now I see the reasoning.
