### ISSUE TITLE
Documentation mismatch between `ruff` and `docs` for `f-string-in-exception`

### ISSUE THREAD

**Issue by UriyaHarpeness** [astral-sh/ruff#12504]
This is a documentation issue, not related to the logic.
This issue is relevant for the current version: 0.5.4.

In https://docs.astral.sh/ruff/rules/f-string-in-exception/ there's a section that shows the traceback before and after, in the after one it does not include the first line of the traceback.

I wanted to open a PR to add the missing line, but when opening the code docstrings it seemed to already include that line:
https://github.com/astral-sh/ruff/blob/2ce3e3ae60ba44700b5e98a61adc96d80b0e4bd3/crates/ruff_linter/src/rules/flake8_errmsg/rules/string_in_exception.rs#L43-L48

I went to the `docs` repo, and there the first line was missing:
https://github.com/astral-sh/docs/blob/main/site/ruff/rules/f-string-in-exception/index.html#L827-L830

I don't know what the source of this mismatch is, but seemed that just opening a manual change to the generated docs is not the way to go. So here I am opening an issue.

**Comment by UriyaHarpeness** [comment]
Sigh... my bad, I'll open a PR soon.
Thanks.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/12508.
