### ISSUE TITLE
ruff_format not shown as format binary

### ISSUE THREAD

**Issue by ic-768** [astral-sh/ruff#12527]
I use neovim and was trying to setup ruff as a formatter. I was not able to get it to work, as I thought that simply using `ruff` as my formatter would be enough, when in fact I had to use `ruff_format`.

![image](https://github.com/user-attachments/assets/58e8d05f-c63f-41f6-95b7-99e03c52ab13)

In the `mason` package manager, it does not show that `ruff_format` is an available executable, just `ruff`.
The only reason I was able to get this to work is because I found other people's configs online and tried copying it.

![image](https://github.com/user-attachments/assets/bb603a0a-4377-49b8-a353-c325f865b881)

For new users who want to set formatting up maybe it would be beneficial to show `ruff_format` as the binary for the formatter.

**Comment by dhruvmanila** [comment]
The `ruff_format` is an identifier which comes from `conform.nvim` while `mason.nvim` (correctly) reports that we provide the `ruff` binary. The `ruff_format` is just an identifier to indicate that it'll run the `ruff format` command and is not an actual executable. You might want to refer to the docs in `conform.nvim` / `mason.nvim`.
