### ISSUE TITLE
Server doesn't consider a file with no extension

### ISSUE THREAD

**Issue by khufu1** [astral-sh/ruff#12539]
consider this minimal example
`
#!/usr/bin/python3
target = None
if target != None:
    print   ("target's not none")
`
if the file that contains the script has a .py extension it will display the following

![Screenshot from 2024-07-27 01-04-31](https://github.com/user-attachments/assets/88b55cb8-9a84-438d-8690-2f8ed4e64161)

and if i remove the .py extension ,no warnings will display nor file can be formatted even though vscode detects
that it's a python file.

ruff version: 0.5.5
Python version: 3.12.4
vscode version: 1.91.1
OS: archlinux

**Comment by majutsushi** [comment]
I just wasted several hours trying to debug why the Ruff server wasn't working for me in Zed, where I was editing extension-less Python scripts that Ruff apparently silently skips. There really needs to be a way for the server to consider these files to make it generally useful.

**Comment by dhruvmanila** [comment]
Apologies for the trouble, I can make this a priority. Thanks for sharing your experience.

**Comment by majutsushi** [comment]
Thanks for the fix! Sorry if I came across as a bit rude, I was just frustrated because according to all the logs I could find everything seemed to be fine, but it still wasn't working. Maybe it would be useful to log ignored files at debug level?

**Comment by dhruvmanila** [comment]
> Thanks for the fix! Sorry if I came across as a bit rude, I was just frustrated because according to all the logs I could find everything seemed to be fine, but it still wasn't working. Maybe it would be useful to log ignored files at debug level?

No need to apologize, sharing your experience is helpful and bugs are always considered high priority :) 

The PR that fixes this also added debug level log for cases where this kind of exlusion happens.
