### ISSUE TITLE
Check supported plugins for new codes

### ISSUE THREAD

**Issue by nkakouros** [astral-sh/ruff#12541]
It would be nice to have a CI job report new, unsupported codes for the plugins (or tools) that ruff already has some support for. There could be a blacklist of codes that were purposefully omitted in ruff. 

As it stands now, users have to request support for new codes. Reading in the docs that e.g. `flake8-builtins` rules are supported may also give the wrong impression that ruff and the plugin are on par. Searching in the issue tracker may not return a relevant issue. The user then has to visit the flake8 extension's page and compare the ruleset with ruff's rules.

Since the list of supported plugins and tools is known, extracting the codes should be straightforward.

Would there be interest in such a CI job?

**Comment by MichaReiser** [comment]
Hi @nkakouros 

Thanks for the suggestion. Can you tell me more about what the CI job would do and how it would work? What does it do when it detects a missing rule?

**Comment by charliermarsh** [comment]
It's a reasonable request but I have no idea how we'd extract them reliably.
