### ISSUE TITLE
Rename `too-many-positional{→-arguments}`

### ISSUE THREAD

**Issue by flying-sheep** [astral-sh/ruff#12619]
In https://github.com/pylint-dev/pylint/pull/9842, they renamed `too-many-positional` to `too-many-positional-arguments` and implemented it.

If we at some point implement support for full names in addition to the codes we support already, this will affect us too.

PS: What’s the schedule for this rule coming out of preview?

**Comment by AlexWaygood** [comment]
Annoyingly, these are strictly-speaking _parameters_ rather than _arguments_... but the new name seems strictly better than the old one, and it's useful to have the same name as pylint. PR welcome!
