### ISSUE TITLE
How to lint a Python string?

### ISSUE THREAD

**Issue by shner-elmo** [astral-sh/ruff#12687]
Hello, I'm working on a script that generate Python code and returns it as a string (doesn't write to disk), and I was wondering whats the best way I can lint the string with `ruff`?

for example:
```py
from ruff import lint_code

code = "def f(x): x*x"
assert lint_code(code) == """def f(x):\n    x * x"""
```

**Comment by MichaReiser** [comment]
Ruff doesn't provide a Python API today. https://github.com/astral-sh/ruff/issues/659 tracks the feature request for a Pyo3 API. 

Your options are:

* Use the `CLI` and pass the code via stdin `ruff check --stdin-filename name.py -`
* Use the wasm API
* Contribute a Pyo3 ApI

**Comment by shner-elmo** [comment]
FYI this is how I ended up doing it:

https://gist.github.com/shner-elmo/b2639a4d1e04ceafaad120acfb31213c
