### ISSUE TITLE
Is there a way for `ruff format` to return the formatted source files as outputs to `stdout` instead of formatting inplace?

### ISSUE THREAD

**Issue by jymchng** [astral-sh/ruff#12793]
As titled, simple question - from the documentation, it seems like it can't do this but let's see.

**Comment by chrreisinger** [comment]
--check
          Avoid writing any formatted files back; instead, exit with a non-zero status code if any files would have been modified, and zero otherwise

**Comment by charliermarsh** [comment]
Yeah if you write via stdin, we write back as stdout, e.g., `cat python/uv/__main__.py | ruff format -`.

**Comment by jymchng** [comment]
> Yeah if you write via stdin, we write back as stdout, e.g., `cat python/uv/__main__.py | ruff format -`.

Thank you for your response - sorry for my delayed response.

I realize that it actually works for the answer you have given me - thank you!

I have a new question if you don't mind - is there a way to dynamically check the files using a Python script? Like sending a source text to `ruff` in Python and get back the formatted source text or linting (with `ruff check` within the Python API, or `ruff format`, respectively).

**Comment by MichaReiser** [comment]
Not yet no. See https://github.com/astral-sh/ruff/issues/659. There's only a WASM API.

**Comment by jymchng** [comment]
Yeah, I guess something like [this](https://www.npmjs.com/package/@astral-sh/ruff-wasm-web) is what I can work with for my Python playground with formatting capability lol - thank you!

**Comment by MichaReiser** [comment]
Yes, that should work. It's also what we use in our playground :)
