### ISSUE TITLE
Disable Ruff lint

### ISSUE THREAD

**Issue by memeLordo** [astral-sh/ruff#12795]
Is there anyway to disable `ruff ` linting completely and leave it only for formattiong? I'm using a NeoVim configuration with Mason. What I have is a double display for linting in `basedpyright` and `ruff`:
![Error](https://github.com/user-attachments/assets/89182f2b-04a3-4f3f-8f0a-803e4309eeb2)

**Comment by memeLordo** [comment]
My previous attemts to set up configuration using help from #12514 and #12778 had no effect.

**Comment by MichaReiser** [comment]
Have you tried setting [lint.enable](https://docs.astral.sh/ruff/editors/settings/#lint_enable)

I'm not really familiar with neovim

**Comment by memeLordo** [comment]
Sent request. My config is used by AstroNvim. I tried to put the code at different places, but still nothing seems to work.

**Comment by dhruvmanila** [comment]
Can you share your Neovim config? I'm specifically interested in how you've setup basedpyright and Ruff. Which plugins are you using to set them up? Is it just `nvim-lspconfig` or do you have any other plugins as well?

**Comment by memeLordo** [comment]
Basically,  `basedpyright` and `ruff` installed via `Mason`, and it configures using AstroNmiv nested structure. Unfortunately, I haven't been able to find the same configuration for `ruff`, because it implies that user would be using it as a main linter, instead of  `basedpyright`. Here is an example: https://github.com/astral-sh/ruff-lsp/issues/384#issuecomment-2038623937
`ruff` works from the package, and I can't manage to configure it inside my nvim-config.

My `basedpyright_config.lua`:
```lua
-- if true then return {} end -- INFO: REMOVE THIS LINE TO ACTIVATE THIS FILE
return {
  "AstroNvim/astrolsp",
  opts = {

    servers = {
      "basedpyright",
    },

    ---@diagnostic disable: missing-fields
    config = {
      basedpyright = {
        before_init = function(_, c)
          if not c.settings then c.settings = {} end
          if not c.settings.python then c.settings.python = {} end
          c.settings.python.pythonPath = vim.fn.exepath "python"
        end,
        settings = {
          basedpyright = {
            analysis = {
              -- ignore = { "*" },
              -- autoImportCompletions = true,
              -- autoSearchPaths = true,
              diagnosticMode = "openFilesOnly",
              useLibraryCodeForTypes = true,
              -- reportMissingImports = true,
              typeCheckingMode = "standard",
            },
          },
        },
      },
    },
  },
}
```

**Comment by dhruvmanila** [comment]
> Unfortunately, I haven't been able to find the same configuration for `ruff`, because it implies that user would be using it as a main linter, instead of `basedpyright`.

I'm not familiar with AstroNvim but are you saying that Ruff is configured to be the default linter in that framework and you're interested in using Ruff only as a formatter? I couldn't find any references to "ruff" in the repository (https://github.com/search?q=repo:AstroNvim/AstroNvim%20ruff&type=code). It's a bit difficult to help without knowing the way you've configured Ruff in your editor 😅

**Comment by memeLordo** [comment]
That's the point, it isn't configured at all, but still works. I will ask in a forum of AstroNvim for this.

**Comment by memeLordo** [comment]
> Have you tried setting [lint.enable](https://docs.astral.sh/ruff/editors/settings/#lint_enable)
> 
> If you need more help, please share your neovim configuration.
Here how you, presumably, can configure the same code in AstroNvim:

`.../plugins/ruff_config.lua`:
```lua
return {
  "AstroNvim/astrolsp",
  opts = {
    ruff_lsp = {
      settings = {
        ruff = {
          lint = {
            enable = false,
          },
        },
      },
    },
  },
}
```

**Comment by memeLordo** [comment]
But still I get the same double-linting. Will be waiting for the reply from AstroTeam.

**Comment by dhruvmanila** [comment]
Can you confirm (via docs?) the name of the Ruff server as defined in the plugin? Is it `ruff_lsp` or `ruff` (native server)? Either way, it should be `init_options` instead of `settings` if these are the server settings.

**Comment by memeLordo** [comment]
Yeah, it's true.
