### ISSUE TITLE
`noqa` comments parsing logic

### ISSUE THREAD

**Issue by InSyncWithFoo** [astral-sh/ruff#12808]
Currently these are all valid `noqa` comments:

```py
# noqa: A100,B101
# noqa: A100 B101
# noqa: A100, B101
# noqa: A100 , B101
```

```py
# noqa: A100B101
# noqa: A100,,B101
```

The formats in the second group should be invalid.

**Comment by charliermarsh** [comment]
I think `noqa: A100,,B101` is maybe ok since it's at least unambiguous (but not currently formatted).

**Comment by charliermarsh** [comment]
`# noqa: A100B101` is definitely wrong.
