### ISSUE TITLE
Auto-format `# noqa` directives

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#12810]
It'd be nice to have a lint rule to enforce consistent formatting of `# noqa` directives (e.g., `# noqa: F401, F841`), along with a fix to auto-format them.

**Comment by charliermarsh** [comment]
Partly inspired by some of the cases in #12808.

**Comment by dhruvmanila** [comment]
I wonder if this should be in the formatter instead as there's probably only one way to format them (we shouldn't consider line length in this case i.e., not breaking them into multiple lines). Although, the linter has all the infrastructure for it but we could extract that out as a crate.

**Comment by MichaReiser** [comment]
Related issue https://github.com/astral-sh/ruff/issues/10160
