### ISSUE TITLE
[Lint Request] Lint against `assertTrue`/`assertFalse` instead of more specific asserts

### ISSUE THREAD

**Issue by alanhdu** [astral-sh/ruff#12851]
The default `unittest.TestCase` uses a set of specialized `assert*` functions to give better error messages (unlike `pytest` which does some metaprogramming to work with "bare" `assert` statements).

Would it be possible to have a lint that auto-detects (and corrects) using the less general `assertTrue/assertFalse` instead of the more specialized asserts (since those will have subpar error message)? For instance, a lint that would autofix
`self.assertTrue(isinstance(x, int))` to `self.assertIsInstance(x, int)`?

I think the actual implementation should be straightforward, but one subtlety is that this would be incompatible with the existing 

This would be incompatible with PT009 (which encourages "bare asserts"), but presumably we can just document that users should only use one or another?

I assume this is already implemented somewhere in some other linter, but I actually haven't seen one before -- in our codebase, I just have a set of regexes to apply (which isn't great, but so far hasn't led to too many false positives either).

**Comment by Avasam** [comment]
> This would be incompatible with PT009 (which encourages "bare asserts"), but presumably we can just document that users should only use one or another?

That would be expected given you probably shouldn't be mixing unittest and pytest together ^^

**Comment by dhruvmanila** [comment]
This should be addressed by https://github.com/astral-sh/ruff/issues/2417 which has rules for your specific use-case. I'll merge this issue into it.
