### ISSUE TITLE
LSP: include `version` on code action responses

### ISSUE THREAD

**Issue by LDAP** [astral-sh/ruff#12855]
Including `version` on code action responses would prevent outdated code actions being applied if the document has changed in the meantime.

See https://github.com/sublimelsp/LSP-ruff/issues/72

**Comment by dhruvmanila** [comment]
Can you clarify which "version" key are you talking about here? The `CodeAction` type doesn't have a `version` field: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction

**Comment by dhruvmanila** [comment]
Oh, do you mean the document version in `TextDocumentEdit`?

**Comment by dhruvmanila** [comment]
I think this could be merged into https://github.com/astral-sh/ruff/issues/11730

**Comment by LDAP** [comment]
@rchl

**Comment by dhruvmanila** [comment]
Thanks for confirming. I'll merge this into #11730.
