### ISSUE TITLE
Import sorting does not (immediately) converge?

### ISSUE THREAD

**Issue by ax3l** [astral-sh/ruff#12872]
Hi,

I am using `ruff` verison 0.5.6 in [pyAMReX](https://github.com/AMReX-Codes/pyamrex) (linter, not the formatter).

I am using [pre-commit](https://pre-commit.com/) to update our source code after merge to `development`. I used `black` in the past and switched this week, discovering on August 10th and following that `ruff` creates a lot of rotating changes when run multiple times:
https://github.com/AMReX-Codes/pyamrex/commit/74e076228d4f3d2d6d7ca137610b60b4f91495a5
https://github.com/AMReX-Codes/pyamrex/commit/5dc9c029bacec441ca4484763b34527112408d2b
https://github.com/AMReX-Codes/pyamrex/commit/902c41b012b58fe9479ab6fd414193d9c5f81a97
...
https://github.com/AMReX-Codes/pyamrex/commits/development/

for code of the form
```py
from a.b1 import c1
from a.b1 import c1 as cc1
from a.b2 import c2
from a.b3 import c3
```

Is there a way to avoid this?

This happens for us on `.pyi` headers and we intentionally have an alias for some of those imports (for backwards compatibility with a public API change that we are shipping).

**Comment by charliermarsh** [comment]
I can take a look.

**Comment by charliermarsh** [comment]
It's possible that we've just never seen this pattern before and so the sort isn't stable:
```python
from amrex.space1d.amrex_1d_pybind import IntVect1D
from amrex.space1d.amrex_1d_pybind import IntVect1D as IntVect
```

**Comment by ax3l** [comment]
That's definitely possible. I recently switched over to all-`ruff`ing from isort+black+... The pattern here is for backwards compatibility as we face out the `IntVect` type for more explicit versions in our public APIs.

**Comment by charliermarsh** [comment]
Did you have any sort of configuration set? Like:
```toml
[tool.ruff.lint.isort]
force-single-line = true
```

The style in those files doesn't match our standard style, so trying to figure out how to reproduce.

**Comment by ax3l** [comment]
No, none of that kind set. I know add "amrex" as known first party module, but that's all I set (no change with our without that option regarding the stability)

**Comment by charliermarsh** [comment]
Okay thanks. I'm just struggling because if I check out `858e2a9359c6379782b3f2766e5415ba61be44f2` and run `ruff check --select I --fix`, it completely changes the import style in those files, so I don't think Ruff was run on those commits. Am I misunderstanding?

**Comment by ax3l** [comment]
That is right, this is just the commit before I switched from black+isort to ruff.

Here is how I see the issue:

1. I [build](https://github.com/AMReX-Codes/pyamrex?tab=readme-ov-file#build) the project.
2. I run [pybind-stubgen](https://github.com/sizmailov/pybind11-stubgen) via [this script](https://github.com/AMReX-Codes/pyamrex/blob/development/.github/update_stub.sh) to update the `.pyi` files in the repo
3. I run the ruff linter

The last step creates the unstable result for these imports.

**Comment by ax3l** [comment]
Example file after step 1 & 2: [__init__.pyi.txt](https://github.com/user-attachments/files/16615669/__init__.pyi.txt)

**Comment by ax3l** [comment]
This is super interesting, the local files I create differ from the PRs I autogenerated above (only difference I know is that they used ruff 0.5.6).

**Comment by ax3l** [comment]
Oh no, I think I see the issue, it's the pre commit.

Either I should list no types or include explicitly pyi
https://github.com/AMReX-Codes/pyamrex/blob/c61add4fd44ad4ec69b131865375d76c68f12b29/.pre-commit-config.yaml#L82

**Comment by ax3l** [comment]
I think it was indeed the case that in the pre-commit rules, the `.pyi` files were not sorted at all, resulting in the unstable result of `pybind11-stubgen` to fluctuate.

The underlying issue is  that I did not know what to put in `types_or`, which comes from pre-commit itself, but I only looked at the ruff docs:
https://github.com/astral-sh/ruff-pre-commit?tab=readme-ov-file#using-ruff-with-pre-commit
https://pre-commit.com/#filtering-files-with-types

I am so sorry for the confusion and noise.
