### ISSUE TITLE
 B019 discuss  

### ISSUE THREAD

**Issue by linpan** [astral-sh/ruff#12917]
`  @lru_cache(maxsize=128)
    # def get vcab size
    def vocab_size(self):
        return self.tokenizer.vocab_size`

 B019 Use of `functools.lru_cache` or `functools.cache` on methods can lead to memory leaks

**Comment by MichaReiser** [comment]
Thanks for opening the issue

Could you help me understand why `B019` use of `lru_cache` or `functions.cache` can lead to memory issues and in what situations this happens?

**Comment by MichaReiser** [comment]
Can you expand on what you wan to discuss about `B019`? It's not clear to me what this issue is asking for.
