### ISSUE TITLE
PLW0211: `@staticmethod ; def __new__(cls, ...)` disagrees with the Python docs

### ISSUE THREAD

**Issue by cclauss** [astral-sh/ruff#12930]
```
ruff check --select=PLW0211 - <<EOF
class TestNew:
    @staticmethod
    def __new__(cls, title, *args, **kwargs):
        print(cls)
EOF
```
> -:3:17: PLW0211 First argument of a static method should not be named `cls`

This contradicts https://docs.python.org/3/reference/datamodel.html#basic-customization which uses `cls` and states that `__new__()` is a static method.

PEP20 statement `Explicit is better than implicit.` suggests that `@staticmethod` should be allowed in this code.

**Comment by AlexWaygood** [comment]
I think that's a somewhat extreme reading of PEP20! But yes, we should make an exception for `__new__` here, which is obviously very special
