### ISSUE TITLE
Feature: Disable unused args check for stub functions

### ISSUE THREAD

**Issue by dargueta** [astral-sh/ruff#12963]
Keywords: ARG, ARG001, unused argument

### Feature

It'd be great if we could have some settings to disable the unused argument check for stub and abstract functions, such as one that only throws `NotImplementedError` and does nothing else. The [Flake8 plugin](https://pypi.org/project/flake8-unused-arguments/) has a relevant setting for this.

### To Reproduce

This code:

```py
def foo(a, b):
    raise NotImplementedError
```

Command: `ruff check --isolated --select ARG repro.py `

Output:
```
repro.py:1:9: ARG001 Unused function argument: `a`
  |
1 | def foo(a, b):
  |         ^ ARG001
2 |     raise NotImplementedError
  |

repro.py:1:12: ARG001 Unused function argument: `b`
  |
1 | def foo(a, b):
  |            ^ ARG001
2 |     raise NotImplementedError
  |

Found 2 errors.
```

### Configuration

The output is the same if I don't run it in isolated mode. However, in case you may find it useful, this is  the relevant part of my Ruff configuration in `pyproject.toml`.

```toml
[tool.ruff.lint]
extend-ignore = [
    "COM812",
    "D105",
    "EM",
    "FBT",
    "PLR2004",
    "S311",
    "TRY003",
]
select = ["ALL"]
```

### Platform

* Python: 3.12.3
* Ruff: 0.6.1

**Comment by charliermarsh** [comment]
For some reason we already do this for all of the `ARG` rules except `ARG001`.
