### ISSUE TITLE
Feature request: Require explanations on rule overrides

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#12992]
Similar to [this ESLint rule](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html), I don't want any Ruff rules to be overridden without an explanation of why.

**Comment by dhruvmanila** [comment]
Is this the same as https://github.com/astral-sh/ruff/issues/5182 ?

**Comment by tylerlaprade** [comment]
Yes, looks like it, sorry for the duplicate!
