### ISSUE TITLE
Unspecific error message from tiny typo

### ISSUE THREAD

**Issue by turkishmaid** [astral-sh/ruff#13022]
Using Ruff 0.6.1 as native server in VSCode 1.92.1, Ruff extension v2024.42.0, on MacOS 14.4 (but I guess all of that is irrelevant).

With a tiny typo like this in the `ruff.toml`

```toml
[lint]
ignore = [
## typo, should be "EM102"
  "ME102", # f-string in exception
]
select = ["ALL", "TD006", "TD007", "FIX"]
```

I am shown some unspecific Ruff error popup referring to the logs:

> Error while resolving settings from workspace /(redacted). Please refer to the logs for more details.
Source: Ruff

Unfortunately, in the logs there is no trace of the actual issue:

![image](https://github.com/user-attachments/assets/eb15e76a-bd5c-42c6-90d2-f9ed717ef93a)

Took me ages to find out and I was only successful when I commented out the whole `ruff.toml` and added it back line by line.

Would it be possible to have a message like so instead? In the popup if that is possible, or at least in the Ruff output...

> ruff.toml(/path): line 12: [lint.ignore]: "ME102" is not a valid rule

Even better would be when Ruff would lint its own settings and issue warnings about incorrect or deprecated settings in `ruff.toml` or  `pyproject.toml`.

Else: Great tool. Love lightning fast linting. Sometimes I create an issue deliberately just to see it pop up 😁

**Comment by dhruvmanila** [comment]
Can you try turning on the server log messages via https://docs.astral.sh/ruff/editors/settings/#traceserver ?

```json
{
    "ruff.trace.server": "messages"
}
```

You should then see the log messages in the output channel.

I agree that this is a bit annoying that the notification suggests to refer to the log messages but there won't be any until the user turns them on. This relates to https://github.com/astral-sh/ruff/issues/12523.

**Comment by dhruvmanila** [comment]
Regardless, I don't see any specific location in the message:
```
2024-08-21 14:57:09.926 [info] [Trace - 2:57:09 PM]   29.078199584s ERROR ThreadId(42) ruff_server::session::index::ruff_settings: Failed to parse /Users/dhruv/playground/ruff/pyproject.toml
```

Although it is visible when I run it from the command-line:
```console
❯ ruff check .                         
ruff failed
  Cause: Failed to parse /Users/dhruv/playground/ruff/pyproject.toml
  Cause: TOML parse error at line 1, column 1
  |
1 | [tool.ruff.lint]
  | ^^^^^^^^^^^^^^^^
Unknown rule selector: `ME102`
```
