### ISSUE TITLE
[red-knot] emit diagnostics on invalid syntax

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#13058]
We regularly hit confusion because of the error-recovering parser letting syntax errors pass silently, and then red-knot behaving in unexpected ways because we didn't realize there was a syntax error in the code. We should emit diagnostics on syntax errors to avoid this.

Related: #12923

**Comment by MichaReiser** [comment]
We already do this but in `lint_syntax`.

https://github.com/astral-sh/ruff/blob/dce87c21fdf73a58f3821cae5e71b9da234e29ce/crates/red_knot_workspace/src/lint.rs#L40-L51

We should move this into `check_file`.
