### ISSUE TITLE
F841: Unused variable with boolean expression not entirely deleted by --fix --unsafe-fixes

### ISSUE THREAD

**Issue by Liritt** [astral-sh/ruff#13054]
Hello,

We encountered an issue while using the --unsafe-fixes parameter with Ruff 0.6.1. Specifically, the removal of an unused variable containing a boolean expression caused a problem.

The problematic line is: `active = offer["status"] == "Active"`.
After running the command ruff check --fix --unsafe-fixes, Ruff only removed the `active =` portion, leaving the `offer["status"] == "Active"` part intact in our code.

Firstly, if Ruff can't delete the entire line, shouldn't it consider the line unfixable and ignore it?
Secondly, given that the variable is unused, perhaps Ruff should delete the entire line to avoid this kind of error? (suggestion)

Could you please address this issue?

Thanks!

**Comment by MichaReiser** [comment]
Hi @Liritt 

I can see how removing the entire line is desired in this case. The reason why the rule's auto fix doesn't remove the entire line is because the right hand side could have a side effect in which case removing it would not be safe:

```python
def f():
	unused = sys.stdout.write("bla")
```

The good news is that you can use `B015` to detect and remove unused comparisons. Unfortunately, that rule has no auto fix today

**Comment by MichaReiser** [comment]
A future Ruff version may be able to remove the right-hand side if it can reason about whether the right-hand side has side effects or not.  I don't think we should introduce an option that always removes the right hand side because that can very easily lead to bugs.

**Comment by Liritt** [comment]
I see. Well, thanks for replying ! We'll handle it by hand then.
Have a nice day !

**Comment by MichaReiser** [comment]
Thanks, you too and sorry that we don't have the infrastructure today to handle this better.
