### ISSUE TITLE
playground loads half way between light and dark mode

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#13066]
firefox 130.0b7, "Website appearance" setting is set to dark

![image](https://github.com/user-attachments/assets/555ee13a-1c00-4e31-8d92-e3a51d60001c)

toggling dark mode off and on again fixes it:

![image](https://github.com/user-attachments/assets/ad99ebc6-8f09-4682-b83f-7e42f858c636)

**Comment by KotlinIsland** [comment]
same in chrome

**Comment by dhruvmanila** [comment]
Yeah, I've noticed this too. Thanks for opening an issue for it.
