### ISSUE TITLE
Inconsistent strikethrough in pylint tracking issue (#970)

### ISSUE THREAD

**Issue by BlindChickens** [astral-sh/ruff#13078]
In the pylint/ruff gap tracking issue #970 some rules are striked as to indicate that it is considered obsolete/unneeded.

As I am using this issue in scripts to determine the gap every now and then, I noticed one of them is not striked like the rest.

`confusing-consecutive-elif / R5601` has just the name striked, while the rest is striked through to the end of the rule code.

If possible can it be fixed?

Thanks in advance

**Comment by MichaReiser** [comment]
Done. I hope I did it correctly.
