### ISSUE TITLE
RUF031

### ISSUE THREAD

**Issue by dimaqq** [astral-sh/ruff#13072]
ruff 0.6.2

```py
ops/framework.py:715:29: RUF031 [*] Avoid parentheses for tuples in subscripts.
    |
714 |         kind_: str = kind or cls.handle_kind
715 |         self._type_registry[(parent_path, kind_)] = cls
    |                             ^^^^^^^^^^^^^^^^^^^^ RUF031
716 |         self._type_known.add(cls)
    |
    = help: Remove the parentheses.
```

The thing is, type registry is meant to be indexed by tuples, it's a mapping of `tuple -> class`.

Or am I missing something obvious here?

**Comment by dimaqq** [comment]
Ugh, the default is to write `self._type_registry[parent_path, kind_] = cls`.

I guess I can do that. I may have to take some time to come up with a rationale either way.

**Comment by AlexWaygood** [comment]
You can configure it using https://docs.astral.sh/ruff/settings/#lint_ruff_parenthesize-tuple-in-subscript
