### ISSUE TITLE
[red-knot] defer annotation resolution when __future__.annotations is active

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#13070]
Red-knot panics on this:

```python
class IndexingMixin:
    def iloc(self) -> _iLocIndexer:
        return True


@doc(IndexingMixin.iloc)
class _iLocIndexer:
    pass
```

Changing the return type of `IndexingMixing.iloc` or changing the `_iLocIndexer` decorator to not reference `IndexingMixing.iloc` removes the panic

Source: https://github.com/pandas-dev/pandas/blob/0c24b20bd9cd743bd5f5afceb1a6fef54a2dbdc1/pandas/core/indexing.py#L4

**Comment by carljm** [comment]
We have support now for deferring resolution of annotations, which is the first part of fixing this. The second part is to extend that support to any module where `from __future__ import annotations` is active; currently it only applies in a stub file.

**Comment by carljm** [comment]
Confirmed that the above panic no longer occurs checking pandas. There is one other panic which is a shallow bug in with-item handling, I'll push a fix for it shortly.

**Comment by carljm** [comment]
With this fix and https://github.com/astral-sh/ruff/pull/13409 we can check pandas with no panic.

**Comment by charliermarsh** [comment]
Sweet
