### ISSUE TITLE
FURB105 fix removes `sep` arguments with side effects

### ISSUE THREAD

**Issue by dscorbett** [astral-sh/ruff#13126]
The fix for [FURB105](https://docs.astral.sh/ruff/rules/print-empty-string/) removes unneeded `sep` arguments even when they might have side effects. In that case, the fix should be omitted or marked unsafe.

```console
$ ruff --version
ruff 0.6.2
$ cat furb105.py
print(sep=print("sep"))
$ python furb105.py
sep

$ ruff check --isolated --select FURB105 furb105.py --fix
Found 1 error (1 fixed, 0 remaining).
$ cat furb105.py
print()
$ python furb105.py


```

**Comment by AlexWaygood** [comment]
I'd be happy to accept a PR that marked the fix as unsafe if we detected the argument to `sep=` as something that could have a side effect. We could use the `contains_effect` function we have here for that purpose: https://github.com/astral-sh/ruff/blob/483748c188e854370836182c6f08b35fb140ae93/crates/ruff_python_ast/src/helpers.rs#L46.

However, I think we should still offer the fix (though it'll be marked as unsafe), even in these situations. I think it'll honestly be relatively rare for somebody to pass in a function that has a side effect to `sep=` here, and `contains_effect()` errs on the side of assuming that arbitrary functions might have side effects, although in reality they often won't.
