### ISSUE TITLE
Formatter: quote-style bug

### ISSUE THREAD

**Issue by blackteahamburger** [astral-sh/ruff#13120]
With `quote-style = "double"`.

Example:

```
# test.py
test = {"x": 0}
print(f"{test['x']}")
```
```
$ ruff format test.py
1 file left unchanged
```
`test['x']` is left unchanged.

**Comment by AlexWaygood** [comment]
Hi! I can reproduce with `target-version` set to `"py311"`, but not with `target-version` set to `"py312"`. Do you have `target-version` or `requires-python` set in your `pyproject.toml` or `ruff.toml` config file at all? (The reason for this is that `f"{test["x"]})"` is not a valid f-string on Python 3.11. Python's grammar was changed in 3.12 as part of PEP 701.)

**Comment by blackteahamburger** [comment]
I can reproduce it with `ruff format test.py --config "target-version = 'py312'" --config "format.quote-style = 'double'"`

**Comment by dhruvmanila** [comment]
Is the expected output that the formatter should change the code like so?
```diff
- print(f"{test['x']}")
+ print(f"{test["x"]}")
```

That is available as a preview style, but only when the target version is 3.12 or later: https://play.ruff.rs/9cea74b1-c3fe-4f08-94bc-05f0c53a7ead

**Comment by blackteahamburger** [comment]
Yes, it's expected, thanks.
