### ISSUE TITLE
Remove `if TYPE_CHECKING: pass`

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/ruff#13132]
You can get these as a result of F401 cleanup. It would be nice for the F401 fix to automatically do this (or potentially this could be its own rule)

**Comment by hauntsaninja** [comment]
Ahhhh I should have --select ALL -ed it, sorry for the noise!

**Comment by charliermarsh** [comment]
Haha no worries. Sometimes I just drop code in the playground and enable `ALL` to see if we already have diagnostics for something.
