### ISSUE TITLE
Improving presentation of docstrings in python intellisense

### ISSUE THREAD

**Issue by nikhil-swamix** [astral-sh/ruff#13150]
# Info
Issue Type: inconvenience/ enhancement
KW searched : markdown, formatting 
Using : Ruff extension vscode by astral v2024.42.0 
context: this is dummy project using tortoise ORM, exploring the feature of ruff

![image](https://github.com/user-attachments/assets/df4cdca1-7c1c-496f-b582-835067757f19)

### Can this be Rendered as a proper formatted markdown?
while intellisense worked fine, docstrings are giving unformatted code when hovered over a language token like class/function. 

is it a extension issue or ruff issue? i believe its extension issue as the pylance is rendering markdown likethis
![image](https://github.com/user-attachments/assets/f6f6948b-e731-4ce0-81f7-c7c7be0d0814)

i like how all overloads/ function signatures are shown by ruff , like lets say null=True when compared to pylance, but misses on presentation, maybe vertically show the info args rather than a dense? please let me know at earliest.

side question: is  required to be rust expert to contribute to ruff? or this repo is for purely vscode ext only?

**Comment by dhruvmanila** [comment]
Hey, thanks for using Ruff. I'm assuming that you're using both the Ruff extension and the Pylance extension. Currently, Ruff only provides hover implementation for NoQA codes in the comments as seen at https://docs.astral.sh/ruff/editors/features/#hover and it doesn't support providing hover information for any symbols. I'm not exactly sure why you're getting two different content for the same symbol.

> side question: is required to be rust expert to contribute to ruff?

I think basic knowledge of Rust would be required if you want to contribute to the Rust code, I wouldn't necessarily say that one needs to be an expert. You can refer to the [contributing guidelines](https://docs.astral.sh/ruff/contributing/) for more information.

>  or this repo is for purely vscode ext only?

This repository (https://github.com/astral-sh/ruff) contains the code for the `ruff` binary and the documentation that's hosted at https://docs.astral.sh/ruff while the VS Code extension is in https://github.com/astral-sh/ruff-vscode. Additionally, the implementation of the language server that's used to power any editor using the [language server protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) is present under the [`ruff_server`](https://github.com/astral-sh/ruff/tree/main/crates/ruff_server) crate.

Hope this is helpful, I'll close this issue as resolved but feel free to ask any other questions that you might have.
