### ISSUE TITLE
How to ignore specific import being sorted

### ISSUE THREAD

**Issue by myslak71** [astral-sh/ruff#13156]
I wanna ignore specific import line from being sorted since I wanna have it imported first but I'd like to organize all remaining imports.
```
from tracer import tracer  # noqa: I001

from bmodule import importb
from amodule import a
```

`# fmt: skip` is being ignored completely - so it organizes imports anyway
` # noqa: I001` stops ordering completely even for lines without `noqa`

Im running ruff check --select I

**Comment by AlexWaygood** [comment]
Hi! I think our [`lint.isort.force-to-top` setting](https://docs.astral.sh/ruff/settings/#lint_isort_force-to-top) will do this for you. E.g. in a `pyproject.toml` file:

```toml
[tool.ruff.lint.isort]
force-to-top = ["tracer"]
```

Does that work?

**Comment by myslak71** [comment]
it works partially - it just moves the import to the top of own modules - is there a way to move it all the way to the top even before builtin modules?

**Comment by AlexWaygood** [comment]
Yeah, you can define a custom section and put `tracer` in that section, then use `section-order` to enforce that that section comes before all others:

```toml
[tool.ruff.lint.isort]
sections = {"tracer" = ["tracer"]}
section-order = [
    "future",
    "tracer",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

- https://docs.astral.sh/ruff/settings/#lint_isort_sections
- https://docs.astral.sh/ruff/settings/#lint_isort_section-order
