### ISSUE TITLE
[red-knot] assert that we don't infer the same expression/definition in multiple regions

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#13168]
We should not double-infer the same expression (or the same definition) in e.g. both "scope" region and "definition" region.

To check this invariant, we could modify `TypeInferenceBuilder::extend` to check that the sets of keys in the two expression maps and definition maps being combined are disjoint.

This will probably be a bit costly, so we probably want to do it only in a debug build.

**Comment by carljm** [comment]
@MichaReiser I think you recently added an assertion for this and cleaned up the existing issues? Closing as completed, feel free to reopen if you feel there's more we should do here.

**Comment by MichaReiser** [comment]
I added an assertion for expressions. I don't think we currently handle `Definition`s but it's also unclear to me how to detect this. However, we do have unit tests that pull the types of every (or most) definitions... so maybe that's fine for now
