### ISSUE TITLE
[red-knot] Fixes for string literal handling

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#13224]
* Chane the type of `StringLiteralType::value` to `Option<Box>` so that we can distinguish between empty strings in the source code and strings that were truncated
* Avoid building strings that are larger than `MAX_STRING_LITERAL_SIZE` when concatenating strings with `+` in `infer_binary_expression`

See comments in https://github.com/astral-sh/ruff/pull/13117

**Comment by AlexWaygood** [comment]
> * Chane the type of `StringLiteralType::value` to `Option<Box>` so that we can distinguish between empty strings in the source code and strings that were truncated

I think we should just use `Type::LiteralString` (which means "a string literal, but not one we know the value of") for the latter target than changing the type of `StringLiteralType::value`
