### ISSUE TITLE
Code navigation

### ISSUE THREAD

**Issue by maidamai0** [astral-sh/ruff#13239]
Hi, Thanks for your great work.
However, it seesm `code navigation` function is missing now in `ruff`

Will the `code navigation` feature be added in the future?

**Comment by dhruvmanila** [comment]
I'm assuming that by "code navigation" you mean goto definition, goto references, etc. If so, that is planned but it'll be taken up after the ongoing red knot project. There's some discussion in https://github.com/astral-sh/ruff/discussions/10581. I'll close this to keep the issue tracker actionable. We'll open a tracking issue once we start working on that.
