### ISSUE TITLE
Error on Neovim after upgrading to 0.6.3

### ISSUE THREAD

**Issue by Zeioth** [astral-sh/ruff#13238]
## Description
Ruff displays errors on neovim (installed using)

## Screenshot
![screenshot_2024-09-04_09-17-36_480641034](https://github.com/user-attachments/assets/472f8496-d270-4eb8-9dc0-51a46aaab36d)

![screenshot_2024-09-04_09-18-48_932678326](https://github.com/user-attachments/assets/71df3752-4241-4d3d-b6a6-da08f184c53f)

## LSP Log
```
[START][2024-09-04 09:14:29] LSP logging initiated
[ERROR][2024-09-04 09:14:29] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "2"\n'
[START][2024-09-04 09:14:36] LSP logging initiated
[ERROR][2024-09-04 09:14:36] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "2"\n'
[ERROR][2024-09-04 09:15:27] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "3"\n'
[ERROR][2024-09-04 09:15:28] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "4"\n'
```

**Comment by Zeioth** [comment]
also, my ruff-lsp version

![screenshot_2024-09-04_09-21-14_744180110](https://github.com/user-attachments/assets/3181d9b1-6e19-42e2-a77b-82d9a7964520)

**Comment by MichaReiser** [comment]
Closing as duplicate of https://github.com/astral-sh/ruff-lsp/issues/486

**Comment by dhruvmanila** [comment]
Let's keep this open as the notification is coming from the native server.

Can you try removing `ruff_lsp` and only running the native server? It's not recommended to use both at the same time.

**Comment by dhruvmanila** [comment]
Can you also check the logs via `:LspLog` and check if there's any error message present there? I think you'll need to turn on the server tracing like so:
```lua
require('lspconfig').ruff.setup({
  trace = 'messages',
  init_options = {
    settings = {
      logLevel = 'debug',
    },
  },
})
```

**Comment by dhruvmanila** [comment]
Sorry, I didn't notice the logs that you've provided. That doesn't contain anything relevant, you'll need to turn on server tracing via the config that I've provided in my previous comment.

**Comment by Zeioth** [comment]
It seems to have been fixed, to I'm closing this for now.

**Comment by Zeioth** [comment]
I think I found the issue:
It seems after `0.6.3`, only ruff-lsp from mason is necessary. As that already includes linter and formatter. And installing old packages would cause conflict. I will report it to mason.

**Comment by Zeioth** [comment]
The issue is on ruff itself, so the workaround on my end has been using `ruff-lsp` + `pywright`.

**Comment by MichaReiser** [comment]
@Zeioth please stop opening and closing this issue unnecessarily because it triggers a notification for everyone observing the repository. 

To get this resolved, please provide us with the log that @dhruvmanila asked you for. It's very difficult to help you without it.

**Comment by Zeioth** [comment]
@MichaReiser Here is the log generated by 

## Process followed to generate the log file

* opening nvim
* Exucuting `:lua require('lspconfig').ruff.setup({ trace = 'messages', init_options = { settings = { logLevel = 'debug' } } })
`
* Opening a python file

Executing the command after the python file has been opened generates the same debug output, so it should be the good one.

## log file (when opening a python file and pass the cursor over lines)

```
[START][2024-09-21 12:42:58] LSP logging initiated
[ERROR][2024-09-21 12:42:58] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	"   0.000011050s  WARN main ruff_server::server: No workspace(s) were provided during initialization. Using the current working directory as a default workspace...\n"
[ERROR][2024-09-21 12:42:59] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	"   0.012430178s  WARN ruff:main ruff_server::server: LSP client does not support dynamic capability registration - automatic configuration reloading will not be available.\n"
[ERROR][2024-09-21 12:43:01] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "2"\n'
[ERROR][2024-09-21 12:43:01] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "3"\n'
[ERROR][2024-09-21 12:43:57] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "27"\n'
```

## log file (when lsp autocomplete is triggered)
```
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 424.907668433s DEBUG  ruff:worker:5 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/utils/controller.py\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "103"\n'
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.022634237s ERROR  ruff:worker:8 ruff_server::server::api: An error occurred with result ID 73: failed to deserialize diagnostic data: invalid length 0, expected struct AssociatedDiagnosticData with 4 elements\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	"Exception occurred for message \"104\": AttributeError: 'NoneType' object has no attribute 'get'\nTraceback (most recent call last):\n  File \"/home/zeioth/.local/share/nvim/mason/packages/ruff-lsp/venv/lib/python3.12/site-packages/pygls/protocol/json_rpc.py\", line 194, in _execute_request_callback\n    self._send_response(msg_id, result=future.result())\n                                       ^^^^^^^^^^^^^^^\n  File \"/home/zeioth/.local/share/nvim/mason/packages/ruff-lsp/venv/lib/python3.12/site-packages/ruff_lsp/server.py\", line 992, in code_action\n    fix = cast(DiagnosticData, diagnostic.data).get(\"fix\")\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'get'\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.084355442s DEBUG  ruff:worker:4 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/utils/controller.py\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.092566072s DEBUG  ruff:worker:9 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/utils/controller.py\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.277145226s DEBUG ruff:worker:10 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/utils/controller.py\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.707603056s DEBUG ruff:worker:11 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/utils/controller.py\n"
[ERROR][2024-09-21 12:53:50] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "105"\n'
[ERROR][2024-09-21 12:53:52] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"	'Cancel notification for unknown message id "106"\n'
```

## More info
Might be a problem in the package itself?

* by installing ruff-lsp on mason, I get linting and formatting.
* by installing ruff on mason, I get linting and formatting.
* none of them provide lsp autocompletion / go to definition.

**Comment by MichaReiser** [comment]
Thanks for sharing the logs. From the logs, it seems you're running both `ruff-lsp` and `ruff` (server) at the same time. This is not a supported setup and shouldn't be needed. Can you try to remove `ruff-lsp` and only use `ruff` server?

```
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	" 425.022634237s ERROR  ruff:worker:8 ruff_server::server::api: An error occurred with result ID 73: failed to deserialize diagnostic data: invalid length 0, expected struct AssociatedDiagnosticData with 4 elements\n"
[ERROR][2024-09-21 12:53:47] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff-lsp"	"stderr"
```

**Comment by Zeioth** [comment]
@MichaReiser I've tried with `ruff` alone. Now I only get this error when I trigger lsp autocomplete (which doesn't work). Linting and formatting work as expected.

```
[ERROR][2024-09-22 15:19:50] .../vim/lsp/rpc.lua:770	"rpc"	"/home/zeioth/.local/share/nvim/mason/bin/ruff"	"stderr"	"  59.355577387s DEBUG ruff:worker:16 ruff_server::resolve: Included path via `include`: /home/zeioth/raven-app/src/main.py\n"
```

Because you say using both ruffs at the same time is not supported, I understand `ruff-lsp` is already included inside `ruff`, and lsp autocompletion should be working fine?

If I install pyright + ruff or ruff-lsp everything seems to work as expected.

**Comment by MichaReiser** [comment]
What you're seeing there isn't an error. It's only a debug message. I think you can turn it of again by removing the `logInfo` setting

> ruff, and lsp autocompletion should be working fine

Ruff's LSP doesn't provide any auto completion. It only provides formatting and linting capabilities.

**Comment by Zeioth** [comment]
Got it. Thank you. I think we can close this for now then.
