### ISSUE TITLE
formatter should change f strings using single quotes with nested double quotes to use double quotes when `target-version` is `py312`

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#13237]
on older python versions, the following code is a syntax error:
```py
f"{""}"
```
which is why the formatter does not convert the following f string to use double quotes:

```py
f'{""}'
```

but on python 3.12, it's allowed, so the formatter should always convert them to double quotes. [playground](https://play.ruff.rs/5435f8ea-ad9b-4d5f-8900-7c40c6b7a3fa)

**Comment by dhruvmanila** [comment]
This is available under preview style (https://github.com/astral-sh/ruff/discussions/9785) although it seems like the formatter still doesn't change the outer quote. For example, if the quotes are inverted (`f"{''}"`), the formatter changes the inner quote to use double quotes. This case (`f'{""}'`) seems like a bug.
