### ISSUE TITLE
Add UP rule: rewrite TypeVar defaults for Generator / AsyncGenerator

### ISSUE THREAD

**Issue by hugovk** [astral-sh/ruff#13269]
There's a new check in pyupgrade to rewrite using PEP 696 TypeVar defaults:

* https://github.com/asottile/pyupgrade#pep-696-typevar-defaults
* https://github.com/asottile/pyupgrade/pull/948

```diff
from collections.abc import Generator, AsyncGenerator

-def f() -> Generator[int, None, None]:
+def f() -> Generator[int]:
     yield 1
```
```diff
from collections.abc import Generator, AsyncGenerator

-async def f() -> AsyncGenerator[int, None]:
+async def f() -> AsyncGenerator[int]:
     yield 1
```

See the https://github.com/asottile/pyupgrade/pull/948/files for some variations.

**Comment by iamlucasvieira** [comment]
May I work on this one?

**Comment by iamlucasvieira** [comment]
I think we already have this rule implemented: UP043
