### ISSUE TITLE
`PYI013` emitted on empty class with documentation

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [astral-sh/ruff#13277]
When an otherwise empty class contains documentation, ruff identifies it as non-empty and emits PYI013:
```console
$ cat empty.py
class ArrayArrayCodec:
    ...
$ 
$ ruff check --isolated --select=PYI013 empty.py 
All checks passed!
$ 
$ cat nonempty.py
class ArrayArrayCodec:
    """Base class."""
    ...
$ 
$ ruff check --isolated --select=PYI013 nonempty.py 
file.py:3:5: PYI013 [*] Non-empty class body must not contain `...`
  |
1 | class ArrayArrayCodec:
2 |     """Base class."""
3 |     ...
  |     ^^^ PYI013
  |
  = help: Remove unnecessary `...`

Found 1 error.
[*] 1 fixable with the `--fix` option.
$ 
```

* List of keywords you searched for before creating this issue. Write them down here so that others can find this issue more easily and help provide feedback.
  "PYI013"
* A minimal code snippet that reproduces the bug.
  ```python
  class ArrayArrayCodec:
  """Base class."""
      ...
  ```
* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.
   `ruff check --isolated --select=PYI013 nonempty.py`
* The current Ruff settings (any relevant sections from your `pyproject.toml`).
  None
* The current Ruff version (`ruff --version`).
  ```ruff 0.6.4```

**Comment by AlexWaygood** [comment]
Hi, thanks for the issue! This behaviour looks correct to me, however. The ellipsis in your class body is redundant; your class could be written more simply as:

```py
class ArrayArrayCodec:
   """Base class."""
```

**Comment by DimitriPapadopoulos** [comment]
It's true that the Python interpreter. accepts the docstring as actual class content and `...` is therefore not needed. I guess I'll have to disable that rule as maintainers prefer seem to prefer explicit `...` even with a docstring.
