### ISSUE TITLE
Ruff format attempts to format git related files

### ISSUE THREAD

**Issue by naquiroz** [astral-sh/ruff#13272]
Keywords searched: `git`

When creating a branch with a name that ends in `.py`, ruff attempts so format it.

![CleanShot 2024-09-06 at 15 58 11](https://github.com/user-attachments/assets/c9b7b28d-d003-4230-9a4a-86a9ae6d6c13)

## Steps to reproduce

1. Create a branch in git with a name like `my-file.py`
2. Run the ruff formatter.
3. See how it tries to format a git file.

**Comment by MichaReiser** [comment]
Hehe that's funny. Would you mind sharing your configuration? I wonder if [respect-gitignore](https://docs.astral.sh/ruff/settings/) is on or off

**Comment by naquiroz** [comment]
How do I get my configuration?

**Comment by MichaReiser** [comment]
Do you have a `pyproject.toml` with a `[tool.ruff]` section or a `ruff.toml` in your project? See [How to configure Ruff](https://docs.astral.sh/ruff/configuration/)

**Comment by Avasam** [comment]
Oh yeah I remember this happenning to me once, but forgot to report. I don't have `respect-gitignore` set in any of my projects.

**Comment by MichaReiser** [comment]
I verified this locally and I can only reproduce this behavior when overriding the [`exclude`](https://docs.astral.sh/ruff/settings/#exclude) setting. 

Ruff ignores the `.gitignore` directory by default because it is part of the default `exclude` list. You may want to consider using `extend-exclude` if you want to exclude some directories in addition to the default once.

**Comment by naquiroz** [comment]
I'm sharing my `pyproject.toml`

I'll also take a link into the `extend-exclude`

**Comment by MichaReiser** [comment]
@naquiroz  I think you want to use `tool.ruff.extend-include` instead of `tool.ruff.exclude`. I think that should fix the problem for you.

**Comment by Avasam** [comment]
I've just replicated this with a `ruff.toml` that doesn't have an `exclude`:
Link to the problematic branch name as an example: https://github.com/Avasam/pywin32/blob/Random-testFileTimes-test-failure-in-test_win32file.py/ruff.toml
Permalink for when I inevitably delete that branch from the remote one day: https://github.com/Avasam/pywin32/blob/41efba18976ed93966591109bcc46aa937f1ed8b/ruff.toml
