### ISSUE TITLE
[FR] Add config option to emit pre-0.5 condensed output of `ruff check`

### ISSUE THREAD

**Issue by sterliakov** [astral-sh/ruff#13311]
In 0.5.0 the format of ruff's output became much more verbose. It may be useful in some cases, but I use ruff mostly in pre-commit and will navigate to all these files anyway. I don't want to see the big code snippet and would rather see just code, file+lineno and short description.

I do not propose reverting the design change, I only would like to have e.g. `--condensed` flag available.

This will also make adding `ruff` to new projects more trivial: I finally went to ask for this feature after trying to survive scrolling through 204 diagnostics.

Compare the following (keeping in mind that I see 200 such messages).

```
rest_framework_simplejwt/views.py:42:47: ARG002 Unused method argument: `kwargs`
   |
40 |         )
41 | 
42 |     def post(self, request: Request, *args, **kwargs) -> Response:
   |                                               ^^^^^^ ARG002
43 |         serializer = self.get_serializer(data=request.data)
   |
```

vs

```
rest_framework_simplejwt/views.py:42:47: ARG002 Unused method argument: `kwargs`
``` 

Keywords: verbose, CLI, output, silent, condensed

I'm running `ruff check some_project/ --select ALL --isolated` (for example).

Ad a workaround, I pretend to be a TTY and `grep` a bit, obtaining the desired output:

```bash
unbuffer -p ruff check some_project/ --select ALL | grep -v -P '^(\e\[1;38| |\s*$)'
```

Ruff 0.6.4 (starting from 0.5.0).

**Comment by MichaReiser** [comment]
Hi @sterliakov 

That makes sense to me. Does `ruff check --output-format=concise` work for you ([docs](https://docs.astral.sh/ruff/settings/#output-format))?

**Comment by sterliakov** [comment]
Sorry, I swear I looked through `ruff help format` several times... Works
for me, thanks!

Aside, can I ask `ruff` to avoid checking whether its stdout is attached to
a TTY and keep colorizing the output (e.g. `--color=always` or
`--force-color`)? Would be nice to `tail`/`head`/`grep` its output without
the `unbuffer` trick. This is something I expect from any unix CLI tool, to
be honest - perhaps I'm also just unable to find that in the docs?

**Comment by MichaReiser** [comment]
There's no CLI flag for this but you can set an environment variable. The documentation for it is a bit hard to find but see Ruff's [FAQ](https://docs.astral.sh/ruff/faq/#how-can-i-disableforce-ruffs-color-output)

**Comment by sterliakov** [comment]
Amazing, thanks, that's it!
