### ISSUE TITLE
Formatter: Different behavior of `line-length` between ruff and black for docstrings and comments

### ISSUE THREAD

**Issue by kevalmorabia97** [astral-sh/ruff#13339]
I am using `ruff==0.6.4`. I have been using Ruff linter for quite some time alongside black formatter. Now I would like to use Ruff Formatter instead of black but my issue is with the handling of `line-length` between Ruff and Black. With Black, line length is only enforced for code blocks and not for docstrings or comments. But Ruff's `tool.ruff.line-length` is a universal length restriction and causes `E501 Line too long` for hundreds of lines making it extremely difficult to manually fix them all. Plus I would prefer to leave those as is as they are just comments or docstrings and I don't want the linter to complain for them. 

Is there a way to configure length restriction to ignore docstrings and comments? Or perhaps allow a different length for linter and formatter?

**Comment by MichaReiser** [comment]
Hy @kevalmorabia97 

My recommendation is to disable `E501` and rather formatting related lint runes when using `ruff format`by adding them to `ignore = ["E501"]`. Annoter common setup is to keep `E501` enabled and increase the `[max-line-length`](https://docs.astral.sh/ruff/settings/#lint_pycodestyle_max-line-length) and [`max-doc-length`](https://docs.astral.sh/ruff/settings/#lint_pycodestyle_max-doc-length) settings to find very long lines that the formatter wasn't able to break lines into shorter lines automatically.

**Comment by kevalmorabia97** [comment]
Thanks @MichaReiser `[max-line-length]` was exactly what I needed!
