### ISSUE TITLE
FURB188 ignores the slice’s step

### ISSUE THREAD

**Issue by dscorbett** [astral-sh/ruff#13349]
[FURB188](https://docs.astral.sh/ruff/rules/slice-to-remove-prefix-or-suffix/) can apply to any slice regardless of the slice’s step. FURB188 should only apply if the step is omitted, `None`, `1`, or `True`.

```console
$ ruff --version
ruff 0.6.5
$ cat furb188.py
text = "!x!y!z"
if text.startswith("!"):
    text = text[1::2]
print(text)
$ python furb188.py
xyz
$ ruff check --isolated --preview --target-version py39 --select FURB188 furb188.py --fix
Found 1 error (1 fixed, 0 remaining).
$ python furb188.py
x!y!z
```

**Comment by dylwil3** [comment]
Thanks! I'm visiting family the next few days but I should be able to fix this early next week.
