### ISSUE TITLE
Bug: False format for list slicing with self.x as index

### ISSUE THREAD

**Issue by CareF** [astral-sh/ruff#13351]
```python
# file foo.py
a = list(range(5))
b = 2
print(a[1:b])


class Foo:
    def __init__(self):
        self.a = list(range(5))
        self.b = 2

    def bar(self):
        # The next line will be formatted to self.a[1 : self.b]
        print(self.a[1:self.b])
```

Running `ruff format tmp.py` will change the `self.a[1:self.b]` to `self.a[1 : self.b]` which is a conflict with `flake8: E203`. However the `a[1:b]` is not touched. No extra configs are needed.

```
$ ruff --version
ruff 0.6.5
```

**Comment by trag1c** [comment]
I believe this is intended behavior. It doesn't conflict with Ruff's `E203`, and is in line with Black's style: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
> PEP 8 [recommends](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements) to treat `:` in slices as a binary operator with the lowest priority, and to leave an equal amount of space on either side, except if a parameter is omitted (e.g. `ham[1 + 1 :]`). It recommends no spaces around `:` operators for “simple expressions” (`ham[lower:upper]`), and extra space for “complex expressions” (`ham[lower : upper + offset]`). Black treats anything more than variable names as “complex” (`ham[lower : upper + 1]`).

**Comment by CareF** [comment]
Thank you!
