### ISSUE TITLE
D400: bad autofix if the first line ends in a question mark

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#13365]
The autofix for D400 currently changes this:

```py
def should_frob() -> bool:
    """Should we frob the bar?"""
```

To this:

```py
def should_frob() -> bool:
    """Should we frob the bar?."""
```

Which seems pretty clearly worse! We probably just shouldn't offer an autofix if the first line ends in a question mark or exclamation mark?

List of keywords you searched for before creating this issue:
* D400
* `ends-in-period`

**Comment by yahayaohinoyi** [comment]
can i get assighned to this?

**Comment by yahayaohinoyi** [comment]
would send PR by EOD

**Comment by yahayaohinoyi** [comment]
https://github.com/astral-sh/ruff/pull/13399
