### ISSUE TITLE
`ruff format` check lines-after-imports options but not respect it

### ISSUE THREAD

**Issue by trim21** [astral-sh/ruff#13364]
I'm using `ruff 0.6.5 (8558126df 2024-09-13)` with config `tool.ruff.lint.isort.lines-after-imports = 2`

ruff format warns about `lines-after-imports` are not -1,1,2 but did't add 2 empty lines after last import

for example, not changes for this file:
```python
import io

with io.StringIO() as f:
    print("ok", file=f)
```

**Comment by MichaReiser** [comment]
The `lines-after-imports` setting is a `isort` setting and `isort` runs as part of `ruff check` and not `ruff format`. 

Can you try to run 

```shell
ruff check --fix --select I
```

It should add the two empty lines. We hope to integrate format into `ruff check` in the long-term and possibly move `isort` to `format` to reduce the confusion (see https://github.com/astral-sh/ruff/issues/8232)

**Comment by trim21** [comment]
> > ruff check --fix --select I
> 
> [@MichaReiser](https://github.com/MichaReiser) why it only works when I specify the `--select I` option?

It's an option of I rule
