### ISSUE TITLE
Monorepo support with root .ruff.toml

### ISSUE THREAD

**Issue by augustelalande** [astral-sh/ruff#13450]
I'm having an issue with rule inheritance in a monorepo with the following structure
```
root
├── .ruff.toml
└── packages
    ├── package1
    │   └── pyproject.toml
    └── package2
        └── pyproject.toml
```
if the package `pyproject.toml` specifies a ruff configuration (e.g. ignore ANN), then ruff will ignore the root `.ruff.toml` and use a default ruff configuration plus whatever is specified in the `pyproject.toml`. If the package doesn't have a ruff section in the `pyproject.toml` then it works as expected.

**Comment by augustelalande** [comment]
Also the reason I don't have a `pyproject.toml` at the root is that the monorepo is mixed language so I prefer to just have a tool configuration.

**Comment by MichaReiser** [comment]
Did you set the extend setting in the pyproject.toml? Ruff doesn't automatically extend from configurations in a parent directory. If you did, would you mind sharing an example ruff and pyproject.toml configuration?

**Comment by augustelalande** [comment]
Thanks. That works. I don't know why I thought it would inherit automatically.

**Comment by augustelalande** [comment]
Thanks. That works. I don't know why I thought it would inherit automatically.
