### ISSUE TITLE
0.6.7: `ruff --diff` does not generate quoted file name when file or directory contains spaces

### ISSUE THREAD

**Issue by kloczek** [astral-sh/ruff#13489]
In such cases instead generate
```parch
--- foo bar/bar.py
+++ foo bar/bar.py
```
Should be generated 
```parch
--- "foo bar/bar.py"
+++ "foo bar/bar.py"
```
Issue can be tested on `meson`  (https://github.com/mesonbuild/meson/) or `ipyparallel` (https://github.com/ipython/ipyparallel/) code

**Comment by zanieb** [comment]
Is this per a specification or something? Or just what you would prefer? e.g. `diff` does not do this

```
❯ echo "test" > "foo bar"
❯ echo "test2" > "foobar"
❯ diff foo\ bar foobar --unified=0
--- foo bar	2024-09-23 16:59:54
+++ foobar	2024-09-23 16:59:59
@@ -1 +1 @@
-test
+test2
```

**Comment by zanieb** [comment]
Not does `git`

```
❯ ga foo\ bar
❯ echo "test2" > "foo bar"
❯ gd
diff --git a/foo bar b/foo bar
index 9daeafb98..180cf8328 100644
--- a/foo bar   
+++ b/foo bar   
@@ -1 +1 @@
-test
+test2
```

**Comment by kloczek** [comment]
> Is this per a specification or something? Or just what you would prefer? e.g. `diff` does not do this

You did not use ruff to generate that patch.
**This issue is about patch generated by ruff.**

Please reopen this ticket.
I've proficed example githunb repo https://github.com/mesonbuild/meson/  on which i poossible to test this issue.
Please::
- clone https://github.com/mesonbuild/meson/
- generate "ruff --diff" and check what is in the **generated** output.

**Comment by kloczek** [comment]
> Nor does `git`

Reported issue has nothing to do with git.
It is about what generates  "ruff --diff".

**Comment by ntBre** [comment]
I think Zanie understood that the question was about ruff's behavior and was pointing out that this is how other tools that generate diffs (`git`, `diff`) also work. As such, it's not really a bug in ruff, it's a common diffing behavior across multiple tools.

Do you have a concrete use case that is being impacted by this, or is this a stylistic preference for what the output looks like?

**Comment by kloczek** [comment]
> I think Zanie understood that the question was about ruff's behavior and was pointing out that this is how other tools that generate diffs (git, diff) also work. As such, it's not really a bug in ruff, it's a common diffing behavior across multiple tools.

Yes those tools are buggy as well.
Space o tab after path is skipped as that part usually contains time stamp so to mark that space is not part of the time stamp path needs to quoted or spaces in that path needs to quoted using "\\". Tools like patch and git understands already those quotations.
**There is no any oper way to distinguish those two cases**. 
Patch generated without quoted paths or spaces cannot be used by patch and git -> Ergo: it is the bug.
