### ISSUE TITLE
Formatter ignores nested f-strings

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#13488]
`f'{    "\n".join([f"•{   k }" for k in [1,2,3]])}'`
My extra whitespace is not removed from this line.

**Comment by MichaReiser** [comment]
F-string formatting is a preview-only feature because we implemented it after the 2024 style guide was released.

Ruff removes the whitespace inside the expression when using `ruff.format.preview = true` ([playground](https://play.ruff.rs/87006684-d5eb-4a3e-a515-5919025445a7))

```python
f'{"\n".join([f"•{k}" for k in [1, 2, 3]])}'
```
