### ISSUE TITLE
Implement flake8-libfaketime

### ISSUE THREAD

**Issue by wwuck** [astral-sh/ruff#13496]
https://github.com/vikingco/flake8-libfaketime/

This blocks usages of `from libfaketime import fake_time`.  It can be useful in some unit/integration tests, but is unlikely to be wanted in regular non-test code.

This would be nice to have in ruff. I'm not sure if there are other similar imports that could be detected, maybe `freezegun`?

**Comment by MichaReiser** [comment]
> Is this covered by [docs.astral.sh/ruff/rules/banned-api](https://docs.astral.sh/ruff/rules/banned-api/)? I didn't notice that until after creating this issue.

If it's about flagging specific imports, than banned-api's is what you want.
