### ISSUE TITLE
Conda installation of Ruff not running on aarch64

### ISSUE THREAD

**Issue by bcaddy** [astral-sh/ruff#13506]
I'm trying to run Ruff on an NVIDIA Grace (i.e. ARM Neoverse v2) CPU and getting the following error:

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
Aborted
```

This appears to be a reappearance of the page size issue noted in #3791 and I'm not sure how to fix it. I've installed Ruff with Conda from the Conda-forge channel and I'm on the latest version. Any suggestions?

**Comment by bcaddy** [comment]
The page size is 64k and I'm just installing it with `conda install -c conda-forge ruff`.

I tried with the exact same version of Ruff installed via `pip` and it works just fine, so the issue is not actually with Ruff but with the version built/installed with Conda; I've updated the title accordingly.

**Comment by zanieb** [comment]
Related:

- https://github.com/astral-sh/ruff/issues/3791
- https://github.com/astral-sh/ruff/issues/10073

**Comment by zanieb** [comment]
Presumably we need to set this variable over in the conda-forge builds?

**Comment by MichaReiser** [comment]
Yes, I can take a look. @zanieb do you know who has access to our conda forge recipe and how it can be changed?

For reference:

https://github.com/astral-sh/ruff/blob/be1d5e33680c3e2e71b452ad1ed651dcc6f37f55/.github/workflows/build-binaries.yml#L271-L287

https://github.com/astral-sh/ruff/blob/be1d5e33680c3e2e71b452ad1ed651dcc6f37f55/.github/workflows/build-binaries.yml#L412-L416

**Comment by zanieb** [comment]
Anyone can open a pull request https://github.com/conda-forge/ruff-feedstock

**Comment by MichaReiser** [comment]
@bcaddy would you be interested in PRing a fix? It's on my todo list but it probably takes me a while before I get to and I have no prior conda forge knowledge

**Comment by bcaddy** [comment]
I also have no experience with conda forge and don't see an obvious place to change the jemalloc setting so I opened an issue on the ruff feedstock, hopefully they can help out. 

https://github.com/conda-forge/ruff-feedstock/issues/222
