### ISSUE TITLE
`INP001` doesn't trigger if there are no Python files in the immediate directory

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#13519]
If you have a directory within your project that's missing an `__init__.py` file, but it only contains Python modules (directories with `__init__.py` files), and no Python _files_, we won't catch it in the [implicit namespace package](https://docs.astral.sh/ruff/rules/implicit-namespace-package/) rule.

**Comment by charliermarsh** [comment]
This is a pretty substantial limitation. It looks non-trivial to fix though, since we rely on `package` being `None` for this detection.

**Comment by MichaReiser** [comment]
Hmm, I think there's a similar issue somewhere

**Comment by MichaReiser** [comment]
Here, https://github.com/astral-sh/ruff/issues/13225

Folders without an `__init__.py` are considered namespace packages which Ruff doesn't support at all.

**Comment by charliermarsh** [comment]
We do support them but you have to mark them explicitly.

**Comment by charliermarsh** [comment]
(The whole point of the rule is to find implicit namespace packages though.)
