### ISSUE TITLE
red-knot thinks that the type of `1 / 2` is `Literal[0]`

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#13570]
This is not accurate

**Comment by AlexWaygood** [comment]
the issue is this logic here: https://github.com/astral-sh/ruff/blob/5f4b2823277df38fc222e9d8096b805f9cc34c74/crates/red_knot_python_semantic/src/types/infer.rs#L2248-L2251

**Comment by zanieb** [comment]
:)
