### ISSUE TITLE
Question: How to disable code block help when failing `check`

### ISSUE THREAD

**Issue by tomhamiltonstubber** [astral-sh/ruff#13584]
Hi folks,

Quick question. Recently I've started getting the helpful code block displayed when `ruff check` fails and I'm not sure why. Perhaps my env was very out of date but I downgraded to version 0.5.0 and I've still got it, plus my other devs tell me they've always had it displayed so now I think I'm going mad.

Anyway, can I disable it? I like just the one line version. I've checked [here](https://docs.astral.sh/ruff/settings/#) but can't seem to see anything.

Example:
```python
patch.py:534:9: F811 Redefinition of unused `period` from line 526
    |
533 |     @cached_property
534 |     def period(self) -> int:
    |         ^^^^^^ F811
535 |         return int(self.charge_key.split('_')[-2])
    |
    = help: Remove definition: `period`
```

Preferred output:

```py
patch.py:534:9: F811 Redefinition of unused `period` from line 526
```

**Comment by dhruvmanila** [comment]
There's also `RUFF_OUTPUT_FORMAT` environment variable that can be used. I'll mark this as resolved, feel free to ask any other questions that you might have :)
