### ISSUE TITLE
In-place formatting by default considered harmful

### ISSUE THREAD

**Issue by mainini** [astral-sh/ruff#13626]
Hi!

I've searched the issues for various keywords like "ruff format", "in-place", "write by default" etc.

I do consider the default behavior of "ruff format" to be harmful: without further notice, it proceeds to recursively format files (*.py, *.pyi, *.ipynb and some toml files, as I could observe). I do have the standard configuration without any modifications.

As a new user of ruff, I wanted to display the help for the format command by just typing "ruff format", which accidentally formatted several thousand files. To me, this was completely  unexpected behavior and opposed to that what "traditional" tools do: either nothing or write the conducted changes to stdout instead of modifying in-place (think e.g. "sed -i" if you really want to change things...).

I did briefly check "ruff analyze" and "ruff check", however was unable to reproduce / draw conclusions. I would also consider this behavior harmful for other subcommands.

I would reconsider this choice and have all ruff commands not perform modifications by default (or at least ask before). That could also be made configurable.

Thanks!

**Comment by zanieb** [comment]
Sorry this surprised you, but it's pretty standard for formatting commands (e.g., `cargo fmt`, `black`, etc.) to write in-place. I don't think we will change this behavior.

You can use `ruff format --diff`

**Comment by zanieb** [comment]
Fair point. I think the main goal here was to match `black`'s behavior though. And, you can't really develop a Rust project without a `cargo.toml` but it's very common for people to develop a Python project without a `pyproject.toml`.

**Comment by MichaReiser** [comment]
I don't think there's a standard across formatters. `prettier` doesn't write the changes by default but `rustfmt` (the command that `cargo fmt` runs under the hood), and black do. I see good reasons for either approach:

* Require explicit `--write` argument: Formatting is a destructive operation that should require explicit opt in
* Implicit `--write`: The default use case is to write the changes back. Requiring an extra argument is extra verbose and surprising in the opposite way. I'm always surprised when I find prettier hitting me with a wall of text when I forgot the `--write` option

I find either default valid (and both are harmful in their own way), so I don't think it's justified to disrupt all existing users by changing the default (where it's unclear which default is better).
