### ISSUE TITLE
[flake8-todos] TD rules trigger on words beginning with todo

### ISSUE THREAD

**Issue by autinerd** [astral-sh/ruff#13638]
Hi,

currently the TD rules trigger on words beginning with "todo", like `# Todoist API`

I think it should only trigger on the whole word "todo"

Thanks!

**Comment by zanieb** [comment]
What's the upstream plugin do?

**Comment by autinerd** [comment]
I looked in the code of that, and yeah, it does the same as in using the regex `#\s*({tags})` and not looking if it is part of a word.
