### ISSUE TITLE
`allowed-unused-imports` has incorrect documentation

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#13668]
* In the [docs](https://docs.astral.sh/ruff/settings/#lint_allowed-unused-imports), it's part of the `lint` section rather than `lint.pyflakes`
* In those same docs, "thought" is used in place of "though"
* The TOML schema doesn't recognize the setting at any of the three possible levels.
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/b5385226-f74d-45d0-873b-4658087af557">

**Comment by zanieb** [comment]
https://github.com/SchemaStore/schemastore/pull/4131

**Comment by tylerlaprade** [comment]
Thanks! Is there precedent for allowing other settings at two different levels? It seems a bit confusing.

**Comment by zanieb** [comment]
I'm not sure honestly. It does seem confusing if it's not necessary for some reason. cc @charliermarsh who reviewed that contribution.

**Comment by charliermarsh** [comment]
It should only be under lint.pyflakes.

**Comment by tylerlaprade** [comment]
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/ab1afc1f-40fd-435e-98f4-96999db48c0d" />
`lint` is still not recognized for me

**Comment by MichaReiser** [comment]
@tylerlaprade I'm unable to reproduce this. I created a `.ruff.toml` file and opened it in VS Code with even better toml installed. It provides me intelli sense and auto suggestions. Any chance you manually selected an old schema in Better toml for `ruff.toml` files?

**Comment by tylerlaprade** [comment]
@MichaReiser, hmm, these are the three options it gives me. I don't know how to distinguish between them. All three seem to have the same problem, though.

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/06424685-b537-4771-834e-ffc90f57607e" />

**Comment by MichaReiser** [comment]
What's the exact error message from the schema? Can you try commenting out all settings and then, one by one (or doing a binary search where you comment in 50%) comment in the sections? Do you see the same in a `pyproject.toml`?

**Comment by tylerlaprade** [comment]
Oh! Good idea - it was hard to tell which line was problematic since _all_ occurrences of `lint` were squiggled, but the problem seems to come solely from `extend-safe-fixes = ["ANN", "C4", "EM", "RET", "SIM", "TCH", "UP"]`. Was that setting deprecated?

**Comment by MichaReiser** [comment]
The setting wasn't deprecated but `TCH` was renamed to `TC` ([blog](https://astral.sh/blog/ruff-v0.8.0#new-error-codes-for-flake8-type-checking-rules)) and this seems to be causing the issue. 

I see you just solved it. Nice. Yeah, our error reporting for the lint section is unfortunate because we use some functionality to avoid repeating all options globally and under `lint` and it doesn't seem to be that well supported
