### ISSUE TITLE
[red-knot] understand the `Literal[]` special form in annotations

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#13672]

**Comment by MichaReiser** [comment]
This is to teach red knot that `mode` is a union over `w` or `r` for `def open(mode: Literal["w", "r"])`

**Comment by carljm** [comment]
> This is to teach red knot that `mode` is a union over `w` or `r` for `def open(mode: Literal["w", "r"])`

In order to fully achieve this, we also have to implement https://github.com/astral-sh/ruff/issues/13693. But that issue isn't a blocker for this one. If we implement this issue such that we understand this case:
```
from typing import Literal

x: Literal[10] = 10

def f():
    reveal_type(x)  # revealed: Literal[10]
```

then the parameter-annotation case @MichaReiser described will fall out naturally once we correctly infer parameter annotation types in general.

**Comment by Glyphack** [comment]
I'd be happy to work on this. I also need this to be able to complete https://github.com/astral-sh/ruff/pull/13827.

**Comment by MichaReiser** [comment]
I'll check in with @sharkdp because he considered working on this. I'll keep you posted.

**Comment by sharkdp** [comment]
@Glyphack your contribution would be very welcome!
