### ISSUE TITLE
Check whether {filename} conflicts with standard library

### ISSUE THREAD

**Issue by Riezebos** [astral-sh/ruff#13676]
I think this would be a useful rule, I found a few other rules that use `{filename}` (e.g. INP001) but as far as I can tell this one doesn't exist.

The rule would check whether `{filename}` is the same as any module in the standard library. 

Creating a file like that can cause problems, e.g.:
```
   # bisect.py
   ...

   # main.py
   import random

with:

   Traceback (most recent call last):
     File ".../foo.py", line 1, in <module>
       import random
     File "/usr/lib/python3.12/random.py", line 62, in <module>
       from bisect import bisect as _bisect
   ImportError: cannot import name 'bisect' from 'bisect'
```

This rule would help prevent these types of errors.

**Comment by ember91** [comment]
A bit unrelated but Python 3.13 will include an improved error message of this: https://docs.python.org/3.13/whatsnew/3.13.html#improved-error-messages

**Comment by autinerd** [comment]
There is A005 https://docs.astral.sh/ruff/rules/builtin-module-shadowing/ (which is currently in preview), does this rule show an error?

**Comment by Riezebos** [comment]
Yes, that's exactly what I was looking for! Sorry for not finding it before.
