### ISSUE TITLE
Server panics when code contains CJK characters

### ISSUE THREAD

**Issue by HusuSama** [astral-sh/ruff#13674]
When I use Click, errors occur. I'm not sure if it's because of my Chinese comments or the decorators.

log:
![图片](https://github.com/user-attachments/assets/92167a53-08c6-4ee0-96d6-e43c2bbf6b91)

code:
![图片](https://github.com/user-attachments/assets/14b691ad-5448-4a70-abe3-06f9f2470e29)

**Comment by dhruvmanila** [comment]
@HusuSama Sorry, somehow I missed this. Can you provide the code content as text instead of an image? I can copy paste that and try to reproduce it. Additionally, can you provide the Ruff config if it's being used here (both server settings and Ruff configuration)?

**Comment by HusuSama** [comment]
Thank you for noticing the issue I raised. I haven't made any additional configurations for Ruff, and I'm using the AstroNvim configuration. Here is the configuration content: [AstroNvim's Ruff Configuration](https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/python-ruff).

I can't fully pinpoint this issue; it seems to be random. It tends to occur more frequently when I add Chinese comments at the top, and the usage is very unstable. I'm also not quite sure if it's an issue with my Neovim configuration. By the way, I use `Tab` for code completion.

my code:

```python
"""
测试comment
一些测试内容
"""

import click


@click.group()
def interface():
    pass


@interface.command()
def test(file):
    click.echo(file)


if __name__ == "__main__":
    interface()

```

**Comment by dhruvmanila** [comment]
Thanks! I've a couple of questions:
1. Can you describe the scenario which produces the panic? It could be like something you clicked, requested the server for something (like hover request), while typing etc.
2. What's the Ruff version that is being used here?
3. Can you provide debug logs for the server? I'm not sure how to set the config for AstroNvim but for `lsp-config` you can refer to the end of [this section in the docs](https://docs.astral.sh/ruff/editors/setup/#neovim).

**Comment by HusuSama** [comment]
1. I suspect that the issue might be related to my code completion settings. When I use TAB to automatically select the first code suggestion, this error occurs. However, if I first move the cursor and then use TAB to select, the error does not appear. 
![图片](https://github.com/user-attachments/assets/50837288-88fe-40cb-8a1b-4a0c528ded5f)
![图片](https://github.com/user-attachments/assets/959a8f06-a136-404e-a2e6-6e52c7042ae3)

2. ruff version
![图片](https://github.com/user-attachments/assets/9692ce28-ab14-4e88-a9dd-56084463cdd7)

3. I only have the LSP error log
```log
[START][2024-10-29 09:10:40] LSP logging initiated
[ERROR][2024-10-29 09:10:40] ...lsp/handlers.lua:623    "Notification workspace/didChangeConfiguration defines parameters by name but received parameters by position"
[ERROR][2024-10-29 09:10:40] ...lsp/handlers.lua:623    "Notification workspace/didChangeConfiguration defines 1 params but received 0 arguments"
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        'panicked at crates/ruff_server/src/edit/range.rs:68:71:\nbyte index 96 is out of bounds of `"""\n测试comment\n一些测试内容\n"""\nimport click\n\n@click.group()\ndef interface():\n    pas\n`\n'
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "   "
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "0: ruff_server::server::Server::run::{{closure}}\n   1: std::panicking::rust_panic_with_hook\n   2: std::panicking::begin_panic_handler::{{closure}}\n   3: std::sys::backtrace::__rust_end_short_backtrace\n   4: rust_begin_unwind\n   5: core::panicking::panic_fmt\n   6: core"
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "::str::slice_error_fail_rt\n   7: core::str::slice_error_fail\n   8: <lsp_types::Range as ruff_server::edit::range::RangeExt>::to_text_range\n   9: ruff_server::edit::text_document::TextDocument::apply_changes\n  10: ruff_server::session::index::Index::update_text_document\n  11: <ruff_server::server::api::notifications::did_change::DidChange as ruff_server::server::api::traits::SyncNotificationHandler>::run\n  12: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  13: std::sys::backtrace::__rust_begin_short_backtrace\n  14: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  15: std::sys::pal::unix::thread::Thread::new::thread_start\n  16: <unknown>\n  17: <unknown>\n\n"
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:\ncalled `Result::unwrap()` on an `Err` value: Any { .. }\n"
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "   0: "
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "ruff_server::server::Server::run::{{closure}}\n   1: std::panicking::rust_panic_with_hook\n   2: std::panicking::begin_panic_handler::{{closure}}\n   3: std::sys::backtrace::__rust_end_short_backtrace\n   4: rust_begin_unwind\n   5: core::panicking::panic_fmt\n   6: core::result::unwrap_failed\n   7: ruff_server::server::Server::run\n "
[ERROR][2024-10-29 09:11:05] .../vim/lsp/rpc.lua:770    "rpc"   "/home/husu/.local/share/nvim/mason/bin/ruff"   "stderr"        "  8: ruff::run\n   9: ruff::main\n  10: std::sys::backtrace::__rust_begin_short_backtrace\n  11: std::rt::lang_start::{{closure}}\n  12: std::rt::lang_start_internal\n  13: main\n  14: <unknown>\n  15: __libc_start_main\n  16: <unknown>\n\n"
```

**Comment by HusuSama** [comment]
Do I need to make the following settings?
![图片](https://github.com/user-attachments/assets/24ac2961-5a05-4375-810d-7ca89bc3fb3a)

**Comment by MichaReiser** [comment]
Thanks for the additional logs. 

Looking at the stack trace, I suspect that the panic happens here because it's the only place where we slice into the string in `to_text_range`:

https://github.com/astral-sh/ruff/blob/b0731ef9cbbfcad82144c2fc33dcbad1cd99de7b/crates/ruff_server/src/edit/range.rs#L64-L70

It would suggest that the line-ranges are incorrect but it's unclear to me how it comes to this. The LSP messages would be helpful for debugging. @dhruvmanila could you share the instructions on how to get the LSP messages in neovim?

**Comment by dhruvmanila** [comment]
> could you share the instructions on how to get the LSP messages in neovim?

Yeah, you'd need to add the following lines in your Neovim config and then restart Neovim:
```lua
vim.lsp.set_log_level("debug")
-- This is mainly to make sure the messages are logged in a pretty way
require('vim.lsp.log').set_format_func(vim.inspect)
```
This will then log the request - response messages between the server and the client.

**Comment by MichaReiser** [comment]
> I think having detailed logs involving the request - response messages would be very useful.

What positional encoding does your neovim setup use? Is it UTF8 or UTF16?

**Comment by HusuSama** [comment]
[error.webm](https://github.com/user-attachments/assets/23c54370-04d9-46b9-825e-ec2939824174)

This issue seems to occur randomly, and I'm not quite sure if it's related to my nvim configuration or the system.

os:
![图片](https://github.com/user-attachments/assets/1bf7600b-fff4-4cfd-b9b0-a9c5b878a88a)

Most of the time when problems occur, I automatically select the first code suggestion rather than manually choosing the first one.

`nvim-cmp` config:

![图片](https://github.com/user-attachments/assets/68b45c7f-a616-4a5f-af0d-be5987b50213)

@dhruvmanila

**Comment by dhruvmanila** [comment]
> What positional encoding does your neovim setup use? Is it UTF8 or UTF16?

UTF-16. I think Neovim's LSP client only support UTF-16 as per their client capabilities.

**Comment by dhruvmanila** [comment]
@HusuSama Can you provide detailed logs? I've mentioned the change in your config to enable debug logs at https://github.com/astral-sh/ruff/issues/13674#issuecomment-2443456417.

**Comment by HusuSama** [comment]
This data might be quite lengthy.
[lsp.log](https://github.com/user-attachments/files/17566722/lsp.log)

**Comment by MichaReiser** [comment]
Thanks. The logs are very useful. I've been able to reproduce the bug with the following unit test:

```rust
mod tests {
    use crate::edit::DocumentVersion;
    use crate::{PositionEncoding, TextDocument};
    use lsp_types::{Position, TextDocumentContentChangeEvent};

    #[test]
    fn regression() {
        let mut document = TextDocument::new(
            r#""""
测试comment
一些测试内容
"""
import click


@click.group()
def interface():
    pas
"#
            .to_string(),
            0,
        );

        document.apply_changes(
            vec![
                TextDocumentContentChangeEvent {
                    range: Some(lsp_types::Range::new(
                        Position::new(9, 7),
                        Position::new(9, 7),
                    )),
                    range_length: Some(0),
                    text: "s".to_string(),
                },
                TextDocumentContentChangeEvent {
                    range: Some(lsp_types::Range::new(
                        Position::new(9, 7),
                        Position::new(9, 8),
                    )),
                    range_length: Some(1),
                    text: "".to_string(),
                },
                TextDocumentContentChangeEvent {
                    range: Some(lsp_types::Range::new(
                        Position::new(9, 7),
                        Position::new(9, 7),
                    )),
                    range_length: Some(0),
                    text: "s".to_string(),
                },
            ],
            1,
            PositionEncoding::UTF16,
        );

        dbg!(document);
    }
}
```

**Comment by HusuSama** [comment]
I'm very happy to be able to help you, and I look forward to hearing about the repair as soon as possible. 😄
