### ISSUE TITLE
Incorrect autofix for `PYI030`

### ISSUE THREAD

**Issue by yut23** [astral-sh/ruff#13685]
Running Ruff 0.6.9 as `ruff check --isolated --select PYI030 --fix test.py` deletes any subscripted types in a union with the offending Literals:
```python
from typing import IO, Literal

InlineOption = Literal["a"] | Literal["b"] | IO[str]
```
becomes
```python
from typing import IO, Literal

InlineOption = Literal["a", "b"]
```

Glancing through the code, it looks like this `if` block is just missing `else { other_exprs.push(expr); }`: https://github.com/astral-sh/ruff/blob/93eff7f1744cc428d615d5f8a3cb9f75b1768f42/crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_literal_union.rs#L66-L83

**Comment by diceroll123** [comment]
Good catch, that was exactly the fix! 😄
