### ISSUE TITLE
[red-knot] Infer subscript expression types

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#13689]
Limited support for inferring subscript expressions, e.g when the value is a tuple, or string.

```python
def test(a: str):
	c = a[0]
```

**Comment by MichaReiser** [comment]
@carljm String and tuple support has already been implemented in https://github.com/astral-sh/ruff/pull/13562. Do you have something else in mind that goes beyond what's covered in that PR?

**Comment by AlexWaygood** [comment]
Following #13562, #13579 and #13667, I think the only thing we don't support with regard to subscript expressions is where a class does not define `__class_getitem__` but its metaclass defines `__getitem__`. But we don't really support anything regarding metaclasses yet.

**Comment by AlexWaygood** [comment]
Oh, it looks like we might not support slices for string-literal and tuple types yet? `x[1:3]` should be inferred as `tuple[str, str]` if x has type `tuple[int, str, str, int]`. `y[1:3]` should be inferred as `Literal["aa"]` if y has type `Literal["baab"]`.

**Comment by AlexWaygood** [comment]
We could probably also add special handling for subscript expressions where BytesLiteral types are on the l.h.s.

**Comment by sharkdp** [comment]
> Oh, it looks like we might not support slices for string-literal and tuple types yet? `x[1:3]` should be inferred as `tuple[str, str]` if x has type `tuple[int, str, str, int]`. `y[1:3]` should be inferred as `Literal["aa"]` if y has type `Literal["baab"]`.

This is now supported via #13917 

> We could probably also add special handling for subscript expressions where BytesLiteral types are on the l.h.s. and IntLiteral or BooleanLiteral types are on the r.h.s.

This is now supported via #13901

> the only thing we don't support with regard to type inference of subscript expressions is where a class does not define `__class_getitem__` but its metaclass defines `__getitem__`. But we don't really support anything regarding metaclasses yet.

This is not yet supported. Do we want to close the ticket and come back to this when we tackle metaclasses, or keep it open until then?

**Comment by AlexWaygood** [comment]
No strong opinion. When we add support for metaclasses, we'll have to audit lots of our type inference to account for the fact that any class must be considered an instance of its metaclass. So perhaps this could be closed; but it also doesn't hurt to keep it open so that we remember to address this last point.

**Comment by sharkdp** [comment]
> When we add support for metaclasses, we'll have to audit lots of our type inference to account for the fact that any class must be considered an instance of its metaclass

I think this is a good enough reason to close this.
