### ISSUE TITLE
Direct link when searching for a short code

### ISSUE THREAD

**Issue by opk12** [astral-sh/ruff#13684]
When I type a short code in the search bar on the website (https://docs.astral.sh/ruff), for example `ruf005`, the search suggestion is a link to the list of warnings. When I type a long code, for example `collection-literal-concatenation`, the search suggestion is a direct link to the warning's article. Could the short code case be changed?

**Comment by MichaReiser** [comment]
Hmm, that's unfortunate. We would have to look into our Algolia search configuration to see how it index pages and either change the Algolia configuration or the structure of the rule's page. I don't think I've access to Algolia (@charliermarsh )

**Comment by charliermarsh** [comment]
I think we'd need some sort of support in material-for-mkdocs, e.g., via https://squidfunk.github.io/mkdocs-material/plugins/search/.

**Comment by squidfunk** [comment]
Author of Material for MkDocs here – results should drastically improve once we release the new search, which is currently blocked by a bigger refactor we're working on in the background, as mentioned in [our latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/). Once we got a first version of that ready, we'll reach out to you for giving it a try ☺️ We estimate that this should be the case by the beginning of next year.

**Comment by MichaReiser** [comment]
Wow thanks @squidfunk for the details! Adding the tags should be a very straightforward change and looking forward to the new search engine

**Comment by hreeder** [comment]
I've pushed a draft PR that adds these tags to the function used to generate the page metadata - I'm going to do a bit of tidying up of my work but wanted to get it opened for visibility.

**Comment by dhruvmanila** [comment]
The PR implementing this (#14040) has been merged and has been deployed with the release of `0.7.2`.

<img width="1728" alt="Screenshot 2024-11-04 at 9 19 22 AM" src="https://github.com/user-attachments/assets/46f6ca4a-7274-4df8-b442-fa173da31794">
