### ISSUE TITLE
Rule idea: pass regex flags by keyword

### ISSUE THREAD

**Issue by xmo-odoo** [astral-sh/ruff#13702]
In my experiece this is a relatively common issue for re.sub / re.subn: they take both a `count` and a `flags` parameter, and `count` is first. So

    re.sub(pattern, repl, text, re.MULTILINE)

will not apply `re.MULTILINE` but will limit the number of matches to 8. This typechecks because both parameters are typed as `int` and `re.RegexFlag` is an `IntFlag`. It can also happen with `re.split` (where the first parameter after the text is `maxsplit`) though I've less experience with that one.

Strictly speaking it's not needed for the rest (compile, search, match, iterfind, ...) as `flags` is their only integer parameter. I don't think it would *hurt* too keep things uniform but it can go either way.

Alternatively: more specifically flag passing an `re` flag as count or maxsplit, but I'm not sure that's possible, easier, or more useful.

**Comment by Skylion007** [comment]
Already implemented by [FURB167)](https://docs.astral.sh/ruff/rules/regex-flag-alias/#regex-flag-alias-furb167)

**Comment by AlexWaygood** [comment]
Hi, thanks for the issue! Does https://docs.astral.sh/ruff/rules/re-sub-positional-args/ already catch this error?

**Comment by AlexWaygood** [comment]
No worries! Glad we could help :-)
