### ISSUE TITLE
"Cleanup" markdown test names

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#13768]
I don't know if rstest allows to do that but the generated test names are hard to read and the enumerating of the tests also leads to instable identifiers across runs (changing test names can be very annoying when bisecting a test failures). 

![image](https://github.com/user-attachments/assets/d3d1a557-9755-4b19-92af-9629d2240eb1)

It would be nice if we could:

* remove the `path` prefix
* remove the index
* remove the `resources_md` prefix
* remove the `md` postfix

Ideally, we would use the markdown title but that's probably not possible.

**Comment by MichaReiser** [comment]
I think removing the `resources_md` should be possible by using the `#[base_dir = "/path/to/your/files"]` attribute.

**Comment by Aditya-PS-05** [comment]
@MichaReiser , 
Instead of removing `resource_md`, we should remove `resource_`. 
![Screenshot from 2024-10-20 14-57-49](https://github.com/user-attachments/assets/51b5d28d-9ea3-46eb-a455-26e570c83aec)


Is this modification okay?

**Comment by MichaReiser** [comment]
@Aditya-PS-05 ahh, the `md` isn't the file extension but comes from `mdtest`. Yes, that looks better

**Comment by AlexWaygood** [comment]
I think this is all done following #13831! (Please reopen if I'm mistaken!)
