### ISSUE TITLE
B007 fixer: don't mark loop variable as ignored when the dict iteration can be fixed

### ISSUE THREAD

**Issue by xmo-odoo** [astral-sh/ruff#13771]
Given code like
```python
for a, b in foo.items():
    something(b)
```
Currently the fixer will rename `a` to `_a`, but the better fix here would be to drop `a` entirely and iterate on `foo.values()` instead. Likewise `foo.keys()` if `b` is the unused loop variable.

Now obviously `foo` could technically be a non-mapping which just happens to have a `.items()` yielding a pair of items, but given the fixer is already unsafe I am not sure that would be a major issue?

**Comment by sbrugman** [comment]
Hi @xmo-odoo ,

The rule [incorrect-dict-iterator (PERF102)](https://docs.astral.sh/ruff/rules/incorrect-dict-iterator/#incorrect-dict-iterator-perf102) already addresses the case you are describing (and supports auto fix which is marked unsafe as you note).
