### ISSUE TITLE
select = ["E"] Not working. 

### ISSUE THREAD

**Issue by lozik4** [astral-sh/ruff#13793]
ruff==0.6.9
Python 3.12
MacOS 
Pytest Framework

pyproject.toml
```
[tool.ruff.lint]
select = ["E", "W", "F", "C90", "I", "COM", "ISC", "PT", "Q", "ARG", "PLC", "PLE", "A"]
ignore = ["F403", "F405", "E266", "PT013"]
fixable = ["ALL"]
unfixable = []
preview = true
explicit-preview-rules = true
```

```
ruff check --fix .
All checks passed!
```

But
E302, and E303 are not working, but if I moderate select block:
select = ["E", "W", "F", "C90", "I", "COM", "ISC", "PT", "Q", "ARG", "PLC", "PLE", "A", **"E302", "E303"**]
It helps fix

**Comment by zanieb** [comment]
Hi! Those rules are in preview and you have `explicit-preview-rules` turned on which requires exact rule codes for preview rules

- https://docs.astral.sh/ruff/preview/#using-rules-that-are-in-preview
- https://docs.astral.sh/ruff/preview/#selecting-single-preview-rules

**Comment by lozik4** [comment]
Thanks
