### ISSUE TITLE
RUF013 incorrectly emitted on invalid annotation with bare `Optional`

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#13833]
Here is the bad code diff
```diff
-        hsdp_device_mesh: Optional = None,
+        hsdp_device_mesh: Optional[Optional] = None,
```
Obviously, an untyped Optional is fine, and `Optional[Optional]` doesn't make much sense here as an autofix. 
* version ruff 0.7.0
* ruff check RUF013 --select=RUF013 . --fix --unsafe-fixes

**Comment by AlexWaygood** [comment]
A bare `Optional` is not a valid type annotation; both mypy and pyright will reject using `Optional` without type arguments in an annotation:

- https://mypy-play.net/?mypy=latest&python=3.12&gist=6cb9bb283ad911103c5a7ba4c09def98
- https://pyright-play.net/?pythonVersion=3.13&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDyCMSYKAhgDYBQ1AHgFyHGkWVQC8UAcmQKZA

But you're right that the autofix here just makes things worse! I think we should just not emit RUF013 at all here. It's outside the scope of this rule to detect type annotations that are simply invalid, and definitely outside the scope of the rule to try to fix them.

**Comment by henryiii** [comment]
A bare `Optional` would be `Optional[Any]`, which is `Any | None`. Which isn't helpful, since `Any` already includes `None`. The ones that are allowed to be bare, like `list` -> `list[Any]`, still make sense with `Any`.
