### ISSUE TITLE
Ruff formatter - unicode string inside of Enum object always lowercasing characters

### ISSUE THREAD

**Issue by DashKenny** [astral-sh/ruff#13859]
Hi,

I've been trying to upgrade ruff and use the formatter, so we can remove black. I have noticed this diff when using the formatter:

<img width="227" alt="image" src="https://github.com/user-attachments/assets/4a526853-5cca-4b50-9ca1-c858c9a60081">

This enum is used to validate codes from an external API, I would rather not try and handle lowercasing that data before accessing this enum. I cannot seem to find a rule to turn off this behaviour, does this not exist or am I missing something? Nothing interesting popped out to me when running `ruff format --verbose <path>`

Ruff version: `0.7.0`

Code snippet:

```
from enum import Enum


class TestEnum(Enum):
    ANGRY = '\u1F621'
    SAD = '\u1F622'
```

Ruff pyproject settings:
```
[tool.ruff.lint]
select = ["E", "F", "I", "Q", "N"]
ignore = []

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
```

Command invoked: 
`ruff format <path>` (Doesn't matter if it's only the file, or the whole repo)

**Comment by MichaReiser** [comment]
hi @DashKenny 

The casing of the hex-values in unicode escapes doesn't change the value at runtime:

```
>>> '\u1F621' == '\u1f621'
True
```

**Comment by DashKenny** [comment]
Thanks for the quick reply @MichaReiser and pointing that out. That makes sense.
