### ISSUE TITLE
[red-knot] Compare expression inference - Intersection

### ISSUE THREAD

**Issue by sharkdp** [astral-sh/ruff#13854]
As part of #13618, implement inference for compare expressions involving intersection types.

**Comment by carljm** [comment]
@sharkdp What is the status here? It would be nice to just close out the compare-expression task, but I also think this is probably a low-priority edge case. Is there an imprecise-but-not-incorrect approach we could put in place for now, pending real use cases, and call this done?

**Comment by sharkdp** [comment]
@carljm The status is that I have [this draft](https://github.com/astral-sh/ruff/pull/14138). It's better than nothing in that it turns a lot of `Type::Todo`s into correct answers, but it feels unfinished and potentially even wrong in some cases.

Glad to talk about it.

**Comment by carljm** [comment]
We discussed offline - the PR looks pretty good to me (it's OK if we are correct but not as precise as we could theoretically be) so we'll get it wrapped up and landed soon.
