### ISSUE TITLE
D204: enabled or disabled by default for Google convention?

### ISSUE THREAD

**Issue by void-rooster** [astral-sh/ruff#13864]
The docs have conflicting information about the default behavior for D204 in the Google convention. The rule page says D204 is enabled by default:

https://github.com/astral-sh/ruff/blob/fa7626160bd89ff76ac877ee9c71e15c5bad3ff8/crates/ruff_linter/src/rules/pydocstyle/rules/blank_before_after_class.rs#L68

while the answer to the FAQ says D204 is disabled by default:

https://github.com/astral-sh/ruff/blob/fa7626160bd89ff76ac877ee9c71e15c5bad3ff8/docs/faq.md?plain=1#L532

**Comment by MichaReiser** [comment]
The FAQ is correct and the rule documentation is the exact opposite. 

Source of truth:

https://github.com/astral-sh/ruff/blob/83b1c48a935f17869b9ee618faadc99213f83d95/crates/ruff_linter/src/rules/pydocstyle/settings.rs#L30-L43
