### ISSUE TITLE
SIM108 for return statements

### ISSUE THREAD

**Issue by joppi588** [astral-sh/ruff#13898]
For the following code snippet ruff detects a violation of SIM505:
```
def foo_sim108(bar):
    if bar is not None:
        xyz = bar
    else:
        xyz = "bar"
    return xyz
```
and proposes
```
def foo_sim108(bar):
    xyz=bar if bar is not None else "bar"
    return xyz
```
Usually I would omit xyz and write
```
def foo_ret505(bar):
    if bar is not None:
        return bar
    else:
        return "bar"
```
which is simplified by RET505 to
```
def foo(bar):
    if bar is not None:
        return bar
    return "bar"
```

However the shortest version would be
```
def simplified_foo(bar):
    return bar if bar is not None else "bar"
```

For me it is a special case for SIM108 (return means that a value is assigned to the function output), but ruff does not propose this solution.
Is this intended? 
If yes, I would be happy to have this behavior described in the SIM108 documentation.
If no, I would love to have it implemented.

Keywords: SIM108, RET505
Ruff version: 0.7.0

**Comment by MichaReiser** [comment]
Hi @joppi588 

That makes sense to me. 

Yes, this is intentional because there's `RET504` that detects the unnecessary assignment to `xyz` before returning ([playground](https://play.ruff.rs/7a1dee08-f03e-4882-95ff-7b64eb4d7c1f)).  Keeping the rules separate is that users are in control on whether they prefer the assignment before the return or not. 

Running `ruff check --fix` should directly fix 

```python
def foo_sim108(bar):
    if bar is not None:
        xyz = bar
    else:
        xyz = "bar"
    return xyz
```

to 

```python
def simplified_foo(bar):
    return bar if bar is not None else "bar"
```

if you have both rules enabled.

**Comment by joppi588** [comment]
Thanks, I see.

However simplifying
```
def foo(bar):
    if bar is not None:
        return bar
    return "bar"
```
to
```
def simplified_foo(bar):
    return bar if bar is not None else "bar"
```
would require a new rule, right?

**Comment by MichaReiser** [comment]
> would require a new rule, right?

Yes, but it would be a very opinionated rule because it could result in very long expressions.
