### ISSUE TITLE
f-string formatting: Consider format specs when choosing the preferred quotes

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#13935]
The new preview style formats

```python
"" f'{1:""}'
```

as 

```python
f"{1:\"\"}"
```

This is correct but results in unnecessary escapes. I think we should account for the quotes in format-specs when choosing the preferred quotes for an f-string. 

This can be changed here https://github.com/astral-sh/ruff/blob/113ce840a690cd59acbaf7d40d70b4352df681fe/crates/ruff_python_formatter/src/string/normalize.rs#L264-L295

CC: @dhruvmanila

**Comment by dhruvmanila** [comment]
I don't think we can do that because it would change the value of the format spec itself: https://play.ruff.rs/baf27789-023c-4803-aa8d-e933cc616f0f (refer to the AST).

Note that those quotes are not the surrounding quotes of a literal element but the quotes itself are _part_ of it.

**Comment by dhruvmanila** [comment]
Oh wait, I think I misunderstood. Do you mean we should account for the possible quotes inside a format spec, thus choosing single quote for this specific example?

**Comment by MichaReiser** [comment]
> Oh wait, I think I misunderstood. Do you mean we should account for the possible quotes inside a format spec, thus choosing single quote for this specific example?

Yes. We should use single quotes for the outer f-string because it avoids escaping the format-spec (unless the f-string contains more single quotes outside the format spec)
