### ISSUE TITLE
[red-knot] fix adding intersection to negative side of an intersection

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#13931]
Per de Morgan's law, `~(T & U)` is equivalent to `~T | ~U`.

So if we see an intersection in `IntersectionBuilder::add_negative`, we need to distribute it into a union, much like we do when adding a union to the positive side of an intersection (the same fold code should even apply, slightly modified.)

**Comment by TomerBin** [comment]
Can we close this issue as #13962 has landed?
