### ISSUE TITLE
New Rule + fixer: Use a list instead of calling split with string literals

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#13944]
I've seen this pattern a handful of time:
```py
"""
	itemA
	itemB
	itemC
""".split()
```
or
```py
"a,b,c,d".split(",")
```
And I'd like a rule to transform usages of `join` with literals into actual inline lists without the overhead of calling "join". My two examples above would become:
```py
[
	"itemA",
	"itemB",
	"itemC",
]
```
or
```py
["a", "b", "c", "d"]
```

I don't think this rule exists in any linters that I'm aware of.

The exact details of how this gets formatted isn't important to this rule. Probably just rewrite everything on a single line and let formatting/other rules take care of the rest.

**Comment by sbrugman** [comment]
Great suggestion, I think it's worth adding. With autofix this adds to developer experience as writing the comma-seperated pattern is sometimes just more convenient.

Real-world examples:
- https://github.com/apache/fury/blob/main/java/benchmark/analyze.py#L246
- https://github.com/alibaba/AliceMind/blob/main/VECO/NLU/evaluate.py#L103
- https://github.com/microsoft/DirectXShaderCompiler/blob/main/utils/hct/hctdb.py#L261
- https://github.com/pandas-dev/pandas/blob/main/pandas/tests/reshape/merge/test_merge_asof.py#L61
- https://github.com/numpy/numpy/blob/main/numpy/f2py/tests/test_return_real.py#L91

**Comment by sbrugman** [comment]
For posterity, @AlexWaygood noticed that this rule exists in flake8-simplify:
 https://github.com/MartinThoma/flake8-simplify/issues/86 (SIM905)
