### ISSUE TITLE
Black.format_file_in_place() equivalent for ruff?

### ISSUE THREAD

**Issue by zarif98** [astral-sh/ruff#13975]
I was wondering if there is an equivalent within Ruff?

> black.format_file_in_place(src: pathlib.Path, line_length: int, fast: bool, write_back: bool = False) → bool
> Format file under src path. Return True if changed.
> 
> If write_back is True, write reformatted code back to stdout. line_length and fast options are passed to [format_file_contents()](https://test-black.readthedocs.io/en/doc-conda/reference/reference_functions.html#black.format_file_contents).

**Comment by dhruvmanila** [comment]
i.e., a public API that Ruff exposes which is equivalent to the Black function that you've mentioned? Currently no, but we're interested in exposing a minimal API, refer https://github.com/astral-sh/ruff/issues/659. I'll merge this into that.
