### ISSUE TITLE
allow for multiple output formats in different output files

### ISSUE THREAD

**Issue by MarcBresson** [astral-sh/ruff#13997]
Hello,

I'm currently writing a CI pipeline in gitlab. I tried to make ruff generate reports in different format for sonarqube, gitlab, and grouped (for stdout). However, it seems like to do that I must call the `ruff check` command for every file format I want.

I think it would be beneficial to add the possibility to specify an array for output-format in the same way pytest-cov pluging works. For instance, in my case, I would do: 

`ruff check . --output-format=gitlab:report/ruff-gitlab.json --output-format=json:report/ruff.json --output-format=grouped`.

**Comment by MichaReiser** [comment]
Thanks for this feature request. 

This has come up before in https://github.com/astral-sh/ruff/issues/2388 Your ask goes slightly beyond in that you want many output formats and not just two. I'll merge this issue into the existing one. A new design should take both use cases into account.

**Comment by MarcBresson** [comment]
ok thanks ! It did not come up when I searched in github open/closed issues
