### ISSUE TITLE
Formatter breaks line-length and removes line continuations 

### ISSUE THREAD

**Issue by andre-muraro-umbrage** [astral-sh/ruff#14025]
When applying `format` , it removes line continuations resulting in E501 violations: 

Before:
```python
some_dict = {
    "some_really_long_key_name": some_ridiculously_even_impossibly_long_variable_name. \
        THIS_IS_A_RIDICULOUSLY_LONG_PROPERTY_NAME
}
```
After:
```python
some_dict = {
    "some_really_long_key_name": some_ridiculously_even_impossibly_long_variable_name.THIS_IS_A_RIDICULOUSLY_LONG_PROPERTY_NAME
}
# ˆˆˆ breaks E501
```

my local version `0.6.9`

POSSIBLY related 
[#11820](https://github.com/astral-sh/ruff/issues/11820)
[#10272](https://github.com/astral-sh/ruff/issues/10272)

[playground](https://play.ruff.rs/c4bc5f99-8c09-4836-ba58-10f6c61fa7bf)

**Comment by charliermarsh** [comment]
This is an intentional formatting decision -- continuations are always removed.

**Comment by MichaReiser** [comment]
You can parenthesize the value if you want to shorten the line a bit:

```py
some_dict = {
    "some_really_long_key_name": (
        some_ridiculously_even_impossibly_long_variable_name.THIS_IS_A_RIDICULOUSLY_LONG_PROPERTY_NAME
    )
}
# ˆˆˆ breaks E501
```
