### ISSUE TITLE
Add check for param in doc string that is not in the function signature.

### ISSUE THREAD

**Issue by brass75** [astral-sh/ruff#14050]
If we remove a parameter from a function/method signature we need to also remove it from the doc string. `ruff` does not check to make sure that all parameters mentioned in the doc string exist in the signature but it should.

**Comment by brass75** [comment]
It should also flag for a parameter that is in the signature (other than `self`) that is not included in a doc string if there is a doc string that includes a parameter list.

**Comment by MichaReiser** [comment]
Thanks. The doctring rules are tracked in https://github.com/astral-sh/ruff/issues/12434

**Comment by brass75** [comment]
Sorry for dropping a dupe on y'all. Too many issues to go through and find.

**Comment by MichaReiser** [comment]
> Sorry for dropping a dupe on y'all. Too many issues to go through and find.

Yeah, and GitHub search does no good job at finding....
