### ISSUE TITLE
[Question] Will implementation crates be published to crates.io?

### ISSUE THREAD

**Issue by tgeng** [astral-sh/ruff#14051]
Hey first thank you for creating this awesome tool!

I am curious if the implementation crates in ruff would be published to crates.io? That would be nice since I would like to leverage it for some python-related tools.

**Comment by MichaReiser** [comment]
We currently have no plans to publish the crates but we could reconsider for some specific crates if someone's interested in setting up a release process. See https://github.com/astral-sh/ruff/issues/10417 and https://github.com/astral-sh/ruff/issues/43
