### ISSUE TITLE
Add all Ruff release builds to Ruff Playground, selectable by user

### ISSUE THREAD

**Issue by diceroll123** [astral-sh/ruff#14062]
Would be neat if Ruff Playground had a dropdown selector to use older Ruff versions.

_Bonus points for the ability to share playground links that include version numbers for bug reports and regression tests._

**Comment by dhruvmanila** [comment]
I think this is the same as #1386

**Comment by dhruvmanila** [comment]
And, #7776. Closing this as duplicate.
