### ISSUE TITLE
Request: Fix to remove docstrings in stubs (PYI021/docstring-in-stub)

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#14123]
I'd like `PYI021` to provide an autofix (even an "unsafe" one is fine by me) to easily remove docstrings that may be generated by other tools. For example, https://github.com/microsoft/python-type-stubs/tree/main/stubs/sympy-stubs#remove-doc-comments has a custom script to remove docstrings that could be replaced by Ruff.

**Comment by MichaReiser** [comment]
I'm leaning towards making this fix unsafe by default, just because it's fairly destructive and the docstring could have contained meaningful text.
