### ISSUE TITLE
method on a class that returns an instance of that class gets F821 (undefined name) for the annotated return type

### ISSUE THREAD

**Issue by JoranDox** [astral-sh/ruff#14134]
file `path/to/myclass.py` contents:
```
class Myclass:
    def returnself(self) -> Myclass:
        return self
```
command: `ruff check --isolated path/to/myclass.py`
error:
```
path/to/myclass.py:2:29: F821 Undefined name `Myclass`
  |
1 | class Myclass:
2 |     def returnself(self) -> Myclass:
  |                             ^^^^^^^ F821
3 |         return self
  |

Found 1 error.
```
This code (in a much more complex form, specifically as a factory method for a class) works fine in production code, and I see no reason the linter shouldn't just see the name from right above.

ruff version: ruff 0.5.4

keywords searched for: F821, return type, classmethod, factory method

**Comment by dylwil3** [comment]
I agree with Micha - you could also surround the annotation with quotation marks [playground](https://play.ruff.rs/bfd71d97-6d9a-4385-b945-6c571d3d8d65).

**Comment by dylwil3** [comment]
But it sounds like you're seeing an undesired lint with your production code (which presumably can't have a syntax error in it!) Would it be possible to find a version of the more complex code that produces the undesired lint?

**Comment by JoranDox** [comment]
@MichaReiser Huh, I was literally just going to comment that pandas does literally this here https://github.com/pandas-dev/pandas/blob/v2.2.3/pandas/core/frame.py#L1805-L1931

but it doesn't trigger the same error, and you're right, they import annotations from __future__

Is that the intended way to do this? Python allows this as-is, right?

@dylwil3 Indeed, I realised now that quoting the annotation is exactly what `from __future__ import annotations` does lol
I'm not entirely understanding why this makes a difference, 

As for the production code, it's really very similar in structure, just with more arguments & other irrelevant things.
It gets the underline in vscode from ruff, but just runs fine with actual python.

**Comment by dylwil3** [comment]
What version of Python are you using? This is what I see for Python 3.11:

```bash
➜  ~ python
Python 3.11.5 (main, Sep  8 2023, 16:31:47) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class Myclass:
...     def returnself(self) -> Myclass:
...         return self
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in Myclass
NameError: name 'Myclass' is not defined
```

**Comment by JoranDox** [comment]
Huh, I think something is being weird here, you're right, running this example is indeed failing.
I'm afraid I accidentally found a hole in our tests :fearful: 
And I was mistaken, it's not yet production code, it's a refactor in progress pulling a function like this
```python

class Myclass:
    def __init__(self, params):
        ...

def create_myclass(params) -> Myclass:
    return Myclass(params)
```

into the class as a factory method, my bad.

All right, TIL about how annotations (don't) work in python, sorry for the confusion and thanks!

**Comment by dylwil3** [comment]
No worries, glad we could sort out the issue!
