### ISSUE TITLE
[red-knot] consolidate detection of cyclic class definitions

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#14141]
Currently both MRO resolution and metaclass resolution separately detect cycles, but we emit the diagnostic only from MRO resolution and ignore it from metaclass resolution. This is inefficient both in code to maintain and runtime cost.

Since detection of cyclic class definitions in the MRO case is already implemented as a standalone function, we can instead hoist the call to that function out to `TypeInferenceBuilder::check_class_definitions`, before resolving MRO or metaclass. If the class definition is cyclic, we can specify an `Unknown` result for the class' MRO and metaclass and avoid ever calculating them. Then MRO and metaclass resolution can assume non-cyclic as an invariant.

One thing we may have to guard against here is if the MRO or metaclass is accessed before we've done full inference of the scope the class is defined in.

**Comment by MichaReiser** [comment]
Wouldn't that regress the recovery? I believe we now only replace the cyclic-subgraph with `Unknown` instead of the entire MRO.

**Comment by carljm** [comment]
> Wouldn't that regress the recovery? I believe we now only replace the cyclic-subgraph with `Unknown` instead of the entire MRO.

Yes, but I think this doesn't actually matter at all.

**Comment by MichaReiser** [comment]
> Yes, but I think this doesn't actually matter at all.

Is that because `Unknown` silences all resulting false positives anyway?

**Comment by carljm** [comment]
> Is that because `Unknown` silences all resulting false positives anyway?

Exactly. It may mean a few more false negatives, but if you have a cyclic class definition it'd be perfectly reasonable to call the entire class `Unknown`; it's really not worth going out of our way for incrementally more precise types on a nonsense/impossible class definition.
