### ISSUE TITLE
[red-knot] Adapt the `fuzz-parser` script to fuzz red-knot too

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#14157]
We have a script here which proved very useful in discovering issues with our parser during the rewrite of the parser: https://github.com/astral-sh/ruff/tree/main/scripts/fuzz-parser. It generates random source-code snippets for Python that are guaranteed to be syntactically valid.

I think it wouldn't be too hard to adapt the script so that it can also run red-knot instead of just running the parser over the randomly generated source code. It might be quite useful for finding red-knot panics.

**Comment by connorskees** [comment]
As part of this work, would it make sense to add support to red-knot for type checking files read from stdin? Right now red-knot assumes that it's parsing workspaces from the file system, and doesn't seem to support ad hoc type checking of individual files. For fuzzing this would be helpful, as it avoids the overhead of reading and writing to the file system in a hot loop.

**Comment by MichaReiser** [comment]
> As part of this work, would it make sense to add support to red-knot for type-checking files read from stdin? 

Possibly, although I would prefer waiting to add stdin support until we have a clearer picture on how red-knots CLI should look like (should it even support paths)
