### ISSUE TITLE
[red-knot] Port more tests in `infer.rs` to mdtest

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#14166]
Following https://github.com/astral-sh/ruff/pull/14126, mdtest now supports Python snippets that contain invalid syntax. This enables us to port more tests in `infer.rs` over to the mdtest framework; we should do so

**Comment by carljm** [comment]
Closing as duplicate of https://github.com/astral-sh/ruff/issues/13696

**Comment by AlexWaygood** [comment]
Oh oops, I thought that had been closed... sorry!
