### ISSUE TITLE
[red-knot] understand more special forms in annotation expressions

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#14172]
Feel free to create and link a sub-task to claim one of these to work on:

- [x] Unions via `|`
- [x] #14498
- [x] #14354
- [x] #14544
- [x] https://github.com/astral-sh/ruff/issues/14558
- [x] #14545
- [x] #14703
- [x] #14834
- [x] #14546
- [x] #14922
- [x] https://github.com/astral-sh/ruff/issues/14891
- [x] https://github.com/astral-sh/ruff/issues/14916

**Comment by Glyphack** [comment]
To understand better: Do we want to follow the same approach for `typing.Any` and infer it as a known instance?
[Any](https://github.com/python/typeshed/blob/ca65e087f1f9dfc28e89192b60ce7cfc2e92c674/stdlib/typing.pyi#L134) is assigned an object. If we leave it as is then we just need to infer the `KnownClass::Object` in the annotations.

**Comment by AlexWaygood** [comment]
> To understand better: Do we want to follow the same approach for `typing.Any` and infer it as a known instance?

I think so. It's important that we distinguish internally between "members of the type `Any`" and "the singleton symbol that actually represents the `Any` type itself". Inferring the symbol `typing.Any` as a known instance allows us to do that.
