### ISSUE TITLE
FAST003 doesn't work on subclasses of FastAPI or APIRouter

### ISSUE THREAD

**Issue by fraser-langton** [astral-sh/ruff#14179]
We use custom classes for our app and router objects, wondering if it was possible for that to be picked up?

```python
from fastapi import APIRouter, FastAPI


class CustomAPI(FastAPI): ...


class CustomRouter(APIRouter): ...


app = CustomAPI()
router = CustomRouter()


@app.get("/things_1/{thing_id}")
async def read_thing_1(query: str): ...


@router.get("/things_2/{thing_id}")
async def read_thing_2(query: str): ...
```

currently `ruff check .` yields no errors - if I change to using the base classes it throws an error

**Comment by MichaReiser** [comment]
Hi @fraser-langton 

Ruff's current capabilities to reason about class inheritance is very limited and ad hoc. It doesn't work at all if the types are defined in different modules. We're working on a new analysis backend that will support this long-term but it's still far out. 

Short term, we could consider introducing a setting (or multiple) similar to [`logger-objects`](https://docs.astral.sh/ruff/settings/#lint_logger-objects) that lists all custom fast api base classes. Note, the setting should be plugin-specific and not in the global `lint` section.

**Comment by fraser-langton** [comment]
@MichaReiser makes complete sense, thanks for the advice
