### ISSUE TITLE
Request: Autofix for `future-annotations-in-stub`/`PYI044`

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#14186]
This one sounds like a pretty safe autofix, as the description of the rule says: "`from __future__ import annotations` has no effect in stub files". It's basically the same autofix as https://docs.astral.sh/ruff/rules/unused-import/

**Comment by dylwil3** [comment]
I think this autofix already exists but it's currently in preview.

```console
➜   echo "from __future__ import annotations" > tmp.pyi
➜   ruff check tmp.pyi --select PYI --preview --fix
Found 1 error (1 fixed, 0 remaining).
➜   cat tmp.pyi
➜  
```

**Comment by Avasam** [comment]
Ah I must've missed it being in preview then. Thanks !
