### ISSUE TITLE
`FBT001` exclude operators like `__and__`, `__or__` and `__xor__`, etc.

### ISSUE THREAD

**Issue by randolf-scholz** [astral-sh/ruff#14202]
[`FBT001`](https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/) should probably by default exclude methods used for operator overloading, in particular boolean logic specific operations:

- `__and__`, `__rand__`, `__iand__`
- `__or__`, `__ror__`, `__ior__`
- `__xor__`, `__rxor__`, `__ixor__`

And potentially also arithmetic operations like `__add__`, `__sub__`, `__mul__`, etc. (These may add overloads / type hints for boolean values)

**Comment by dylwil3** [comment]
This is an interesting idea! I guess one question I have is: if you are defining one of the Boolean magic methods for `MyClass`, why would the `other` parameter be a `bool` (as opposed to `MyClass`? Similarly for arithmetic operations.

I'd be interested to see examples of this in code out in the wild.

**Comment by MichaReiser** [comment]
An other option would be to ignore methods marked with @overload

**Comment by randolf-scholz** [comment]
@dylwil3 A typical example are custom scalar/vector/tensor classes/protocols.
@MichaReiser overloads are already excluded!

https://github.com/astral-sh/ruff/blob/a7e9f0c4b9f29201fe086b9fa32b87f1d5ae98a6/crates/ruff_linter/src/rules/flake8_boolean_trap/rules/boolean_type_hint_positional_argument.rs#L147-L151

Maybe one could add an `Exceptions` section to rule specification to document this?

**Comment by dylwil3** [comment]
Alright that makes sense to me- thanks for the example! I'm in favor of adopting this change.
