### ISSUE TITLE
SIM300 (yoda-conditions) triggered by CAPITAL class attributes with function call

### ISSUE THREAD

**Issue by DanielYang59** [astral-sh/ruff#14242]
[The following would trigger `SIM300`](https://github.com/materialsproject/pymatgen/pull/4159/commits/30e0f66de63c1605b2077394f4c21657455599f2), similar to #10848:

`bar` in the following code snippet seems stupid, in our case however it's `pytest.approx`.

```python
class Foo:
    def __init__(self):
        self.Z = 0.0
        self.Z_VAL = 0.0
        self.Z_val = 0.0

def bar(val):
    return val

kls = Foo()

assert kls.Z == 0.0           # all good
assert kls.Z == bar(0.0)      # SIM300 [*] Yoda condition detected
assert kls.Z_val == bar(0.0)  # all good
assert kls.Z_VAL == bar(0.0)  # SIM300 [*] Yoda condition detected
```

`--preview` would also trigger this, `ruff` version `0.7.3`.

Is it expected to treat `kls.Z` as a constant?

**Comment by charliermarsh** [comment]
Yeah it's expected that `kls.Z` is considered to be a constant -- it uses the screaming capitalization case.

**Comment by DanielYang59** [comment]
Okay thanks for the input!

**Comment by jakobhansen-blai** [comment]
I ran into this problem in the following context:

```python
class C:
    def __init__(self, X):
        self.X = X

xs = [C(i) for i in range(10)]
val = xs[0].X
for x in xs:
    assert x.X == val # SIM300
```

I don't think it makes sense to assume `x.X` is a constant in this situation, since `X` is scoped to the class instance, so different instances could have different values of this property.

**Comment by gsakkis** [comment]
Another case with pydantic-settings:
```python
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    foo: int = 1
    BAR: int = 1


settings = Settings()

print(settings.foo == 1)                 # ok
print(settings.foo == [])                # ok
print(settings.foo == frozenset())       # ok

print(settings.BAR == 1)                 # ok
print(settings.BAR == [])                # ok
print(settings.BAR == frozenset())       # SIM300
```
