### ISSUE TITLE
Import sorting does not respect `requires-python` when specified via inline script metadata

### ISSUE THREAD

**Issue by brettcannon** [astral-sh/ruff#14258]
In the below example I would expect `tomllib` to be sorted as a stdlib module as the script specifies that it requires Python 3.13 or newer which guarantees tomllib in the stdlib:
```python
# /// script
# requires-python = ">=3.13"
# ///

import sys

import tomllib
```

**Comment by dhruvmanila** [comment]
Related: #10457, #13446

We don't support reading any configuration from inline metadata yet.

I'll merge this into the above linked issue.
