### ISSUE TITLE
`lint.per-file-ignores` option is ignored by native server in `ruff.toml`

### ISSUE THREAD

**Issue by SXHRYU** [astral-sh/ruff#14282]
Basically it's the same issue as https://github.com/astral-sh/ruff/issues/11751 but the problem still occurs when using `ruff.toml` as config file.

jic: this happens in VS Code, when `ruff check`ing via console everything's okay.

**Comment by amoralesc** [comment]
I'm experiencing the same problem. I might add that I'm using a custom location for my Ruff config file, setting it under `.config/.ruff.toml`. Also working on Dev Containers.

I want to ignore the pydocstyle linter on all files under `src/migrations/versions`. Here's my environment (simplified) and steps to reproduce:

**Versions**

- `ruff`: 0.7.3
- `charliermarsh.ruff` extension: latest
- VSCode: 1.95.2

**Project structure:**

```
.
├─ .config
│  └─ .ruff.toml
├─ .venv
└─ src
   └─ migrations
      └─ versions
         └─ 1e8f6175aeef_a.py # <- file with errors
```

**VSCode settings:**

```json
{
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit"
    }
  },
  "ruff.importStrategy": "fromEnvironment",
  "ruff.interpreter": ["./.venv/bin/python"],
  "ruff.fixAll": true,
  "ruff.organizeImports": true,
  "ruff.configuration": "./.config/.ruff.toml",
}
```

**Ruff config file:**

```toml
target-version = "py312"
line-length    = 80
indent-width   = 4

[lint]
select = [
  "D"
]

[lint.per-file-ignores]
"**/versions/*.py" = [
  "D",
]

[lint.pydocstyle]
convention = "numpy"
```

The problematic file in question:

```python
"""Test

Revision ID: 1e8f6175aeef
Revises:
Create Date: 2024-11-14 02:42:01.465193

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1e8f6175aeef"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

```

When the file is on focus:

![image](https://github.com/user-attachments/assets/8a94be05-40ff-4e44-9122-61696602f116)

Running ruff check from the project root:

```bash
ruff check --config .config/.ruff.toml .
```

```
All checks passed!
```

For good measure, commenting out the `[lint.per-file-ignores]` section and running ruff again returns:

```
src/migrations/versions/1e8f6175aeef_a.py:1:1: D400 First line should end with a period
  |
1 | / """Test
2 | | 
3 | | Revision ID: 1e8f6175aeef
4 | | Revises:
5 | | Create Date: 2024-11-14 02:42:01.465193
6 | | 
7 | | """
  | |___^ D400
8 |   
9 |   from collections.abc import Sequence
  |
  = help: Add period

src/migrations/versions/1e8f6175aeef_a.py:18:5: D103 Missing docstring in public function
   |
18 | def upgrade() -> None:
   |     ^^^^^^^ D103
19 |     # ### commands auto generated by Alembic - please adjust! ###
20 |     pass
   |

src/migrations/versions/1e8f6175aeef_a.py:24:5: D103 Missing docstring in public function
   |
24 | def downgrade() -> None:
   |     ^^^^^^^^^ D103
25 |     # ### commands auto generated by Alembic - please adjust! ###
26 |     pass
   |

Found 3 errors.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

**Comment by amoralesc** [comment]
Same behavior with `exclude = []` on the Ruff config file

**Comment by dhruvmanila** [comment]
@amoralesc Do you mind trying it outside the Dev Container? There have been a couple of issues when working inside a dev container and I want to find some time to look into those soon.

**Comment by amoralesc** [comment]
@dhruvmanila I can indeed reproduce this error outside of the dev container. Tested with `extend-exclude` and `[lint.per-file-ignores]`.

My local environment is WSL. Worth noting that VSCode through WSL is still a remote server.

@SXHRYU Can you confirm how does your environment look like?

**Comment by dhruvmanila** [comment]
Ok, thanks for confirming. Although I don't have a Windows machine I can try reproducing on a Mac.

**Comment by dhruvmanila** [comment]
@amoralesc I'm looking at this now but just want to point out a couple of things:

```json
  "ruff.interpreter": ["./.venv/bin/python"],
```
I don't think this will work (https://github.com/astral-sh/ruff-vscode/pull/553), you'll need to update it to:

```json
  "ruff.interpreter": ["${workspaceFolder}/.venv/bin/python"],
```

But, otherwise I can reproduce this on my end although I'm not sure why this is happening.

**Comment by amoralesc** [comment]
@dhruvmanila Yes, my bad there. I wanted to generalize the reproducible environment and totally forgot that dot access doesn't work in `ruff.interpreter`. I'm actually using `${containerWorkspaceFolder}` there as well as in `ruff.configuration`. I'm gonna update the original snippet.

I may also add that the behavior is rather strange. Let's call the the problematic file `file.py`, deeply nested at `/path/to/file.py`. If I exclude the file like this:

```toml
# .config/.ruff.toml

# either like:
exclude = ["**/file.py"]
# or:
[lint.per-file-ignores]
"**/file.py" = ["D"]
```

That actually works correctly! This is not the ideal solution though, because I'd want to ignore everything under `path/to`. So when the pattern matching is changed to `./path/to/*.py`, `**/path/to/*.py` or `**/to/*.py`, it fails.

**Comment by amoralesc** [comment]
I can confirm the fix on https://github.com/astral-sh/ruff/issues/14282#issuecomment-2476724202 works on my environment.

I can't comment on this being the intended behavior, but it is still different from calling ruff from the project's root with:

```bash
ruff check --config .config/.ruff.toml
```

Thankfully, adding the `..` does work on both calls (VSCode extension and ruff).

**Comment by dhruvmanila** [comment]
@amoralesc I'd also recommend to use absolute path for `ruff.configuration` because this setting is applied for every workspaces that you open in VS Code. So, it could be that in a workspace there isn't a `.config/ruff.toml` file. Using absolute path is more useful in this context, we also support expanding tilde (`~`) here. I don't know your setup so I leave this up to you.

**Comment by amoralesc** [comment]
Since my environment is a Dev Container, I choose to use `${containerWorkspaceFolder}`. I can confirm this resolves to an absolute path to the config file inside the container in the extension logs.

Thanks for the heads up though!
