### ISSUE TITLE
(📚) documentation for `B028` is misleading

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#14289]
> The `warnings.warn` method uses a `stacklevel` of 1 by default, which limits the rendered stack trace to that of the line on which the `warn` method is called.

https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/#no-explicit-stacklevel-b028

reading this, it implies that if a higher number is set, then the stack trace will contain multiple entries

> It's recommended to use a `stacklevel` of 2 or higher, give the caller more context about the warning.

```diff
- give
+ giving
OR
+ to give
```

### maybe

```
The `warnings.warn` method uses a stacklevel of 1 by default, which will output a stack frame of the line on which the `warn` method is called. Setting it to a higher number will output a stack frame from higher up the stack.

It's recommended to use a `stacklevel` of 2 or higher, to give the caller a more appropriate context about the warning.
```

**Comment by dylwil3** [comment]
Nope! Hoping for a new contributor to take it as an excuse to pull down the repo and get comfortable with the PR process 😄

**Comment by glthm** [comment]
Yeah I was starting to look at it but the PR process is a bit complex so I won't be able to get into it during this month, so anyone can feel free to do it

**Comment by njhearp** [comment]
I thought I would try this to learn the process for a pull request. Sorry about the mess with the commits.

**Comment by dylwil3** [comment]
- @glthm Please don't hesitate to reach out and I can help navigate the PR process! Also would love feedback if the CONTRIBUTING docs could be made more helpful / less intimidating 😄 

- Thanks @njhearp! No need to apologize for the commits - great contribution!
