### ISSUE TITLE
Neovim LSP settings with a dash in the name are ignored

### ISSUE THREAD

**Issue by mamekoro** [astral-sh/ruff#14310]
I've tried to set `extend-exclude` to `["__about__.py"]` and `lint.allowed-confusables` to `["（", "）"]` in various ways, but none of them work.

Here is what I tried:

```lua
require("lspconfig").ruff.setup {
    init_options = {
        settings = {
            ["extend-exclude"] = { "__about__.py" },
            extend_exclude = { "__about__.py" },
            extendExclude = { "__about__.py" },
            lint = {
                select = { "ALL" },
                ["allowed-confusables"] = { "（", "）" },
                allowed_confusables = { "（", "）" },
                allowedConfusables = { "（", "）" },
            },
        },
    },
}
```

I created `__about__.py` as follows:
```py
# This is __about__.py
a = "（）"
```

And ruff shows the following diagnostics.
As you can see, both `extend-exclude` and `allowed-confusables` are not taking effect.

```text
# This is __about__.py     ■ Missing docstring in public module
a = "（）"     ■■ String contains ambiguous `）` (FULLWIDTH RIGHT PARENTHESIS). Did you mean `)` (RIGHT PARENTHESIS)?
```

The project directory contains only `__about__.py`. There are no `pyproject.toml`, `ruff.toml`, or `.ruff.toml` files.

How can I make these settings work?

**Comment by MichaReiser** [comment]
The `settings` don't support arbitrary ruff settings. They only support the LSP settings listed [here](https://docs.astral.sh/ruff/editors/settings/). 


`extend-exclude` can't be configured directly in the LSP. You have to create a configuration file instead and point to that. See [configuration](https://docs.astral.sh/ruff/editors/settings/#configuration)

**Comment by mamekoro** [comment]
> The settings don't support arbitrary ruff settings.

Is it intentional that the supported settings are limited?

In my opinion, it would be more convenient if all settings could be passed via Lua, as this would allow for the entire configuration to be managed in a single file.

**Comment by MichaReiser** [comment]
> Is it intentional that the supported settings are limited?

Somewhat. But I could see us supporting a `config` setting long-term that allows setting arbitrary configuration options, similar to the CLI's `ruff check --config extend-exclude=[...]`

**Comment by mamekoro** [comment]
OK. Closing since the question has been resolved.
