### ISSUE TITLE
DTZ901 Instead of warning replace datetime.datetime.min.time() with datetime.time.min

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#14378]
datetime.datetime.min may cause a timezone bug, but datetime.datetime.min.time() does not cause timezone problems.

I propose to add an exception to DTZ901 for datetime.datetime.min.time() and datetime.datetime.max.time()
Or replace them with datetime.time.min and datetime.time.max

**Comment by charliermarsh** [comment]
Can you expand on why `datetime.datetime.min.time()` is okay? (Not arguing that it isn't, just want to fully understand before we change it.)

**Comment by spaceby** [comment]
> Can you expand on why `datetime.datetime.min.time()` is okay? (Not arguing that it isn't, just want to fully understand before we change it.)

datetime.datetime.min returns an object that can explode.
However, datetime.datetime.min.time() returns a normal time. There are no localization issues here. There is no problematic datetime here. There is no localization either.
Moreover, it is actively used in datetime.combine

It's strange that people use datetime.datetime.min.time() instead of datetime.time.min .
It's as if people look to the beginning of time to find out what time the day begins.
