### ISSUE TITLE
Rule proposal: require explicit `strict=` argument for `itertools.batched`

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#14387]
[As of Python 3.13](https://docs.python.org/3/library/itertools.html#itertools.batched), `itertools.batched` has a `strict` parameter that defaults to `False`.  By default, the batches might not be of the same size, which may cause subtle bugs. When`strict=True`, it raises `ValueError` if the final batch is not the same size as the rest.

This seems analogous to the existing rule `B905` which requires an explicit `strict=` parameter for `zip`. Hence, I think it makes sense if there is a similar rule for `itertools.batched`.

I also created an [issue](https://github.com/PyCQA/flake8-bugbear/issues/498) `flake8-bugbear` which seems like a natural place for the rule given the similarity to `B905`.

Searched keywords: `itertools.batched`, `itertools`, `batched`

**Comment by MichaReiser** [comment]
Thanks for creating the upstream issue. Let's see what the outcome is upstream before adding this rule to avoid recoding in the near future.

**Comment by tjkuson** [comment]
Merged as `B911` upstream.

**Comment by MichaReiser** [comment]
Great. @InSyncWithFoo do you want to update your PR and recode the rule to B911?
