### ISSUE TITLE
Issue with new `PYI034` autofix when first param is annotated

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#14421]
Thanks @InSyncWithFoo for adding an autofix in https://github.com/astral-sh/ruff/pull/14217 .

* A minimal code snippet that reproduces the bug.

I did notice an issue that I think should be possible to handle. This case:
```py
class Container(tuple):
    def __new__(cls: Type[Container], *args, **kwargs) -> Container: ...
```

gets autofixed to
```py
class Container(tuple):
    def __new__(cls: Type[Container], *args, **kwargs) -> Self: ...
```

Which causes type error:
```
error: "Self" cannot be used in a function with a `self` or `cls` parameter that has a type annotation other than "Self" (reportGeneralTypeIssues)
```

I think it should be:
```py
class Container(tuple):
    def __new__(cls, *args, **kwargs) -> Self: ...
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

`ruff check --select=PYI034 --fix --preview --unsafe-fixes --isolated`

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

None

* The current Ruff version (`ruff --version`).

ruff 0.7.4

**Comment by Avasam** [comment]
I don't think this falls under PYI019, there are no typevar used here.

Ruff probably doesn't need to try and fix code like `def __new__(cls: Type[Container], *args, **kwargs) -> Self: ...` when it's encountered in the wild, as it's invalid to begin with. So I'm not asking for a rule to fix it, *but* it shouldn't produce it either.

The autofix is indeed unsafe, as there are cases where you wouldn't want to use `Self`. But assuming this is not one of those cases, it's correct to attempt an autofix here, the current implementation just doesn't yet handle it.

---

However this case is handled (if and when), both known reasons for this fix to be unsafe could be documented. (1. Intentionally returning a specific class from `__new__`; 2. May introduce type issues, for instance if the `self`/`cls` param is annotated)

**Comment by Avasam** [comment]
Maybe Ruff *should* have a rule to disallow (and remove) non-typevar annotations on `self`/`cls`? 🤔 
That'd solve the issue and this issue could be closed with only documenting the fix safety.

**Comment by MichaReiser** [comment]
@InSyncWithFoo If I recall, then https://github.com/astral-sh/ruff/pull/14238 handles type annotations in `self`/`cls` positions correctly. Any concerns with applying the same logic for this rule?
