### ISSUE TITLE
Wrong fix for PLC2801

### ISSUE THREAD

**Issue by bebound** [astral-sh/ruff#14423]
`ruff check kk.py --select PLC2801 --fix --preview --unsafe-fixes --isolated` change the code from
``` python
if 'kk'.__contains__("k"):
    print("yes")
```
to
``` python
if 'kk' in "k":
    print("yes")
```

The correct fix is `if 'k' in 'kk'`.

Version: ruff 0.7.4

**Comment by bebound** [comment]
Woo, that's so fast. Thank you.

**Comment by charliermarsh** [comment]
Thanks for pointing that out!
