### ISSUE TITLE
F-string formatting adds unnecessary space after `**` operator

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#14487]
Consider the following source code:

```py
f"aaaaaaaaaaaaaaaaaaaaaaaaaa {10**27} bbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccccccccccc"
```

Running `ruff format --preview`:

```py
f"aaaaaaaaaaaaaaaaaaaaaaaaaa {10** 27} bbbbbbbbbbbbbbbbbbbbbbbbbb ccccccccccccccccccccccccc"
```

Playground: https://play.ruff.rs/80926d6e-f183-4631-94ce-f1702502a0e0

Found in https://github.com/astral-sh/ruff/pull/14454#issuecomment-2488346686

**Comment by MichaReiser** [comment]
Huh, that's weird

**Comment by MichaReiser** [comment]
Oh, is it because of the inner `group` and the entire line exceeds the line length. We might need to remove `if_group_breaks` from `RemoveSoftLinesBuffer`

**Comment by MichaReiser** [comment]
this could be annoying
