### ISSUE TITLE
F841 is disabled by following, unrelated code lines

### ISSUE THREAD

**Issue by kud1ing** [astral-sh/ruff#14516]
This is with ruff 0.7.4.

`a` is recognized correctly as unused here (`F841 Local variable 'a' is assigned to but never used`):
```
def foo(x):
    if x:
        a = "hello"
        return
```
But if you add lines below, ruff stops recognizing it as unused (`All checks passed!`):
```
def foo(x):
    if x:
        a = "hello"
        return

    a = "goodbye"
    print(a)
```

**Comment by MichaReiser** [comment]
Ruff's "is used" detection isn't branch sensitive. This means, Ruff isn't aware that `a = "hello"` is only specific to the `if x:` branch.  All it sees is that there's a definition of `a` and that it is used somewhere inside `foo`. Thus, the variable is marked as unused. 

This is similar to https://github.com/astral-sh/ruff/issues/14355 and other linked issues. We're working on a new analysis engine that allows us to dedect unused assignments in individual branches, but it will be a while before we can use that in F841.
