### ISSUE TITLE
Add autofix for RUF039

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#14527]
The newly added preview rule RUF039 doesn't have an autofix. It would be very convenient if it had one, since it's otherwise quite a noisy rule.

**Comment by MichaReiser** [comment]
At least for the common cases. Conversions to raw strings can be tricky if backslashes are involved

**Comment by MichaReiser** [comment]
Or a fix involving backslashes at least needs to be unsafe because

```
>>> re.compile("\n\r\t").pattern == re.compile(r"\n\r\t").pattern
False
>>> re.compile("\n\r\t").pattern
'\n\r\t'
>>> re.compile(r"\n\r\t").pattern
'\\n\\r\\t'
```

**Comment by AlexWaygood** [comment]
Yeah. But even an autofix fix just for strings that don't have any backslashes in them would make things much more ergonomic. E.g. none of the strings that I had to manually edit in https://github.com/python-trio/trio/pull/3143 had any backslashes in them.

**Comment by dylwil3** [comment]
@AlexWaygood feel free to reopen if you'd like to encourage a second pass on this with more extensive auto-fixing!

**Comment by AlexWaygood** [comment]
Thanks! 😃 I think this is going to take care of most of the noise as-is, so I'm happy to leave it there for now unless we get requests from users for fixes in more cases 👍
