### ISSUE TITLE
[red-knot] support type[Any]

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#14546]
The Python type system supports the `type[Any]` type as a special case of [the `type[...]` special form](https://typing.readthedocs.io/en/latest/spec/special-types.html#type). This is a gradual type representing some unknown class and all of its subclasses.

Once we have fixed https://github.com/astral-sh/ruff/issues/14544, we should also support `type[Any]`. This will require updating our representation of `SubclassOfType` to an enum, so it can store either a `Class` or just represent `type[Any]`. This will also require checking each place we handle `Type::SubclassOf` and updating it to handle the gradual variant correctly.

We should also infer `type[Any]` from an annotation that just uses bare `type`, e.g. `x: type = ...`.

**Comment by AlexWaygood** [comment]
I suspect the enum we want here will have the same variants as this one:

https://github.com/astral-sh/ruff/blob/07d13c6b4a9acdfac3fbce314ee50685d0e8df0d/crates/red_knot_python_semantic/src/types/mro.rs#L303

I don't know whether it's worth trying to reuse (and rename?) that one or create another one with the same variants

**Comment by carljm** [comment]
> This seems simple enough. I'll have a PR ready by tomorrow.

Appreciate the interest in contributing! This issue (and a few others) are assigned to me because they are on the ramp up plan for a new Astral team member. If there isn't an unassigned issue that looks interesting to you, I can create some additional ones soon!

**Comment by dcreager** [comment]
> We should also infer `type[Any]` from an annotation that just uses bare `type`, e.g. `x: type = ...`.

Surfacing from https://github.com/astral-sh/ruff/pull/14876#discussion_r1878322282 that we have decided to interpret bare `type` as `type[object]`, not `type[Any]`.
