### ISSUE TITLE
[red-knot] support narrowing on `if x` and `if not x`

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#14550]
This is trickier than it might appear; the complexities are discussed in https://github.com/astral-sh/ruff/issues/13694#issuecomment-2438438759

It will likely require adding a new method `Type::exclude_always_truthy` which returns a new `Type` that excludes all inhabitants of the previous type that are known to always be truthy.

**Comment by cake-monotone** [comment]
May I work on this?

I noticed the comment about using an enum for narrowing (e.g., EliminateNonTruthy). Did you perhaps mean EliminateNonFalsy or EliminateTruthy instead?( `if not x`)

Would it be simpler to just define it as Falsy? I feel that the enum name doesn't necessarily need to include the notion of negation. What do you think about this approach?

If your intention is to emphasize that intersections with literals must always be negative, I can proceed as you suggested.

Additionally, I think we might also need a variant for the 'entire set.' For example, a case like `if x or not x` might require this.

**Comment by MichaReiser** [comment]
@cake-monotone  We have someone new starting next week and I think Carl created this task deliberately for them.  That's why he assigned it to himself.

**Comment by cake-monotone** [comment]
Ah! I see! Thanks for your comment! I haven’t started working on it.

**Comment by MichaReiser** [comment]
I haven't done much typing work myself so I don't have a good sense for how "hard" some of these tasks are but if you're interested in contributing, you could consider tackling one of the [special form](https://github.com/astral-sh/ruff/issues/14172) tasks or take a look at any other [task labeled with help-wanted](https://github.com/astral-sh/ruff/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Ared-knot+label%3A%22help+wanted%22)

**Comment by carljm** [comment]
@cake-monotone Micha is right about why I created this issue and assigned it to myself, but that said: if you are interested in working on this, please go ahead, that would be great! Given your past work I have no doubt you'll do a good job with it. We have plenty of things to work on, I won't have any trouble finding a replacement task for our new hire. (And this isn't one of the initial starter tasks, so they wouldn't have gotten to it for a few weeks anyway.)

Please do confirm if you start working on it, and I will assign it to you.

**Comment by carljm** [comment]
Regarding the naming, I think you are right, it will be clearer to use a name like I suggested in the description of this issue (`exclude_always_truthy`). It is important to reflect that this is a negative intersection (that is, we are excluding all types known to always be truthy, which is different from intersecting with Falsy.)

But the word "exclude" already serves that purpose, it's just confusing to use another negative beyond that.

**Comment by cake-monotone** [comment]
I got it. Thanks for clarifying and for your encouragement! I’ll start working on this—feel free to assign it to me.

Also, thanks to MichaReiser for pointing out other potential tasks. I really appreciate it!
