### ISSUE TITLE
Feature: Detection of unused libraries from pyproject.toml

### ISSUE THREAD

**Issue by akshaybabloo** [astral-sh/ruff#14620]
A good to have feature would be to list out all unused libraries (dev and dependencies), so that they can be removed or used.

**Comment by dylwil3** [comment]
That sounds like a neat idea! It will require multi-file analysis, I think (which is included under the umbrella of "type inference").

**Comment by dhruvmanila** [comment]
I think this is more of a packaging problem and it should be covered by the third point in https://github.com/astral-sh/ruff/issues/10015. Merging this issue with the linked one.
