### ISSUE TITLE
Disable TC001, TC002, TC003 by default ?

### ISSUE THREAD

**Issue by RomainBrault** [astral-sh/ruff#14637]
It breaks runtime type checking.

See the discussions: https://github.com/beartype/beartype/discussions/460
And: https://github.com/beartype/beartype/pull/440#issuecomment-2421528743

It also break library that use type information at runtime.

From flake8-type-checking itself, see: https://github.com/snok/flake8-type-checking/issues/52#issuecomment-1004842907

Also `from __future__ import annotations` will be removed when Python 3.13 support will end. Moreover PEP 649, implemented in python 3.14, should solve the time penalty that TC001,2,3 try to resolve.

Alternative solutions:

disable starting from Python 3.14 only. Or do exception for all library that use runtime type information as in flake8 (e.g. beartype)

**Comment by RomainBrault** [comment]
Indeed, i used the ALL selector 😳 , thanks for pointing it out

however it would be nice to have a warning in the documentation saying that this rules might break runtime type usage, and maybe that `from __future__ import annotations` will be deprecated in Python 3.14 (thus not using the rule is encouraged for the version >= 3.14) and the rule should be removed when 3.13 support will end.

**Comment by MichaReiser** [comment]
Thanks for pointing that out. We'll revisit all rules when Python 3.14 is closer to reaching beta status, and I'll close this as there's nothing immediate that needs to be done now.
