### ISSUE TITLE
Documentation with complete rulesets and parity information

### ISSUE THREAD

**Issue by kaddkaka** [astral-sh/ruff#14651]
I would like to propose that the rule documentation or rule page (or a new subpage?) lists all existing rules from the different tools (flake8, pycodestyle, pylint, etc...) and which ones currently are and are not implemented in ruff.

This would make it easier for developers to understand if they can stop using some tool and adopt ruff instead. 

Related issues:
- https://github.com/astral-sh/ruff/issues/2322
- https://github.com/astral-sh/ruff/issues/1593
  - This issue also asks for this information but was closed without much discussion as at that time there was a section into the README called "How does ruff compare to flake8".

The list could include:
- all rules of each set and which rules are implemented: 
  - in ruff (stable default)
  - in ruff (stable opt-in)
  - in ruff (preview)
  - in ruff (not yet)
  - in ruff (not planned/low priority because of reason X)
  - what version of ruff the rule was implemented in

**Comment by kaddkaka** [comment]
Existing issues I could find that tried to reach parity and implement remaining rules of a specific ruleset:
- #970 
- #2402

**Comment by MichaReiser** [comment]
Thanks. Something very similar has come up before in https://github.com/astral-sh/ruff/issues/13897 Please see my response in that issue (and feel free to continue the conversation over there)
