### ISSUE TITLE
new rule - Removing extra spaces in dictionary

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#14673]
Ruff does not remove extra spaces in such dictionaries.
```python
d = {'a':               'b'}
```
In other cases, spaces are removed.
Please add a rule for this case too.

**Comment by MichaReiser** [comment]
Have you tried `ruff format`? It should remove the extra spacing. Or aren't you using it because it is too opinionated?

**Comment by spaceby** [comment]
Yes, I don't use it.

**Comment by MichaReiser** [comment]
I'll merge this into https://github.com/astral-sh/ruff/issues/2402 because this is covered by pycodestyle E241
