### ISSUE TITLE
New Metadata Version on ruff-0.8.1-py3-none-linux_armv6l.whl

### ISSUE THREAD

**Issue by matthewakram** [astral-sh/ruff#14681]
It seems that there is an issue with latest wheel. The metadata version on is at 2.4. The pkginfo package support only metadata versions up to 2.3. This is pretty important since this is a crucial part of how Poetry resolved the package to install. Would it be possible to roll that back, ensuring that none of the released wheels have metadata version >2.3? I am not sure what the metadata versions of all the other wheels are, but I am getting the error for ruff-0.8.1-py3-none-linux_armv6l.whl.

here is the exact error:
```
C:\Users\\...\.venv\Lib\\site-packages\pkginfo\\distribution.py:175: NewMetadataVersion: New metadata version (2.4) higher than latest supported version: parsing as 2.3
  warnings.warn(NewMetadataVersion(self.metadata_version))

Unable to determine package info for path: C:\Users\...\AppData\Local\Temp\2\tmpivaox21p\ruff-0.8.1-py3-none-linux_armv6l.whl

Unknown metadata version: 2.4
```

Steps to recreate. 
1) windows machine
2) start a poetry project
3) add ruff = "0.8.1" to the dependencies
4) run poetry update

**Comment by dmcauslan** [comment]
Maybe it depends on how poetry is installed? I'm seeing the same issue with poetry 1.8.4 installed via pipx.

**Comment by MichaReiser** [comment]
> Maybe it depends on how poetry is installed? I'm seeing the same issue with poetry 1.8.4 installed via pipx.

I hope not. That would be rather surprising. Can you share what platform your on and run `poetry --version`? I now verified that adding ruff works on macos and windows.

**Comment by mohsen-eng74** [comment]
I have the same issue:

```
OS: Ubuntu 22.04.5 LTS 64-bit
Poetry: 1.8.4 (Installed via vendor-specific installation script)
Python: 3.12.7 (Installde via `pyenv 2.4.19-2-g61406193`)
```

```
Downloading ...pypi/packages/packages/a2/d6/1a6314e568db88acdbb5121ed53e2c52cebf3720d3437a76f82f923bf171/ruff-0.8.1-py3-none-linux_armv6l.whl#sha256=fae0805bd514066f20309f6742f6ee7904a773eb9e6c17c45d6b1600ca65c9b5  96% (14.7s).../.local/share/pypoetry/venv/lib/python3.12/site-packages/pkginfo/distribution.py:175: NewMetadataVersion: New metadata version (2.4) higher than latest supported version: parsing as 2.3
  warnings.warn(NewMetadataVersion(self.metadata_version))

Unable to determine package info for path: /tmp/tmpv0nhj4py/ruff-0.8.1-py3-none-linux_armv6l.whl

Unknown metadata version: 2.4
```

**Comment by MichaReiser** [comment]
I suggest reporting this to poetry because downgrading the metadata version is not in our control (managed by maturin)

**Comment by MichaReiser** [comment]
To give some more context on why we bumped the metadata version. 

We tried publishing Ruff 0.8 with the old metadata version but pypi rejected the wheel (unlike previous releases where this just worked)

```
error: Failed to publish `wheels/ruff-0.8.1-py3-none-linux_armv6l.whl` to https://upload.pypi.org/legacy/
  Caused by: Upload failed with status code 400 Bad Request. Server says: 400 license-file introduced in metadata version 2.4, not 2.3. See https://packaging.python.org/specifications/core-metadata for more information.
```

That's why I don't think we can do anything at our end.

**Comment by bigpick** [comment]
> I hope not. That would be rather surprising. Can you share what platform your on and run poetry --version? I now verified that adding ruff works on macos and windows.

FWIW, I'm seeing this on macOS, with poetry `1.8.4` and `Python 3.11.10`)

**Comment by Slooz** [comment]
We're seeing the same issue, even with fresh installations.

```
OS: Mac Sequoia/Ubuntu 22.04
Python 3.11/3.12
pipx: 1.7.1
Poetry: 1.8.4
Ruff: 0.8.1
```

We're also using Artifactory. I'm out of my depth here, but the following seems related? Is this an Artifactory issue?

https://github.com/pypa/wheel/issues/643

**Comment by bigpick** [comment]
> I suggest reporting this to poetry because downgrading the metadata version is not in our control (managed by maturin)

Related to this, I think: https://github.com/python-poetry/poetry/issues/9670

**Comment by MichaReiser** [comment]
Could you try updating the `pkginfo` dependency. The newest released version (which poetry uses) adds support for 2.4

https://pypi.org/project/pkginfo/

**Comment by bigpick** [comment]
> The newest released version (which poetry uses) adds support for 2.4. This also explains why running poetry with uvx works because it installs the latest pkginfo version but might not work in your project where you use an older verison.

Trying the above against, looks like it does get the newest version (1.12.0, that was release _12 minutes ago_) and works for me (for both the public and Artifactory example)

**Comment by MichaReiser** [comment]
I'll close this because there's now a known fix on the poetry side (upgrade `pkginfo`). Let me know if it doesn't resolve your problem.

**Comment by sagnik** [comment]
I am just going to leave a comment that I had to upgrade poetry that I had installed through pipx for this to work, so both `pipx upgrade poetry` and `poetry run pip install --upgrade pkginfo`.
