### ISSUE TITLE
[red-knot] understand `type[A | B]` where A and B are both classes

### ISSUE THREAD

**Issue by Glyphack** [astral-sh/ruff#14703]
(part of https://github.com/astral-sh/ruff/issues/14172)
`type[A | B]` Is equivalent to an enum of `type[A]` | `type[B]`.

There are not a lot of edge cases looking at the tests here: https://github.com/python/typing/blob/main/conformance/tests/specialtypes_type.py#L50

**Comment by sbrugman** [comment]
Just a heads-up for future reference: red-knot should produce a violation when the `type[A, B]` syntax is used.

This came up in [this PR](https://github.com/astral-sh/ruff/pull/14660)
