### ISSUE TITLE
0.8.1 regression - formatter removes strings causing a syntax error on multiline fstring with implicitly concatenated strings and an `if` expression inside it

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#14778]
before:
```py
f"""{'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' 'a' if True else ""}\
a"""
```

after:
```py
f"""{ if True else ""}\
a"""
```

[playground](https://play.ruff.rs/53e2a577-7898-4ac9-9ceb-c5c0c26eca36)

**Comment by dhruvmanila** [comment]
A bit more minimal example:
```python
f"{'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' 'a' if True else ""}"
```

If you remove one `a` from the string, the formatting is correct because it now fits on the line.

**Comment by MichaReiser** [comment]
I think this is related to https://github.com/astral-sh/ruff/pull/14489

We may need a more local fix or change our approach in the f-string formatter to instead format the inner expression on its own with line-length set to max.
