### ISSUE TITLE
I001: isort behavior is inconsistent.

### ISSUE THREAD

**Issue by ofk** [astral-sh/ruff#14784]
The formatting of from-import statements with and without parentheses is not consistent.

There is a sentence like:

```py
from package import value
```

Let's rewrite it like:

```py
from package import (
    value,
)
```

It cannot be reverted to the original format.

**Comment by MichaReiser** [comment]
Keeping the import over multiple lines if there's a trailing comma after the last imported name is a convention used by Black/Ruff and isort. You can disable this behavior by [`isort.split-on-trailing-comma`](https://docs.astral.sh/ruff/settings/#lint_isort_split-on-trailing-comma) to `false`

**Comment by ofk** [comment]
Thanks! I got the behavior I wanted. 🎉
