### ISSUE TITLE
[Autofix request] B028: no-explicit-stacklevel

### ISSUE THREAD

**Issue by DanielYang59** [astral-sh/ruff#14805]
Can I request an autofix for B028: no-explicit-stacklevel?

I understand `stacklevel=2` may not be the one-size-fits-all solution (some implementation might need higher stack level), but I guess it's a good default value for `ruff` autofix?

**Comment by AlexWaygood** [comment]
Yeah, I agree that an unsafe autofix to `stacklevel=2` is reasonable here.

**Comment by DanielYang59** [comment]
Thanks for the confirm that would be really helpful :)

**Comment by DanielYang59** [comment]
@dylwil3 Really appreciate the quick fix, I noticed another minor relevant issue while cleaning up our code base, that is: some people might notice this warning, and might thought it's "no explicit stacklevel" that is bad, and ended up giving "stacklevel=1", is it possible to extend B028 to cover "stacklevel=1" as well? I'm happy to keep a separate issue to track this if you believe it's worth the effort :)

**Comment by DanielYang59** [comment]
Thanks for the quick implementation again.

> If a developer explicitly specifies the stacklevel it feels a little rude to contradict them

Yep I agree, they might know well what they're doing, so perhaps don't warn for such case. Also manual fixing for such cases is much easier, just do a regular expression search and replace.

> So maybe there is some editing to be done to the message and/or documentation? 

I'm personally happy with the state of the docs. Our code base is built around chemistry so most people don't come from CS background to understand "stack", and they just don't bother to read the documentation and ended up passing a safe `stacklevel=1` to mute the warning I guess.

> I don't think I know enough about the usage here to gauge whether this would be common/helpful, but please feel free to suggest this as a new lint rule in a separate issue and folks can weigh in.

Thanks for the comment. I guess it's not worthy a issue as it's just a unnecessary default argument given (looks not so tidy but don't have any other side effect), there's no way for us to warn again every default value using I guess :)

Thanks again and all the best
