### ISSUE TITLE
ruff check -w stuck in file change detected loop when pyproject.toml present (since 0.7.3)

### ISSUE THREAD

**Issue by ziddey** [astral-sh/ruff#14807]
To reproduce (ruff 0.7.3-0.8.2):
```
mkdir test
cd test
touch pyproject.toml
ruff check -w
```

Will be stuck in a `File change detected...` loop.

`ruff.toml` file has the same effect. I've tried using the equivalent default configuration in the docs instead of a blank file with the same result.

0.7.2 seems to work fine with the watch flag

Ubuntu 22.04 LTS amd64 / Debian 12 arm64

**Comment by MichaReiser** [comment]
This is interesting. It seems that ruff is constantly notified about changed
