### ISSUE TITLE
[Fix error] C417 and walrus statements

### ISSUE THREAD

**Issue by zeevox** [astral-sh/ruff#14808]
Applying fixes for rule [C417](https://docs.astral.sh/ruff/rules/unnecessary-map/) introduces a syntax error when the second `map` argument is a walrus assignment operator. 

Minimal example below.
I'm using `ruff` 0.8.2 and Python 3.12.7 to test this.
For a more complete example, this issue first arose in my [solution](https://github.com/zeevox/advent-of-code/blob/26a86375aab513f4020b6264d7096561d031ba03/2019/python/Day03.py#L24-L27) to Advent of Code [2019 Day 3](https://adventofcode.com/2019/day/3). 

```diff
a = [1, 2, 3]
b = map(lambda x: x, c := a)
print(c)
```

Fix applied by `ruff check test.py --select C417 --fix --unsafe-fixes`

```diff
-b = map(lambda x: x, c := a)
+b = (x for x in c := a)
```

is syntactically incorrect

```python
  File "/home/zeevox/test.py", line 2
    b = (x for x in c := a)
                      ^^
SyntaxError: invalid syntax
```

You would think wrapping the walrus statement in parentheses would suffice, like

```python
b = (x for x in (c := a))
```

And indeed, `ruff` believes all is well

```
% ruff check test.py --select C417
All checks passed!
```

but this too, in fact, raises a syntax error

```python
  File "/home/zeevox/test.py", line 2
    b = (x for x in (c := a))
                     ^^^^^^
SyntaxError: assignment expression cannot be used in a comprehension iterable expression
```

I wonder whether the real solution is to extract the assignment onto the previous line, or not show the warning in the first place.

**Comment by harupy** [comment]
@AlexWaygood Can this change fix the error?

```diff
diff --git a/crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs b/crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
index 4761c80b8..9e2baec85 100644
--- a/crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
+++ b/crates/ruff_linter/src/rules/flake8_comprehensions/fixes.rs
@@ -697,7 +697,7 @@ pub(crate) fn fix_unnecessary_map(
     let iter = iter.clone();
     let iter = if iter.lpar().is_empty()
         && iter.rpar().is_empty()
-        && matches!(iter, Expression::IfExp(_) | Expression::Lambda(_))
+        && matches!(iter, Expression::IfExp(_) | Expression::Lambda(_) | Expression::NamedExpr(_))
     {
         iter.with_parens(LeftParen::default(), RightParen::default())
     } else {
```
