### ISSUE TITLE
Upgrade to React 19

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#14859]
Ref: https://github.com/astral-sh/ruff/pull/14856

Migration guide: https://react.dev/blog/2024/04/25/react-19-upgrade-guide

As mentioned, I think it'll be useful to first upgrade it to v18.3, fix the warnings and then upgrade to v19.

**Comment by MichaReiser** [comment]
Hmm we now have a bit of a mess hehe. The typing stubs already use React 19, but the runtime still uses react 18.2

**Comment by MichaReiser** [comment]
Depends on https://github.com/suren-atoyan/monaco-react/issues/656
