### ISSUE TITLE
Feature request: Support for .editorconfig

### ISSUE THREAD

**Issue by Lattay** [astral-sh/ruff#14865]
It would be nice if the ruff autoformat system could read settings from .editorconfig, such as indentation related parameters.

**Comment by AlexWaygood** [comment]
Thanks for opening the issue -- this is a duplicate of https://github.com/astral-sh/ruff/issues/1530, however :-)

**Comment by Lattay** [comment]
Deeply sorry, I don't know how I missed the other issue.

**Comment by AlexWaygood** [comment]
No worries, it happens! GitHub issue search is pretty bad :-)
