### ISSUE TITLE
Ability to output junit format to a file and retain default output to standard out.

### ISSUE THREAD

**Issue by martinka** [astral-sh/ruff#14878]
We attempt to use the same Makefile for both our dev environments and our CI pipelines.  We would like junit reporting for the CI pipelines but its not particularly human readable.  We have been able to configure other linters  to emit a file in junit while having the stdout still be human readable.  Effective this would change the output-format setting to a list and allow setting a file with the formatter.  An Example of how this is handled in pylint is `output-format="text,junit:build/junit-pylint.xml` 

I am new to rust but it looks like a bulk of the change would be in printer.rs

This would make our ci pipeline a lot cleaner, the only alternative right now seems to be to run ruff twice.

**Comment by MichaReiser** [comment]
Hi @martinka 
I think this is the same as https://github.com/astral-sh/ruff/issues/2388

**Comment by martinka** [comment]
Yes it is.. I missed that when looking at the issues.  you can close this I will follow that.
