### ISSUE TITLE
[red-knot] mdtest should fail if you have a triple-backtick block that is unclosed

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#14934]
If you have an [mdtest](https://github.com/astral-sh/ruff/tree/main/crates/red_knot_test) like this at the end of the Markdown file, it doesn't fail:

````
# bytes should be inferred as strings

```py
x = b"42"

reveal_type(x)  # revealed: str
````

That's because the backticks are never closed, so mdtest doesn't even recognise this as a test snippet. I _keep on_ making this mistake locally and wondering why my tests aren't even running! It would be ideal if the framework could detect this and tell me that my test file is invalid because the backticks were never closed.

**Comment by sharkdp** [comment]
Yes, please! Ran into this multiple times already.
