### ISSUE TITLE
[RUF051] Formatting issue for description of `if-key-in-dict-del` (RUF051) in docs

### ISSUE THREAD

**Issue by echoix** [astral-sh/ruff#14976]
In the new rule [if-key-in-dict-del (RUF051)](https://docs.astral.sh/ruff/rules/if-key-in-dict-del/#if-key-in-dict-del-ruf051), there seems to be a formatting issue, as shown in the following screenshot.
![Image](https://github.com/user-attachments/assets/5d528cd7-d923-43ea-aced-9531753885ae)

I don't see the problem in the PR that seems to have added that text: https://github.com/astral-sh/ruff/pull/14553/files#diff-b0fd57331d4ce41cac2a70091108b4053b5514a06d5d75da3b6bb0e880fbaeb0R11-R16

What is different from other rules that don't show up like this?

**Comment by dylwil3** [comment]
Good catch! My guess is that `mkdocs` does not like the backticks that it's pulling out for the description? (That description/tag is auto-generated by a script based on the doc-comment).
