### ISSUE TITLE
How to get a list of rules that are applied when running `ruff format --diff`?

### ISSUE THREAD

**Issue by zachvalenta** [astral-sh/ruff#15024]
When viewing list of potential formats to make with `ruff format --diff`, would be nice to list the associated rule (e.g. `E117`) that's behind the proposed format. Not sure if one can config ruff to ignore particular rules, but would be useful to know for pedagogical reasons as well.

**Comment by dylwil3** [comment]
Just to make sure I understand: The ruff _linter_ and _formatter_ are distinct- the former has rules (like the `pycodestyle` one you referenced) but the latter does not. Are you using the linter with selected rules to format and want to see changes from those rules?

**Comment by dhruvmanila** [comment]
Related: #14948, #8206

**Comment by dhruvmanila** [comment]
The formatter doesn't work in the same way as the linter where the linter provides a set of rules that are checked and possibly fixed while the formatter has a set of rules built into the implementation that are applied. There are certain rules that overlap as you've noticed but the logic for such "rules" in both the linter and the formatter is different. Please refer to the linked issues for more details.
