### ISSUE TITLE
Fix for INP001 implicit-namespace-package

### ISSUE THREAD

**Issue by kiyoon** [astral-sh/ruff#15029]
Can there be a fix for the rule? I would like to add `__init__.py` files where missing.

**Comment by kiyoon** [comment]
In the meantime I generated a simple python script that checks the lint and adds the files:

https://github.com/deargen/workflows/blob/e99efa3e0c7d415d56af820d3875c749365e8dea/scripts/gen_init_py.py

**Comment by dhruvmanila** [comment]
Our current fix infrastructure doesn't support modifying files on disk. I think this might be useful because language servers do provide refactoring ability to move snippets of code to another file.

**Comment by dhruvmanila** [comment]
Thank you!

**Comment by kiyoon** [comment]
oops, sorry
