### ISSUE TITLE
ruff check --add-noqa struggles on lines that already have comments

### ISSUE THREAD

**Issue by arrdem** [astral-sh/ruff#15028]
Consider the snippet

```
elif type(event) == RiskEvent:  # since some common helper methods call this function
  return False
```

This is an instance of E721 as it rightly should be, and `ruff check` will correctly detect that. The long comment is within the line length limit and so the condition won't be parenthesized and flowed either. However if you `ruff check --add-noqa`, you get the expanded comment `# ... # noqa: E721` which does overflow the line length, causing the expression to be parenthesized and reflowed into

```
elif (
  type(event) == RiskEvent
):  # since some common helper methods call this function  # noqa: E721
  return False
```

Which is still an instance of E721 because the `noqa:` has been flowed off the problem line.

Produced in Ruff 0.8.3

**Comment by dhruvmanila** [comment]
Thanks for raising this. This is a known issue, I'll merge this into https://github.com/astral-sh/ruff/issues/12901.
