### ISSUE TITLE
No way to avoid adding imports to a file (i.e. "isort: dont-add-imports")

### ISSUE THREAD

**Issue by chrisburr** [astral-sh/ruff#15077]
In my project there are a couple of files where `from __future__ import annotations` can't be used due to upstream bugs but we want to enforce the future import for all other files.

As it stands there doesn't seem to be a way to do this in ruff.

When using isort `# isort: dont-add-imports` can be used, however ruff ignores this option:

```bash
$ echo '# isort: dont-add-imports' > test.py; echo '' >> test.py; echo 'x: int = 5' >> test.py
$ ruff check --config lint.select='["I"]' --config lint.isort.required-imports='["from __future__ import annotations"]' --fix test.py
Found 1 error (1 fixed, 0 remaining).
$ cat test.py
# isort: dont-add-imports
from __future__ import annotations

x: int = 5
```

**Comment by chrisburr** [comment]
After posting this I realised I can get what I need with:

```toml
[tool.ruff.lint.extend-per-file-ignores]
"my/problematic/file.py" = ["I002"]
```

**Comment by MichaReiser** [comment]
It looks like you found a solution for your problem. If not, feel free to comment and we can re-open this issue
