### ISSUE TITLE
`FAST002` only checks positional and keyword parameters

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#15117]
`FAST002` only checks positional and keyword parameters. Should it also check keyword-only parameters?

```python
from fastapi import FastAPI, Path

app = FastAPI()


@app.get("/items/{item_id}")
async def read_items(*, item_id: int = Path(title="The ID of the item to get"), q: str):
    results = {"item_id": item_id}
    if q:
        results.update({"q": q})
    return results
```

Source: https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/#order-the-parameters-as-you-need-tricks

**Comment by dhruvmanila** [comment]
Yeah, that makes sense.
