### ISSUE TITLE
`SyntaxError` in example replacement snippet in `nonlocal-without-binding` (`PLE0117`)

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#15154]
The docs for [`nonlocal-without-binding`](https://docs.astral.sh/ruff/rules/nonlocal-without-binding/) have this snippet under the heading `## Use instead`:

```py
class Foo:
    bar = 1

    def get_bar(self):
        nonlocal bar
        ...
```

I would not advise anybody to use this code, because it causes a `SyntaxError` 😆

```pycon
>>> class Foo:
...     bar = 1
... 
...     def get_bar(self):
...         nonlocal bar
...         ...
...         
  File "<python-input-13>", line 5
    nonlocal bar
    ^^^^^^^^^^^^
SyntaxError: no binding for nonlocal 'bar' found
```

That's because name lookup in method scopes can't see bindings in class scopes. I.e., an example with a function scope inside a function scope (rather than a function scope inside a class scope) works correctly:

```py
>>> def foo():
...     bar = 1
...     def get_bar():
...         nonlocal bar
...
>>>
```

**Comment by enochkan** [comment]
@AlexWaygood can I contribute to this? 

Assuming this is the only fix: https://github.com/astral-sh/ruff/commit/a4ea647faf30e73e7237d36f3e5cff3efcaaab54 ?
