### ISSUE TITLE
`PTH201` fix does not consider trailing comma

### ISSUE THREAD

**Issue by InSyncWithFoo** [astral-sh/ruff#15165]
```python
from pathlib import Path

# Before:
_ = Path(".",)
#        ^^^ PTH201

# After:
_ = Path(,)
```

This happens because [the fix is a simple range deletion](https://github.com/astral-sh/ruff/blob/2288cc74789108bdc854f09d813b51662ff4e1d8/crates/ruff_linter/src/rules/flake8_use_pathlib/rules/path_constructor_current_directory.rs#L65-L73):

```rust
let [Expr::StringLiteral(ast::ExprStringLiteral { value, range })] = &*arguments.args else {
    return;
};

if matches!(value.to_str(), "" | ".") {
    let mut diagnostic = Diagnostic::new(PathConstructorCurrentDirectory, *range);
    diagnostic.set_fix(Fix::safe_edit(Edit::range_deletion(*range)));
    checker.diagnostics.push(diagnostic);
}
```

Perhaps it should instead replace `arguments.range` with `()`?

**Comment by MichaReiser** [comment]
We could also just search for a trailing comma using the `checker.tokens` or the `SimpleLexer`. It might also be worth to see if there's an existing helper method for removing an argument

**Comment by dylwil3** [comment]
>It might also be worth to see if there's an existing helper method for removing an argument

There is! It's here:

https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/fix/edits.rs#L207
