### ISSUE TITLE
Ruff format generates code that has an invalid syntax in Python 3.8

### ISSUE THREAD

**Issue by bblommers** [astral-sh/ruff#15181]
If you have a `with` statement with two context managers with fairly long name, running `ruff format` will put them on a separate line:
```
with (
    GenericContextManagerWithAFairlyLongName() as some_volume,
    GenericContextManagerWithAFairlyLongName() as gcm2,
):
```

I don't quite understand why, but this is considered invalid syntax in Python 3.8.

A reproduction can be found here:
https://github.com/bblommers/ruff-py3.8-compat/pull/2

The original source is included in the PR.

The CI workflow formats it using `ruff`, and you can see that the invocation of the original file succeeds - but invoking the formatted file fails in Python 3.7/3.8:

https://github.com/bblommers/ruff-py3.8-compat/actions/runs/12535710649/job/34957895029?pr=2

**Comment by wookie184** [comment]
If you set the target version (https://docs.astral.sh/ruff/settings/#target-version) to 3.8 it should fix this.

Parentheses here are only supported in 3.9+ because the syntax wasn't possible to implement with the old parser (https://peps.python.org/pep-0617/ if you're interested)

**Comment by bblommers** [comment]
Our project does have the `python_requires` metadata set, but in `setup.cfg` instead of in `pyproject.toml` - I guess that's why `ruff` doesn't pick it up.

And TIL about the PEP! It actually specifically mentions this example 🙂

Thank you for the info @wookie184!

**Comment by albertz** [comment]
Just a note: Once Ruff has introduced parenthesized context managers due to wrong configuration, then running Ruff even with correct configuration (fixed target-version in pyproject.toml), it will not change this back. You must manually remove the brackets. But then Ruff will not introduce the brackets again and leave it without.
