### ISSUE TITLE
PIE794 causes behavior change

### ISSUE THREAD

**Issue by spaceone** [astral-sh/ruff#2390]
```
$ ruff --select PIE794 --fix --diff foo.py
--- foo.py
+++ foo.py
@@ -1,3 +1,2 @@
 class foo(object):
     bar = 1 
-    bar = 2

Would fix 1 error.
```

              Yeah that's a reasonable argument. Okay, I'll do another pass on this.

_Originally posted by @charliermarsh in https://github.com/charliermarsh/ruff/issues/1787#issuecomment-1379609301_

**Comment by charliermarsh** [comment]
Closing as we made this a "suggested" fix, so in the future it'll only run with `--fix-unsafe`.
