### ISSUE TITLE
Add Markdown documentation for existing lint rules

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#2646]
If we write documentation on the `#[violation]` macro:

```rust
/// ### What it does
/// Checks for `self.assertRaises(Exception)`.
///
/// ## Why is this bad?
/// `assertRaises(Exception)` can lead to your test passing even if the
/// code being tested is never executed due to a typo.
///
/// Either assert for a more specific exception (builtin or custom), use
/// `assertRaisesRegex` or the context manager form of `assertRaises`.
#[violation]
pub struct NoAssertRaisesException;
```

This explanation shows up with `ruff rule B017`, and in the docs:

- https://github.com/charliermarsh/ruff/blob/main/docs/rules/assert-raises-exception.md
- https://beta.ruff.rs/docs/rules/assert-raises-exception/

We'll track progress here:

- [x] `airflow`
- [x] `eradicate`
- [x] `flake8-2020`
- [x] `flake8-annotations`
- [x] `flake8-async`
- [x] `flake8-bandit`
- [x] `flake8-blind-except`
- [x] `flake8-boolean-trap`
- [x] `flake8-bugbear`
- [x] `flake8-builtins`
- [x] `flake8-commas`
- [x] `flake8-comprehensions`
- [x] `flake8-copyright`
- [ ] `flake8-datetimez`
- [x] `flake8-debugger`
- [x] `flake8-django`
- [x] `flake8-errmsg`
- [x] `flake8-executable`
- [x] `flake8-fixme`
- [x] `flake8-future-annotations`
- [x] `flake8-gettext`
- [x] `flake8-implicit-str-concat`
- [x] `flake8-import-conventions`
- [x] `flake8-logging-format`
- [x] `flake8-no-pep420`
- [x] `flake8-pie`
- [x] `flake8-print`
- [ ] `flake8-pyi`
- [x] `flake8-pytest-style`
- [x] `flake8-quotes`
- [x] `flake8-raise`
- [x] `flake8-return`
- [x] `flake8-self`
- [x] `flake8-simplify`
- [x] `flake8-slots`
- [x] `flake8-tidy-imports`
- [x] `flake8-todos`
- [x] `flake8-type-checking`
- [x] `flake8-unused-arguments`
- [x] `flake8-use-pathlib`
- [x] `flynt`
- [x] `isort`
- [x] `mccabe`
- [x] `numpy`
- [x] `pandas-vet`
- [x] `pep8-naming`
- [x] `perflint`
- [x] `pycodestyle`
- [x] `pydocstyle`
- [x] `pyflakes`
- [x] `pygrep-hooks`
- [x] `pylint`
- [x] `pyupgrade`
- [x] `ruff`
- [x] `tryceratops`

**Comment by spaceone** [comment]
That's very nice!
In the README the rule is linked twice. Once for the code and once fore the human-readable-name. Isn't one link at the humann-readable-name enough? This would enable to double-click/select the rule name into copy&paste buffer instead of opening the link.

**Comment by charliermarsh** [comment]
We could link it once -- I don't feel strongly!

**Comment by charliermarsh** [comment]
(Making a concerted effort to add these for all new rules.)

**Comment by thatlittleboy** [comment]
Hi, I'm looking to do my part in contributing some docs~

**Quick question**: I noticed that in #2796  for example, there is a change to `bare_except.rs` and the OP added `docs/rules/bare_except.md`. Do I have to write the markdown file myself or is it a generated file (since it's largely replicated from the text in `define_violation!` macro)?

**Comment by charliermarsh** [comment]
Thanks! Everything is generated from the rustdoc in the macro, so no need to touch any Markdown. (We actually don’t even check in the generated Markdown anymore, so it won’t appear as part of any PRs — only need to write the rustdoc part, and the rest is taken care of for you when we generate the docs :))

**Comment by JonathanPlasse** [comment]
`try.ceratops` already has documented its rules in its [documentation](https://github.com/guilatrova/tryceratops/tree/main/docs/violations).

**Comment by charliermarsh** [comment]
👍 I'd prefer not to copy over their documentation though, would prefer to write our own. But we can look to theirs for guidance.

**Comment by charliermarsh** [comment]
Amazingly, thanks in large part to @tjkuson, we're now at 381 rules with documentation out of 634 total (> 60% coverage).

**Comment by charliermarsh** [comment]
@tjkuson - FYI I shouted you out on Twitter :)

https://twitter.com/charliermarsh/status/1669139322077847553?s=20

**Comment by tjkuson** [comment]
Aww, thanks! I think static code analysers are an under-appreciated learning resource, so am just happy to help out a bit.

**Comment by harupy** [comment]
I'll take `flake8-raise`.

**Comment by harupy** [comment]
I'll take `flake8-pytest-style`.

**Comment by klistwan** [comment]
I'll take `flake8-datetimez`:

- [x] DTZ001
- [x] DTZ002
- [ ] DTZ003
- [ ] DTZ004
- [ ] DTZ005
- [ ] DTZ006
- [ ] DTZ007
- [ ] DTZ011
- [ ] DTZ012

**Comment by harupy** [comment]
`flake8-pytest-style` is complete!

**Comment by charliermarsh** [comment]
It looks like we're down to 31 rules that lack documentation:

- [ ] `call-with-shell-equals-true`
- [ ] `start-process-with-a-shell`
- [ ] `start-process-with-no-shell`
- [ ] `call-datetime-strptime-without-zone`
- [ ] `call-date-today`
- [ ] `call-date-fromtimestamp`
- [ ] `pass-statement-stub-body`
- [ ] `non-empty-stub-body`
- [ ] `typed-argument-default-in-stub`
- [ ] `pass-in-class-body`
- [ ] `argument-default-in-stub`
- [ ] `assignment-default-in-stub`
- [ ] `duplicate-union-member`
- [ ] `quoted-annotation-in-stub`
- [ ] `docstring-in-stub`
- [ ] `unassigned-special-variable-in-stub`
- [ ] `snake-case-type-alias`
- [ ] `t-suffixed-type-alias`
- [ ] `future-annotations-in-stub`
- [ ] `stub-body-multiple-statements`
- [ ] `no-return-argument-annotation-in-stub`
- [ ] `unannotated-assignment-in-stub`
- [ ] `string-or-bytes-too-long`
- [ ] `numeric-literal-too-long`
- [ ] `pytest-incorrect-fixture-name-underscore`
- [ ] `missing-whitespace`
- [ ] `unexpected-spaces-around-keyword-parameter-equals`
- [ ] `missing-whitespace-around-parameter-equals`
- [ ] `missing-whitespace-after-keyword`
- [ ] `io-error`
- [ ] `syntax-error`
