### ISSUE TITLE
flake8-to-ruff flake8-bugbear opinionated rules

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#3015]
By default `flake8-bugbear` does not activate opinionated rules.
Should `flake8-to-ruff` ignore by default `B9` rules if they are not selected?

The recent issues I opened originate from testing `ruff` against [python/typeshed](https://github.com/python/typeshed) :slightly_smiling_face: .

**Comment by charliermarsh** [comment]
(Closing as we've deprecated `flake8-to-ruff`.)
