### ISSUE TITLE
PT016 recommends deprecated kwarg.

### ISSUE THREAD

**Issue by tobiasraabe** [astral-sh/ruff#3387]
- ruff version: 0.0.254

Hi!

Thanks for the amazing application!

Rule PT016 suggests adding a reason when using `pytest.fail()`, but when using a keyword argument it requires the deprecated `msg` keyword instead of the new `reason` kwarg introduced in v7 (https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.fail).

```python
pytest.fail("reason")  # OK
pytest.fail(msg="reason")  # OK
pytest.fail(reason="reason")  # Error PT016
```

The current behavior is the same as flake8-pytest-style (https://github.com/m-burst/flake8-pytest-style/blob/master/docs/rules/PT016.md), but I do not see a reason to stay with deprecated behavior.

Cheers!

**Comment by charliermarsh** [comment]
Oh interesting! I guess the risk here is that (at least right now) we don't know your `pytest` version, so if you're on a version older than 7, using `reason` might actually be a breaking change.

**Comment by charliermarsh** [comment]
We could make the `pytest` major version configurable.

**Comment by charliermarsh** [comment]
@edgarrmondragon - do you know if Pytest v7 is widely adopted? Are a lot of projects on older versions?

**Comment by edgarrmondragon** [comment]
@charliermarsh Did some quick numbers from the PyPI download stats starting from 2023-01-01 and by that it seems pytest 7 is indeed widely adopted 🙂 

</style>
<table id="T_8cda0_">
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th class="col_heading level0 col0" >downloads</th>
    </tr>
    <tr>
      <th class="index_name level0" >major</th>
      <th class="blank col0" >&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_8cda0_level0_row0" class="row_heading level0 row0" >2</th>
      <td id="T_8cda0_row0_col0" class="data row0 col0" >288,744</td>
    </tr>
    <tr>
      <th id="T_8cda0_level0_row1" class="row_heading level0 row1" >3</th>
      <td id="T_8cda0_row1_col0" class="data row1 col0" >2,076,701</td>
    </tr>
    <tr>
      <th id="T_8cda0_level0_row2" class="row_heading level0 row2" >4</th>
      <td id="T_8cda0_row2_col0" class="data row2 col0" >5,356,972</td>
    </tr>
    <tr>
      <th id="T_8cda0_level0_row3" class="row_heading level0 row3" >5</th>
      <td id="T_8cda0_row3_col0" class="data row3 col0" >8,021,611</td>
    </tr>
    <tr>
      <th id="T_8cda0_level0_row4" class="row_heading level0 row4" >6</th>
      <td id="T_8cda0_row4_col0" class="data row4 col0" >25,819,778</td>
    </tr>
    <tr>
      <th id="T_8cda0_level0_row5" class="row_heading level0 row5" >7</th>
      <td id="T_8cda0_row5_col0" class="data row5 col0" >80,133,528</td>
    </tr>
  </tbody>
</table>
