### ISSUE TITLE
I want ruff to fix `F811` error.

### ISSUE THREAD

**Issue by yuji38kwmt** [astral-sh/ruff#3477]
# Environments

```
$ uname -a
Linux example 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.11.2
$ ruff --version
ruff 0.0.254
```

# What's happened?
I want to fix the following code.

```
import pandas
import pandas
df = pandas.Series(["a", "b", "c"])
```

But ruff did not fix line 1.

```
$ ruff sample.py  --fix --isolated
sample.py:2:8: F811 Redefinition of unused `pandas` from line 1
Found 1 error.
```

# What do I expect?
I expect that ruff fix `F811` error.

**Comment by charliermarsh** [comment]
We used to fix this, but it's not always safe and can be hard to get right. Not in this trivial case, but, e.g., see #2044.

**Comment by yuji38kwmt** [comment]
Thanks! I Got it.

**Comment by charliermarsh** [comment]
I think we should consider fixing these in the event that _both_ are imports.

**Comment by madkinsz** [comment]
I definitely agree these should be fixed if both are imports — in my move from `isort` to `ruff` this is one of the biggest changes to my workflow. For example, when resolving import merge conflicts (which are common) I usually just accept both changes then rely on the linter to resolve duplicate and unused imports.

Does this seem like a straight-forward feature to implement? Happy to give it a go with some guidance.
