### ISSUE TITLE
Add autofixit for B004 

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#3545]
This check seems autofixable with minimal chance of being an incorrect fixit. I would recommend enabling autofixes for this check by using `callable(x)` when possible instead of `hasattr(x, "__call__")`. Should be a good first issue for someone to implement.

**Comment by Skylion007** [comment]
Ah, I just found an edge case that makes this a bit more complex to autofix:
```
  
               func = getattr(self._f, '__call__', self._f.__init__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ B004
    
```
Is also flagged. I am not sure if this is a bug from flake8-bugprone or if it wants us to replace it with
```
               func = self._f if callable(f) else self._f.__init__
```

**Comment by JonathanPlasse** [comment]
We could ignore the complex case.

**Comment by charliermarsh** [comment]
Agreed, we should be able to fix these.

**Comment by glokta1** [comment]
Hi, I'd like to take this up!

**Comment by charliermarsh** [comment]
@glokta1 - Awesome! Please ask me here or on Discord if you have questions.

**Comment by JonathanPlasse** [comment]
How can I join the discord?

**Comment by charliermarsh** [comment]
There's a link in the README! Clicking this should work: https://discord.com/invite/c9MhzV8aU5
