### ISSUE TITLE
[Autofix error] Autofix error with if statement

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#3619]
Ruff  a45753f462c7a53afd7f942ab3c6f9af3871bf1f

```
def _parseline(path: str, line: str, lineno: int) -> tuple[str | None, str | None]:
    if iscommentline(line):
        line = ""
    else:
        line = *line.rstrip()
```
[25633_parse9.py.zip](https://github.com/charliermarsh/ruff/files/11025388/25633_parse9.py.zip)

with 
```
ruff file.py --fix
```

```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `Desktop/RunEveryCommand/Ruff/Broken/17333_parse90.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!
```

**Comment by charliermarsh** [comment]
Is the initial example valid Python? I can't get that to parse under Python 3.11.

**Comment by charliermarsh** [comment]
```❯ python foo.py
  File "/Users/crmarsh/workspace/ruff/foo.py", line 5
    line = *line.rstrip()
           ^^^^^^^^^^^^^^
SyntaxError: can't use starred expression here```

**Comment by qarmin** [comment]
I cannot find original file with this lines.

I tried to run this with several python versions and with each I had parse error, so the problem here is probably with recognizing this file by ruff as valid

**Comment by charliermarsh** [comment]
I think it's an error that Ruff doesn't flag the _original_ source as invalid syntax.

**Comment by qarmin** [comment]
Such files I reported upstream - https://github.com/RustPython/Parser/issues/66

**Comment by charliermarsh** [comment]
I'm going to close this one in favor of the RustPython issue.
