### ISSUE TITLE
Support an allowlist of function calls in argument defaults for B008

### ISSUE THREAD

**Issue by rouge8** [astral-sh/ruff#3762]
It would be great if B008 supported an allowlist of function calls, similar to `extend-immutable-calls` for B006. We do a lot of this in our code which as far as I know has no subtle bugs:

```python
def f(x=Decimal("1000")):
    pass
```

Or maybe it's worth hardcoding `Decimal` as an exception?

**Comment by charliermarsh** [comment]
Yeah perhaps we add that to the list of `IMMUTABLE_FUNCS` in `crates/ruff/src/rules/flake8_bugbear/rules/function_call_argument_default.rs`.

**Comment by JonathanPlasse** [comment]
It could be a good first issue.

**Comment by rouge8** [comment]
> Yeah perhaps we add that to the list of `IMMUTABLE_FUNCS` in `crates/ruff/src/rules/flake8_bugbear/rules/function_call_argument_default.rs`.

I think it's probably worth doing that and adding an allowlist. Looking at our codebase, we have some custom functions we'd want to allow while still benefiting from flagging this in general.

**Comment by rouge8** [comment]
Okay, I opened https://github.com/charliermarsh/ruff/pull/3764 adding a few more immutable functions. I can work on another PR adding a setting if you're open to that!

**Comment by rouge8** [comment]
Oh wait, reading the code, it looks like B008 might already support `extend-immutable-calls`?

**Comment by charliermarsh** [comment]
Oh wait, you're right...

**Comment by rouge8** [comment]
Hmm and I don't see it used in https://github.com/charliermarsh/ruff/blob/main/crates/ruff/src/rules/flake8_bugbear/rules/mutable_argument_default.rs ? Is the doc saying it's used for B006 wrong and it's actually used for B008?

**Comment by charliermarsh** [comment]
Yeah something's a bit off between these.

**Comment by aberres** [comment]
@rouge8 `pathlib.Path` is another candidate. See https://peps.python.org/pep-0428/#immutability

**Comment by rouge8** [comment]
> @rouge8 `pathlib.Path` is another candidate. See https://peps.python.org/pep-0428/#immutability

Good catch! Added it in https://github.com/charliermarsh/ruff/pull/3794

**Comment by JonathanPlasse** [comment]
Why not `(Pure)(Posix|Windows)Path` too?

**Comment by Apakottur** [comment]
So at this point should it be possible to use `extend-immutable-calls` for B008?
I have the following code:
```python
# test.py
from typing import TypeAlias

MyTypeAlias: TypeAlias = str

def func(
    x: str = str("default"),
    y: str = MyTypeAlias("default"),
):
    return x + y
```
```toml
# ruff.toml
[flake8-bugbear]
extend-immutable-calls = ["MyTypeAlias"]
```

And running `ruff check --config ruff.toml --select B008 test.py` still gives me:
```shell
test.py:9:14: B008 Do not perform function call `MyTypeAlias` in argument defaults
Found 1 error.
```

**Comment by charliermarsh** [comment]
It should work for B008 if you use a fully-qualified path to the symbol, rather than the string name. For example:

```toml
[flake8-bugbear]
extend-immutable-calls = ["path.to.module.MyTypeAlias"]
```

Unfortunately, that won't work for symbols defined in the file in which they're used -- they have to be imported from another file. It's just a limitation which we'll resolve eventually (#5486).

**Comment by charliermarsh** [comment]
Unrelatedly, looking back at this issue, I see a few touch-ups we can do:

- B008 could ignore arguments with immutable annotations.
- B006 could consider `extend_immutable_calls` when determining whether an annotation is immutable.

**Comment by zanieb** [comment]
`B008` already supports this so I'm going to close this issue.

I've also added the improvements that Charlie suggested in #6781 and #6784
