### ISSUE TITLE
Inconsistent results running ruff via `poetry` and `pre-commit`

### ISSUE THREAD

**Issue by ghost** [astral-sh/ruff#3781]
I have ruff set up in my (monorepo's) `.pre-commit-config.yaml`, and this runs and I see a bunch of problems! Yay? For instance:

``` shell
% pre-commit run --files app/tools.py
# bunch of junk
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

projects/role_explorer/app/tools.py:65:21: PLR2004 Magic value used in comparison, consider replacing 365 with a constant variable
projects/role_explorer/app/tools.py:71:34: ANN401 Dynamically typed expressions (typing.Any) are disallowed in `v`
```
Sweet! But! I'm also trying to make sure I'm not too startled by large problems that ruff finds, so I try this:
``` shell
% poetry run ruff check app/tools.py ; and echo "wat" # I use fish
wat
```
huh? I would expect `ruff` in both cases to act identically.

If I dump the config with `--show-settings` I see all my changes from my `pyproject.toml`, but they're seemingly ignored when I run ruff? I'm really confused here.

Thanks? Thoughts?

**Comment by charliermarsh** [comment]
Is this in a public repo? Not obvious to me what’s going on but happy to debug.

**Comment by charliermarsh** [comment]
Aw man, you probably fell victim to one of the edge cases in configuration, which is that there are a few `pyproject.toml` fields that are only respected when you run from the current directory (`fix-only`, fix`, maybe one or two others). All other fields work as expected regardless of where you invoke Ruff from.
