### ISSUE TITLE
Extend SLF001 to allow accessing private fields on "other" instance in binary operators?

### ISSUE THREAD

**Issue by tpgillam** [astral-sh/ruff#3933]
Suppose I run the follow code through ruff with the `SLF` module enabled, with Ruff 0.0.256:

```python
class Moo:
    def __init__(self, a: int):
        self._a = a

    def __eq__(self, other) -> bool:
        return isinstance(other, Moo) and self._a == other._a
```

Currently the last line will trigger `SLF001: private member access`, specifically the `other._a` call.

Since this is a fairly common pattern (and also within other binary operations, e.g. addition, multiplication), arguably it would be nice if this were permitted without a `# noqa` (*).

Is this something that could be addressed within Ruff? Or is the policy to first decide changes inside flake8-self, and then ensure that Ruff always replicates upstream exactly?

If it _were_ something that could be addressed within Ruff I'm not sure the best approach to implement it. It seems as though the current implementation relies on the string `"self"` being used, as opposed to noting what `self` would have been bound to given its position in the argument list to the method. A generalisation to the latter method could presumably also tag the _second_ object in e.g. `__eq__, __add__, __radd, ...` as "allowed to access private members"

(*) At least, everywhere I have worked has preferred this approach, as opposed to e.g. explicitly publicising any necessary internal state via properties.

**Comment by charliermarsh** [comment]
I'm torn on this but find myself erring on the side of "it's a reasonable thing to expect" (that we wouldn't enforce `SLF` here).

We may be able to handle it in the common case with our current semantic analysis tools.

**Comment by nickbutsky** [comment]
Is there any reason why it would only be allowed in dunder methods?
