### ISSUE TITLE
ruff sometimes removes raw strings

### ISSUE THREAD

**Issue by MikulasZelinka** [astral-sh/ruff#4130]
Ruff (sometimes) turns `r"^.:\\Users\\[^\\]*\\Downloads\\.*"` into `"^.:\\\\Users\\\\[^\\\\]*\\\\Downloads\\\\.*"` which I believe is a bug.

Specifically, this happens (at least) when `not (<something_with_a_raw_string>) is None` is on the input.

```
❯ ruff --version
ruff 0.0.262
```

Using no config, all defaults.

Minimal reasonable reproduction:

```
❯ cat fmt_test.py
import re

# r not removed:
re.search(r"^.:\\Users\\[^\\]*\\Downloads\\.*") is not None
# r removed:
not (re.search(r"^.:\\Users\\[^\\]*\\Downloads\\.*") is None)

```

```
❯ ruff fmt_test.py --diff
--- fmt_test.py
+++ fmt_test.py
@@ -3,4 +3,4 @@
 # r not removed:
 re.search(r"^.:\\Users\\[^\\]*\\Downloads\\.*") is not None
 # r removed:
-not (re.search(r"^.:\\Users\\[^\\]*\\Downloads\\.*") is None)
+re.search("^.:\\\\Users\\\\[^\\\\]*\\\\Downloads\\\\.*") is not None

Would fix 1 error.
```

And this is an ultra minimal reproduction:

`not r"\\" is None` turns into `"\\\\" != None`

**Comment by charliermarsh** [comment]
👍 (Internal note: this is a limitation of `Stylist`. Raw strings aren't captured in the AST, so we end up removing them.)

**Comment by addisoncrump** [comment]
Of note: the `parser_idempotency` fuzzer finds this bug, but I haven't been reporting these issues since the idempotency didn't seem to be a strong guarantee.
