### ISSUE TITLE
Consider adding an inverse of `D200`

### ISSUE THREAD

**Issue by CobaltCause** [astral-sh/ruff#4174]
`D200` enforces that single-line docstrings must fit on a single line. Personally, I prefer `D213` over `D212`, and so `D200` will cause unnecessary diffs when a description is added. I'd like a lint that enforces that docstrings are *always* multiline to reduce this noise and keep things consistent.

**Comment by charliermarsh** [comment]
I'm going to deprioritize this for now. I understand the use-case, and it's definitely not unreasonable, but I don't want to deviate from the pydocstyle hierarchy right now.
