### ISSUE TITLE
[feature] Differentiate between safe and unsafe fixes

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#4181]
This task tracks the work implementing safe and unsafe fixes as described in #1997. 

*Safe* fixes are fixes that don't change the semantics of the program. *Unsafe* fixes may change the program's semantics; therefore, we advise users to manually review and test the changes.

## Tasks 

* [x] #4182
* [x] #4183
* [x] #4340
* [ ] #4276
* [x] #4184
* [x] #4185
* [ ] #4186
* [x] #4187

**Comment by evanrittenhouse** [comment]
@MichaReiser You can assign this to me, I'd like to take it to completion!

**Comment by MichaReiser** [comment]
> @MichaReiser You can assign this to me, I'd like to take it to completion if it's open!

Hey @evanrittenhouse. Do you plan to work on all of it or individual sub-tasks?

**Comment by MichaReiser** [comment]
@zanieb should we close this issue? I'm okay deferring the add "message to fix" for now as it also is somewhat unrelated to the applicability work.
