### ISSUE TITLE
Respect `Applicability` in LSP

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#4186]
This task is part of #4181 and it depends on #4183 and #4185

* Double check if we need to change the LSP fix command to use `--fix-unsafe` when applying a code fix. 
* Change the `fixAll` action handler to only apply safe fixes by default
* Introduce a new option to also run unsafe fixes as part of `fixAll`

**Comment by zanieb** [comment]
Discussed more at https://github.com/astral-sh/ruff/issues/6962#issuecomment-1696845966

**Comment by dhruvmanila** [comment]
Additionally, would having `unsafe-fixes = true` in the config mean that the `fixAll` code action _includes_ them?

**Comment by zanieb** [comment]
Yes, I think it should.

**Comment by charliermarsh** [comment]
I think applicability is now respected in the LSP but @zanieb correct me if I'm wrong.
