### ISSUE TITLE
[Autofix error] C408 - unnecessary-collection-call - syntax error when fixing within f-string

### ISSUE THREAD

**Issue by Hnasar** [astral-sh/ruff#4249]
Presumably replacing `dict()` with `{}` gets confused when inside an f-string when it comes to using `"` vs `'` (or maybe it's the nested `{`)

```python
# test.py
f"{dict(x='y')}"  # should turn into f"{{'x': 'y'}}"
```

```
$ ruff --select=C408 test.py  --fix

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `test.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

test.py:1:4: C408 Unnecessary `dict` call (rewrite as a literal)
```

Using ruff 0.0.264

**Comment by charliermarsh** [comment]
Good call, thanks!

**Comment by charliermarsh** [comment]
(We track `in_f_string`, so we should just avoid triggering this rule, and perhaps some others in this category, when `in_f_string` is `true`.)

**Comment by dhruvmanila** [comment]
I think it's the braces and not the quotes as the quotes are taken as is. So, this should be avoided in `dict` and `set` comprehensions.

**Comment by akx** [comment]
Maybe the heuristics in the new `ruff::rules::flynt::helpers::to_fstring_elem` function could be of more generic use here :)

**Comment by DavideCanton** [comment]
I can work on it if nobody else wants to
