### ISSUE TITLE
RUF009 false positive for descriptor fields

### ISSUE THREAD

**Issue by nstarman** [astral-sh/ruff#4451]
Dataclasses permit descriptor fields (https://docs.python.org/3.10/library/dataclasses.html#descriptor-typed-fields) but RUF009 is complaining about function calls at class construction. This is similar to https://github.com/charliermarsh/ruff/issues/4091, but I think sufficiently different to merit its own issue.

**Comment by JonathanPlasse** [comment]
You can use [flake8-bugbear.extend-immutable-calls](https://beta.ruff.rs/docs/settings#extend-immutable-calls) to set your descriptor as immutable.
You can find this option in the rule documentation [function-call-in-dataclass-default-argument](https://beta.ruff.rs/docs/rules/function-call-in-dataclass-default-argument/)

The documentation could be explicit on the possibility to mark a call as immutable.

**Comment by charliermarsh** [comment]
That's almost certainly the "best we can do" for now, until we can reliably detect that a class is a descriptor across files.

**Comment by JonathanPlasse** [comment]
Ruff did not have the type checking necessary to do this now.

**Comment by charliermarsh** [comment]
We might be able to do it based on references though, even without type-checking. In the linked example, if the file were `src/foo.py`, we could certainly detect that references within that file to `IntConversionDescriptor` are `foo.IntConversionDescriptor`.

**Comment by JonathanPlasse** [comment]
@charliermarsh, should we add a tag for issues that could be improved with type checking ability?
It would facilitate finding what should be changed when we add the type checker.

**Comment by charliermarsh** [comment]
Yeah, we have an existing tag -- just added it.
