### ISSUE TITLE
Should `__main__.py` really be considered a public module?

### ISSUE THREAD

**Issue by CobaltCause** [astral-sh/ruff#4489]
Reading [this](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages), I wouldn't think so; it seems to imply that nothing should be defined in that file and then imported elsewhere. Yet, `ruff` will give me such errors as `D100 Missing docstring in public module` in `__main__.py`, which I found surprising. I'm not entirely certain which behavior is correct, though.

**Comment by tjkuson** [comment]
I would add that it also seems to flag missing docstrings for `__init__.py` which I don't like for the reason above. I usually ignore this rule for that reason, but perhaps it should be considered a false positive too.

**Comment by JonathanPlasse** [comment]
According to `pydocstyle` [implementation](https://github.com/PyCQA/pydocstyle/blob/07f6707e2c5612960347f7c00125620457f490a7/src/pydocstyle/parser.py#L157-L185), `__main__.py` is public.

**Comment by CobaltCause** [comment]
Looking at `git blame`, that code hasn't been touched since 2020-09-05. Clicking through the version history on the page I linked in the issue description, `__main__.py` was added in Python 3.10 which was released on 2021-10-04. So I think `pydocstyle` simply doesn't account for this, since that code was written before this feature existed. Maybe I should open an issue over there as well?

**Comment by charliermarsh** [comment]
Thanks :)

**Comment by charliermarsh** [comment]
I'm gonna close for now to keep the issue tracker actionable.

**Comment by CobaltCause** [comment]
Looks like pydocstyle was deprecated in favor of ruff somewhat recently
