### ISSUE TITLE
[Autofix error] RUF001 autofix fails for `a = "丶"`

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#4519]
The RUF001 autofix replace

```
a = "丶"
```

with

```
a = "\"
```

which is a syntax error. For some reason ruff doesn't realize this is a syntax error, so you need e.g. `--select RUF001,UP025` to get a syntax error displayed.

Command:

```shell
target/debug/ruff --no-cache --select RUF001 --fix a.py
```

ruff version fd16d658e9407ce76bc38cd8f5112dd272fc5be0

This was originally discovered in https://github.com/bolucat/Firefox/blob/43f773cc70d6bc6322c2f085fa360957d7916bdb/third_party/python/idna/idna/uts46data.py

**Comment by charliermarsh** [comment]
I think it's because this doesn't go through the AST checker, so we don't attempt to re-parse.

**Comment by charliermarsh** [comment]
At the very least we should be checking if the replacement character is syntactically relevant within strings (a quote, a backslash... maybe some others).

**Comment by qarmin** [comment]
So is this still relevant after https://github.com/astral-sh/ruff/pull/7168 ?

**Comment by charliermarsh** [comment]
No, thanks for noticing!
