### ISSUE TITLE
Autofix B006 (mutable-argument-default)

### ISSUE THREAD

**Issue by auscompgeek** [astral-sh/ruff#4693]
B006 could have an autofixer to instead make the default `None` and check if it is `None` within the function.

[pybetter](https://github.com/lensvol/pybetter#readme) includes a fixer for this:

<blockquote>

**Default values for `kwargs` are mutable.**

As described in [Common Gotchas](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) section of "The Hitchhiker's Guide to Python", mutable arguments can be a tricky thing. This fixer replaces any default values that happen to be lists or dicts with None value, moving initialization from function definition into function body.

```python
# BEFORE
def p(a=[]):
    print(a)

# AFTER
def p(a=None):
    if a is None:
        a = []
    
    print(a)
```

Be warned, that this fix may break code which _intentionally_ uses mutable default arguments (e.g. caching).

</blockquote>

This _may_ want to also autofix the type hint to be `Optional` if there is one.

**Comment by qdegraaf** [comment]
I'll give this one a go
