### ISSUE TITLE
Writing lint output to file

### ISSUE THREAD

**Issue by TalAmuyal** [astral-sh/ruff#4754]
**TL;DR:** I couldn't find how to tell Ruff to write the report to file.

**Examples:**
- `bandit` -> `--output=reports/report.txt`
- `flake8` -> `--output-file=reports/report.txt`
- `pylint` -> `--output-format=text:reports/report.txt`

**Motivation:**

I'm using Ruff with [Pants](https://www.pantsbuild.org/docs/python-linters-and-formatters).
Pants parallelises Ruff's run for monorepos.
In general, it runs linters in a sandbox, collects their reports and puts them in `dist/[linter]/...` which can then be used by Jenkins to display the results to the user.

**Comment by charliermarsh** [comment]
Naive question, but what's the difference between an `--output-file` argument and `ruff > report.txt`?

**Comment by TalAmuyal** [comment]
The issue with that is it requires to add a shell (e.g bash) between `ruff` and the process that invokes it.

Currently, I'm running Pants which runs Ruff, rather than running a Bash script or Make that then runs Ruff.

**Comment by TalAmuyal** [comment]
To be clear, I really appreciate your work and the fast response, and I submit this as a question or a feature-request.
If the above is perceived as offensive in any way, please know that it is unintentional and that I'm extremely grateful and do not take this work or your time for granted.

**Comment by charliermarsh** [comment]
No worries at all, I appreciate the kind words, and I didn't take it as offensive in any way -- it's a super reasonable request! I just wanted to understand the context to make sure I could probably evaluate whether it's a worth supporting as a new CLI option. It does seem reasonable to me -- any reactions, @MichaReiser?

**Comment by MichaReiser** [comment]
@TalAmuyal do you know how other tools handle this that you use in your pants stack?

**Comment by TalAmuyal** [comment]
In `pants.toml`, the following needs to be added for Pylint:
```toml
# pants.toml

[pylint]
args = ["--output-format=text:reports/report.txt"]
```

Then, Pants adds `--output-format=text:reports/report.txt` as an argument to Pylint when it is executed.
After Pylint completes its execution, Pants collects the files under `reports/` (only `report.txt` in this example) and puts them in `dist/pylint/` (or under `dist/flake8/` etc.).

I imagine that for Ruff it will be something like:
```toml
# pants.toml

[ruff]
args = ["--format=junit", "--report-path=reports/report.xml"]
```

Does this answer your question?

**Comment by TalAmuyal** [comment]
Should I close this issue and sum it up in https://github.com/charliermarsh/ruff/issues/995?

**Comment by MichaReiser** [comment]
Seems reasonable. `rustc` provides the `-o` option

>  -o FILENAME         Write output to <filename>

**Comment by dhruvmanila** [comment]
Yes, I think `-o`/`--output-file` flags are reasonable. I can take this up.

Some observations about what `eslint` does in various scenarios:
1. `eslint --fix --format=junit --output-file=eslint.out .` - This will write the fixed content back to the original files and remaining diagnostics will be written to the output file in the specified format.
2. `eslint --fix-dry-run --format=junit --output-file=eslint.out .` - The dry run doesn't produce any output so the only output is the remaining diagnostics _if_ the fixes were applied.
3. `eslint --format=stylish --output-file=eslint.out .` - This will write the stylish output in the file which includes the [ASCII escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) as well.

For Ruff, I think we should default to `NO_COLOR=1` in case we're writing the output to a file avoid creating confusion when that file is viewed/parsed.
