### ISSUE TITLE
Autofix ISC001 (single-line-implicit-string-concatenation)

### ISSUE THREAD

**Issue by tkukushkin** [astral-sh/ruff#4829]
ISC001 could have an autofixer. It can be difficult to combine strings of different kinds, but it shouldn't be difficult to combine strings of the same kind, so, IMHO, it would be ok to fix only such cases.

**Comment by saippuakauppias** [comment]
Totally agree, autofix could make it easier to fix this kind of code

**Comment by tkukushkin** [comment]
Trying to write autofixer by myself
