### ISSUE TITLE
v0.0.271 pipeline failing on homebrew

### ISSUE THREAD

**Issue by ColemanDunn** [astral-sh/ruff#4946]
Not sure if this belongs here but [the pipeline is failing](https://github.com/Homebrew/homebrew-core/pull/133013) thus my brew and pre-commit versions are out of sync (select = ["ALL"] user here). I have since uninstalled homebrew and installed using pipx. just FYI

**Comment by madkinsz** [comment]
It looks like this is because they need to upgrade to the latest version of Rust still https://github.com/Homebrew/homebrew-core/pull/132584

**Comment by charliermarsh** [comment]
Thank you so much @chenrui333.
