### ISSUE TITLE
Feature: Exporting report to a file

### ISSUE THREAD

**Issue by victorcrrd** [astral-sh/ruff#4965]
I'm wondering if it's possible to export the generated report to a file given as an option to the command? Something like `ruff check --format json --output report.json .` I have seen nothing like that reading the docs.
If not, is it already an idea to implement in the future? Would you accept contributions to add that feature?

**Comment by JonathanPlasse** [comment]
- There is a PR open #4950

**Comment by victorcrrd** [comment]
Thank you! I'm closing the issue then :)
