### ISSUE TITLE
Format `Constant::Ellipsis`

### ISSUE THREAD

**Issue by evanrittenhouse** [astral-sh/ruff#4987]
From https://github.com/astral-sh/ruff/issues/4798

**Comment by evanrittenhouse** [comment]
@MichaReiser can you please assign this to me? Interested in moving into the formatter

**Comment by MichaReiser** [comment]
I'll be off next week, but you can reach out to @konstin with questions.

**Comment by evanrittenhouse** [comment]
@konstin Hey, just going through the code for this. I'm curious why [this line](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/src/expression/expr_constant.rs#L22) doesn't already format `Constant::Ellipsis`? Happy to implement the issue, but not sure what else has to be done.

**Comment by charliermarsh** [comment]
From my perspective, it does look complete, but I’ll let Konsti chime in.

**Comment by konstin** [comment]
Sorry, that was already implemented, i updated #4798 now

**Comment by evanrittenhouse** [comment]
All good, we can probably close this
