### ISSUE TITLE
Format `Await`

### ISSUE THREAD

**Issue by evanrittenhouse** [astral-sh/ruff#4988]
From https://github.com/astral-sh/ruff/issues/4798

**Comment by evanrittenhouse** [comment]
@MichaReiser can you please assign this to me? Interested in moving into the formatter

**Comment by evanrittenhouse** [comment]
Shoot, this one also looks like it's [done](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/src/expression/expr_await.rs), right? :D

**Comment by charliermarsh** [comment]
Oh, maybe >.<
