### ISSUE TITLE
ruff_textwrap accepts illegal Python whitespace

### ISSUE THREAD

**Issue by addisoncrump** [astral-sh/ruff#4991]
Python does not consider `U+00a0` to be whitespace, but this character *is* whitespace according to Rust's `trim_start` (which uses Unicode character classes): https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start

In addition, Rust's str::len() method returns the length in _bytes_, not in characters. This combination can lead to a confusion in ruff_textwrap: https://github.com/astral-sh/ruff/blob/main/crates/ruff_textwrap/src/lib.rs#L95

This issue potentially indicates incorrect processing of leading whitespace in ruff_textwrap::dedent. For example, the mixing of tabs and spaces, the use of non-ASCII whitespace, etc. will be misprocessed by dedent currently.

----

#### How this was discovered

Since trim_start removes UTF-8 whitespace, `U+00a0` used as leading whitespace leads to a panic if an odd number of single-byte whitespace (e.g., space) characters are used as leading whitespace later. The [string slicing](https://github.com/astral-sh/ruff/blob/main/crates/ruff_textwrap/src/lib.rs#L117) attempts to slice between UTF-8 code points because `prefix_len` is computed by number of bytes, not in characters.

Here is a reproducing (illegal python syntax, don't pay attention to that) file which triggers this behaviour: [illegal-whitespace.txt](https://github.com/astral-sh/ruff/files/11710187/illegal-whitespace.txt)

**Comment by charliermarsh** [comment]
Thank you!

**Comment by addisoncrump** [comment]
Looks like this was a potentially incomplete fix; I am still able to trigger this behaviour. See this line: https://github.com/astral-sh/ruff/blob/main/crates/ruff_textwrap/src/lib.rs#L117

**Comment by charliermarsh** [comment]
I'm confused, I fixed that and added a test all in that same PR, but somehow it didn't end up in the diff on GitHub? Operator error somewhere.
