### ISSUE TITLE
Ruff nested min max PYLW3301 autofix bug?

### ISSUE THREAD

**Issue by Ryang20718** [astral-sh/ruff#5066]
ruff version 0.0.272

```
print(min(1, 2, 3, min(4)))
```

With pylint warning enabled, ruff check --fix on this file causes autofix to return
```
print(min(1, 2, 3, *4))
```

**Comment by charliermarsh** [comment]
Hmm, but `min(4)` is not valid either? If you provide a single argument to `min`, I believe it has to be iterable.

**Comment by Ryang20718** [comment]
ah you're right, I always ran ruff before actually running the code. 😭 I'm just being dumb

**Comment by charliermarsh** [comment]
No worries, I had to check it myself too :joy:
