### ISSUE TITLE
Consider `--fix-dry-run`

### ISSUE THREAD

**Issue by evanrittenhouse** [astral-sh/ruff#5081]
While implementing #4181, I saw [this comment](https://github.com/astral-sh/ruff/blob/main/crates/ruff_cli/src/lib.rs#L201) which mentions the implementation of `--fix-dry-run`. Is that something that we'd like to do? If so, how should the generated fixes be outputted? We could probably just use `TextEmitter` to write it to a file

P.S. Is adding labels permissions-restricted? I don't seem to be able to tag it

**Comment by charliermarsh** [comment]
Hmm, I don't think this is relevant anymore, since we now _always_ generate fixes -- so there's no difference between `--fix-dry-run` and the default behavior.

**Comment by charliermarsh** [comment]
(Gonna clean this up real quick...)
