### ISSUE TITLE
Ruff fails to detect nonsensical list index

### ISSUE THREAD

**Issue by dgjustice** [astral-sh/ruff#5082]
`ruff` is an awesome project! :heart: I saw this in the wild today on a PR to fix a bug that passed through CI (with `ruff check`).

## Python source code

The developer accidentally deleted the dict variable during a refactor resulting in something structurally identical to this:

```python
foo = ["abc"]["def"]
```

## Ruff check

```shell
$ cat foo.py 
foo = ["abc"]["def"]

$ python foo.py 
/home/djustice/tmp/foo.py:1: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  foo = ["abc"]["def"]
Traceback (most recent call last):
  File "/home/djustice/tmp/foo.py", line 1, in <module>
    foo = ["abc"]["def"]
TypeError: list indices must be integers or slices, not str

$ ruff check foo.py


$ echo $status
0

```

## Ruff version

```shell
$ ruff --version
ruff 0.0.264

$
```

**Comment by charliermarsh** [comment]
I think this is reasonable but we can probably only support literals. This blog post from Adam Johnson is a good explanation of the rule and what we could support: https://adamj.eu/tech/2020/06/21/why-does-python-syntaxwarning-saying-list-indices-must-be-integers-or-slices/.
