### ISSUE TITLE
🐢 `.ruff_cache` directory has a huge size and it slows down PyCharm load

### ISSUE THREAD

**Issue by saippuakauppias** [astral-sh/ruff#5132]
After checking with all linters of a large project - the directory `.ruff_cache` has a large size and a huge number of files inside. The first load of PyCharm slows down at the stage of indexing all the files.

The volume of lines in all files:
```
$ ( find src apps -name '*.py' -print0 | xargs -0 cat ) | wc -l
  979136
```

Cache directory size:
```
$ du -h .ruff_cache
1,5G	.ruff_cache/content
1,5G	.ruff_cache
```

Number of files in the cache directory:
```
ls -1 .ruff_cache/content | wc -l
  319586
```

As a quick fix, I excluded directory `.ruff_cache` using the context menu: «Mark Directory as -> Excluded».

But it doesn't seem to be ok if the cache doesn't clear itself.

PS: MacBook Pro Intel Core i9 with SSD

**Comment by charliermarsh** [comment]
Thanks for this. Coincidentally, we're actually working on the cache a bit now (\cc @Thomasdezeeuw). It has a couple significant problems. (You can always run `ruff clean` to remove all caches recursively, though it's not self-cleaning.)

**Comment by KotlinIsland** [comment]
> As a quick fix, I excluded directory .ruff_cache using the context menu: «Mark Directory as -> Excluded».
> 
> But it doesn't seem to be ok if the cache doesn't clear itself.

As far as I know, this is the recommended solution. Can you elaborate on what you mean by "But it doesn't seem to be ok if the cache doesn't clear itself."?

**Comment by saippuakauppias** [comment]
I meant that it would be good if ruff itself would periodically check the directory with the cache at the time of the check and automatically delete old files (for example, those that were created earlier than 7 days ago).

Maybe we should rework the caching system itself, because it is not normal to have so many files, don't forget that a disk has inodes.

**Comment by charliermarsh** [comment]
#5117 will fix that -- it changes to a single cache file per package.

**Comment by saippuakauppias** [comment]
By the way, in principle, if in the directory is formed such a large number of files - it is not normal. The directory listing will be slow.

Usually, if the cache is stored on disk - try to spread it over N directories inside, so that each directory has a limited number of files.

**Comment by Thomasdezeeuw** [comment]
Should fixed by https://github.com/astral-sh/ruff/pull/5120.
