### ISSUE TITLE
DJ008 in model type stub is incompatible with PYI029

### ISSUE THREAD

**Issue by federicobond** [astral-sh/ruff#5138]
When a Django model type stub contains a `__str__` method, ruff complains about PYI029.

```
PYI029 [*] Defining `__str__` in a stub is almost always redundant
```
The autofix though triggers a DJ008:
```
DJ008 Model does not define `__str__` method
```

Given that DJ008 is about providing an override implementation for the default model `__str__` method, it probably does not make sense to enforce DJ008 in .pyi stub files.

**Comment by charliermarsh** [comment]
Good call -- I will fix this real quick.

**Comment by federicobond** [comment]
Wow, that's fast! Thank you.

**Comment by charliermarsh** [comment]
No problem, thanks for reporting. I may cut a release tomorrow, but otherwise it'll go out some time early next week.
