### ISSUE TITLE
RUF013: unproper handling of quotes around annotations

### ISSUE THREAD

**Issue by Alexerson** [astral-sh/ruff#5231]
The new rule RUF013 doesn’t properly handle string annotations.

I would expect the following to be fine:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime

def last_value(timestamp: 'datetime | None'=None) -> float ...
```

but with the latest version, I get: ``RUF013 [*] PEP 484 prohibits implicit `Optional` `` and the `--fix` version will replace it by:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime

def last_value(timestamp: 'datetime | None' |None=None) -> float ...
```
which is not valid and will give me:
`TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'`

**Comment by charliermarsh** [comment]
Thank you.

**Comment by charliermarsh** [comment]
I’ll fix this and include it in tonight’s release.

**Comment by Alexerson** [comment]
Thanks, it’s very appreciated!
