### ISSUE TITLE
formatter: capture more comment info in placement.rs

### ISSUE THREAD

**Issue by davidszotten** [astral-sh/ruff#5247]
Hi,

it seems to me we have a bunch of information available (or calculated) in the various helpers in `comments/placement.rs` that we have to throw away that could be handy to use instead of having to e.g. re-figure out where each dangling comment should be attached in `fmt_fields` implementations. i wonder if we could capture it somehow and make available

**Comment by MichaReiser** [comment]
Yeah. I think that could ease the implementation of `fmt_fields`. 

Something I had in mind but never implemented is that we could *label* `SourceComments`. A label could either be an enum or a struct similar to the `LabelId` in the formatter

https://github.com/astral-sh/ruff/blob/046becffee3d928b2470726f320091c4a72b5829/crates/ruff_formatter/src/format_element/tag.rs#L238-L267

What is important in my view is that the label is just a marker. Meaning, it shouldn't hold any additional information beyond what type of comment it is. 

Whether it is more expensive to store the label or just re-compute the information in the formatter is hard to say. We would probably need to do some profiling to figure that out.

**Comment by cnpryer** [comment]
> We would probably need to do some profiling to figure that out

I apologize if I haven't seen it yet, but is this figured out? I'd love to help where I can with internal design changes like this, even if its peripheral.

Is there something I can do to help with establishing some benchmarking/profiling tools for the formatter?

**Comment by MichaReiser** [comment]
> > We would probably need to do some profiling to figure that out
> 
> I apologize if I haven't seen it yet, but is this figured out? 

No, we haven't further investigated this. Feel free to take a stab at it.

> Is there something I can do to help with establishing some benchmarking/profiling tools for the formatter?

Our formatter has a few benchmarks. 

https://github.com/astral-sh/ruff/blob/main/crates/ruff_benchmark/benches/formatter.rs

I picked the test files rather arbitrarily. I mainly tried to have files of different sizes and some that use typing. But that's it. I e.g. didn't check if they contain comments or deeply nested expressions. 

You can read about how to run the benchmarks in our [contribution documentation](https://github.com/astral-sh/ruff/blob/main/CONTRIBUTING.md#benchmarking-and-profiling) or you may decide to add a new benchmark. 

The first thing I would probably do is to add the new `Label` field to `SourceComment` and `CommentPlacement` to see how much this impacts performance. Maybe together with adding a new benchmark test file that has a fair amount of comments. This should allow us to measure the overhead of adding the label with relatively little work. 

The next step would be to refactor the existing placement logic (and formatter rules) to use the labels instead.

**Comment by MichaReiser** [comment]
While useful, it seems that we managed to implement all formatting without. I'm closing this for now as it is unplanned. Feel free to open a new issue if you're interested in contributing this infrastructure change.
