### ISSUE TITLE
Shadowed variable incorrect report - F821 Undefined name

### ISSUE THREAD

**Issue by eddyashton** [astral-sh/ruff#5250]
Started getting a ruff failure from `0.0.273` (still present in `0.0.274`), which wasn't present in `0.0.272`. Believe the source is valid (though ugly) Python, and the ruff failure is incorrect.

Given this file:

```python
# tmp.py
list = [1, 2, 3]

for e in list:
    if e % 2 == 0:
        try:
            pass
        except Exception as e:
            pass
    else:
        print(e)
```

Old:
```
$ pip install ruff==0.0.272
...

$ ruff check tmp.py

$ echo $?
0
```

New:
```
$ pip install ruff==0.0.273
...

$ ruff check tmp.py
tmp.py:10:15: F821 Undefined name `e`
Found 1 error.

$ echo $?
1
```

The shadowing/reuse of `e` is risky, but (afaict) `e` is unambiguously defined at the line where `ruff` complains.

**Comment by eddyashton** [comment]
Looks like this is also reported in #5249 - feel free to close this as dupe if its tracked there.

**Comment by charliermarsh** [comment]
Thanks — gonna close as a dupe, but appreciate the clear issue and example.

(I do recommend against shadowing variable names with caught exceptions but agree we shouldn’t flag this.)
