### ISSUE TITLE
Include newly added rules in changelog

### ISSUE THREAD

**Issue by namurphy** [astral-sh/ruff#5266]
## Proposed change

Add a section in the changelog of each release on which rules have been added since the previous release.

If there already exists such a list that I missed, it would be helpful to increase its visibility.

## Motivation

Right now, the changelog contained within [`BREAKING_CHANGES.md`](https://github.com/astral-sh/ruff/blob/main/BREAKING_CHANGES.md) currently only includes backward incompatible changes.  As a user of `ruff` who is actively following its development, I also want to know which rules have been added in each release so that I know which rules to consider adding to the `ruff` configuration.  

## Alternatives

At present, I usually end up doing a [GitHub search](https://github.com/astral-sh/ruff/pulls?q=is%3Apr+is%3Amerged+label%3Arule) of merged pull requests with the label of `rule`, though this misses PRs that are not labeled. (The labels really do help!)

It's also possible to look at the [releases](https://github.com/astral-sh/ruff/releases) page on GitHub. However, this shows pull request titles, which often do not include the rule codes being added.

As always, thank you so much for a fantastic tool!

**Comment by charliermarsh** [comment]
Yeah I'm happy to do a clearer and more structured section atop the release notes that outlines all newly-added rules. Right now, all of the PRs that add rules get included in the "Rules" section at the top, but you're right that it doesn't always include the rule name or code (and that section also ends up including modifications to rules, e.g., adding autofix capabilities).

I'll give this a try next time -- I'll add a dedicated summary upfront of all new rules. Thanks for the push!

**Comment by namurphy** [comment]
Awesome, thank you again!  Going point about needing to note changes like adding autofixes. I forgot about those.

I'm also wondering if it'd be worthwhile to set up a changelog package like [towncrier](https://towncrier.readthedocs.io/en/stable/) or [scriv](https://scriv.readthedocs.io/en/latest/).  I've never tried scriv, but I've personally found towncrier to be quite helpful.

**Comment by charliermarsh** [comment]
Planning to add this going forward.

To your question: not sure! I'm actually pretty okay with the current practice for release notes. We tag PRs, and GitHub automatically collates them and excludes them in the auto-generated release notes based on those labels. Then I do a pass of manual curation. It hasn't been too bad.
