### ISSUE TITLE
New option to include or exclude git submodules

### ISSUE THREAD

**Issue by tgross35** [astral-sh/ruff#5285]
Would it be possible to add a configuration option to automatically opt git submodules in or out?

It's fairly common to have submodules be read-only within a parent repository, meaning that any `ruff` errors need to be fixed in that submodule, rather than in the parent project. When there are multiple (or potentially changing) submodules, it would be nicer to just be able to exclude them all, rather than needing to manually track their paths in the configuration file.

Related: #4920

**Comment by charliermarsh** [comment]
I think I'd be open to this if we were supported by ripgrep's `ignore` crate, but given that they [closed this as not-implemented](https://github.com/BurntSushi/ripgrep/issues/23), I'd rather just defer to the existing `exclude` behavior for now.
