### ISSUE TITLE
PERF + SLOT missing in schema

### ISSUE THREAD

**Issue by janosh** [astral-sh/ruff#5321]
`PERF` and `SLOT` are not recognized by `ruff`'s VS Code extension.

![Screenshot 2023-06-22 at 8 04 08 PM](https://github.com/astral-sh/ruff/assets/30958850/d8922a00-1647-481b-95a9-a344952fa652)

Related: https://github.com/astral-sh/ruff/issues/4529

**Comment by charliermarsh** [comment]
Yes, we need to manually update this.

**Comment by charliermarsh** [comment]
https://github.com/SchemaStore/schemastore/pull/3030
