### ISSUE TITLE
[Linter panic] when fixing `TCH003` violation for `typing` import

### ISSUE THREAD

**Issue by bendoerry** [astral-sh/ruff#5331]
## Ruff settings and version
Version: [`0.0.275`](https://github.com/astral-sh/ruff/releases/tag/v0.0.275)

### Settings
```toml
# ruff.toml
select = ['TCH']

[flake8-type-checking]
exempt-modules = []
```

## Description
When I try to autofix a `TCH003` violation for an import from `typing`, I get the following stack trace:
```
panicked at 'assertion failed: start.raw <= end.raw', /root/.cargo/git/checkouts/rustpython-parser-c806f105bc27c7db/f60e204/ruff_text_size/src/range.rs:48:9
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  17: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  18: <unknown>
```
I have confirmed this only occurs for imports from `typing`.

### Files
I used two files for testing, one using an import from `typing` and one from `collections.abc`:

#### `non_typing.py`
```python
# non_typing.py
from __future__ import annotations

from collections.abc import Iterable

def foo(a: Iterable[int]) -> None:
    pass
```
Running `ruff check non_typing.py --fix` works as expected

#### `typing.py`
```python
# typing.py
from __future__ import annotations

from typing import Iterable

def foo(a: Iterable[int]) -> None:
    pass
```
However if I run `ruff check typing.py --fix` I get the stacktrace above.
This also occurs for `typing` imports that aren't part of `collections.abc` as well. e.g. `Any`.

**Comment by charliermarsh** [comment]
Thank you!

**Comment by charliermarsh** [comment]
This might need special-casing. The problem is that we're trying to modify the `from typing` import to add `TYPE_CHECKING`, but we're also trying to remove the `Iterable` member from it.
