### ISSUE TITLE
Empty ruleset table in documenation when all rules are in the nursery section

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#5333]
Visit [the documentation](https://beta.ruff.rs/docs/rules/#copyright-related-rules-cpy) online (version `0.0.275`) and you will see an empty table where the rule `missing-copyright-notice` should be. I think something broke when the rule was moved to the `flake8-copyright` crate.

**Comment by charliermarsh** [comment]
It's probably because I moved it to the "nursery" section.

**Comment by tjkuson** [comment]
Makes sense, the empty table made it look like an error.

**Comment by charliermarsh** [comment]
I think we should add the nursery rules to the docs, and add a column to indicate that they’re nursery (like with autofix).

**Comment by charliermarsh** [comment]
(Right now it looks like an error, and there’s no way to discover the nursery rules.)

**Comment by tjkuson** [comment]
Closed by #5439.
