### ISSUE TITLE
Add cpython & other repos as formatting stability check to CI

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5355]
We have a script that formats cpython twice and checks that the formatting stays the same, that we only output valid syntax and that we don't panic due to some input. I want to integrate this script into CI to avoid regressions. This also needs documentation on how to run the check locally.

**Comment by cnpryer** [comment]
> This also needs documentation on how to run the check locally

Is this already solved or is there more that could be helpful to document?

**Comment by konstin** [comment]
The general way is documented at https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/README.md#checking-entire-projects. I'm currently working a small but diverse set of projects that we continuously check and will add more instructions once that's done.

I also ran the stability checks with the 3k repo from [ruff-usage-aggregate](https://github.com/akx/ruff-usage-aggregate/blob/master/data/known-github-tomls-clean.jsonl) and have to go through all of them and either fix them directly or open issues for each distinct one.

**Comment by konstin** [comment]
i've posted the initial script in https://github.com/astral-sh/ruff/issues/5828, this ticket is effectively about automating most of the scores from that ticket.

**Comment by konstin** [comment]
Fixed by #5919
