### ISSUE TITLE
Formatter: `With` / `AsyncWith` (includes `WithItem`)

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#5368]
* [x] `With` https://github.com/astral-sh/ruff/pull/5350
* [x] `AsyncWith`
* [ ] Parentheses in `WithItem`

**Comment by davidszotten** [comment]
sure, will take a look

**Comment by MichaReiser** [comment]
I'm not sure how to handle this inside of the formatter but we're currently adding to many parentheses for 

```python
# Input
with (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) as c:
    ...

# Ruff Output
with (
	(
		aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
	) as c,
):
	...

# Black
with (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
) as c:
    ...

```

Because both the binary expression and the `with` statement are adding parentheses. It may be necessary to explicitly enumerate all the expressions that support breaking the left side, similar to `can_break_expr` OR rethink how we group elements, potentially use `best_fitting`.

Other interesting patterns

```python
with (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) as c, (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) as c:
    ...

with (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb), (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb):
    ...

with aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb as c, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb as c:
    ...
```

We don't need to match black precisely but I do prefer black's formatting overall.

We can tackle this in a separate PR and I can also look into it

**Comment by davidszotten** [comment]
i was trying to follow the code to understand how `if_group_breaks` works. does the outer group also consider itself broken if the inner one does? or what is causing the outer group to expand?
