### ISSUE TITLE
[rule] simpify `x if x else y` to `x or y`

### ISSUE THREAD

**Issue by dorschw** [astral-sh/ruff#5377]
I wanted to suggest it to `flake8-simplify` but there hasn't been much activity there in a while, and `flake8-pie` says they're deprecated and link to ruff. 

```diff
x = ...
- y = x if x else 'default'
+ y = x or 'default'
```

It could be a bit confusing to newcomers, but cleaner, imo, to anyone familiar with ternaries in Python.

**Comment by evanrittenhouse** [comment]
I think the logic here should be pretty closely related to [`ExprOrTrue`](https://github.com/astral-sh/ruff/blob/main/crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs#L213).

**Comment by dosisod** [comment]
This is implemented as [`FURB110`](https://github.com/dosisod/refurb/blob/master/docs/checks.md#furb110-use-or-oper) in Refurb (see #1348), so you could put this check under that category.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/10687.
