### ISSUE TITLE
Fun edge case in D407

### ISSUE THREAD

**Issue by john-science** [astral-sh/ruff#5378]
Let's say I have a function in my code with a standard NumPy docstring:

```python
def something_amazing(inputs):
    """
    Wow, this does stuff!
    
    Parameters
    ==========
    inputs: dict
        Oh boy, oh boy
    """
    return sum(inputs.keys())
```

This will return the ruff error:

```bash
λ ruff .
awesome_sauce.py:6:9: D407 [*] Missing dashed underline after section ("Parameters")
Found 1 error.
```

But when I do a `ruff --fix .`, the code now looks like this:

```python
def something_amazing(inputs):
    """
    Wow, this does stuff!
    
    Parameters
    ----------
    ==========
    inputs: dict
        Oh boy, oh boy
    """
    return sum(inputs.keys())
```

This happened hundreds of times in our codebases, because someone thought dashes equal signs were the same.  

Now, I'm not sure if you want to support finding and fixing this problem. But in an ideal world I wouldn't have to worry about `ruff --fix` breaking things.

So, just FYI.

**Comment by charliermarsh** [comment]
Haha. When an issue has "Fun" in the title...

Do you think D407 should detect and replace the equals signs?

**Comment by zanieb** [comment]
If they're of a matching length it seems like a good user experience to remove the equal signs automatically.

**Comment by john-science** [comment]
> Do you think D407 should detect and replace the equals signs?

It would have helped my team.  Luckily, someone didn't trust the auto `--fix` flag and reviewed my PR.

BUT, I'm willing to concede I don't have a wide view of the huge feature set that `ruff` wants to support.  So it's up to ya'll.

I could take a whack at it, of course. But I haven't tried to contribute to `ruff` before, so there would be a long spin-up process.

**Comment by charliermarsh** [comment]
All good, @dhruvmanila already finished it :)
