### ISSUE TITLE
UP035: Literal removed too soon

### ISSUE THREAD

**Issue by henryiii** [astral-sh/ruff#5380]
If you activate UP035, Ruff removes `Literal` imports if 3.8+ is targeted. However, due to a caching bug in `Literal` fixed in CPython 3.10.1+ and 3.9.8+, `typing_extensions` provides `Literal` for <= 3.10.0 - see [the changelog for 4.6.0](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-460-may-22-2023).

**Comment by charliermarsh** [comment]
Thanks.

**Comment by charliermarsh** [comment]
Oh, we recently moved `Literal` to Python 3.10 to match pyupgrade and based on Alex Waygood's advice [here](https://github.com/astral-sh/ruff/issues/5112#issuecomment-1602800558), as part of the next release. Is that sufficient to close this?

**Comment by henryiii** [comment]
Yes, I think so. Technically an issue in 3.10.0, but no one should care about a bug in an old .0 release. Thanks!
