### ISSUE TITLE
Add remove noqa

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/ruff#5408]
This would be the reverse of add-noqa, so as such would be exclusive flag with ``--add-noqa``. This is something one would want to use when they decide to no longer ignore those failures and instead fix them.

**Comment by charliermarsh** [comment]
We have `--ignore-noqa`, would that have the same effect in practice?

**Comment by gaborbernat** [comment]
No I'd actually like ruff to delete the noqa entry, the same way add-noqa writes to the file.

**Comment by charliermarsh** [comment]
How would that differ from a workflow of:

- Run `--ignore-noqa`.
- Fix violations.
- Run with `ruff --extend-select RUF100 --fix` (to automatically remove unused `noqa` comments, now that the comments are unused).

**Comment by gaborbernat** [comment]
Hmm, that works just feels less intuitive.
