### ISSUE TITLE
Support globbing in the `known-first-party` isort option

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#5420]
Globbing should be supported in the `known-first-party` isort option so that

```
[tool.ruff.isort]
known-first-party = ["mymodule_*"]
```

works, and users are not required to list all modules manually.

Globbing should probably also work for `known-third-party` following the same logic.

Discussed in #5419.

**Comment by charliermarsh** [comment]
We can look at how `ignore_names` works as an example.
