### ISSUE TITLE
Test for regressions with something like crater/mypy_primer

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#5433]
Currently, regressions in new versions are automatically checked by running tests in CI.

Project rely on users and fuzzers to find regressions between new releases, but this could be automated in some way.

Rust and mypy also use in CI crater/mypy_primer - tools that can check for differences/regressions in hundreds of projects
https://github.com/hauntsaninja/mypy_primer
https://github.com/rust-lang/crater

Example how mypy_primer works from its README
```
    Clones a copy of mypy (potentially from a fork you specified)
    Checks out a "new" and "old" revision of mypy
    Clones a hardcoded list of projects (potentially filtered by you)
    Installs necessary stubs and dependencies per project
    Runs the appropriate mypy command per project
    Shows you the potentially differing results!
    Lets you bisect to find the mypy commit that causes a given change
```

**Comment by charliermarsh** [comment]
I believe we already have this - have you seen the “ecosystem checks” which appear on CI and in the repo? It does what you describe, unless I’m misunderstanding.

**Comment by qarmin** [comment]
Yes, this is indeed what I was writing about
