### ISSUE TITLE
Make flake8-quotes descriptions consistent with default settings

### ISSUE THREAD

**Issue by trag1c** [astral-sh/ruff#5496]
![34882](https://github.com/astral-sh/ruff/assets/77130613/101e593a-d610-48b4-a589-0624a211b5b9)

Whether single quotes are preferred over double quotes, or vice versa, depends on the `docstring-quotes`, `inline-quotes` and `multiline-quotes` settings, which all default to `"double"`. I think it would make more sense to make the descriptions prefer double quotes as well.

**Comment by charliermarsh** [comment]
Makes sense.
