### ISSUE TITLE
Expand Ruff's default exclusions

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#5510]
Like Black, I'd like to add:

- `.vscode`
- `.ipynb_checkpoints`
- `.pytest_cache`

Unlike Black, I'd also like to add `.pyenv`.

**Comment by charliermarsh** [comment]
Anyone for or against this?

**Comment by dhruvmanila** [comment]
What's the motivation behind `.pyenv`? Isn't that probably always going to be in the home directory unlike others which could be in a project directory?

**Comment by charliermarsh** [comment]
It's relevant in the context of VS Code: https://github.com/astral-sh/ruff/discussions/5509

**Comment by dhruvmanila** [comment]
Makes sense then! No objections from my side 👍
