### ISSUE TITLE
0.0.277 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [astral-sh/ruff#5551]
👋 it looks like 0.0.277 release was not completed, see [this action run](https://github.com/astral-sh/ruff/actions/runs/5458523781), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/135796

**Comment by charliermarsh** [comment]
Hmm, I think it was completed? This is the actual release run: https://github.com/astral-sh/ruff/actions/runs/5458525309.

**Comment by chenrui333** [comment]
somehow the release attached builds attached to the git tag did not show as success
![image](https://github.com/astral-sh/ruff/assets/1580956/a6e3b5bd-442c-4ec7-9ba8-167a5f16fbb5)

Also there is no release labeling for 0.0.277

**Comment by charliermarsh** [comment]
Oh, it was marked as a draft. I just marked it as latest: https://github.com/astral-sh/ruff/releases/tag/v0.0.277. But the tag already existed?

**Comment by charliermarsh** [comment]
(That first screenshot is the release dry-run jobs running on commit, not the actual release job.)

**Comment by charliermarsh** [comment]
Can I help at all w/ the Homebrew release? Is it blocked?

**Comment by chenrui333** [comment]
yeah, it was blocked mostly due to the draft release thing. I think I am unblocked now, thanks!

**Comment by chenrui333** [comment]
shipping the homebrew formula update now, thanks again!

**Comment by charliermarsh** [comment]
Thank you! Sorry for the confusion, new release workflow as of recently.

**Comment by chenrui333** [comment]
no worries, happy to help
