### ISSUE TITLE
Copyright rules not selectable with "CPY"

### ISSUE THREAD

**Issue by Hnasar** [astral-sh/ruff#5569]
Unlike with other rules which I can enable with the linter prefix, the CPY rules seems to require the specific error code. 

```
touch foo.py
ruff --select=CPY001 foo.py  # foo.py:1:1: CPY001 Missing copyright notice at top of file
ruff --select=CPY foo.py   # no output
# ruff --version
# ruff 0.0.277
```

Also, the docs still mention the old name of the checker before it was renamed to flake8-copyright in #5236 
https://beta.ruff.rs/docs/rules/#copyright-related-rules-cpy

Thanks for ruff!

**Comment by zanieb** [comment]
Hey @Hnasar — this is intentionally because this rule is in the "nursery" group which requires explicit opt-in since the rules are still under development. See https://github.com/astral-sh/ruff/pull/4407 for some more background.

**Comment by charliermarsh** [comment]
I did intend to change the category name, but I think I missed one reference. 

That these rules are in the "nursery" group is supposed to be reflected in the docs which would make this a lot clearer, but we haven't finished that change yet :sob: (https://github.com/astral-sh/ruff/pull/5439)

**Comment by zanieb** [comment]
The name should be addressed now by https://github.com/astral-sh/ruff/pull/5577

**Comment by charliermarsh** [comment]
I'm going to close for now since I think this is mostly blocked on fixing the docs, which is being tracked elsewhere.
