### ISSUE TITLE
Memoize?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [astral-sh/ruff#5606]
I cannot find `memoize` in dictionaries, shouldn't it have been `memorize?`
https://github.com/astral-sh/ruff/blob/0b9af031fb8f51e7f9a72c31366bf5f87b90ca3c/crates/ruff_formatter/src/format_extensions.rs#L72
https://github.com/astral-sh/ruff/blob/0b9af031fb8f51e7f9a72c31366bf5f87b90ca3c/crates/ruff_formatter/src/prelude.rs#L5
https://github.com/astral-sh/ruff/blob/0b9af031fb8f51e7f9a72c31366bf5f87b90ca3c/crates/ruff_python_formatter/src/expression/binary_like.rs#L36

**Comment by MichaReiser** [comment]
Interesting. I guess the problem why the term isn't in a general purpose dictionary is because it is a term specific to computer science. https://en.wiktionary.org/wiki/memoize

**Comment by DimitriPapadopoulos** [comment]
I wouldn't be surprised if many words "specific to computer science" were initially actual misspellings. I don't see a substantial difference between the definitions of `memorize` and `memoize`, one that would explain the new spelling. Besides, the usual word in computer science for "_store (the result of a computation so that it can be subsequently retrieved without repeating the computation_" is **`cache`**.

It is true `memoize` has been used more "widely" [since 1980](https://books.google.com/ngrams/graph?content=memoize&year_start=1800&year_end=2019&corpus=en-2019), but [many orders of magnitude less than `memorize`](https://books.google.com/ngrams/graph?content=memoize%2Cmemorize&year_start=1800&year_end=2019&corpus=en-2019). I wonder how to find the seminal misspelling around 1970-1980, just to check whether it seems intentional or not.

**Comment by wookie184** [comment]
The [wikipedia page for memoization](https://en.wikipedia.org/wiki/Memoization) suggests the spelling was intentional, and describes it as a specific type of caching
