### ISSUE TITLE
Format assignment expressions (`FormatExprNamedExpr`)

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5613]
Assignment expressions are those using the "walrus operator" `:=`:
```python
if x := f():
    g(x)
```
In general, they are easy to format, they are a sequence of target, space, `:=`, space, value with optional parentheses.

The difficulty is that there are a list of [exceptional cases in PEP 572](https://peps.python.org/pep-0572/#exceptional-cases) where the parentheses are mandatory based on the surrounding node, e.g. keyword argument values need parentheses. So for implementing this we either need to use the [tuple way of checking if there are parentheses in range](https://github.com/astral-sh/ruff/blob/40ddc1604cf53d209d55c7fd9ec40a399fc2a53f/crates/ruff_python_formatter/src/expression/expr_tuple.rs#L128) or each node in the list in PEP 572 needs to have a special case where it checks whether the expression it is about to format is a `ExprNamedExpr` and in that cases sets the parentheses to always.

**Comment by charliermarsh** [comment]
If the named expression needs to be parenthesized, won’t it already have been parenthesized in the parsed source? (Otherwise it would’ve been invalid syntax in the first place.) So would those “exceptions” be solved by preserving original parentheses? May be misunderstanding.

**Comment by konstin** [comment]
Good point, i filed this because i [tried the naive solution and failed](https://github.com/astral-sh/ruff/compare/main...named_expr_stash), but you're right, the [tuple way of checking if there are parentheses in range](https://github.com/astral-sh/ruff/blob/40ddc1604cf53d209d55c7fd9ec40a399fc2a53f/crates/ruff_python_formatter/src/expression/expr_tuple.rs#L128) is likely better

**Comment by konstin** [comment]
Implemented this differently because unlike tuples even mandatory parentheses are not part of the range
