### ISSUE TITLE
"ALL" rule selector undocumented

### ISSUE THREAD

**Issue by benjamin-kirkbride** [astral-sh/ruff#5619]
I looked for a while to figure out how to do this, and eventually found it in https://github.com/astral-sh/ruff/discussions/4237

I think it should be documented:
- at the top of https://beta.ruff.rs/docs/rules/
-  in https://beta.ruff.rs/docs/settings/#select

**Comment by dhruvmanila** [comment]
Hey, thanks for opening an issue. It's present in the documentation in this section: https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml:

> As a special-case, Ruff also supports the `ALL` code, which enables all rules. Note that some pydocstyle rules conflict (e.g., `D203` and `D211`) as they represent alternative docstring formats. Ruff will automatically disable any conflicting rules when `ALL` is enabled.

Do you think it would be useful to add it elsewhere?

**Comment by ssweber** [comment]
Is there somewhere that has all the rule categories in list format? I made one myself a few months back, and am slowly uncommenting rules as I have time to fix a codebase with them.

**Comment by benjamin-kirkbride** [comment]
@dhruvmanila ah, sorry I missed that.

IMO, I think the whole
> As a special-case, Ruff also supports the ALL code, which enables all rules. Note that some pydocstyle rules conflict (e.g., D203 and D211) as they represent alternative docstring formats. Ruff will automatically disable any conflicting rules when ALL is enabled.
>
>If you're wondering how to configure Ruff, here are some recommended guidelines:
>
>Prefer select and ignore over extend-select and extend-ignore, to make your rule set explicit.
Use ALL with discretion. Enabling ALL will implicitly enable new rules whenever you upgrade.
Start with a small set of rules (select = ["E", "F"]) and add a category at-a-time. For example, you might consider expanding to select = ["E", "F", "B"] to enable the popular flake8-bugbear extension.
By default, Ruff's autofix is aggressive. If you find that it's too aggressive for your liking, consider turning off autofix for specific rules or categories (see [FAQ](https://beta.ruff.rs/docs/faq/#ruff-tried-to-fix-something--but-it-broke-my-code)).

Section should be much higher up, possibly at the top or even in it's own section.

**Comment by charliermarsh** [comment]
Hmm yeah, `ALL` is intentionally under-documented, I view it as a little bit of an anti-pattern and don't want to encourage its use. I'm hoping to replace it in the future with semantically meaningful categories and better defaults.

**Comment by hmvp** [comment]
We use `ALL` in combination with a pinned version of ruff. This works great because on upgrade we can always ignore new rules if we don't want them (or don't want to fix them yet).

However what I miss in the proposed documentation above is how to deal with the conflicting pydocstyle rules.. The actual behavior seems to be to select the first and deselect the conflicting one. But what to do if you actually want the conflicting one...

**Comment by doolio** [comment]
> Hmm yeah, `ALL` is intentionally under-documented, I view it as a little bit of an anti-pattern and don't want to encourage its use. I'm hoping to replace it in the future with semantically meaningful categories and better defaults.

Counter argument. I'm a beginner programmer and using `ALL` as a teaching aid to write better code! Just the other day it taught me about the built-in function `all` via `SIM110`.

**Comment by zanieb** [comment]
We'd like to resolve this by re-categorizing the rules and having sensible defaults as noted by Charlie — then Ruff will still teach you to write better code and you won't get a bunch of pedantic or rules without common consensus like you do when you turn on ALL. I worry that learning with ALL is too noisy of an experience.

**Comment by sanxiyn** [comment]
Current status: `ALL` is documented at https://docs.astral.sh/ruff/linter/#rule-selection.
