### ISSUE TITLE
Busted documentation page

### ISSUE THREAD

**Issue by claird** [astral-sh/ruff#5624]
[The documentation page for `PERF203`](https://beta.ruff.rs/docs/rules/try-except-in-loop/) advises readers to "... [u]se instead" source which is not only fails to be stylish, but does not even compile (roughly, it has `break` where `pass` perhaps was intended).  Also, early experiments suggest that **Ruff** fires `PERF203` even for Py3.11 and 3.12, contrary to the text.

I have little sense of how **Ruff** documentation is maintained.  Perhaps someone's already planning corrections for this page.  If not, and if I learn the appropriate workflow, I'll happily submit my own suggestions for revisions.

**Comment by charliermarsh** [comment]
Thanks! Are you specifying a target-version? Ruff doesn’t rely on the currently-running Python version, it picks up the minimum-supported version either from your pyproject.toml or the target-version setting.

The example could definitely be improved — PR welcome, it would only require editing the Markdown around [here](https://github.com/astral-sh/ruff/blob/38fa305f358df8420f94ce62d072908010a38ec4/crates/ruff/src/rules/perflint/rules/try_except_in_loop.rs#L30).
