### ISSUE TITLE
Formatter: Expression subscript gets additional whitespace where black doesn't insert any

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5673]
We format
```python
parts[1:-1]
```
as
```
parts[1 : -1]
```
We need to change the logic to treat `-1` like a normal constant instead of a complex expression that needs whitespace

**Comment by MichaReiser** [comment]
> We need to change the logic to treat -1 like a normal constant instead of a complex expression that needs whitespace

Is it specific to `-1` or does it apply to all unary expressions (`+` and `-`) that have a numeric constant?

**Comment by konstin** [comment]
both plus and minus work, `not` doesn't, for other operators i'd have to check the black source
