### ISSUE TITLE
Nested bare except not found

### ISSUE THREAD

**Issue by puittenbroek** [astral-sh/ruff#5678]
Tried to search for an existing issue regarding this but couldn't find any. Apologies if my search was insufficient.
Busy introducing ruff for our repositories and ran into situation where it didn't find all issues that flake8 did raise.
Most notably this 'bare except' issue. 

A minimal code snippet that reproduces the bug.:
```python
def some_function(*args, **kwargs):
    try:
        1 / 0
    except:
        raise


if __name__ == "__main__":
    try:
        1 / 0
    except:
        pass

    some_function()

```
The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.:
```bash
ruff check --isolated -n broken.py
```

The current Ruff version (`ruff --version`):
```
ruff 0.0.277
```

Output:
```
broken.py:11:5: E722 Do not use bare `except`
Found 1 error.
```

Expected it to also find line 4, flake8 does find this; `flake8 broken.py`:
```
broken.py:4:5: E722 do not use bare 'except'
broken.py:11:5: E722 do not use bare 'except'

```

**Comment by charliermarsh** [comment]
I believe it's because you're re-raising the exception on line 5, which we allow, since it then forces the exception to be handled by the caller.

**Comment by puittenbroek** [comment]
Ha.. you're right. If I replace it with a `pass` ruff does error on it. Case closed then :+1:
