### ISSUE TITLE
formatter: comment formatting instability in named expr (and dict, others)

### ISSUE THREAD

**Issue by davidszotten** [astral-sh/ruff#5695]
input

```
if (
    # 1
    x # 2
    # 2.5
    := # 3
    # 3.5
    y # 4
):
    pass
```

```
Formatted once:
---
if (
    # 1
    x := # 2.5  # 2  # 3
    # 3.5
    y  # 4
):
    pass

---

Formatted twice:
---
if (
    # 1
    x := # 3.5  # 2.5  # 2  # 3
    y  # 4
):
    pass
```

i think the issue is that we use a `space()` around the operator (`:=`) and not a `soft_line_break_or_space` so nothing is inserting the newline before the leading ownline comment

**Comment by MichaReiser** [comment]
The use of space might be intentional to avoid breaking after the operator. But it might be necessary to emit a soft line break if the right side has a leading comment

**Comment by davidszotten** [comment]
yes sorry for being unclear. wasn't suggesting switching out the `space`, only thinking out loud why we hadn't seen this more elsewhere

**Comment by charliermarsh** [comment]
I'll take this one. There are similarities to `with... as...` so I'll wait for that to be approved before pushing anything.

**Comment by charliermarsh** [comment]
Didn't end up being that similar to `with` so PR here: https://github.com/astral-sh/ruff/pull/6634.
