### ISSUE TITLE
Help messages with dunders are rendered as bold instead of displaying literal `__`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#5699]
Help messages with content that includes `__XXXX__` is rendered bold instead of displaying the `__` which is common for dunder variables.

<img width="496" alt="Screenshot 2023-07-11 at 19 04 06" src="https://github.com/astral-sh/ruff/assets/2586601/95546a1f-0faa-4bef-bf7b-2629e149f7d4">

```
example.py:1:22: F401 [*] `.version.__version__` imported but unused
  |
1 | from .version import __version__
  |                      ^^^^^^^^^^^ F401
  |
  = help: Remove unused import: `.version.version`

Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

or

```
example.pyi:3:32: PYI016 Duplicate union member `Literal["__test__"]`
  |
1 | from typing import Literal, Union

2 | 
3 | x = Union[Literal["__test__"], Literal["__test__"]]
  |                                ^^^^^^^^^^^^^^^^^^^ PYI016
  |
  = help: Remove duplicate union member `Literal["test"]`
```

Originally reported in https://github.com/astral-sh/ruff/issues/5697#issuecomment-1631623181

**Comment by charliermarsh** [comment]
This came up once before, in response IIRC @MichaReiser said we should look into replacing the annotate-snippets crate which has some unusual behavior (like this).

**Comment by MichaReiser** [comment]
See https://github.com/rust-lang/annotate-snippets-rs/pull/54

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/8646.
