### ISSUE TITLE
Ecosystem CI check links should use permalinks

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#5702]
I notice that one of the Airflow links pointed to an irrelevant line of code. I'm guessing that the code changed between the ecosystem CI run and my clicking through. Could we instead use permalinks, so that they point to the relevant violations in perpetuity? (Is that even possible?)

**Comment by dhruvmanila** [comment]
Yeah, it should be possible. We just need to get the current commit hash at the time of checkout.
