### ISSUE TITLE
sort autofix incorrectly removes nested sorts

### ISSUE THREAD

**Issue by BorisOrca** [astral-sh/ruff#5712]
Minimal reproduction:

```python
values = [(2, "b"), (2, "a"), (1, "b"), (1, "a")]
print(sorted(sorted(values, key=lambda x: x[1]), key=lambda x: x[0]))
```
prints out: `[(1, 'a'), (1, 'b'), (2, 'a'), (2, 'b')]`

After running `ruff check reproduce_sort_issue.py`
``` Found 1 error (1 fixed, 0 remaining).```

The "fixed" code is:
```python
values = [(2, "b"), (2, "a"), (1, "b"), (1, "a")]
print(sorted(values, key=lambda x: x[0]))
```

prints out: `[(1, 'b'), (1, 'a'), (2, 'b'), (2, 'a')]`

```
> ruff --version
ruff 0.0.277
```

**Comment by charliermarsh** [comment]
Looks like we need to avoid collapsing sorts with different keys.
