### ISSUE TITLE
EXE002 doesn't update when the file permissions change

### ISSUE THREAD

**Issue by tom-mcdermott-morse** [astral-sh/ruff#5726]
`
spon> ruff --version
ruff 0.0.277
spon> touch fake.py
spon> chmod +x fake.py
spon> ruff check --select EXE .
fake.py:1:1: EXE002 The file is executable but no shebang is present
Found 1 error.
spon> chmod -x fake.py
spon> ls -l
total 0
-rw-rw-r-- 1 spon spon 0 Jul 13 16:50 fake.py
spon> ruff check --select EXE .
fake.py:1:1: EXE002 The file is executable but no shebang is present
Found 1 error.
spon> ruff check --select EXE -n .
spon> ruff check --select EXE .
fake.py:1:1: EXE002 The file is executable but no shebang is present
Found 1 error.

`
I'd expect ruff to work here without explicit cache manipulation

**Comment by charliermarsh** [comment]
Previous PR that fixed this, before we refactored the cache: https://github.com/astral-sh/ruff/pull/3104. In that case, we added the file permissions (for each file) to the cache key.
