### ISSUE TITLE
Docs: Options sections of some rules are broken

### ISSUE THREAD

**Issue by eggplants** [astral-sh/ruff#5740]
The docs for rules that have multiple options appears to be broken.

![image](https://github.com/astral-sh/ruff/assets/42153744/acef59f6-d534-47b6-b687-433790ce8f65)

Broken docs:
- [E501](https://beta.ruff.rs/docs/rules/line-too-long/#options)
- [N804](https://beta.ruff.rs/docs/rules/invalid-first-argument-name-for-class-method/#options)
- [N805](https://beta.ruff.rs/docs/rules/invalid-first-argument-name-for-method/#options)
- [W505](https://beta.ruff.rs/docs/rules/doc-line-too-long/#options)

**Comment by charliermarsh** [comment]
Thanks!
