### ISSUE TITLE
UP007 - Bug for Unions and Optional with Quotes Inside Brackets

### ISSUE THREAD

**Issue by max-muoto** [astral-sh/ruff#5756]
## Bug Description

Ruff doesn't detect instances of `Union` where there is at-least one quoted type among the unioned types for [UP007(https://beta.ruff.rs/docs/rules/non-pep604-annotation/).

The same goes for quoted types inside of `Optional`.

Take several examples:

- `"Optional[str]"` autofixed -> `"str | None"`
- `"Union[str, int]"` autofixed -> `"str | int"`
- `Union["str", int]` not detected by `ruff check`
- `Union["str", "int"]` not detected by `ruff check`
- `Optional["str"]` not detected by `ruff check`

Obviously once difference here is that `Union["str", int]` is valid, but `"str" | int` will cause a runtime error, so if there was an autofix I'd assume it would just get transformed to `"str | int"`.

## Other Details:
- Command: `ruff check`
- Ruff Settings: `UP007` enabled individually (not the entire `UP` suite).
- Version: `ruff 0.0.278`

**Comment by charliermarsh** [comment]
We now support this in limited cases #5725, when `"str" | int` won't error at runtime (e.g., it's an assignment annotation within a function body). We still don't fix `Union["str", int]` to `"str | int"`, but I'm not totally sure that we should.

**Comment by charliermarsh** [comment]
We could arguably flag-but-not-fix these -- the original behavior was motivated by pyupgrade's decisions (pyupgrade doesn't fix any cases that include a string in the subscript).

**Comment by max-muoto** [comment]
> 

I see, that makes sense then, thanks for the context! I do think a flag would at least be helpful, but understand if the goal is just simple parity with pyupgrade.
