### ISSUE TITLE
Remove unnecessary walrus operator parentheses

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#5781]
Our formatter currently always adds parentheses around the walrus (`a := 5`) operator in for/if/... cases

https://github.com/astral-sh/ruff/blob/3cda89ecafc24722c17d77727cde71f8d9c7df68/crates/ruff_python_formatter/src/expression/expr_named_expr.rs#L32-L41

The goal of this issue is to implement black's parentheses behavior (inside `NeedsParentheses`) and only preserve parentheses that are necessary.

https://github.com/psf/black/blob/b4dca26c7d93f930bbd5a7b552807370b60d4298/src/black/linegen.py#L1387-L1401

**Comment by zanieb** [comment]
Related discussion suggesting we may not want to always remove them(?) https://github.com/astral-sh/ruff/discussions/4870

**Comment by MichaReiser** [comment]
> Related discussion suggesting we may not want to always remove them(?) #4870

Oh thanks. Our formatter preserves parentheses for nested expression but removes them in if/for/... headers.
