### ISSUE TITLE
`# ruff: noqa` rejects comments after directive

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#5791]

**Comment by farmio** [comment]
Hi 👋! 
You asked me to paste the exact code raising the warnings. So here it is:
https://github.com/XKNX/xknx/blob/ef92f03db5bdbf163f6010bd545c1ba20007318d/xknx/dpt/dpt_hvac_mode.py#L15
The comment-comment text does not seem to matter even 
```py
# ruff: noqa: RUF012  # M
``` 
would raise warnings.

**Comment by charliermarsh** [comment]
Thanks so much!

**Comment by charliermarsh** [comment]
Ok, I just confirmed that I see these warnings on 0.0.277, but not on 0.0.278. So, hopefully fixed by upgrading Ruff, but let me know if you see otherwise.
