### ISSUE TITLE
Does `crates/ruff/resources/test/fixtures/pyupgrade/UP014.py` contain incorrect `NamedTuple` calls?

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#5794]
https://github.com/astral-sh/ruff/blob/f012ed2d77272bfdd75f6988c2658e36fbf63102/crates/ruff/resources/test/fixtures/pyupgrade/UP014.py#L7-L12

Is this a valid `NamedTuple` call?

```
> python3 --version
Python 3.11.4

> cat a.py
from typing import NamedTuple

MyType = NamedTuple(
    "MyType",
    [("a", int), ("b", str), ("c", list[bool])],
    defaults=["foo", [True]],
)

> python a.py
Traceback (most recent call last):
  File "/home/haru/Desktop/repositories/ruff/a.py", line 3, in <module>
    MyType = NamedTuple(
             ^^^^^^^^^^^
  File "/home/haru/miniconda3/envs/py311/lib/python3.11/typing.py", line 2916, in NamedTuple
    raise TypeError("Either list of fields or keywords"
TypeError: Either list of fields or keywords can be provided to NamedTuple, not both
```

**Comment by harupy** [comment]
or this intentional?

**Comment by cnpryer** [comment]
> Is this a valid NamedTuple call?

If I understand this function signature correctly, no, right?

https://github.com/python/cpython/blob/8c177294899b621fe04ae755abd41b4d319dd4b5/Lib/typing.py#L2770

If not the signature that elif will throw
```py
def NamedTuple(typename, fields=None, /, **kwargs):
    # ...
    if fields is None:
        fields = kwargs.items()
    elif kwargs:
        raise TypeError("Either list of fields or keywords"
                        " can be provided to NamedTuple, not both")
```

**Comment by cnpryer** [comment]
> or is this intended?

Is this what you saw?

```py
from typing import NamedTuple
 
MyType = NamedTuple(
    "MyType",
    [("a", int), ("b", str), ("c", list[bool])],
    defaults=["foo", [True]],
)
```
```
crates/ruff_python_formatter/scratch.py:6:16: F821 Undefined name `foo`
Found 1 error.
```

**Comment by harupy** [comment]
I saw that, and then found this issue. What I meant by `is this intended` was:

```
MyType = NamedTuple(
    "MyType",
    [("a", int), ("b", str), ("c", list[bool])],
    defaults=[1, "foo", [True]],
)
```

is an invalid `NamedTuple` call, but syntactically correct. It could be useful if ruff automatically fixes this to:

```
class MyType(NamedTuple):
    a: int = 1
    b: str = "foo"
    c: list[bool] = [True]
```

It appears ruff does.

**Comment by charliermarsh** [comment]
I think it's intended, just to see how we would handle that case, even if it's not valid at runtime.

**Comment by harupy** [comment]
Makes sense. Is F821 on `foo` unintended (https://github.com/astral-sh/ruff/issues/5794#issuecomment-1636970152)?

**Comment by charliermarsh** [comment]
Is passing `defaults` as a list supported at all? I wonder why we support that at all? (Maybe that's why you opened the issue and I just misunderstood.)

**Comment by charliermarsh** [comment]
(I assumed there was some case in which passing a list of defaults was supported, just that you couldn't mix it with specifying the fields that way.)

**Comment by harupy** [comment]
```python
from typing import NamedTuple

# valid
MyType = NamedTuple(
    "MyType",
    defaults=str,
)

# valid
MyType = NamedTuple(
    "MyType",
    defaults=list[str],
)

# invalid because [str] is not a valid type annotation
MyType = NamedTuple(
    "MyType",
    defaults=[str],
)

# Invalid, throws `TypeError: Either list of fields or keywords can be provided to NamedTuple, not both`
MyType = NamedTuple(
    "MyType",
    [("a", int), ("b", str), ("c", list[bool])],
    defaults=["foo", [True]],
)

```

**Comment by charliermarsh** [comment]
In each case, `defaults` is just treated as a standard field though, right? I feel like UP014 is under the mistaken impression that you can provide a list of default values via `defaults`... If so, we should remove that.

**Comment by charliermarsh** [comment]
Yeah, we should remove all the special-casing around `defaults`.

**Comment by charliermarsh** [comment]
E.g., this and related code seems unnecessary:

```rust
/// Match the `defaults` keyword in a `NamedTuple(...)` call.
fn match_defaults(keywords: &[Keyword]) -> Result<&[Expr]> {
    let defaults = keywords.iter().find(|keyword| {
        if let Some(arg) = &keyword.arg {
            arg == "defaults"
        } else {
            false
        }
    });
    match defaults {
        Some(defaults) => match &defaults.value {
            Expr::List(ast::ExprList { elts, .. }) => Ok(elts),
            Expr::Tuple(ast::ExprTuple { elts, .. }) => Ok(elts),
            _ => bail!("Expected defaults to be `Expr::List` | `Expr::Tuple`"),
        },
        None => Ok(&[]),
    }
}
```

**Comment by harupy** [comment]
> In each case, defaults is just treated as a standard field though, right?

`defaults` is visited as a type annotation:

https://github.com/astral-sh/ruff/blob/d692ed08961cbdc56a9f254fba906bd6d3b711d8/crates/ruff/src/checkers/ast/mod.rs#L3690-L3695


Ruff thinks `"foo"` is a forward ref, but no `foo` exists, F821 is thrown.

**Comment by harupy** [comment]
Happy to file a PR.
