### ISSUE TITLE
Formatter: Ellipses in stub files get formatted on a single line

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5822]
If a class, method or function is stub out with an ellipsis (`...`), black gives them their own line in python files and appends them end-of-line after the colon in stub files:

**scratch.py**

```python
class Animal:
    ...


class Cat(Animal):
    def meow(self):
        ...


def f():
    ...
```

**scratch.pyi**

```python
class Animal: ...

class Cat(Animal):
    def meow(self): ...

def f(): ...
```

**Comment by MichaReiser** [comment]
Note: This requires tracking the source type and passing it to the formatter context.

**Comment by andersk** [comment]
With any luck, Black will soon be changing here to allow the concise form in both `.py` and `.pyi` files.

- psf/black#1797
- psf/black#3796

**Comment by konstin** [comment]
Applying the same formatting for source and stub files would be nice, and it would also reduce formatter complexity because it gives us one variable that changes formatting less.

**Comment by hauntsaninja** [comment]
Black still handles other things (like whitespace) differently between py and pyi, so you'll still need to put source type in formatter context if you wish to format stub files like Black does.

**Comment by MichaReiser** [comment]
We should probably implement this anyway for now, because the change will be part of Black's new preview style.

**Comment by konstin** [comment]
Added the file type information to the context #6331

**Comment by konstin** [comment]
`PyFormatOptions` now has a `source_type` field

**Comment by saulshanabrook** [comment]
Hey! I would love to try to adopt this formatting in my normal Python files as well. I saw that black I believe supports this under the next flag and was curious if that might be possible to support in ruff too.

---

For what it's worth, my use case is for [a library](https://egglog-python.readthedocs.io/latest/) that allows other libraries to create DSLs based off uninterpreted functions, so none of them will have bodies. I have [gotten some feedback](https://egraphs.zulipchat.com/#narrow/stream/375765-egg.2Fegglog/topic/egglog.20python.20midlevel.20api/near/421923656) that it's annoying that it takes an extra line for every definition.

**Comment by MichaReiser** [comment]
@saulshanabrook You can give it a try by running the formatter with `--preview`. We plan to release the new preview styles soon. See https://github.com/astral-sh/ruff/issues/8678

**Comment by saulshanabrook** [comment]
Oh wow, thank you @MichaReiser! That's great!
