### ISSUE TITLE
Formatter: `Match` (includes `MatchCase` and `Patterns`)

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5834]
This is a bigger project that includes the following nodes:

- [x] #6298
- [x] #6299
- [x] #6641
- [x] #6642
- [x] #6644
- [x] #6643
- [x] #6645
- [x] #6557
- [x] #6558
- [x] #6555
- [x] #6753
- [ ] #6933

The match arms have the same considerations for comments as if branches or try-except branches.

**Comment by MichaReiser** [comment]
As a note. The idea isn't that this is all implemented in a single PR. I recommend to start implementing `StmtMatch` and stubbing out the match cases (if they aren't already). We can then add support for the match statements one by one

**Comment by dhruvmanila** [comment]
Regarding the match patterns, I would say that `PatternMatchValue`, `PatternMatchSingleton`, `PatternMatchStar`, `PatternMatchSequence` (sequence of other patterns), and `PatternMatchOr` (similar to `PatternMatchSequence`) are good first issues and could be taken on in the order mentioned.

**Comment by evanrittenhouse** [comment]
I can take those pattern issues! Feel free to assign them to me

**Comment by MichaReiser** [comment]
I don't think this is ready yet. We first need to land https://github.com/astral-sh/ruff/pull/6594 (@evanrittenhouse  you can work on top of that PR, as long as you don't mind that there's one failing test).

**Comment by cnpryer** [comment]
Is #6933 still required for the Alpha release? Looks like it’s marked as Beta.

**Comment by charliermarsh** [comment]
My impression is that #6933 shouldn't be blocking for alpha.
