### ISSUE TITLE
[question] `I001`, joined imports and `import as`

### ISSUE THREAD

**Issue by dorschw** [astral-sh/ruff#5836]
Hi,`I001` suggests
```diff
- from x import a
- from x import b 
+ from x import a, b
```
On the other hand, it doesn't say anything about 
```python
from x import a as aa
from x import b as bb
```

I'd expect it to suggest
```diff
- from x import a as aa
- from x import b as bb
+ from x import (a as aa, b as bb)
```

(real example: https://github.com/demisto/demisto-sdk/pull/3308#discussion_r1265550042, https://github.com/demisto/demisto-sdk/pull/3308#discussion_r1265576685)

Is this by design, or should it suggest grouping even when `as` is used, and this behavior is a bug?

Thanks! 🙂

**Comment by charliermarsh** [comment]
Check out [`combine-as-imports`](https://beta.ruff.rs/docs/settings/#isort-combine-as-imports), which I think does what you're describing.
