### ISSUE TITLE
Add unit tests for file discovery

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#5850]
> Unfortunately we don’t have any unit tests for the file discovery behavior right now, so we’d need to establish some new patterns.

_Originally posted in https://github.com/astral-sh/ruff/pull/5775#issuecomment-1636793201_

We should establish a pattern that can be used by contributors to add test coverage for changes in behavior as well as add coverage for existing behavior.

Needs test coverage:
- [x] https://github.com/astral-sh/ruff/pull/5775

**Comment by charliermarsh** [comment]
Thank you for filing -- would love to have tests for this.

**Comment by konstin** [comment]
i added some error case tests in https://github.com/astral-sh/ruff/pull/5611

**Comment by harupy** [comment]
Can I work on writing a test for #5775?

**Comment by charliermarsh** [comment]
Of course!

**Comment by harupy** [comment]
Where can I add a test? `crates/ruff/src/resolver.rs`?

**Comment by charliermarsh** [comment]
Yes I think that’s appropriate.
