### ISSUE TITLE
incorrect ranges for constants in joined strings?

### ISSUE THREAD

**Issue by davidszotten** [astral-sh/ruff#5907]
input
```
f"a{b}"
```

ast

```
Module(
    ModModule {
        range: 0..7,
        body: [
            Expr(
                StmtExpr {
                    range: 0..7,
                    value: JoinedStr(
                        ExprJoinedStr {
                            range: 0..7,
                            values: [
                                Constant(
                                    ExprConstant {
                                        range: 0..7,            <---- is this correct (the entire string)? or should it be 2..3 ?
                                        value: Str(
                                            "a",
                                        ),
                                        kind: None,
                                    },
                                ),
                                FormattedValue(
                                    ExprFormattedValue {
                                        range: 0..7,
                                        value: Name(
                                            ExprName {
                                                range: 4..5,
                                                id: "b",
                                                ctx: Load,
                                            },
                                        ),
                                        conversion: None,
                                        format_spec: None,
                                    },
                                ),
                            ],
                        },
                    ),
                },
            ),
        ],
        type_ignores: [],
    },
)
```

**Comment by MichaReiser** [comment]
Yeah, this looks wrong.

**Comment by MichaReiser** [comment]
This should be the relevant code:

https://github.com/astral-sh/RustPython-Parser/blob/2d1f69cbb9e331bd7b29253e7f101b47d92bcbff/parser/src/string.rs#L678-L710

**Comment by MichaReiser** [comment]
@davidszotten are you interested in implementing the necessary changes in our parser or would you prefer if I or konsti tackle this?

**Comment by davidszotten** [comment]
i started having a look but i'll admit i'm struggling a bit. i guess i need to first fix the ranges e.g. in https://github.com/astral-sh/RustPython-Parser/blob/2d1f69cbb9e331bd7b29253e7f101b47d92bcbff/parser/src/string.rs#L480 and then extract/track those to use in `take_current`

**Comment by MichaReiser** [comment]
> i started having a look but i'll admit i'm struggling a bit. i guess i need to first fix the ranges e.g. in [astral-sh/RustPython-Parser@`2d1f69c`/parser/src/string.rs#L480](https://github.com/astral-sh/RustPython-Parser/blob/2d1f69cbb9e331bd7b29253e7f101b47d92bcbff/parser/src/string.rs#L480) and then extract/track those to use in `take_current`?

I'm honestly not sure. I haven't worked with this code before. 

What I noticed is that the `range` function

https://github.com/astral-sh/RustPython-Parser/blob/2d1f69cbb9e331bd7b29253e7f101b47d92bcbff/parser/src/string.rs#L75-L77

Returns the range from `self.start..self.end`. Maybe it is sufficient to change it to `self.location..self.end`?

**Comment by davidszotten** [comment]
> Maybe it is sufficient to change it to self.location..self.end?
i don't think that does the right thing

i got something reasonable working last night i think and raised a pr

**Comment by davidszotten** [comment]
> [astral-sh/RustPython-Parser#33](https://github.com/astral-sh/RustPython-Parser/pull/33)

sorry for not explicitly posting it, thought the back references github add were enough. will be more explicit in the future

**Comment by charliermarsh** [comment]
I think this is now fixed (cc @dhruvmanila).
