### ISSUE TITLE
Formatter: `TypeAlias`

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#5929]
See [PEP 695](https://peps.python.org/pep-0695/) for details on this python 3.12 feature. Not to be confused with `typing.TypeAlias` of python 3.10. The goal is to format statements in the form:

```python
# TypeAlias
type ListOrSet[T] = list[T] | set[T]
```

**Comment by zanieb** [comment]
Technically probably best to implement formatting for type parameters on functions and classes first as the implementation for that will need to be reused here.

**Comment by MichaReiser** [comment]
> Technically probably best to implement formatting for type parameters on functions and classes first as the implementation for that will need to be reused here.

I changed the issue to cover both.

**Comment by konstin** [comment]
i meanwhile had made a new issue: https://github.com/astral-sh/ruff/issues/5931

**Comment by MichaReiser** [comment]
> i meanwhile had made a new issue: https://github.com/astral-sh/ruff/issues/5931

Oh I'm sorry. I defer the decision on whether to revert my changes or close this issue to you.

**Comment by konstin** [comment]
i've reverted, i think they'll require two separate PRs
