### ISSUE TITLE
[rule suggestion] simplify `if x, if not x` to `if/else`

### ISSUE THREAD

**Issue by ScDor** [astral-sh/ruff#5969]
Instead of 
```python
if x:
    ...
if not x:
    ... 
```

Use 
```python
if x:
    ...
else:
    ... 
```

A little silly, but improves code readability.

**Comment by Mark90** [comment]
(disclaimer: I'm not a maintainer/contributor, I was just randomly looking through the issues)

I don't think this is possible; in the original way of writing both branches could execute, for example

```python
if x:
    ...
    x = False
    ...

if not x:
    ...
```

While in this example it's clear that `if not x` branch would execute, it could also be `x = <response from an external resource>` and there's no way of knowing in advance whether `x` will be truthy or falsy

**Comment by charliermarsh** [comment]
Gonna close for now as seems low priority and a little tricky to get right.
