### ISSUE TITLE
`SIM115` extend with `Path.open`

### ISSUE THREAD

**Issue by sbrugman** [astral-sh/ruff#5974]
The `SIM115` rule covers the builtin `open` function, and should also pick up on `Path.open`, which is used for the same purpose.

<img width="337" alt="open vs Path.open" src="https://github.com/astral-sh/ruff/assets/9756388/131b8837-ded8-413f-ab20-66ae0cdd0168">

**Comment by harupy** [comment]
@charliermarsh I'll take this :)
