### ISSUE TITLE
Ruff should consider adding rules first as a warning instead of a block

### ISSUE THREAD

**Issue by leandrodamascena** [astral-sh/ruff#5991]
First of all, thank you so much for working so hard to create and maintain Ruff, this is an amazing project and it has made our CI so much faster than using flak8 and other tools. This issue is not a bug, but a behavior that Ruff should consider before adding new rules/checks.

In this latest version, Ruff added the `PLR1714` rule and broke our CI because the project I work on has code that this rule complains about - https://github.com/aws-powertools/powertools-lambda-python/pull/2822. In my opinion, this can be considered a breaking change as it has changed the behavior of how Ruff checks our code and evaluates rules.

That said, I would suggest that Ruff initially add a new rule/check as a warning for at least 2 or 3 releases before considering it a block, so we have time to fix the problems before breaking the CI.

Please let me know if I'm missing anything, but you should take this into account to improve the developer experience for Ruff customers.

Thanks

**Comment by MichaReiser** [comment]
Thanks for raising this problem, and I'm sorry that we broke your CI. 

Here are some thoughts of mine on this:

* We never defined our versioning policy explicitly listing what ruff considers a breaking change. An explicit versioning policy would set expectations and help users understand the risk of laxer version ranges. 
* Releasing new rules with warning severity helps users by giving them a grace period for upgrading. However, it doesn't solve the breaking change problem by itself except if we decide only to introduce new rules when bumping the major version.

**Comment by Mr-Pepe** [comment]
I think this is an inherent "problem" of linters. What if a rule has bugs and does not identify problematic code? The bug gets fixed and suddenly your pipeline breaks because previously unidentified code smells are found. In my opinion, it's on the user to at least explicitly control the applied rules or (even better) to pin a version and explicitly update it. This also means that you have control over when your pipeline breaks and not your linter's release schedule.

**Comment by tjkuson** [comment]
> In my opinion, it's on the user to at least explicitly control the applied rules or (even better) to pin a version and explicitly update it.

For what it is worth, Rome recommends doing this on their [Getting Started](https://docs.rome.tools/guides/getting-started/#installation) and [Versioning](https://docs.rome.tools/internals/versioning/) pages.

**Comment by leandrodamascena** [comment]
> In my opinion, it's on the user to at least explicitly control the applied rules or (even better) to pin a version and explicitly update it. 

In my specific case I pin the version for all my dependencies/actions and only updated when dependabot opens a PR. In this case the CI broke on that particular PR and it was easy to fix. But, in my opinion, a clear policy on versioning release is needed here.

Imagine I pin v0.0.280 and see that Ruff has released a new v0.0.281. What's in this version? A new rule? Is this update dropping a supported version of Python? Have any configuration files changed and some existing configuration is not supported anymore? This is a minor version update, so I would expect minor changes and bugix, but today it could happen both: bug fix and new rules (besides other cases). Today we need to read the entire release notes to identify what could be a breaking change or not even in patch release. We see lot of breaking changes in patch releases - https://github.com/astral-sh/ruff/blob/main/BREAKING_CHANGES.md.

I'm not complaining about the Ruff project, it's really amazing and we trust that we are maintaining the best standards and practices using Ruff as our linter, but we need to be clear on how Ruff versioning is done so that it's simple to identify changes that we need to modify anything before using it.

**Comment by Mr-Pepe** [comment]
I agree that ruff's versioning scheme does not convey a lot of information. Even with ZeroVer one could distinguish between feature (potentially breaking) and bugfix releases. Is there a reason for only bumping patch versions?

However, I think it's important to be precise and in my opinion adding a rule is not a breaking change. A breaking change would mean dropping or changing the meaning of CLI or configuration options. A new rule might prevent a pipeline from passing, but that's due to a changed return code of the ruff invocation and not due to a break in ruff's API. That's also how Pylint is versioned.

**Comment by leandrodamascena** [comment]
> I agree that ruff's versioning scheme does not convey a lot of information. Even with ZeroVer one could distinguish between feature (potentially breaking) and bugfix releases. Is there a reason for only bumping patch versions?
> 

Yeah, I agree with this.

I think that would be nice to hear from the Ruff's maintainers what they think.

Thanks.

**Comment by leandrodamascena** [comment]
Hello Ruff team! Is it possible to have a conversation about this in the coming weeks?

This latest patch release of Ruff has brought a lot of breaking changes and I have to update my code before bumping the version. It would be really important if we had a versioning document to avoid this kind of thing.

![image](https://github.com/astral-sh/ruff/assets/4295173/d219250f-044d-4d1b-bb7f-7529106976e9)

Thank you

**Comment by charliermarsh** [comment]
Yes, I’ll add it to my queue to post some thoughts here before the end of the week.

**Comment by leandrodamascena** [comment]
> Yes, I’ll add it to my queue to post some thoughts here before the end of the week.

This is super @charliermarsh! Thank you so much!

**Comment by charliermarsh** [comment]
Thank you for bringing it up, it’s an important thing that we keep meaning to spend time on 😅

**Comment by charliermarsh** [comment]
We've had a few discussions around this internally and have some initial ideas on what a more useful versioning scheme could look like. Our tentative plan is to queue this up as a project for next month -- so we'll draft a proposal internally, circulate it for public feedback and discussion, then put a transition plan in place.

**Comment by leandrodamascena** [comment]
> We've had a few discussions around this internally and have some initial ideas on what a more useful versioning scheme could look like. Our tentative plan is to queue this up as a project for next month -- so we'll draft a proposal internally, circulate it for public feedback and discussion, then put a transition plan in place.

Hi @charliermarsh! This is really amazing to hear. If I can help in anything, please let me know.

Thank you.

**Comment by charliermarsh** [comment]
@leandrodamascena - Heads up: we now have a proposal up for our versioning scheme available in https://github.com/astral-sh/ruff/discussions/6998

**Comment by leandrodamascena** [comment]
Hi @charliermarsh! Thank you very much for tagging me here. I've already sent my impressions about this RFC and I think it's heading in the right direction. Congrats! 🚀

**Comment by charliermarsh** [comment]
We're now doing this in practice (new rules are being added under the preview flag), so gonna close out. Thanks again for the push @leandrodamascena!
