### ISSUE TITLE
Is it possible to avoid raising `PT012` if `with pytest.raises` contains a `with` statement with a single raise statement? 

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#6054]
Is it possible to avoid raising `PT012` if `with pytest.raises` contains a `with` statement with a single raise statement? 

Example

```python
def test_start_run_does_not_suppress_error():
    with pytest.raises(Exception, match="foo"):
        with mlflow.start_run(...):
            raise Exception("foo")

    assert ...
```

References

- https://github.com/m-burst/flake8-pytest-style/blob/master/docs/rules/PT012.md

**Comment by harupy** [comment]
```
def test_start_run_does_not_suppress_error():
    with pytest.raises(...), mlflow.start_run(...):
         raise Exception(...)
```

this works

**Comment by charliermarsh** [comment]
Can you say a bit more about the intent of the code? E.g. why raise within the context manager?

**Comment by harupy** [comment]
@charliermarsh @zanieb Thanks for the comments! 

> The example asserts that it does not swallow the exception (or raises it with a new type).

Yes, exactly.

**Comment by charliermarsh** [comment]
I think it's reasonable to accept any `with` with a single node body.

**Comment by harupy** [comment]
Can we only accept `with` with a non-compound-single-statement (e.g. `raise`) body?

**Comment by harupy** [comment]
Sounds good. I'll file a PR tomorrow.

**Comment by charliermarsh** [comment]
Thank you @harupy :)
