### ISSUE TITLE
Formatter: Preserve end-of-line comments in imports

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6067]
We turn dangling end-of-line comments in the parentheses of import-from into own line comments instead of preserving them

black:
```python
from .fields import (  # NOQA
    GeometryField,
)
```

ours:
```python
from .fields import (
    # NOQA
    GeometryField,
)
```

**Comment by charliermarsh** [comment]
Relatedly, this:

```python
from foo import bar, bop, bar, bop, bar, bop, bar, bop, bar, bop, bar, bop, bar, bop, bar, bop # baz
```

Gets wrapped as:

```python
from foo import (
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
    bar,
    bop,
)  # baz
```

**Comment by charliermarsh** [comment]
We already solved these problems for the `isort` module, but it's probably hard to reuse what we built there 🤔

**Comment by konstin** [comment]
I've been thinking about reusing comment placement logic in the linter, it would allow e.g. better comment handling in edits
