### ISSUE TITLE
📋 Black-compatible formatting of django

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6069]
We would like to format the black-user django as closely to black as possible. Below is a list the bugs to be solved and features necessary to reach black compatibility on django. This list is manually curated by checking `git diff` after `cargo run --bin ruff_dev -- format-dev --write django`

## Larger features
- [x] https://github.com/astral-sh/ruff/issues/5913 (single biggest diff source)
- [x] https://github.com/astral-sh/ruff/issues/5343
- [x] https://github.com/astral-sh/ruff/issues/6064

## Comment placement
- [x] https://github.com/astral-sh/ruff/issues/5675
- [x] https://github.com/astral-sh/ruff/issues/6062
- [x] https://github.com/astral-sh/ruff/issues/6067

## Breakpoints/grouping

- [x] https://github.com/astral-sh/ruff/issues/6059
- [x] https://github.com/astral-sh/ruff/issues/6063
- [x] https://github.com/astral-sh/ruff/issues/6065
- [x] https://github.com/astral-sh/ruff/issues/6066
- [x] https://github.com/astral-sh/ruff/issues/6068
- [x] https://github.com/astral-sh/ruff/issues/6499
- [x] https://github.com/astral-sh/ruff/issues/6500
- [x] https://github.com/astral-sh/ruff/issues/6505
- [x] https://github.com/astral-sh/ruff/issues/6271

## Other
- [x] https://github.com/astral-sh/ruff/issues/5781
- [x] https://github.com/astral-sh/ruff/issues/5894 
- [x] https://github.com/astral-sh/ruff/issues/5941
- [x] https://github.com/astral-sh/ruff/issues/6498
- [x] https://github.com/astral-sh/ruff/issues/5630

**Comment by konstin** [comment]
i went through the diff again an added some that i previously missed

**Comment by MichaReiser** [comment]
We don't plan on fixing the following black deviations because we believe that Ruff's formatting is more readable and implementing Black's formatting would require special handling.

* #6938
* https://github.com/astral-sh/ruff/issues/6974

**Comment by MichaReiser** [comment]
@konstin should we close this issue or do you want to do another pass?

**Comment by konstin** [comment]
I want to shift focus to user reports and prioritize from there
