### ISSUE TITLE
(🎁) Icon for Idea plugin

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#6113]
Hi 👋,

I'm attempting to address this issue:

https://github.com/koxudaxi/ruff-pycharm-plugin/issues/136.
I would like some advice from your media relations team regarding iconography, I wasn't able to find a press pack on any of your documentation.

It must be an svg: https://plugins.jetbrains.com/docs/intellij/plugin-icon-file.html#plugin-logo-requirements

I can see https://github.com/astral-sh/ruff/blob/main/docs/assets/ruff-favicon.png, but it is a png.

We have the technology to support both a light and a dark icon, although that might not be required.

**Comment by MichaReiser** [comment]
Hey @KotlinIsland . Our [brand guidance](https://brandpad.io/astral/) contains a few tool badges (in SVG). Does that suite your needs? CC @charliermarsh as our media relations team

**Comment by KotlinIsland** [comment]
Cloud
Ruff
Astral
Packaging

<details><summary>Expand to find out!</summary>
<p>

:trollface:
![image](https://github.com/astral-sh/ruff/assets/65446343/6b259f66-fe48-4091-8d3e-f0cf0867570f)



</p>
</details> 

The Ruff logo in the brand guidance is sized differently to the one used for the vscode extension. Are you happy for me to use it for the Idea icon? I think the VScode one looks better, but I can't steal that one because it's a png.


![image](https://github.com/astral-sh/ruff/assets/65446343/ef57c471-c40a-4054-bbf2-697778493739) ![image](https://github.com/astral-sh/ruff/assets/65446343/6aa5b835-e932-4930-871e-2e6deff6b907)
brand / vscode

**Comment by charliermarsh** [comment]
Yeah I will post something here later.

**Comment by charliermarsh** [comment]
Hahah those other icons were just examples to demonstrate the pattern and motivate the design of the letters, they are not Easter Eggs of things we're actually building right now :)

**Comment by charliermarsh** [comment]
Here's the icon as an SVG.

![Favicon](https://github.com/astral-sh/ruff/assets/1309177/30cb65b0-c411-471d-9452-9f221270932b)

**Comment by KotlinIsland** [comment]
# 🚀🚀🚀🚀🚀🚀🚀🚀🚀

![image](https://github.com/astral-sh/ruff/assets/65446343/9eacf81d-1e81-4e0b-98d1-cdf7df508666)
