### ISSUE TITLE
In-line ruff: noqa ignores entire file

### ISSUE THREAD

**Issue by roganartu** [astral-sh/ruff#6157]
I'm not sure if this is expected behaviour or not. After reading the docs at https://beta.ruff.rs/docs/configuration/#error-suppression I could see it being interpreted both ways so I thought it was worth raising an issue to confirm.

Given the following file:
```
from typing import Optional

import bar  # ruff: noqa
import baz

class Foo:
    x: Optional[str] = None
```
And the following ruff invocation:
```
❯ ruff --version                                                                                               
ruff 0.0.280

❯ ruff --fix --exit-non-zero-on-fix foo.py --show-fixes --select F,E,I,UP,RUF --target-version py311 --isolated
```
ruff does nothing.

If the `noqa` line changes to this:
```
import bar  # ruff: noqa: F401
```
We see something closer to what I would've intuitively expected an in-line directive to do, but it still applies `F401` to the whole file:
```
❯ ruff --fix --exit-non-zero-on-fix foo.py --show-fixes --select F,E,I,UP,RUF --target-version py311 --isolated              

Fixed 2 errors:
- foo.py:
    1 × UP007 (non-pep604-annotation)
    1 × I001 (unsorted-imports)

Found 2 errors (2 fixed, 0 remaining).

✗❯ cat foo.py
from typing import Optional

import bar  # ruff: noqa: F401
import baz


class Foo:
    x: str | None = None
```
And finally, if we instead remove the `ruff:` prefix from the `noqa` line, it only applies to the line it's suffixed to:
```
❯ cat foo.py          
from typing import Optional

import bar  # noqa
import baz

class Foo:
    x: Optional[str] = None

❯ ruff --fix --exit-non-zero-on-fix foo.py --show-fixes --select F,E,I,UP,RUF --target-version py311 --isolated

Fixed 4 errors:
- foo.py:
    2 × F401 (unused-import)
    1 × UP007 (non-pep604-annotation)
    1 × I001 (unsorted-imports)

Found 4 errors (4 fixed, 0 remaining).

✗❯ cat foo.py

import bar  # noqa


class Foo:
    x: str | None = None
```

Reviewing the docs, the in-line examples all omit the `ruff:` prefix, while the file-scope examples all include the `ruff:` prefix so perhaps this is intended. If so, I think the docs could make this behaviour clearer with an explicit callout, though absent some constraint I'm not aware of I'd argue that it's quite surprising for an in-line directive to apply to the whole file. I am very used to using eg `isort:skip` in-line to ignore single lines, so naturally reached for `ruff: noqa: <code>` for the same after migrating our projects to ruff, not realising I was quietly ignoring errors for the entire file.

**Comment by charliermarsh** [comment]
Ah yeah, this is intended, and the behavior comes from Flake8, where `# flake8: noqa` is used as a file-wide suppression and `# noqa` is used as an inline suppression. So we use `# ruff: noqa` as a file-wide exception.

I can think of two useful things to do here:

1. Clarify this in the docs further.
2. Ignore-and-warn when `# ruff: noqa` is used at the end of a line.

**Comment by roganartu** [comment]
An ignore-and-warn sounds great, thanks.

If anyone stumbles across this and is looking for a pre-commit rule to protect themselves against this in the interim, someone on my team came up with this simple one:

```
    - id: inline ruff noqa
      name: Checks that ruff noqa is not used inline.
      language: pygrep
      types: [python]
      entry: " # ruff: noqa"
      pass_filenames: true
```

**Comment by charliermarsh** [comment]
Fixed in the next release: https://github.com/astral-sh/ruff/pull/6160
