### ISSUE TITLE
`UP031` ignores `line-length`

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#6164]
For example, the following code:

```python
(
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa %s %s"
    % (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
)
```

is fixed to:

```python
(
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa {} {}".format(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
)

```

**Comment by harupy** [comment]
I have a fix.

**Comment by dhruvmanila** [comment]
Hey, thanks for opening this issue. I don't think a rule fix should consider line length, it should be the job of the formatter to break long lines.

**Comment by harupy** [comment]
@dhruvmanila Thanks for the comment. UP032 is similar to this rule and not raised if the fixed code exceeds the line length.

**Comment by harupy** [comment]
In UP031, ignoring the line length might make sense.
