### ISSUE TITLE
[Proposal] Rule to keep a collection alpha-sorted.

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#6175]
Sometimes we have large dictionaries, enums, or even lists that contain relevant config info, but the order of the elements is not relevant. For example, we have a map from each of our Django models to the relevant basenames. We need to include every model, and it's easier to verify that a model is already included if you know where to look. This can be accomplished by alpa-sorting the keys. My suggestion is for there to be a special comment I can put at the top of the collection which will cause the entries to always be alpha-sorted. Maybe `# autosort` so that other tools can adopt the convention if they so choose?

**Comment by charliermarsh** [comment]
I think this can be collapsed with https://github.com/astral-sh/ruff/issues/1198 which proposes that we support sorting collections based on isort's rules (though that's not fully decided yet).

**Comment by tylerlaprade** [comment]
Would that apply to all collections? This would potentially break other lists for which the order changes the behavior.

**Comment by charliermarsh** [comment]
No, I believe there's a pragma comment to mark such collections (see the linked issue for more).
