### ISSUE TITLE
Raw string formatting should not remove quote escape backslahes

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6186]
Currently, `print(r"\"" + "|" + r"\"''")` gets formatted as `print(r'"' + "|" + r"\"''")`, but raw strings keep the backslash so they not equivalent:

```
> print(r"\"" + "|" + r"\"''")
\"|\"''
> print(r'"' + "|" + r"\"''")
"|\"''
```

**Comment by MichaReiser** [comment]
Is this the same as https://github.com/astral-sh/ruff/issues/5941?

**Comment by konstin** [comment]
yes :see_no_evil:
