### ISSUE TITLE
UP036 auto-fixer breaks code at runtime after #5766

### ISSUE THREAD

**Issue by mrcljx** [astral-sh/ruff#6189]
After #5766 the auto-fixer for UP036 has broken some code for us:

```diff
from typing import Any

import cachetools

class MyClass:
    def __init__(self) -> None:
        self._cache: "cachetools.LRUCache[Any, Any]" = cachetools.LRUCache(maxsize=100)
```

```
ruff --isolated --select UP --fix ruff_up037.py
```

> ruff_up037.py:7:22: UP037 [*] Remove quotes from type annotation

The auto-fixer strips the quotes. However this is semantically not valid, as `LRUCache` is not `Generic` at runtime, only for the `pyi` files.

```
$ ruff --version
ruff 0.0.280
```

**Comment by clement-escolano** [comment]
I would like to add another example of the rule breaking code at runtime:

```py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dependency import MyClass

def my_func():
    result: list["MyClass"] = []
    return result
```

The quotes around `MyClass` are removed which breaks at run time.

**Comment by charliermarsh** [comment]
@clement-escolano -- Hmm, I'm unable to reproduce. This, for example, runs without error for me:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dependency import MyClass

def my_func():
    result: list[MyClass] = []
    return result

my_func()
```

Running `python foo.py` completes without error.

**Comment by mrcljx** [comment]
@charliermarsh This indeed seems to have been an IDE bug. Very sorry for bothering you with this report, thanks for Ruff!

**Comment by charliermarsh** [comment]
No worries, I went ahead and reverted any way, it seems like it's going to cause some annoyance for folks.

**Comment by zanieb** [comment]
@mrcljx Which IDE? Did you open an issue there?

**Comment by mrcljx** [comment]
<img width="639" alt="CleanShot 2023-08-01 at 19 53 31@2x" src="https://github.com/astral-sh/ruff/assets/56807/b61c38e0-3454-4e02-81d5-1f754610a0fc">

PyCharm. That said, it also had that warning earlier (but it became more visually pronounced in ^):

<img width="364" alt="CleanShot 2023-08-01 at 19 54 10@2x" src="https://github.com/astral-sh/ruff/assets/56807/e57602ab-eb1e-4d4e-b862-604a718bdaa7">
