### ISSUE TITLE
Formatter: Pragma comments

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6197]
See https://github.com/astral-sh/ruff/discussions/6670 for the proposal for the details:

* [x] https://github.com/astral-sh/ruff/issues/5630
* [x] #6771
* [x] #6772

**Comment by davidszotten** [comment]
do you have any examples of this happening? (how did you find them)

**Comment by MichaReiser** [comment]
> do you have any examples of this happening? (how did you find them)

I haven't looked closely into it but there's some related Black logic:

https://github.com/psf/black/blob/2fd9d8b339e1e2e1b93956c6d68b2b358b3fc29d/src/black/lines.py#L227-L294

and 

https://github.com/psf/black/blob/268dcb677ce80331e0ef104d8335c2ada32872fb/src/black/comments.py#L324-L335

I don't know if this is a valid noqa placement, but splitting by the arguments could change what it annotates

```python
def test(a, b, # noqa: RUFXXX
	c, d): pass

# Formatted
def test(
	a, 
	b, # noqa: RUFXXX
	c, 
	d
): pass
```

This could cause `RUFXXX` to trigger now if it suppressed `a` or `test` and not `b`.

**Comment by roshanjrajan-zip** [comment]
Hi! This is one of the problems we have in our repo. However, we use # pyright: ignore instead of # type: ignore. It would be great to have this as dynamic or something to support different use cases. Please lmk if there is anything I can do to provide more info or more help - https://github.com/psf/black/pull/3661

**Comment by MichaReiser** [comment]
Relevant lines in the Black formatter (I think) 

https://github.com/psf/black/blob/2fd9d8b339e1e2e1b93956c6d68b2b358b3fc29d/src/black/lines.py#L227-L294

**Comment by charliermarsh** [comment]
My one-second reaction is that I think we probably do a reasonably good job of avoiding the uncollapsible comment case since we don't really collapse comments (comments always expand the parent), but I don't think we handle the unsplittable line case at all.

**Comment by MichaReiser** [comment]
Some more relevant issues:
* https://github.com/psf/black/issues/195
* https://github.com/psf/black/issues/1061

**Comment by MichaReiser** [comment]
@roshanjrajan-zip The example you brought up on the Black issue is 

```python
some_long_variable_name = some_long_dict_name[0] # pyright: ignore[reportGeneralTypeIssues]
```

How would you preferred formatting look like? 

Would the following work for you?

```python
some_long_variable_name = ( # pyright: ignore[reportGeneralTypeIssues]
	some_long_dict_name[0] 
)
# Or
some_long_variable_name = some_long_dict_name[  # pyright: ignore[reportGeneralTypeIssues]
	0
] 
```

It would still require manual intervention (you have to move the comment to the opening parentheses), but it would allow you to suppress the issue.

**Comment by MichaReiser** [comment]
Black issue and PR that added the special `type: ignore` handling

* https://github.com/psf/black/issues/997
* https://github.com/psf/black/pull/1040

**Comment by MichaReiser** [comment]
See https://github.com/astral-sh/ruff/discussions/6670

**Comment by roshanjrajan-zip** [comment]
Hi @MichaReiser,

Definitely the first one is much better imo and my team agrees! That makes sense but is much Thanks so much for your work on the proposal. Taking a look at it!
```python
some_long_variable_name = ( # pyright: ignore[reportGeneralTypeIssues]
	some_long_dict_name[0] 
)
```
