### ISSUE TITLE
Run PR benchmarks on comment, rather than on every PR

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6211]
The benchmarks that run on each pull request are useful, but they're somewhat noisy and require a release build, which means we spend a lot of GitHub Action worker-time running the benchmarks, even for PRs that very-confidently won't affect performance.

Instead, we'd like to move towards running the benchmarks on selective PRs by adding a comment. Rome has a workflow for this, which we likely learn from: https://github.com/rome/tools/blob/main/.github/workflows/bench_analyzer.yml.

**Comment by zanieb** [comment]
Change needs to be on `main` for testing so I'm testing over in https://github.com/zanieb/ruff/pull/1
