### ISSUE TITLE
Collapse short multi-line import groups to one line with I001

### ISSUE THREAD

**Issue by andersk** [astral-sh/ruff#6288]
Ruff, like upstream isort, expands single-line import groups that are too long to multiple lines.

```diff
-from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple, TypeVar
+from typing import (
+    Any,
+    Callable,
+    Dict,
+    List,
+    Mapping,
+    Optional,
+    Sequence,
+    Tuple,
+    TypeVar,
+)
```

Upstream isort, but not Ruff, also does the reverse: it collapses multi-line import groups that are short enough to a single line. I think we should do this too.

```diff
-from typing import (
-    Any,
-    Callable,
-    Dict,
-    List,
-    Mapping,
-    Optional,
-    Sequence,
-    Tuple,
-)
+from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple
```

**Comment by charliermarsh** [comment]
I believe we collapse such imports if you disable [`split-on-trailing-comma`](https://beta.ruff.rs/docs/settings/#isort-split-on-trailing-comma).

I've looked into this before, and [isort's documentation](https://pycqa.github.io/isort/docs/configuration/profiles.html) states that this setting is enabled for `profile = "black"`, but in practice it appears not to be.

**Comment by andersk** [comment]
It works for me.

```console
$ cat > a.py
from typing import (
    Any,
    Callable,
)
$ isort --profile=black a.py
Fixing /tmp/a.py
$ cat a.py
from typing import Any, Callable
```

**Comment by charliermarsh** [comment]
What I meant is that: the isort documentation suggests that it _shouldn't_ be removing magic trailing commas there. The documentation says that `split-on-trailing-comma: true` is the default for that profile. But in practice it appears not to be.

**Comment by charliermarsh** [comment]
To be clear: we support this behavior, it's just not our default.

**Comment by andersk** [comment]
Got it. Feel free to close if you think this should remain as is.

**Comment by charliermarsh** [comment]
I'm torn on it but I'm going to leave as-is for now.
