### ISSUE TITLE
[Linter panic] --select=D203

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/ruff#6329]
### Ruff Version
 commit message: Make the Nodes vector generic on node type (#6328)
https://github.com/astral-sh/ruff/tree/8a5bc93fdd621aec745b6b86f7a4b880a5342625
### Command
```powershell
cargo run -p ruff_cli -- check --no-cache --select=D203 --isolated "D:\ruff-temp" *> D:\ruff-temp\output.txt
```
### Content of output.txt 
[output.txt](https://github.com/astral-sh/ruff/files/12257757/output.txt)
### Linting panicked file
[panicked_file.zip](https://github.com/astral-sh/ruff/files/12257923/panicked_file.zip)
virus scan:
https://www.virustotal.com/gui/file/47ce6dbf86e248dfeb40e4c8b10edf7031a8e5c8741a8d20354e3d2cf4f8eeb3
If you are worried about something wrong with the zip file, you can find me on Discord to get the python file in the zip.
### Ruff settings
nothing. 
### Remark
I've executed these commands before checking, I'm not sure if it has any effect.
```powershell
cargo clean
cargo build -p ruff_cli
```

**Comment by charliermarsh** [comment]
Thanks! Here's an MRE:
```python
def test_class(self):
    class C: "New-style class"
```
