### ISSUE TITLE
Autofix for UP032 swallows comment

### ISSUE THREAD

**Issue by WhyNotHugo** [astral-sh/ruff#6336]
Given this snippet:

```py
        return "data:image/{};base64,{}".format(
            ext[1:], data.decode()  # Remove the leading dot.
        )
```

Ruff autofix produces this output:

```py
        return f"data:image/{ext[1:]};base64,{data.decode()}"
```

Note that the autofixed code "swallows" the comment. See here for original context: https://github.com/WhyNotHugo/django-afip/pull/186/commits/2974184b776bede851eba0632b80d915673dea81

This is reproducible with ruff 0.0.281. [The relevant pyproject.toml is here](https://github.com/WhyNotHugo/django-afip/blob/2974184b776bede851eba0632b80d915673dea81/pyproject.toml).

**Comment by WhyNotHugo** [comment]
> Can we avoid raising UP032 if comments are present in the argument range like this^?

That's definitely one approach. Another possible approach is to raise the warning but skip it when auto-fixing.

I'll let you decide which one is best :)

**Comment by harupy** [comment]
+1

**Comment by WhyNotHugo** [comment]
That was quick! Thanks
