### ISSUE TITLE
logging-f-string falsely passes for Logger instances

### ISSUE THREAD

**Issue by jmelahman** [astral-sh/ruff#6353]
[logging-f-string](https://beta.ruff.rs/docs/rules/logging-f-string/)

* A minimal code snippet that reproduces the bug.
```
import logging

logging.info(f"{__name__}")

_LOGGER = logging.getLogger()
_LOGGER.info(f"{__name__}")
```
___
* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

```
$ ruff check --isolated --select G004 repro.py
repro.py:3:14: G004 Logging statement uses f-string
Found 1 error.

```

while `pylint`'s and `flake8` will both error for the latter,
```
$ flake8 repro.py 
repro.py:3:14: G004 Logging statement uses f-string
repro.py:6:14: G004 Logging statement uses f-string

``` 

```
$ pylint repro.py 
************* Module repro
repro.py:3:0: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
repro.py:6:0: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)

-----------------------------------
Your code has been rated at 2.50/10
 
```
___
* The current Ruff settings (any relevant sections from your `pyproject.toml`).

___
* The current Ruff version (`ruff --version`).

```
$ ruff --version
ruff 0.0.282
```

**Comment by charliermarsh** [comment]
Unfortunately we don't have the ability to know definitely whether a given variable is a logger object from the standard library. Neither does Flake8 or Pylint, so it's all a matter of heuristics that trade off false negatives vs. false positives. It looks like `_LOGGER` doesn't match our heuristic. (Anything ending with `logger` does, but it's not case insensitive.)
