### ISSUE TITLE
Formatter: Trailing comment on list gets formatted to a separate line

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#6367]
Given:

```python
[  # comment
    first,
    second,
    third
]  # another comment
```

Notice that there's no magic trailing comma, so the list will be collapsed.

Ruff:

```python
[first, second, third]  # comment
  # another comment
```

Black:

```python
[first, second, third]  # comment  # another comment
```

**Comment by charliermarsh** [comment]
I can take a look.

**Comment by dhruvmanila** [comment]
This might be relevant: I noticed it first while working on the `StmtMatch` node and one of the test cases contained a list as the match subject:

https://github.com/astral-sh/ruff/blob/a755afe7288cd17539710a074acbfad57d35be40/crates/ruff_python_formatter/tests/snapshots/format%40statement__match.py.snap#L32-L36

which gets formatted correctly (although the comments are in wrong order) when using `dangling_comments`:

https://github.com/astral-sh/ruff/blob/a755afe7288cd17539710a074acbfad57d35be40/crates/ruff_python_formatter/tests/snapshots/format%40statement__match.py.snap#L93

But, it gets formatted in the way mentioned in the issue description is using `trailing_comments` here:

https://github.com/astral-sh/ruff/blob/a755afe7288cd17539710a074acbfad57d35be40/crates/ruff_python_formatter/src/statement/stmt_match.rs#L32

**Comment by charliermarsh** [comment]
It kind of feels like a bug in line_suffix, but I need to understand the implementation better to say for certain.
