### ISSUE TITLE
End-of-line comments are ignored when breaking long lines in the formatter

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6377]
For example, we treat this as stable formatting:

```python
def get_recent_deployments(threshold_days: int) -> Set[str]:
    # Returns a list of deployments not older than threshold days
    # including `/root/zulip` directory if it exists.
    recent = set()
    threshold_date = (
        datetime.datetime.now() - datetime.timedelta(days=threshold_days)  # noqa: DTZ005
    )
```

Whereas we _should_ be formatting it as:

```python
def get_recent_deployments(threshold_days: int) -> Set[str]:
    # Returns a list of deployments not older than threshold days
    # including `/root/zulip` directory if it exists.
    recent = set()
    threshold_date = datetime.datetime.now() - datetime.timedelta(
        days=threshold_days
    )  # noqa: DTZ005
```

Since the `# noqa: DTZ005` causes the accompanying line to exceed the line length.

**Comment by charliermarsh** [comment]
I haven't looked into this at all, but @MichaReiser has mentioned that this is hard (for line suffixes to be included in the break length).

**Comment by MichaReiser** [comment]
Thanks for the detailed report. I don't know if we want to change this. I think you can argue both ways and it adds a fair amount of complexity. See https://github.com/astral-sh/ruff/issues/5630 for the details

**Comment by charliermarsh** [comment]
Thanks, missed that this was a dupe.
