### ISSUE TITLE
Parenthesizing starred `yield` inner-expression causes a syntax error

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6384]
```python
def test():
    (
        yield 
        #comment 1
        * # comment 2
        # comment 3
        test # comment 4
    )
```

Get's formatted as 

```python
def test():
    (
        yield (
            # comment 1
            # comment 2
            *# comment 3
            test
        )  # comment 4
    )
```

This is invalid syntax because the `*` needs to be in front of the parenthesized expression.

Open question: Should yield be calling into `needs_parentheses` and parenthesize the expression if it is always (and otherwise never add parentheses) instead of using `maybe_parenthesize_expression` (which also implies a different breaking logic than parenthesizing the expression directly).

Unrelated Nit: The `comment 3` placement is a bit strange

**Comment by charliermarsh** [comment]
The input code here isn't valid syntax either. You can't have a starred expression after a `yield`. Do you recall where this came up?

**Comment by MichaReiser** [comment]
> The input code here isn't valid syntax either. You can't have a starred expression after a `yield`. Do you recall where this came up?

Ruff and black parse this just fine

```python
def test():
    (
        yield 
        #comment 1
        * # comment 2
        # comment 3
        test # comment 4
    )
```
But I get a parse error in Python, and I must admit I don't know why. The full grammar specification tells me that I can have a `*` expression after the `yield` keyword and the spec doesn't mention that trivia is forbidden. 

```
yield_expr:
    | 'yield' 'from' expression 
    | 'yield' [star_expressions] 

star_expressions:
    | star_expression (',' star_expression )+ [','] 
    | star_expression ',' 
    | star_expression
```

Does Python not support `yield *`?

**Comment by charliermarsh** [comment]
It's allowed if the right-hand side is a tuple, like `yield 1, *x` or `yield *x, 1`, but I think the target itself cannot be a starred expression. I can't find this defined formally anywhere, I just spent a while looking for it. This is also true of assignments (`x = *y` is invalid, `x = *y, 1` is valid) and other statements.

**Comment by charliermarsh** [comment]
For completeness, Black formats that as:

```python
def test():
    (
        yield
        # comment 1
        *  # comment 2
        # comment 3
        test,  # comment 4
        1,
    )
```

**Comment by charliermarsh** [comment]
I can work on improving the comments.

**Comment by charliermarsh** [comment]
I guess the way to think of it is that with `yield *starred`, there's nothing to unpack `*starred` into, i.e., no containing tuple into which the elements should be unpacked?

**Comment by charliermarsh** [comment]
I think that would be `yield from generator` in Python.
