### ISSUE TITLE
Formatter adds unnecessary parentheses around return type annotations

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6431]
Contrived example:

```python
def handleMatch(self, m: Match[str], data: str) -> Union[Tuple[None, None, None], Tuple[None, None, None], Tuple[Element, int, int], Tuple[Element, int, int]]:
    pass
```

Ruff:

```python
def handleMatch(self, m: Match[str], data: str) -> (
    Union[
        Tuple[None, None, None],
        Tuple[None, None, None],
        Tuple[Element, int, int],
        Tuple[Element, int, int],
    ]
):
    pass
```

Black:

```python
def handleMatch(
    self, m: Match[str], data: str
) -> Union[
    Tuple[None, None, None],
    Tuple[None, None, None],
    Tuple[Element, int, int],
    Tuple[Element, int, int],
]:
    pass
```

**Comment by charliermarsh** [comment]
(This issue is just about the parentheses around the `Union` in the Ruff case; ignore the breaking of the parameters.)

**Comment by MichaReiser** [comment]
Id this specific to subscripts in type positions? E.g how does black break if you put a similar expression into an of condition?

**Comment by charliermarsh** [comment]
Do you mean "or" condition, like this?

```python
Union[Tuple[None, None, None], Tuple[None, None, None], Tuple[Element, int, int], Tuple[Element, int, int]] or True
```

Ruff:
```python
Union[
    Tuple[None, None, None],
    Tuple[None, None, None],
    Tuple[Element, int, int],
    Tuple[Element, int, int],
] or True
```

Black:
```python
Union[
    Tuple[None, None, None],
    Tuple[None, None, None],
    Tuple[Element, int, int],
    Tuple[Element, int, int],
] or True
```

**Comment by charliermarsh** [comment]
It looks like this behavior only kicks in if the parameters breaks ([playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AO6AKNdAD2IimZxl1N_WlbvK5WAyg6q-gZl1JqaLLCTCBcrOc_jKAgkaYzQZkMnSiPEI9QFGxRWi8ZRO_zphAO9dYnWK6C4U1JOnXyslDiEeN4vXuNQ727NsSHJ31rsleEN9NDwCw75Lmu5ObLJf4kx9pWIIKZ0OCxOkNQYtKQ1_gtbYWo5GNgoMQh7elIXvaw774P8Hs8NYRVfF1XJn6oDIv5gHdtDjgAAALI5cbmARo3AAAG_AbsHAADTg5XascRn-wIAAAAABFla)).

**Comment by charliermarsh** [comment]
(No need to engage here until I understand the behavior, I am reading the Black source.)
