### ISSUE TITLE
Docs request: linking `target-version` setting in FA docs

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#6461]
[`FA102`](https://beta.ruff.rs/docs/rules/future-required-type-annotation/) only happens if one has the [`target-version`](https://beta.ruff.rs/docs/settings/#target-version) set below Python 3.10.

Thus, it would be useful to link the `target-version` docs in the [FA general section](https://beta.ruff.rs/docs/rules/#flake8-future-annotations-fa) or [FA102 instructions](https://beta.ruff.rs/docs/rules/future-required-type-annotation/
), as it's a closely related configuration parameter.

**Comment by zanieb** [comment]
@jamesbraza makes sense to me! Are you interested in contributing it?

**Comment by jamesbraza** [comment]
I tried to add this tonight here to the general rules page.  I decided to add here (as opposed to rule-specific pages), as `target-version` impacts all sub-rules.

https://beta.ruff.rs/docs/rules/#flake8-future-annotations-fa

![screenshot of current rules section](https://github.com/astral-sh/ruff/assets/8990777/e3588327-6414-4ad0-b2a5-377093301868)

Honestly, I couldn't figure out what file to add the text:

> Configuring the [`target-version`](https://beta.ruff.rs/docs/settings/#target-version) setting to newer Python versions can nullify these rules.

Should I put this text somewhere in `crates/ruff/rules/flake8_future_annotations/rules/mod.rs`?

**Comment by charliermarsh** [comment]
I would prefer that we put those notes on the specific rules -- it's more consistent with the rest of the documentation, and the text you're referencing there is auto-generated, it would require special-casing in the documentation.

**Comment by jamesbraza** [comment]
Okay sounds good, per noting this on specific rules.

I came across https://github.com/astral-sh/ruff/pull/5105, which actually links `target-version` in the docs, just the linking is so low in the rules page that I didn't actually see it in the docs 👀 

Anyways, I opened https://github.com/astral-sh/ruff/pull/6520 to clarify `target-versions`'s role even more
