### ISSUE TITLE
Docs request: how `target-version` can support `>=` syntax

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#6462]
I support Python>=3.10 and use `ruff==0.0.284`.  I am wondering how to specify `>=3.10` using `target-version`.

Can we add to the [`target-version`](https://beta.ruff.rs/docs/settings/#target-version) docs how to specify `>=` relations?  Or alternately, can we document that one should set `target-version` to be the lowest version in the supported range?

**Comment by zanieb** [comment]
Hey!

`target-version` is your _minimum_ compatible version so you'd use `3.10`. We also infer this setting from the "requires-python" `pyproject.toml` setting.

The documentation already states

> The minimum Python version to target

How would you propose clarifying it?

**Comment by jamesbraza** [comment]
Okay gotchu, my eyes must have filtered out "minimum" text.  I propose adding an example, something like:

> The minimum Python version to target, e.g., when considering automatic code upgrades, like rewriting type annotations. For example, to represent supporting Python >= 3.10, specify `target-version = "py310"`.

**Comment by zanieb** [comment]
Sure! I'd be happy to review a pull request adding that.
