### ISSUE TITLE
merging import lines like isort

### ISSUE THREAD

**Issue by nijel** [astral-sh/ruff#6471]
After some refactoring, several imports were removed and this was left:

```python
from foo import (
    bar,
    baz,
)

bar()
baz()
```

With isort this is nicely formatted as:

```python
from foo import bar, baz

bar()
baz()
```

But ruff does no formatting here and keeps the file as is.

Ruff 0.0.284 was executed as `ruff check --fix --select I test.py` with no config, isort as `isort test.py` with not config.

**Comment by charliermarsh** [comment]
I think you’re looking for this setting: https://beta.ruff.rs/docs/settings/#isort-split-on-trailing-comma. Ruff defaults it to true while isort does not. (It’s a point of confusion as the isort docs state it defaults to true for their Black configuration, but doesn’t seem to do so in practice.)

**Comment by nijel** [comment]
Thanks, that's it. While reading through the doc, I didn't realize that something called `split` will actually toggle folding. 


And isort documentation is indeed wrong on this, I've created https://github.com/PyCQA/isort/pull/2163 for that.
