### ISSUE TITLE
zoneinfo module triggers false positive I001

### ISSUE THREAD

**Issue by Atilla** [astral-sh/ruff#6475]
Ruff considers the python stdlib module `zoneinfo` to be 3rd party now, so it sorts it in the wrong section. This disagrees with `isort`. 

It seems to have regressed between 0.0.283 and 0.0.284. 

Relevant ruff config for reference. 

 [tool.ruff.isort]
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true

[tool.ruff.isort.sections]
django = ["django"]

**Comment by charliermarsh** [comment]
zoneinfo was added in 3.9, and we now default to 3.8 as the minimum target version, if it’s not specified via a requires-python in pyproject.toml or Ruff’s target-version support. Does upping your target-version resolve this? (I don’t believe we changed anything related to module classification.)

**Comment by Atilla** [comment]
Oh, sorry, I didn't really realise when it was added to stdlib, and that's what's really happening. 

Our pyproject didn't define any of those, which it should have. 

Having the `requires-python`  or `target-version` set higher (at 3.11 in our case) works just fine. 

Thank you for the quick help.

**Comment by charliermarsh** [comment]
No worries, sorry for the churn.
