### ISSUE TITLE
Formatter: Expands function call after multi-line string

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6500]
```python
"""
{}
""".format("hi")
```
should be formatted as
```python
"""
{}
""".format(
    "hi"
)
```
This depends on the string content, e.g.
```python
"""{}""".format("hi")
```
does not get expanded.

**Comment by charliermarsh** [comment]
It looks like this no longer happens in Black's preview style: https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACHAFhdAD2IimZxl1N_Wk8Jgdzhwf57J25o-MMyJFDdKTbHVMsgIS4qWrqO3MV-q3-8HoAKJvbhIFbv_2jUfXQyafZeaz7n_OCmk3vdd7F3rCF3dZvDEseZ-a6DkyQAYnRsQVfRpAwAAXSIAQAAADwHzGqxxGf7AgAAAAAEWVo=

**Comment by charliermarsh** [comment]
Okay, I think it's https://github.com/psf/black/issues/256 and https://github.com/psf/black/pull/1879. Closing as I think this is reasonable given it's in preview.

**Comment by charliermarsh** [comment]
However, there's another behavior implemented in the linked PRs that we _don't_ have: https://github.com/astral-sh/ruff/issues/6581.
