### ISSUE TITLE
Scorecards for formatter PRs

### ISSUE THREAD

**Issue by cnpryer** [astral-sh/ruff#6506]
I can't claim this just yet, but if I can I'll come and snag it.

It'd be nice to generate this scorecard for formatter PRs
```
| project      | score   | improved  | main     |
|--------------|---------|-----------|----------|
| build        | 0.75623 | +0.001    | 0.75622  |
| cpython      | 0.75989 | +0.005    | 0.75987  |
| django       | 0.99784 | +0.002    | 0.99782  |
| transformers | 0.99470 | +0.001    | 0.99469  |
| typeshed     | 0.74853 | +0.001    | 0.74852  |
| warehouse    | 0.99585 | +0.001    | 0.99584  |
| zulip        | 0.99702 | +0.001    | 0.99701  |
```

"score" is the similarity index. "improved" is the change in "score" from `main`'s similarity index.

**Comment by charliermarsh** [comment]
(Nice-to-have but not blocking for any releases.)

**Comment by zanieb** [comment]
Related to https://github.com/astral-sh/ruff/issues/7239

**Comment by MichaReiser** [comment]
I'll close this in favor of ruff-shades. The score card was useful when trying to match Black perfectly, but becomes less useful when we start intentionally diverging from black.

**Comment by cnpryer** [comment]
The good kind of *not planned* :)
