### ISSUE TITLE
TRY003 should not apply to `NotImplementedError`

### ISSUE THREAD

**Issue by benjamin-kirkbride** [astral-sh/ruff#6528]
My understanding of the rationale according to https://beta.ruff.rs/docs/rules/raise-vanilla-args/ it's to prevent overloading exceptions to be used broadly, with the specifics of the exceptions being defined by the string passed to them.

In general, I agree with this, but for `NotImplementedError`, do we really want to encourage people subclassing it for every feature that they haven't built yet? I treat `NotImplementedError` as a slightly nicer `sys.exit("This is not supported yet")`

**Comment by tylerlaprade** [comment]
Are you attaching messages to your `NotImplementedErrors`? I find the to be self-explanatory and not need a mesage.

**Comment by benjamin-kirkbride** [comment]
I am, here is an example: 
![image](https://github.com/astral-sh/ruff/assets/3373830/9d3cc2f3-58da-47e4-8bbf-c7c8e0ad3bcb)

**Comment by charliermarsh** [comment]
But, just confirming -- that example doesn't trigger TRY003, since you're assigning to a `msg` variable, right?

https://play.ruff.rs/730cceb0-7578-4140-b09e-b52fed77e965

**Comment by benjamin-kirkbride** [comment]
@charliermarsh that is correct, but that probably could be considered a bug / limitation, as the string being defined in a variable outside of the raise statement has nothing to do with "long exception messages that are not defined in the exception class itself."
