### ISSUE TITLE
FBT002 has inaccurate / misleading documentation

### ISSUE THREAD

**Issue by benjamin-kirkbride** [astral-sh/ruff#6530]
The output is: "Boolean default value in function definition"

![image](https://github.com/astral-sh/ruff/assets/3373830/9469117c-8bbb-40a7-9c1c-1241b46a33af)

And the docs say:
> What it does
> Checks for the use of booleans as default values in function definitions.

But then it says:
> Instead, define the relevant argument as keyword-only.

and in fact that does silence the error:
![image](https://github.com/astral-sh/ruff/assets/3373830/6345bdac-ec7b-4e03-81fb-4ef8fae9c895)

But an argument being kwonly does not have anything to do with it being a "boolean default".

The first [example](https://beta.ruff.rs/docs/rules/boolean-default-value-in-function-definition/#example) already has the boolean defaults as kwonly, so the "bad" example would not even trigger the lint.

FWIW, I think that this should be split into two rules, one for default values that are not kwonly, and one for just boolean defaults.

**Comment by tjkuson** [comment]
> FWIW, I think that this should be split into two rules, one for default values that are not kwonly, and one for just boolean defaults.

I think that is the intention to be the case with `boolean-positional-arg-in-function-definition` and `boolean-default-value-in-function-definition` being separate rules.

You are right about the current documentation being confusing, though.

**Comment by charliermarsh** [comment]
My read is that FBT001 and FBT002 are meant to be basically the ~same rule with the ~same fix (make it keyword-only, so you don't have isolated `True` and `False` arguments in the call), but they're just two different heuristics for detecting the bad case. So I think the documentation on the default-value rule might be wrong.
