### ISSUE TITLE
Provide pydocstyle convention setting through the CLI

### ISSUE THREAD

**Issue by Jonas1312** [astral-sh/ruff#6553]
Hi,

I would like to set the [pydocstyle convention](https://beta.ruff.rs/docs/settings/#pydocstyle-convention) to "google", but I struggle to pass this setting to the CLI.

Is it only possible to change this setting in the toml config?

Thanks

**Comment by charliermarsh** [comment]
Yeah, it's only possible to set via the TOML file right now. We've avoided exposing every parameter to the CLI to keep the interface lean. In the future, we'll likely implement a generic mechanism for setting any argument (it's discussed a bit here: https://github.com/astral-sh/ruff/issues/5102). Sorry for the inconvenience.
