### ISSUE TITLE
Format `PatternMatchValue`

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6555]
Implement formatting for `PatternMatchValue`, see https://github.com/astral-sh/ruff/issues/5834

Implement formatting for the value pattern:

```python
match x:
    case "Relevant":
        ...
```

**Comment by dhruvmanila** [comment]
This could be delegated directly to the expression formatting. We probably just need to make sure that the comments are handled correctly around the pattern itself which might be handled automatically by the expression formatting itself.

**Comment by evanrittenhouse** [comment]
@MichaReiser I can take this
