### ISSUE TITLE
Format `PatternMatchSingleton`

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#6557]
This would be done in a similar manner as mentioned here (https://github.com/astral-sh/ruff/issues/6555#issuecomment-1677241864) except that this would be delegated to [`ExprConstant`](https://github.com/astral-sh/ruff/blob/b05574babd6224af99938a429d0b19ba3297513c/crates/ruff_python_formatter/src/expression/expr_constant.rs) formatting instead.

Implement formatting for singleton formatting

```python
match x:
    case None:
        ...
```

**Comment by LaBatata101** [comment]
I would like to work on this
