### ISSUE TITLE
Format `PatternMatchStar`

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#6558]
This would be done in a similar manner as mentioned here (https://github.com/astral-sh/ruff/issues/6555#issuecomment-1677241864) except that this would be delegated to [`Identifier`](https://github.com/astral-sh/ruff/blob/b05574babd6224af99938a429d0b19ba3297513c/crates/ruff_python_formatter/src/other/identifier.rs) formatting instead.

Implement formatting for the `*pat` pattern

```python
match x:
    case [1, 2, *rest]:
        ...
    case [*_]:
        ...
```

**Comment by harupy** [comment]
Can I work on this?
