### ISSUE TITLE
Formatter: don't break single-argument multi-line strings if the first line "fits"

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6581]
See: https://github.com/psf/black/pull/1879/files.

In Preview, Black now reformats:

```python
textwrap.dedent(
    """
    This is a
    multiline string
"""
)
```

to:

```python
textwrap.dedent("""
    This is a
    multiline string
""")
```

https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGlAIldAD2IimZxl1N_WmhEpla9DGFkUapmMYaVDChQFFzFY8lTc9V-psgZJEaxBwinapUZzdJvX8NXjM1PIFkv5tdgxiTStTWHDKc-RWzWjZvcHL8-afLVYsHq6y_3a6xN_lELxXHP-HR-0jzuepYl65gRWE-um2cLzTZWAycQpu0Bz_5igXnUT4SeJh8AAAAAAHz0sc5o1W6jAAGlAaYDAACwhaLdscRn-wIAAAAABFla

**Comment by charliermarsh** [comment]
(This is part of preview style, so perhaps not required for now.)

**Comment by charliermarsh** [comment]
@MichaReiser -- do we have a general opinion on preview style? My assumptions:

- If we implement formatting that _does_ match preview style (but doesn't match Black's stable formatting), that's okay.
- However, preview style is currently a nice-to-have and not required to ship.

**Comment by MichaReiser** [comment]
Preview style isn't a priority right now. We can implement it but we need to add a preview option first and gate the logic accordingly

**Comment by MichaReiser** [comment]
Tracked as part of [#6935](https://github.com/astral-sh/ruff/issues/6935)
