### ISSUE TITLE
ruff docs display problem

### ISSUE THREAD

**Issue by devicehzy** [astral-sh/ruff#6585]
* when i searching help by [ruff docs](https://beta.ruff.rs/docs/rules/#isort-i),i find isort rules all of is not nursery in native page,like this  
<img width="1208" alt="image" src="https://github.com/astral-sh/ruff/assets/92512639/ec1d563b-37b8-481a-9e6a-bc4e146542c7">
* when i use google translate in this page(translate to chinese),i found isort rules modfiy to is nursery  
<img width="1158" alt="image" src="https://github.com/astral-sh/ruff/assets/92512639/e69d6cb1-7416-4688-8e53-d7ffb2424bcd">     
### test  
  
*  when i set extend-select,`ruff --fix` can fix my project have problem part(isort)   
  
<img width="1219" alt="image" src="https://github.com/astral-sh/ruff/assets/92512639/54cca20f-daba-4c1e-8d2e-66d0afd795da">  

  
```
[tool.ruff]
extend-select = ["I001","I002"]
```  
* when i not set extend-select,`ruff --fix` dont work  
<img width="1081" alt="image" src="https://github.com/astral-sh/ruff/assets/92512639/e1631c03-9e2a-49c7-831c-7d4f3737fae7">
  
* so isort rules is nursery?

**Comment by devicehzy** [comment]
in test rseult,translate to chinese display page maybe is correct rendering

**Comment by charliermarsh** [comment]
The isort rules are not in the nursery, no. But you they're not in the _default_ rule set, so you have to add them to `extend-select` like you did above.

**Comment by devicehzy** [comment]
tks for solved

**Comment by charliermarsh** [comment]
No prob!
