### ISSUE TITLE
Formatter: Comprehension leading if comments

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6588]
This is not a bug per se but something I found rather confusing. The comprehension comment placement associates leading and trailing comments on the `if`s as dangling comments of the condition node:

```
// Handle comments inside comprehensions, e.g.
//
// ```python
// [
//      a
//      b
//      c
//      # leading becomes dangling on if
//      if  # trailing becomes dangling on if
//      d
// ]
// ```
```

https://github.com/astral-sh/ruff/blob/96d310fbab0112f8ab899f6d665f79a5aecdafd5/crates/ruff_python_formatter/src/comments/placement.rs#L1244-L1369

This is confusing because nodes that otherwise cannot have dangling comments now suddenly have dangling comments. I ran into this because I added assertions to `fmt_dangling_comments` in `ExprName` and `ExprCompare` to verify that the dangling comments are empty (because that's what the comment says) and got surprised by the assertions failing. 

The more common approach is to make the comments dangling comments on the comprehension and then find them again during formatting. This is probably a bit more work. Let's see how it turns out.

**Comment by charliermarsh** [comment]
I can take a look at this.

**Comment by charliermarsh** [comment]
Gonna prioritize some other things over this but agree we should do it.
