### ISSUE TITLE
Formatting breaks in `with` statement with leading comments on `as`

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#6600]
```python
with test as (
    # test
foo):
    pass
```

The above code gets formatted to:

```python
with test as
# test
(foo):
    pass
```

Most likely this can be handled in a similar manner as done in #6594

**Comment by charliermarsh** [comment]
Looks like this is still a problem.

**Comment by charliermarsh** [comment]
It looks like there are a lot of deviations in our `with` formatting, I need to revisit it holistically.
