### ISSUE TITLE
Autofix breaks code: lambda-assignment in class body

### ISSUE THREAD

**Issue by Adamantish** [astral-sh/ruff#6620]
**Version**: 0.0.284
**Config**: No config. Just evaluating ruff.
**Command**: `ruff src --isolated --fix`

Codebase uses lambdas as values in an `Enum`. Whether that be considered a nice trick or not, it certainly doesn't work if those assignments are turned into methods.

```python
class TemperatureScales(Enum):
    CELSIUS = (lambda deg_c: deg_c)
    FAHRENHEIT = (lambda deg_c: deg_c * 9 / 5 + 32)

# will not work if converted to:

class TemperatureScales(Enum):
    def CELSIUS(deg_c):
        return deg_c
    def FAHRENHEIT(deg_c):
        return deg_c * 9 / 5 + 32
```

**Comment by charliermarsh** [comment]
Thanks! It turns out that we already mark this as a manual-only fix when it's within a class. So it will automatically be avoided once we start respecting those annotations in the CLI.

**Comment by charliermarsh** [comment]
Closing this optimistically as we've now marked these as "manual only" fixes. Once we respect those annotations in the CLI, we'll avoid these breakages in the future (though the violations themselves will still be raised, so either way I'd suggest a `# noqa` here). Thanks again for reporting!
