### ISSUE TITLE
False-positive PD011 without using pandas

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#6630]
* A minimal code snippet that reproduces the bug.

```python
class Class:
    def __init__(self, values: str) -> None:
        self.values = values
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

`ruff --isolated --select PD011 bug.py `

> bug.py:3:9: PD011 Use `.to_numpy()` instead of `.values`

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

None

* The current Ruff version (`ruff --version`).

`ruff 0.0.284`

**Comment by charliermarsh** [comment]
We can't avoid these in general, but we can definitely avoid flagging them on `self` and `cls`.
