### ISSUE TITLE
Format `PatternMatchOr`

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6643]
Implement formatting of `a | b` patterns

```python
match x:
    case [x] | (y):
        ...
```

**Comment by LaBatata101** [comment]
I can take this

**Comment by charliermarsh** [comment]
Nice, thanks @LaBatata101

**Comment by charliermarsh** [comment]
You can maybe look at `expression/expr_bool_op.rs` as a reference, or the `BinOpLayout::Default` branch in `expression/expr_bin_op.rs` although that may have handling and special cases that we don't need here -- I'm not sure yet.
