### ISSUE TITLE
Question about SIM401 issue involving length of strings

### ISSUE THREAD

**Issue by nth10sd** [astral-sh/ruff#6686]
This testcase does not show `SIM401`:

```
import os

a = {}

if "A123456789012" in os.environ:
    a["A123456789012"] = os.environ["A123456789012"]
else:
    a["A123456789012"] = "123456789012345678901234567890123"
```

However, shortening the length of the `A123456789012` key by deleting the last `2` or shortening `123456789012345678901234567890123` by deleting the last `3` causes the issue to be detected by `ruff`, for example:

```
test.py:5:1: SIM401 [*] Use `a["A123456789012"] = os.environ.get("A123456789012", "12345678901234567890123456789012")` instead of an `if` block
```

May I know if this is intended?

```
$ ruff --version
ruff 0.0.285
```

**Comment by charliermarsh** [comment]
I believe we avoid flagging this if the fix would cause the code to exceed the line length?

**Comment by charliermarsh** [comment]
That’s my guess, I’d have to look it up later though if it doesn’t explain it.

**Comment by charliermarsh** [comment]
Yes that's the explanation. We may change this behavior at some point in the future once we have our own formatter.
