### ISSUE TITLE
Add `fixable` option

### ISSUE THREAD

**Issue by shager** [astral-sh/ruff#6693]
Hello,

would it be possible to implement a `fixable` configuration option for rust, similar to the `unfixable` option?
The usecase for this would be be a ruff configuration with a large number of rules, where only a small amount of auto-fixes should be allowed.
Currently, I have to replicate nearly the entire contents of the `select` option into the `unfixable` option, because I want the auto-fix only for one single rule.
This approach is also error-prone, because if I want to add another rule to `select`, I must ensure to also add it to `unfixable`.
This contradicts the "single source of truth" principle.

Of course, a simple workaround would be to use to different configuration files and run rust twice, but IMO this clearly contradicts the performance mindset of the tool.

Using the above described approach, the entire set of fixable rules could be computed as follows:

```
if `fixable` is not configured:
    CONFIGURED_FIXABLE_RULES = ALL_ACTIVATED_RULES_THAT_ARE_TECHNICALLY_FIXABLE
else:
    CONFIGURED_FIXABLE_RULES = those rules that are contained in the `fixable` option
FIXABLE_RULES = CONFIGURED_FIXABLE_RULES - CONFIGURED_UNFIXABLE_RULES
```

**Comment by shager** [comment]
Sorry for the noise, just saw that this already exists ;)
Keep up the great work =)

**Comment by charliermarsh** [comment]
Thanks, glad the existing settings were useful here :)
