### ISSUE TITLE
PYI026 autofixes ignoring target_version, not importing from typing_extensions

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#6695]
PYI026s autofix is broken. It addes TypeAlias annotations everywhere, but unconditionally imports `from typing` when it should import `from typing_extensions` if the target_version is less than py310. The bug appears to present when the PR was initially introduced in https://github.com/astral-sh/ruff/pull/5844

https://beta.ruff.rs/docs/rules/type-alias-without-annotation/

**Comment by charliermarsh** [comment]
Will take a look now.

**Comment by charliermarsh** [comment]
Thanks, will fix.
