### ISSUE TITLE
Failed to create fix for `UnnecessaryComprehensionAnyAll: Expected Expression::ListComp`

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#6713]
Ruff 0.0.285

```
ruff  *.py --select ALL
```

file content:
```
any(x.id for x in bar)
any({x.id for x in bar})
```

error:
```
error: Failed to create fix for UnnecessaryComprehensionAnyAll: Expected Expression::ListComp
PY_FILE_TEST_51040573.py:1:1: D100 Missing docstring in public module
```

[PY_FILE_TEST_51040573.py.zip](https://github.com/astral-sh/ruff/files/12394105/PY_FILE_TEST_51040573.py.zip)

**Comment by dhruvmanila** [comment]
It seems that neither `flake8-comprehension` or `flake8-pie` raises a violation when set comprehensions are used. \cc @charliermarsh any idea why this was added in https://github.com/astral-sh/ruff/pull/3824?

Sets are unordered so we might not know when `any` stops and if it benefits or not. Depending on the reason for the PR, the fix would be either to not flag it for set comprehensions or update the autofix to account for that.

**Comment by charliermarsh** [comment]
@dhruvmanila - It still makes sense to avoid allocating the set IMO. We should update the autofix, I think.
