### ISSUE TITLE
 Failed to create fix for `UnnecessaryMap: Currently not supporting default values`

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#6715]
Ruff 0.0.285

```
ruff  *.py --select ALL
```

file content:
```
_ = f"{dict(map(lambda v: (v, v**2), nums))}"
# For simple expressions, this could be: `(x if x else 1 for x in nums)`.
map(lambda x=1: x, nums)
```

error:
```
error: Failed to create fix for UnnecessaryMap: Currently not supporting default values
```

For me, this error should not be visible for user, because this message is useless for it

[PY_FILE_TEST_178904787.py.zip](https://github.com/astral-sh/ruff/files/12394161/PY_FILE_TEST_178904787.py.zip)

**Comment by dhruvmanila** [comment]
The fix might not work if there are any falsy values in the iterable. For example, if one of the values of `nums` is 0 then it would use 1 but it explicitly passed the argument.

I do agree that the message isn't useful from user perspective and instead we should avoid auto-generating the fix.

**Comment by charliermarsh** [comment]
> The fix might not work if there are any falsy values in the iterable. For example, if one of the values of nums is 0 then it would use 1 but it explicitly passed the argument.

Can you expand on this with an example?

**Comment by dhruvmanila** [comment]
Here, you can see the output is different. Default values in this context will never be used as `map` will always pass a value to the function.
```python
In [1]: nums = [0, 1, 2]

In [2]: list(map(lambda x=1: x, nums))
Out[2]: [0, 1, 2]

In [3]: list(x if x else 1 for x in nums)
Out[3]: [1, 1, 2]
```

**Comment by charliermarsh** [comment]
But, isn't this suggesting that the user change `list(map(lambda x=1: x, nums))` to `[x for x in nums]`? Why the inclusion of `if x else 1`?

**Comment by dhruvmanila** [comment]
Oh, it's mentioned in the PR description: 

> For simple expressions, this could be: `(x if x else 1 for x in nums)`.

But yeah, your suggestion would work correctly.

**Comment by charliermarsh** [comment]
We should probably just skip attempting the fix if there are default values. It's an unusual pattern and I can think of a few cases where it would cause problems.

**Comment by dhruvmanila** [comment]
Yeah, I'm thinking of the same solution.
