### ISSUE TITLE
Formatter: inconsistency for parenthesized `with` with trailing comment

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#6750]
Given:
```python
with (
    open('file')  # trailing
):
    pass


while (
    True  # trailing
):
    pass


match (
    some  # trailing
):
    case (
        pattern  # trailing
    ):
        pass
```

Formatted as:
```python
with open("file"):  # trailing
    pass


while (
    True  # trailing
):
    pass


match (
    some  # trailing
):
    case (
        pattern  # trailing
    ):
        pass

```

Notice that for `with` and `case` pattern the formatting is not collapsed while it does happen for the rest. The `case` pattern formatting was adopted from `with` which is the reason they both are the same.

I think the reason is that the nodes are different i.e, `WithItem` and `Pattern*` for `with` and `case` pattern while it's an expression for `while` which can utilize the `maybe_parenthesized_expression` helper directly.

https://play.ruff.rs/6cacd9e5-03dc-4da7-b185-fb45eb264be4

**Comment by dhruvmanila** [comment]
I'm not sure if this is intentional but if it is then for `case` pattern we should use the same formatting style as `while` i.e, collapse if < line-length.

Also, this is what Black does: https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE2AJxdAD2IimZxl1N_WmufDs0Lm7j3vYVv-fyEpjcGjBT5by7AjxamaYxYeXCngIOH5QOeUk1iGkcjENXoEKV2cVzP_u3sv7VfD5lAxtwFCY23EQCvVGAvRPjLiEhAwVufltiyjII1kYitIFme5SB59fpPGx3iYamtMmF8SVyHBiIH-3KV8PmEYg2CJ_nu-AHtt1oWkU5wBozrLxhgr3WuOQBS1mEMOm0c5AABuAG3AgAAOM6Ni7HEZ_sCAAAAAARZWg%3D%3D

**Comment by charliermarsh** [comment]
I _believe_ we want to collapse all of these (i.e., the `while` formatting is correct). We should only expand if there's `has_trailing_own_line`, not _any_ `own_line`.

**Comment by charliermarsh** [comment]
On `main`, we get the `with` right, in my testing...

**Comment by dhruvmanila** [comment]
Yeah, might be 181131272. So, the `MatchCase` needs to be updated accordingly.

**Comment by charliermarsh** [comment]
On main, it's now the case that these all preserve parentheses except the `with`.

We should make it consistent, but it's low priority and not required for the Beta.

**Comment by MichaReiser** [comment]
@charliermarsh Do you mind if we keep this issue open to ensure we fix it eventually (It's already part of the stable milestone)
