### ISSUE TITLE
Spurious PLE1300 error with 0.0.285

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [astral-sh/ruff#6767]
Follow-up of https://github.com/astral-sh/ruff/issues/6442

* A minimal code snippet that reproduces the bug:
  ```python
  print("{0:.{prec}g}".format(1.23, prec=15))
  ```
* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag:
  ```
  $ ruff --select PLE1300 file.py --isolated
  file.py:1:7: PLE1300  Unsupported format character 'g'
  Found 1 error.
  $ 
  ```
* The current Ruff version (`ruff --version`).
  ```
  $ ruff --version
  ruff 0.0.285
  $
  ```

**Comment by charliermarsh** [comment]
Thanks for re-filing @DimitriPapadopoulos.
