### ISSUE TITLE
Include trailing end-of-line comments in the measured line width

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6771]

**Comment by cnpryer** [comment]
I can help look into this, but how is it different from #5630? Are there ever situations where a trailing end-of-line comment isn't handled as a line suffix?

**Comment by MichaReiser** [comment]
> I can help look into this, but how is it different from #5630? Are there ever situations where a trailing end-of-line comment isn't handled as a line suffix?

#5630 is only about adding the reserved_width field to LineSuffix but without changing the formatting yet (always initialise it with 0). This issue is about changing the default to the actual comment with.
