### ISSUE TITLE
Rules Q002,PTH116 causes autofix error

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#6785]
Ruff 0.0.285 (latest changes from main branch)

```
ruff  *.py --select Q002,PTH116 --no-cache
```

file content:
```
﻿''"assert" ' SAM macro definitions '''
```

error:
```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `869198225PY_FILE_TEST_7954205181857005371.py`, the rule codes Q000, Q002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

```

[869198225PY_FILE_TEST_7954205181857005371.py.zip](https://github.com/astral-sh/ruff/files/12411438/869198225PY_FILE_TEST_7954205181857005371.py.zip)

**Comment by zanieb** [comment]
```
unexpected EOF while parsing at byte offset 39
---
"""assert" " SAM macro definitions "''

---

**Comment by robincaloudis** [comment]
The underlying classes and concepts handling this quote-fixing mechanism used for inline/multiline strings as well as docstrings look interesting. I give it a shot.

**Comment by robincaloudis** [comment]
Hey @zanieb, in case you are interested in the fix, I'd highly appreciate a review. I got in the habit of tagging Charlie whenever I had PR's to review, but do not want to put the pressure of reviewing on him all the time as he has probably a lot of things to do. You are a maintainer as well, aren't you? Thanks!

**Comment by zanieb** [comment]
I'll try to take a look this week.
