### ISSUE TITLE
Request: Raise error on any printf style formatting for direct string interpolation

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#6796]
As explained here: https://github.com/astral-sh/ruff/issues/3549#issuecomment-1477242022 , Ruff cannot safely autofix all usages of [printf-style-formatting (UP031)](https://beta.ruff.rs/docs/rules/printf-string-formatting/).

I would still like cases like `"%s" % may_be_a_single_element_tuple` to be raised, as they can be manually fixed.
I don't mind whether this is done through UP031 or as another rule (could be in FLY, see https://github.com/astral-sh/ruff/issues/2102#issuecomment-1400731914).

**Comment by charliermarsh** [comment]
I think this is a reasonable change. I'd love to get more opinions on it.

**Comment by Avasam** [comment]
This likely relates to #3863 (fixable groups) now.

You may still want to split it in a different rule to separately configure "fixable w/o type information" vs "unfixable (bad argument count)/risky fix". Idk.

In my case I'm looking to refactor out print-f style formatting. And prevent using it in new code across my projects. And the following risky fix is acceptable (under the understanding it *is* a **risky** fix and needs review, but can be fixed later if missed during testing):

```py
world = ("World",)
print("Hello %s" % world)
>>> Hello World

print(f"Hello {world}")
>>> Hello ('World',)
```

**Comment by Avasam** [comment]
As far as the original post goes. I really just want to prevent printf formatting and raise location in CI . Autofix or not.

As far as autofixing goes. It'd be a *nice to have* for me if printf-style strings are updated even if it causes the constructed string to change. My last comment is just because I think those two features (are likely related.

**Comment by zanieb** [comment]
I'd be happy to review a pull request that changes this rule to raise a violation when type information cannot be inferred. We should gate this behavior behind preview mode. We can explore an unsafe fix after.

**Comment by MichaReiser** [comment]
Ruff 0.8 now flags all format string usages, see https://github.com/astral-sh/ruff/issues/12461
