### ISSUE TITLE
False-positive F401 when typing is used in comment

### ISSUE THREAD

**Issue by mmhw** [astral-sh/ruff#6807]
```python
from typing import List, Callable, Tuple


keys = [
        ('IP', 'ip', str),
        ('Domain', 'domain', str)
]  # type: List[Tuple[str, str, Callable]]
```
`ruff --isolated file.py` (0.0.285) gives

> file.py:1:20: F401 [\*] `typing.Callable` imported but unused
file.py:1:30: F401 [\*] `typing.Tuple` imported but unused
file.py:1:37: F401 [\*] `typing.List` imported but unused
Found 3 errors.
[\*] 3 potentially fixable with the --fix option.

But if i remove the imports and run `mypy file.py` (1.5.1) i get the following error:

> file.py:1: error: Name "List" is not defined  [name-defined]
file.py:1: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
Found 1 error in 1 file (checked 1 source file)

**Comment by charliermarsh** [comment]
I believe this is the same as: https://github.com/astral-sh/ruff/issues/1619.
