### ISSUE TITLE
`TD` rules should respect `task-tags`

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#6808]
![image](https://github.com/astral-sh/ruff/assets/5475199/98ef7ff4-0262-4fbb-9a1d-7413dced5aa9)

I use `TODO` for long-term fixes and `FIXME` for anything that I want to remember to fix before submitting my current PR. `FIX001` is sufficient for this - I don't need the three `TD` errors. I can't disable them, because I _do_ want them applied to `TODO` comments.

**Comment by charliermarsh** [comment]
Makes sense -- I think this is similar to https://github.com/astral-sh/ruff/issues/5407.
