### ISSUE TITLE
Formatter: Unstable call arguments comment formatting

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6818]
I created this example to test some edge cases with #6817. That PR is handling the edge case correctly but I can't add the test case because the call expression formatting with the following comment itself is unstable

```python
aaa = (
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    # awkward comment
    ()
    .bbbbbbbbbbbbbbbb
)


aaa = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb# awkward comment
().bbbbbbbbbbbbbbbb
```

[Playground](https://play.ruff.rs/31db160f-3bd9-4c5d-939c-69e2819c16e2)

**Comment by MichaReiser** [comment]
> @MichaReiser - Want me to look at this, or are you taking as part of #6817?

I used a different example to work around the issue

**Comment by charliermarsh** [comment]
I'm thinking that I'll just make that a leading comment on `bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb`.

**Comment by MichaReiser** [comment]
Prettier makes it a leading comment of what comes after [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDdACAvBgFAHSg2IwCNyLKrqba76HHbCSMB6NjVAdwGtvUAJwAmGSAFtxCGCxK4AlLOIA6JhULyQAGhAQADjACW0AM7JQQwRG4AFIQjMpUAGwEBPMztKDUYXnBgAZVQpABlDKDhkADMXEzgvHz8AwL1fCIBzZBhBAFcEkHjxQ2y8gpNM5zgARVyIeBi4goArEwAPQMqauoakWOd4nQBHHrgbKz1HNBMAWki4YQXtEBzUQ2dMgGEISVRkNGdnZYqoDKqAQRgcw1Jc+Bs4QXDIxoGCgAsYcWcAdXfDeAmNJgOCBBwAwwANwBbn2YBMnhAkPyAEkoItYIEwIJDAZzujAjA3FVXoMQHorPEfj49PsKXB4oJIVEdBFGTBxqgMuI9n0mjo0oJGftSKhSHAjgKcbAfoZhDB3sgABwABh0gjgI0MGs53N5-TJMDFsvliqQACYdLl4gAVMWOA0FODicXCRbCUKoU65LlwABiEEEPKumX2qDuEBAAF8o0A). You have to be careful with comment ordering if you make it a leading comment of `bbb`, e.g if `bbb` has some trailing comments too

**Comment by charliermarsh** [comment]
I need to understand why we break the latter but not the former:

```python
aaa = (
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    # awkward comment
    ()
    .bbbbbbbbbbbbbbbb
)

aaa = (
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ()
    # awkward comment
    .bbbbbbbbbbbbbbbb
)
```

**Comment by MichaReiser** [comment]
Attribute formatting has special handling for leading comments of the next attribute 

https://github.com/astral-sh/ruff/blob/0cea4975fcfe09716c084c0a18d1b4c4cd9b8f05/crates/ruff_python_formatter/src/expression/expr_attribute.rs#L113-L117
