### ISSUE TITLE
Comments around attribute dot are moved around incorrectly

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6823]
Given:

```python
aaa = (
    aaa
    # foo
    .  # bar
    # baz
    bbb
)
```

We format like:

```python
aaa = (
    aaa.  # bar
    # foo
    # baz
    bbb
)
```

Whereas Black retains the original formatting.

I believe `# bar` is being marked as a trailing end-of-line comment on `aaa`.

**Comment by charliermarsh** [comment]
That treatment of `# bar` seems intentional (see: `handle_attribute_comment`), but it seems incorrect that it's reordered vis-a-vis `# foo` (which is marked as a leading comment of `bbb`).

**Comment by MichaReiser** [comment]
Prettier's handling seems [reasonable](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDdACAvBgFAHSg2I3VUJIwHoqMAzCCCkgOmJowCNUAnZ92twBe-Lp07VaMVCKgBKEABoQEAA4wAltADOyULx4QA7gAVeCXSlQAbI6gCeu5Zx6owAazgwAyqgC2cAAyGlBwyHQ22nDOrh5e3qpuIQDmyDA8AK7RIFF+GmmZ2dop1nAAihkQ8OGR2QBW2gAe3iXlldVIEdZRygCO7XAmhqqWaNoAtKFwACYzSiDpqBrWKQDCEH5+qMho1tbzxVDJpQCCMOkanBnwJnA8waE13dkAFjB+1gDqLxrw2olgODeCy-DQAN1+9h2YG0ThAYKyAEkoLNYN4wDwNOoTijvDB7KUnj0QKpDFFPq5VDtSXAojwwWFlCE6TAhqhklsidlEjw6TtuJw4PtlKSQjBPhppjAXsgABwABmUPDg-Q0yrZHO2nVqymknAlUplSAATMoMlEACqoTiWLrEuB+QXTWbTQKoI4ZdlwABiEB4W3OKR2qGuEBAAF9w0A)

**Comment by charliermarsh** [comment]
Prettier's handling also reorders the comments though, that strikes me as odd.

**Comment by charliermarsh** [comment]
You might be mistaking `bar` and `baz` in that example -- I don't think they convert between own-line and end-of-line, unless I'm misreading.

**Comment by MichaReiser** [comment]
> You might be mistaking `bar` and `baz` in that example -- I don't think they convert between own-line and end-of-line, unless I'm misreading.

Ahh you're right.

**Comment by charliermarsh** [comment]
We're too deep on comments. It's not healthy.
