### ISSUE TITLE
`banned-from` docs is confusing

### ISSUE THREAD

**Issue by duongdominhchau** [astral-sh/ruff#6839]
> `banned-from`
>
> A list of modules that are allowed to be imported from

I read `banned-from = ["A"]` as "ban `from A import ...` statements". However, that doesn't match the description here.

> A list of modules that are allowed to be imported from

Is there a missing "not" here or am I misunderstanding something?

Link to relevant option: https://beta.ruff.rs/docs/settings/#flake8-import-conventions-banned-from

**Comment by charliermarsh** [comment]
Yeah I think you're right, thank you -- I'll revise...
