### ISSUE TITLE
max-doc-length configuration not available but documented

### ISSUE THREAD

**Issue by amrit110** [astral-sh/ruff#6854]
Hi, it seems like the [max-doc-length](https://beta.ruff.rs/docs/settings/#pycodestyle-max-doc-length) option is not available as of v0.0.285. I get the error:

```bash
unknown field `max-doc-length`, expected one of `convention`, `ignore-decorators`, `property-decorators`
```

**Comment by charliermarsh** [comment]
It looks like you're providing that under `tool.ruff.pydocstyle` based on the message. Can you try this?

```toml
[tool.ruff.pycodestyle]
max-doc-length = 88
```

**Comment by amrit110** [comment]
Oh my bad, i thought this might be a config to wrap docstrings as well!
