### ISSUE TITLE
Ruff and Black disagree on spacing between slice indices

### ISSUE THREAD

**Issue by Arborym** [astral-sh/ruff#6861]
When running `ruff . --fix` on this line of code, it deletes a space between `1` and `:`, which is inconsistent with the Black formatter.
```diff
- self.reduce_section_group(merged_sections[i - 1 : i + 2])
+ self.reduce_section_group(merged_sections[i - 1: i + 2])
```
Running `black .` reverts this change

Another snippet example:
```diff
- for row in self.data[self.cur_page * 10 - 10 : self.cur_page * 10]
+ for row in self.data[self.cur_page * 10 - 10: self.cur_page * 10]
```

**Comment by charliermarsh** [comment]
Can you share your Ruff configuration?

**Comment by Arborym** [comment]
@charliermarsh I have found that it originates from Nursery Rule `E203`

**Comment by charliermarsh** [comment]
@Arborym - Yeah, that's right. We don't enable any rules by default that conflict with Black, but Pycodestyle (and, by extension, Flake8) contain some, a few of which would be enabeld via `NURSERY`. See: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8. I'd recommend turning off that rule explicitly if you're using the nursery set alongside Black.

**Comment by Avasam** [comment]
This issue now extends to Ruff's own formatter. But I assume the answer would be the same: Just disable that rule. So I won't open a new issue for it. 

Also https://github.com/astral-sh/ruff/discussions/7305#discussioncomment-6980767
> [...] there are some unanswered questions about how the linter/formatter configuration should co-exist.
> 
> There's no definite timeline but we plan to add configuration support as part of our [beta release](https://github.com/astral-sh/ruff/milestone/5). Expect it to take a couple of weeks, maybe even more, depending on the user feedback.
