### ISSUE TITLE
`handle_parenthesized_comment` can't deal with certain kinds of match comments 

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#6866]
The following code is valid python, but crashes `handle_parenthesized_comment`:

```python
match a:
    case A(
        # a
        b # b
        = # c
        2 # d
        # e
    ):
        pass
```

```
thread 'main' panicked at 'Unexpected token between nodes: `"\n        b # b\n        = # c\n        "`', crates/ruff_python_formatter/src/comments/placement.rs:147:17
```

The assert in question:

https://github.com/astral-sh/ruff/blob/1044d66c1cdfdfae45af74abeda07ed550131b51/crates/ruff_python_formatter/src/comments/placement.rs#L138-L153

**Comment by charliermarsh** [comment]
Probably because the b in that example isn’t a node but rather an identifier? I can own.
