### ISSUE TITLE
Incorrect f-string application

### ISSUE THREAD

**Issue by hotpxl** [astral-sh/ruff#6889]
Python file
```
a = 1
b = ("{{hello}}" "{}").format(a)
```

Command
```
target/debug/ruff check --select UP032 --fix --diff a.py
```
Vanilla Ruff, no settings, built from master
```
commit f91bacbb94e1ba0dc56b15afe388fe1f6c92e3e8 (HEAD -> main, origin/main, origin/HEAD)
Author: Charlie Marsh <charlie.r.marsh@gmail.com>
Date:   Fri Aug 25 19:47:15 2023 -0400
```

The ruff output is
```
--- a.py
+++ a.py
@@ -1,2 +1,2 @@
 a = 1
-b = ("{{hello}}" "{}").format(a)
+b = ("{{hello}}" f"{a}")
```
which is incorrect. The old code, when calling `.format`, collapses the double braces in `{{hello}}`. But the Ruff version doesn't

**Comment by zanieb** [comment]
Hi @hotpxl on what version did this used to work? Could you help us determine the cause of this regression?

**Comment by hotpxl** [comment]
I don't know if any version used to work, but I can try and git bisect

**Comment by dhruvmanila** [comment]
It seems like the case of implicit string concatenation and as there are no placeholder in the first string, it's not being considered. If you change the code to `b = ("{{hello}}{}" "{}").format(a, a)`, the fix is correct. I guess the fix could be to add the `f` prefix to all strings within `(...).format()` call?

**Comment by charliermarsh** [comment]
Yeah, we probably need to add the f prefix to all segments in the implicit concat, is my guess.

**Comment by raylu** [comment]
another example:
```py
print('{{ {} {}'.format(1, 2))
```

```diff
$ ruff check -v --select UP032 test.py --diff
--- test.py
+++ test.py
@@ -1 +1 @@
-print('{{ {} {}'.format(1, 2))
+print(f'{{ {1} {2}')
```
the correct version is `print(f'{ {1} {2}')`

**Comment by MichaReiser** [comment]
> Yeah, we probably need to add the f prefix to all segments in the implicit concat, is my guess.

Won't that potentially trigger another violation because some parts now use f-strings unnecessarily?

**Comment by raylu** [comment]
surprisingly, no

```py
print(f'{{ ')
```
```
$ ruff check . --select F541
test.py:1:7: F541 [*] f-string without any placeholders
```
but
```py
print(f'{{ ' f'{1} {2}')
```
```
$ ruff check . --select F541
[no output]
```

**Comment by charliermarsh** [comment]
No, we don't flag pieces of an implicit concatenation, if at least one segment contains a placeholder. (This is intentional.)
