### ISSUE TITLE
PTH123 shadows ASYNC101 and SIM115

### ISSUE THREAD

**Issue by Olegt0rr** [astral-sh/ruff#6892]
Let's ruff:

```python
async def foo() -> None:
    """Open something."""
    open("foo")
```

Result:
```
ASYNC101 Async functions should not call `open`, `time.sleep`, or `subprocess` methods
SIM115 Use context handler for opening files
PTH123 `open()` should be replaced by `Path.open()`

```

Let's apply fix for `PTH123` and ruff it again:

```python
async def foo() -> None:
    """Open something."""
    path = Path("foo")
    path.open("foo")

```

Result: `success`

Expected:

- ASYNC101 (cause `path.open` is also blocking as `open` for async.)
- SIM115 (cause `path.open` works the same as `open`)

**Comment by zanieb** [comment]
Sounds like `PTH123` needs to be updated to be async aware and `ASYNC101` should probably raise on `Path.open` too?

**Comment by Olegt0rr** [comment]
That's right, but it doesn't seem so easy to catch `path.open()`, since the `Path` object can be named differently.

**Comment by charliermarsh** [comment]
Gonna call this one closed by https://github.com/astral-sh/ruff/pull/9703.
