### ISSUE TITLE
Ruff does not signal E999 SyntaxError on literal assignment.

### ISSUE THREAD

**Issue by 0x6d6e647a** [astral-sh/ruff#6895]
I'm using Ruff v0.0.286 in the following.

For the following Python code:
```python
#!/usr/bin/env python
5 = 3
``` 
No output is generated from `ruff` when analyzed:
```shell
user@host $ ruff literal_assign.py
```

When run from Python:
```shell
user@host $ python literal_assign.py
  File "/home/user/literal_assign.py", line 2
    5 = 3
    ^
SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?
``` 
When analyzed with `flake8`:
```shell
user@host $ flake8 literal_assign.py
literal_assign.py:2:2: E999 SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?
```

**Comment by charliermarsh** [comment]
Yeah the parser is more permissive than the Python interpreter -- this is better than being _less_ permissive (i.e., rejecting valid code), but it'd be nice to error here.
