### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Arborym** [astral-sh/ruff#6907]
In VSC, I have code that flags rule `PLR6301`:

![image](https://github.com/astral-sh/ruff/assets/105245560/e1294b5b-2375-4841-9d77-8deb81000634)

When I click on the hyperlink to go to the Ruff documentation for that rule, this is what I see:

![image](https://github.com/astral-sh/ruff/assets/105245560/4b4baa61-99d2-41df-b7e9-9385ff9e690c)

The URL that it brings me to is: https://beta.ruff.rs/docs/rules/no-self-use

**Comment by DetachHead** [comment]
that URL works for me

![image](https://github.com/astral-sh/ruff/assets/57028336/b27d8073-b5ac-4df9-a73f-e87822c0da69)

**Comment by charliermarsh** [comment]
Thanks, I think the docs must’ve failed to update on deploy. I re-ran the job.
