### ISSUE TITLE
`E501` - option to customize line length

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#6908]
also, it seems weird that [the docs only mention PEP 8's 79 character recommendation](https://beta.ruff.rs/docs/rules/line-too-long/#why-is-this-bad) but the number it actually uses 88 characters

**Comment by charliermarsh** [comment]
Is this covered by https://beta.ruff.rs/docs/settings/#line-length ?

**Comment by DetachHead** [comment]
yeah, i guess i missed that because it wasn't mentioned in [the rule's "Options" section](https://beta.ruff.rs/docs/rules/line-too-long/#options). is there a reason for that?

**Comment by charliermarsh** [comment]
Just an oversight -- will fix, thank you.
