### ISSUE TITLE
option to treat nursery rules like normal rules

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#6910]
i just found out that there are a bunch of rules that i thought i was using because i enabled the category they were in, and i didn't know about the nursery.

it would be nice if there was an option to treat these like regular rules so i don't have to explicitly enable them all. (i prefer when linters have everything enabled by default, then i can just easily disable ones that i don't like)

**Comment by DetachHead** [comment]
leaving this here as a quick and easy way to get a list of all the nursery rules:
```js
Array.from($x("//tr[.//span[.='🌅' and @style='opacity: 1']]/td[@id]")).map(element => element.innerText)
```

run this in the devtools console on https://beta.ruff.rs/docs/rules/

**Comment by charliermarsh** [comment]
\cc @zanieb - would be solved by a preview-like mode.

**Comment by zanieb** [comment]
Yep this is on our roadmap, thanks for raising though!

**Comment by DetachHead** [comment]
looks like the new `--preview` flag does this https://github.com/astral-sh/ruff/releases/tag/v0.0.289

**Comment by zanieb** [comment]
Thanks for the bookkeeping! We're going to continue working on `--preview`, it got released early with some formatter fixes :)
