### ISSUE TITLE
Can omit parentheses layout for patterns

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6933]
Ruff avoids adding parentheses to expressions that start or end with a parenthesized node (see `can_omit_parentheses`). 

This is implemented by using `optional_parentheses` in conjunction with the `in_parentheses_only_*` builders. We need something similar for patterns to support 

```python
match test:
    case A | B | ["Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"]: ...

# Formatted
match test:
    case (
        A
        | B
        | ["Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"]
    ):
        ...

# Instead of
match test:
    case A | B | [
        "Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    ]:
        ...

```

**Comment by dhruvmanila** [comment]
This seems to be fixed: https://play.ruff.rs/e7f95918-d71e-479f-8fae-29cdaa476463

**Comment by MichaReiser** [comment]
This isn't fixed yet. We need to avoid adding the parentheses in this case. I'm not sure why the function isn't using `maybe_parenthesize(IfBreaks)` directly

https://github.com/astral-sh/ruff/blob/c05e4628b1d385d106e7e3d355f5d1d76fbfe401/crates/ruff_python_formatter/src/other/match_case.rs#L38-L58
