### ISSUE TITLE
Formatter: Nested if expression formatting

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6939]
What I can tell from the Django diff is that Black uses newlines to separate all `if` and `else` branches if any `ExprIf` in the chain breaks:

```python
# Black
_check_for_duplicates(
    "bases",
    (
        base._meta.label_lower
        if hasattr(base, "_meta")
        else base.lower()
        if isinstance(base, str)
        else base
        for base in self.bases
    ),
)
        
clone._iterable_class = (
    NamedValuesListIterable
    if named
    else FlatValuesListIterable
    if flat
    else ValuesListIterable
)

# Ruff

_check_for_duplicates(
    "bases",
    (
        base._meta.label_lower
        if hasattr(base, "_meta")
        else base.lower() if isinstance(base, str) else base
        for base in self.bases
    ),
)

clone._iterable_class = (
    NamedValuesListIterable
    if named
    else FlatValuesListIterable if flat else ValuesListIterable
)
```

Notice how ruff "flattens" the nested else clauses. 

The fix for this is likely to special case the formatting of the `else` clause if it contains a nested `ExprIf` and pass a custom layout that doesn't introduce a new `group` (it should reuse the group of the parent to ensure that either both of them expand). This is similar to the `BoolOp` formatting

**Comment by LaBatata101** [comment]
I would like to work on this one
