### ISSUE TITLE
Feature request: ignore `PLW3201` for methods marked with `@override`

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#6958]
Same request and reasoning as #3910

Python 3.12 will introduce the `override` decorator. It is already backported by `typing_extensions`.

Overridden method names are out of the dev's control when subclassing an external library. An example of this are Enum's `_generate_next_value_`. Ruff could understand that there's nothing the dev can do about the names if a method is marked with `@override` (and it'll still raise anyway on the base class if it's internal).

**Comment by brendonh8** [comment]
I can take this if nobody has yet

**Comment by charliermarsh** [comment]
Go for it @brendonh8
