### ISSUE TITLE
Add a `--check` flag to the formatter CLI

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#6966]
Avoids writing the files to disk, and exits with a non-zero status code if any files would be changed.

**Comment by MichaReiser** [comment]
We may need to wait with this until we decided on the formatter cli integration

**Comment by MichaReiser** [comment]
No, go for it, I mainly wanted to avoid unnecessary work.

**Comment by zanieb** [comment]
I propose this flag anyway :)
