### ISSUE TITLE
Fix "not a character boundary" panic in `missing_copyright_notice`

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7015]
The missing copyright notice only looks at the 1024 first bytes. However, this can go wrong for unicode text if the 1024 byte is not a character boundary (because it is a multibyte character).

https://github.com/astral-sh/ruff/blob/2cf00fee96eedaf061d1c8578d2d479eeb65658a/crates/ruff/src/rules/flake8_copyright/rules/missing_copyright_notice.rs#L36-L40

Fix: Use `is_char_boundary` to find a valid char boundary close to 1024.

```
locator.contents().is_char_boundary(1024)
```

**Comment by WindowGenerator** [comment]
@MichaReiser Hello. Can I solve this bug?

**Comment by MichaReiser** [comment]
@WindowGenerator sure. #7012 or #7027 both contain a code snipped that triggers the error and you may want to use as a test case.

**Comment by qarmin** [comment]
This is fixed and can be closed
