### ISSUE TITLE
Add `extend-ignore-names` for `flake8-self`

### ISSUE THREAD

**Issue by jaap3** [astral-sh/ruff#7018]
The [default](https://beta.ruff.rs/docs/settings/#flake8-self-ignore-names) for `ignore-names` is `["_make", "_asdict", "_replace", "_fields", "_field_defaults", "_name_", "_value_"]`.

For a Django project I want to **add**  `["_base_manager", "_default_manager",  "_meta"]`. This means I need to copy over the defaults, and then add my overrides. 

`pep8-naming` has a `extend-ignore-names` configuration option. Is it possible to provide a similar option for `flake8-self`?

**Comment by dhruvmanila** [comment]
I think I would go with adding a new config option as oppose to adding library specific names.

**Comment by MichaReiser** [comment]
> I think I would go with adding a new config option as oppose to adding library specific names.

Another idea. What if users could configure their used frameworks and we would use that information to derive the most meaningful defaults? The configuration could even be optional in the future when ruff understands the project dependencies.

**Comment by dhruvmanila** [comment]
This was added in #7194
