### ISSUE TITLE
Standardize number of lines between module-level docstring and first import

### ISSUE THREAD

**Issue by petermattia** [astral-sh/ruff#7026]
Currently, the below three snippets are all valid.

````python
"""My module."
import os
````

````python
"""My module."

import os
````

````python
"""My module."


import os
````

Is it possible to standardize to some convention? I don't have a preference for which format is best. In my experience, this is the only remaining nonstandardized import whitespace "issue".

Many thanks!

**Comment by zanieb** [comment]
Would you expect this to be enforced by an existing lint rule, a new lint rule, or our formatter?

**Comment by petermattia** [comment]
I don't see an existing lint rule for this. I don't have a strong expectation around how it would be implemented, although it seems like it could be a part of `ruff`'s `isort` functionality?

**Comment by dhruvmanila** [comment]
Do you mean something like this #3759 ?

**Comment by petermattia** [comment]
Yes exactly. I can close this issue since it's duplicated.
