### ISSUE TITLE
Formatter removes line break between implicitly concatenated strings

### ISSUE THREAD

**Issue by cnpryer** [astral-sh/ruff#7052]
Couldn't find an *exact* issue, but I'm almost certain this has been reported already. 

Maybe related to #6936
Also see #5893

Line-length: 88

Black (23.7.0):
```py
print(
    "aaaaaaa {:.2f}% "
    "aaaaaaaaaaaaaaaa".format(
        (
            ((df_aaaaaaaaaaa["fak"].isna()) | (df_aaaaaaaaaaa["fak"] == 0)).sum()
            / len(df_aaaaaaaaaaa)
        )
        * 100
    )
)
```

Ruff (0.0.287):
```py
print(
    "aaaaaaa {:.2f}% " "aaaaaaaaaaaaaaaa".format(
        (
            ((df_aaaaaaaaaaa["fak"].isna()) | (df_aaaaaaaaaaa["fak"] == 0)).sum()
            / len(df_aaaaaaaaaaa)
        )
        * 100
    )
)
```

Playground: https://play.ruff.rs/126e4315-3c75-4268-b43a-12586c5da779

**Comment by MichaReiser** [comment]
Black applies special formatting for strings inside binary expressions. We have a "cheap" implementation that works for the most simple cases but it falls short in more complicated settings. I hope to have a fix for this by next week.

**Comment by charliermarsh** [comment]
We're marking this as an intentional deviation, since the resulting code doesn't exceed line width and reduces vertical spacing. (If you make the strings longer, we _do_ split and format identically to Black.)

Can be closed once documented.
