### ISSUE TITLE
Formatter: Add end of line configuration option

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7061]
Add a `end-of-line` configuration option similar to Prettier and editorconfig that allows configuring the preferred line ending. The option supports the following value:

* lf [Default]
* crlf
* cr
* Auto

Making `Lf` the default over `Auto` is to avoid accidentally mixing line endings in a project [see](https://prettier.io/docs/en/options.html#end-of-line).

**Comment by jet-c-21** [comment]
does this feature online right now? how can I set LF as default in my `pyproject.toml`?

**Comment by dhruvmanila** [comment]
@jet-c-21 https://docs.astral.sh/ruff/settings/#format_line-ending
