### ISSUE TITLE
new `FURB` category is not on website

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#7069]
the new refurb category added in [v0.0.287](https://github.com/astral-sh/ruff/releases/tag/v0.0.287) is not on https://beta.ruff.rs/docs/rules/

![image](https://github.com/astral-sh/ruff/assets/57028336/3962e3e7-daab-4eaf-a215-45332a711946)

probably the same issue as #6907 where the deploy job failed

**Comment by charliermarsh** [comment]
Fixed, thanks.
