### ISSUE TITLE
Rule F401 cause infinite loop error

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#7078]
Ruff 0.0.285 (latest changes from main branch)

```
ruff  *.py --select F401 --no-cache --fix
```

file content:
```
import aws_cdk.aws_docdb._jsii
```

error:
```
error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `1167912.py`, the rule codes F401, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

1167912.py:1:8: F401 `aws_cdk.aws_docdb._jsii` imported but unused
Found 101 errors (100 fixed, 1 remaining).

```
[1167912.py.zip](https://github.com/astral-sh/ruff/files/12505681/1167912.py.zip)

**Comment by charliermarsh** [comment]
I'm unable to reproduce this. Is this from 0.0.285 as mentioned in the issue?

**Comment by qarmin** [comment]
From latest 0.0.287 version(copy-paste from another issue)

Looks that it was fixed already or I messed with reproducible project - I will try to find another one, this should not be so hard to do
