### ISSUE TITLE
Update identifier Unicode character validation to match Python spec

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#7169]
Python supports some, but not all Unicode characters in identifiers. See https://docs.python.org/3/reference/lexical_analysis.html#identifiers and https://peps.python.org/pep-3131/

However, Ruff is not correctly enforcing the subset of valid unicode characters e.g. in `is_identifier` 

https://github.com/astral-sh/ruff/blob/1df7e9831b90e6bfc2ab4533e20fe33e4ed5b4b4/crates/ruff_python_stdlib/src/identifiers.rs#L3-L23

This causes bugs such as:
- https://github.com/astral-sh/ruff/issues/7156
- https://github.com/astral-sh/ruff/issues/7157

We need to add validation of the specific supported subset of characters.

**Comment by MichaReiser** [comment]
See https://github.com/astral-sh/ruff/blob/4d49d5e8451277f8159a30b7da187626d3a75494/crates/ruff_python_parser/src/lexer.rs#L1182-L1187 as reference

**Comment by LaBatata101** [comment]
I can work on this one
