### ISSUE TITLE
Rule suggestion: Prevent walrus assignments in assert statements

### ISSUE THREAD

**Issue by awaelchli** [astral-sh/ruff#7205]
If you want to make your software package run with the `python -O` optimization, you might want to ensure that the code does not contain a walrus assignment in `assert` statements:

```py
y = 0
assert (x := y) is not None
x = x + 1
```

This code example runs fine normally, but if run with `python -O` the assertion gets removed and the program raises a `UnboundLocalError` because x is no longer bound. 

As a developer, I might want to configure my linter in such a way that walrus assignments are not allowed in assertion statements. This way, I can enforce that the code will be compatible running with `python -O`.

**Comment by charliermarsh** [comment]
Seems reasonable to me. We can add it as a `RUF` rule.
