### ISSUE TITLE
Formatter / Linter integration

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7232]
This depends on the CLI design, e.g. should `ruff check` or `ruff fix` run the linter, and if so, how do you opt-in/opt-out?
 
* Do we want to run the linter and the formatter at the same time? Is the formatter a normal rule code like isort or entirely separate?
* Should activating the formatter deactivate certain lint rules?
* How do we structure fix/format passes?
* When/where do we warn about invalid suppression comment (#6611)
* How to configure the formatter

**Comment by JonathanPlasse** [comment]
I would like Ruff to fix all errors before formatting the code.
The formatting at the end could be enabled/disabled via configuration in a dedicated setting like `ruff.format.run_after_fix`.
This workflow would be similar to my current use of pre-commit where I run Ruff then Black.

**Comment by MichaReiser** [comment]
@JonathanPlasse we like to do that, but we intentionally exclude integrating the formatter into our fix infrastructure for now not to explode scope. We hope to play around with integrating our formatter once it is stable.
