### ISSUE TITLE
Range formatting

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7233]
For IDE integration, it would be great if it was possible to select a certain range of code and only format that range.

**Comment by T-256** [comment]
Thats cool, not just one range, but [batch range formatting](https://code.visualstudio.com/updates/v1_82#_support-for-batch-range-formatting).

**Comment by MichaReiser** [comment]
> Thats cool, not just one range, but [batch range formatting](https://code.visualstudio.com/updates/v1_82#_support-for-batch-range-formatting).

Oh, I didn't know about that. We'll start with one range but being aware of multi range formatting may help us to decide on the design

**Comment by MichaReiser** [comment]
Relevant code in Rome/Biome 

https://github.com/biomejs/biome/blob/92be3f8fc3c13bd3ab7827b828bc4167db1d5ee0/crates/rome_formatter/src/lib.rs#L1059-L1307

**Comment by konstin** [comment]
do you know what's the use case for this from the editor side?

**Comment by MichaReiser** [comment]
I assume it's to speed up "Format changed code" when saving a file with multiple non-overlapping changed ranges.

**Comment by KraXen72** [comment]
> do you know what's the use case for this from the editor side?
  
For example, VSCode's format selection command. i use it most of the time instead of formatting the entire document.

**Comment by konstin** [comment]
Current state (only very basic statement range formatting): https://github.com/astral-sh/ruff/tree/range-formatting

**Comment by skykasko** [comment]
FYI, this capability has recently been added to Black (https://github.com/psf/black/pull/4020).

**Comment by LazyRen** [comment]
> do you know what's the use case for this from the editor side?

Addition to the `format selection` command, it seems `Format on Save Mode: modifications` also depend on this feature.

Currently, Ruff doesn't format the document automatically even if format on save is enabled if `Format on Save Mode` is set to `modifications`.
