### ISSUE TITLE
Formatter: code containing long string literal is parenthesized and generates worse output

### ISSUE THREAD

**Issue by rossmacarthur** [astral-sh/ruff#7246]
Thanks for this great project. I'm looking forward to a future where I will only need a single tool, I tried testing `ruff format` on a private project with about ~30 000 lines of Python code where we already use black. There were hardly any differences to black's output. The following is the only objectively worse formatting.

## Code

**Input**
```python
assert items == [
    "a very very very very very very very very very very very very very very very long string",
]
```

**`ruff format` Output**

```python
assert (
    items
    == [
        "a very very very very very very very very very very very very very very very long string",
    ]
)
```

**`black` Output**

```python
assert items == [
    "a very very very very very very very very very very very very very very very long string",
]

```

## Details

```
❯ ruff --version
ruff 0.0.287
```

```
❯ black --version
black, 23.7.0 (compiled: yes)
Python (CPython) 3.11.2
```

**Comment by MichaReiser** [comment]
Thanks for reporting. Let me double check if this is related to https://github.com/astral-sh/ruff/pull/6857

**Comment by MichaReiser** [comment]
This is fixed on main https://play.ruff.rs/3ce97226-6ede-4e28-8851-8cd026bfaff6
