### ISSUE TITLE
False positive for UP012?

### ISSUE THREAD

**Issue by fschulze** [astral-sh/ruff#7254]
``"Föö".encode("utf-8")`` triggers the rule, but can't be replaced with ``b"Föö"``. I use this quite often in tests.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by jaap3** [comment]
It can be replaced by `"Föö".encode()` (utf-8 is the default encoding). This stops the warning from triggering.

Not sure if that's the intention of the rule, but that's how I fixed it when I encountered it.

**Comment by fschulze** [comment]
I think ``.encode()`` seems to be the right fix. I'm not sure since when that is the default though. The docs for 3.5 say it is the default and it says: "Changed in version 3.1: Support for keyword arguments added.", so I guess that is when the default was added as well.

So maybe only the message needs to be adjusted.

**Comment by charliermarsh** [comment]
Ah okay cool -- so I confirmed we do the right thing here, but the message needs to be updated to reflect the two cases.
