### ISSUE TITLE
RUF001: exclude `×` by default

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#7255]
From https://github.com/astral-sh/ruff/issues/4859#issuecomment-1576776381, I see that you seem to consider VS Code as (one) reference to determine which characters should be reported in `RUF001`. VS Code does not flag `×`, so maybe ruff should allow it by default, too.

Otherwise, I am fine with adding `allowed-confusables = ["×"]`.

**Comment by charliermarsh** [comment]
Yeah our behavior should match VS Code. Will take a look.

**Comment by charliermarsh** [comment]
It looks like VS Code does flag it... But we may be enforcing this in places VS Code does not. Is there any other context you can provide on this one?

<img width="870" alt="Screen Shot 2023-09-11 at 11 31 12 PM" src="https://github.com/astral-sh/ruff/assets/1309177/be690af3-c278-4094-b458-23d8ae57c106">

**Comment by bersbersbers** [comment]
In fact,

- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/strings.ts#L1081C15524-L1081C15527 has ` 215,` (only) in `_default, es, fr, it, ja, ko, pl, pt-BR, qps-ploc, ru, tr, zh-hans, zh-hant`, but not in `de`.
- https://github.com/hediet/vscode-unicode-data/blob/main/out/ambiguous-formatted.json looks similar.

I have no idea on what basis these are filled, but that explains why I did not see the highlight. I think this can be closed.

**Comment by charliermarsh** [comment]
Ahh okay, that's interesting... Thanks tons for following up! I'll close for now.
