### ISSUE TITLE
Links in the PyPi documnetation are broken

### ISSUE THREAD

**Issue by Cjkjvfnby** [astral-sh/ruff#7257]
On PyPI page  https://pypi.org/project/ruff/0.0.287/ in the table of contents, headers in the document do not have anchors, so references to them are broken.

When you click a link nothing happens.
For example [Getting Started](https://pypi.org/project/ruff/#getting-started)

On the GitHub page links are ok.

![изображение](https://github.com/astral-sh/ruff/assets/171597/aad3e8db-355c-42b3-acff-db731c66b82f)

Not sure what to do with it.  Maybe just replace it with links to new documentation.

**Comment by MichaReiser** [comment]
Related Pypi issue https://github.com/pypa/readme_renderer/issues/169
