### ISSUE TITLE
UP036 (outdated-version-block) is off-by-one for the target version

### ISSUE THREAD

**Issue by oprypin** [astral-sh/ruff#7258]
If my `target-version` is `py37`, I expect the code block guarded by `sys.version_info < (3, 7)` to be dropped but it isn't.
It gets dropped for `py38`, though.

### A minimal code snippet that reproduces the bug.

```python
import sys

if sys.version_info < (3, 7):
    print('oh no')
```

### The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

```bash
ruff check test.py
```

### The current Ruff settings (any relevant sections from your `pyproject.toml`).

```toml
[tool.ruff]
target-version = "py37"
select = ["UP036"]
```

### The current Ruff version (`ruff --version`)

```
ruff 0.0.287
```

**Comment by charliermarsh** [comment]
Thanks!
