### ISSUE TITLE
JSON schema should contain `"NURSERY"`

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#7261]
`"NURSERY"` is missing here
https://github.com/astral-sh/ruff/blob/9cb5ce750e9dead53eb8235e8cfb7cff653a1cd2/ruff.schema.json#L1683-L2754

leading to errors such as this:

![image](https://github.com/astral-sh/ruff/assets/12128514/1138220b-6dac-4418-b89e-60e2bc5ba515)

**Comment by zanieb** [comment]
This may be addressed by #7195

**Comment by bersbersbers** [comment]
> This may be addressed by #7195

Doesn't look like it to me: https://github.com/astral-sh/ruff/commit/6566d00295b93af489e0d64d26d05138f5500f00#diff-0a03bc8f85db936902b6bfe61e0893160ee1c00de4253de91aa4fdb00202d73f doesn't seem to add `"NURSERY"` nor `"PREVIEW"`.

**Comment by charliermarsh** [comment]
I think these are manually excluded. The original intent was to hide them from autocompleting since we wanted to discourage ALL usage. But it ends up being too confusing that they’re marked as errors (we should fix).

**Comment by zanieb** [comment]
I think we'll want to exclude NURSERY since it's deprecated but include PREVIEW — I need to do a bit more work to decide if a PREVIEW selector makes sense though.

**Comment by zanieb** [comment]
It's only valid as in "if you are using it currently we will not break your workflow on the next release" — I hope to remove it entirely soon. I could go either way on including it in the schema but would generally prefer to push people not to use it. Perhaps we can use a `deprecated` keyword per https://github.com/json-schema-org/json-schema-spec/pull/737

If someone wants to look into support for marking schema items as deprecated I'd be curious to review :)
