### ISSUE TITLE
Ruff Isort line between import and from import

### ISSUE THREAD

**Issue by MehulBatra** [astral-sh/ruff#7275]
I saw Ruff insert a line between import and from import statements:

```
import Cython.Compiler.Options  

from Cython.Build import build_ext, cythonize 
```

How can this be avoided, I am on version v0.0.286

**Comment by zanieb** [comment]
Please don't make multiple comments — although I appreciate that you opened a new issue instead of discussing further on the old closed one :)

See my response at https://github.com/astral-sh/ruff/issues/465#issuecomment-1714318093

Let me know if you have more questions!
