### ISSUE TITLE
Apparent duplicate rule (`S307` and `PGH001`)

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#7283]
Rules [`suspicious-eval-usage` (`S307`)](https://beta.ruff.rs/docs/rules/suspicious-eval-usage/) and [`eval` (`PGH001`)](https://beta.ruff.rs/docs/rules/eval/) seem to do the same thing. If they are, in fact, distinct, then the difference between them should probably be explained in the documentation.

**Comment by zanieb** [comment]
I can confirm these look duplicated and have separate implementations. I'm not sure what we should do about it though.

**Comment by charliermarsh** [comment]
We should remove PGH001, and add a redirect to S307 (IMO).

**Comment by charliermarsh** [comment]
This got done!
