### ISSUE TITLE
`C413` breaks reversed(sorted(generator expression))

### ISSUE THREAD

**Issue by vpoverennov** [astral-sh/ruff#7289]
C413 breaks reversed(sorted(generator expression))

* The command you invoked - `ruff main.py --isolated --select C413 --fix`
* The current Ruff settings - none
* The current Ruff version - `ruff 0.0.288`

* A minimal code snippet that reproduces the bug.
```
# main.py

x = reversed(sorted(i for i in range(42)))
```

Actual result:

```
x = sorted(i for i in range(42), reverse=True)
```

Expected (notice the extra parentheses around the generator expression)
```
x = sorted((i for i in range(42)), reverse=True)
```

**Comment by dhruvmanila** [comment]
It seems that if there are any additional arguments, the generator expression needs to be parenthesized. So, this works:

```python
x = sorted(i for i in range(42))
```
