### ISSUE TITLE
Consider suggesting using tempfile classes as context managers 

### ISSUE THREAD

**Issue by NeilGirdhar** [astral-sh/ruff#7313]
Just as in:
```
f = Path.open('x')  # SIM115 Use context handler for opening files
f.close()
```
Ruff nudges the user to use context managers, Ruff should do the same for:
```
from tempfile import NamedTemporaryFile
f = NamedTemporaryFile()  # Should nudge SIM115
f.close()
```
and similarly for the other classes in `tempfile`.

**Comment by zanieb** [comment]
Sounds good to me!

**Comment by AlexWaygood** [comment]
Reopening the issue for now so we remember to stabilise this behaviour as part of Ruff 0.7
