### ISSUE TITLE
Formatter: multiline conditionals wrap differently

### ISSUE THREAD

**Issue by DanCardin** [astral-sh/ruff#7314]
Black wants to split boolean operators across lines, where they're being forced (at least here due to the comment) onto multiple lines:
```python
some_example_var = ""
if not some_example_var or (
    # A comment in the middle
    some_example_var
    and some_example_var not in some_example_var
):
    pass
```

whereas ruff wants to combine them onto one line:
```python
some_example_var = ""
if not some_example_var or (
    # A comment in the middle
    some_example_var and some_example_var not in some_example_var
):
    pass
```

I dont really have a preference, it was just one of 3 total formatting diffs over 30k LOC (one being a documented intentional diff).

**Comment by DanCardin** [comment]
Ultimately i think the effect is very marginal either way, but I think perhaps I agree.

Particularly with the deviations regarding inline comments, it seems like this gives more control over where the comment "targets", as you can insert more comments to arrive at the same formatting decision otherwise, if it's important to the block of code.

Mostly posted so it could get added to the list of intentional deviations, if you were going to keep it.

**Comment by MichaReiser** [comment]
> Mostly posted so it could get added to the list of intentional deviations, if you were going to keep it.

Thank you for reporting it. It's extremely helpful for us to have a collection of all deviations because we should either:

* Document them or
* fix them. 

So thanks again :)
