### ISSUE TITLE
Formatter undocumented deviation: power spacing

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7318]
Black formatting
```python
10 ** (2)
```
Ruff formatting
```python
10**(2)
```
Use Ruff 0.0.289 with line length 100

**Comment by MichaReiser** [comment]
Thanks. This should be easy to fix. We need to ensure that both left and right aren't parenthesized (using `is_expression_parenthesized`)

https://github.com/astral-sh/ruff/blob/41f0aad7b3e163436d870dd936e0cdd05cf4b80b/crates/ruff_python_formatter/src/expression/binary_like.rs#L364-L366
