### ISSUE TITLE
CLI: Invocation without arguments should check the current directory

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#7347]
Currently `ruff check` requires an input path. Instead, it should default to checking the current directory.

**Comment by MichaReiser** [comment]
To make sure we're aligned. Does that mean it checks the current directory respecting the `exclude` and `include` configurations? Meaning, it wouldn't check anything if `exclude = ["**"]`

**Comment by bluetech** [comment]
Various tools have a configuration for which directories to use when invoked with no arguments.
Mypy has [`files`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-files), `modules`, `packages`.
Pytest has [`testpaths`](https://docs.pytest.org/en/7.4.x/reference/reference.html#confval-testpaths).
I find it useful.

**Comment by zanieb** [comment]
Thanks for the resources! We should respect the `include` and `exclude` configuration options.

**Comment by dhruvmanila** [comment]
Related: #3970
