### ISSUE TITLE
CLI: Show source context by default in `ruff check`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#7349]
The `--show-source` flag can be used to show source information alongside violations during `ruff check`. This should be the default behavior.

`--no-show-source` can be used to return to the previous output. In the future, this option will be removed; see #7350.

**Comment by MichaReiser** [comment]
How does this align with our long-term goal of removing `--show-source` in favor of different formats?

**Comment by charliermarsh** [comment]
This is already the case in preview, right?

**Comment by T-256** [comment]
IIUC `--output-fomat=full` as default is stabilized in v0.5, why keeping this issue for v0.6 milestone?
