### ISSUE TITLE
Disable E501 for inline comments

### ISSUE THREAD

**Issue by Actticus** [astral-sh/ruff#7400]
Our project has pytest-cov, and some lines are disabled from being checked. We use the # noqa: nocover comment, and sometimes it goes beyond the length of the line. I would like to disable the E501 error for inline comments, is there any way to do this?

**Comment by charliermarsh** [comment]
Do you want E501 to be disabled for _all_ inline comments, or only pragma comments like `# noqa`?

**Comment by Actticus** [comment]
I think it's better for all inline comments

**Comment by charliermarsh** [comment]
For now, we are disabling E501 for pragma comments, but not for all inline comments (https://github.com/astral-sh/ruff/pull/7692).

**Comment by Actticus** [comment]
Ty
