### ISSUE TITLE
Ruff needs to formats files 2 times until there is nothing to format

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#7433]
Ruff 0.0.289

Ruff after formating this files once, needs to format them again, because looks that not everything is applied after first run

[Example1](https://github.com/astral-sh/ruff/files/12640339/DOWNLOADED.zip)

Here are 3 files - A2.py is original, A1.py after first run of ruff format and A0.py after second run
```
--- A2.py	2023-09-16 11:33:41.426063461 +0200
+++ A1.py	2023-09-16 11:34:05.873498261 +0200
@@ -32,8 +32,8 @@
 
 def get_rocm_smi_stats() -> Dict[str, Any]:
     command = [str(ROCM_SMI_CMD), "-a", "--json"]
-    output = (
-        subprocess.check_output(command, universal_newlines=True).strip().split("\n")
+    output = subprocess.check_output(command, universal_newlines=True).strip().split(
+        "\n"
     )[0]
     return json.loads(output)  # type: ignore

```
```
--- A1.py	2023-09-16 11:34:05.873498261 +0200
+++ A0.py	2023-09-16 11:34:15.089285492 +0200
@@ -32,9 +32,9 @@
 
 def get_rocm_smi_stats() -> Dict[str, Any]:
     command = [str(ROCM_SMI_CMD), "-a", "--json"]
-    output = subprocess.check_output(command, universal_newlines=True).strip().split(
-        "\n"
-    )[0]
+    output = (
+        subprocess.check_output(command, universal_newlines=True).strip().split("\n")[0]
+    )
     return json.loads(output)  # type: ignore
```

more files with same problems(28)

[broken_files.zip](https://github.com/astral-sh/ruff/files/12640340/broken_files.zip)

**Comment by charliermarsh** [comment]
Thanks! Internally we refer to this as an "instability". (We have tests for this over a few projects.)

**Comment by MichaReiser** [comment]
Thanks. Identifying instabilities is extremely useful (and maybe something a fuzzer can do well). This seems to be fixed as of https://github.com/astral-sh/ruff/pull/7409
