### ISSUE TITLE
Is code formatting in scope for ruff?

### ISSUE THREAD

**Issue by 89465127** [astral-sh/ruff#7439]
In most of my projects, I use isort, autoflake, pyupgrade, and black. Love that I can potentially replace the first 3 with ruff. Ideally, I would like to replace all of these, including black, with just ruff.

Wondering if in the future ruff will take up (more?) code formatting work or leave that to another tool like black?

In [this post](https://notes.crmarsh.com/python-tooling-could-be-much-much-faster) the second hypothesis is:

> An integrated toolchain can tap into efficiencies that aren’t available to a disparate set of tools.

and 

> How many times, in your pre-commit hooks, do you read your source code from disk, parse it, and traverse the parse tree?
> 
> An integrated toolchain could read every file exactly once, generate the AST exactly once, and leverage that representation throughout.
> 
> This is one of Ruff’s goals: generate all violations in a single pass, and even autofix the low-hanging fruit without a noticeable performance penalty.

So is a comprehensive black-like formatter in scope for ruff someday? Or do you see ruff as strictly a linter?

**Comment by charliermarsh** [comment]
It is! In fact we quietly shipped an alpha of our code formatter earlier this week :) Check out the announcement here: https://github.com/astral-sh/ruff/issues/1904#issuecomment-1716130700. Instructions for testing it out are available in the [README](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/README.md).
