### ISSUE TITLE
Instability in 105 python files

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#7445]
Ruff 0.0.290 latest branch
```
ruff format .
```

Simple example file
```


# TODO
```
which became
```

# TODO
```
and later
```
# TODO
```

Files - [105 files](https://github.com/astral-sh/ruff/files/12641459/unstable.files.zip)

**Comment by MichaReiser** [comment]
Only 105 files 🫣

Thank you

**Comment by MichaReiser** [comment]
I created issues for most of the files. Let's fix these and then give this another try. Thank you so much
