### ISSUE TITLE
Formatter undocumented deviation: comment line wrapping inside lists

### ISSUE THREAD

**Issue by m-richards** [astral-sh/ruff#7448]
Hi, thanks for building ruff, it's a great tool, and I've been watching eargerly for auto-formatter support for a while now. Have just tried it out and wanted to report a few formatting deviations - at least as far as I can tell from reading the readme. Apologies if any of these are duplicates, I've had a quick scan of the open issues and I can't seem to see these exact cases.

```python
# before / with black
def test_to_wkb(self):
    wkbs0 = [
        (
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        ),  # POINT (0 0)
    ]
```

```python
# after running `ruff format`
def test_to_wkb(self):
    wkbs0 = [
        (
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"  # POINT (0 0)
        ),
    ]

```
I don't know if this is related to the pragma comment rules? The difference is super minor but black's behaviour is preferable as it is the entire binary sequence inside the parentheses that is the binary encoding of a Point.

**Comment by MichaReiser** [comment]
This sounds similar to https://github.com/astral-sh/ruff/pull/7269 

Although implementing a generic solution could be challenging. But it may be worth special casing it for implicit concatenated strings.

My recommendation would be to make this a leading comment instead. leading comments tend to work better than trailing comments

```python
def test_to_wkb(self):
    wkbs0 = [
		 # POINT (0 0)
        (
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        )
    ]
```

Although Ruff get's this wrong too (for the same reasons):

```python
def test_to_wkb(self):
    wkbs0 = [
        (
			# POINT (0 0)
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        )
    ]
```

**Comment by MichaReiser** [comment]
For comparison, Prettier always moves comments out of the parentheses. This would work well in the second example I made, but prevents you from e.g. documenting the first item.

**Comment by charliermarsh** [comment]
For now, our priority is gonna be to fix the suggested alternative:

```python
def test_to_wkb(self):
    wkbs0 = [
        # POINT (0 0)
        (
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        ),
        (1)
    ]
```

Which we currently format as:

```python
def test_to_wkb(self):
    wkbs0 = [
        (
            # POINT (0 0)
            b"\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        ),
        (1),
    ]
```

We want this to be part of the Beta.

It'd be nice to fix the trailing comment case here, but we see it as lower-priority. It may fall out of the same solution.

**Comment by charliermarsh** [comment]
(This probably requires rethinking how we handle parenthesized comments in general.)
