### ISSUE TITLE
Formatter undocumented deviation: ruff recurses into .git folder and can try to format files inside.

### ISSUE THREAD

**Issue by m-richards** [astral-sh/ruff#7450]
This is a quite an obscure edge case, but is still a behaviour difference with black. I maintain an open source project, and have previously checked out a branch from a contributor which they named `th-geodataframe.py`. This creates files `.git\logs\refs\heads\th-geodataframe.py` and `.git\refs\heads\th-geoseries.py` as part of git's internal data.

I ran `ruff format .` in the root of the repository to test out how the formatting compares to black and noticed it generated errors for these files, I guess ruff tries to format these as they are text files with a .py extension I guess.

I'm not exactly sure what black does here - why it doesn't format these (or if it does, why there are no errors). I suppose it might either blanket ignore .git folders or somehow try to check if a file contains valid python.

It seems it could be reasonable to never recurse into the .git folder? (or at least folders besides hooks, as one could have python file hooks)

It also seems fair enough to call this a weird edge case and not do anything special for it.

**Comment by MichaReiser** [comment]
Uhh, that shouldn't happen. Any chance you set [`respect-gitignore`](https://docs.astral.sh/ruff/settings/#respect-gitignore)[#](https://docs.astral.sh/ruff/settings/#respect-gitignore) to false in your project?

**Comment by m-richards** [comment]
Ah, I managed to cut down to a minimal reproducer - it's because we have exclude set:
```toml

[tool.ruff]

exclude = ["doc/*"]

```
And I think we should be using extend-exclude instead?

**Comment by dhruvmanila** [comment]
> And I think we should be using extend-exclude instead?

Yes, using `extend-exclude` should ignore the `.git` directory as it's included in the default value for [`exclude`](https://docs.astral.sh/ruff/settings/#exclude) option.
