### ISSUE TITLE
Extend `bad-dunder-method-name` to permit `__html__`

### ISSUE THREAD

**Issue by jaap3** [astral-sh/ruff#7478]
The `__html__` dunder method is used by [Jinja2](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.escape), [Django](https://docs.djangoproject.com/en/4.2/_modules/django/utils/safestring/) and other frameworks (?) to return the "safe" html representation of an object.

There doesn't seem to be an equivalent of [pylint's good-dunder-names](https://pylint.readthedocs.io/en/stable/user_guide/configuration/all-options.html#good-dunder-names) in ruff. Would it be acceptable to add `__html__` to the allow list?

**Comment by jaap3** [comment]
I'm willing to make a PR if this is accepted

**Comment by charliermarsh** [comment]
Yes that seems reasonable. PR appreciated!
