### ISSUE TITLE
Improve warnings when ignoring preview rules without preview flag

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#7491]
```shell
ruff check --isolated --ignore PLC1901,PLR0904  # version 0.0.290
```
outputs
```
warning: Selection of nursery rule `PLC1901` without the `--preview` flag is deprecated.
warning: Selection `PLR0904` has no effect because the `--preview` flag was not included.
```

I think these warnings are rather irrelevant - they basically confirm what the users wants to do anyway, which is *not* select these rules.

**Comment by silverwind** [comment]
Also noticed this strange warning, had `PLC1901` in my `ignore` config for a long time, ruff v290 now suddenly started warning about it.

**Comment by hmvp** [comment]
> Also noticed this strange warning. I had `PLC1901` in my `ignore` config for a long time (because it's a unsafe rule), ruff v0.0.290 now suddenly started warning about it.

That rule moved to the nursery

**Comment by silverwind** [comment]
Does nursery mean it's disabled by default now when I `select=["PL"]`?

**Comment by charliermarsh** [comment]
@silverwind - Yeah, if you do `select=["PL"]`, `PLC1901` will _not_ be included.

**Comment by silverwind** [comment]
Thanks, I'll remove it then from `ignore` and I see the warning also makes sense. It should probably explain better what the "nursery" is, the online docs also have no info on this topic.

**Comment by charliermarsh** [comment]
"Nursery" was changed to ["Preview"](https://docs.astral.sh/ruff/preview/) -- we should probably update the docs to reflect that it used to be called "Nursery".

**Comment by charliermarsh** [comment]
\cc @zanieb - when you're back :)

**Comment by zanieb** [comment]
"select" is kind of a broad term in this warning, we're referring to the use of a _rule selector_ which can be used with any of the command line options e.g. `--select` / `--ignore`. I figured this would be a little ambiguous and we could improve it with more careful messaging in a follow-up — thanks for your feedback!

**Comment by frenck** [comment]
Just ran into this on the Home Assistant project.

A rule was ignored explicitly and still gives us this warning. Meaning if you run it with `--preview`, it still was ignored. But that is now something we should not do anymore?

It is a bit odd as we don't want it in preview but also want to ignore it if it gets out of preview/nursery.

I'm not sure why an ignore flag has to trigger this warning. Wat is the goal for triggering the warning in that case? What is the risk if it would still be set to be ignored while only available in preview?

I'm just confused about what problem is solved here and why this warning is added for this specific case report in this issue.

../Frenck

**Comment by zanieb** [comment]
Hey @frenck 

The implementation is just naively collecting all of the selector options e.g. https://github.com/astral-sh/ruff/blob/316f75987d138028a282333f8cce780f064f4000/crates/ruff_workspace/src/configuration.rs#L703-L712

This warning is not explicitly targetting use of `--ignore <RULE>`, it applies to _any_ option in which `<RULE>` is used. This was just the simplest way to implement the warning alongside our existing warnings, but we can update that iterator to be aware of the specific option used to remove or reword the message as needed.

I'll be working on this soon.
