### ISSUE TITLE
Should preview mode also contained important rule behavior changes?

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7509]
`FBT001` could be changed to have more positive cases. This will break the current behavior.
Should we include rule behavior changes in the preview mode?

> This could introduce a lot of new positives.
> Is it possible to have a preview of rules behavior change?

_Originally posted by @JonathanPlasse in https://github.com/astral-sh/ruff/issues/7501#issuecomment-1724351749_

**Comment by MichaReiser** [comment]
I believe yes, once we reach 0.1.0 but depends on the change. See the [versioning policy](https://github.com/astral-sh/ruff/discussions/6998) proposal.

**Comment by charliermarsh** [comment]
Technically we don't need to adhere to this until 1.0, but yes, the intent is that significant rule changes (that aren't bug fixes) are gated behind preview, and go out in minor releases. However, there's a carveout for bug fixes (as I said) and changes that adhere to the intent of the rule, so this one is a good test case for that criteria.

**Comment by charliermarsh** [comment]
Would love to get @zanieb's input next week.

**Comment by MichaReiser** [comment]
> Technically we don't need to adhere to this until 1.0, but yes, the intent is that significant rule changes (that aren't bug fixes) are gated behind preview, and go out in minor releases. However, there's a carveout for bug fixes (as I said) and changes that adhere to the intent of the rule, so this one is a good test case for that criteria.

This should already apply with 0.1.0

**Comment by charliermarsh** [comment]
Oh sorry, that was a typo.

**Comment by zanieb** [comment]
Yes this sounds great to me and follows the intent of preview. I don't think we need to wait until `0.1.0` to begin using this.
