### ISSUE TITLE
[rule] replace `if key in dict: del dict[key]` with `dict.pop(key, None)`

### ISSUE THREAD

**Issue by dorschw** [astral-sh/ruff#7537]
I'd suggest it to flake8-simplify, but their repo seems inactive since late March 😞 
If there's a better place to suggest it, please let me know and I'll copy it there.

```diff
- if key in dictionary:
-     del dictionary[key]
+ dictionary.pop(key, None)
```

**Comment by charliermarsh** [comment]
Seems reasonable to me as a `ruff` rule.

**Comment by Skylion007** [comment]
You should bring this rule up to the flake8-simplify folks too, they love this kind of stuff and if they implement it, we have a nice rule code for us to build on.

**Comment by ScDor** [comment]
Some PRs there were merged recently, I may be able to implement it in
python there.

**Comment by harupy** [comment]
@charliermarsh Can I work on this?
