### ISSUE TITLE
Rename `pydocstyle.max-doc-length` to `max-doc-width`

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7574]
Rename `pydocstyle.max-doc-length` to `doc-width` to align with other text width options and clarify that the option is about the text width and not character or byte length. 

The `max-doc-length` option should act as an alias but Ruff should warn and hint users towards migrating to the new option.

**Comment by ngnpope** [comment]
Wondering whether the `max-` prefix is relevant? 🤔

If we are going for `line-width`, as the general line width value (without `max-`), would `doc-line-width` make more sense?
