### ISSUE TITLE
First string token is always considered as docstring

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#7595]
In the [docstring detection state machine](https://github.com/astral-sh/ruff/blob/82978ac9b54e16286e5b2fa60240e06ad8cc88d7/crates/ruff_linter/src/lex/docstring_detection.rs), the first string token is always considered as docstring without considering the context. For example, the first strings in the following example are considered as docstrings:

```python
"abcba".strip("ab")
```

On the opposite end, if multiple strings are implicitly concatenated then only the first string is considered as docstring:

```python
"first" "second"
```

Python considers the entire string (`"firststring"`) as the module docstring but the state machine will only say that `"first"` is docstring while `"second"` is a normal string.

**Comment by charliermarsh** [comment]
Yeah, we need something more reliable here. I wish this could use our AST-based docstring detection -- that is, I wish we could just move these rules to the AST checker.

We _could_ move them, but we'd then have to re-lex the strings in the AST for any implicit concatenations, which seems expensive.

**Comment by MichaReiser** [comment]
> We could move them, but we'd then have to re-lex the strings in the AST for any implicit concatenations, which seems expensive.

Why is this necessary, considering that python detects the whole string as docsttring? 

Let's see if @dhruvmanila ends up refactoring our string representation anyway to represent string parts in the AST.

**Comment by charliermarsh** [comment]
@MichaReiser -- Because the string could contain comments in-between the segments:

```python
x = (
    "foo" # comment
    "bar"
)
```

This isn't a problem in the token-based model because we iterate over string segments and comment tokens. But in the AST, we'd need to delineate the string contents from the comments.

**Comment by MichaReiser** [comment]
> This isn't a problem in the token-based model because we iterate over string segments and comment tokens. But in the AST, we'd need to delineate the string contents from the comments.

I see, but we would only need to do this for strings where implicit concatenated is true. So it shouldn't be as many? But I guess it is now more complicated with the `fstrings` support.

**Comment by dhruvmanila** [comment]
I haven't explored it fully but I don't think it'll be an issue once the new AST node is merged.

**Comment by charliermarsh** [comment]
I think we can now solve this.

**Comment by dhruvmanila** [comment]
I think we would need to move the existing rules which uses the state machine to be based on AST instead of tokens. There aren't many -- `RUF001-003` and `flake8-quotes` rules. I think the only reason they're token based is because of implicit string concatenation.

The implementation should probably be in the semantic model.

**Comment by dhruvmanila** [comment]
No, the last rule (`Q003`) is remaining, maybe I'll pick that up this weekend. I remember that was a bit difficult because it supports PEP 701 syntax.
