### ISSUE TITLE
Format jupyter notebooks

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#7598]
We currently lint and fix python files and jupyter notebook but only format python files.

Formatting jupyter notebooks can reuse the infrastructure we use to lint and fix them, it should mostly be a matter of formatting each cell in a loop (being mindful of leading and trailing newlines) and adding a test.

**Comment by charliermarsh** [comment]
This isn't _required_ for the Beta but it'd be nice to have for the release announcement and such.

**Comment by charliermarsh** [comment]
I have a working version of this going.
