### ISSUE TITLE
Formatter instability: own-line comments on function parameter defaults

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#7603]
Given:

```python
def f2(x:e2=
    #
"foo") -> r2:
    pass

def f3(#
 x:e3#=
  = #
    #
 123#
#
) -> r3:
    pass
```

We first format as:

```python
def f2(
    x: e2 = #
    "foo",
) -> r2:
    pass


def f3(  #
    x: e3 = #  # =  #
    123,  #
    #
) -> r3:
    pass
```

And then as:

```python
def f2(
    x: e2 = "foo",  #
) -> r2:
    pass


def f3(  #
    x: e3 = 123,  #  # =  #  #
    #
) -> r3:
    pass
```

We probably need to treat those comments as dangling, as for comments around colons.

Sourced from https://github.com/astral-sh/ruff/issues/7590 (`A_870428921595896654.py`).

**Comment by charliermarsh** [comment]
The challenge there is that the leading comment could be within parentheses.

**Comment by MichaReiser** [comment]
> The challenge there is that the leading comment could be within parentheses.

I see. Would be good if we have a solution for this that works consistently. E.g. a `has_leading_comments_outside_parentheses`.  There's another issue around this as well but I can't find it right now

**Comment by MichaReiser** [comment]
As a diff

```diff
---
--- Formatted once
+++ Formatted twice
@@ -1,13 +1,11 @@
 def f2(
-    x: e2 = #
-    "foo",
+    x: e2 = "foo",  #
 ) -> r2:
     pass
 
 
 def f3(  #
-    x: e3 = #  # =  #
-    123,  #
+    x: e3 = 123,  #  # =  #  #
     #
 ) -> r3:
     pass
---

```

**Comment by charliermarsh** [comment]
Keeping this for the Beta. It's likely uncommon but should be fixed.

**Comment by charliermarsh** [comment]
(I'd suggest taking a look at #7493 and #7495, we can handle similarly to those.)
