### ISSUE TITLE
Make B006 fixes inserted after import

### ISSUE THREAD

**Issue by Hoxbro** [astral-sh/ruff#7616]
When running `ruff --select=B006 b006.py --fix` on a function like this
``` python
def test(arg=[]):
    import os
```

the fix would be:
``` python
def test(arg=None):
    if arg is None:
        arg = []
    import os
```

I would like to see the fix move below the import like this:
``` python
def test(arg=None):
    import os
    if arg is None:
        arg = []
```

For my own enjoyment, I have already started implementing this [here](https://github.com/Hoxbro/ruff/pull/1). Though, as this is the first time I have written any Rust, it could likely be improved upon :sweat_smile:

**Comment by charliermarsh** [comment]
This makes sense to me!

**Comment by Hoxbro** [comment]
Awesome, can you assign it to me?
