### ISSUE TITLE
Improvements to RUF15

### ISSUE THREAD

**Issue by Hoxbro** [astral-sh/ruff#7618]
I have two (small) suggestions for improving [unnecessary-iterable-allocation-for-first-element (RUF015)](https://docs.astral.sh/ruff/rules/unnecessary-iterable-allocation-for-first-element/#unnecessary-iterable-allocation-for-first-element-ruf015)

1) Don't add `iter` to built-in functions that are already iterable
An example of this could be `list(zip([0]))[0]`, which right now is converted to `next(iter(zip([10])))`, and my suggestion would make it not add `iter` so it would be `next(zip([10]))`

2) Handle an unpacked list
This could be something like this `[*x][0]`, which should be handled like `list(x)[0]` and converts to `next(iter(x))`. I don't think this is used much in the wild, so it could be overkill to add it. 

I have a first already started implementing this [here](https://github.com/Hoxbro/ruff/pull/2). Though, as this is the first time I have written any Rust, it could likely be improved upon 😅

**Comment by charliermarsh** [comment]
I'd like to support the former but would probably skip the latter -- or, at least, that could be a separate rule that converts `[*x]` to `list(x)`, rather than part of RUF015.

**Comment by Hoxbro** [comment]
With the latter my point was _not_ to do a conversion of `[*x]` to `list(x)`, but convert `[*x][0]`  to `next(iter(x))`.

 Can you assign me this?
