### ISSUE TITLE
:parasol_on_ground:  Formatter: Configuration changes

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7642]
Umbrella issue to track the necessary configuration changes to integrate the ruff formatter. 

* [x] #7354 
* [x] Introduce `lint` section #7549
* [x] Use `-width` for text widths consistently
	* [x] #7573
	* [x] #7643
	* [x] #7574
* [x] New Linter options
	* [x] #7644
* [x] New formatter specific settings
	* [x] Add `format` section #7566
	* [x] #7648
	* [x] #7649
	* [x] Decide on default for line ending (Auto vs Lf) https://github.com/astral-sh/ruff/pull/8057
* [x] #7645
* [x] #7646
* [x] #7647
* [ ] #7651 (After Beta?)
* [x] Decide on #7615
* [x] #7572

**Comment by latonis** [comment]
@MichaReiser is it ok if I help out with a few of these? I've implemented rules for the codebase before, but I'd like to help out with config options like this too if possible :smile_cat:
