### ISSUE TITLE
Add `exclude` option to `format` and `lint` sections

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7645]
Add the new `exclude` option to the `format` and `lint` section to exclude a set of files for a specific tool only. Respect the new option in the `check`, `fix`, and `format` commands.

**Comment by charliermarsh** [comment]
@MichaReiser - Yeah, that would be my suggestion: `python_files_in_path` applies the top-level filters, then we apply any further filters in `lint`. It's kind of similar to `per-file-ignores`: we filter down the global rule set based on the `ignore` setting, but we then apply any `per-file-ignores` after collecting diagnostics, on a per-file basis.

**Comment by MichaReiser** [comment]
We may also want to make sure that these files don't get formatted in the IDE even when called with `--stdin-path`

**Comment by MichaReiser** [comment]
Adding `exclude` to lint will be somewhat challenging because we use serde's `flatten` to expose the same options top-level and under the `lint` keyword. This works perfectly but imposes a challenge now because `exclude` (and, in the future, the `preview` flag) conflicts with the top-level `exclude` setting. 

I think what we can try is to have a few more structs 😆 

* `CommonLintOptions`: The lint options without `exclude` (and eventually `preview`).
* `LintOptions`: Defines the `preview` option and flattens the `CommonLintOptions` 
* `Options` flattens the `CommonLintOptions` (instead of `LintOptions` as of today)
