### ISSUE TITLE
Document rules potentially conflicting with the formatter

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7647]
Update the documentation of lint-rules that potentially conflict with the formatter and mention that we discourage using them in combination with the formatter. 

- [line-too-long](https://beta.ruff.rs/docs/rules/line-too-long/)
- [single-line-implicit-string-concatenation](https://beta.ruff.rs/docs/rules/single-line-implicit-string-concatenation/) (could be annoying when the formatter collapses implicit strings)

**Comment by ngnpope** [comment]
One to add to this list is C812 which wants trailing commas everywhere and is thus semi-incompatible with black's handling of formatting based on the presence or absence of trailing commas.

**Comment by charliermarsh** [comment]
(I think that should be COM812 in Ruff parlance.)

**Comment by ngnpope** [comment]
Yes, my mistake!
