### ISSUE TITLE
Remove deprecated configuration options

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7650]
Remove configuration options that are marked as deprecated.

**Comment by tibor-reiss** [comment]
Looks like a nice place to start contributing to this super tool!

**Comment by MichaReiser** [comment]
As of today:
* `show-source`
* `tab-size`
* Top level lint settings 
* `extend-ignore`
* `extend-unfixable`
* `ignore-init-module-imports`

**Comment by MichaReiser** [comment]
> `ignore-init-module-imports`

This option has only been deprecated with Ruff 0.4.4 (https://github.com/astral-sh/ruff/pull/11436) and the new behavior is still gated behind preview (we may want to promote it to stable?). I think we should wait with removing the option until after the new F401 behavior has been stabilized

**Comment by MichaReiser** [comment]
There's also the `output-format` `text` that is deprecated and that we probably should remove

**Comment by MichaReiser** [comment]
I'll close this and will create specific deprecation tasks to ease tracking of what needs to be deprecated/errored/removed when.
