### ISSUE TITLE
Deprecate top-level lint options

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#7651]
Deprecate the top level lint options in favor of `[lint]` https://github.com/astral-sh/ruff/pull/7549

**Comment by zanieb** [comment]
We can deprecate these options before v0.2.0

**Comment by charliermarsh** [comment]
(Clarifying: deprecate, but not remove.)

**Comment by MichaReiser** [comment]
This shipped as part of 0.2
