### ISSUE TITLE
FURB148 generates invalid fix when arg is a generator

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#7656]
```python
a = (b for b in range(1, 100))
for i, _ in enumerate(a):
    print(i)
```
gets autofixed to:
```python
a = (b for b in range(1, 100))
for i in range(len(a)):
    print(i)
```
but a is a generator, and `len`, surprisingly cannot take a generator (len needs a SizedSequence). Running the code in this autofix will generate the following error:
```
Traceback (most recent call last):
  File "test_file.py", line 2, in <module>
    for i in range(len(a)):
TypeError: object of type 'generator' has no len()
```
So while this would work if object was a SizedSequence like a tuple, list, dict, or set, it does not work in this case and will generate invalid.

As an aside, using enumerate to generate an index here when it's a generator is rather nifty, not sure there is an easier way to actually get a range length on generator, using enumerate might actually be most efficient in this case.

The command run is `ruff test_file.py --select FURB148 --preview --fix`
on `ruff 0.0.291`

**Comment by charliermarsh** [comment]
Thanks!

**Comment by dhruvmanila** [comment]
This will probably require type inference as the variable might be defined outside the `enumerate` call site as is in this example.

**Comment by Skylion007** [comment]
@dhruvmanila True, but in the meantime we shouldn't suggest or force the change because if the arg is a generator, enumerate might strictly be better than range (I can't think of a cleaner way to do it).

**Comment by tjkuson** [comment]
Suppressing the fix would still have the rule trigger, which is less destructive but still frustrating for the user who has to figure out it's a false negative and suppress the rule. Limiting the rule to known safe sequences (for example, using `ruff_python_semantic::analyze::typing::is_list`) would eliminate this, but result in a whole load of false negatives. We could do that to eventually promote the rule out of the preview category, and then create an issue for generator discrimination when Ruff has better type inference?

**Comment by charliermarsh** [comment]
Yeah, I think my suggestion would be to only trigger the enumerate case if `is_list` or `is_set` or `is_dict` or `is_tuple` (i.e., it's a known container) is truthy.

**Comment by tjkuson** [comment]
Feel free to assign to me, I can work on a merge request tomorrow.
