### ISSUE TITLE
Rule N806 and Django

### ISSUE THREAD

**Issue by aqeelat** [astral-sh/ruff#7675]
In django, you can access a model by importing it or by getting it from the registry (i.e. calling apps.get_model). The convention is to name the variable in title case to match the model's name.
Example from the docs: https://docs.djangoproject.com/en/4.2/ref/applications/#django.apps.AppConfig.ready

However, this clashes with rule N806.

Is there a way to make this work?

**Comment by aqeelat** [comment]
I think this could a setting for N806 that allows`(\w*) = .*\.get_model\(.*,"(\w*)"\)` if $1 and $2 match.

**Comment by charliermarsh** [comment]
I'm open to supporting this, although I think it should just be enabled and not behind a setting. I think we need to support both `apps.get_model("core", "Activation")` and (e.g.) the `MyModel = self.get_model("MyModel")` form.

**Comment by q0w** [comment]
Also [`import_string`](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.module_loading.import_string)

**Comment by tylerlaprade** [comment]
This fix is great! We had previously turned this rule off in our `migrations/` folder for exactly this reason. However, if we remove that override, we have a few cases where we need to dynamically set the model, so `$1` and `$2` don't match:

<img width="633" alt="image" src="https://github.com/astral-sh/ruff/assets/5475199/6d44afbf-f86d-43a1-bb5c-de641654f131">

<img width="740" alt="image" src="https://github.com/astral-sh/ruff/assets/5475199/74c510f4-688a-4f1d-9dec-309637fe2750">

<img width="1019" alt="image" src="https://github.com/astral-sh/ruff/assets/5475199/fc056ecd-4dd1-42e0-a2ac-6dcad5863936">

**Comment by charliermarsh** [comment]
I suppose we could extend this to allow any `apps.get_model`-like assignments, and not limit it to matches on the left- and right-hand side...

**Comment by tylerlaprade** [comment]
Perhaps the restriction should only be relaxed when the right-hand side is a variable? I know this would cause my third screenshot to be broken, but I think there's more value in ensuring you didn't typo your model name than there is in allowing this one-off rare case.

**Comment by charliermarsh** [comment]
That seems reasonable to me. I added it in: https://github.com/astral-sh/ruff/pull/9065.
