### ISSUE TITLE
Formatter: breaks single-element pattern

### ISSUE THREAD

**Issue by mrcljx** [astral-sh/ruff#7681]
A `case` with single-element tuple pattern (e.g. `(x,)`) is broken into multiple lines:

```
match a:
    case (x,):
        pass
```

is formatted to

```
match f:
    case (
        x,
    ):
        pass
```

Would have expected the formatter leaving it alone like it does for `(x,) = y` (and like Black does).

### Invocation

`ruff format test.py`

### Version

ruff 0.0.291

**Comment by charliermarsh** [comment]
Thanks! I consider that a bug too, since it deviates from our `if (x,):` handling.
