### ISSUE TITLE
Consider removing ANN101

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#7709]
Note to self, to fill in when I’m back at my laptop.

**Comment by cosmojg** [comment]
Is ANN102 included in this discussion?

**Comment by NeilGirdhar** [comment]
Why remove ANN101?

But if anything, at least don't trigger on the first argument of an ordinary or class method (typically called "self" or "cls").  These have implicit types: `typing.Self` and `type[typing.Self]`.

**Comment by charliermarsh** [comment]
ANN101 and ANN102 only affect `self` and `cls` respectively, right?

**Comment by NeilGirdhar** [comment]
I thought that they check all of the arguments?  "Checks that function arguments have type annotations."

I'm just saying to ignore the first argument for ordinary and class methods.

**Comment by charliermarsh** [comment]
It's broken into multiple rules, so ANN101 only checks `self`. ANN001 checks arbitrary arguments: https://docs.astral.sh/ruff/rules/missing-type-function-argument/.

**Comment by NeilGirdhar** [comment]
Ohhh, my mistake.   I confused ANN001 with ANN101.  Yes, please get rid of ANN101 and 102 😄

**Comment by KotlinIsland** [comment]
> Note to self, to fill in when I’m back at my laptop.

Instead of a Note to `self`, could we add an annotation to `self`?

**Comment by zanieb** [comment]
See #9689 which currently deprecate these rules
