### ISSUE TITLE
Syntax error while parsing variables containing unicode? character

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#7731]
Surfaced in #7632. Maybe it's related to the encoding comment?

```python
# -*- coding: iso-8859-15 -*-
¸uite = 1
```

```python
# -*- coding: latin-1 -*-
cu÷t_ie = 1
``` 

```python
# -*- coding: iso-8859-1 -*-
macro.÷equest.getText = 1
```

**Comment by charliermarsh** [comment]
I confirmed that all of these are due to the alternative encoding (if you remove the coding comment, Python fails to parse these files), which we don't currently support. Merging into https://github.com/astral-sh/ruff/issues/6791.
