### ISSUE TITLE
Invalid fix for `UP025` when implicitly concatenated with f-string

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#7784]
Note that this is unrelated to the new f-string changes.

If a unicode string is implicitly concatenated with a f-string, then the fix removes the first character of the string instead of the prefix:

```python
u"foo" f"{bar}"
```

The fix:
```console
$ pipx run "ruff==0.0.291" check --select=UP  ~/playground/ruff/fstring.py --ecosystem-ci
/Users/dhruv/playground/ruff/fstring.py:1:3: UP025 [*] Remove unicode literals from strings
ℹ Fix
1   |-u"foo" f"{bar}"
  1 |+u"oo" f"{bar}"

Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

This is because the "foo" string is part of the outer f-string expression and the range of the string constant is within the quotes.

**Comment by harupy** [comment]
@dhruvmanila Can I work on this?

**Comment by dhruvmanila** [comment]
I would recommend to wait for this a bit as we could change the AST representation for an implicit string concatenation node which then would make this easier to solve.

**Comment by harupy** [comment]
@dhruvmanila Sounds good!
