### ISSUE TITLE
False `RUF012` on empty mutable collections as default values in `msgspec.Struct`s

### ISSUE THREAD

**Issue by floxay** [astral-sh/ruff#7785]
`msgspec.Structs` allow empty mutable collections as default values, however Ruff currently warns about these.\
[Docs](https://jcristharif.com/msgspec/structs.html#default-values):
> Builtin empty mutable collections ([], {}, set(), and bytearray()) may be used as default values (as in c above). Since defaults of these types are so common, these are “syntactic sugar” for specifying the corresponding default_factory (to avoid accidental sharing of mutable values). A default of [] is identical to a default of field(default_factory=list), with a new list instance used each time.

Ruff version: `0.0.292`

MRE:
```py
import msgspec

class Example(msgspec.Struct):
    c: list[int] = []  # Mutable class attributes should be annotated with `typing.ClassVar` Ruff(RUF012)
```

**Comment by charliermarsh** [comment]
Thanks, will fix.
