### ISSUE TITLE
Do not require built-in sections to be present in `section-order`

### ISSUE THREAD

**Issue by levrik** [astral-sh/ruff#7868]
I'm currently in the process of migrating from flake8 and isort to Ruff.

Something I've noticed is that when leaving out a built-in section from `section-order`, a warning appears and these sections are appended to the end of `section-order`. With isort imports that correspond to a built-in section that is missing from `section-order`, are assigned to the `third-party` section instead. I used this before to combine `standard-library` and `third-party` sections into a single one as I don't see much value in separating these.

As a workaround I've added all packages from https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_stdlib/src/sys.rs to `known-third-party` but it's rather ugly.

It would be great if the behavior could match `isort` or could be configured to match it somehow.

**Comment by mmerickel** [comment]
Ran into this as well, isort supports a `default_section` for this purpose if you want to be explicit:

**Comment by mmerickel** [comment]
Looks like something along similar lines was just merged https://github.com/astral-sh/ruff/pull/8657. It would've been possible to implement `no_sections` from that PR with the equivalent proposal above:

```
sections = "THIRDPARTY"
default_section = "THIRDPARTY"
```

**Comment by mmerickel** [comment]
I've implemented `default-section` in https://github.com/astral-sh/ruff/pull/10149.
