### ISSUE TITLE
E251 from spaces around equals in f-string in function argument

### ISSUE THREAD

**Issue by mymoomin** [astral-sh/ruff#7882]
On Ruff version 0.0.292, `ruff --preview --isolated` will misinterpret spaces around equals in f-strings that are function arguments as spaces around keyword arguments and raise an error.

```py
a = 1
b = f"{a = }"  # This is fine
print(a = 1)  # Expected E251 Unexpected spaces around keyword / parameter equals
print(f"{a = }")  # Unexpected E251
```

**Comment by charliermarsh** [comment]
Thanks! \cc @dhruvmanila who fixed a few of these prior to release.

**Comment by mymoomin** [comment]
Thank you for the incredibly fast fix!
