### ISSUE TITLE
UP036 (outdated-version-block) is off-by-one for the target version

### ISSUE THREAD

**Issue by oprypin** [astral-sh/ruff#7902]
If my `target-version` is `py38`, I expect the condition `if sys.version_info >= (3, 8):` to be dropped but it isn't.
It gets dropped for `py37`, though.

**This is a regression introduced in #7284 while fixing #7258.**

### A minimal code snippet that reproduces the bug.

```python
import sys

if sys.version_info >= (3, 8):
    print('oh no')
```

expected:

```python
print('oh no')
```

actual: (no lint and the file doesn't get fixed)

### The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

```bash
ruff check test.py
```

### The current Ruff settings (any relevant sections from your `pyproject.toml`).

```toml
[tool.ruff]
target-version = "py38"
select = ["UP036"]
```

### The current Ruff version (`ruff --version`)

```
ruff 0.0.292
```

**Comment by tdulcet** [comment]
Another related issue here is that indexing/slicing does not work:
```py
import sys

if sys.version_info[:2] < (3, 7):
    print('oh no')
```
```
ruff --target-version py37 --select UP036 --isolated test.py
```
This if block should be removed, but nothing changes. Even the [Ruff documentation](https://docs.astral.sh/ruff/rules/sys-version-slice3/) suggests using this slice syntax here, so it should work as expected.
