### ISSUE TITLE
Does ruff have a plan for addressing flake8 or pycodestyle new changes?

### ISSUE THREAD

**Issue by mythnc** [astral-sh/ruff#7904]
According to ruff documents, [it is stated](https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-flake8) that

> Under those conditions, Ruff implements every rule in Flake8. In practice, that means Ruff implements all of the F rules (which originate from Pyflakes), along with a subset of the E and W rules (which originate from pycodestyle).

I'm curious if ruff will continue to follow and implement changes every time flake8 or pycodestyle updates itself?

For instance, pycodestyle recently [made changes](https://github.com/PyCQA/pycodestyle/blob/21abd9b6dcbfa38635bc85a2c2327ec11ad91ffc/CHANGES.txt#L12-L13) in how it handles E721.

> * E721: adjust handling of type comparison.  Allowed forms are now
  ``isinstance(x, t)`` or ``type(x) is t``.  PR `#1086`, `#1167`.

I would like to know if ruff plan to adopt these changes.

Thank you.

**Comment by charliermarsh** [comment]
We generally do implement changes that are made upstream, though they sometimes need to be brought to our attention so it's always welcome to file an issue if we've missed something. I'll take a look at the E721 changes, thank you!

**Comment by charliermarsh** [comment]
I'll update E721 now and use this issue for it.
