### ISSUE TITLE
--unfixable is ignored for ISC001

### ISSUE THREAD

**Issue by moshelooks** [astral-sh/ruff#7909]
* A minimal code snippet that reproduces the bug.
```
> echo 'print("foo" "bar")' > dummy.py
> ruff --isolated --select=ISC dummy.py
dummy.py:1:7: ISC001 [*] Implicitly concatenated string literals on one line
Found 1 error.
[*] 1 potentially fixable with the --fix option.
> ruff --isolated --select=ISC --unfixable=ISC001 --fix dummy.py
Found 1 error (1 fixed, 0 remaining).
> cat dummy.py
print("foobar")
```

* The current Ruff version (`ruff --version`).
ruff 0.0.292

Apologies if I failed reading comprehension, but my expectation is for `--unfixable` to to block the fix here. 

Thank you for your attention!

**Comment by charliermarsh** [comment]
Thanks, that's just a bug!
