### ISSUE TITLE
Feature Request: Support isort literal ordering

### ISSUE THREAD

**Issue by kkirsche** [astral-sh/ruff#7929]
This issue is to request support for isort's ordering action comments.

For example:

```python
# isort: unique-list
__all__ = ["b", "c", "a", "c"]
```

Would be rewritten to:

```python
# isort: unique-list
__all__ = [ "a", "b", "c"]
```

This code within isort is located here:
https://github.com/PyCQA/isort/blob/9e0ad3d9939e0649a77f4e04db23652f170808a6/isort/literal.py#L97

With the code styling comments supported by isort located here:
https://github.com/PyCQA/isort/blob/9e0ad3d9939e0649a77f4e04db23652f170808a6/isort/core.py#L18

This was originally requested within isort in the issue below and released as part of isort 5.3.0:
https://github.com/PyCQA/isort/issues/1358

Thank you for your time and consideration.

**Comment by charliermarsh** [comment]
Thanks for the clear issue. I'm going to merge this into https://github.com/astral-sh/ruff/issues/1198 since we're tracking these collection comments there.
