### ISSUE TITLE
description of C408

### ISSUE THREAD

**Issue by yuuuxt** [astral-sh/ruff#7936]
Not reporting a bug - seeing [C408 description](https://docs.astral.sh/ruff/rules/unnecessary-collection-call/) saying `dict()` call is not necessary, while there is a useful use case - it can be used to prevent having duplicate (string) keys easily (ref: [StackOverflow](https://stackoverflow.com/a/22242922/4318625)). I'm using it for that purpose, so I have to disable `C408` check there. 

![image](https://github.com/astral-sh/ruff/assets/3153534/bb1ee723-d58e-4a53-936c-8471af4c9aa6)

Maybe it's worth mentioning in the C408 description? Thx

**Comment by charliermarsh** [comment]
I appreciate this call-out though am not sure that it merits mentioning in the docs, since we'll still end up flagging C408 in that case.
