### ISSUE TITLE
Insert newline after docstring even when there are comments

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#7948]
Ours:
```pyhton
class ModuleBrowser:
    """Browse module classes and functions in IDLE."""
    # This class is also the base class for pathbrowser.PathBrowser.

    def __init__(self, master, path, *, _htest=False, _utest=False):
        pass
```
Black:
```python
class ModuleBrowser:
    """Browse module classes and functions in IDLE."""

    # This class is also the base class for pathbrowser.PathBrowser.

    def __init__(self, master, path, *, _htest=False, _utest=False):
        pass
```
We should also insert the empty line after the docstring even if there is comment

**Comment by charliermarsh** [comment]
This _might_ be intentional (though whether it’s good is debatable) — I believe we intentionally don’t insert a newline like that if it immediately follows an import, unlike Black.

**Comment by charliermarsh** [comment]
What if there’s no empty line between the comment and the function definition?

**Comment by konstin** [comment]
> What if there’s no empty line between the comment and the function definition?

In that case both we do the same thing as black, one empty line between docstring and the own line comment
