### ISSUE TITLE
Add parentheses around power operations

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#7951]
Ours:
```python
self.assertRaises(IndexError, lambda: b[-10**100])
```
Black:
```python
self.assertRaises(IndexError, lambda: b[-(10**100)])
```
We should implement the same rules as black to add parentheses around power operations.

**Comment by charliermarsh** [comment]
Is this documented anywhere in the style guide?

**Comment by charliermarsh** [comment]
Maybe this? https://github.com/psf/black/pull/909
