### ISSUE TITLE
Support the Poetry pyproject.toml equivalent of `requires-python`

### ISSUE THREAD

**Issue by newbery** [astral-sh/ruff#7957]
The docs on the `target-version` setting, 
https://docs.astral.sh/ruff/settings/#target-version,
say the following:

    If omitted, and Ruff is configured via a pyproject.toml file, the target version
    will be inferred from its project.requires-python field

In the Poetry case, the python version would actually be elsewhere, under `tool.poetry.dependencies.python`. Can the inference logic be updated to support the Poetry version of pyproject.toml?

**Comment by charliermarsh** [comment]
Thanks for the note. This has been discussed a bit in the past (https://github.com/astral-sh/ruff/issues/5448), and the suggestion from a Poetry maintainer was to _not_ support this as Poetry is going to deprecate `tool.poetry.dependencies.python` in favor of the standards-compliant `requires-python`.

**Comment by newbery** [comment]
Ahh, that make sense. Thanks  👍🏻
