### ISSUE TITLE
New rule idea: alphabetic `__all__`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#7960]
I am using `ruff==0.0.292`.

I think a nifty rule would be to alphabetize the values in a module's `__all__`.  An alphabetized `__all__` is easier to skim through than an unsorted `__all__`.

**Comment by charliermarsh** [comment]
I believe this is similar to #3119!

**Comment by jamesbraza** [comment]
Sorry for the dupe 👌
