### ISSUE TITLE
PLW3201 flags _missing_ in Enum subclass

### ISSUE THREAD

**Issue by mal** [astral-sh/ruff#7971]
`Enum` in Python has a few [supported sunder names](https://docs.python.org/3/library/enum.html#supported-sunder-names). Of them, `_missing_` and `_generate_next_value_` are explicitly called out as overridable but when doing so they get flagged as misspelled dunder methods.

Looks separate from, but related to #4592.

```py
from enum import StrEnum
class Build(StrEnum):
    @classmethod
    def _missing_(cls, value):
        pass
```

```sh
$ ruff --isolated --preview --select PLW3201 --show-source test.py
test.py:4:9: PLW3201 Bad or misspelled dunder method name `_missing_`. (bad-dunder-name)
  |
2 | class Build(StrEnum):
3 |     @classmethod
4 |     def _missing_(cls, value):
  |         ^^^^^^^^^ PLW3201
5 |         pass
  |
```

Observed using `ruff 0.0.292`.

**Comment by charliermarsh** [comment]
Thanks!
