### ISSUE TITLE
Rename use of `--format` in `ruff rule` to `--output-format`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#7990]
As with #7354, we should probably rename `ruff rule --format ...` to `ruff rule --output-format ...` for clarity.

The old option should be deprecated then removed later.

**Comment by Skylion007** [comment]
I got bitten by this when upgrading ruff as well.

**Comment by sibocw** [comment]
Yes... This broke my Github Action that uses ruff. I guessed something like this could be the reason, but it wasn't obvious to me from the ruff documentation that `--format` is now `--output-format`
