### ISSUE TITLE
Inconsistent EXE001 behavior

### ISSUE THREAD

**Issue by Scrat94** [astral-sh/ruff#7994]
Hello,

Steps to reproduce:
1. Have file `main.py`
2. On the first line:  `#!/usr/bin/env python3`
3. Run ruff locally on windows
4. Run ruff on Linux in GitLab CI runner

Current behavior:
* Locally on windows no finding/error occurs
* On GitLab Runner (Linux) the following error shows up: `main.py:1:1: EXE001 Shebang is present but file is not executable`

Expected behavior:
* Same result on local (windows) as well as on GitLab CI (Linux)

Is my understanding correct, or is this the intended behavior? Much thanks in advance!

**Comment by charliermarsh** [comment]
So, we don't enforce that rule on Windows at all, since IIUC there is no concept of file modes on Windows. So this may be expected, in that if the file isn't marked as executable, you wouldn't see an error on Windows, but _would_ on Linux.

**Comment by charliermarsh** [comment]
I'm wondering if you can run `git update-index --chmod=+x /path/to/exe`?

**Comment by Scrat94** [comment]
> So, we don't enforce that rule on Windows at all, since IIUC there is no concept of file modes on Windows. So this may be expected, in that if the file isn't marked as executable, you wouldn't see an error on Windows, but _would_ on Linux.

Thanks for the explanation, I guess I will just ignore the EXE-Rule(s). Currently cannot run the `git update-index --chmod=+x /path/to/exe`

We can close the issue. Thanks for the quick reply.

**Comment by charliermarsh** [comment]
No worries -- sorry for the confusion.
