### ISSUE TITLE
Add newline after module docstrings

### ISSUE THREAD

**Issue by DanielNoord** [astral-sh/ruff#7995]
```python
"""Test docstring"""
a = 1
```

On the playground this does not currently get a newline added with the `format` option turned on.

Recently a PR of mine got merged to `black` to include a newline after the module docstring:
https://github.com/psf/black/pull/3932
_Most credits should go to others though for that PR as I mostly copied and rebased code._

It's still in the preview style but got generally favourable responses when initially proposed a couple of year ago. Since nobody has really objected to it during its previous iterations I expect it to be part of the default style some day.

Would `ruff` be open to to include this change to `ruff format` as well?

_EDIT: Oh, and congrats on the `0.1.0` release 🎉_

**Comment by charliermarsh** [comment]
Cool, so this is part of Black's preview style? If so, we'll likely add it under our own `--preview` flag soon.

(And thank you!)

**Comment by charliermarsh** [comment]
@konstin - Perhaps another good / easy one for preview.

**Comment by DanielNoord** [comment]
@charliermarsh Sorry should have been clearer. This is currently only available on `black` `main` as `preview`. (I run from `master` locally). You can see in the linked PR that it actually already applies to `blacks` own codebase. There hasn't been a release yet, I can ask them when they plan on doing so but I don't want to bother the maintainers too much.

**Comment by MichaReiser** [comment]
> I added a test case in #8044, it's not trivial to fix though

We could try to format it as part of the module if the first statement in the suite is a doc comment without any leading comments? Not sure how to handle trailing suppression comments though.
