### ISSUE TITLE
TRY401 false-positive detection

### ISSUE THREAD

**Issue by a-shchupakov** [astral-sh/ruff#8008]
TRY401 false-positively triggered if `error` object passed to function call inside of `logger.exception` arguments

```python
try:
    pass
except SlackApiError as api_error:
    logger.exception(
        "Got %s error while posting comment to thread %s in channel %s",
        get_error_message(api_error),  # <--- TRY401
        thread_ts,
        channel_name,
    )
    raise
```

`get_error_message` returns some string from `error`

* Playground link - https://play.ruff.rs/cad4767c-2a7a-4a77-be41-332d36e42817
* `ruff 0.1.0`.

**Comment by a-shchupakov** [comment]
Thank you for response!
I moved it into variable and error is gone

So if you think current behaviour is fine, let's close it or wait for more feedback from other users :)

**Comment by danhje** [comment]
Encountered exactly the same. I would guess `logger.exception(get_exception_message(e))` is quite a common pattern.

**Comment by Daraan** [comment]
I like to use `"%s"` + `repr(e)` the assumed ruff compliant alternative to `"%r" , e` as often these are more informative - however this is also a TRY 401 error.

I would love to have some ways to call functions on the exception object without logging a false positive TRY401.

@charliermarsh Out of curiosity, what are potential false negatives here? Currently I do assume that a `function(e)` is more used by users that try to extract strings or a cleaner object.
Maybe a flag to silence TRY401 on functions, or a list of allowed functions would be a nice solution here.
