### ISSUE TITLE
B005 doc error

### ISSUE THREAD

**Issue by Ahmed-Abdou14** [astral-sh/ruff#8009]
### [strip-with-multi-characters (B005)](https://docs.astral.sh/ruff/rules/strip-with-multi-characters/)
![image](https://github.com/astral-sh/ruff/assets/104530599/d5193519-32a3-4e59-a66b-37d750c1d92b)

```python
# Wrong output (used in docs) 
"text.txt".strip(".txt")  # "ex" 

# Correct output
"text.txt".strip(".txt")  # "e"
```

Was planning to open a PR for it but couldn't find the docs project, would appreciate if you elaborate on how to contribute to the docs ^_^

**Comment by T-256** [comment]
@Ahmed-Abdou14 Rules documents are specified in rules sources via doc-comments, For this case:
https://github.com/astral-sh/ruff/blob/dc6b4ad2b4b8d89757bb74968d1865b3e11c9b7a/crates/ruff_linter/src/rules/flake8_bugbear/rules/strip_with_multi_characters.rs#L35-L38

**Comment by charliermarsh** [comment]
Oh thanks, PR welcome! You can edit the Rust file directly.

**Comment by Ahmed-Abdou14** [comment]
> Oh thanks, PR welcome! You can edit the Rust file directly.

Thank you @T-256 & @charliermarsh 
I have created a [PR](https://github.com/astral-sh/ruff/pull/8028)
A tiny contribution but many to come! Thank you for the amazing tool ^_^

**Comment by charliermarsh** [comment]
Thank you @Ahmed-Abdou14, much appreciated! (Closed by https://github.com/astral-sh/ruff/pull/8028.)
