### ISSUE TITLE
Docs: `magic-value-comparison` shows an example that is not flagged

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#8109]
The code example at https://docs.astral.sh/ruff/rules/magic-value-comparison/ shows an example that is not flagged.

Here's a demo and an example that is actually flagged:
https://play.ruff.rs/0cd75dbb-5452-4b44-ac7b-ef1cc92e6d6e

**Comment by charliermarsh** [comment]
Thanks, will fix...

**Comment by bersbersbers** [comment]
I haven't checked, but I wouldn't be surprised if the new code wasn't flagged by https://docs.astral.sh/ruff/rules/superfluous-else-return/ now ;)
