### ISSUE TITLE
Autofix for missing whitespace rules in E pycodestyle (preview)

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#8121]
- [x] E225
- [x] E226
- [x] E227
- [x] E228
- [X] E231
- [x] E252
- [x] E275

All these rules are very similar, already implemented, and have a trivial autofix that should be added. It would also be a good first issue since the autofix is an easy one to write. @charliermarsh you may want to add a `good-first-issue` label.

**Comment by charliermarsh** [comment]
Thanks @reswqa! Great work!
