### ISSUE TITLE
Optimize formatter with hot cache

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#8135]
There's a lot of optimization opportunities with the formatter with a hot cache (the example is apache airflow with rayon removed):

* Sorting the result takes a long time so does building the result vec, even though we know its approximate size
* #8132
* Deserializing the cache takes noticeable time even if we just need 4k paths plus timestamps
* We first iterate over each directory only to check the timestamps later, could those be combined?

![image](https://github.com/astral-sh/ruff/assets/6826232/bc47843b-64c3-467c-ac76-99d1df836cb0)

Instructions for generating the flamegraph:
 * Install perf and `cargo install flamegraph`
 * git clone apache airflow
 * Apply https://gist.github.com/konstin/2e8c45c7f1fa53dc003833870226bab8
 * `flamegraph -F 9999 -- target/release-debug/ruff format ../airflow/` (Set your cpu to powersave for more samples)

**Comment by charliermarsh** [comment]
Fixing the sort here.

**Comment by charliermarsh** [comment]
We did a bunch of stuff here.
