### ISSUE TITLE
Request: allowlist of codes for `RUF100` not to autoremove

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#8153]
Some tools like to use `flake8` as a vehicle for config files and ignores:
- https://github.com/jsh9/pydoclint
- https://github.com/andreoliwa/nitpick

However, `RUF100` in `ruff==0.1.1` is removing the `# noqa`'s I add for those tools.

Any chance we can a new config option for `ruff` that is basically an allowlist override for RUF100?

**Comment by jamesbraza** [comment]
I guess a workaround is, for each `noqa` that is being removed by `RUF100`, I can do `# noqa: DOC501,RUF100`

**Comment by charliermarsh** [comment]
I think we have a setting for this: https://docs.astral.sh/ruff/settings/#external.  Codes marked as external won’t be removed and flagged by RUF100 (or at least, they shouldn’t be).

Mind giving that a try?

**Comment by jamesbraza** [comment]
Thanks for the response!

I am using [`pydoclint`](https://github.com/jsh9/pydoclint), which has `DOC` error codes: https://github.com/jsh9/pydoclint#3-style-violation-codes

`external` does work, though you have to specify the exact code. It would be nice to be able to use `external = ["DOC"]`, as opposed to `external = [..., "DOC201", "DOC301", ..., "DOC501"]`

This leads me to a few requests:

- Document `external` setting in https://docs.astral.sh/ruff/rules/unused-noqa/
- (there is a broken link at the bottom of https://docs.astral.sh/ruff/rules/unused-noqa/)
- Allowing `external` to use rule prefixes (e.g. DOC instead of DOC501)

Let me know what you think

**Comment by jamesbraza** [comment]
Thank you!  Interested in hearing what you think of moving `external` to work using prefixes of rules, not just exact matches

**Comment by charliermarsh** [comment]
I think matching prefixes is pretty reasonable.

**Comment by jamesbraza** [comment]
Thank you and cool!  I opened https://github.com/astral-sh/ruff/issues/8174 for that.

Will leave this open for @zanieb 's two docs PRs to close this one out ✅ .
