### ISSUE TITLE
Broken link in https://github.com/astral-sh/ruff/blob/main/docs/formatter.md#configuration

### ISSUE THREAD

**Issue by brettcannon** [astral-sh/ruff#8178]
https://github.com/astral-sh/ruff/blob/main/docs/formatter.md#configuration has a link to "Settings", but it's a 404.

**Comment by zanieb** [comment]
Hi!

We generate that file. On the documentation website, the link works.

ref https://docs.astral.sh/ruff/formatter/#configuration

**Comment by charliermarsh** [comment]
I wish they both worked :sob:

**Comment by brettcannon** [comment]
> We generate that file. On the documentation website, the link works.

Ah, I got thrown by the fact that the other links via the Markdown file was working.
