### ISSUE TITLE
Formatter undocumented deviation: No wrap in long return

### ISSUE THREAD

**Issue by henribru** [astral-sh/ruff#8182]
[Black:](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AD7AGZdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyg7Vbzvz0jlNR2_bpXU07f205BRmTbXczRtImDQGwvxVeZ0igpjl1qY5GjsPOvWAo45rNmyDKffTMdBonyq7OakaQnjgdtL9VEwdljVCAAAAABNrGxsCFLuyAAGCAfwBAACWiz9gscRn-wIAAAAABFla)
```
def foo():
    if foo:
        return (
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        )

```

[Ruff:](https://play.ruff.rs/ca8b5351-00c1-4ddc-a1f3-fe9ee3aeeb7d?secondary=Format)
```
def foo():
    if foo:
        return aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
```

**Comment by MichaReiser** [comment]
I'm slightly confused. Black generally tries to avoid parentheses if the parenthesized content also exceeds the line length. We added support for this behavior in #6817 (and refined it later). Now, it seems that this logic doesn't (always?) apply for attribute chains?

**Comment by charliermarsh** [comment]
I don't quite understand that either, I wonder if it's intentional.

**Comment by njzjz** [comment]
I got the same behavior with `assert`.

**Comment by MichaReiser** [comment]
I played with this further and it is correct. Black always wraps attributes in parentheses, even if it doesn't make them fit. 

Black

```python
# fits parenthesized
______ = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvv
)
return (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb
)

# exceeds parenthesized
______ = (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvv
)
return (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbb
)


def doesnt_exceed_line_length_when_parenthesizing():
    ______ = (
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvv
    )
    return (
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbb
    )


def exceeds_line_length_parenthesized():
    ______ = (
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvv
    )
    return (
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbb
    )
```

Ruff would remove the parentheses for the "exceeds line length" cases. I believe the same is true for call chains.

Changing our code to use the normal `Multiline` layout for attribute chains in itself isn't to hard. However, there's another difference between `BestFit` and `Multiline: 

* `BestFit`: Breaks right first. It first breaks the value (right) before parenthesizing the target (left)
* `Multiline`: Breaks the left first: It breaks the target (left) before parenthesizing the value (right)

Changing the precedence between breaking the target or value has the result that:

```python
state[
    "event_queue_longpoll_timeout_seconds"
] = settings.EVENT_QUEUE_LONGPOLL_TIMEOUT_SECONDS
```

gets reformatted to 

```python
state["event_queue_longpoll_timeout_seconds"] = (
    settings.EVENT_QUEUE_LONGPOLL_TIMEOUT_SECONDS
)
```

which matches [Black's preview style](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-line-breaks), at least for attributes. I believe this will require changing `BestFit` to be right to left too, but that seems straightforward. 

However, I don't know of a good way to make our parenthesizing left to right, and if it's worth spending time on this, considering that implementing preview style "solves" the problem and it seems rare enough (I didn't find any usages in our baseline projects)

**Comment by MichaReiser** [comment]
I opened an issue on the Black repository to see if omitting parentheses is intentional. https://github.com/psf/black/issues/4001

**Comment by MichaReiser** [comment]
Black considers aligning with ruff's style.

**Comment by MichaReiser** [comment]
I recommend us to keep it as for now and see if Black changes their style.

**Comment by henribru** [comment]
Can it get added to the documented deviations in the meantime?

**Comment by henribru** [comment]
@MichaReiser This is in a return type and not a return value, but is this the same issue?

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AORAahdAD2IimZxl1N_WlbvK5V8VwGvpky2hHvxJKDBSYISDIkXZGJG4SJMgx6_11S4gUOnTDWjHwJaiM6dlpIbDBLvtd7rfffNEd3HafefdTpwBZWZsH2D652XvLSeuqzfBgpUW8YBK4WelZ6dWGMxHiSwGu2chnbe3hJfPqsGS4WucjxLTHCHhdIxlqwYohxVBltlO12woMOHr1NP6DVUc5HBxFOIKjgjZbilMZn-7-E1XWXCYLkoStiN4kGXio0D_kEOEYgY75dedJRg1cOuhcbG-GVyX8IRNbluxBAwSUGnl6RgPCh_ifBOYvI9kFWBVXB5zOFIysanReiU28yBqcIToJ_cstX_N4sw12ftCNgzy9bOwu4KyvMd0Y59g5XqhSmuoIYKChIENIVJh319IdJH9L5MqaH3UwWcwzCSiNQDGuMOZBxT2UX-zmAazCS-7sLFQ4P77cdKdjhFuEzr-ujdHBakv9G9elRwKG2IVIJXSEVXP6RF6aYg0nhgk9rAUFqYsNQjf6wSpDFqrW-SGITiAO2unHRfDZe2DFfkGs_SRpDO3Jpm6KpowVYAJhy94zLR2lsAAcQDkgcAAAXNihyxxGf7AgAAAAAEWVo=

https://play.ruff.rs/88f317d4-7f5a-4d59-8404-a2b117c47caa?secondary=Format

**Comment by MichaReiser** [comment]
@henribru yes this seems to be the same issue. Changing the return type to an identifier (remove all dots) makes Black match Ruff's formatting

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AONAaNdAD2IimZxl1N_WlbvK5V8VwGvpky2hHvxJKDBSYISDIkXZGJG4SJMgx6_11S4gUOnTDWjHwJaiM6dlpIbDBLvtd7rfffNEd3HafefdTpwBZWZsH2D652XvLSeuqzfBgpUW8YBK4WelZ6dWGMxHiSwGu2chnbe3hJfPqsGS4WucjxLTHCHhdIxlqwYohxVBltlO12woMOHr1NP6DVUc5HBxFOIKjgjZbilMZn-7-E1XWXCYLkoStiN4kGXio0D_kEOEYgY75dedJRg1cOuhcbG-GVyX8IRNbluxBAwSUGnl6RgPCh_ifBOYvI9kFWBVXB5zOFIysanReiU28yBqcIToJ_cstX_N4sw12ftCNgzy9bOwu4KyvMd0Y59g5XqhSmuoIYKChIENIVJh319IdJH9L5MqaH3UwWcwzCSiNQDGuMOZBxT2UX-zmAazCS-7sLFQ4P77cPOFJOUUipdc1UEHCM3XhBwE05-vHjsZevtZNgzB30fWy286CplsUtQ3fVAA-HF6kXbP--S2KEDJfhJi2ewDi4v_VnBJOZXP3iUkqYLeyDRAADRqnwBGWR3AAABvwOOBwAAINigZ7HEZ_sCAAAAAARZWg==
