### ISSUE TITLE
Formatter undocumented deviation: Redundant parentheses in boolean expression can lead to extra line breaks

### ISSUE THREAD

**Issue by henribru** [astral-sh/ruff#8183]
[Black:](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADtAHtdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyv9jIpYCegD3gYD7EyeAgiILbu4HLFJcJOGomsGIui2j4fvxg-ubYGm00rJ3POd7Otj7BsS8qKAOPqj5RYhHkKKWdavWCbQBVtBbfaMZwMbeFK26F0ek2yy-Pe023i3gAQ-rAAAATqNMSNT2D50AAZcB7gEAAKqHNMmxxGf7AgAAAAAEWVo=)
```
def foo():
    while (
        not (aaaaaaaaaaaaaaaaaaaaa(bbbbbbbb, ccccccc)) and dddddddddd < eeeeeeeeeeeeeee
    ):
        pass
```

[Ruff:](https://play.ruff.rs/485d6e0e-16e1-4b64-8756-8cd3f62c5f4f?secondary=Format)
```
def foo():
    while not (
        aaaaaaaaaaaaaaaaaaaaa(bbbbbbbb, ccccccc)
    ) and dddddddddd < eeeeeeeeeeeeeee:
        pass
```

**Comment by MichaReiser** [comment]
This could be related to #8090

**Comment by MichaReiser** [comment]
I think the issue here is that we set `first` in `CanOmitOptionalParenthesesVisitor` to the `UnaryExpr.value` instead of the unary expression itself. I think we have the same problem for other nodes that start with a token (if expression, dict etc)

**Comment by MichaReiser** [comment]
Okay I think I understand it now... It is an issue with `can_omit_parentheses`. Black uses different rules to test if the first or last node have parentheses. 

* first: Needs to start with parentheses. That excludes call expressions. 
* last: Needs to end with parentheses. Call, lists, etc
