### ISSUE TITLE
Unintentional formatter deviation: strange spacing around `TypeAlias` declarations

### ISSUE THREAD

**Issue by stinodego** [astral-sh/ruff#8188]
Reproducible example:
```python
from typing import TypeAlias

MultiColSelector: TypeAlias = (
    "slice | range | list[int] | list[str] | list[bool] | Series"
)
```

black leaves this alone, while ruff formats it as follows:
```diff
- MultiColSelector: TypeAlias = (
-     "slice | range | list[int] | list[str] | list[bool] | Series"
- )
+ MultiColSelector: (
+     TypeAlias
+ ) = "slice | range | list[int] | list[str] | list[bool] | Series"
```

This looks like an undesirable change to me.

In our code base, I worked around this by rewriting the string as a `Union` of types.

Command: `ruff format .`
Formatter settings: None
Version: ruff `0.1.2`

_P.S.: Other than the two minor issues I just reported, the new ruff formatter is working excellently. It has improved formatting in quite a few cases. Thank you for the amazing work!_

**Comment by MichaReiser** [comment]
Thank's for reporting and thank you for the kind words. 

This deviation is documented as [type annotations may be parenthesized](https://docs.astral.sh/ruff/formatter/black/#type-annotations-may-be-parenthesized-when-expanded) and is related to [7315](https://github.com/astral-sh/ruff/issues/7315). 

Let's keep this issue open to collect some more feedback as I can see that the formatting in this case is not ideal. I also want to re-test if implementing https://github.com/astral-sh/ruff/issues/6975 (preview style) will make fixing it obsolete.

**Comment by henryiii** [comment]
AFAICT, the rule should be that type annotations are only parenthesized if the type annotation itself is long. It should never parenthesize a type annotation to make something after the equals sign have more space.

**Comment by charliermarsh** [comment]
We ended up reverting this decision (so we no longer have this Black deviation). Once we implement preview style, we should have roughly the behavior you describe.
