### ISSUE TITLE
Invalid autofix for RSE102

### ISSUE THREAD

**Issue by Geo5** [astral-sh/ruff#8228]
In the following simple example `test_ruff.py`:
```python
from typing import NoReturn


class SomeObject:
    def get_error(self) -> ValueError:
        return ValueError("some error")


def testfun() -> NoReturn:
    obj = SomeObject()

    raise obj.get_error()


testfun()
```
When run:
```sh
$ python test_ruff.py 
Traceback (most recent call last):
  File ..., line 15, in <module>
    testfun()
  File ..., line 12, in testfun
    raise obj.get_error()
ValueError: some error
```
ruff reports the error [RSE102](https://docs.astral.sh/ruff/rules/unnecessary-paren-on-raise-exception/) and suggests fixing it, producing:
```diff
$ ruff check --isolated --select RSE102 --fix --diff test_ruff.py
--- test_ruff.py
+++ test_ruff.py
@@ -9,7 +9,7 @@
 def testfun() -> NoReturn:
     obj = SomeObject()
 
-    raise obj.get_error()
+    raise obj.get_error
 
 
 testfun()

Would fix 1 error.
```
Which changes the behaviour when run from the original code:
```sh
$ python test_ruff.py 
Traceback (most recent call last):
  File ..., line 15, in <module>
    testfun()
  File ..., line 12, in testfun
    raise obj.get_error
TypeError: exceptions must derive from BaseException
```

**Comment by charliermarsh** [comment]
Ahh yeah, I believe this is similar to https://github.com/astral-sh/ruff/issues/5416 -- we just can't detect this reliably in all cases.

**Comment by charliermarsh** [comment]
We should mark this as an unsafe edit, so that users have to opt in to apply it.

**Comment by Geo5** [comment]
> Ahh yeah, I believe this is similar to #5416 -- we just can't detect this reliably in all cases.

I agree.
For some reason i must have misused the Github search, so i did not find this issue before - sorry!

**Comment by charliermarsh** [comment]
No worries! Thanks for reporting, since we did have at least one change to make here.
