### ISSUE TITLE
Format as lint rule

### ISSUE THREAD

**Issue by hmvp** [astral-sh/ruff#8229]
Congrats on the release with the new formatter. Besides a few changed lines that I still need to investigate It looks really good!

I was a bit surprised with the fact that it is *only* a separate command. I kind of expected it to work as a lint rule: `RUF300: Code not formatted` or something... Which of course includes an autofix.

Using Ruff would allow me to drop 3 tools (flake8, isort, black) but I still need to run two commands...

I also noticed #8185 and feel that those warnings are better suited in the case that the formatter is enabled as lint rule. It seems to me that as a separate command you might want to differ between formatting and conflicting lint rules...

**Comment by zanieb** [comment]
Thanks!

We're planning to integrate the formatter and linter into a single command as a part of the "Stable" formatter release.

Some previous mentions at https://github.com/astral-sh/ruff/discussions/7310#discussioncomment-7376397 and https://github.com/astral-sh/ruff/issues/7232

I'm going to close this issue in favor of a tracking issue at https://github.com/astral-sh/ruff/issues/8232 which we'll use for general updates on this feature — implementing as a lint rule is only one of the possible interfaces.
