### ISSUE TITLE
Format python code in docstrings

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#8236]
Support formatting python code in docstrings similar to [blacken-docs](https://github.com/adamchainz/blacken-docs) (minus markdown support, for markdown see https://github.com/astral-sh/ruff/issues/3792).

**Comment by stinodego** [comment]
Perhaps this supersedes #7146?

**Comment by MichaReiser** [comment]
Oh, let's keep that one instead. It has more context
