### ISSUE TITLE
Docs: Some docs showing `[tool.ruff.linter]` when it should be `[tool.ruff.lint]`

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff#8242]
Example: https://docs.astral.sh/ruff/tutorial/#configuration

**Comment by MichaReiser** [comment]
Thanks for reporting. We landed a few fixes in the last few days but haven't redeployed the documentation yet. 
I quickly searched and couldn't find any remaining `ruff.linter` or `linter` usages. So this should be fixed,  but requires a doc redeployment.

**Comment by thernstig** [comment]
@MichaReiser I understand, I thought it was immediate. Apologize for this noise. Closing.

**Comment by MichaReiser** [comment]
> @MichaReiser I understand, I thought it was immediate. Apologize for this noise. Closing.

No worries. It's extremely helpful to get these reports and they improve our user experience a lot. Keep it up :)
