### ISSUE TITLE
Docs: Ruff formatter and conflicting isort rules ambiguity

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff#8245]
I have read all the docs now, and they are in general in great shape! So good job. There was only one section I could not grok, and I believe it could use some kind of improvement in its description.

From https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules

> Similarly, we recommend disabling the following isort settings, which are incompatible with the formatter's treatment of import statements when set to non-default values:

Some of the settings are not able to be "disabled" per se. And there seems to be no action to take by a user if just using the formatter as-is, right?

Could the sentence be re-phrased slightly?

**Comment by charliermarsh** [comment]
Good feedback -- will tweak today.
