### ISSUE TITLE
Docs: Redirect to rule page from only rule code

### ISSUE THREAD

**Issue by Mogost** [astral-sh/ruff#8249]
### Problem
The Ruff Linter documentation provides URLs for specific rules, such as [https://docs.astral.sh/ruff/rules/collapsible-if/](https://docs.astral.sh/ruff/rules/collapsible-if/). While these URLs are useful for referencing rules, they can be cumbersome to include in code comments or documentation. It would be more convenient if we could have simplified and consistent URLs for each rule, making them easier to reference.

### Expected Behavior
It would be beneficial to have URL redirects in place, so that each rule can be referenced with a simplified URL structure, such as [https://docs.astral.sh/ruff/rules/SIM102/](https://docs.astral.sh/ruff/rules/SIM102/), where 'SIM102' represents the specific rule. This would improve the usability of the documentation and streamline the process of linking to individual rules.

### Additional Context
Developers frequently include references to specific rules in their code comments or documentation. Simplifying the URLs for these rules would enhance the overall experience of using the Ruff Linter and referring to its documentation.

**Comment by dhruvmanila** [comment]
Hey, thanks for a detailed issue description.

> While these URLs are useful for referencing rules, they can be cumbersome to include in code comments or documentation.

If I'm understanding you correctly, can you expand on why is having https://docs.astral.sh/ruff/rules/collapsible-if/ in the comment cumbersome than https://docs.astral.sh/ruff/rules/SIM102/?

Additionally, we'd want to hold off until https://github.com/astral-sh/ruff/issues/1774 is finalized.

**Comment by T-256** [comment]
Rules already point to document in IDEs, For example in VSCode you can either click on it or drag-and-drop it to where you want put the link.

![image](https://github.com/astral-sh/ruff/assets/132141463/5a684134-1cee-4fa7-88ff-94697ebbdf31)

Also another approach could document all rules in schema with [description](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiM2sSkiqOCAxX2gf0HHSv7D40QFnoECBQQAQ&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F64233370%2Fin-json-schema-how-to-define-an-enum-with-description-of-each-elements-in-the-e&usg=AOvVaw0EB5uUuCHyttNt8_neOEcP&opi=89978449), so you can hover on the rule to read info and go to online docs if you want.

**Comment by Mogost** [comment]
@T-256 looks good! Unfortunately, I do not see the same in PyCharm.

**Comment by dhruvmanila** [comment]
> Unfortunately, I do not see the same in PyCharm.

It's because this feature is part of `ruff-lsp` but the [PyCharm Ruff plugin](https://plugins.jetbrains.com/plugin/20574-ruff) (which is what I assume you're using?) is implemented in a separate way. They're adding support for the Language Server Protocol (LSP) which you can try using:

> ### Support ruff-lsp for only PyCharm Pro/IDEA Ultimate
> You can enable it in `Preferences/Settings` -> `Tools` -> `Ruff` -> `Use ruff-lsp (Experimental) for PyCharm Pro/IDEA Ultimate`
>
> The lsp integration applies only below features:
>
> * Errors/warnings highlighting ([textDocument/publishDiagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics))
> * Quick-fixes for these errors/warnings ([textDocument/codeAction](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction)
>
> _This is experimental feature._

**Comment by charliermarsh** [comment]
I want to support this, it's a bit of a pain right now since we'd need to add redirects at the Cloudflare level...

I'm gonna merge with https://github.com/astral-sh/ruff/issues/4710 since I believe it's the same request.
