### ISSUE TITLE
Formatter: single quote style converts triple single quotes to double quotes anyway

### ISSUE THREAD

**Issue by henryiii** [astral-sh/ruff#8252]
I was moving pypa/build to Ruff format in https://github.com/pypa/build/pull/696, since it's a single quote package, and it was previously handed by Black + pre-commit-hook's double to single quotes option. But it turns out Ruff converts triple quoted strings to double quotes even if single quotes is selected via `quote-style = "single"`:

```python
def foo():
    '''
    Single quotes.
    ''''

    return '''foo''' + 'bar'
```

Gets turned into:

```python
def foo():
    """
    Single quotes.
    """

    return """foo""" + 'bar'
```

**Comment by henryiii** [comment]
Okay, closing as dup.

**Comment by charliermarsh** [comment]
@henryiii - We ended up changing the behavior (during the alpha) such that we always use double quotes for multiline strings. Also relevant is the discussion in here (https://github.com/astral-sh/ruff/issues/7525) around supporting a `quote-style = "preserve"`.
