### ISSUE TITLE
Ruff and reviewdog question

### ISSUE THREAD

**Issue by eremeevfd** [astral-sh/ruff#8253]
Guys, I'd appreciate a little help here, has anybody integrated reviewdog with ruff yet?  
Which `--output-format` value did you use?

**Comment by Keramblock** [comment]
@VianneyMI I saw you mentioned it here: https://github.com/astral-sh/ruff/discussions/4982#discussioncomment-6140413 could you please share your config?

**Comment by charliermarsh** [comment]
I'm gonna merge this into #8655 which is an explicit request to support the reviewdog format as a first-class `--output-format`.

**Comment by ryaminal** [comment]
Just so I understand, this was marked closed "not planned" because it's been merged with #8655 , not because we aren't going to have `ruff` + `reviewdog` support, right?

**Comment by ryaminal** [comment]
Ah, it does say "duplicate" but i totally missed that. doh.
Thanks for the response.

**Comment by abitrolly** [comment]
I guess you can use https://github.com/reviewdog/action-suggester which is generic suggester based in `diff`.

**Comment by benner** [comment]
I also have directly reviewdog+ruff action: https://github.com/benner/action-ruff
