### ISSUE TITLE
Consider requiring a uniform quote style for implicit string concatenations

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#8265]
Given a string concatenation, the formatter currently determines the quote style for each segment individually, which can result in different segments using different quote styles.

I believe this is consistent with Black, but I don't know that it's the right decision... For example, it means that if you move content between the segments, you may have to change quotes.

We explicitly avoid this in our flake8-quotes rule (https://github.com/astral-sh/ruff/issues/2400). Let's at least consider doing the same here.

**Comment by MichaReiser** [comment]
> I believe this is consistent with Black, but I don't know that it's the right decision... For example, it means that if you move content between the segments, you may have to change quotes.

To clarify: Do you mean our behavior is consistent with Black or using a single quote style for an entire string is consistent with black? 

[Black](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB-AE1dAD2IimZxl1N_Wk6Clxrt77Zbv3ZcCoP_W78Viofe7KlLF4ZvO-sc32lJ-5_yjUiZPw0b_O9I2zcOomSiEdjAO7F2RhrTugFCnMfz8rdgAAAAAG7HY-yfprSoAAFpf2gJA1QftvN9AQAAAAAEWVo=)

**Comment by charliermarsh** [comment]
> To clarify: Do you mean our behavior is consistent with Black or using a single quote style for an entire string is consistent with black?

I mean our behavior is consistent with Black.

**Comment by MichaReiser** [comment]
I close this. Has never come up ;)
