### ISSUE TITLE
Formatter: `hug_parens_with_braces_and_square_brackets` preview style

### ISSUE THREAD

**Issue by konstin** [astral-sh/ruff#8279]
Port the `hug_parens_with_braces_and_square_brackets` preview style added to black in [PR1](https://github.com/psf/black/pull/3964) and [PR1]([second PR](https://github.com/psf/black/pull/3992)) to ruff formatter:

For better readability and less verticality, _Black_ now pairs parantheses ("(", ")")
with braces ("{", "}") and square brackets ("[", "]") on the same line for single
parameter function calls. For example:

```python
foo(
    [
        1,
        2,
        3,
    ]
)
```

will be changed to:

```python
foo([
    1,
    2,
    3,
])
```

**Comment by MichaReiser** [comment]
Is this preview style?

**Comment by konstin** [comment]
yes

**Comment by zanieb** [comment]
😬 I do not prefer this style.

**Comment by ju1ius** [comment]
> 😬 I do not prefer this style.

😬 I do prefer this style.

**Comment by Mogost** [comment]
Don't forget to share your opinions in the black repo when the time comes. 

https://github.com/psf/black/issues/3989#issuecomment-1783196332

> Last year I feel we may not have gotten enough feedback during this period, leading to some controversy over certain decisions, so I hope we'll be able to get more early feedback this year. If Ruff or its users could provide feedback on any preview-style features, I'd be happy.

**Comment by henriholopainen** [comment]
FYI: https://github.com/psf/black/pull/3992

**Comment by konstin** [comment]
@henriholopainen That's what's implemented in https://github.com/astral-sh/ruff/pull/8293/files#diff-b84e5729fb09571d5fd2e3fcba65612a57765cd6351ba6388b674208b79877ffR48-R60, right?

**Comment by charliermarsh** [comment]
This is now supported via https://github.com/astral-sh/ruff/pull/8293, though we don't yet apply these rules recursively (intentionally).

**Comment by charliermarsh** [comment]
We're gonna continue without applying these rules recursively.

**Comment by ulgens** [comment]
Is this ~rule~ _behaviour_ listed in docs? I looked for it and found nothing. How `--preview` affects format behaviour seems to be missing in docs too.

**Comment by MichaReiser** [comment]
This is not a rule. It's a formatter preview style (can be enabled with `format.preview = true`)

**Comment by ulgens** [comment]
I understand it's not a rule, but there is no mention of `format.preview = true` changes this mechanism and I think there should be.

**Comment by ntBre** [comment]
I'd be supportive of documenting our preview styles somewhere (and happy to open the PR). Unless I'm missing it, I don't think we list or describe them anywhere in the docs currently.
