### ISSUE TITLE
`S604` shows warning for any type, not just `True`

### ISSUE THREAD

**Issue by adamhl8** [astral-sh/ruff#8310]
Say you have something like this:
```python
def do_stuff(shell):
    pass
```

Calling this function with any argument for `shell` will show `S604`, not just `True` as the warning/documentation implies.

```python
do_stuff(shell="bash")
# S604 Function call with `shell=True` parameter identified, security issue
```

```python
do_stuff(shell=123)
# S604 Function call with `shell=True` parameter identified, security issue
```

**Comment by charliermarsh** [comment]
I believe this is as intended and matches Bandit's behavior -- I think the documentation is the problem.
