### ISSUE TITLE
Formatter: method call chain with comment, differs from black output

### ISSUE THREAD

**Issue by robmoss** [astral-sh/ruff#8330]
Black 23.10.1 and Ruff 0.1.3 produced slightly different outputs for a method call chain that includes a comment, and I couldn't find a relevant issue in the issue tracker. I've reduced to it to a much simpler example where both tools produce identical formatting for `x = ...` but different formatting for `y = ...` — black doesn't insert a newline before the closing `)` and `.f()`.

It isn't clear to me which tool is producing the "best" result. I find black's decision here slightly odd, and if I add a second method call after the `# Comment goes here: black and ruff differ` line, black **does** insert a newline before `.f()`. So perhaps I should file this is an issue with black?

```py
x = (
    very_long_function_name_with_many_arguments(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000).f().g()
    # Comment goes here: no difference
    .h()
)

y = (
    very_long_function_name_with_many_arguments(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000).f()
    # Comment goes here: black and ruff differ
    .h()
)
```

## Black output

```py
x = (
    very_long_function_name_with_many_arguments(
        100, 200, 300, 400, 500, 600, 700, 800, 900, 1000
    )
    .f()
    .g()
    # Comment goes here: no difference
    .h()
)

y = (
    very_long_function_name_with_many_arguments(
        100, 200, 300, 400, 500, 600, 700, 800, 900, 1000
    ).f()
    # Comment goes here: black and ruff differ
    .h()
)
```

## Ruff output

```py
x = (
    very_long_function_name_with_many_arguments(
        100, 200, 300, 400, 500, 600, 700, 800, 900, 1000
    )
    .f()
    .g()
    # Comment goes here: no difference
    .h()
)

y = (
    very_long_function_name_with_many_arguments(
        100, 200, 300, 400, 500, 600, 700, 800, 900, 1000
    )
    .f()
    # Comment goes here: black and ruff differ
    .h()
)
```

**Comment by MichaReiser** [comment]
Interesting, thank's for reporting. 

To me, ruff's formatting seems more consistent and produces fewer changes when inserting/removing `.g()` (a method call) from the call chain, which is what both Black and Ruff optimize for.

I'm not quite sure why black avoids inserting the newline when omitting `g`, and it could be a bug on their side.  It might be worth filing an issue on their side.

**Comment by robmoss** [comment]
There have been quite a few similar issues filed with Black recently, and they've all been given the label `T:bug`. So I think it's fair to say that ruff's formatting isn't an issue here.

**Comment by charliermarsh** [comment]
@robmoss - Thanks for following up!
