### ISSUE TITLE
Formatter: `dummy_implementations` preview style

### ISSUE THREAD

**Issue by jab** [astral-sh/ruff#8357]
Add support for Black's [`dummy_implementations`](https://github.com/psf/black/pull/3796) preview style. It introduces new rules around blank lines. Violates [`E704`](https://github.com/psf/black/issues/3887) that Ruff does not implement. 

See https://github.com/psf/black/pull/3796 and referenced links. E.g. from https://github.com/psf/black/issues/1797#issuecomment-1528381732:

> * If the body of a class or function is just `...`, put it on the same line directly after the colon
> * If multiple adjacent functions with the same name each have only `...` as their body, remove the blank lines between them. (This would apply to overloads in practice, but avoids hardcoding behavior for the "overload" name.)

This task is a child of https://github.com/astral-sh/ruff/issues/6935. This is required for ruff to provide a drop-in replacement for black with the preview style.

**Comment by zanieb** [comment]
@jab would you mind updating the issue with some consolidated documentation about what this change entails and what motivates it? e.g. as in #8436

**Comment by MichaReiser** [comment]
Part of this was implemented in https://github.com/astral-sh/ruff/issues/7440
