### ISSUE TITLE
Improve documentation on import sorting

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#8367]
We've seen a lot of confusion about the relationship of import sorting with the linter and formatter. In the future, this situation may be improved i.e. by #8232 but until then it'd be great to have some clear guides in the documentation about how these currently interact and a recipe for enabling import sorting in projects.

**Comment by bluthej** [comment]
I ran into that a few days ago and ended up tweaking my helix config to have both format and import sorting on save. I'd very much like to help out on this issue if you're looking for some hands on this! 

Right now I'm following what I've found on some other thread, which consists in piping the result of a call to `ruff check` (which sorts imports) to a call to `ruff format` (which does the rest of the formatting). Is that the kind of config you would like to be documented? Or did you have something a bit cleaner in mind? Ideally if there's a way to do both in a single call to Ruff that'd be great but AFAIK this is not doable right now.
