### ISSUE TITLE
B008 complains about function call when constructing a default parameter value as a exception

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [astral-sh/ruff#8378]
https://play.ruff.rs/54edf8a4-4c2f-4c0e-a5d8-b7b4afa7a19e

a definition like 
```py
def pain( error: Exception | None = ValueError("Hosts weren't successfully added")):
    pass
```

triggers
```
B008: Do not perform function call `ValueError` in argument defaults`
```

**Comment by charliermarsh** [comment]
I'm definitely open-minded about improving the rule, but can you say a bit more about why you think this case should be excluded? Alternatively, why prefer this over the in-body initialization pattern?

```python
if error is None:
    error = ValueError("Hosts weren't successfully added")
```

**Comment by RonnyPfannschmidt** [comment]
In my case none is a valid meaningful parameter variant

Creating sentinels as replacement is pretty painful

**Comment by charliermarsh** [comment]
Ahh I see, so passing in `error=None` has meaningfully different behavior. And I assume you don't want to define the sentinel in the module body.

The challenge here is that I don't know how to avoid this without disabling the rule altogether. Even here, `error` isn't immutable, so calls to `pain` could modify the shared error value...

**Comment by RonnyPfannschmidt** [comment]
The rule is about function calls,I believe it's fair game to allow construction of built-in exceptions

**Comment by RonnyPfannschmidt** [comment]
https://github.com/PyCQA/flake8-bugbear/blob/907e0dd29a99818591a604d4557c70ea33204712/bugbear.py#L1660-L1667 has more details in the error

https://github.com/astral-sh/ruff/blob/4170ef050853998f2ea3423e7fbf0a5c38a9323b/crates/ruff_linter/src/rules/flake8_bugbear/rules/function_call_in_argument_default.rs#L60 is rather barebones

i would recommend to extend the error with the suggestion

**Comment by charliermarsh** [comment]
Does that suggestion solve the problem for you though? Do you consider that a reasonable workaround?

**Comment by RonnyPfannschmidt** [comment]
Yes
