### ISSUE TITLE
Show configuration toml files in tabs within the docs

### ISSUE THREAD

**Issue by doolio** [astral-sh/ruff#8384]
To better understand what I mean see [here](https://hatch.pypa.io/latest/config/environment/overview/#environment-configuration) and below in the hatch docs which also uses Material for Mkdocs.

![image](https://github.com/astral-sh/ruff/assets/13859009/573e8730-c72c-4b50-8214-7c5e184f55f9)

It doesn't seem the case in the hatch docs that if you select one such tab that all the tabs that follow automatically select the same tab. I don't know how it is done but that is the case in the hugo docs for example [here](https://gohugo.io/getting-started/configuration/#configuration-directory) and below and it is a really nice feature.

![image](https://github.com/astral-sh/ruff/assets/13859009/0b8b0f8c-0914-44c1-b2ed-1854923f5b49)

I think this would be a great improvement to the `ruff` docs in terms of readability and understanding for users.

**Comment by charliermarsh** [comment]
This would be great, especially for showing `pyproject.toml` vs. `ruff.toml`.

**Comment by charliermarsh** [comment]
mkdocs: https://squidfunk.github.io/mkdocs-material/reference/content-tabs/

**Comment by doolio** [comment]
> Content tabs are linked based on their label, not offset. This means that all tabs with the same label will be activated when a user clicks a content tab regardless of order inside a container. 

And this from the page you linked suggests maybe what I described implemented in the hugo docs is possible with Material for MkDocs.

**Comment by dhruvmanila** [comment]
For reference, FastAPI does a lot of this in it's documentation. For example,
* Code: https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/python-types.md#generic-types
* Rendered: https://fastapi.tiangolo.com/python-types/#generic-types

**Comment by charliermarsh** [comment]
Would love for someone to take this on, great contributor project that doesn't require Rust :)

**Comment by trag1c** [comment]
I'd like to work on this, please assign me :)

**Comment by doolio** [comment]
I would be happy to help too. I'm a bit reluctant to take it all on owing to the pace this project is moving and my time. I wouldn't want to disappoint people. Maybe, if it is a lot of work we could split it between myself and trag1c?

**Comment by MichaReiser** [comment]
@trag1c could you comment here / reach out to @doolio if you see ways of collaborating on this issue? 

@doolio in what kind of wark are you interested?

**Comment by trag1c** [comment]
Hey, to be fair I think I'm almost done if I didn't miss anything, I just need to update the part that generates the Settings section.

**Comment by charliermarsh** [comment]
Thanks @trag1c, that's awesome (and to @doolio for offering to help)!

**Comment by doolio** [comment]
I'm only learning to program (starting with python) so I think I could only meaningfully contribute right now in terms of reporting issues  and improving the docs.
