### ISSUE TITLE
N805 not compatible with sqlalchemy hybrids

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#8397]
Apologies for opening a new issue for what's basically part of #4604, but considering that this is one closed even though half of it has not been addressed at all, and I'm not getting any replies to my comment there, I think opening a new one makes sense - this is clearly a missing feature / bug, and it makes this particular check from ruff pretty much unusable for any codebase using SQLAlchemy's hybrid properties.

Basically I need ruff to treat either `@*.expression` as a classmethod decorator, or alternatively have a way of telling it that `sqlalchemy.ext.hybrid.hybrid_property` returns a normal property, but the method decorated with that property has a `.expression` attribute that is a classmethod decorator...

---

### ruff.toml

```toml
select = ['N805']

[pep8-naming]
classmethod-decorators = [
    'classmethod',
    'declared_attr',
    'expression',
    'comparator',
]
```

### ruff_sample.py

```python
from sqlalchemy.ext.hybrid import hybrid_property


class SQLAlchemyModel:
    @hybrid_property
    def foo(self):
        return not self._foo

    @foo.expression
    def foo(cls):
        return ~cls._foo
```

### Output

```
$ ruff check ruff_sample.py
ruff_sample.py:10:13: N805 First argument of a method should be named `self`
Found 1 error.
```

### Version
```
ruff==0.1.3
```

**Comment by zanieb** [comment]
Perhaps we can allow wildcards in `classmethod-decorators`; would that address your use case?

**Comment by ThiefMaster** [comment]
i think one of these solutions would be the easiest and indeed solve my issue:

- wildcard support as you proposed, applied to the whole decorator function name
- doing a suffix match when the entry in classmethod-decorators starts with a dot
