### ISSUE TITLE
Integrate GitHub Actions in this repo

### ISSUE THREAD

**Issue by jonathanberthias** [astral-sh/ruff#8400]
Hello! And thanks for the great work on `ruff`!

As a first disclaimer, I know about [ChartBoost/ruff-action](https://github.com/ChartBoost/ruff-action), and I've read the arguments that were raised at the time in #3289.

Currently, to run `ruff` in an idiomatic way with a pinned version, we have to use:
```yaml
- uses: chartboost/ruff-action@v1
  with:
    - version: 0.1.3
```

I'd like to reopen the discussion of having the action as part of this repo, primarily to help automated dependency updaters like Dependabot and [Renovate](https://docs.renovatebot.com/). In the snippet above, they detect the version of `chartboost/ruff-action`, and would open a PR to update that version if another version __of the action__ were released. However, they do not detect the version of `ruff` automatically.
With Renovate, it is possible to get it to find and update the version of `ruff` but that requires a custom regex which must be configured in each repo/org.

By contrast, _Black_ can be run as:
```yaml
- uses: psf/black@23.10.0
```
which would run _Black_ version 23.10.0, and the tag would be updated automatically whenever _Black_ gets a new release.

In the initial issue and associated PR (#3756), there was some concern due to linking the version of the action and `ruff` itself. 7 months later, I think it is safe to say the action is [very low maintenance](https://github.com/ChartBoost/ruff-action/commits/main), and does not require its own versioning. And if changes need to be done to the action, they can be released with `ruff`

The end goal of this issue would be to get:
```yaml
- uses: astral-sh/ruff@0.1.3
```
to work as expected.

For reference, [here](https://github.com/psf/black/blob/main/action/main.py) is the action code run by _Black_. It is slightly more complicated than the current `ruff-action`, though perhaps not all features are necessary (such as specifying any commit as version?).

Is this something the `ruff` team is willing to reconsider?

**Comment by zanieb** [comment]
I would like to have an official action if someone is willing to contribute it. I think this would be ideal for us to maintain since we can then update it as we make breaking changes which would alleviate some of the issues we saw when dropping support for `--format`.

I want @charliermarsh's opinion too though.

**Comment by charliermarsh** [comment]
Yeah, I think we should have our own official action.

**Comment by ethanholz** [comment]
Out of curiosity, what would this take to fold in the work from #3289 into something supported by Astral? I am interested in helping to assist with this but want to understand what it would take to get this into something more official.

**Comment by ethanholz** [comment]
As a follow-up to above, I did find the following: https://github.com/ChartBoost/ruff-action/issues/26#issuecomment-2120939757 . So it looks like this might not need much more in terms of contribution if I am understanding correctly.

**Comment by zanieb** [comment]
Yes we are attempting to make the action official and are just being patient regarding the transfer so it doesn't break a bunch of existing users.

**Comment by charliermarsh** [comment]
We now have https://github.com/astral-sh/ruff-action and are continuing to invest in the action over there.
