### ISSUE TITLE
Proposal: Add basic Python API

### ISSUE THREAD

**Issue by sam-bristow** [astral-sh/ruff#8401]
Is the ruff team open to exposing a minimal Python API for interacting with the checker and formatter?

I am looking at integrating Ruff into some code-generation tooling but having to interact with the tool through `subprocess` and temporary files adds a few footguns.

By exposing ~4 Python functions I think we could cover 90% of the common requirements for Ruff as a library:

```python
def load_config(config: str) -> RuffConfig:
    ...

def format(source: str, config: Optional[RuffConfig] = None) -> str:
    ...

def formatted(source: str, config: Optional[RuffConfig] = None) -> bool:
    ...

def check(source: str, config: Optional[RuffConfig] = None) -> bool:
    ...
```
These functions all operate on strings rather than files leaving all IO to the wrapping code.

A typical example of using this API might look like:

```python
#...
with open('pyproject.toml', 'r') as f:
    config = load_config(f.read())

formatted_code = ruff.format(some_code_fragment, config)
#...
```

With these functions available implementing Ruff equivalents of `blacken-docs` etc would be fairly mechanical.

Any thoughts?

**Comment by MichaReiser** [comment]
Hey. Yeah, interacting with subprocess is annoying. There are a couple concerns outlined in https://github.com/astral-sh/ruff/issues/659 mainly around the stability concerns and Ruff using `stdout` in some places instead of structured diagnostics.

**Comment by sam-bristow** [comment]
Ah, I spent a reasonable amount of time looking for an existing ticket but clearly didn't have the right combo of keywords. Should I close this ticket and reword my use-cases as a comment on #659 ?

In my case I don't really need structured diagnostics for the checker functionality. A simple "good"/"no-good" is plenty.

More important for me is being able to work with strings rather than temporary files.

**Comment by akx** [comment]
@sam-bristow You don't need to use temporary files, since `ruff` supports the UNIX convention of `-` being a stand-in for `stdin`.

```python
import json
import subprocess

bad_code = "print   ('hi');"

# Formatter example
formatted = subprocess.check_output(
    ["ruff", "format", "-"], input=bad_code, encoding="utf-8"
)
print(repr(formatted))

# Checker example
proc = subprocess.run(
    ["ruff", "--select=ALL", "--output-format=json", "check", "-"],
    input=bad_code,
    stdout=subprocess.PIPE,
    stderr=subprocess.DEVNULL,
    encoding="utf-8",
)
print(proc.returncode)  # 1 if bad
print(json.loads(proc.stdout))
```

outputs 
```
'print("hi")\n'
1
[{'cell': None, 'code': 'E902', ...
```

You can also add `--stdin-filename=...` if you like.

**Comment by charliermarsh** [comment]
👍 I'm gonna merge this into #659. Definitely feel free to chime in there -- though if your use-case is solved by passing data via `stdin` as @akx kindly mentioned above, that's cool too :)
