### ISSUE TITLE
Feature Request: ICN001 import-alias-is-not-conventional fixer

### ISSUE THREAD

**Issue by peterjc** [astral-sh/ruff#8405]
Trying out ruff 1.0.3, I'm getting a fair few non-conventional import warnings:

```
ICN001 `matplotlib` should be imported as `mpl`
ICN001 `matplotlib.pyplot` should be imported as `plt`
ICN001 `networkx` should be imported as `nx`
ICN001 `numpy` should be imported as `np`
ICN001 `tkinter` should be imported as `tk`
```

Is this something which could have a fixer? The import lines themselves ought to be fairly easy to fix, but you _also_ need to update all usage of the old name to the new alias.

(Ideally without introducing a bug due by creating a name collision etc.)

**Comment by charliermarsh** [comment]
I think we actually do support a fix for that rule. Have you tried running with `--unsafe-fixes`?

**Comment by peterjc** [comment]
Confirmed, and it looks to have worked perfectly too. I'm not sure how I overlooked this. Apologies, and thank you!
