### ISSUE TITLE
Fun with imports :)

### ISSUE THREAD

**Issue by vgoklani** [astral-sh/ruff#8408]
Hey there,

Thanks for updating Ruff to support the python-black formatter!

I'm using this on Sublime Text 4 via LSP-ruff, and these are my settings:

    {
      "log_debug": true,
      "lsp_format_on_save": true,
      "lsp_code_actions_on_save": {
        "lsp_format_on_save": true,
        "source.lsp_format_on_save": true,
        "source.fixAll": true,
        "source.organizeImports": true,
        "source.applyFormat": true
      },
      "clients": {
        "ruff-lsp": {
          "command": [
            "ruff-lsp"
          ],
          "enabled": false,
          "selector": "source.python",
          "initializationOptions": {
            "settings": {
              "args": [],
            },
          },
        },
      },
    }

There are a few quirks that I just wanted to point out:

1. imports that aren't yet used automatically get removed when I save the file.  

> As I'm writing code, I add import statements, and instinctively hit the save button, only to find that those imports are then removed. I do like how you *organize* the imports, but I don't like how they disappear! Is it possible to add an additional parameter to separate these two cases.

2. When writing f-strings, this case is not being caught by Ruff:

    my_string = f"Hello {data["name"]}"

previously `python-black` would catch the fact that we are using `"` in both the string declaration and the `data` dictionary. Ruff is not catching these cases, which leads to run-time errors.

Thanks for releasing Ruff, looking fowrard to more features :)

**Comment by dhruvmanila** [comment]
> previously `python-black` would catch the fact that we are using `"` in both the string declaration and the `data` dictionary. Ruff is not catching these cases, which leads to run-time errors.

Can you expand on how is `python-black` catching this case? Is it throwing an error stating that this syntax isn't supported? I think https://github.com/astral-sh/ruff/issues/6591 would solve your use-case.

**Comment by dhruvmanila** [comment]
For (1), do you wish to just disable the fix and allow the editor to highlight unused imports? If so, you can use the [`unfixable`](https://docs.astral.sh/ruff/settings/#unfixable) setting to do that.

For additional context, the organize imports action isn't responsible for removing unused imports. It's the [`F401`](https://docs.astral.sh/ruff/rules/unused-import/) rule whose auto-fix removes them and as @zanieb suggested, you could either disable the rule entirely or just disable the fix.

**Comment by charliermarsh** [comment]
Going to close for now, but happy to answer any follow-up questions.

**Comment by vgoklani** [comment]
@dhruvmanila sorry I missed your reply

I used `python-black` in sublime text 4. For case #2, it would highlight the row when either `'` or `"` were used incorrectly as part of the f-string.

**Comment by dhruvmanila** [comment]
> I used `python-black` in sublime text 4. For case #2, it would highlight the row when either `'` or `"` were used incorrectly as part of the f-string.

By incorrectly, do you mean that the outer and inner quotes were the same? The linked issue in my comment should solve this although how do we go about implementing it isn't final yet.
