### ISSUE TITLE
Disable formatter for specific lines

### ISSUE THREAD

**Issue by sparisi** [astral-sh/ruff#8415]
Say I have a function like `f(a, b, c, d, e, f)` (with longer var names) that gets split into 
```
f(
 a,
 b, 
 c, 
 d, 
 e, 
 f,
)
```

I'd prefer to have
```
f(
 a, b, c,
 d, e, f,
)
```

so I would like ruff formatter to ignore it.  
I know there are `noqa` comments that work for the linter, but I can't make them work for the formatter as well. Is it possible to do something like that?

**Comment by charliermarsh** [comment]
You should be able to use `# fmt: off` and `# fmt: on`, like:

```python
# fmt: off
f(
 a, b, c,
 d, e, f,
)
# fmt: on
```

There's a bit more in the docs here: https://docs.astral.sh/ruff/formatter/#format-suppression

**Comment by sparisi** [comment]
I'm using `# fmt: skip`, works perfectly! Thanks again!

**Comment by charliermarsh** [comment]
Awesome! No prob.

**Comment by madduck** [comment]
I am trying this but to no avail:

```
albatross:~/code/pngx|main|pngx% ruff format --diff pngx.py
--- pngx.py
+++ pngx.py
@@ -67,7 +67,9 @@
         self._api_doctypes: PaperlessObjectWrapper | None = None
 
     def __enter__(self) -> PaperlessNGX:
-        import ipdb; ipdb.set_trace()  # fmt: skip  # noqa: E402 E702 I001
+        import ipdb
+
+        ipdb.set_trace()  # fmt: skip  # noqa: E402 E702 I001
         return self
 
     def __exit__(

1 file would be reformatted
```

I also tried putting `# fmt: skip` at the end of the line. Same problem.

Any clues?
