### ISSUE TITLE
Smart handling of lines that are too long

### ISSUE THREAD

**Issue by pitosalas** [astral-sh/ruff#8428]
In my code I have some lines which are too long. Perhaps it's a long f string for output or a long expression. It would be nice if ruff did some smart things to deal with the too long lines in a way that looks good. For example turning the string into several concatenated strings or something. Is that possible?

I have tried various pyproject.toml settings but they don't seem to have any effect. Maybe that's my problem>?

**Comment by zanieb** [comment]
This is available in Black's preview style (https://github.com/psf/black/issues/182) and we are working on an implementation for it — but it's a difficult feature to get correct.

**Comment by MichaReiser** [comment]
@pitosalas are you using ruff's formatter or is this feedback related to `E501` (line-too-long) rule?

**Comment by pitosalas** [comment]
@MichaReiser Honestly I am not sure. This is my first use of ruff. But my intent is that the formatter notices a line too long and does semi-intelligent things with indentation and even notational changes to make the line not be too long anymore.

**Comment by charliermarsh** [comment]
@pitosalas - Have you tried running `ruff format` instead of `ruff check`? That will attempt to wrap lines for you.

**Comment by charliermarsh** [comment]
Gonna close for now in the absence of more info, but recommend trying out `ruff format`!
