### ISSUE TITLE
Formatter: Parenthesize long expressions in dicts

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#8437]
See https://github.com/astral-sh/ruff/issues/8436 for background.

Stable formatting of dicts with a long value results in a wrap that reduces readability

Unformatted:

```python
if True:
    ___ = {
        "x": "---",
        "y": "--------------------------------------------------------------" if True else None,
        "z": "---",
    }
```

Formatted (Ruff, Black stable):

```python
if True:
    ___ = {
        "x": "---",
        "y": "--------------------------------------------------------------"
        if True
        else None,
        "z": "---",
    }
```

Formatted (Black preview):

```python
if True:
    ___ = {
        "x": "---",
        "y": (
            "--------------------------------------------------------------"
            if True
            else None
        ),
        "z": "---",
    }

```

With a shorter line, Ruff retains parenthesis when the lines are collapsed:

```python
if True:
    ___ = {
        "x": "---",
        "y": ("----------------------------------------------------" if True else None),
        "z": "---",
    }
```

However, these parenthesis should be removed as they are superfluous.

Black's preview style **will** remove these parenthesis:

```python
if True:
    ___ = {
        "x": "---",
        "y": "----------------------------------------------------" if True else None,
        "z": "---",
    }
```

See https://github.com/psf/black/issues/620 https://github.com/psf/black/pull/3440

Note that Black does _not_ remove these parenthesis for calls or lists, see https://github.com/astral-sh/ruff/issues/8436 and #8438

**Comment by MichaReiser** [comment]
I merged this into https://github.com/astral-sh/ruff/issues/8438 and create a new issue for parenthesizing long values.
