### ISSUE TITLE
playground - popover is cut off when at the top of the file

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#8442]
![image](https://github.com/astral-sh/ruff/assets/57028336/375ae386-b6f4-45bd-92b6-410da597408c)
https://play.ruff.rs/e10d4570-4368-4d83-af88-57b221fe899f

tested in both chrome and firefox

**Comment by MichaReiser** [comment]
You mean that the popower is cut off when at the top of the file?

**Comment by DetachHead** [comment]
yeah oops i messed up the title lol
