### ISSUE TITLE
Question: is it possible to exclude test files specifically for pydocstyle 

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/ruff#8471]
I'm considering enabling ruff.pydocstyle for an existing project that is supposed to follow NumPy's style but isn't systematically checked yet. The issue I'm having is that most errors I'm getting are about missing docstrings in test functions. I would like to ignore tests files entirely but only for this subset of rules, is there a way to do it ? If not, I'd suggest adding a `extend-exclude` option to `[tool.ruff.pydocstyle]`.

Thanks again for building this wonderful tool !

**Comment by charliermarsh** [comment]
Yeah, I'd recommend [`per-file-ignores`](https://docs.astral.sh/ruff/settings/#per-file-ignores):

```toml
[tool.ruff.per-file-ignores]
# Ignore all directories named `tests`.
"tests/**" = ["D"]
# Ignore all files that end in `_test.py`.
"*_test.py" = ["D"]
```

You can use this same approach to ignore other errors in tests too.

**Comment by neutrinoceros** [comment]
Perfect ! Sorry I missed that in the documentation, and thank you for answering so promptly !

**Comment by charliermarsh** [comment]
No worries!
