### ISSUE TITLE
UP007: Does not respect target version and suggests incompatible syntax

### ISSUE THREAD

**Issue by chbndrhnns** [astral-sh/ruff#8484]
To me it seems that ruff should only suggest fixes that are compatible with the configured target version. That's not the case for this example using ruff 0.1.4.

Command:

```
ruff check .
```

Config:

```
target-version = "py39"

[lint]
select = ["UP"]

```

Code:

```py

from __future__ import annotations

from typing import Optional


class C:
    int: Optional[int]

```

Output:
```
main.py:7:10: UP007 Use `X | Y` for type annotations
```

This is even auto-fixable but will result in a syntax error on Python 3.9

**Comment by tjkuson** [comment]
Using `|` isn't a syntax error in Python 3.9 if you import `annotations` from `__future__`. More information can be found on the [docs](https://docs.astral.sh/ruff/rules/non-pep604-annotation/).

**Comment by chbndrhnns** [comment]
Thanks, I read the docs now and it turned out it's coming from pydantic. Thanks much!

**Comment by charliermarsh** [comment]
👍 You can also disable this behavior (of using newer syntax when `__future__` is present via [`keep-runtime-typing`](https://docs.astral.sh/ruff/settings/#pyupgrade-keep-runtime-typing).
