### ISSUE TITLE
Docs/website: https://astral.sh/ruff is not automatically updating `VERSION v0.1.2`

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff#8493]
Ruff is currently at version [`v0.1.4`](https://github.com/astral-sh/ruff/releases/tag/v0.1.4), but https://astral.sh/ruff shows:

Top of the page:

![image](https://github.com/astral-sh/ruff/assets/30827238/f14d5e9e-5464-4ba7-8944-e32400696907)

Bottom of the page:

![image](https://github.com/astral-sh/ruff/assets/30827238/74519cfe-4aa0-420c-ab3f-89445b02d494)

**Comment by charliermarsh** [comment]
Thanks, just fixed...
