### ISSUE TITLE
E701 is not listed on the "Conflicting lint rules" page but it conflicts with `ruff format` when `--preview` flag is used

### ISSUE THREAD

**Issue by AIGeneratedUsername** [astral-sh/ruff#8496]
## The original code

```py
from contextlib import nullcontext

ctx = nullcontext()
with ctx:
    ...
```

## Steps to reproduce

`ruff format --isolated --preview sample.py` moves ellipsis:

```py
from contextlib import nullcontext

ctx = nullcontext()
with ctx: ...
```

and now `ruff --isolated --fix --preview sample.py` will complain about `:` and ellipsis on a same line:

```
sample.py:4:9: E701 Multiple statements on one line (colon)
Found 1 error.
```

## Expected behavior 

No conflicts between `ruff check` and `ruff format`.

## Versions

- ruff 0.1.4
- Python 3.11.6

## Related

In the comment a developer assumed that `E701` is not conflicting https://github.com/astral-sh/ruff/pull/8088/files#r1366486452

**Comment by charliermarsh** [comment]
Thanks, it should now be marked as conflicting as of that change to preview style.

**Comment by charliermarsh** [comment]
Actually, I think we should just allow this in `E701`.

**Comment by charliermarsh** [comment]
Oh, we do allow it in some cases (https://github.com/astral-sh/ruff/pull/2837).
