### ISSUE TITLE
Fix ruff.toml examples in the documentation

### ISSUE THREAD

**Issue by CharlesPerrotMinotHCHB** [astral-sh/ruff#8505]
Hi,
Thank so much for tuff! Love it so far.

There are a couple inconsistencies in the documentation for settings, where the value given as an example for what to use in the `ruff.toml` is the one to put in the `pyproject.toml` ; it has `tool.ruff.` in the the section name.
- https://docs.astral.sh/ruff/settings/#extend-per-file-ignores
- https://docs.astral.sh/ruff/settings/#per-file-ignores
- https://docs.astral.sh/ruff/settings/#flake8-import-conventions-aliases
- https://docs.astral.sh/ruff/settings/#flake8-import-conventions-banned-aliases
- https://docs.astral.sh/ruff/settings/#flake8-import-conventions-extend-aliases
- https://docs.astral.sh/ruff/settings/#flake8-tidy-imports-banned-api
- https://docs.astral.sh/ruff/settings/#isort-sections

**Comment by charliermarsh** [comment]
Thanks a lot for reporting this, good catch (the dual `pyproject.toml` and `ruff.toml` tabs are new).

**Comment by doolio** [comment]
I also noticed the tabs have not been added to all the FAQs.

https://docs.astral.sh/ruff/faq/?query=If+Ruff+detects+multiple+configuration+files#i-want-to-use-ruff-but-i-dont-want-to-use-pyprojecttoml-what-are-my-options

I will submit a PR.

**Comment by doolio** [comment]
Do you want the `ruff.toml` tab labels to include `.ruff.toml` as well i.e. something like `ruff.toml/.ruff.toml`?

**Comment by doolio** [comment]
> I also noticed the tabs have not been added to all the FAQs.
> I will submit a PR.

See #8512 for consideration.

**Comment by trag1c** [comment]
> Edit: There is also an inconsistency in the markdown source blocks where for some the entire block is indented and for others it is not. Do you have a preference so I could apply the same style consistently?

As far as I'm concerned indented code blocks are only used for tabs because that's the syntax they require (up until my change you couldn't even have indented code blocks because CI would fail otherwise).
