### ISSUE TITLE
Difference in multi-line str.format between ruff and black

### ISSUE THREAD

**Issue by dwyatte** [astral-sh/ruff#8530]
Settings: Default ruff `0.1.3`

`black` formats multi-line strings by adding args to `str.format` on a newline

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACkAG9dAD2IimZxl1N_Wj9gaSn83r_MDRh3Sohxk5tq0YJ9PWyG6Cyohdz_PJoc7zUs17RxhRdCnJ7Npmq7PfdCxS68vrTxtZKdTAoQUsbG77GpIhJyuHq4tEKRNQcU7LDmXIq_Rno-hiLpkYbL4dUTP5aaAAAA1H7xhdfRFL8AAYsBpQEAAHaaNfGxxGf7AgAAAAAEWVo=

`ruff` keeps args to a multi-line `str.format` on a single line, presumably until it hits `line-length`

ruff
```
MULTI_LINE_STRING = """
a
b
c
{}
""".format("d")
```

black
```
MULTI_LINE_STRING = """
a
b
c
{}
""".format(
    "d"
)
```

This causes a cost in migrating to ruff in codebases that contain a large number of multi-line strings that get formatted

**Comment by zanieb** [comment]
Thanks for the report.

I'm not sure I understand the logic in Black's formatting here.

Separately from Black compatibility, do you prefer that formatting?

Note that Black's preview style formats the same as Ruff so we are unlikely to change this.

**Comment by dwyatte** [comment]
> Note that Black's preview style formats the same as Ruff so we are unlikely to change this

Ah, so if I'm understanding correctly, this *might* get collected into Black's 2024 release anyway ([link for others](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-multiline-string-handling)). If it ends up not making the cut, would `ruff` continue to use the current one-line style?

**Comment by zanieb** [comment]
That's a good question, I'm not sure. Often we would only implement the preview style over the stable style if it was a hard technical challenge. The inconsistency here is pretty weird, I can't think of other cases where a function call would be forced to break over multiple lines like that. It'd likely make it difficult for us to implement.

**Comment by charliermarsh** [comment]
(Thanks for filing!) We tend not to fix deviations from Black if they are (1) a result of greater internal consistency in Ruff's formatter, and/or (2) already part of Black's preview style. This one feels like it meets both of those descriptions, so I think I'd categorize it as acceptable.

**Comment by dwyatte** [comment]
> (2) already part of Black's preview style

Yep, was unaware of this. I think we can close this as I don't have a strong preference independent of compatibility

**Comment by charliermarsh** [comment]
Thanks @dwyatte, appreciate you taking the time to file these.

**Comment by MichaReiser** [comment]
The reason for the difference is that Ruff already implements Black's [multiline-string preview style](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-multiline-string-handling) because it was more difficult to support the stable style.
