### ISSUE TITLE
Difference in line-length handling between ruff and black when line ends in #

### ISSUE THREAD

**Issue by dwyatte** [astral-sh/ruff#8531]
Settings: Default ruff 0.1.3

Note: there is something specific about the example line below in terms of variable string length vs actual assignment value such that reproduction becomes difficult when changing the name/value, but this example captures the behavior I'm interested in raising in this issue

Example
```
AAAAA_BBBBBBB_CCCC = "xxxxxxxx_xxxxxxxxxx_xxx_xxxxxxxx_xx_xxxx_xxxxxxx_xxxx_xxxx_xxxx_xxxxxxx_xxxx_xxxxx"
```

When the line above is suffixed with a `#` e.g., to disable linting / formatting, black will not break it:
https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFEAGhdAD2IimZxl1N_WjPZmMnerqoaitTnd2a09E8Bi61KJWbnQshHGxfdai0l17K2DqAdXFD89RHKQ6jT30nA8Il4tW9g8JRaFzqeaQ-5TntovkAApVkiDMflIUXe64zjHKvCTRtNm3SZQwHmAKLERh2XSkjRAAGEAcUCAAD5YQM5scRn-wIAAAAABFla

Ruff however, will always break this line into 

```
AAAAA_BBBBBBB_CCCC = (
    "xxxxxxxx_xxxxxxxxxx_xxx_xxxxxxxx_xx_xxxx_xxxxxxx_xxxx_xxxx_xxxx_xxxxxxx_xxxx_xxxxx"  #
)
```

My code has some long constant names that I'd prefer not to split and apparently `# noqa: E501` is enough to exclude them from flake8 _as well as_ black's formatting by virtue of how it handles lines ending in `#`

**Comment by zanieb** [comment]
In general, we're far more careful with comment handling and therefore _can_ wrap lines like that without fear of dropping comments accidentally.

We explicitly exclude pragma comments from the line length #6772 

We provide a `# fmt: skip` pragma to skip formatting of statements, which appears to be what you need here?

**Comment by dwyatte** [comment]
> We provide a # fmt: skip pragma to skip formatting of statements, which appears to be what you need here?

Thanks, I think this will get me what I need although I suppose it's not clear how to support both disabling linting E501 _and_ formatting on that line -- I wonder if that's something ruff should support?

Seems this was an oversight on `black` as you mention though since it is using the pragma of my linting pragma to skip formatting

**Comment by zanieb** [comment]
Hm yeah I don't see a good way to do that cc @MichaReiser

**Comment by charliermarsh** [comment]
This works as expected, which seems reasonable to me?

```python
AAAAA_BBBBBBB_CCCC = "xxxxxxxx_xxxxxxxxxx_xxx_xxxxxxxx_xx_xxxx_xxxxxxx_xxxx_xxxx_xxxx_xxxxxxx_xxxx_xxxxx"  # fmt: skip  # noqa: E501
```

**Comment by zanieb** [comment]
@charliermarsh that is formatted for me with 

```
❯ ruff version
ruff 0.1.3 (3e7b92991 2023-10-26)
```

but it looks fixed in 0.1.4 so @dwyatte perhaps upgrade

**Comment by charliermarsh** [comment]
Ah okay, interesting. I'll close for now then. It does require that the skip comes before the noqa, but I think that's _okay_.

**Comment by dwyatte** [comment]
> Ah okay, interesting. I'll close for now then. It does require that the skip comes before the noqa, but I think that's okay.

Perfect, thanks all!
