### ISSUE TITLE
COM812 breaks conditionals inside multi-line f-strings

### ISSUE THREAD

**Issue by parafoxia** [astral-sh/ruff#8556]
## Synopsis

The COM812 rule is capable of breaking conditional statements within triple f-strings by converting the else-statement into a tuple (or a tuple containing the original tuple).

Of course you can use `# noqa: COM812`, though I think that linters should be incapable of breaking code.

## MRE

(This example assumes the line should be split across multiple lines.)

Original mre.py:
```py
x = f"""This is a test. {
    "Another sentence."
    if True else
    "Alternative route!"
}"""

print(x)
```
```bash
$ py test.py
This is a test. Another sentence.

$ ruff check mre.py
mre.py:4:25: COM812 [*] Trailing comma missing
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

"Fixed" mre.py
```py
x = f"""This is a test. {
    "Another sentence."
    if True else
    "Alternative route!",
}"""

print(x)
```
```bash
$ py test.py
This is a test. ('Another sentence.',)

$ ruff check mre.py
(Exit code 0)
```

## Environment
* Ruff version: 0.1.3
* Python version: 3.9.11
* OS: macOS Sonoma 14.0

**Comment by charliermarsh** [comment]
Thanks, I'll take a look at this!

**Comment by dhruvmanila** [comment]
I think it must be considering the curly braces as `ContextType::Dict`. It needs to take into account the new f-string tokens and skip if inside a f-string.

**Comment by charliermarsh** [comment]
@dhruvmanila - Feel free to fix if you're there, I won't get to it for a few hours.

**Comment by charliermarsh** [comment]
Taking a look now.
