### ISSUE TITLE
should the docs for pre-commit point to the latest ruff?

### ISSUE THREAD

**Issue by raybellwaves** [astral-sh/ruff#8561]
https://docs.astral.sh/ruff/integrations/#pre-commit (https://github.com/astral-sh/ruff/blob/main/docs/integrations.md#pre-commit) currently lists v0.0.291 as the ruff version the latest version is v0.1.4.

It would be good to have the latest version listed so users can copy-paste it and get the latest and greatest ruff features.

I image this could be fixed with a bot once new versions are released

**Comment by T-256** [comment]
fixed in https://github.com/astral-sh/ruff/pull/8545

**Comment by charliermarsh** [comment]
Thanks @raybellwaves, sorry about that.
