### ISSUE TITLE
Default config target-version 3.7 or 3.8

### ISSUE THREAD

**Issue by doolio** [astral-sh/ruff#8564]
The docs [here](https://docs.astral.sh/ruff/configuration/) state the default target version is Python 3.8 yet the README suggests ruff supports back to 3.7. Should these two be aligned?

```toml
# Assume Python 3.8
target-version = "py38"
```

**Comment by charliermarsh** [comment]
@doolio - I believe this is intended as Python 3.7 is EOL, so we no longer default to it.

**Comment by doolio** [comment]
I see. OK, sorry for the noise.
