### ISSUE TITLE
[pydocstyle] Document which rules are disabled by which conventions?

### ISSUE THREAD

**Issue by alanhdu** [astral-sh/ruff#8573]
On https://docs.astral.sh/ruff/settings/#pydocstyle-convention, it says

> Enabling a convention will force-disable any rules that are not included in the specified convention

But I can't seem to find documentation about *which* rules are included in *which* conventions! Maybe I totally missed it, but I only found this information by going to the source code and finding https://github.com/astral-sh/ruff/blob/4760af3dcbcf772fdcc1cae9aa9d0c4b8037c132/crates/ruff_linter/src/rules/pydocstyle/settings.rs#L24

Is there some place this is documented? If not, how easy/hard would it be to add some documentation? I'd be happy to contribute a patch if the best way is to just add some markdown at https://github.com/astral-sh/ruff/blob/4760af3dcbcf772fdcc1cae9aa9d0c4b8037c132/crates/ruff_workspace/src/options.rs#L2378, but maybe there's some clever way to auto-generate that information from the code to ensure it stays in sync?

**Comment by charliermarsh** [comment]
The list originally comes from pydocstyle. Perhaps we could enumerate the conventions in the FAQ, as part of the "Does Ruff support NumPy- or Google-style docstrings?" section?

**Comment by charliermarsh** [comment]
Adding this real quick.
