### ISSUE TITLE
UP007 adds parentheses when using --fix --unsafe-fixes and the Union has more than two types

### ISSUE THREAD

**Issue by Lassii-** [astral-sh/ruff#8599]
Ruff seems to add unnecessary parentheses when automatically fixing UP007 related errors.

test.py:
```python
from typing import Union

def sample(a: Union[str, int, list]):
    print(a)
```
The ruff command used:
```
ruff check --select UP007 --target-version py311 --fix --unsafe-fixes test.py
```
test.py after being modified by Ruff:
```python
from typing import Union

def sample(a: str | (int | list)):
    print(a)
```
Based on https://docs.python.org/3.11/library/stdtypes.html#union-type 
```python
from typing import Union

def sample(a: str | int | list):
    print(a)
```
would be okay unless I'm missing something?

**Comment by zanieb** [comment]
Thanks for reporting. This seems reasonable to fix, although I do not know why it is that way in the first place.

**Comment by charliermarsh** [comment]
I believe this was fixed in https://github.com/astral-sh/ruff/pull/8610.
