### ISSUE TITLE
Extend `PIE790` to ellipses

### ISSUE THREAD

**Issue by doolio** [astral-sh/ruff#8602]

**Comment by charliermarsh** [comment]
That would be reasonable. The other option is to implement a standalone rule for this, as in Pylint: https://github.com/astral-sh/ruff/pull/4726. The blocker we ran into there is that we have an existing rule from flake8-pyi ([`PYI013`](https://docs.astral.sh/ruff/rules/ellipsis-in-non-empty-class-body/)) that enforces this logic _just_ for classes, so we likely need to deprecate that rule.

I don't see a reason not to have `ellipsis` and `pass` in the same rule, though. So we could extend PIE790 (under `--preview` for now), and then mark `PYI013` as deprecated.

**Comment by Skylion007** [comment]
We would have to make sure `PIE790` applies to `.pyi` files too though as we deprecate `PYI013`.

**Comment by charliermarsh** [comment]
@Skylion007 -- Confirmed, it does.
