### ISSUE TITLE
Difference between PLR1701 and SIM101?

### ISSUE THREAD

**Issue by alanhdu** [astral-sh/ruff#8603]
I was browsing through the code and came across both PLR1701 https://docs.astral.sh/ruff/rules/repeated-isinstance-calls/ and SIM101 https://docs.astral.sh/ruff/rules/duplicate-isinstance-call/. To my reading, they look like they do the same thing (merge `isinstance(x, int) or isinstance(x, float)` to `isinstance(x, (int, float))`. Is there a difference in implementation that I'm missing, or is it a deliberate duplication?

**Comment by Skylion007** [comment]
duplicate of #8122

**Comment by alanhdu** [comment]
Huh... could've sworn I looked for duplicates. Going to close this then -- sorry for the noise!
