### ISSUE TITLE
Feature Request: `per-file-extend-select` - enable rule(s) for specific file(s).

### ISSUE THREAD

**Issue by Warchant** [astral-sh/ruff#8614]
I am facing a use-case when I need to have 1 .py file very well documented, so I'd like to enable `D` rules only for that file. 

I figured I could **ignore** certain rules in specific files with:
```
--per-file-ignores <PER_FILE_IGNORES>
    List of mappings from file pattern to code to exclude
--extend-per-file-ignores <EXTEND_PER_FILE_IGNORES>
    Like `--per-file-ignores`, but adds additional ignores on top of those already specified
```

But there is no way to **extend-select** current rule set with a rule for a specific file. 

I do not really want to enable `D` for entire project, then to ignore entire project except 1 file.

**Comment by charliermarsh** [comment]
Unfortunately it's not currently possible, but it's been requested here and folks clearly want it :) I'm gonna merge into that issue.

https://github.com/astral-sh/ruff/issues/3172

**Comment by jasha-hrp** [comment]
It looks like the other issue https://github.com/astral-sh/ruff/issues/3172 was closed as completed (since `[extend-]per-file-ignores` is now implemented), but `[extend-]per-file-select` was never implemented. @charliermarsh, do you think we could re-open this issue?
