### ISSUE TITLE
support no_sections option for isort

### ISSUE THREAD

**Issue by jelmer** [astral-sh/ruff#8653]
ruff's isort doesn't support the ``no_sections`` option that isort upstream has.  This option puts all import sinto the same import bucket.

For example, consider this source file:

```python
import os

import bar
import blah
```

isort --no-sections x.py format it as

```python
import bar
import blah
import os
```

As far as I can tell, there is no set of options for ruff's isort that provides this behaviour (if there is and I've missed it, I'll volunteer to add a note to the docs)

**Comment by charliermarsh** [comment]
I don't believe we support this today.

**Comment by jelmer** [comment]
FWIW I'm trying to come up with a PR for this.
