### ISSUE TITLE
There are too many line breaks after formatting. What can I do to reduce this?

### ISSUE THREAD

**Issue by zhuang1234** [astral-sh/ruff#8671]
line-length looks not work.
If the code is not very long, I don't think it's necessary to wrap a line.

**Comment by charliermarsh** [comment]
I think we'll need more information to be helpful here, such as examples of code before and after formatting.

One guess: you could consider disabling magic trailing comma support via [`skip-magic-trailing-comma`](https://docs.astral.sh/ruff/settings/#format-skip-magic-trailing-comma):

```toml
[tool.ruff.format]
skip-magic-trailing-comma = true
```
