### ISSUE TITLE
Add python binding / support input text

### ISSUE THREAD

**Issue by ArthurZucker** [astral-sh/ruff#8673]
Hey! 🤗 `transformers` core maintainer here, great work everyone! 🔥 

We are trying to switch from `black` to `ruff` for the formatter now! See this [PR](https://github.com/huggingface/transformers/pull/27144). 
I humbly have 2 feature requests! (This might be a bit selfish 😓 )
- having some python bindings: allowing us to do something like `from ruff import format; formatted_code = format(code)` 
- support directly passing text as an input to avoid having to write it to files. So `ruff format "Class Blob:\n...."

🤗

**Comment by Wauplin** [comment]
Adding also a use case for the [huggingface_hub](https://github.com/huggingface/huggingface_hub) repo. We generate some Python code automatically and need to format it once generated.

What we do [here](https://github.com/huggingface/huggingface_hub/blob/b054006d7582914df458a3e5595414a97f1aedeb/utils/check_static_imports.py#L82C1-L84C84) is to spawn a process to run ruff (using `ruff.__main__.find_ruff_bin`):

```py
        ruff_bin = find_ruff_bin()
        os.spawnv(os.P_WAIT, ruff_bin, ["ruff", "format", str(filepath), "--quiet"])
        os.spawnv(os.P_WAIT, ruff_bin, ["ruff", str(filepath), "--fix", "--quiet"])
```

A Python-binding would seem less hacky than this current solution :smile: (but totally understand if not a priority, I already love the work you've done on `ruff`!)

**Comment by Wauplin** [comment]
Thanks for the context and confirming that using `subprocess` is the good strategy here!
And sorry for the duplicate with https://github.com/astral-sh/ruff/issues/659, I guess we can close this one?

**Comment by ArthurZucker** [comment]
Yep thanks a lot for the tip, applying this to `transformers`! 🤗

**Comment by akx** [comment]
If it helps, I wrote a more full-fledged "format this bit" example for just the same usecase in https://github.com/astral-sh/ruff/issues/8401#issuecomment-1788806462
