### ISSUE TITLE
Add suggestion or fix for FA102 (future-required-type-annotation)

### ISSUE THREAD

**Issue by RunDevelopment** [astral-sh/ruff#8682]
The rule [FA102](https://docs.astral.sh/ruff/rules/future-required-type-annotation/) (future-required-type-annotation) is very useful when writing code in a code base that support python <3.10. The only issue with this rule is that it only *tells* you that a `from __future__ import annotations` is required, it doesn't have any way of applying the suggested fix.

Please add a suggestion or fix for this rule to automatically add the missing `from __future__ import annotations`.

**Code example:**
```py
# py 3.8 code base
def foo(l: list[int]): ...
```

**Comment by charliermarsh** [comment]
One way to achieve this is via [`missing-required-import`](https://docs.astral.sh/ruff/rules/missing-required-import/) (`I002`) -- you can mark `from __future__ import annotations`, and it'll be added to all non-empty files (see: https://docs.astral.sh/ruff/settings/#isort-required-imports):

```pyproject
[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
```

**Comment by charliermarsh** [comment]
I will fix this :)

**Comment by RunDevelopment** [comment]
Thanky you @charliermarsh!
