### ISSUE TITLE
import grouping/formating doesn't work like isort

### ISSUE THREAD

**Issue by ArazHeydarov** [astral-sh/ruff#8684]
I want to use ruff as my primary format tool. Even though it fixes some other issues like, unused imports, single quotes and etc. it seems it has no effect on grouping imports.

Ruff version: 0.1.5
Tool: Mac-terminal

There are no settings for isort or ruff

Python file:
```Python
from local_file import local_module
import os
print(os)
print(local_module)
```

Command(tried both):
```console
ruff format <path_to_file>
ruff --fix <path_to_file>
```

Result:
No change

Isort command:
```console
isort <path_to_file>
```

Expected and isort result:
```Python
import os

from local_file import local_module

print(os)
print(local_module)
```

**Comment by charliermarsh** [comment]
Import sorting isn't part of the default rule set, so it's not enabled by default. You can turn it on by enabling the `I` rules -- so, e.g., if you use a `ruff.toml` in your project:

```toml
[lint]
extend-select = ["I"]
```

With that, `ruff check --fix` should group and sort imports.

**Comment by ArazHeydarov** [comment]
Thank you for your quick response. It works now.
