### ISSUE TITLE
`INP001`: Skip scripts, for example Python files with shebang

### ISSUE THREAD

**Issue by sanmai-NL** [astral-sh/ruff#8690]
A Python _script_ isn't meant to be imported as a package, and so INP001 is not applicable.

![image](https://github.com/astral-sh/ruff/assets/3374183/d6289230-e5b8-4b5d-8994-55191dafd36c)

There are multiple criteria that each imply a file is a script, in particular in combination:

- It contains a shebang (not necessary but sufficient).
- It's outside the `src` directory (only necessary and sufficient if you stick to the [src-layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout), perhaps).

ruff 0.1.5.

**Comment by sanmai-NL** [comment]
Work-around for `src/` criterion in `pyproject.toml`.

```toml
[tool.ruff.per-file-ignores]
"[!s][!r][!c]*/**" = ["INP001"]
```

**Comment by charliermarsh** [comment]
I thought (2) was already respected to some degree -- we skip files that are direct children of the project root, and of any of the declared `src` directories. This tends to catch most scripts. I'm wondering if declaring your `.gitlab-ci` directory as a source root would solve the problem here?

**Comment by sanmai-NL** [comment]
Do you mean skipped when traversing a root target directory? A CI tool/Git hook may specify a path explicitly.

**Comment by charliermarsh** [comment]
I mean if you have a source set, like:
```toml
[tool.ruff]
src = ["src", ".gitlab-ci"]
```
Then any files that are direct children of those directories get skipped.

**Comment by charliermarsh** [comment]
We could ignore files with shebangs though.
