### ISSUE TITLE
UP032 does not cleanup escaped format placeholders in string continuations

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#8694]
Original code:
```python
query = ('type != {} OR '
         "data::text = '{{}}'"
         .format(my_type))
```

```
$ ruff --isolated --select UP032 --preview rufftest/ruff_sample.py
rufftest/ruff_sample.py:1:10: UP032 [*] Use f-string instead of `format` call

$ ruff --isolated --select UP032 --preview rufftest/ruff_sample.py --fix
Found 1 error (1 fixed, 0 remaining).
```

"Fixed" code:
```python
query = (f'type != {my_type} OR '
         "data::text = '{{}}'"
         )
```

Weird whitespace aside, the second string now contains a literal `{{}}` instead of the previous `{}` after formatting.

Any escaped `{{}}` format placeholders in string parts not converted to an f-string should be replaced with their unescaped version `{}`

**Comment by Skylion007** [comment]
We just realized we hit the same bug in PyTorch with ruff a while back when we updated.

**Comment by charliermarsh** [comment]
I thought this was filed before and fixed — will look into it!

**Comment by zanieb** [comment]
Here's a failing test case https://github.com/astral-sh/ruff/pull/8697
