### ISSUE TITLE
F821 false positive for IPython display()

### ISSUE THREAD

**Issue by guyrosin** [astral-sh/ruff#8702]
F821 (undefined-name) gives an "Undefined name `display`" when IPython's [display()](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display) method is used in jupyter notebooks, although this method is automatically made available without import ([reference](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display)).

See related issue in https://github.com/microsoft/vscode-jupyter/issues/8539

<img width="325" alt="image" src="https://github.com/astral-sh/ruff/assets/1250162/cb91ec35-7c4d-46fc-8549-43014d6ddf28">

Ruff version: 0.1.5

**Comment by charliermarsh** [comment]
Is there any consolidated documentation on the builtins that are exposed in Jupyter?

**Comment by guyrosin** [comment]
Not that I know of... I think they are just display() and magic commands
