### ISSUE TITLE
Change PT015 to trigger only on tests

### ISSUE THREAD

**Issue by NeilGirdhar** [astral-sh/ruff#8703]
[PT015](https://docs.astral.sh/ruff/rules/pytest-assert-always-false/) recommends using `pytest.fail`, which makes perfect sense inside a test.  But why is it triggering in ordinary code?

**Comment by charliermarsh** [comment]
This may be an ignorant question, but how can we determine whether something is a test or not in the context of pytest? Aren't pytest tests just ordinary, arbitrary functions?

**Comment by NeilGirdhar** [comment]
> Aren't pytest tests just ordinary, arbitrary functions?

Here's the [test discovery from the docs](https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#conventions-for-python-test-discovery).

I'm not sure how careful you want this test to be, but it could be ignored in functions that do not have the `test` prefix or suffix.  What do you think?

**Comment by dhruvmanila** [comment]
Closing this in favor of #8794
