### ISSUE TITLE
(🐞) is `bad-dunder-method-name` called `bad-dunder-name`?

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#8731]
```py
class A:
    def __among_us__(self):  # PLW3201: Bad or misspelled dunder method name `__among_us__`. (bad-dunder-name)
        ...
```
but in the docs it's called `bad-dunder-method-name`
https://docs.astral.sh/ruff/rules/bad-dunder-method-name/

**Comment by charliermarsh** [comment]
We use `bad-dunder-method-name` and I believe it's intentional -- I think Pylint uses `bad-dunder-name`, but we made the name more specific.

**Comment by charliermarsh** [comment]
Ohh I didn't realize we were including this in the rule message. Yes, that's a bug, thanks!
