### ISSUE TITLE
Formatter undocumented deviation: Trailing comma added after kwargs

### ISSUE THREAD

**Issue by henribru** [astral-sh/ruff#8748]
[Black:](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADhAGNdAD2IimZxl1N_WlbvK5V9KEd00teEET9osIZigniJF5fr_T7GfCbcGUBQhUU3aA1epEd495EVTT5WLbOM4upLfhfjwWg9Cp0Mh8h9sbfEEDGcq8Z-myt2zvNgeXO5vo1Vmkx7AAAAoJ0uR6yEDA8AAX_iAQAAABOYidOxxGf7AgAAAAAEWVo=)
```
def foo(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    b,
    **kwargs
):
    ...
```

[Ruff:](https://play.ruff.rs/1e68e379-2427-44ae-ace8-53bd5a937b45?secondary=Format)
```
def foo(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    b,
    **kwargs,
):
    ...
```

Not sure if this is somehow related to https://github.com/astral-sh/ruff/blob/main/docs/formatter/black.md#trailing-commas-are-inserted-when-expanding-a-function-definition-with-a-single-argument, but there's more than one argument here at least.

**Comment by charliermarsh** [comment]
I believe this is intentional as we view Black's behavior here as inconsistent, but it should be documented.

**Comment by charliermarsh** [comment]
I'm actually unable to reproduce this with the Black executable, only in the playground under certain circumstances (e.g., see [here](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFfAG9dAD2IimZxl1N_WlbvK5V9KEd00teEET9osIZigniJF5fr_T7GfCbcGUBQhUU3aA1epE1XHBGrTi7yEbaaNnAWgzoeI31q1coFWupDVR4mT6KoJs0brDOpVkjAfO4WtqJ8JpfwvuPoOVZqyN70iB9QAAAAYOgxoiNok58AAYsB4AIAACCMuV-xxGf7AgAAAAAEWVo=)). Is this something you experienced in one of your projects?

**Comment by henribru** [comment]
> I'm actually unable to reproduce this with the Black executable, only in the playground under certain circumstances (e.g., see [here](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFfAG9dAD2IimZxl1N_WlbvK5V9KEd00teEET9osIZigniJF5fr_T7GfCbcGUBQhUU3aA1epE1XHBGrTi7yEbaaNnAWgzoeI31q1coFWupDVR4mT6KoJs0brDOpVkjAfO4WtqJ8JpfwvuPoOVZqyN70iB9QAAAAYOgxoiNok58AAYsB4AIAACCMuV-xxGf7AgAAAAAEWVo=)). Is this something you experienced in one of your projects?

I can reproduce my example with the executable. It also reproduces if I duplicate the function. But your example shows something curious. It seems like if none of the functions have trailing comma on kwargs it doesn't get added, but if one of them has it it gets added for all of them? 🤔

**Comment by henribru** [comment]
Ahh, I see what's going on. Trailing comma on kwargs is a syntax error before Python 3.6. If you have a trailing comma already, without a specified target version, Black is inferring the code must be >=3.6, so it adds it to the rest as well. Since Ruff doesn't infer the target version (and in any case has 3.7 as the minimum), this doesn't apply to Ruff. My bad!

**Comment by henribru** [comment]
Though maybe a quick note in the documentation about how if you're relying on Black inferring the target version you might see differences when migrating to Ruff could be useful

**Comment by charliermarsh** [comment]
Ahh that explains a lot! Thank you for the follow-up.
