### ISSUE TITLE
__main__ is considered third party by isort

### ISSUE THREAD

**Issue by Numerlor** [astral-sh/ruff#8750]
```py
import os

import __main__
import third_party

import first_party

os.a
third_party.a
__main__.a
first_party.a
```
formatting the four imports results in the above order instead of
```py
import os

import third_party

import __main__
import first_party
```

https://play.ruff.rs/e1e21a3a-5567-4c46-9f6d-5ef508551206

**Comment by charliermarsh** [comment]
It seems that `isort` does the same, but I guess that's also a bug?

**Comment by Ezrashaw** [comment]
I'd like to work on this. I assume that `__main__` just has to be special-cased?

**Comment by charliermarsh** [comment]
That's right -- mostly likely in here: https://github.com/astral-sh/ruff/blob/e30635941140a3ad9418f3b940a8f5507ddb7f1a/crates/ruff_linter/src/rules/isort/categorize.rs#L68

**Comment by zanieb** [comment]
@Ezrashaw yep similar to how `known-first-party` works — @charliermarsh would have a more concrete recommendation if you need more guidance.
