### ISSUE TITLE
SIM300 tries to add a Yoda condition...

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#8759]
```python
class DummyHandler(RequestHandler):
    CONFIG = {'foo': 'bar'}


assert DummyHandler.CONFIG == {}
```

```diff
$ ruff --isolated --select SIM300 --preview rufftest/ruff_sample.py --diff
--- rufftest/ruff_sample.py
+++ rufftest/ruff_sample.py
@@ -2,4 +2,4 @@
     CONFIG = {'foo': 'bar'}


-assert DummyHandler.CONFIG == {}
+assert {} == DummyHandler.CONFIG

Would fix 1 error.
```

I guess it considers anything in *ALL UPPERCASE* a constant. But this is clearly too broad, and it also seems questionable whether `FOO == bar` would even be a Yoda condition to begin with.

At least from the rule description and example it's meant to detect obviously-weird stuff like `'literal' == variable`, ie having a literal value on the left side of a binary comparison operator.

My suggestion would be to remove the uppercase checks from `is_constant_like` altogether and just keep the check for literal expressions. Alternatively, any literal could be considered "more of constant" than an uppercase string and thus never be expected on the left side of a binary op.

**Comment by charliermarsh** [comment]
I think part of the problem here is that we don't consider `{}` to be a literal for the purpose of the rule, which seems wrong to me.

**Comment by charliermarsh** [comment]
I would suggest two improvements here...

1. We could consider dicts, lists, etc. to be literals for the purpose of the rule.
2. We should probably flag `assert 1 == DummyHandler.CONFIG`, which we don't today -- we consider both of those expressions to be equally "constant".

**Comment by charliermarsh** [comment]
I think this is the same as https://github.com/astral-sh/ruff/issues/6956.
