### ISSUE TITLE
False positive F821 (Undefined name) for NamedTuple

### ISSUE THREAD

**Issue by cbeytas** [astral-sh/ruff#8803]
ruff 0.1.6, Python 3.11

```python
import typing
User = typing.NamedTuple('User', **{'name': str, 'password': bytes})
User = typing.NamedTuple('User', name=str, password=bytes)
User = typing.NamedTuple('User', [('name', str), ('password', bytes)])
```
Those namedtuples should all be functionally equivalent. Why is F821 flagged on the first one?

```
ruff test.py --isolated
test.py:2:38: F821 Undefined name `name`
test.py:2:51: F821 Undefined name `password`
Found 2 errors.
```

**Comment by tmke8** [comment]
Worth noting maybe that the syntax used in the first two lines has been deprecated in Python 3.13:
> *Deprecated since version 3.13, will be removed in version 3.15:* The undocumented keyword argument syntax for creating NamedTuple classes (`NT = NamedTuple("NT", x=int)`) is deprecated, and will be disallowed in 3.15. Use the class-based syntax or the functional syntax instead.

https://docs.python.org/3.13/library/typing.html#typing.NamedTuple
