### ISSUE TITLE
UP034 misses unnecessary parenthesis

### ISSUE THREAD

**Issue by chbndrhnns** [astral-sh/ruff#8807]
```py
class C:
    def __init__(self, arg):
        ...

    @classmethod
    def from_env(cls):
        return cls(arg=("str"))
```

Run `ruff check --fix test.py` with such config:

```
[tool.ruff]
select = ["UP"]
```

I expect ruff to remove the parenthesis around "str":

```py
class C:
    def __init__(self, arg):
        ...

    @classmethod
    def from_env(cls):
        return cls(arg=("str"))

```

**Comment by zanieb** [comment]
I don't think this is in scope for the upgrade rule as these parentheses were never necessary. Perhaps I misunderstand the intent of the rule though cc @charliermarsh

**Comment by Ezrashaw** [comment]
I'm not sure that any lint rule is relevant here. However, the ruff formatter doesn't remove those parentheses, whereas it does for:
```python
def fun():
	return (1 + 1)
```
It seems that the formatter doesn't format function call arguments correctly.

**Comment by zanieb** [comment]
We could consider a separate rule for removing superfluous parentheses.

**Comment by charliermarsh** [comment]
I think that the last time this came up, we said we'd treat it as a request to implement Pylint's C0325: https://github.com/astral-sh/ruff/issues/2389. So let's do the same here.
