### ISSUE TITLE
Do not flag `PLR0124` for floats

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#8833]
`PLR0124` does usually indicate a bug, but one place where it's used in a lot of codebases is to check whether a float value is NaN as it will fail this test only if it's a NaN. As such, it would be good to not flag these comparisons if they are float or add a setting to ignore them for floats.

**Comment by dhruvmanila** [comment]
Can you expand a bit as I'm unable to follow? Do you mean that if `foo` is `float('nan')` then `foo == foo` will give `False` when it's a NaN and that's what the code is intended to check?

**Comment by Skylion007** [comment]
Exactly @dhruvmanila

**Comment by Skylion007** [comment]
Although I suppose `math.isnan` might be a more idiomatic way to check it.

**Comment by zanieb** [comment]
Yeah I don't think using `foo == foo` to detect NaN is something we want to encourage — we could add a case to `PLR0124` that suggests `math.isnan` or a new rule for that?

**Comment by charliermarsh** [comment]
I might settle for just a note in the documentation here as to how users should handle this specific case.
