### ISSUE TITLE
please add an option to enable black-like formatting of trailing comments

### ISSUE THREAD

**Issue by rpodgorny** [astral-sh/ruff#8836]
in the section of intentional deviations from black, this is mentioned:

Expressions with (non-pragma) trailing comments are split more often[#](https://docs.astral.sh/ruff/formatter/black/#expressions-with-non-pragma-trailing-comments-are-split-more-often)

please add a way to retain black behaviour. or at least for "task" (TODO, XXX, ...) comments.

our team usually tries to stick to short trailing comments but one big exception are TODO and FIXME comments which are used as kind of a "conversation" between the submitter and reviewer within the code itself. as such, they tend to be pretty long (containing explanations, questions, etc.) and we are fine with that as they will be ironed out before the final merge.

ruff constantly reformatting this is kind of anoying for everyone involved and is often a reason to be reluctant to switch from black to ruff.

please consider an option to leave trailing comments (as long as they start within the line-lenght limit) untouched. that would be the best solution for us. the second best would be to make the formatter honor the "ignore-overlong-task-comments" for the formatter.

thank you.

**Comment by MichaReiser** [comment]
@rpodgorny I understand that moving comments is annoying and we try to minimise the cases where this is happening. 

However, the comment placement logic is one of the most complicated parts of the ruff formatter and supporting multiple placement logic would significantly increase complexity. That's why I prefer better understanding your use case and see if we can improve the comment placement overall. 

Could you share a specific example where adding / removing the TODO/FIXME comment changes formatting and how you're ideal formatting would look like?

**Comment by MichaReiser** [comment]
I'm closing this because it is out of scope for now. @rpodgorny feel free to re-open if you have a follow up question.

**Comment by rpodgorny** [comment]
i don't really know if i have enough privileges to reopen, but anyway - i can't provide exact code but i've created this example that should show our use case:

```
def func(args):
        code
        code code code

        # TODO: case 1 - the entire logic in following block needs rework becase such and such. now follows dozen lines of explanation of how such change is meant and how it should be implemented. individual lines do not really matter, the block as a while is commented here. this comment being split automatically to multiple lines is acceptable.
        block code code
        block code
        block code code code

        # this is some very long, possibly multi-line comment explaining what the following block does.
        code code code
        code
        code code
        code code  # TODO: case 2 - this line's performance is sub-optimal becase such and such. follows a very long explanation how it should be changed. the rest of the block is alright. it's just this line that's to be taken care of. splitting this comment to multiple lines is not acceptable. also, moving this comment to line above is not acceptable as it "lessens" the intent of being local only to this line. splitting and/or moving may be misinterpreted as having the meaning of "rest of block" or something...
        code
        code code code

        code
        code code
        code code code
        # TODO: case 3 - drop the rest of this because such and such. if case 2 gets reformatted, there could be confusion with this case.
        code code code
        code code
```

line wrapping in editor ensures all todo items are fully visible. the exact placement of comments carries meaning and any shuffling would be counter-productive.

...anyway, isn't this exactly what ignore-overlong-task-comments is meant for?
