### ISSUE TITLE
docstring code formatter: figure out how to handle line width

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/ruff#8855]
In #8811, the formatter grew the ability to format doctest code snippets in docstrings. In this initial implementation, it handles line width limits by resetting the column of the code snippet to the first column. It is [unclear whether this is the right behavior](https://github.com/astral-sh/ruff/pull/8811#discussion_r1401165926). This means that individual lines inside the docstring can exceed [line length limits imposed by the linter](https://github.com/BurntSushi/polars/actions/runs/7006619426/job/19058868021?pr=1), and it also just generally means that it is difficult to maintain a line length limit in the source code.

The benefit of the current behavior is that it prioritizes the presentation of the code snippet itself. So that when a documentation generator renders a code snippet, its presented line length will be correct with respect to the project's configured line limits.

The downside of the current behavior is that the source code itself can have long lines. (This would be quite annoying to me personally, perhaps enough to eclipse the benefit of the presentation having a correct line length.)

Here are a few options we can pursue:

1. We could leave the existing behavior as-is and provide no configuration.
2. We could add a new option, `docstring-code-line-width`, that lets one configure the line width of code snippets independent of the line width of the surrounding code.
3. We could add a new option, `docstring-code-preserve-line-width` that dynamically chooses the line width of a reformatted code snippet based on the column at which in starts within the source code and the globally configured line width.
4. Do (2) and (3).

Maybe there are other choices. Speaking for myself personally, if I were to use code snippet formatting, I would want option (3) because it preserves the line length limit correctly regardless of the indentation of the docstring. I'm not sure I would add option (2) at all.

**Comment by ofek** [comment]
I would also very much prefer option 3

**Comment by charliermarsh** [comment]
I don't know that I have a strong opinion on what the "right behavior" is, but I _would_ like to avoid adding an additional setting for this and instead make an opinionated decision between the two strategies -- which leads me to think we should just ship with what we have and react to user feedback if it comes in.

**Comment by stinodego** [comment]
There is definitely something to be said for the behavior you have implemented now. It will lead to the best experience for users browsing the docs when they have been built and published.

Though from a developer standpoint, I will probably end up having to add `# noqa: W505` to about 25%+ of our docstrings. That's a pretty bad developer experience. I don't want to disable the lint entirely as docstrings are the number 1 thing contributors are getting wrong.

I would like to at least have to option to enforce the resulting line length (in the file as opposed to the isolated example). This should probably be the default - it would also help users transition from other docstring formatters such as `blackdoc` to `ruff`.

**Comment by ofek** [comment]
Another thing we need to be cognizant of is that rendered documentation almost always has a restricted horizontal viewport. For example, I prefer my line with to be 120 however I know that no documentation framework will do that. Here are some examples on my very large monitor:

- Material for MkDocs: ~80 characters https://squidfunk.github.io/mkdocs-material/reference/math/#using-inline-block-syntax
- Docusaurus: ~110 characters https://docusaurus.io/docs/advanced/ssg#browseronly
- Sphinx (what CPython docs use): ~80 characters https://www.sphinx-doc.org/en/master/tutorial/describing-code.html#documenting-python-objects

After writing this out actually I changed my view a little bit and now I am quite confident that 3 should be the default behavior and 2 should be option so users can build for their particular theme.

**Comment by BurntSushi** [comment]
> Do you know what rustfmt's experimental implementation of code-snipped formatting in the documentation does?

Good question. So rustfmt has two options here. [`format_code_in_doc_comments`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#format_code_in_doc_comments) to enable code example formatting, and [`doc_comment_code_block_width`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#doc_comment_code_block_width) to set a line width for it.

In terms of its behavior, it seems like it operates the same as what we have today but also provides option (2). In particular, I went through the issues on the topic:

* https://github.com/rust-lang/rustfmt/issues/3348
* https://github.com/rust-lang/rustfmt/issues/5359
* https://github.com/rust-lang/rustfmt/issues/5345

And the general sense that I got was that folks really wanted to be able to make code examples have a shorter line width than the surrounding code because the rendering _usually_ uses less horizontal space overall. This drives folks to use a bit more wrapping than they otherwise would.

It looks like `rustfmt` does not offer option (3), which is what I would want personally. :P

@charliermarsh It looks to me like it would be somewhat difficult to do this without introducing another option, although I'm not opposed to shipping the status quo and seeing what kind of feedback we get. The status quo has no option, but that can lead to longer lines than one would like in the rendered docs. Doing (3) also lets us avoid adding an option, but it could result in much more tightly wrapped documentation examples than folks would like.

**Comment by MichaReiser** [comment]
One challenge I see with a new `width` setting that sets the width for docstring examples is that it doesn't solve the potential conflict with E501, even when `indent-width` > `docstring-indent-width` because whether the example fits also depends on the indent level. 

The downside I see with option 3 is that the width for examples will be different depending on the indent level at which they were defined. This may lead to inconsistency when viewing the documentation. However, it seems to be the only option that plays nicely with E501.

**Comment by zanieb** [comment]
If we're particularly concerned about conflicts with E501 or W505, should we consider adding a setting or exception for docstring code to the _rule_  instead of complicating the formatter?

**Comment by zanieb** [comment]
I think in my ideal world, the code would by dynamically formatted to fit within my current line width depending on the indent of the block. While reading in an editor, the width would always be consistent. Later,  documentation tooling would format the code blocks again at the desired width for display e.g. on an API reference website.

**Comment by ofek** [comment]
> Later, documentation tooling would format the code blocks again

I don't know of any docs framework that does this. As far as I know they leave it as-is and if the line is too long the browser will automatically add a horizontal scrollbar.

**Comment by charliermarsh** [comment]
It sounds like most folks want to make (3) our default behavior (so, use the same line width as the rest of the formatter, and take into account the docstring indentation), with a setting (2) to let you set a line width for docstring code that would ignore the indentation depth of the docstring itself. I have no objection to that, it seems reasonable to me.

**Comment by charliermarsh** [comment]
Although, is anyone going to use this setting described in (2)? It doesn't seem like anyone in this thread would actually use it.

**Comment by ofek** [comment]
As I mentioned in my comment above, I would definitely use it because I prefer my line length to be 120 and my preferred documentation renders maximum ~80 characters and therefore I would set (2) to 80.

**Comment by zanieb** [comment]
> I don't know of any docs framework that does this.

We'll have to make one ;) although... this can be solved without a new tool if there's an option

> Although, is anyone going to use this setting described in (2)?

You could use this option and reformat the project when generating the documentation without committing the change.

It'd be nice to hear some more feedback requesting such a setting though.

**Comment by ofek** [comment]
To be clear, you're saying that when we build docs the recommendation is to have a separate config file just for that option and format the code in the CI using that config file, and then run the documentation generator?

**Comment by pawamoy** [comment]
Most of the time, I wouldn't mind that code examples in docstrings are formatted using the global line length, i.e. regardless of their base indentation, because docstrings are usually indented by 0, 1, or 2 levels, not more. 8 characters less is not a huge difference in size, at least when using a large line length such as 120. If the line length is configured to 80, then it can become quite small yes, and pose readability and rendering issues. This would especially be problematic for (draft) PEP 727 docstrings (parameter docstrings using `Annotated[..., Doc(...)]`, since their base indentation level can go up to 4:

```python
class Yo:
    def yo(
        param: Annotated[
            str,
            Doc(
                """
                doc
                """,
            ),
        ],
    ):
        ...
```

So in the end, I'd be more in favor of defaulting to a dynamic line length for code snippets in docstrings (configured line length + base indentation level), *as well as* allowing configuration of the line length for code snippets in docstrings, because as @ofek mentioned I think, while 120 is acceptable in the editor, SSGs will typically have a smaller rendering width like 80.

**Comment by charliermarsh** [comment]
> As I mentioned in my comment above, I would definitely use it because I prefer my line length to be 120 and my preferred documentation renders maximum ~80 characters and therefore I would set (2) to 80.

Just to be totally clear, when you set (2) to 80, would you expect that to be 80 characters from the start of the _line_, or 80 characters from the start of the docstring (i.e., exclusive of the indentation)?

**Comment by ofek** [comment]
80 characters from the start of the docstring

**Comment by zanieb** [comment]
> To be clear, you're saying that when we build docs the recommendation is to have a separate config file just for that option and format the code in the CI using that config file, and then run the documentation generator?

Well ideally we'd make it easier than creating a whole separate config file to override a single option (as described in https://github.com/astral-sh/ruff/issues/8368) but yes. This is more of a solution for people who have a documentation line width that _would_ cause conflict with their global line width e.g. they're the same number instead of 80 / 120.

**Comment by BurntSushi** [comment]
Bikeshed; what name should we use for the option to control line width in docstring code snippets? rustfmt uses [`doc_comment_code_block_width`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#doc_comment_code_block_width), which I think would translate to `docstring-code-block-width` for us. With that said, we already have a `line-length` configuration option, so "width" might be read as inconsistent there.

Some ideas:

* `docstring-code-block-length`
* `docstring-code-line-length`

There is also the other question as to what the _default_ value for this option should be. One thought is to make the default value `dynamic`, which makes its value a mixed type. Where `dynamic` means, "the line width is dynamically set so that the lines are wrapped in a way to respect the global line length setting."

**Comment by charliermarsh** [comment]
My vote would be for `docstring-code-line-length`. We had a lot of discussion about length vs. width when we released the formatter Beta, and opted to keep everything as `-length` for now to avoid a bunch of deprecations while keeping things internally consistent. (We do use width conceptually, and may rename eventually, but for now it's preferable to be consistent across settings at least.)

My guess would be that `docstring-code-line-length` defaults to `None`, and when `None`, it behaves dynamically, matching the global line length setting.

**Comment by ofek** [comment]
> My guess would be that docstring-code-line-length defaults to `None`, and when `None`

Do you mean a string `"None"`?

**Comment by charliermarsh** [comment]
I was suggesting that we use the absence of a value to represent the default, and internally it would be modeled as the null value. But I guess that doesn't allow overrides for projects that use `extends`, since TOML doesn't have a null value.

**Comment by BurntSushi** [comment]
Yeah I was going to say that relying on "absence" to represent a value usually winds up breaking down for $reasons, with overrides and what not being one of them. You usually want some way to explicitly set a particular type of configuration, even if we do permit its absence to default to it.

(I'm not opposed to a mixed type field, I just don't know enough about ruff's configuration yet to know whether that's both doable and desirable.)

**Comment by BurntSushi** [comment]
I also like `docstring-code-line-length` as a name.

**Comment by MichaReiser** [comment]
> We had a lot of discussion about length vs. width when we released the formatter Beta, and opted to keep everything as -length for now to avoid a bunch of deprecations while keeping things internally consistent. (We do use width conceptually, and may rename eventually, but for now it's preferable to be consistent across settings at least.)

I no longer see it as a priority to change from `length` to `width`, considering the bikeshedding that it introduces. I'm also fairly happy with our documentation, explaining the `length` well. I even considered renaming our internal variables to `length` to avoid the external/internal concept mismatch. 

> My guess would be that docstring-code-line-length defaults to None, and when None, it behaves dynamically, matching the global line length setting.

The global line length setting defaults to 88 and not `None`. Or do you mean that the absence of a value inherits the global line-length setting?


> Some ideas:

* `docstring-code-block-length`
* `docstring-code-line-length`

I slightly prefer `code-in-docstring-line-length` because of the `line-length` suffix, although `docstring-code-block-length` seems more correct. 

We decided to name the knob enabling docstring formatting `format-code-in-docstrings`, where `code` comes before `docstring`, opposed to the proposed options. This makes it harder to predict what the option names are without looking them up in the documentation. How about: `code-in-docstrings-line-length`. It's unfortunate that `format-code-in-docstrings` starts with `format`, because seeing all docstring options by simply typing `code-in` and waiting for intellisense won't work. 


> There is also the other question as to what the default value for this option should be. One thought is to make the default value dynamic, which makes its value a mixed type. Where dynamic means, "the line width is dynamically set so that the lines are wrapped in a way to respect the global line length setting."

Implementing `dynamic` could be interesting ;) You need a way to determine the current indent level, which probably requires upward traversal (which our AST doesn't support), tracking the nesting level somewhere in the context, or build a parent tree in the pre-traversal step (probably expensive).


Considering that `blackdoc` (and maybe others?) never exposed such option and I agree with Zanie, that documentation tooling ideally would reformat the code again. Is now the right time to add this option or could we default to `dynamic` and defer supporting two modes?

**Comment by BurntSushi** [comment]
> Implementing `dynamic` could be interesting ;) You need a way to determine the current indent level, which probably requires upward traversal (which our AST doesn't support), tracking the nesting level somewhere in the context, or build a parent tree in the pre-traversal step (probably expensive).

Yeah, I don't actually know precisely how to implement this. I probably naively assumed that I would "just" compute the indentation length of the minimum indent of the code block, subtract that from the configured global setting and use the result of that subtraction as the new global line width setting in the call to the formatter for the snippet. And of course, have some kind of reasonable fallback for cases where the new line width setting would be unreasonable small.

I haven't actually tried that, so I don't know if it works. If it doesn't work, and we do indeed need to do something like what you said, then that could be an issue.

> Considering that `blackdoc` (and maybe others?) never exposed such option and I agree with Zanie, that documentation tooling ideally would reformat the code again. 

I think the issue with putting the onus on the documentation tooling is that it does let folks strike a practical middle ground when this feature ships.

One of the key motivating factors for having `dynamic`, or at the very least, an option to set a fixed width, is to avoid tripping the long line length limit. With the status quo, folks with a long line length lint enabled will turn this on, format their code snippets, and very likely end up with a huge set of line length violations. They _could_ choose to suppress those lints for docstrings, but 1) this isn't a good UX and 2) docstrings tend to be an area where the line length lint gets tripped and is most useful. This is distilled from [existing feedback](https://github.com/astral-sh/ruff/issues/8855#issuecomment-1829334728) from @stinodego.

> Is now the right time to add this option or could we default to `dynamic` and defer supporting two modes?

I am slightly confused by this phrasing. The status quo today is not `dynamic`. It is a mode where the line length of reformatted code is unchanged, despite the fact that its first column may not be the actual first column in the source code.

To be clear, we could ship what we have today, as-is, with no new options. My _instinct_ is that it will immediately lead to a bunch of complaints that we can predict. I don't know for sure though. Maybe it's fine.

I think we need to at least provide a way to specify a fixed line width. It won't completely solve the user experience problem with violating line length limits, but it will probably let users heuristically avoid most issues. It also lets them set it to something small to motivate more wrapping in documentation without relying on their documentation tooling to do auto-reformatting itself.

**Comment by BurntSushi** [comment]
> I think we need to at least provide a way to specify a fixed line width.

So to be extra clear here, one possibility is that we add a docstring code snippet line length option, set to a fixed default value (probably just `88`) and have it always enabled. Then users could shrink that if they want it shorter. But nothing will happen automatically. It basically gives end users _some_ control, if not ideal control (IMO).

**Comment by MichaReiser** [comment]
> Yeah, I don't actually know precisely how to implement this. I probably naively assumed that I would "just" compute the indentation length of the minimum indent of the code block,

I don't think we can rely on the source text for this, because the source text may not be correctly indented. 

> One of the key motivating factors for having dynamic

From what I understand is that `dynamic` is what `blackdoc` implements today. That's why I considered only shipping `dynamic` for now.

**Comment by BurntSushi** [comment]
> (although adding a setting is probably easier than implementing dynamic, at least when we ignore naming)

Yeah exactly, `dynamic` _may_ be tricky to implement correctly. 

> I don't think we can rely on the source text for this, because the source text may not be correctly indented.

Right, I think I see now. I was only thinking about the contents of the docstring, but the indentation of the _docstring itself_ might not be correct in the source. Is that what you mean? If so, yeah I'm not sure exactly how to implement `dynamic` in simple way.

I'll investigate what `blackened` and `blackdoc` do today. I had thought they did what is currently implemented, but now I can't seem to remember precisely and it looks like I may not have written it down. AIUI, `blackened` is the more popular tool.

As for naming, I'm still note a huge fan of adding "block" in there. It feels a little redundant and more verbose? I'm not strongly opposed though. If everyone likes that naming, then I'm totally cool with it.

**Comment by BurntSushi** [comment]
I am not fully comfortable shipping with `same-as-global` because of the UX concerns raised in prior comments. But I think I would be comfortable shipping with _only_ `{integer}`, assuming we're open to making it a mixed type field in the future to possibly support `dynamic`.

Note that it may be the case that we just never need to provide a `same-as-global` setting. If we have `{integer}`, then users can always just configure both the line length and the docstring line length settings to be the same value. Slightly more work for the end user, but probably clearer semantics. And in the default configuration, it's indistinguishable from `same-as-global`.
