### ISSUE TITLE
docstring code formatter: add support for Markdown Python code snippets

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/ruff#8860]
The initial implementation of the docstring code snippet formatter in #8811 only reformats doctest code snippets. This issue tracks the work for making it also reformat Markdown Python code snippets. Work should probably proceed by adding a new `CodeExampleKind`:

https://github.com/astral-sh/ruff/blob/d9845a2628d25cba3fa21bb53ad78ad377128aa2/crates/ruff_python_formatter/src/expression/string.rs#L1373-L1385

**Comment by ofek** [comment]
I am especially looking forward to this as my code snippets render as documentation and are almost exclusively written as Markdown Python code blocks.

**Comment by BurntSushi** [comment]
@ofek Do you have any example code I could take a look at that uses Markdown blocks?

**Comment by konstin** [comment]
Another example, with mixed non-python and python blocks: https://github.com/sacdallago/bio_embeddings/blob/efb9801f0de9b9d51d19b741088763a7d2d0c3a2/bio_embeddings/embed/bepler_embedder.py#L1-L38. i think it makes sense to assume blocks are python just like rustdoc defaults to code blocks being python, but we should skip blocks with an explicitly different language

**Comment by BurntSushi** [comment]
I think it makes sense to _assume_ unmarked blocks are Python code. As @konstin said, this is what `rustdoc` does and it works great. The mitigation here is that if the blocks are not valid Python code, then we can leave them as-is untouched.

**Comment by ofek** [comment]
I understand what you both are saying but I'm saying that model does not work for Python because historically we do not use Markdown and have no such concept of embedded documentation that is rendered in a standard way. If you do what you say here you're going to immediately fail on the vast majority of code blocks, because most are not Python, because we do not do that.

**Comment by zanieb** [comment]
Here are some additional examples from a real project

- https://github.com/PrefectHQ/prefect/blob/bbaa0208d476240da1ac370d2735c4af41c304f0/src/prefect/utilities/annotations.py#L81-L89 (no annotation, python)
- https://github.com/PrefectHQ/prefect/blob/bbaa0208d476240da1ac370d2735c4af41c304f0/src/prefect/blocks/kubernetes.py#L38-L42 (`python` annotation)
- https://github.com/PrefectHQ/prefect/blob/bbaa0208d476240da1ac370d2735c4af41c304f0/src/prefect/settings.py#L160-L163 (`python` annotation)
- https://github.com/PrefectHQ/prefect/blob/bbaa0208d476240da1ac370d2735c4af41c304f0/src/prefect/utilities/templating.py#L180-L186 (no annotation, json)
- https://github.com/PrefectHQ/prefect/blob/bbaa0208d476240da1ac370d2735c4af41c304f0/src/prefect/workers/process.py#L10-L12 (`bash` annotation)
