### ISSUE TITLE
please allow boolean positional arguments (`FBT001`, `FBT002`) in case of `@override`

### ISSUE THREAD

**Issue by ZeeD** [astral-sh/ruff#8867]
While generally useful, the rules `FBT001` and `FBT002` may trigger errors if applied to an ovverriden method.

In my case I'm extending a class from a 3rd part library, and I need to override some methods with "naked booleans".

I got the FBT00? errors by ruff in my code, but if I fix them, the original class doesn't work anymore because there are calls to the methods passing the booleans positionally, and they are out of my control.

**Comment by Avasam** [comment]
Same reasoning as #3910 and #6958

**Comment by charliermarsh** [comment]
Makes sense.

**Comment by ZeeD** [comment]
Thanks!
