### ISSUE TITLE
ruff formatting not working if `match` statements exists anywhere (vscode; vscode extension; ipynb)

### ISSUE THREAD

**Issue by JulianCologne** [astral-sh/ruff#8870]
# Problem

ruff formatting does nothing in a vscode notebook (`.ipunb`) for specific code statements.
Seems to be related to `match/case` statements

# Example

![image](https://github.com/astral-sh/ruff/assets/25177421/56bfc147-090b-48b1-ba51-654a91a13fd7)

The command `Ruff: Format document` does NOTHING with this setup.
Once I comment out the `match` cell it will again format everything correctly.

![image](https://github.com/astral-sh/ruff/assets/25177421/486a95d8-bef6-4bbf-8705-ff6e22380f24)

code (NOTE: this works in a python file but not in ipynb files): 
```python
x = ['a'   ,     'b', 'c'      ,]

text = input()

match text:
    case 'hello': print('HI')
    case 'world': print('hey')
    case other: print(other)

x2 = ['a'   ,     'b', 'c'      ,]

```

# Version
vscode Ruff extension `v2023.50.0`

**Comment by zanieb** [comment]
Thanks for the report cc @dhruvmanila

**Comment by dhruvmanila** [comment]
Thanks, looking into it now...

**Comment by dhruvmanila** [comment]
Ok, found the issue, pushing a fix for it. Thanks again for highlighting this!
