### ISSUE TITLE
`# fmt: skip` should have comments after the `skip` keyword

### ISSUE THREAD

**Issue by georgettica** [astral-sh/ruff#8874]
`# fmt: skip` should have a comment section to allow developers to explain why they don't want to format

my motives are to allow partial grouping of array inputs.

data that was requested:
---

python file:
```
commands_to_run = [
    "./command.sh",
    "-n", "5",
    "-v",
]  # fmt: skip - reason for skipping 
```

command:
```
ruff format --isolated <file.py>
```

output:
```
list_of_items = [
    "./command.sh",
    "-n",
    "5",
    "-v",
]  # fmt: skip - reason for skipping 
```

```
$ ruff --version
ruff 0.1.6
```

**Comment by MichaReiser** [comment]
Related to https://github.com/astral-sh/ruff/issues/8892
