### ISSUE TITLE
New rule: Prefer in-place operators

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#8877]
I don't think any linter currently checks for this, although I did open a feature request in those I knew of where this feature might be in scope (https://github.com/MartinThoma/flake8-simplify/issues/188 and https://github.com/dosisod/refurb/issues/310). Whether they accept it, (and who knows when it would be implemented), this is still a check I'd like to see in Ruff as I don't directly use those other linters and autofixing should be possible. If you think this is a viable rule.

In-place operators lead to more concise code that is still readable. I'm not sure if there's any objective drawbacks (like a common pitfall for certain types). And performance-wise my understanding is that it should be faster (due to the in-place nature) or equivalent (thanks to Python duck-typing that will fallback to  `__add__` if `__iadd__` is not implemented).

Any of the following:
```python
some_string = (
  some_string
  + "a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long end of string"
)
index = index - 1
a_list = a_list + ["to concat"]
some_set = some_set | {"to concat"}
to_multiply = to_multiply * 5
to_divide = to_divide / 5
to_cube = to_cube ** 3
timeDiffSeconds = timeDiffSeconds % 60
flags = flags & 0x1
# etc.
```

Could be re-written as:
```python
some_string += "a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long end of string"
index -= 1
a_list += ["to concat"]
some_set |= {"to concat"}
to_multiply *= 5
to_divide /= 5
to_cube **= 3
timeDiffSeconds %= 60
flags &= 0x1
# etc.
```

**Comment by zanieb** [comment]
Makes sense to me, I'm surprised this does not exist already.

**Comment by Avasam** [comment]
I just thought of a special case with string interpolation that idk if should be included:
```python
# from
base_string = f"{base_string} end of string"`

# to
base_string += " end of string"`
```

**Comment by zanieb** [comment]
We could support that conditional on the ability to determine that the type of `base_value` is `str`.

**Comment by dhruvmanila** [comment]
We could first implement the simple cases of `var = var <operator> <expr>`. I think this could go into the `RUF` category. If anyone's interested, I'd be happy to give a look at the implementation.

**Comment by tdulcet** [comment]
Maybe this should be a separate rule, but there might be an opportunity for some more micro optimizations here. For example, if it were faster, these:
```py
a_list += ["to concat"]
a_list += ["to concat 1", "to concat 2"]
some_set |= {"to concat"}
some_set |= {"to concat 1", "to concat 2"}
# ect.
```
could potenchally be further rewritten as:
```py
a_list.append("to concat")
a_list.extend(("to concat 1", "to concat 2"))
some_set.add("to concat")
some_set.update(("to concat 1", "to concat 2"))
# ect.
```

**Comment by lshi18** [comment]
Hello, I would like to contribute to this issue if it hasn't been taken yet.

**Comment by lshi18** [comment]
Hi, I've made an attempt implementing this rule. Please help to have a review and let me know your thoughts. Thanks.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/9932.
