### ISSUE TITLE
Unsafe fix for `ANN2XX` is too unsafe

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#8879]
```
def do_thing(thing: Thing | None):
    if not thing:
        return None
    return { 'foo': 1 }
```
The (unsafe) autofix adds ` -> None` as the return type. I know this is under "unsafe" fixes, but this should be easy enough to avoid. https://github.com/JelleZijlstra/autotyping handles this case, so maybe that logic can be reused.

**Comment by zanieb** [comment]
```python
Thing = dict


def do_thing(thing: Thing | None):
    if not thing:
        return None
    return {"foo": 1}
```
```
❯ ruff check example.py --select ANN
example.py:4:5: ANN201 Missing return type annotation for public function `do_thing`
Found 1 error.
```
```
❯ ruff version
ruff 0.1.6 (f460f9c5c 2023-11-17)
```

I don't get a suggested fix for this example. Could you provide more reproduction details?

**Comment by charliermarsh** [comment]
I can reproduce this with preview enabled -- I think it's just a bug.

**Comment by charliermarsh** [comment]
Huh, I can reproduce this in the playground but not locally.

**Comment by charliermarsh** [comment]
Oh, you need to have the target Python version set to >= 3.10. Okay. I'm on it.
