### ISSUE TITLE
Feature request: PLW1514 autofix

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#8883]
Can an autofix be created for the preview rule `PLW1514` ? Even if it's "unsafe". Updating hundreds of instances manually is quite tedious.

In Python 3.10+ this would autofix to `encoding="locale"`, in Python <=3.9 this would autofix to `encoding=locale.getpreferredencoding(False)` (see: https://peps.python.org/pep-0597/). Search & replacing those if I want a specific encoding is easier. An option to specify prefered encoding can also be set (which could even be re-used by a new rule that ensures consistent encoding is used with desired value, like `"utf-8"`)

**Comment by qdegraaf** [comment]
While I'm working on the general utility mentioned in https://github.com/astral-sh/ruff/pull/8928#discussion_r1411171679, if anyone wants to do the autofix separately in the meantime, feel free to jump in.
