### ISSUE TITLE
Formatter: `wrap_multiple_context_managers_in_parens` preview style

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#8889]
Implement Black's [`wrap_multiple_context_managers_in_parens`](https://github.com/psf/black/pull/3489) as a preview style. The new style only applies to Py39+. 

```python
with \
     make_context_manager1() as cm1, \
     make_context_manager2() as cm2, \
     make_context_manager3() as cm3, \
     make_context_manager4() as cm4 \
:
    pass
```

Gets formatted as

```python
with (
    make_context_manager1() as cm1,
    make_context_manager2() as cm2,
    make_context_manager3() as cm3,
    make_context_manager4() as cm4,
):
    pass
```

Black automatically detects the python version used in a file based on the syntax used. E.g. a file using match statements is Py310+. I'm unsure if we should autodetect the python version based on the syntax or rely on `requires-python`

**Comment by charliermarsh** [comment]
> I'm unsure if we should autodetect the python version based on the syntax or rely on `requires-python`.

I would prefer to stick to our existing configuration semantics, and not introduce any autodetection.
