### ISSUE TITLE
Formatter: `parenthesize_long_type_hints` preview style

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#8894]
Implement Black's [`parenthesize_long_type_hints`](https://github.com/psf/black/pull/3899) as a preview style in Ruff. 

```python
def foo(
    i: int,
    x: Loooooooooooooooooooooooong
    | Looooooooooooooooong
    | Looooooooooooooooooooong
    | Looooooong,
    *,
    s: str,
) -> None:
    pass

# Formats now to 

def foo(
    i: int,
    x: (
        Loooooooooooooooooooooooong
        | Looooooooooooooooong
        | Looooooooooooooooooooong
        | Looooooong
    ),
    *,
    s: str,
) -> None:
    pass

```

This seems to be similar to what Ruff used to have but we reverted in https://github.com/astral-sh/ruff/pull/8233. We should investigate why Black isn't breaking the list on the left for 

```python
tags: List[str] = [],  # noqa: B006 - ignored by automatic migration, but should be fixed
``` 

Which people found ugly. Maybe it's because of https://github.com/astral-sh/ruff/issues/6975?

**Comment by jakkdl** [comment]
heya, author of the PRs that added the feature in black. Lemme know if you encounter anything weird or wonder something about my implementation choices.

**Comment by MichaReiser** [comment]
We've implemented the changes for parenthesizing type hints in annotated assignments but are holding off on implementing the proposed layout for type hints in parameters. See https://github.com/psf/black/issues/4123 for the rational.
