### ISSUE TITLE
Fails to parse type aliases after semicolon

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#8899]
```python
type One = int; type Another = str
```

Ruff fails to parse `Another`. Probably because the `SoftKeywordTokenizer` doesn't expect the contextual keyword `type` at that position.

This prevents us from importing Black's `type_aliases` test case.

**Comment by zanieb** [comment]
Depending on the urgency, I can try to take a look at this one.

**Comment by MichaReiser** [comment]
I don't think its super urgent. I'm ignoring that black test for now.

**Comment by charliermarsh** [comment]
(Coordinated with @zanieb, I'm gonna take this and the related parser error.)
