### ISSUE TITLE
Feature request: FKA100 (Flake8 force keyword arguments)

### ISSUE THREAD

**Issue by sebastian-sz** [astral-sh/ruff#8907]
Would it be possible to add the Flake8's https://pypi.org/project/flake8-force-keyword-arguments/ rule?
Cheers!

**Comment by zanieb** [comment]
This is very similar to https://github.com/astral-sh/ruff/issues/8382 and was previously discussed at https://github.com/astral-sh/ruff/discussions/8137

**Comment by sebastian-sz** [comment]
@zanieb Thank you for pointing that out. Closing the issue in favor of mentioned links.
