### ISSUE TITLE
Incorrect range for `WithItem` node

### ISSUE THREAD

**Issue by LaBatata101** [astral-sh/ruff#8913]
Ruff version: v0.1.6

In the following code snippet
```python
with (a := b) as x: pass
```

The `WithItem` range is `6..17` which contains this part of the source code `a := b) as`, as you can see the left parenthesis and the `x` is missing from the range. The correct range would be `5..18`.

[Here is the AST](https://play.ruff.rs/f34cef2d-7ccc-410d-b90d-60ff655f6c60).

**Comment by charliermarsh** [comment]
Odd, I can take a look at this.
