### ISSUE TITLE
RFC: rule to warn on non-annotation usage of TYPE_CHECKING imports

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [astral-sh/ruff#8927]
related to https://github.com/python/mypy/issues/16587

it would be great to warn if a variable that is imported using `if TYPE_CHECKING:` was used outside of a type anotation

aka cast/isinstance checks, calls)

**Comment by flisboac** [comment]
As an additional flag/config, this would be very useful.

**Comment by charliermarsh** [comment]
Can you try out [`TCH004`](https://docs.astral.sh/ruff/rules/runtime-import-in-type-checking-block/)?

**Comment by charliermarsh** [comment]
It may be what you're looking for -- at least, that's the intent :)
