### ISSUE TITLE
feature request: allow PLR0913 in `@override`n methods

### ISSUE THREAD

**Issue by ZeeD** [astral-sh/ruff#8945]
Basically same scenario of #8867 - in case of `@override` there is nothing I can do to simplify the signature of the method, so please ignore [too-many-arguments (PLR0913)](https://docs.astral.sh/ruff/rules/too-many-arguments/) checks.

**Comment by g-as** [comment]
Same should apply to newly added `too-many-positional`/`PLR0917`?

**Comment by charliermarsh** [comment]
Yes, sorry, just an oversight. Fixed in https://github.com/astral-sh/ruff/pull/9000.
