### ISSUE TITLE
Include version number in release assets

### ISSUE THREAD

**Issue by tobbez** [astral-sh/ruff#8961]
The assets attached to [releases](https://github.com/astral-sh/ruff/releases) currently use the exact same archive names for every release.

Please consider including the version number in the archive name (for example, `ruff-0.1.6-aarch64-apple-darwin.tar.gz` instead of the current `ruff-aarch64-apple-darwin.tar.gz`), so it's possible to easily tell archives from different releases apart.

**Comment by MichaReiser** [comment]
I don't feel opinionated about whether the version numbers should be included in the release assets or not. Do you know of other tools that include the version numbers? Would you be interested in creating a PR that includes the version number in our release assets?

**Comment by tobbez** [comment]
No hard stats to back it up, but in my experience including the version number is the rule (both for source archives and binary archives). A few other tools that include version numbers (the first few that came to mind): [ripgrep](https://github.com/BurntSushi/ripgrep/releases), [hyperfine](https://github.com/sharkdp/hyperfine/releases), [fd](https://github.com/sharkdp/fd/releases).

I suppose I could have a go at updating the workflow to include version numbers in archive names.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/9002. Thank you!
