### ISSUE TITLE
Disable ANN201 None-autofix for abstractmethods?

### ISSUE THREAD

**Issue by twoertwein** [astral-sh/ruff#9004]
Abstract methods often have an almost empty body (doc-string, pass, or raise) but it seems unlikely that they should return `None`. https://github.com/JelleZijlstra/autotyping does not add `None` for `abstractmethod`s.
```py
import abc

class Test(abc.ABC):
    @abc.abstractmethod
    def test(self):  #ruff adds  -> None
        """sub-classes have to implement this"""
```
```sh
$ ruff --version
ruff 0.1.7
$ ruff --select ANN2 --exit-non-zero-on-fix --unsafe-fixes test.py 
Found 1 error (1 fixed, 0 remaining).
```

**Comment by charliermarsh** [comment]
Seems reasonable to me.

**Comment by twoertwein** [comment]
(and also not add None return types to pyi files)

**Comment by charliermarsh** [comment]
I guess I'm not sure if we should flag these at all for abstract methods with empty bodies. Probably not.

**Comment by charliermarsh** [comment]
Sorry, actually, we should flag.

**Comment by twoertwein** [comment]
> Sorry, actually, we should flag.

ANN201 should definitely report missing return annotations for abstract methods and in pyi files, but autofixing those two error cases based on the "non-existing" function body with `-> None` seems not helpful to me. As in the case of autotyping https://github.com/JelleZijlstra/autotyping/issues/33  it is still helpful to add `-> None` based on the name of the method, such as for `__init__` (even when it is abstract or in a pyi file).

I stumbled into these cases when trying to run ruff with the preview fixes on pandas.
