### ISSUE TITLE
Add ignore noqa support for doc lines

### ISSUE THREAD

**Issue by amrit110** [astral-sh/ruff#9008]
Hi, when I use ruff on docstring lines, and get errors such as `W505 Doc line too long`, adding a `# noqa: W505` at the end of the line doesn't seem to work. Could we please add support for that. I believe `flake8` supports it.

**Comment by FishAlchemist** [comment]
Thank you for taking the time to report an issue! We're glad to have you involved with Ruff.

If you're filing a bug report, please consider including the following information:

* A minimal code snippet that reproduces the bug.
* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.
* The current Ruff settings (any relevant sections from your `pyproject.toml`).
* The current Ruff version (`ruff --version`).

**Comment by charliermarsh** [comment]
@amrit110 -- For errors within multi-line strings, we require that the `# noqa` be placed _after_ the string. Otherwise, it ends up being included within the content of the string itself, which is generally not intended.

For example:

```python
"""Some docstring.

Pretend this line is too long.
"""  # noqa: W505
```

**Comment by charliermarsh** [comment]
(There's a note on this in docs [here](https://docs.astral.sh/ruff/linter/#error-suppression).)

**Comment by amrit110** [comment]
thanks @charliermarsh !
