### ISSUE TITLE
Autofix conflict between `PLR1736` and `FURB148`

### ISSUE THREAD

**Issue by danparizher** [astral-sh/ruff#9010]
The following autofix introduces a NameError when both `PLR1736` and `FURB148` are selected.

Before:
```py
letters = ["a", "b", "c"]

for index, letter in enumerate(letters):
    print(letters[index])
```
After:
```py
letters = ["a", "b", "c"]

for index in range(len(letters)):
    print(letter)
```
ruff 0.1.7

**Comment by charliermarsh** [comment]
👍 We need to ensure that these fixes conflict so that they don't overwrite one another.
