### ISSUE TITLE
RUF017 Avoid quadratic list summation: consider itertools.chain.from_iterable

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [astral-sh/ruff#9045]
currently `RUF017`

takes 
```python
mess = [[1], [1,2],[1], [1,2],[1], [1,2]]

tags = sorted(sum([x for x in mess], []))
```

and turns it into 
```python
import functools
import operator
mess = [[1], [1,2],[1], [1,2],[1], [1,2]]

tags = sorted(functools.reduce(operator.iadd, [x for x in mess], []))
```

instead of the more idiomatic

```python
import itertools

mess = [[1], [1,2],[1], [1,2],[1], [1,2]]

tags = sorted(itertools.chain.from_iterable(mess))
```

based on the applications of the pattern i have seen so far, i would almost always recommend to replace
the sum with a `list(chain.from_iterable(...))`

with the additional "optimization" of in-lining list comprehensions and/or generator expressions when applicable

**Comment by charliermarsh** [comment]
This makes sense... We could at least do this for cases in which it's directly within a `sorted` or similar.

**Comment by charliermarsh** [comment]
Interestingly, though, the `functools.reduce` variant does seem to be quite a bit faster.

```python
import timeit

code1 = """
tags = sorted(itertools.chain.from_iterable(mess))
"""

code2 = """
tags = sorted(functools.reduce(operator.iadd, [x for x in mess], []))
"""

repeats = 10000

time1 = timeit.timeit(stmt=code1, setup='import itertools\nmess = [[i, i + 1] for i in range(10000)]', number=repeats)
print(f"{time1} seconds")

time2 = timeit.timeit(stmt=code2, setup='import itertools\nimport functools\nimport operator\nmess = [[i] for i in range(10000)]', number=repeats)
print(f"{time2} seconds")
```

Yields:

```
4.019917957950383 seconds
2.7585187909426168 seconds
```

**Comment by RonnyPfannschmidt** [comment]
I suspect this relates to different optimization levels of the Code paths

**Comment by hauntsaninja** [comment]
Here's some more benchmarking from when we added this: https://github.com/astral-sh/ruff/issues/5073#issuecomment-1591836349

**Comment by Skylion007** [comment]
This would be covered under a REFURB/FURB rule when we choose to implement it. https://github.com/astral-sh/ruff/issues/1348

**Comment by hauntsaninja** [comment]
I'd recommend closing this issue, since the functools variant is meaningfully faster: https://github.com/astral-sh/ruff/issues/5073#issuecomment-1591836349

**Comment by charliermarsh** [comment]
I agree.
