### ISSUE TITLE
Bad contrast for hyperlinks on note blocks in the webpage

### ISSUE THREAD

**Issue by MicaelJarniac** [astral-sh/ruff#9046]
![image](https://github.com/astral-sh/ruff/assets/19514231/4dba8220-b676-434d-bce1-77ed9aabb799)

https://docs.astral.sh/ruff/formatter/#ruff-format

**Comment by charliermarsh** [comment]
Thanks!

**Comment by zanieb** [comment]
Oh Dark mode.... :D
