### ISSUE TITLE
FURB152 has too many false positives

### ISSUE THREAD

**Issue by alanhdu** [astral-sh/ruff#9049]
FURB152 tries to replace hard-coded constants with the built-in constants (e.g. `3.1415` to `math.pi`). Unfortunately -- I have found it to be too false-positive happy -- e.g. it will correct `3.15` to `math.pi`.

At the very least, I'd argue that this should be an *unsafe* fix if the constant does not exactly match the builtin (since we will observe some behavioral difference). But I think we should *also* increase the precision required (e.g. https://github.com/astral-sh/ruff/blob/6bbabceead840e0d232950a1ed1e8f02cdafb92c/crates/ruff_linter/src/rules/refurb/rules/math_constant.rs#L61C29-L61C29) -- I don't have a strong opinion about how precise it should be, but IMO `3.15` should not be corrected to `math.pi` (maybe do it based on the # of digits vs the rounded version?).

Would be happy to contribute a patch if you think this a good idea.

**Comment by zanieb** [comment]
There was some discussion about safety at https://github.com/astral-sh/ruff/pull/8727#discussion_r1396381872 and we're a bit divided on it. I'd prefer to leave it as safe for now and instead reduce the false positives. Unsafe isn't really intended to account for false positives i.e. if the rule was always applied correctly would it be safe? If we still get feedback that it's causing problems, we can consider changing it. 

I agree 3.15 should definitely not change to `math.pi`. I'd welcome a pull request resolving that issue (and similar).
