### ISSUE TITLE
Autofix EM101

### ISSUE THREAD

**Issue by kunaltyagi** [astral-sh/ruff#9052]
EM101: Exception must not use a string literal, assign to variable first

This seems a simple enough to auto-fix given [the example](https://docs.astral.sh/ruff/rules/raw-string-in-exception/)

current
```py
    raise XYZ(<some-kind-of-string>)
```

autofix to:
```py
    msg = <some-kind-of-string>
    raise XYZ(msg)
```

1. if msg has been previously defined, we could still fail (with an unfixable message) (or try weird names for the variable like message, xyz_msg, xyz_message, error_msg, error_message, etc.)

Verified no autofix for:
* ruff: ruff 0.1.7
* python: 3.11
* nothing relevant to em101 in pyproject.toml (except selecting "EM")

**Comment by charliermarsh** [comment]
You may need to run with `--unsafe-fixes`?

**Comment by kunaltyagi** [comment]
I did use --unsafe-fixes but it still didn't fix

**Comment by kunaltyagi** [comment]
![image](https://github.com/astral-sh/ruff/assets/2657068/27641039-52c0-4bfc-8f70-f445e2a31721)

And I verified that I was using ruff 0.1.7

**Comment by kunaltyagi** [comment]
Only F401 is marked as unfixable

**Comment by charliermarsh** [comment]
Can you share a complete reproducible example? The rule is typically fixable, as you can see in the [playground](https://play.ruff.rs/408a1766-159f-4d16-ada0-dfaec37ca006).

**Comment by charliermarsh** [comment]
Yup!

<img width="642" alt="Screen Shot 2023-12-08 at 12 04 00 AM" src="https://github.com/astral-sh/ruff/assets/1309177/5e4cd0dc-c90d-4b31-86d3-774a72ede0d3">

<img width="766" alt="Screen Shot 2023-12-08 at 12 04 04 AM" src="https://github.com/astral-sh/ruff/assets/1309177/a92f01be-2e33-4c7a-9ab7-1cd35d38eae0">

<img width="269" alt="Screen Shot 2023-12-08 at 12 04 11 AM" src="https://github.com/astral-sh/ruff/assets/1309177/7c4a588e-762f-4f32-ba56-e941f59b8f8c">

**Comment by kunaltyagi** [comment]
I copied my own code instead of trying to re-create

![image](https://github.com/astral-sh/ruff/assets/2657068/b18c0503-2cb8-4a74-94c3-3b7aeccc9eba)


https://play.ruff.rs/70dcf7e0-23f6-40f4-95cf-670b6b713307

**Comment by kunaltyagi** [comment]
But that msg is used to raise an error earlier. It's not on any code-path that leads to this error

**Comment by kunaltyagi** [comment]
https://play.ruff.rs/1feffa3b-9314-481d-ace9-7a15c5c644e2

**Comment by dhruvmanila** [comment]
> If I tried accessing msg, I'd get a big fat error

You would be getting a runtime error in that case. This is a limitation of every static analysis tools - it's not possible to determine the path the code will take, _statically_.

**Comment by kunaltyagi** [comment]
Statically, it's possible to determine if:
1. There's a raise, or return right after the variable
2. The variable is in the literally different part of `if-elif-else`

**Comment by charliermarsh** [comment]
Correct but updating the semantic model to support control-flow analysis isn't a current priority. I would say we should just always offer this fix now that it's marked as unsafe anyway.
