### ISSUE TITLE
Can ruff support `flake8-private-name-import`

### ISSUE THREAD

**Issue by Tomperez98** [astral-sh/ruff#9062]
* ruff 0.1.2

[flake8-private-name-import](https://pypi.org/project/flake8-private-name-import/) prevents importing private modules. I'd say that ideally only the `__init__.py` script on the same level should be able to access those private modules, but it could be easily solved by adding in the `per-file-ignore` configuration

**Comment by Tomperez98** [comment]
https://github.com/astral-sh/ruff/discussions/9061

**Comment by tjkuson** [comment]
I think a rule similar to this is being tracked by the Pylint issue (#970) under `import-private-name` (`C2701`).

**Comment by charliermarsh** [comment]
Yeah let's consolidate in favor of the Pylint tracking issue. Thanks for filing :)
