### ISSUE TITLE
`check` and `format` do not respect the same rules

### ISSUE THREAD

**Issue by aaronmarkey** [astral-sh/ruff#9064]
I've a simple reproducible issue: Ruff's `check` and `format` commands do not respect the same configuration. 

In some directory the two following files:

```python
# example.py
if True is True and True is False and False is True and 1 == 2 and 2 == 9 and 4 == 7 and 5 == True:
    print(1)


'''asdf'''

'adf'

a = 'asdf'
```

```toml
# ruff.toml
line-length=80
```

I would expect running `ruff check example.py` to have a number of issues related to line length and quote type. However, running that returns `0`. But, running `ruff format example.py` results in the following file: 

```python
# example.py
if (
    True is True
    and True is False
    and False is True
    and 1 == 2
    and 2 == 9
    and 4 == 7
    and 5 == True
):
    print(1)


"""asdf"""

"adf"

a = "asdf"

```

So my issue: Is it expected that ruff's formatter and checker don't follow one another? If so, why are there shared configs for both at top level which both are documented as following if only the formatter follows them?

**Comment by aaronmarkey** [comment]
So in order to lint a project to it's fullest extent, I need to chain hundreds of `--select`s?

**Comment by zanieb** [comment]
@aaronmarkey You can select rules in your `pyproject.toml` file — it is very common for projects to choose a subset of the rules since we implement so many different plugins. You can also select `ALL` then ignore rules that you do not want, however we don't generally suggest that. We do not include rules that overlap with the formatter by default, so if you want to have formatter violations in `check` you will need to enable those until we implement #8232.

**Comment by aaronmarkey** [comment]
Is there a set of rules I can supply `lint.select` which will match whatever the `format` command uses?

**Comment by zanieb** [comment]
No, the `format` command is an entirely different implementation than the linter and it is not feasible to display line by line violations as done in the linter. The background in [the announcement blog post](https://astral.sh/blog/the-ruff-formatter) may be useful.

Perhaps https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules would be helpful if you want lint rules that overlap with formatting. As I said though, we'd highly recommend disabling formatting related lint rules and instead using `ruff format --check`.

**Comment by tylerlaprade** [comment]
@aaronmarkey, the linter and formatter serve entirely different purposes. Lint is for detecting possible bugs, while format is to standardize whitespace so humans don't have to think about it. I'm not sure which of those purposes you're seeking to achieve, but if you want to run a script that tells you if you have any formatting "violations" (things which would be automatically reformatted), then you can run `ruff format --check` or `ruff format --diff`.

**Comment by charliermarsh** [comment]
Gonna close based on the explanations above.

**Comment by Gatsby-Lee** [comment]
I understand the goal of the design, but inconvenience.
