### ISSUE TITLE
Ruff format always splits single positional-only argument list across two lines

### ISSUE THREAD

**Issue by drhagen** [astral-sh/ruff#9074]
Black [keeps this code as is](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADVAHpdAD2IimZxl1N_WlbvK5V_r8p8RWVQhH4T2O7WqUDeXrzfa-e6wziIBZ7QgnOLLS6AI8_u-ndkugsJo2YBSDMHN0D47vXymeQ1jtqapcY5xyV7JpggMWoOxoxwKgPXPN0A2MQwkZu3vmIU6QGNqrpOmboAPkPAchIEDU0AAAAAXBH-g4MbwnEAAZYB1gEAAEGE9zexxGf7AgAAAAAEWVo=):

```python
def some_function(
    string: str, /
) -> ReallyReallyReallyReallyReallyReallyReallyReallyLongName:
    pass
```

But Ruff 0.1.7 forces the argument list to be split across lines.

```python
def some_function(
    string: str,
    /,
) -> ReallyReallyReallyReallyReallyReallyReallyReallyLongName:
    pass
```

I would also consider Black's behavior to be more desirable here. This is a regression from Ruff 0.1.6. I suspect that this was caused by #8921, where it would be easy to think this function has one argument. Semantically, it does, while syntactically, it has two.

**Comment by charliermarsh** [comment]
Interesting, that makes sense... Thanks for reporting!

**Comment by charliermarsh** [comment]
Should be straightforward to fix. I appreciate you finding + linking back to the relevant PR.
