### ISSUE TITLE
Document that `ruff format` is in Beta

### ISSUE THREAD

**Issue by johnthagen** [astral-sh/ruff#9092]
The [recent blog post](https://astral.sh/blog/the-ruff-formatter) mentions 

> Ruff’s Python formatter, available now in Beta 

but the official docs, don't mention the beta fact:

- https://docs.astral.sh/ruff/formatter/

I think that it would be helpful to mention this in the docs as this is what most people will find and read rather than the original blog post, and it also gives a natural point for people to check to see when the formatter goes out of beta.

**Comment by charliermarsh** [comment]
I can add this, thanks!
