### ISSUE TITLE
`W505` can't be ignored

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#9096]
Hi, unless I messed up the syntax, it seems that `W505` violations can't be ignored with `noqa` when `max-doc-length` is set.

<img width="943" alt="image" src="https://github.com/astral-sh/ruff/assets/5475199/b3f951ac-a206-4f44-a1b5-c5241e4f4049">

**Comment by charliermarsh** [comment]
Is that within a multiline string? If so, you need to put the `# noqa` after the end of the multiline string, rather than _within_ it.

**Comment by tylerlaprade** [comment]
Ah, looks like it has to be at the end of the docstring
