### ISSUE TITLE
`ruff format --check` outputs "files left unchanged", which is slightly confusing

### ISSUE THREAD

**Issue by johnthagen** [astral-sh/ruff#9132]
This is pretty minor, but when you run:

```
$ ruff format --check .
401 files left unchanged
```

It's slightly confusing to me that it says "files left unchanged", since in `--check` mode, it will _never_ change any files. The first time I saw this, I thought I had accidentally forgotten to add the `--check` argument in a Nox session.

Would it be a small improvement if `ruff format` checked if it was in `--check` mode and changed the output to something like:

```
$ ruff format --check .
401 files checked successfully
```

```
$ ruff format --check .
Would reformat: main.py
1 file needs to be reformatted, 400 files checked successfully
```

Then again, maybe using the exact output from normal `ruff format` is better for consistency? No strong opinions from me, just an observation. Feel free to close if you disagree.

**Comment by zanieb** [comment]
This makes sense to me!

**Comment by charliermarsh** [comment]
Good call. Or "already formatted"? (Is that less clear?)

**Comment by johnthagen** [comment]
@charliermarsh I like "already formatted" as well!

**Comment by Cherrymelon** [comment]
in version 0.7.2,  type `ruff format ./dataset/api.py`  still return 1 file left unchanged,
I think it need be update also

**Comment by MichaReiser** [comment]
Looking at the PR, this seems intentional. See [this comment](https://github.com/astral-sh/ruff/pull/9153#discussion_r1428808967) although I'm not sure why. @charliermarsh do you remember?
