### ISSUE TITLE
v0.1.8 introduced breaking formatting changes to my `# noqa` pragma comment

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#9134]
This formatting was stable in v0.1.7:
```
def update_or_create_patients_and_sites_from_edc(instance: 'EdcPatientRecordObjectMixin'):  # noqa: C901,PLR0912 -- # ! Disabled for emergency bugfix.
```

Under v.0.1.8, it gets changed to:
```
def update_or_create_patients_and_sites_from_edc(
    instance: 'EdcPatientRecordObjectMixin',
):  # noqa: C901,PLR0912 -- # ! Disabled for emergency bugfix.
```

Instead, it should be:
```
def update_or_create_patients_and_sites_from_edc(  # noqa: C901,PLR0912 -- # ! Disabled for emergency bugfix.
    instance: 'EdcPatientRecordObjectMixin',
):
```

which is also stable for formatting, but keeps the `# noqa` on the correct line.
We used to have this problem all the time with Black, but so far Ruff has been much better in how it handles pragmas.

**Comment by charliermarsh** [comment]
What is your configured line length?

**Comment by tylerlaprade** [comment]
I haven't set one. Here are the possibly relevant parts of my config:
```
[format]
skip-magic-trailing-comma = true
quote-style = "single"
docstring-code-format = true

[pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 150
```

**Comment by charliermarsh** [comment]
At the default, it's correct to wrap the lines there, so I'm surprised that it wasn't wrapping at all in v0.1.7. Am I correct that you're saying the first snippet was unchanged in v0.1.7?

(I know the issue is about the comment.)

**Comment by tylerlaprade** [comment]
Yes, it was not reformatting in v0.1.7

**Comment by zanieb** [comment]
This reformats for me on v0.1.7

```
❯ ruff version
ruff 0.1.7 (8d9912a83 2023-12-04)
❯ ruff format --diff example.py
--- example.py
+++ example.py
@@ -1,2 +1,4 @@
-def update_or_create_patients_and_sites_from_edc(instance: 'EdcPatientRecordObjectMixin'):  # noqa: C901,PLR0912 -- # ! Disabled for emergency bugfix.
+def update_or_create_patients_and_sites_from_edc(
+    instance: "EdcPatientRecordObjectMixin",
+):  # noqa: C901,PLR0912 -- # ! Disabled for emergency bugfix.
     pass

1 file would be reformatted
```

**Comment by tylerlaprade** [comment]
Ah, I see what happened here - v0.1.8 added the quotes to the type annotation, which must have pushed it over the default line length

**Comment by charliermarsh** [comment]
I think this is not specific to a change in v0.1.8, and more a general issue with the pragma moving.
