### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by vectro** [astral-sh/ruff#9141]
A number of the documentation Markdown files contain a link to `settings.md`; but that file does not exist.

For example, the file `docs/configuration.md` contains this link:
```
For a complete enumeration of the available configuration options, see [_Settings_](settings.md).
```

**Comment by T-256** [comment]
`settings.md` is auto-generated and not exist on repo.
https://github.com/astral-sh/ruff/blob/6c224cec5202e1259340ef3af19c0fea62c6226e/scripts/generate_mkdocs.py#L116-L120

**Comment by charliermarsh** [comment]
This is intentional -- the docs are intended to be consumed via https://docs.astral.sh/ and not via the checked-in Markdown, which really represent source files.
