### ISSUE TITLE
[Panic] byte index 2 is not a char boundary

### ISSUE THREAD

**Issue by yuuuxt** [astral-sh/ruff#9145]
using `v2023.56.0` and `1.85.1` in win10.

Seems a line inside docstring that starts with a Chinese character would cause this. 

In jupyter notebook I create a function:

```python
def sample_func(xx):
    """
    转置 (transpose)
    """
    return xx.T

```

the error logs:

```
thread 'main' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\str\mod.rs:660:13:
byte index 2 is not a char boundary; it is inside '转' (bytes 0..3) of `转置`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MichaReiser** [comment]
What's the command you're running? Is it `ruff check` or `ruff format`?

**Comment by yuuuxt** [comment]
not running any command, it's like an auto-check (not manually triggering formatting), so I assume it's similar to running `ruff check`.
