### ISSUE TITLE
Undocumented formatter deviation - empty lines are removed from block beginning

### ISSUE THREAD

**Issue by jond01** [astral-sh/ruff#9170]
* A minimal code snippet that reproduces the bug:
Original `.py` file:
```py
def f():

    pass

```
Black - unchanged.

Ruff:
```py
def f():
    pass

```

The same happens with if statements, for loops, class declarations, etc.

* The command you invoked: `ruff format`.
* The current Ruff settings: nothing relevant.
* The current Ruff version: 0.1.8

More examples are here:
https://github.com/mlrun/mlrun/pull/4748
* https://github.com/mlrun/mlrun/pull/4748/files#diff-277e10f57c688505214127056ff0b8b38c04197562f1fff844ddbd7700e69ec7
* https://github.com/mlrun/mlrun/pull/4748/files#diff-eab0b5a3c6ae8610645aa6cd8e98d6ada4b71820a550b0ea8c10588f62f018ae
* https://github.com/mlrun/mlrun/pull/4748/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3

**Comment by charliermarsh** [comment]
Confirming that this is part of preview, so it's a case of https://github.com/astral-sh/ruff/issues/8893. Merging into that issue, thanks!
