### ISSUE TITLE
`FURB118` is incorrector for `operator.contains`. The operands are reversed!

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#9191]
There is a bug in the fixit for the FURB118
```python
f = lambda a, b: a in b
```
gets replaced with
```python
f = operator.contains
```
but this is NOT semantically equivalent. [Per the documentation](https://docs.python.org/3/library/operator.html#operator.contains), `operator.contains` is equivalent to `b in a` not `a in b`!
```python
f = lambda a, b: b in a
```
is actually equivalent to `operator.contains` not what is actually getting flagged (or fixed) by refurb.

This is appearing when trying to apply this fix with ruff master.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Fixing now :)
