### ISSUE TITLE
Autofix for ANN 201 incorrectly adds `None` Return Type

### ISSUE THREAD

**Issue by max-muoto** [astral-sh/ruff#9201]
Let's say we have a function that has no ability to return:

```python
def foo():
    raise ValueError
```

The correct return type for this would be [`NoReturn`](https://docs.python.org/3/library/typing.html#typing.NoReturn). However, the autofix for ANN 201, adds `None` here as the return type instead.

Ruff Version: `0.1.8`
Command: `ruff check . --fix --unsafe-fixes`.

**Comment by charliermarsh** [comment]
Nice, makes sense. Thank you!

**Comment by max-muoto** [comment]
Thanks @charliermarsh! Really appreciate the quick fix!
