### ISSUE TITLE
Lint rule shortlinks

### ISSUE THREAD

**Issue by notpushkin** [astral-sh/ruff#9211]
I've set up a short URL for Flake8 rules at [pyflak.es](https://pyflak.es/). It redirects from `pyflak.es/CODE` to the rule page on 
Flake8 Rules (e.g. [pyflak.es/E302](https://pyflak.es/E302)) or the respective plugin documentation (e.g. [pyflak.es/RST202](https://pyflak.es/RST202)). It should work with all rules supported by Ruff.

This can be handy when you want to quickly look up a specific rule. For example, the `wemake` formatter for Flake8 can print out the links, which you can click (in modern terminals) to open the respective docs page:

<pre>
» flake8 . --format=wemake --show-source --show-violation-links
./wemake_python_styleguide/formatter.py
  107:32   E231  missing whitespace after ':'
           <strong>-> <a href="https://pyflak.es/E231">https://pyflak.es/E231</a></strong>
  def show_source(self, error:Violation) -> str:
                              ^
</pre>

Would you be interested in integrating this, too? Let me know and I can try and work out a PR :-)

**Comment by notpushkin** [comment]
I've updated all rules supported by Ruff to link to `https://docs.astral.sh/ruff/rules/*` instead of the respective Flake8 plugin docs (as for most plugins Ruff docs are way more polished :-)

The only exception is pycodestyle errors and warnings, which still link to `https://www.flake8rules.com/rules/*`. Of course, any rules not supported by Ruff will still open the plugin page.

**Comment by charliermarsh** [comment]
That's really neat, thanks!

**Comment by charliermarsh** [comment]
We're likely gonna make some changes to the output format in the near-ish future to show source by default which will also give us an opportunity to incorporate documentation links -- but for now I'd rather omit, I think.
