### ISSUE TITLE
The Cargo.lock file is out of sync in the v0.1.9 release

### ISSUE THREAD

**Issue by alerque** [astral-sh/ruff#9234]
Arch Linux package builds for Rust projects typically use dependency pre-fetching then build in offline mode (`--frozen`). This requires the Cargo.lock file be up to date with Cargo.toml at release time otherwise the locking just throws an error. We can skip this, but it typically means either eschewing reproducibility or some elaborate process of patching the lock file in a reproducible way.

Can you please update the lock file prior to releases so they are always in sync at tagged release points?

As a side note it would be good in the CI builds used `--locked` as well to verify this and also produce more reproducible binaries.

**Comment by charliermarsh** [comment]
Understood, thanks, and sorry for the trouble. We've updated our release checklist to reflect this.
