### ISSUE TITLE
After update to 0.1.9 "DJ008 Model does not define `__str__` method" appears

### ISSUE THREAD

**Issue by sshishov** [astral-sh/ruff#9242]
After release of 0.1.9 the issue with base class inheritance start appearing (same file)

The issue possibly related to this PR: https://github.com/astral-sh/ruff/pull/9151

```ruff
DJ008 Model does not define `__str__` method
```

Example:
```python
import typing_extensions
from django.db import models as django_models

class ParentModel(django_models.Model):
    class Meta:
        abstract = True

    @typing_extensions.override
    def __str__(self) -> str:
        return f'{self.id}'

class ChildModel(ParentModel):  # <-- DJ008 Model does not define `__str__` method
    pass
```

Current ruff version: 0.1.9
Configuration: `--strict` with some small exclusions

**Comment by charliermarsh** [comment]
Thank you, that's my mistake.

**Comment by sshishov** [comment]
No worry @charliermarsh , not a critical issue, just small omission! We have added `type: ignore` by now, when the issue is fixed, it will be reported as unused ignore 🎉
