### ISSUE TITLE
String-rendering bug in docs

### ISSUE THREAD

**Issue by diceroll123** [astral-sh/ruff#9288]
It seems that the docs message for `FURB118` is cut off.

<img width="1646" alt="image" src="https://github.com/astral-sh/ruff/assets/1243957/88d8b970-839f-4da5-b82b-793676075f44">

But the format string in the code is 
```rust
format!("Use `operator.{operator}` instead of defining a {target}")
```

**Comment by charliermarsh** [comment]
Something happening in the Markdown-to-HTML conversion, maybe some lack of escaping?

**Comment by charliermarsh** [comment]
The Markdown looks right, but un-backticked format placeholders are missing upon conversion to HTML.

**Comment by charliermarsh** [comment]
It's probably the `attr_list` extension, the last `{}` placeholder is being treated as an HTML attribute.
