### ISSUE TITLE
Per-tool file exclusion/inclusion?

### ISSUE THREAD

**Issue by ktbarrett** [astral-sh/ruff#9295]
I'm looking to add the `pydocstyle` tool to my ruff config, but it checks all Python sources in the repo with this rule. Not all Python code in the repo is public facing: automation, tests, etc. and does not warrant docstrings which generates a ton of errors.

I'd like to run the pydocstyle checks against only one directory, while the other checks should be applied to all Python files. Is there any way to accomplish this? For further reference, I'm using pre-commit to run ruff.

**Comment by zanieb** [comment]
Hi!

There's [per-file-ignores](https://docs.astral.sh/ruff/settings/#per-file-ignores) which you can use to accomplish this.

There's been some debate about `per-file-selects` but I can't remember where — the closest I can find right now is https://github.com/astral-sh/ruff/issues/6156

**Comment by hauntsaninja** [comment]
You could put a ruff.toml in that directory that extends the base configuration

**Comment by ktbarrett** [comment]
@hauntsaninja Ah yes, that works!
