### ISSUE TITLE
Formatter: Improve handling of syntax errors

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#9311]
The current user-facing messaging for syntax errors encountered during formatting are not friendly and are significantly worse than the linter's. The error should be normalized into a message instead of using the debug representation of `ParseError`

e.g.

Line number not included ([existing issue](https://github.com/astral-sh/ruff/issues/8338)):

`error: Failed to format commands/liberrors.py: source contains syntax errors: ParseError { error: UnrecognizedToken(Name { name: "THE_INVALID_FILE" }, None), offset: 208, source_path: "<filename>" } 157 files left unchanged`

Cell number not included in notebook errors

`error: Failed to format course/videos/domain_adaptation.ipynb: source contains syntax errors: ParseError { error: UnrecognizedToken(Rpar, None), offset: 70, source_path: "<filename>" }`

The previous error is much nicer via the linter

`error: Failed to parse course/videos/domain_adaptation.ipynb:cell 9:1:71: Unexpected token ')'`

**Comment by charliermarsh** [comment]
I can fix these.

**Comment by zanieb** [comment]
It'd also be nice to exit with a specific code if we only fail due to syntax errors rather than some sort of other failure :) that way we can report it nicely in the ecosystem checks instead of treating it as a failed run of Ruff.
