### ISSUE TITLE
Implement new SIM rule SIM911: `zip(dict.keys(), dict.values()) → dict.items()`

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#9319]
Flake8 simplify was updated recently and a simple, but effective new rule was added.
```python
a = dict(...)
items = zip(a.keys(), a.values())
```

should instead be
```python
items = a.items()
```

@dosisod Refurb might be interested in this rule as well.

**Comment by trag1c** [comment]
I'd like to work on this, please assign me :)
