### ISSUE TITLE
Extend docstring-code-format to python snippets in MarkDown, RST etc

### ISSUE THREAD

**Issue by peterjc** [astral-sh/ruff#9326]
With [ruff](https://astral.sh/blog/ruff-v0.1.8) introducing the ``docstring-code-format`` setting, the tool might start to follow what https://pypi.org/project/blacken-docs/ offers - not just black style formatting to doctests within Python files, but also doctests and Python snippets within reStructuredText files (``*.rst``, often used for Python project documentation), Markdown files (``*.md``), and even LaTeX files (``*.tex``).

Is this something you think could be on the ruff roadmap? Or might it be better to look at other ways to achieve this, e.g. one might try modifying ``blacken-docs`` to invoke either ``black`` (as now) or the ``ruff`` formatter internally.

**Comment by charliermarsh** [comment]
👍 We do plan to support this though not sure if it's still captured in any open issues. @BurntSushi -- do you know if there's an issue for this?

**Comment by charliermarsh** [comment]
Ahh found it, I believe this is the same as https://github.com/astral-sh/ruff/issues/8237.

**Comment by peterjc** [comment]
Agreed, closing in favour of #8237. I'm surprised I missed that in my issue searches. Thanks!
