### ISSUE TITLE
About format imports

### ISSUE THREAD

**Issue by Byxs20** [astral-sh/ruff#9361]
![image](https://github.com/astral-sh/ruff/assets/64669718/a02559fe-7e81-4921-9e99-b385a8fc3fff)

Why is it that before it was going to format the import in three pieces and now it's suddenly a two piece area, I'm not sure what I set up to cause this.

Now FORMAT is shown below:

![image](https://github.com/astral-sh/ruff/assets/64669718/3883671a-4769-4528-ac5c-6fddf03745e1)

**Comment by charliermarsh** [comment]
Most likely it can't find `core` (assuming `core` is a local module, and not a third-party module). Could you share your rough project structure, and your `pyproject.toml` or `ruff.toml` file?

**Comment by charliermarsh** [comment]
And where is the `pyproject.toml` relative to those files?

**Comment by charliermarsh** [comment]
Where is the `.ruff.toml` being stored? (The above example works fine for me without _any_ `.ruff.toml` file so want to make sure I'm giving you the correct answer.)

**Comment by charliermarsh** [comment]
Yeah you can -- you can add something like this to your `settings.json` in VS Code:

```json
{
  "ruff.lint.args": ["--extend-select", "I"]
}
```

**Comment by charliermarsh** [comment]
Awesome, so glad to resolve! Sorry for the trouble.
