### ISSUE TITLE
Incorrect `Never` fix from `ANN201`

### ISSUE THREAD

**Issue by tylerlaprade** [astral-sh/ruff#9362]
I return values only inside `if` blocks, and if none of the `if` conditions trigger, I throw an exception. The autofix added `-> Never`, presumably because it was only looking outside the `if` blocks`.
<img width="827" alt="image" src="https://github.com/astral-sh/ruff/assets/5475199/13e813a2-0a2f-4015-b85d-1a17152a24c4">

**Comment by charliermarsh** [comment]
I believe this is fixed on `main` and in the release that's going out today. If not, I will reopen!
