### ISSUE TITLE
Improve `relative-imports` (`TID252`) message

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#9363]
Running `ruff check --select TID252 /tmp/example.py` using version `0.1.9` on

```python
from .. import foo
```

outputs

```
/tmp/example.py:1:1: TID252 Relative imports from parent modules are banned
```

I don't think this is a helpful message as it implies such imports don't work and doesn't suggest an improvement. It also doesn't match the style of other Ruff rule messages.

How about `Prefer absolute imports to relative imports from parent modules`?

**Comment by charliermarsh** [comment]
Makes sense to me!
