### ISSUE TITLE
Error running v0.1.10

### ISSUE THREAD

**Issue by nickdrozd** [astral-sh/ruff#9366]
After installing v0.1.10 via `pip`:

```
python3.11 -m ruff --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nick/.local/lib/python3.11/site-packages/ruff/__main__.py", line 32, in <module>
    ruff = os.fsdecode(find_ruff_bin())
                       ^^^^^^^^^^^^^^^
  File "/home/nick/.local/lib/python3.11/site-packages/ruff/__main__.py", line 25, in find_ruff_bin
    if path.is_file():
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_file'
```

**Comment by MaksAksenov** [comment]
The path method handling was updated for one case https://github.com/astral-sh/ruff/pull/9315/files#diff-a2a4fcdbfaddd66c163fba246256d9648cda29200a4e20a5da780c9fe4e10defR11 and was not updated for another - https://github.com/astral-sh/ruff/pull/9315/files#diff-a2a4fcdbfaddd66c163fba246256d9648cda29200a4e20a5da780c9fe4e10defR25

**Comment by charliermarsh** [comment]
Ah thanks, I'll cut a follow-up release to fix this today.

**Comment by charliermarsh** [comment]
If anyone is interested in a quick PR, welcome to it, otherwise I will :)

**Comment by zanieb** [comment]
Thanks for the pull request! Could ya'll briefly describe how Python / Ruff is installed on your system? It looks like the test coverage in CI is for a different branch of the logic here.

**Comment by nickdrozd** [comment]
I'm running some version of Ubuntu where the system `python3` is `python3.8`. `python3.11` is installed via `apt`, and `ruff` is installed via `python3.11 -m pip`.

**Comment by nickdrozd** [comment]
`which ruff` => `/home/nick/.local/bin/ruff`. But

```python
    ruff_exe = "ruff" + sysconfig.get_config_var("EXE")

    path = os.path.join(sysconfig.get_path("scripts"), ruff_exe)
```

`path` => `/usr/local/bin/ruff`, which is not a path that exists.
