### ISSUE TITLE
Fuzzer fails to build memchr

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#9368]
See https://github.com/astral-sh/ruff/actions/runs/7390478731/job/20105487965

**Comment by charliermarsh** [comment]
@addisoncrump -- Any chance it's obvious to you why this started failing?

**Comment by addisoncrump** [comment]
The CI tells the truth :dove: : https://github.com/astral-sh/ruff/actions/runs/7390478731/job/20105487965#step:6:39

It seems that musl is being set somehow.

**Comment by addisoncrump** [comment]
Notably, it seems that the bin provided from binstall is a musl binary: https://github.com/astral-sh/ruff/actions/runs/7390478731/job/20105487965#step:5:39
This did not use to be the case: https://github.com/astral-sh/ruff/actions/runs/7389857960/job/20103579755#step:5:39

At a guess, this is some weird "rust binary expects consistency" issue. I'll try to repro locally.

**Comment by addisoncrump** [comment]
Yup, just verified locally: building with [the version provided by cargo-fuzz upstream](https://github.com/rust-fuzz/cargo-fuzz/releases/tag/0.11.3) causes a build failure as it expects musl.

**Comment by charliermarsh** [comment]
Nice, thank you. I was able to get CI passing by pinning to the previous minor: https://github.com/astral-sh/ruff/pull/9372

**Comment by addisoncrump** [comment]
Resolved at record pace :rocket: I'll communicate upstream to try to resolve this there so we can remove the pinning. Don't close this issue yet?

**Comment by MichaReiser** [comment]
> Resolved at record pace 🚀 I'll communicate upstream to try to resolve this there so we can remove the pinning. Don't close this issue yet?

@addisoncrump Let us know when we're good to close the issue.

**Comment by addisoncrump** [comment]
You can close it this side, there's now a tracking issue upstream: https://github.com/taiki-e/install-action/pull/352

**Comment by charliermarsh** [comment]
Thanks!
