### ISSUE TITLE
Infinite loop in F632/E711

### ISSUE THREAD

**Issue by addisoncrump** [astral-sh/ruff#9374]
I just tried this on master (6c0734680ede806cef849d2d8c7105e2ecd785ad).

Consider the following snippet:
```py
for x in c > 0 == None:
 pass
```

This fails to converge as `==` is replaced with `is` and back over and over.

This appears in real code: https://github.com/CARocha/suco_proga/blob/543eff68a62a4d742a9b956d6127f8f6076c7211/suco/encuesta/views.py#L79
Though appears to be a bug!

The linked example minimises to:
```py
if encuesta2.count() > 0 is not None:
  pass
```

Testable with `ruff --fix --unsafe-fixes ...`.

**Comment by charliermarsh** [comment]
Nice, thanks!
