### ISSUE TITLE
Set location of ruff binary via env var

### ISSUE THREAD

**Issue by jenia90** [astral-sh/ruff#9378]
Our python dist uses a different location for the bin/ folder, thus getting its location via `sysconfig` functions doesn't work.
So, it'd be really handy to be able to specify the location of ruff executable via env var. We can have something like
`RUFF_BIN_PATH=/some/path/ruff`

If you are ok with that, I can send a PR.

Thanks for all the awesome job you're doing!

**Comment by charliermarsh** [comment]
Are you referring here to invocations of `python -m ruff`? Or use in the VS Code extension? Or something else?

**Comment by jenia90** [comment]
> Are you referring here to invocations of `python -m ruff`? Or use in the VS Code extension? Or something else?

I'm referring to `python -m ruff` or `import ruff.__main__`. If we try running `ruff` by either way, it raises an exception:
```FileNotFoundError: %USERPROFILE%\AppData\Roaming\Python\Python37\Scripts\ruff.exe```

**Comment by zanieb** [comment]
Where is the binary being stored?

If you're going to be customizing the path to the binary you're probably just better off calling it directly, right?

**Comment by jenia90** [comment]
It's deployed too all developer machines, but to a different folder than the default `../Scripts`.
I do call it directly, I just thought to add a more generic way of doing it, so that we can add an env var to our python dist and have it working without any special wrappers.

**Comment by charliermarsh** [comment]
Unfortunately I think I would prefer not to support this. It's straightforward but it feels non-standard and it does open the door to some confusing behaviors (e.g., `python -m ruff` could then resolve to a binary installed in some other virtual environment).
