### ISSUE TITLE
Add support for optional trailing comma

### ISSUE THREAD

**Issue by 17Reset** [astral-sh/ruff#9389]
When I format my code using ruff format, after the format, there is always a comma after the code, can this be avoided by a parameter?
For example, my source code:
```python
FILE_SUFFIX_ICON = {
    MATLAB_SUFFIX: MATLAB_ICON,
    CPP_SUFFIX: CPP_ICON,
    SV_SUFFIX: RTL_ICON,
    'Default': FILE_ICON
}
```
After using format:
```python
FILE_SUFFIX_ICON = {
    MATLAB_SUFFIX: MATLAB_ICON,
    CPP_SUFFIX: CPP_ICON,
    SV_SUFFIX: RTL_ICON,
    'Default': FILE_ICON,
}
```

**Comment by tjkuson** [comment]
The Ruff formatter tries to follow the [Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html), which adds a trailing comma. A configuration option has not been added to Ruff to change that behaviour (it would have to be a new feature).

Related discussion: #9350

**Comment by 17Reset** [comment]
Thanks, hope to add this feature option.

**Comment by heiner** [comment]
Here's a reason this might be useful: It turns `ruff format` into a quite decent `json` formatting engine. E.g.,

```
cat file.json | ruff format - --isolated --config indent-width=2
```

However, sadly trailing commas aren't legal JSON.

**Comment by MichaReiser** [comment]
You may want to try [Biome](https://biomejs.dev/) if you want a JSON formatter.

**Comment by MichaReiser** [comment]
I'm closing this as not planned. Feel free to open a new issue to discuss the style with an outline for the use case and benefit of omitting trailing commas.

**Comment by 17Reset** [comment]
It's not a popular style for trailing commas to appear after line breaks in Python lists, is it?

**Comment by heiner** [comment]
> You may want to give [Biome](https://biomejs.dev/) a try if you are looking for a Rust based JSON formatter.

That's less useful as a quick-and-dirty way to format JSON _within Python code_, where the existence of `ruff` is more or less guaranteed.

Still, ack'd on this being a bit fringe.

**Comment by mshahbazi** [comment]
The issue arises when the formatter adds a trailing comma, which prevents the code from being one-liner, when shortened, due to the presence of the comma, unless the trailing comma is removed manually.

**Comment by dberardo-com** [comment]
i believe trailing commas dont work in python2.7, so it makes sense to make them optional

**Comment by webknjaz** [comment]
I've found that a workaround is a double-pass of `ruff format` with an `add-trailing-comma` in-between: https://github.com/ansible/awx-plugins/blob/002bdc8/.pre-commit-config.yaml#L43-L58.
