### ISSUE TITLE
Invalid formatting of match statement

### ISSUE THREAD

**Issue by MSDehghan** [astral-sh/ruff#9394]
formatting below code with `ruff format file.py` command leads to invalid python code:
```python
match {}:
    case {
        "long_long_long_key": str(long_long_long_key)
    } if value := "long long long long long long long long long long long value":
        pass

```

after formatting with ruff the file will look like this which is not a valid python code:
```python
match {}:
    case {"long_long_long_key": str(long_long_long_key)} if value
    := "long long long long long long long long long long long value":
        pass
```

ruff version:  0.1.11

**Comment by zanieb** [comment]
Can reproduce this, thanks for the report!

**Comment by charliermarsh** [comment]
I can take a look -- thanks for this.

**Comment by charliermarsh** [comment]
Fixed by https://github.com/astral-sh/ruff/pull/9396. Thanks!
