### ISSUE TITLE
Unexpected unwrap in `invalid_escape_sequence.rs`

### ISSUE THREAD

**Issue by th3w1zard1** [astral-sh/ruff#9398]
Been getting these errors in vs code as of late:
```
thread 'main' panicked at crates\ruff_linter\src\rules\pycodestyle\rules\invalid_escape_sequence.rs:215:18: called `Option::unwrap()` on a `None` value note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace )
```
This error message asked me to post here.

Would like to point out this usually happens while I'm typing code, so obviously there are going to be syntax errors but I'm not sure why Ruff is trying to parse them. If I need to post this on a different repo please let me know.

**Comment by charliermarsh** [comment]
Thank you. Do you happen to know what version of Ruff you're using? Or of the VS Code extension?

**Comment by th3w1zard1** [comment]
I update all my extensions and be code daily but I can check this next Im at my pc. Thanks for the quick response. Am running windows 10

**Comment by th3w1zard1** [comment]
Usually happens when I'm actively typing f strings, or when I'm backspacing some of statements

**Comment by charliermarsh** [comment]
It sounds like this was resolved in newer versions of Ruff, based on this similar issue: https://github.com/astral-sh/ruff/issues/9542.

**Comment by th3w1zard1** [comment]
Can confirm I haven't had it happen in two weeks
