### ISSUE TITLE
Formatter: Unnecessary parentheses around return type annotations

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#9447]
Ruff adds unnecessary parentheses around return type annotations that are either:

* guaranteed to break like multiline strings
* Come with their own set of parentheses

```python
def test() -> """test
""": pass

def test() -> [aaa, bbbb,]: pass

def test() -> lists(a, b,): pass
```

**Ruff**

```python
def test() -> (
    """test
"""
):
    pass


def test() -> ([
    aaa,
    bbbb,
]):
    pass


def test() -> (
    lists(
        a,
        b,
    )
):
    pass

```

**Black**

```python
def test() -> """test
""":
    pass


def test() -> [
    aaa,
    bbbb,
]:
    pass


def test() -> lists(
    a,
    b,
):
    pass
```

**Comment by icp1994** [comment]
I know this is somewhat of an edge case, but any workaround (tweaks in settings) for this?

Off-topic: maybe issues from [here](https://github.com/astral-sh/ruff/milestones/Formatter:%20Stable) could be moved to a new `Formatter: Post Stable` milestone for easier tracking.
