### ISSUE TITLE
Add PR title guidelines to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by trag1c** [astral-sh/ruff#9470]
I had difficulty deciding on a suitable name when opening a pull request recently. I couldn't find any guidance on naming PRs in `CONTRIBUTING.md` despite seeing some of them be renamed before merging (e.g., #9166, #9174, #8995, #8036).

I think adding some naming guidelines could be helpful for both contributors and maintainers. Just to share my experience, I spent around 10 minutes going through recently merged PRs trying to perfect the name of mine. 😄

**Comment by Tade77** [comment]
Hello @trag1c  i'm frontend developer, i would like tto work on this issue

**Comment by charliermarsh** [comment]
Hah, yeah, this would be great. I end up doing the names either before merging or when creating the changelog.
