### ISSUE TITLE
Failed to create cache file

### ISSUE THREAD

**Issue by yellowhat** [astral-sh/ruff#9489]
Hi,
with the latest release (0.1.12), I get the following error:

```console
$ pip install ruff==0.1.12
$ ruff check --diff .
ruff failed
  Cause: Failed to create cache file '/data/.ruff_cache/0.1.12/1566177860923460140'
  Cause: No such file or directory (os error 2)
```

It seems that now it expect the cache folder to already exist.

The workaround is to run `mkdir -p .ruff_cache/0.1.12`, that is quite annoying.

**Comment by MichaReiser** [comment]
Sorry for the trouble. This has been fixed very recently and we plan to make a bugfix release soon. See https://github.com/astral-sh/ruff/issues/9478
