### ISSUE TITLE
Display-only fix is marked as fixable in the docs (`ERA001`)

### ISSUE THREAD

**Issue by korchizhinskiy** [astral-sh/ruff#9505]
![image](https://github.com/astral-sh/ruff/assets/100942887/4114397b-e8f4-41ac-b92f-5337f60c562a)

https://docs.astral.sh/ruff/rules/#eradicate-era
This rule specify as fixable, but when i use --fix flag, errors don't fixes automaticly.
And there's no notification below the errors about fixable this error.

**Comment by charliermarsh** [comment]
We probably shouldn't mark display-only fixes as fixable in the docs. \cc @zanieb
