### ISSUE TITLE
No __prepare__ at is_known_dunder_method

### ISSUE THREAD

**Issue by arnaud-ma** [astral-sh/ruff#9508]
For exemple 
```python3
class A(type):
    @classmethod
    def __prepare__(cls, name, bases): ...
```
returns the error "PLW3201 Bad or misspelled dunder method name `__prepare__`". It appears that this is missing in https://github.com/astral-sh/ruff/blob/e8d7a6dfce3251a76afc754899034fad48376d99/crates/ruff_linter/src/rules/pylint/helpers.rs#L202-L210

We can verify that this is the last dunder method missing by doing a regex `\b__\w+__\b` on https://docs.python.org/3/reference/datamodel.html and looking at what is missing in the file. We obtain 
- `__annotations__`
- `__bases__`
- `__classcell__`
- `__closure__`
- `__code__`
- `__defaults__`
- `__file__`
- `__func__`
- `__future__`
- `__globals__`
- `__import__`
- `__kwdefaults__`
- `__match_args__`
- `__mro__`
- `__mro_entries__`
- `__name__`
- `__objclass__`
- `__prepare__`
- `__qualname__`
- `__self__`
- `__slots__`
- `__traceback__`
- `__type_params__`

It appears `__prepare__` is the only method here

**Comment by zanieb** [comment]
Thanks! Not sure if this was excluded intentionally but I'm not sure why it would be.

**Comment by arnaud-ma** [comment]
Well __prepare__ is a bit of a special case that very few people use, this is the only method that only makes sense if it's in a metaclass so I can understand. 
Furthermore for the `PLW3201` as we can add __prepare__ in the bad-dunder-method-name setting it's not really a big problem in itself. But I find it a bit strange that by default the linter acts as if the method does not exist at all.

**Comment by takaya0** [comment]
I'd like to work on this, please assign me :)
