### ISSUE TITLE
Add a rule for `defaultdict(default_factory=list)`

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/ruff#9509]
Kwargs in the defaultdict constructor are forwarded to the dict constructor, so this creates a defaultdict with `{"default_factory": list}`. Since this is a valid call, type checkers may or may not catch this (and even when they catch it, the error might be a little confusing). ruff could lint this specific situation and mention use of `collections.defaultdict(list)` instead.

**Comment by charliermarsh** [comment]
Seems like a good rule.

**Comment by Skylion007** [comment]
@hauntsaninja You should also open the issue in the flake8-bugbear repo, they may be interested in it.

**Comment by mikeleppane** [comment]
I can take this.

**Comment by mikeleppane** [comment]
@hauntsaninja did you use 'list' as an example or I assume this applies to any callable? I tried default_factory with mypy 1.7.1 and it truly seems to be confused with different input types (list, int, dict, lambda, ...).

**Comment by hauntsaninja** [comment]
As an example! :-) Like I said, type checkers can't catch the call itself since it's valid. They may be able to surface an issue later because they'll infer a different type for the defaultdict.

**Comment by charliermarsh** [comment]
Added in https://github.com/astral-sh/ruff/pull/9651, thanks @mikeleppane!
