### ISSUE TITLE
False positive F401 "imported but unused" when use is cast() inside a lambda

### ISSUE THREAD

**Issue by jriddy** [astral-sh/ruff#9534]
I found a fun edgy edge case running this one my code base. Ruff cannot detect use of classes in calls to `cast()` inside a lambda with `from __future__ import annotations` on.

## Minimal reproducer

```python
from __future__ import annotations

from collections import Counter
from typing import cast


def get_most_common_fn(k):
    return lambda c: cast(Counter, c).most_common(k)
```

Running ruff results in an error:

```shell
❯ ruff check --isolated repro.py
repro.py:3:25: F401 [*] `collections.Counter` imported but unused
Found 1 error.
[*] 1 fixable with the `--fix` option.
```
## Expected behavior

I expected Ruff to detect the use of the imported class in the call to `cast()`, but it looks like the combination of `from __future__ import annotations` and having the cast call in a `lambda` expression obscures that use from Ruff.  Note that with the annotations future feature off this does not occur, nor does using a cast in non-lambda code seem to cause any issue.

## Info & versions

Ruff: 0.1.13
Python: 3.11.5
OS: Fedora 38

**Comment by charliermarsh** [comment]
Thank you, very much a bug!

**Comment by jriddy** [comment]
Thanks for the quick turnaround on this! It gives me a lot of confidence in the project
