### ISSUE TITLE
W391 implementation is missing despite being checked off

### ISSUE THREAD

**Issue by sihil** [astral-sh/ruff#9544]
In a pycodestyle tracking issue https://github.com/astral-sh/ruff/issues/2402 the rule for `W391` is checked but this does not exist in the ruff codebase. In fact there is a [comment noting this](https://github.com/astral-sh/ruff/issues/2402#issuecomment-1855323380). Can this be unchecked so the tracking and expectations is right and, ultimately, tackled?

**Comment by charliermarsh** [comment]
Thanks, I unchecked it -- not sure how that happened!
