### ISSUE TITLE
PLR0917: should this exclude `self` and `cls`?

### ISSUE THREAD

**Issue by tmke8** [astral-sh/ruff#9552]
[PLR0917](https://docs.astral.sh/ruff/rules/too-many-positional/) counts the number of non-keyword-only arguments and checks whether the number is above `max-positional-args`. This count includes `self` and `cls` in methods and class-methods, but I feel like those shouldn't count because they are passed in implicitly.

I'd be willing to make the code change if this is acceptable.

**Comment by charliermarsh** [comment]
Yeah, I think it probably should exclude those.
