### ISSUE TITLE
Ruff crashed when checking code in jupyter notebook. It failed to handle non-ascii characters correcly.

### ISSUE THREAD

**Issue by LENAX** [astral-sh/ruff#9575]
Ruff: Lint failed (
error: Ruff crashed. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

...quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread 'main' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\str\mod.rs:660:13:
byte index 2 is not a char boundary; it is inside '且' (bytes 0..3) of `且类型为枚举SupportType中的类型`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
)

![image](https://github.com/astral-sh/ruff/assets/1931031/4ae4ef0f-0a9a-4ea1-9e68-eb97526a33fc)

**Comment by MichaReiser** [comment]
Hy @LENAX I'm sorry you ran into this issue. What ruff version are you using? It should be fixed in ruff 0.1.9 or newer (see https://github.com/astral-sh/ruff/pull/9146)

**Comment by LENAX** [comment]
I was using version 0.1.8. Thanks for reminding me to upgrade.
