### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by stunlocked1** [astral-sh/ruff#9576]
I tried every setting but nothing worked. I wanted to only use ruff for formatting, I don't want it to show everything as warnings in my code. How do I do that?

**Comment by MichaReiser** [comment]
You can run ruff's formatter by using `ruff format <paths>`. It only formats your code. It won't run any lint rules. 

The VS code extension doesn't yet support your use case but we plan to add a setting soonish. You can follow https://github.com/astral-sh/ruff-vscode/issues/329 to get informed once its done.

**Comment by stunlocked1** [comment]
ok thanks
