### ISSUE TITLE
namespace-packages option stopped working in a recent update

### ISSUE THREAD

**Issue by gokay05** [astral-sh/ruff#9579]
When running Ruff with version 0.1.11, namespace-packages option excluded INP001 from being thrown. I recently updated Ruff to 0.1.13 and even though my ruff.toml hasnt changed, I am getting a bunch of INP001 from my test folders and such. I checked the website and I dont see anything change in terms of how the option works, so I think there might be a bug in the new version that effectively breaks namespace-packages.

**Comment by charliermarsh** [comment]
Hmm, I don't think we changed anything there in this version range. Are you able to share an example, including the configuration? It's _possible_ that your old setup was working due to caching, since the INP rules have a bug related to caching (and upgrading your Ruff version would clear the cache).

**Comment by gokay05** [comment]
Here is a small example that reproduces the issue: https://github.com/gokay05/namespace-test 

When I run `ruff check --config ruff.toml` on this repo, I get the errors about the two folders that are in namespace-packages. 

![image](https://github.com/astral-sh/ruff/assets/62908441/e2208caf-8769-44ca-8ce6-cff507a41173)

**Comment by charliermarsh** [comment]
Thanks so much for putting together a repro! I'll take a look.

**Comment by charliermarsh** [comment]
Hm, something about specifying the config explicitly?

```
namespace-test on  main
❯ ruff check . -n
namespace-test on  main
❯ ruff check . --config ruff.toml -n
namespacepackages/namespacepackages/folder2/file2.py:1:1: INP001 File `namespacepackages/namespacepackages/folder2/file2.py` is part of an implicit namespace package. Add an `__init__.py`.
nonpackage/nonpackagefile.py:1:1: INP001 File `nonpackage/nonpackagefile.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 2 errors.
```

**Comment by charliermarsh** [comment]
Ah sorry, this is indeed a bug, my fault. Thank you so much for filing!

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/ruff/pull/9603, will go out in the next release.

**Comment by gokay05** [comment]
Thanks so much!!

**Comment by charliermarsh** [comment]
Thank _you_, I will always fix when there's a clear repro!
