### ISSUE TITLE
Rule suggestion: recommend `dict.fromkeys` over comprehension

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#9592]
Replace

```python
{elt: None for elt in foo}
```

with

```python
dict.fromkeys(foo)
```

`dict.fromkeys` is more efficient and readable.

```
In [4]: import random

In [5]: choices = ("red", "green", "blue")

In [6]: dupes = [random.choice(choices) for _ in range(1000)]

In [7]: %timeit list({elt: None for elt in dupes})
18.8 µs ± 97.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [8]: %timeit list(dict.fromkeys(dupes))
12.6 µs ± 49.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

Efficiency boost tested on both Python 3.9 and 3.12.

Note: would have to skip this rule for mutable values (see #4613).

**Comment by charliermarsh** [comment]
Looks great!

**Comment by mikeleppane** [comment]
I could pick up this one?

**Comment by charliermarsh** [comment]
Feel free unless @tjkuson planned to do it or had started on it -- I'll leave it to @tjkuson to confirm!

**Comment by tjkuson** [comment]
> Feel free unless @tjkuson planned to do it or had started on it -- I'll leave it to @tjkuson to confirm!

Haven't started anything, have at it! @mikeleppane

**Comment by Skylion007** [comment]
This would be a great rule for refurb, C4, or perflint. You should consider pinging the author of those libraries as well.

**Comment by bswck** [comment]
This applies not only to `None`, but any constant.
In my opinion, `{elt: 0 for elt in foo}` should also be replaced with `dict.fromkeys(foo, 0)`.

**Comment by bswck** [comment]
@tjkuson would you agree? ↑

**Comment by tjkuson** [comment]
> @tjkuson would you agree? ↑

Yes, this was my intention with the PR. Admittedly, I communicated that poorly by using only examples with `None`.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff/pull/9613. Thanks @mikeleppane!
