### ISSUE TITLE
Using ruff to format doctests in .rst (and other format) files

### ISSUE THREAD

**Issue by jagerber48** [astral-sh/ruff#9620]
#7146 introduces the ability to format code examples within docstrings in `.py` files. In [this message](https://github.com/astral-sh/ruff/issues/7146#issuecomment-1811115865) outlining the proposed strategy it was specifically deemed out of scope to apply formatting to `.rst` or `.md` files

> **Formatting Python code in other formats**
This means you won't be able to run the formatter over a .rst or a .md file
and have it format any Python code blocks in it. This initial implementation
will only support reformatting Python snippets within docstrings inside Python
files. We can consider formatting Python code in other formats as a future
project.

I'm opening up this issue to request such an ability be added to `ruff` it that is not already being considered. Or, if it has been considered, then to discuss the issue or hear why it wouldn't be possible.

**Comment by zanieb** [comment]
Hi! This looks like a duplicate of https://github.com/astral-sh/ruff/issues/8237 — let us know if that doesn't cover your use case.

**Comment by jagerber48** [comment]
@zanieb yes, duplicate. I tried looking but didn't find it. Thank you!

**Comment by ulgens** [comment]
@zanieb Any chance to reopen the issue and close it as a duplicate, with a link to #8237 ? The current resolution seems misleading.
