### ISSUE TITLE
 Default Ruff configuration file reports schema error

### ISSUE THREAD

**Issue by ssteinerx** [astral-sh/ruff#9630]
[Ruff config](https://docs.astral.sh/ruff/configuration/) gives a .toml file that is equivalent to the default configuration.

[Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) reports an error in that .toml file:

{"quote-style":"double","indent-style":"space","skip-magic-trailing-comma":false,"line-ending":"auto","docstring-code-format":false,"docstring-code-line-length":"dynamic"} is not valid under any of the given schemas

I reported this in the .toml validator used by Even Better TOML: [Taplo issue tracker #536](https://github.com/tamasfe/taplo/issues/536) and they tell me the .toml file does not match the schema and that:

>>  this is not a problem in Taplo but in the [Ruff schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/ruff.json).

and that there's an [issue for this in SchemaStore](https://github.com/SchemaStore/schemastore/issues/2731).

I couldn't find another issue here about it, so here one is.

**Comment by charliermarsh** [comment]
Thanks -- let me check if the schema is out-of-date. We have to update it manually and it sometimes slips through the cracks during releases.

**Comment by charliermarsh** [comment]
The PR is here: https://github.com/SchemaStore/schemastore/pull/3549. But I don't expect any of those to fix the specific error you're reporting, those settings were added long ago. Let me try in VS Code.

**Comment by charliermarsh** [comment]
It seems like the `format` section isn't being picked up by the extension. But the schema file _looks_ right to me on our side. Hmm...

**Comment by charliermarsh** [comment]
Ah, I see, it's specifically this line:
```toml
# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
```

**Comment by charliermarsh** [comment]
Thanks for reporting this, should be fixed by https://github.com/astral-sh/ruff/pull/9632.
