### ISSUE TITLE
New rule: find unused placeholders for f-strings

### ISSUE THREAD

**Issue by Sanchoyzer** [astral-sh/ruff#9638]
`ruff==0.1.14`
```
def func(my_var: int) -> int:
    var = my_var * 2
    print('var is {var}')
    return var
```
It might be useful if Ruff will find such places, I made a typo: `'var is {var}'` instead of `f'var is {var}'`

**Comment by trag1c** [comment]
I think this is a duplicate of #8151

**Comment by charliermarsh** [comment]
Agreed -- I'd like to add this!
