### ISSUE TITLE
Is it possible to suppress a rule on a block of code?

### ISSUE THREAD

**Issue by DaniBodor** [astral-sh/ruff#9646]
I would like to disable/suppress ruff (or certain rules of ruff) on a block of code. I know that I can do this for single lines (by using # noqa: <rule_code> at the end of the line) or for entire files/folder (by specifying them in the settings file).

However, I would like to disable ruff on an entire function or on a multi-line block of code, but not an entire file. Is there a way to do this, without adding the noqa to the end of each line?

Thanks

**Comment by charliermarsh** [comment]
Unfortunately we don't support block-level suppression right now. I believe this is similar to #3711 so I'm going to merge into that issue.
