### ISSUE TITLE
False positive of TCH003 on InitVar import

### ISSUE THREAD

**Issue by jonyscathe** [astral-sh/ruff#9666]
TCH003 should not be raised on InitVar or ClassVar import even if they are only used for typing within a dataclass.
This is because they are needed at runtime.

See the corresponding issue in flake8-type-checking for more information: https://github.com/snok/flake8-type-checking/issues/83

Not sure if it should be fixed in the same way in ruff.

Currently using ruff==0.1.14

Settings:
[tool.ruff]
extend-select = ['D213']
ignore = ['ANN101', 'ANN401', 'D107', 'D203', 'D212', 'E203', 'ISC003', 'N803', 'N806', 'PLC1901', 'PLC2701']
line-length = 120
preview = true
select = ['ALL']
target-version = 'py312'

[tool.ruff.format]
line-ending = 'lf'
quote-style = 'single'

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.isort]
known-first-party = ['namespace.project']

[tool.ruff.lint.pylint]
max-args = 8

**Comment by jonyscathe** [comment]
I now realise that the setting: `exempt-modules = ["dataclasses"]` does fix this.  
So I guess that is fine. Not the most ideal solution as it could mask genuine issues, but it'll work.

**Comment by charliermarsh** [comment]
Is the right solution here not to add `@dataclass` to `runtime-evaluated-decorators`? See: https://docs.astral.sh/ruff/settings/#flake8-type-checking-runtime-evaluated-decorators.

**Comment by charliermarsh** [comment]
Oh, but I guess this only applies to `InitVar` specifically, and not other annotations used within dataclasses?

**Comment by charliermarsh** [comment]
We can fix this.

**Comment by jonyscathe** [comment]
Thanks for the quick fix!
It is annoying that there are a handful of special cases like this in Python where the typing is actually used at runtime.
