### ISSUE TITLE
D207 and D300 doesn't mention formatter redundancy

### ISSUE THREAD

**Issue by trag1c** [astral-sh/ruff#9675]
Both [D207](https://docs.astral.sh/ruff/rules/under-indentation/) and [D208](https://docs.astral.sh/ruff/rules/over-indentation/) seem to be affected by the formatter, yet only D208 documents that behavior. Are there any cases in which D208 violations won't get formatted correctly or is this just an oversight?

**Comment by zanieb** [comment]
It looks like an oversight to me!

**Comment by trag1c** [comment]
Looks like it also applies to [D300](https://docs.astral.sh/ruff/rules/triple-single-quotes/).

**Comment by takaya0** [comment]
I'd like to try this issue. Could you assign me to fix this issue?

**Comment by Avasam** [comment]
Are you sure D300 applies? They playground even with `preview=true` does not format those docstring back to triple-quoting: https://play.ruff.rs/c41e8485-df53-4dbd-a738-274ffc71c6fe
