### ISSUE TITLE
RUF023: Sorting `__match_args__` changes match semantics

### ISSUE THREAD

**Issue by dosisod** [astral-sh/ruff#9723]
RUF023 should not sort `__match_args__` because the order of `__match_args__` affects which elements are matched against when using positional args in class patterns.

Take the following code example:

```python
from dataclasses import dataclass

@dataclass
class UnaryExpr:
    __match_args__ = ("op", "lhs")

    op: str
    lhs: int


def is_minus_one(expr):
    match expr:
        case UnaryExpr("-", 1):
            return True

    return False


is_minus_one(UnaryExpr("-", 1))  # True
is_minus_one(UnaryExpr("+", 1))  # False
```

Ruff emits the following errors:

```
$ ruff --preview --select RUF023 file.py
file.py:6:22: RUF023 [*] `UnaryExpr.__match_args__` is not sorted
```

If you change `__match_args__` to `("lhs", "op")`, the semantics of the match statement changes, and now both `is_minus_one` calls return `False`.

**Comment by AlexWaygood** [comment]
Oof, I can't believe I forgot that this was how things worked. Thanks!
