### ISSUE TITLE
[FEATURE] Support attrs in RUF008 and RUF009

### ISSUE THREAD

**Issue by alanhdu** [astral-sh/ruff#9757]
These rules guard against using mutable default values in `dataclasses`. It would be nice if these rules *also* supported attrs,  which is the (more feature-rich) predecessor which is also pretty widely used.

If this is something that you'd be open for, I think I can get some time to potentially contribute a patch myself.

**Comment by charliermarsh** [comment]
Makes sense!

**Comment by charliermarsh** [comment]
@alanhdu - Do you mind if I assign this one to you?

**Comment by alanhdu** [comment]
No problem! I am busier than I thought and it'll probably at least another week before I get to this, but do plan on getting to this "soon".

**Comment by charliermarsh** [comment]
Cool, thanks! No worries and no rush.

**Comment by segfly** [comment]
I was recently bit by the lack of these rules working with attrs. So I also wish to see this implemented please. Thanks.

**Comment by alanhdu** [comment]
Ah yes, sorry -- I have gotten distracted by other things at work. I hopefully will still get to this "at some point", but if anyone else has time they should feel free to implement it themselves.
