### ISSUE TITLE
Multiline f-strings are not indexed as multiline strings

### ISSUE THREAD

**Issue by sanxiyn** [astral-sh/ruff#9777]
Tracking leftover work from #9744. Removing trailing whitespace inside multiline strings is unsafe, so multiline strings are indexed. But multiline f-strings are currently not indexed as multiline strings.

**Comment by dhruvmanila** [comment]
Thanks for the issue! Are you interested in taking on the work required to complete this as you commented on the linked PR?

**Comment by sanxiyn** [comment]
Yes, I want to try.

**Comment by dhruvmanila** [comment]
Awesome! Feel free to ping me if you run into any issues :)
