### ISSUE TITLE
Feature request: add `DEPRECATED` selector

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#9778]
`ruff check --isolated --select=ALL` selects `ANN101` which is deprecated. I would love to be able to do `ruff check --isolated --select=ALL --ignore=DEPRECATED`. (I know I could do `ruff check --isolated --select=ALL --preview`, but I don't want to add all preview rules.)

**Comment by bersbersbers** [comment]
Another great selector would be `INCOMPATIBLE_WITH_FORMATTER`, including (for example) `COM812`.

**Comment by MichaReiser** [comment]
Sounds reasonable to me. I rename this back to `DEPRECATED` and track the formatter incompatible rules in https://github.com/astral-sh/ruff/issues/10225

**Comment by zanieb** [comment]
I think we should do https://github.com/astral-sh/ruff/issues/10342 instead

**Comment by zanieb** [comment]
By the way, if you don't want to enable all preview rules, you can use [`explicit-preview-rules`](https://docs.astral.sh/ruff/settings/#lint_explicit-preview-rules).
