### ISSUE TITLE
"many more" link is broken on https://docs.astral.sh/ruff/

### ISSUE THREAD

**Issue by graingert** [astral-sh/ruff#9783]
Going to https://docs.astral.sh/ruff/ and clicking "many more" doesn't go anywhere

**Comment by graingert** [comment]
![image](https://github.com/astral-sh/ruff/assets/413772/6cf40cdc-7db9-4082-884c-c96b7f6aa41c)

**Comment by graingert** [comment]
the link is https://docs.astral.sh/ruff/#whos-using-ruff

**Comment by dhruvmanila** [comment]
Thanks for pointing it out! The reason is that the section only exists in the [README](https://github.com/astral-sh/ruff#whos-using-ruff) and not on the documentation.
