### ISSUE TITLE
linter is not checking for E302 rule

### ISSUE THREAD

**Issue by umair313** [astral-sh/ruff#9811]
Ruff version `0.2.0`
or the bellow code following commands are not working, it should fix the space between two functions according to PEP E302 rule.
```
ruff check .
```
```
ruff check --fix .
```
## Code
```
class Node:
    data = None
    next_node = None

    def __init__(self, data):
        self.data = data
    def __repr__(self):
        return f"<Node: {self.data}>"
```

**Comment by charliermarsh** [comment]
Thanks for filing! We haven't shipped support for the `E3` rules yet. You can see the Pycodestyle progress here: https://github.com/astral-sh/ruff/issues/2402. And there's an open PR for it here: https://github.com/astral-sh/ruff/pull/9266.

**Comment by umair313** [comment]
@charliermarsh thanks! I've been considering transitioning from using pre-commit with flake8 to pre-commit with ruff. However, upon reflection, it seems this change might not be feasible at the moment.

🚀 I'm eager to contribute to this. Could you advise on how I might be able to assist?
