### ISSUE TITLE
Segmentation fault: 11 with ruff 0.2.0

### ISSUE THREAD

**Issue by jetli** [astral-sh/ruff#9823]
when run ruff 0.2.0, it always return an error msg: Segmentation fault: 11, but ruff 0.1.15 is ok.
```bash
$ ruff --version
Segmentation fault: 11
```

OS: macOS 11.7.10
python: 3.8.9 in virtual env

**Comment by qarmin** [comment]
Can you run it under gdb?
```
gdb ruff
run --version
```

**Comment by MichaReiser** [comment]
@jetli, what shell are you using? Is it ZSH? https://github.com/astral-sh/ruff/discussions/9824

**Comment by charliermarsh** [comment]
How strange. Does running with `--no-cache` change anything? (I assume not, but worth a try.)

**Comment by jetli** [comment]
not zsh, just bash.  it crashes even with no options.
```
$ ruff
Segmentation fault: 11
```

**Comment by charliermarsh** [comment]
Do you know what version of macOS you’re on? Perhaps this is related to our upgrade to use the Apple Silicon runners.

**Comment by charliermarsh** [comment]
Oh sorry, you said macOS 11 above. I’m guessing there’s something incompatible there.

**Comment by zanieb** [comment]
Could you share the output of the `uname -a` command?

**Comment by Gankra** [comment]
I can reproduce this on my old EOL macbook (macos 11 has been eol for 4 months, but i think this issue can plausibly manifest on 12/13).

The crash stack includes lots of things like `ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)` which is a pretty clear sign the crash is during the dynamic linking of the executable on load. This is *probably* a symptom of binaries compiled against the macos 14 sdk (the default for github's new apple silicon runners) being run on an older OS.

**Comment by charliermarsh** [comment]
@Gankra - Do you think this is an issue for ARM macbooks on macos 11, 12, 13? Or just x86? Or can't say at this point?

**Comment by Gankra** [comment]
I would expect the issue to happen equally on both platforms, with OS version being the primary issue -- but that's purely a guess, and the only thing I can think to do is to find people with macbooks running those versions to try (I guess you could write some github CI jobs to spawn some of those OSes and try to run the binary?).

I can send you the full crash log but it doesn't obviously indicate what symbol was trying to be loaded.

**Comment by charliermarsh** [comment]
@Gankra - FYI, it looks like these binaries work okay on macOS 12 and macOS 13: https://github.com/astral-sh/ruff/pull/9835

**Comment by charliermarsh** [comment]
Now I'm more tempted _not_ to change this given that macOS 11 is EOL :(
