### ISSUE TITLE
Support formatting using line ranges

### ISSUE THREAD

**Issue by jvacek** [astral-sh/ruff#9831]
Black added support for formatting line-ranges https://github.com/psf/black/pull/4020

Would be nice if this was possible within ruff's formatter. The Black VSCode extension also has support for this now, and allows code to be formatted "on modification" https://github.com/microsoft/vscode-black-formatter/pull/380

**Comment by MichaReiser** [comment]
Hy @jvacek Good news. This should be supported in the next ruff release https://github.com/astral-sh/ruff/pull/9733
