### ISSUE TITLE
NPY002 legacy np.random.{method_name} call not triggering on `np.random.random()`

### ISSUE THREAD

**Issue by jack-mcivor** [astral-sh/ruff#9861]
Using ruff v0.2.1

```python
import numpy as np

np.random.random()
```

```bash
$ ruff check --isolated --select=NPY002 tmp.py
```

I expect this to trigger a violation - afaict np.random.random() is deprecated just like any other np.random.{method_name} call. Reference https://numpy.org/doc/stable/reference/random/legacy.html#functions-in-numpy-random

I'm not quite sure why it was left out of https://github.com/astral-sh/ruff/pull/2960

**Comment by jack-mcivor** [comment]
I will try take

**Comment by charliermarsh** [comment]
Looks like an oversight.
