### ISSUE TITLE
The `show-source` deprecation warning should have a clearer call to action

### ISSUE THREAD

**Issue by zanieb** [astral-sh/ruff#9876]
"Please update your configuration" should be more specific. 

Raised in https://github.com/astral-sh/ruff/pull/9874

**Comment by AbhinavMir** [comment]
Hi @zanieb - love Ruff, would love to contribute.

What's a good replacement? 

Current message: `show-source` is deprecated and is now part of `output-format` in the form of `full` or `concise` options. Please update your configuration.

Modified message: `show-source` is deprecated and is now part of `output-format` in the form of `full` or `concise` options. Please update your configuration by replacing `show-source` with either `output-format = full` or `output-format = concise` in your configuration file. `full`  would show you the source code snippets and `concise` would not. Other possible values can be viewed at [https://docs.astral.sh/ruff/settings/#output-format](`show-source` is deprecated and is now part of `output-format` in the form of `full` or `concise` options. Please update your configuration by replacing `show-source` with either `output-format = full` or `output-format = concise` in your configuration file. `full`  would show you the source code snippets and `concise` would not. Other possible values can be viewed at https://docs.astral.sh/ruff/settings/#output-format").

**Comment by zanieb** [comment]
Hey @AbhinavMir! Love to hear that :)

I don't think we need to be quite so verbose. I haven't given the exact message a lot of thought but here are some ideas. This is a bit more work, but we should actually be able to _tell_ which value they're using so if they use `show-source=true` we can say 

> The `show-source` option has been deprecated. Use `output-format=full` instead.

and for `show-source=false` we can say

> The `show-source` option has been deprecated. Use `output-format=text` instead.

We may also be able to tell if this was provided via the CLI or a configuration file. If so, we can make even better suggestions e.g.

> The `show-source` option has been deprecated. Update your configuration file to use `output-format = text` instead.

and

> The `--show-source` option has been deprecated. Use `--output-format=full` instead.

**Comment by AbhinavMir** [comment]
Gotcha, I can probably prod into the code a bit more tomorrow, but it'd be great if you could point out where the options are being read from. The idea, I assume is, read the flags, show the correct output - but just wondering how this is architectured in the code base.

**Comment by dylwil3** [comment]
Should this issue be closed in light of #9814, which removes `show-source` as an option (along with its deprecation warning)?

**Comment by zanieb** [comment]
Thanks!
