### ISSUE TITLE
`D413` is enforcing excessive whitespace

### ISSUE THREAD

**Issue by BrentWilkins** [astral-sh/ruff#9877]
It seems that the change in [this PR](https://github.com/astral-sh/ruff/pull/9654) is exposing a bug in the `D413`. Ruff is calling this docstring bad:

```python
"""Make a summary line.

Note:
----
  Per the code comment the next two lines are blank. "// The first blank line is the line containing the closing
      triple quotes, so we need at least two."

"""
```

> Missing blank line after last section ("Note") Ruff([D413](https://docs.astral.sh/ruff/rules/blank-line-after-last-section))

I can't see what's different between what I have and the `Use instead:` section of [the documentation](https://docs.astral.sh/ruff/rules/blank-line-after-last-section/).

I can make Ruff happy by adding excessive blank lines:

```python
"""Make a summary line.

Note:
----
  Per the code comment the next two lines are blank. "// The first blank line is the line containing the closing
      triple quotes, so we need at least two."


"""
```

**Comment by charliermarsh** [comment]
Thanks!
