### ISSUE TITLE
Allow TODO Link for TD003 to be included in same line

### ISSUE THREAD

**Issue by severus-sn4pe** [astral-sh/ruff#9986]
TD003 checks that a TODO comment is associated with a link to a relevant issue or ticket.
It requires the link or issue code to be on the line **after** the comment:

```
# TODO: Add parameters
# ISSUE-123
```

Problem: having the link/issue code inline the TODO comment, reports a TD003 error:
```
# TODO: ISSUE-123 Add parameters
```

flake8-todos (from which TD003 is derived) supports this. 
It would be great, if inline-links within the TODO could be allowed. 

Some tools, like IntelliJ IDEA can track open TODO's in a project and having the link/issue-code on the same line allows easier locating a specific todo.

**Comment by dhruvmanila** [comment]
Thanks! This should be fixed by https://github.com/astral-sh/ruff/pull/9627

Merging this with https://github.com/astral-sh/ruff/issues/8061
