### ISSUE TITLE
Import sorting is breaking file

### ISSUE THREAD

**Issue by theelderbeever** [astral-sh/ruff#9991]
I am using the vscode sort on save setting and the following happens when I save the file. Variations of this happen on multiple files to the point of affecting code as well.

Before:
<img width="711" alt="image" src="https://github.com/astral-sh/ruff/assets/29295582/47c0ae11-8741-4442-8fcc-eaa29a8d4e73">

After:
<img width="654" alt="image" src="https://github.com/astral-sh/ruff/assets/29295582/f747520d-3893-49d6-9c84-9bfdae2a69ad">

**Comment by theelderbeever** [comment]
I think it has something to do with trailing commas in tuples

**Comment by zanieb** [comment]
Thanks for the report!

If you have time could you provide a minimal example (as text rather than a screenshot) that reproduces the problem? It'd be helpful to narrow down what exactly causes the problem.

**Comment by charliermarsh** [comment]
Do you have the isort extension enabled? To me, this looks a lot like https://github.com/astral-sh/ruff-vscode/issues/128 which unfortunately is actually a VS Code bug (https://github.com/microsoft/vscode/issues/174295). Can you try disabling the isort extension?

**Comment by theelderbeever** [comment]
@charliermarsh I had wondered if `isort` was implicated in this but, forgot that there was a dedicated extension for it. Just turned it off. The issue is weirdly intermittent so I won't know if it fixes the problem for a bit. I think we can close for now and I can just reopen with better examples for @zanieb if it recurs.
